package ct.dna.lakehouse.sr_raw.ct_gbl_p12
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class bsak_E(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  bukrs_string: String,
  maber_string: String,
  augbl_string: String,
  zterm_string: String,
  egrup_string: String,
  rstgr_string: String,
  @Decimal(3, 0) zbd1t_decimal_3_0: BigDecimal,
  @Decimal(13, 2) penlc2_decimal_13_2: BigDecimal,
  lzbkz_string: String,
  rebzt_string: String,
  fkber_string: String,
  cpudt_string: String,
  lnran_string: String,
  @Decimal(13, 2) skfbt_decimal_13_2: BigDecimal,
  zfbdt_string: String,
  saknr_string: String,
  xarch_string: String,
  belnr_string: String,
  mwsk1_string: String,
  vertn_string: String,
  pendays_int: BoxedInt,
  filkd_string: String,
  prctr_string: String,
  @Decimal(13, 2) dmb33_decimal_13_2: BigDecimal,
  dtws1_string: String,
  kontt_string: String,
  zbfix_string: String,
  kontl_string: String,
  kblnr_string: String,
  zlsch_string: String,
  mschl_string: String,
  @Decimal(13, 2) mwst3_decimal_13_2: BigDecimal,
  xegdr_string: String,
  xblnr_string: String,
  @Decimal(13, 2) dmbtr_decimal_13_2: BigDecimal,
  @Decimal(13, 2) dmb32_decimal_13_2: BigDecimal,
  @Decimal(13, 2) dmbt1_decimal_13_2: BigDecimal,
  @Decimal(3, 0) zbd2t_decimal_3_0: BigDecimal,
  fkont_string: String,
  @Decimal(13, 2) dmbe3_decimal_13_2: BigDecimal,
  @Decimal(13, 2) dmbt3_decimal_13_2: BigDecimal,
  samnr_string: String,
  aufnr_string: String,
  bstat_string: String,
  buzei_string: String,
  @Decimal(13, 2) bdif3_decimal_13_2: BigDecimal,
  @Decimal(13, 2) wrbt3_decimal_13_2: BigDecimal,
  egbld_string: String,
  qsznr_string: String,
  @Decimal(13, 2) dmbe2_decimal_13_2: BigDecimal,
  ebeln_string: String,
  mwsk2_string: String,
  nplnr_string: String,
  diekz_string: String,
  sgtxt_string: String,
  xstov_string: String,
  uzawe_string: String,
  propmano_string: String,
  kidno_string: String,
  secco_string: String,
  imkey_string: String,
  @Decimal(5, 3) zbd1p_decimal_5_3: BigDecimal,
  projk_string: String,
  @Decimal(13, 2) wrbtr_decimal_13_2: BigDecimal,
  vbewa_string: String,
  stceg_string: String,
  pycur_string: String,
  anln1_string: String,
  aplzl_string: String,
  qsskz_string: String,
  inwardno_hd_string: String,
  @Decimal(13, 2) dmb21_decimal_13_2: BigDecimal,
  xref3_string: String,
  @Decimal(13, 2) bdif2_decimal_13_2: BigDecimal,
  geber_string: String,
  @Decimal(13, 2) kzbtr_decimal_13_2: BigDecimal,
  intreno_string: String,
  ebelp_string: String,
  rebzj_string: String,
  @Decimal(13, 2) sknto_decimal_13_2: BigDecimal,
  xcpdd_string: String,
  anfbj_string: String,
  dtws3_string: String,
  @Decimal(13, 2) wmwst_decimal_13_2: BigDecimal,
  @Decimal(13, 2) mwsts_decimal_13_2: BigDecimal,
  mandt_string: String,
  mansp_string: String,
  xragl_string: String,
  @Decimal(13, 2) ppdif3_decimal_13_2: BigDecimal,
  hkont_string: String,
  empfb_string: String,
  zinkz_string: String,
  vname_string: String,
  @Decimal(13, 2) qsshb_decimal_13_2: BigDecimal,
  vbund_string: String,
  @Decimal(13, 2) pswbt_decimal_13_2: BigDecimal,
  blart_string: String,
  @Decimal(13, 2) penfc_decimal_13_2: BigDecimal,
  @Decimal(3, 0) zbd3t_decimal_3_0: BigDecimal,
  btype_string: String,
  hktid_string: String,
  xanet_string: String,
  @Decimal(13, 2) penlc3_decimal_13_2: BigDecimal,
  xref2_string: String,
  kblpos_string: String,
  aufpl_string: String,
  projn_string: String,
  @Decimal(13, 2) ppdif2_decimal_13_2: BigDecimal,
  @Decimal(13, 2) wskto_decimal_13_2: BigDecimal,
  madat_string: String,
  zolld_string: String,
  umskz_string: String,
  @Decimal(13, 2) qbshb_decimal_13_2: BigDecimal,
  @Decimal(13, 2) sknt2_decimal_13_2: BigDecimal,
  xref1_string: String,
  @Decimal(13, 2) qsfbt_decimal_13_2: BigDecimal,
  zollt_string: String,
  gjahr_string: String,
  buzid_string: String,
  @Decimal(13, 2) dmbt2_decimal_13_2: BigDecimal,
  xnetb_string: String,
  eglld_string: String,
  anln2_string: String,
  mwskz_string: String,
  landl_string: String,
  vertt_string: String,
  @Decimal(13, 2) pyamt_decimal_13_2: BigDecimal,
  @Decimal(13, 2) sknt3_decimal_13_2: BigDecimal,
  augdt_string: String,
  budget_pd_string: String,
  bschl_string: String,
  bvtyp_string: String,
  @Decimal(5, 3) zbd2p_decimal_5_3: BigDecimal,
  lotkz_string: String,
  pswsl_string: String,
  xpypr_string: String,
  fipos_string: String,
  uebgdat_string: String,
  xinve_string: String,
  anfbu_string: String,
  xnegp_string: String,
  @Decimal(13, 2) dmb31_decimal_13_2: BigDecimal,
  dtws4_string: String,
  xzahl_string: String,
  @Decimal(13, 2) wrbt2_decimal_13_2: BigDecimal,
  penrc_string: String,
  rebzz_string: String,
  auggj_string: String,
  monat_string: String,
  @Decimal(13, 2) bdiff_decimal_13_2: BigDecimal,
  zlspr_string: String,
  umsks_string: String,
  lifnr_string: String,
  @Decimal(13, 2) mwst2_decimal_13_2: BigDecimal,
  srtype_string: String,
  mwsk3_string: String,
  xesrd_string: String,
  dabrz_string: String,
  hbkid_string: String,
  rebzg_string: String,
  @Decimal(13, 2) ppdiff_decimal_13_2: BigDecimal,
  shkzg_string: String,
  anfbn_string: String,
  zuonr_string: String,
  zumsk_string: String,
  bldat_string: String,
  gsber_string: String,
  @Decimal(13, 2) dmb23_decimal_13_2: BigDecimal,
  dtws2_string: String,
  budat_string: String,
  grant_nbr_string: String,
  kostl_string: String,
  fistl_string: String,
  waers_string: String,
  zekkn_string: String,
  @Decimal(13, 2) dmb22_decimal_13_2: BigDecimal,
  @Decimal(13, 2) wrbt1_decimal_13_2: BigDecimal,
  pprct_string: String,
  @Decimal(13, 2) penlc1_decimal_13_2: BigDecimal,
  gmvkz_string: String,
  bupla_string: String,
  manst_string: String,
  inwarddt_hd_string: String
) extends Entity

object bsak extends TableSpec[bsak_E](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
