// LOADED TABLE SPEC AUTO GENERATED:START
// Generated by LoadedTableSpecAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr_raw.ct_gbl_p12

import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.Loaded
import ct.dna.lakehouse.core.model.TableSpec

case class E_ckmlpp(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt_string: String,
    kalnr_string: String,
    bdatj_string: String,
    poper_string: String,
    untper_string: String,
    kz_abger_string: String,
    xkonchk_string: String,
    status_string: String,
    meins_string: String,
    saprl_string: String,
    xerror_string: String,
    cd_ok_string: String,
    xnewccsnextmon_string: String,
    xmymp_string: String,
    @Decimal(15, 3) lbkum_decimal_15_3: BigDecimal,
    @Decimal(15, 3) umkumo_decimal_15_3: BigDecimal,
    @Decimal(15, 3) abkumo_decimal_15_3: BigDecimal,
    @Decimal(15, 3) zukumo_decimal_15_3: BigDecimal,
    @Decimal(15, 3) szkumo_decimal_15_3: BigDecimal,
    @Decimal(15, 3) vpkumo_decimal_15_3: BigDecimal,
    @Decimal(15, 3) vnkumo_decimal_15_3: BigDecimal,
    @Decimal(15, 3) ekkumo_decimal_15_3: BigDecimal,
    @Decimal(15, 3) pbkumo_decimal_15_3: BigDecimal,
    @Decimal(15, 3) pbpopo_decimal_15_3: BigDecimal,
    @Decimal(15, 3) vppopo_decimal_15_3: BigDecimal,
    @Decimal(15, 3) umkuma_decimal_15_3: BigDecimal,
    @Decimal(15, 3) zukuma_decimal_15_3: BigDecimal,
    @Decimal(15, 3) ekkuma_decimal_15_3: BigDecimal,
    @Decimal(15, 3) pbkuma_decimal_15_3: BigDecimal,
    xvnb_string: String,
    xwip_string: String,
    xobjwip_string: String,
    xnopl_string: String,
    xmstuf_string: String,
    xckmm_string: String,
    xclean_string: String,
    xavrsim_string: String
) extends Entity

object ckmlpp
    extends TableSpec[E_ckmlpp](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.Columns("_mk_instance", "_mk_partition", "_mk_file"),
      timetravelDays = 35
    )
    with Loaded
// LOADED TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_ckmlpp(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val mandt_string: ColumnWithName = ColumnWithName(prefix + "mandt_string")
  val kalnr_string: ColumnWithName = ColumnWithName(prefix + "kalnr_string")
  val bdatj_string: ColumnWithName = ColumnWithName(prefix + "bdatj_string")
  val poper_string: ColumnWithName = ColumnWithName(prefix + "poper_string")
  val untper_string: ColumnWithName = ColumnWithName(prefix + "untper_string")
  val kz_abger_string: ColumnWithName = ColumnWithName(prefix + "kz_abger_string")
  val xkonchk_string: ColumnWithName = ColumnWithName(prefix + "xkonchk_string")
  val status_string: ColumnWithName = ColumnWithName(prefix + "status_string")
  val meins_string: ColumnWithName = ColumnWithName(prefix + "meins_string")
  val saprl_string: ColumnWithName = ColumnWithName(prefix + "saprl_string")
  val xerror_string: ColumnWithName = ColumnWithName(prefix + "xerror_string")
  val cd_ok_string: ColumnWithName = ColumnWithName(prefix + "cd_ok_string")
  val xnewccsnextmon_string: ColumnWithName = ColumnWithName(prefix + "xnewccsnextmon_string")
  val xmymp_string: ColumnWithName = ColumnWithName(prefix + "xmymp_string")
  val lbkum_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "lbkum_decimal_15_3")
  val umkumo_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "umkumo_decimal_15_3")
  val abkumo_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "abkumo_decimal_15_3")
  val zukumo_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "zukumo_decimal_15_3")
  val szkumo_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "szkumo_decimal_15_3")
  val vpkumo_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "vpkumo_decimal_15_3")
  val vnkumo_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "vnkumo_decimal_15_3")
  val ekkumo_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "ekkumo_decimal_15_3")
  val pbkumo_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "pbkumo_decimal_15_3")
  val pbpopo_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "pbpopo_decimal_15_3")
  val vppopo_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "vppopo_decimal_15_3")
  val umkuma_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "umkuma_decimal_15_3")
  val zukuma_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "zukuma_decimal_15_3")
  val ekkuma_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "ekkuma_decimal_15_3")
  val pbkuma_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "pbkuma_decimal_15_3")
  val xvnb_string: ColumnWithName = ColumnWithName(prefix + "xvnb_string")
  val xwip_string: ColumnWithName = ColumnWithName(prefix + "xwip_string")
  val xobjwip_string: ColumnWithName = ColumnWithName(prefix + "xobjwip_string")
  val xnopl_string: ColumnWithName = ColumnWithName(prefix + "xnopl_string")
  val xmstuf_string: ColumnWithName = ColumnWithName(prefix + "xmstuf_string")
  val xckmm_string: ColumnWithName = ColumnWithName(prefix + "xckmm_string")
  val xclean_string: ColumnWithName = ColumnWithName(prefix + "xclean_string")
  val xavrsim_string: ColumnWithName = ColumnWithName(prefix + "xavrsim_string")
}

object C_ckmlpp extends C_ckmlpp("") {
  def as(alias: String): C_ckmlpp = new C_ckmlpp(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
