// LOADED TABLE SPEC AUTO GENERATED:START
// Generated by LoadedTableSpecAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr_raw.ct_gbl_p12

import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.Loaded
import ct.dna.lakehouse.core.model.TableSpec

case class E_qmat(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt_string: String,
    art_string: String,
    matnr_string: String,
    werks_string: String,
    ppl_string: String,
    spezueber_string: String,
    conf_string: String,
    tls_string: String,
    app_string: String,
    mer_string: String,
    insmk_string: String,
    ave_string: String,
    stichprver_string: String,
    dynregel_string: String,
    @Decimal(3, 0) sproz_decimal_3_0: BigDecimal,
    hpz_string: String,
    dyn_string: String,
    mpb_string: String,
    mst_string: String,
    ein_string: String,
    @Decimal(3, 0) mpdau_decimal_3_0: BigDecimal,
    chg_string: String,
    qkzverf_string: String,
    @Decimal(6, 4) qpmat_decimal_6_4: BigDecimal,
    kzprfkost_string: String,
    aufnr_co_string: String,
    aktiv_string: String,
    apa_string: String,
    afr_string: String,
    mma_string: String,
    feh_string: String,
    @Decimal(3, 0) prfrq_decimal_3_0: BigDecimal,
    nkmpr_string: String,
    ms_flag_string: String
) extends Entity

object qmat
    extends TableSpec[E_qmat](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.Columns("_mk_instance", "_mk_partition", "_mk_file"),
      timetravelDays = 35
    )
    with Loaded
// LOADED TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_qmat(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val mandt_string: ColumnWithName = ColumnWithName(prefix + "mandt_string")
  val art_string: ColumnWithName = ColumnWithName(prefix + "art_string")
  val matnr_string: ColumnWithName = ColumnWithName(prefix + "matnr_string")
  val werks_string: ColumnWithName = ColumnWithName(prefix + "werks_string")
  val ppl_string: ColumnWithName = ColumnWithName(prefix + "ppl_string")
  val spezueber_string: ColumnWithName = ColumnWithName(prefix + "spezueber_string")
  val conf_string: ColumnWithName = ColumnWithName(prefix + "conf_string")
  val tls_string: ColumnWithName = ColumnWithName(prefix + "tls_string")
  val app_string: ColumnWithName = ColumnWithName(prefix + "app_string")
  val mer_string: ColumnWithName = ColumnWithName(prefix + "mer_string")
  val insmk_string: ColumnWithName = ColumnWithName(prefix + "insmk_string")
  val ave_string: ColumnWithName = ColumnWithName(prefix + "ave_string")
  val stichprver_string: ColumnWithName = ColumnWithName(prefix + "stichprver_string")
  val dynregel_string: ColumnWithName = ColumnWithName(prefix + "dynregel_string")
  val sproz_decimal_3_0: ColumnWithName = ColumnWithName(prefix + "sproz_decimal_3_0")
  val hpz_string: ColumnWithName = ColumnWithName(prefix + "hpz_string")
  val dyn_string: ColumnWithName = ColumnWithName(prefix + "dyn_string")
  val mpb_string: ColumnWithName = ColumnWithName(prefix + "mpb_string")
  val mst_string: ColumnWithName = ColumnWithName(prefix + "mst_string")
  val ein_string: ColumnWithName = ColumnWithName(prefix + "ein_string")
  val mpdau_decimal_3_0: ColumnWithName = ColumnWithName(prefix + "mpdau_decimal_3_0")
  val chg_string: ColumnWithName = ColumnWithName(prefix + "chg_string")
  val qkzverf_string: ColumnWithName = ColumnWithName(prefix + "qkzverf_string")
  val qpmat_decimal_6_4: ColumnWithName = ColumnWithName(prefix + "qpmat_decimal_6_4")
  val kzprfkost_string: ColumnWithName = ColumnWithName(prefix + "kzprfkost_string")
  val aufnr_co_string: ColumnWithName = ColumnWithName(prefix + "aufnr_co_string")
  val aktiv_string: ColumnWithName = ColumnWithName(prefix + "aktiv_string")
  val apa_string: ColumnWithName = ColumnWithName(prefix + "apa_string")
  val afr_string: ColumnWithName = ColumnWithName(prefix + "afr_string")
  val mma_string: ColumnWithName = ColumnWithName(prefix + "mma_string")
  val feh_string: ColumnWithName = ColumnWithName(prefix + "feh_string")
  val prfrq_decimal_3_0: ColumnWithName = ColumnWithName(prefix + "prfrq_decimal_3_0")
  val nkmpr_string: ColumnWithName = ColumnWithName(prefix + "nkmpr_string")
  val ms_flag_string: ColumnWithName = ColumnWithName(prefix + "ms_flag_string")
}

object C_qmat extends C_qmat("") {
  def as(alias: String): C_qmat = new C_qmat(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
