// LOADED TABLE SPEC AUTO GENERATED:START
// Generated by LoadedTableSpecAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr_raw.ct_gbl_p12

import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.Loaded
import ct.dna.lakehouse.core.model.TableSpec

case class E_ska1(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt_string: String,
    ktopl_string: String,
    saknr_string: String,
    xbilk_string: String,
    sakan_string: String,
    bilkt_string: String,
    erdat_string: String,
    ernam_string: String,
    gvtyp_string: String,
    ktoks_string: String,
    mustr_string: String,
    vbund_string: String,
    xloev_string: String,
    xspea_string: String,
    xspeb_string: String,
    xspep_string: String,
    mcod1_string: String,
    func_area_string: String,
    zzct_goa_string: String
) extends Entity

object ska1
    extends TableSpec[E_ska1](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.Columns("_mk_instance", "_mk_partition", "_mk_file"),
      timetravelDays = 35
    )
    with Loaded
// LOADED TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_ska1(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val mandt_string: ColumnWithName = ColumnWithName(prefix + "mandt_string")
  val ktopl_string: ColumnWithName = ColumnWithName(prefix + "ktopl_string")
  val saknr_string: ColumnWithName = ColumnWithName(prefix + "saknr_string")
  val xbilk_string: ColumnWithName = ColumnWithName(prefix + "xbilk_string")
  val sakan_string: ColumnWithName = ColumnWithName(prefix + "sakan_string")
  val bilkt_string: ColumnWithName = ColumnWithName(prefix + "bilkt_string")
  val erdat_string: ColumnWithName = ColumnWithName(prefix + "erdat_string")
  val ernam_string: ColumnWithName = ColumnWithName(prefix + "ernam_string")
  val gvtyp_string: ColumnWithName = ColumnWithName(prefix + "gvtyp_string")
  val ktoks_string: ColumnWithName = ColumnWithName(prefix + "ktoks_string")
  val mustr_string: ColumnWithName = ColumnWithName(prefix + "mustr_string")
  val vbund_string: ColumnWithName = ColumnWithName(prefix + "vbund_string")
  val xloev_string: ColumnWithName = ColumnWithName(prefix + "xloev_string")
  val xspea_string: ColumnWithName = ColumnWithName(prefix + "xspea_string")
  val xspeb_string: ColumnWithName = ColumnWithName(prefix + "xspeb_string")
  val xspep_string: ColumnWithName = ColumnWithName(prefix + "xspep_string")
  val mcod1_string: ColumnWithName = ColumnWithName(prefix + "mcod1_string")
  val func_area_string: ColumnWithName = ColumnWithName(prefix + "func_area_string")
  val zzct_goa_string: ColumnWithName = ColumnWithName(prefix + "zzct_goa_string")
}

object C_ska1 extends C_ska1("") {
  def as(alias: String): C_ska1 = new C_ska1(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
