// LOADED TABLE SPEC AUTO GENERATED:START
// Generated by LoadedTableSpecAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr_raw.ct_gbl_p12

import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.Loaded
import ct.dna.lakehouse.core.model.TableSpec

case class E_stxh(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt_string: String,
    tdobject_string: String,
    tdname_string: String,
    tdid_string: String,
    tdspras_string: String,
    tdtitle_string: String,
    tdfreles_string: String,
    tdfuser_string: String,
    tdfdate_string: String,
    tdftime_string: String,
    tdlreles_string: String,
    tdluser_string: String,
    tdldate_string: String,
    tdltime_string: String,
    tdversion_string: String,
    tdstyle_string: String,
    tdform_string: String,
    tdhyphenat_string: String,
    tdtranstat_string: String,
    tdospras_string: String,
    tdmacode1_string: String,
    tdmacode2_string: String,
    tdtxtlines_string: String,
    tdref_string: String,
    tdrefobj_string: String,
    tdrefname_string: String,
    tdrefid_string: String,
    tdtexttype_string: String,
    tdcompress_string: String,
    tdoclass_string: String,
    logsys_string: String
) extends Entity

object stxh
    extends TableSpec[E_stxh](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.Columns("_mk_instance", "_mk_partition", "_mk_file"),
      timetravelDays = 35
    )
    with Loaded
// LOADED TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_stxh(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val mandt_string: ColumnWithName = ColumnWithName(prefix + "mandt_string")
  val tdobject_string: ColumnWithName = ColumnWithName(prefix + "tdobject_string")
  val tdname_string: ColumnWithName = ColumnWithName(prefix + "tdname_string")
  val tdid_string: ColumnWithName = ColumnWithName(prefix + "tdid_string")
  val tdspras_string: ColumnWithName = ColumnWithName(prefix + "tdspras_string")
  val tdtitle_string: ColumnWithName = ColumnWithName(prefix + "tdtitle_string")
  val tdfreles_string: ColumnWithName = ColumnWithName(prefix + "tdfreles_string")
  val tdfuser_string: ColumnWithName = ColumnWithName(prefix + "tdfuser_string")
  val tdfdate_string: ColumnWithName = ColumnWithName(prefix + "tdfdate_string")
  val tdftime_string: ColumnWithName = ColumnWithName(prefix + "tdftime_string")
  val tdlreles_string: ColumnWithName = ColumnWithName(prefix + "tdlreles_string")
  val tdluser_string: ColumnWithName = ColumnWithName(prefix + "tdluser_string")
  val tdldate_string: ColumnWithName = ColumnWithName(prefix + "tdldate_string")
  val tdltime_string: ColumnWithName = ColumnWithName(prefix + "tdltime_string")
  val tdversion_string: ColumnWithName = ColumnWithName(prefix + "tdversion_string")
  val tdstyle_string: ColumnWithName = ColumnWithName(prefix + "tdstyle_string")
  val tdform_string: ColumnWithName = ColumnWithName(prefix + "tdform_string")
  val tdhyphenat_string: ColumnWithName = ColumnWithName(prefix + "tdhyphenat_string")
  val tdtranstat_string: ColumnWithName = ColumnWithName(prefix + "tdtranstat_string")
  val tdospras_string: ColumnWithName = ColumnWithName(prefix + "tdospras_string")
  val tdmacode1_string: ColumnWithName = ColumnWithName(prefix + "tdmacode1_string")
  val tdmacode2_string: ColumnWithName = ColumnWithName(prefix + "tdmacode2_string")
  val tdtxtlines_string: ColumnWithName = ColumnWithName(prefix + "tdtxtlines_string")
  val tdref_string: ColumnWithName = ColumnWithName(prefix + "tdref_string")
  val tdrefobj_string: ColumnWithName = ColumnWithName(prefix + "tdrefobj_string")
  val tdrefname_string: ColumnWithName = ColumnWithName(prefix + "tdrefname_string")
  val tdrefid_string: ColumnWithName = ColumnWithName(prefix + "tdrefid_string")
  val tdtexttype_string: ColumnWithName = ColumnWithName(prefix + "tdtexttype_string")
  val tdcompress_string: ColumnWithName = ColumnWithName(prefix + "tdcompress_string")
  val tdoclass_string: ColumnWithName = ColumnWithName(prefix + "tdoclass_string")
  val logsys_string: ColumnWithName = ColumnWithName(prefix + "logsys_string")
}

object C_stxh extends C_stxh("") {
  def as(alias: String): C_stxh = new C_stxh(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
