package ct.dna.lakehouse.sr_raw.ct_gbl_p12
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class vbrp_E(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  fsh_season_string: String,
  paobjnr_string: String,
  kvgr1_string: String,
  aubel_string: String,
  vgpos_ex_string: String,
  kowrr_string: String,
  delco_string: String,
  matnr_string: String,
  kvgr2_string: String,
  edatu_string: String,
  prsfd_string: String,
  fkber_string: String,
  abrvw_string: String,
  @Decimal(15, 2) netwr_decimal_15_2: BigDecimal,
  kdkg1_string: String,
  fsh_season_year_string: String,
  dp_gjahr_string: String,
  claims_taxation_string: String,
  kvgr4_string: String,
  erzet_string: String,
  sgt_scat_string: String,
  aplzl_oaa_string: String,
  j_1btaxlw2_string: String,
  perop_end_string: String,
  spara_string: String,
  dpcnr_string: String,
  atpkz_string: String,
  @Decimal(9, 5) kursk_decimal_9_5: BigDecimal,
  taxm5_string: String,
  ernam_string: String,
  msr_id_string: String,
  prctr_string: String,
  contnbr_string: String,
  pargb_string: String,
  vertn_string: String,
  dp_buzei_string: String,
  vkbur_string: String,
  j_3gpmaufv_string: String,
  @Decimal(13, 2) kzwi6_decimal_13_2: BigDecimal,
  contitm_string: String,
  provg_string: String,
  mprok_string: String,
  mvgr2_string: String,
  autyp_string: String,
  augru_auft_string: String,
  @Decimal(13, 2) kzwi5_decimal_13_2: BigDecimal,
  dp_bukrs_string: String,
  pprctr_string: String,
  @Decimal(13, 2) wavwr_decimal_13_2: BigDecimal,
  uvall_string: String,
  sgt_rcat_string: String,
  vstel_string: String,
  vgtyp_ex_string: String,
  knuma_ag_string: String,
  uepos_string: String,
  bemot_string: String,
  fpltr_string: String,
  j_1btaxlw1_string: String,
  aufnr_string: String,
  @Decimal(15, 3) ntgew_decimal_15_3: BigDecimal,
  pospa_string: String,
  packno_string: String,
  @Decimal(13, 2) mwsbp_decimal_13_2: BigDecimal,
  @Decimal(9, 5) stcur_decimal_9_5: BigDecimal,
  bosfar_string: String,
  lland_auft_string: String,
  j_3getypa_string: String,
  arktx_string: String,
  taxm2_string: String,
  sgtxt_string: String,
  mvgr3_string: String,
  audat_string: String,
  regio_auft_string: String,
  vgtyp_string: String,
  taxm9_string: String,
  @Decimal(13, 2) kzwi1_decimal_13_2: BigDecimal,
  @Decimal(15, 2) brtwr_decimal_15_2: BigDecimal,
  taxm7_string: String,
  @Decimal(9, 5) akkur_decimal_9_5: BigDecimal,
  kokrs_string: String,
  j_1btxsdc_string: String,
  j_1atxrel_string: String,
  aplzl_string: String,
  vbeln_string: String,
  vgtyp_ext_string: String,
  kurrf_dat_orig_string: String,
  abrbg_string: String,
  upmat_string: String,
  gewei_string: String,
  vgbel_ex_string: String,
  j_1aidatep_string: String,
  aland_string: String,
  charg_string: String,
  compreas_string: String,
  j_1btaxlw5_string: String,
  aupos_string: String,
  bzirk_auft_string: String,
  prodh_string: String,
  @Decimal(15, 3) brgew_decimal_15_3: BigDecimal,
  pmatn_string: String,
  abfor_string: String,
  vkorg_auft_string: String,
  prosa_string: String,
  lgort_string: String,
  j_1aindxp_string: String,
  kdgrp_auft_string: String,
  @Decimal(13, 2) kzwi3_decimal_13_2: BigDecimal,
  @Decimal(5, 0) umvkn_decimal_5_0: BigDecimal,
  fund_usage_item_binary: Array[Byte],
  taxm6_string: String,
  mvgr5_string: String,
  posnv_string: String,
  posar_string: String,
  werks_string: String,
  j_3gpmaufe_string: String,
  logsys_string: String,
  fonds_string: String,
  sktof_string: String,
  taxm1_string: String,
  cuobj_string: String,
  kvgr3_string: String,
  kursk_dat_string: String,
  mandt_string: String,
  taxm8_string: String,
  kondm_string: String,
  @Decimal(15, 3) volum_decimal_15_3: BigDecimal,
  vtweg_auft_string: String,
  prefe_string: String,
  eannr_string: String,
  kdkg3_string: String,
  rrrel_string: String,
  fplnr_string: String,
  j_1aregio_string: String,
  plaufz_string: String,
  stafo_string: String,
  bonus_string: String,
  wkcty_string: String,
  konda_auft_string: String,
  dpnrb_string: String,
  voleh_string: String,
  txjcd_string: String,
  vkaus_string: String,
  @Decimal(13, 3) smeng_decimal_13_3: BigDecimal,
  fareg_string: String,
  rplnr_string: String,
  wrf_charstc3_string: String,
  aufpl_string: String,
  perop_beg_string: String,
  uepvw_string: String,
  msr_refund_code_string: String,
  kzfme_string: String,
  fsh_theme_string: String,
  meins_string: String,
  kdkg4_string: String,
  farr_reltype_string: String,
  j_1agicd_string: String,
  msr_ret_reason_string: String,
  mvgr4_string: String,
  @Decimal(13, 3) fkimg_decimal_13_3: BigDecimal,
  wgru1_string: String,
  fbuda_string: String,
  j_1btaxlw4_string: String,
  nrab_knumh_string: String,
  koupd_string: String,
  plauez_string: String,
  @Decimal(13, 2) kzwi4_decimal_13_2: BigDecimal,
  @Decimal(13, 2) kzwi2_decimal_13_2: BigDecimal,
  spart_string: String,
  mwskz_string: String,
  vertt_string: String,
  cuobj_ch_string: String,
  @Decimal(11, 2) cmpre_decimal_11_2: BigDecimal,
  j_1adtyp_string: String,
  zzfiresgnup_string: String,
  j_3gbelnri_string: String,
  j_1arfz_string: String,
  budget_pd_string: String,
  ean11_string: String,
  pltyp_auft_string: String,
  ktgrm_string: String,
  ps_psp_pnr_string: String,
  matwa_string: String,
  sernr_string: String,
  dispute_case_binary: Array[Byte],
  auref_string: String,
  wminr_string: String,
  aktnr_string: String,
  pstyv_string: String,
  cmpre_flt_double: BoxedDouble,
  wgru2_string: String,
  @Decimal(13, 3) fklmg_decimal_13_3: BigDecimal,
  xchar_string: String,
  fsh_collection_string: String,
  @Decimal(5, 0) umvkz_decimal_5_0: BigDecimal,
  taxm4_string: String,
  aufpl_oaa_string: String,
  mvgr1_string: String,
  @Decimal(13, 2) nrab_value_decimal_13_2: BigDecimal,
  uvprs_string: String,
  dp_belnr_string: String,
  j_1btaxlw3_string: String,
  @Decimal(13, 3) lmeng_decimal_13_3: BigDecimal,
  stadat_string: String,
  campaign_binary: Array[Byte],
  prsdt_string: String,
  kdkg2_string: String,
  @Decimal(13, 2) skfbp_decimal_13_2: BigDecimal,
  vbelv_string: String,
  wkcou_string: String,
  taxm3_string: String,
  vkgrp_string: String,
  dcpnr_string: String,
  knuma_pi_string: String,
  wktps_string: String,
  vgbel_string: String,
  j_3getype_string: String,
  shkzg_string: String,
  bwtar_string: String,
  cmpnt_string: String,
  j_1bcfop_string: String,
  kdkg5_string: String,
  uecha_string: String,
  prs_work_period_string: String,
  wktnr_string: String,
  gsber_string: String,
  ukonm_string: String,
  @Decimal(13, 2) bonba_decimal_13_2: BigDecimal,
  wkreg_string: String,
  matkl_string: String,
  abges_double: BoxedDouble,
  wrf_charstc1_string: String,
  kostl_string: String,
  wrf_charstc2_string: String,
  grant_nbr_string: String,
  kvgr5_string: String,
  fistl_string: String,
  posnr_string: String,
  fmfgus_key_string: String,
  vrkme_string: String,
  erdat_string: String,
  j_3gorgueb_string: String,
  vgpos_string: String
) extends Entity

object vbrp extends TableSpec[vbrp_E](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
