package ct.dna.lakehouse.sr_raw.ct_gbl_ehq
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

@LakehouseEntity
case class ifiglacctlir_E_part1(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    customerservicenotification_string: String,
    referencepurchaseordercategory_string: String,
    partnerfund_string: String,
    reservicechargekey_string: String,
    isreversed_string: String,
    servicesrendereddate_date: Date,
    partnerservicedocumentitem_string: String,
    partnerventure_string: String,
    inventoryspecialstocktype_string: String,
    partnerconsolidationunit_string: String,
    partnerordercategory_string: String,
    workitem_string: String,
    pubsecbudgetaccountcocode_string: String,
    @Decimal(23, 2) grpvalntotprcvarcinglobcrcy_decimal_23_2: BigDecimal,
    accountingdocumenttype_string: String,
    glbusinesstransactiontype_string: String,
    @Decimal(23, 2) slspriceamountincocodecrcy_decimal_23_2: BigDecimal,
    cutbackaccount_string: String,
    additionalquantity3unit_string: String,
    partnermasterfixedasset_string: String,
    jointventureproductiondate_date: Date,
    reversalreferencedocument_string: String,
    housebank_string: String,
    accrualsubobject_string: String,
    partnerfunctionalarea_string: String,
    chartofaccounts_string: String,
    @Decimal(23, 2) amountintransactioncurrency_decimal_23_2: BigDecimal,
    @Decimal(23, 3) valuationfixedquantity_decimal_23_3: BigDecimal,
    lineitemiscompleted_string: String,
    soldproduct_string: String,
    partnercompanycode_string: String,
    subledgeracctlineitemtype_string: String,
    @Decimal(23, 3) additionalquantity3_decimal_23_3: BigDecimal,
    journalentryissecondaryentry_string: String,
    functionalarea_string: String,
    salesorganization_string: String,
    glrecordtype_string: String,
    @Decimal(23, 2) amountinfreedefinedcurrency8_decimal_23_2: BigDecimal,
    jointventurebillingdate_date: Date,
    predecessorreferencedoctype_string: String,
    repartnerservicechargekey_string: String,
    commitmentitem_string: String,
    prdcssrjournalentryfiscalyear_string: String,
    financialclosingstep_string: String,
    partnersalesdocumentitem_string: String,
    glaccount_string: String,
    eliminationprofitcenter_string: String,
    generalledgeragingincrement_string: String,
    servicedocument_string: String,
    accrualobjecttype_string: String,
    @Decimal(23, 2) fixedamountinglobalcrcy_decimal_23_2: BigDecimal,
    clearingdate_date: Date,
    @Decimal(23, 3) incmpltsummablevalnfxdqty_decimal_23_3: BigDecimal,
    accountingdocumentcategory_string: String,
    functionallocation_string: String,
    isopenitemmanaged_string: String,
    salesdistrict_string: String,
    maintenanceactivitytype_string: String,
    companycode_string: String,
    providercontract_string: String,
    transactioncurrency_string: String,
    sourceledger_string: String,
    iscommitment_string: String,
    invoicereference_string: String,
    senderglaccount_string: String,
    accrualobject_string: String,
    controllingobjectdebittype_string: String,
    operatingconcern_string: String,
    issettlement_string: String,
    debitcreditcode_string: String,
    predecessorjournalentryitem_string: String,
    projectnetwork_string: String,
    realestateproperty_string: String,
    journalentryitemcategory_string: String,
    wbselement_string: String,
    baseunit_string: String,
    valuedate_date: Date,
    offsettingchartofaccounts_string: String,
    @Decimal(15, 0) creationdatetime_decimal_15_0: BigDecimal,
    assettransactiontype_string: String,
    jointventure_string: String,
    businesssolutionorderitem_string: String,
    @Decimal(23, 2) amountinglobalcurrency_decimal_23_2: BigDecimal,
    partnerfixedasset_string: String,
    sourcereferencedocumentcntxt_string: String,
    pubsecbudgetcnsmpntype_string: String,
    @Decimal(23, 2) amountincompanycodecurrency_decimal_23_2: BigDecimal,
    performanceperiodstartdate_date: Date,
    distributionchannel_string: String,
    reversaltransactionsubitem_string: String,
    costsourceunit_string: String,
    transactiontypedetermination_string: String,
    depreciationfiscalperiod_string: String,
    cnsldtnfinancialstatementitem_string: String,
    ledgerfiscalyear_string: String,
    wbselementinternalid_string: String,
    partnerorder_string: String,
    documentitemtext_string: String,
    servicedocumentitem_string: String,
    ststclaccountassignmenttype2_string: String,
    consolidationchartofaccounts_string: String,
    inventoryspclstksalesdocitm_string: String,
    origincostcenter_string: String,
    grantid_string: String,
    assetclass_string: String,
    freedefinedcurrency5_string: String,
    superiororder_string: String,
    businesssolutionorder_string: String,
    partnerbusinessarea_string: String,
    partnerbusinessprocess_string: String,
    gteembudgetvaliditynumber_string: String,
    partnerservicedocument_string: String,
    functionalcurrency_string: String,
    @Decimal(23, 3) fixedquantity_decimal_23_3: BigDecimal,
    ordercategory_string: String,
    partnersegment_string: String,
    @Decimal(23, 3) additionalquantity2_decimal_23_3: BigDecimal,
    segment_string: String,
    housebankaccount_string: String,
    @Decimal(23, 2) amountinobjectcurrency_decimal_23_2: BigDecimal,
    originprofitcenter_string: String,
    supplier_string: String,
    sourcereferencedocument_string: String,
    fundedprogram_string: String,
    servicecontract_string: String,
    revenueaccountingcontract_string: String,
    ststclaccountassignmenttype3_string: String,
    issupplierstockvaluation_string: String,
    originorderoperation_string: String,
    customer_string: String,
    pubsecbudgetisrelevant_string: String,
    repartnersettlementunitid_string: String,
    @Decimal(23, 2) fixedamountincocodecrcy_decimal_23_2: BigDecimal,
    accrualreferenceobject_string: String,
    invoiceitemreference_string: String,
    origincostctractivitytype_string: String,
    partnerbudgetperiod_string: String,
    sponsoredclass_string: String,
    businesstransactiontype_string: String,
    fiscalyearperiod_string: String,
    realestatebuilding_string: String,
    generalledgeragingscope_string: String,
    @Decimal(23, 2) totalpricevarcinglobalcrcy_decimal_23_2: BigDecimal,
    creditriskclass_string: String,
    financialaccounttype_string: String,
    transactionsubitem_string: String,
    clearingdocfiscalyear_string: String,
    offsettingaccounttype_string: String,
    shiptoparty_string: String,
    controllingdocumentitem_string: String,
    accountingdocumentitem_string: String,
    maintenanceorderisplanned_string: String,
    incmpltsummablevalnqtyunt_string: String,
    itemissplit_string: String,
    exchangeratedate_date: Date,
    assetaccttransclassfctn_string: String,
    rerentalobject_string: String,
    groupmasterfixedasset_string: String,
    sendercostrecoverycode_string: String,
    senderaccountassignment_string: String,
    financialmanagementarea_string: String,
    conditioncontract_string: String,
    postingkey_string: String,
    performanceperiodenddate_date: Date,
    performanceobligation_string: String,
    orderitem_string: String,
    realestatepartnerproperty_string: String,
    pubsecbudgetaccount_string: String,
    financialvaluationsubobject_string: String,
    partnercompany_string: String,
    jointventurepartner_string: String,
    fiscalperiod_string: String,
    costorigingroup_string: String,
    logicalsystem_string: String,
    company_string: String,
    alternativeglaccount_string: String,
    partnercontrollingobjectclass_string: String,
    financialdatasource_string: String,
    additionalquantity1unit_string: String,
    companycodecurrency_string: String,
    countrychartofaccounts_string: String,
    customersuppliercountry_string: String,
    partnercostobject_string: String,
    @Decimal(21, 7) cutbackrun_decimal_21_7: BigDecimal,
    costctractivitytype_string: String,
    earmarkedfundsdocument_string: String,
    taxcode_string: String,
    cashledgercompanycode_string: String,
    @Decimal(23, 2) amountinfreedefinedcurrency1_decimal_23_2: BigDecimal,
    @Decimal(23, 3) referencequantity_decimal_23_3: BigDecimal,
    followondocumenttype_string: String,
    documentdate_date: Date,
    partnerservicedocumenttype_string: String,
    earmarkedfundsdocumentitem_string: String,
    maintpriority_string: String,
    organizationdivision_string: String,
    inventoryspclstockwbselement_string: String,
    jrnlentryitemobsoletereason_string: String,
    workcenterinternalid_string: String,
    salesdocument_string: String,
    resettlementunitid_string: String,
    accrualobjectlogicalsystem_string: String,
    partnergrant_string: String,
    sourcereferencedocumenttype_string: String,
    sourcelogicalsystem_string: String,
    jointventurebillingtype_string: String,
    @Decimal(23, 2) fixedpricevarcinglobalcrcy_decimal_23_2: BigDecimal,
    cutbackcostobject_string: String,
    financialservicesbranch_string: String,
    controllingobjectcurrency_string: String,
    assetvaluedate_date: Date,
    accrualvaluedate_date: Date,
    equipment_string: String,
    groupfixedasset_string: String,
    maintprioritytype_string: String,
    globalcurrency_string: String,
    @Decimal(23, 2) fixedamountintranscrcy_decimal_23_2: BigDecimal,
    controllingobject_string: String,
    ledgergllineitem_string: String,
    partnercostctractivitytype_string: String,
    partneraccountassignmenttype_string: String,
    billingdocumenttype_string: String,
    partnersettlementreferencedate_date: Date,
    invtryspclstockwbselmntintid_string: String,
    valuationarea_string: String,
    orderid_string: String,
    rebusinessentity_string: String,
    cnsldtnsubitemcategory_string: String,
    cashledgeraccount_string: String,
    @Decimal(23, 2) amountingrantcurrency_decimal_23_2: BigDecimal,
    sendercompanycode_string: String,
    productgroup_string: String,
    billtoparty_string: String,
    assetdepreciationarea_string: String,
    varianceorigingroup_string: String,
    controllingdebitcreditcode_string: String,
    sourcereferencedocsubitem_string: String,
    fund_string: String,
    partneraccountassignment_string: String,
    jointventureequitygroup_string: String,
    partnerprofitcenter_string: String,
    invoicereferencefiscalyear_string: String
) extends Entity

@LakehouseEntity
case class ifiglacctlir_E_part2(
    @PK _mk_org: String,
    costanalysisresource_string: String,
    @Decimal(23, 2) prftctrvalntotprcvarcinglbcrcy_decimal_23_2: BigDecimal,
    partnerprojectinternalid_string: String,
    partnerwbselementinternalid_string: String,
    controllingbustransactype_string: String,
    accountassignmenttype_string: String,
    partnerprojectnetworkactivity_string: String,
    @Decimal(23, 2) amountinfreedefinedcurrency5_decimal_23_2: BigDecimal,
    @Decimal(23, 2) amountinfreedefinedcurrency7_decimal_23_2: BigDecimal,
    masterfixedasset_string: String,
    partnerproject_string: String,
    settlementreferencedate_date: Date,
    providercontractitem_string: String,
    referencedocumenttype_string: String,
    @Decimal(23, 2) amountinbalancetransaccrcy_decimal_23_2: BigDecimal,
    originorder_string: String,
    financialtransactiontype_string: String,
    ordersuboperation_string: String,
    @Decimal(23, 3) valuationquantity_decimal_23_3: BigDecimal,
    creationdate_date: Date,
    issettled_string: String,
    product_string: String,
    costestimate_string: String,
    reversalreferencedocumentcntxt_string: String,
    pubsecbudgetcnsmpndate_date: Date,
    realestatepartnercontract_string: String,
    partnersalesdocument_string: String,
    purchasingdocumentitem_string: String,
    costcenter_string: String,
    postingdate_date: Date,
    fiscalyearvariant_string: String,
    clearingaccountingdocument_string: String,
    offsettingaccount_string: String,
    jrnlentryitemmigrationsource_string: String,
    @Decimal(23, 2) amountinfreedefinedcurrency2_decimal_23_2: BigDecimal,
    purchasingdocument_string: String,
    fundscenter_string: String,
    @Decimal(23, 2) grpvalnfixedamtinglobcrcy_decimal_23_2: BigDecimal,
    costobject_string: String,
    businessarea_string: String,
    ststclaccountassignmenttype1_string: String,
    financialservicesproductgroup_string: String,
    jointventurecostrecoverycode_string: String,
    @Decimal(23, 2) prftctrvalnfxdprcvarcinglbcrcy_decimal_23_2: BigDecimal,
    profitcenter_string: String,
    accountingdocument_string: String,
    maintenanceorderplanningcode_string: String,
    referencedocument_string: String,
    reversalreferencedocumenttype_string: String,
    businessprocess_string: String,
    timesheetovertimecategory_string: String,
    consolidationunit_string: String,
    prdcssrjournalentrycompanycode_string: String,
    taxcountry_string: String,
    partnercostcenter_string: String,
    referencedocumentitemgroup_string: String,
    @Decimal(23, 2) amountinfreedefinedcurrency6_decimal_23_2: BigDecimal,
    personnelnumber_string: String,
    accountassignmentnumber_string: String,
    relatednetworkactivity_string: String,
    senderaccountassignmenttype_string: String,
    mandt_string: String,
    sponsoredprogram_string: String,
    freedefinedcurrency4_string: String,
    financialvaluationobject_string: String,
    @Decimal(23, 2) grpvalnfixedprcvarcinglobcrcy_decimal_23_2: BigDecimal,
    freedefinedcurrency2_string: String,
    @Decimal(23, 3) incmpltsummablevalnqty_decimal_23_3: BigDecimal,
    jrnlperiodendclosingrunloguuid_binary: Array[Byte],
    financialvaluationobjecttype_string: String,
    orderoperation_string: String,
    predecessorreferencedoccntxt_string: String,
    freedefinedcurrency7_string: String,
    specialglcode_string: String,
    @Decimal(23, 3) additionalquantity1_decimal_23_3: BigDecimal,
    accountingdoccreatedbyuser_string: String,
    @Decimal(23, 2) amountinfunctionalcurrency_decimal_23_2: BigDecimal,
    freedefinedcurrency3_string: String,
    predecessorjournalentry_string: String,
    jrnlentraltvfyconsecutiveid_string: String,
    @Decimal(23, 2) prftctrvalnfxdamtinglobcrcy_decimal_23_2: BigDecimal,
    originsenderobject_string: String,
    productpricecontrol_string: String,
    soldproductgroup_string: String,
    predecessorreferencedocument_string: String,
    billablecontrol_string: String,
    partnerwbselement_string: String,
    materialledgercategory_string: String,
    repartnerbusinessentity_string: String,
    isreversal_string: String,
    project_string: String,
    clearingjournalentry_string: String,
    organizationalchange_string: String,
    balancetransactioncurrency_string: String,
    projectinternalid_string: String,
    quantityisincomplete_string: String,
    customersuppliercorporategroup_string: String,
    originproduct_string: String,
    jointventureequitytype_string: String,
    partnerprojectnetwork_string: String,
    budgetperiod_string: String,
    originctrlgdebitcreditcode_string: String,
    accountingnotificationuuid_binary: Array[Byte],
    @Decimal(23, 3) quantity_decimal_23_3: BigDecimal,
    assignmentreference_string: String,
    servicecontracttype_string: String,
    businesstransactioncategory_string: String,
    accrualitemtype_string: String,
    servicecontractitem_string: String,
    pubsecbudgetcnsmpnfsclyear_string: String,
    accountassignment_string: String,
    inventoryspecialstocksupplier_string: String,
    @Decimal(23, 2) amountinfreedefinedcurrency4_decimal_23_2: BigDecimal,
    workpackage_string: String,
    customersupplierindustry_string: String,
    jointventureaccountingactivity_string: String,
    materialledgerprocesstype_string: String,
    @Decimal(15, 0) lastchangedatetime_decimal_15_0: BigDecimal,
    originobjecttype_string: String,
    varianceoriginglaccount_string: String,
    partnerorderitem_string: String,
    glaccounttype_string: String,
    controllingobjectclass_string: String,
    @Decimal(23, 2) amountinfreedefinedcurrency3_decimal_23_2: BigDecimal,
    cnsldtnsubitem_string: String,
    referencedocumentcontext_string: String,
    freedefinedcurrency8_string: String,
    inventoryvaluationtype_string: String,
    controllingarea_string: String,
    repartnerrentalobject_string: String,
    pubsecbudgetcnsmpnamttype_string: String,
    sourcereferencedocumentitem_string: String,
    freedefinedcurrency1_string: String,
    clearingjournalentryfiscalyear_string: String,
    fixedasset_string: String,
    realestatepartnerbuilding_string: String,
    inventoryspecialstockvalntype_string: String,
    grantcurrency_string: String,
    freedefinedcurrency6_string: String,
    netduedate_date: Date,
    inventoryspclstksalesdocument_string: String,
    realestatecontract_string: String,
    salesdocumentitem_string: String,
    jointventureoperationaldate_date: Date,
    referencequantityunit_string: String,
    assembly_string: String,
    partnerequitygroup_string: String,
    fiscalyear_string: String,
    pubsecbudgetcnsmpnfsclperiod_string: String,
    additionalquantity2unit_string: String,
    customergroup_string: String,
    referencedocumentitem_string: String,
    servicedocumenttype_string: String,
    predecessorreferencedocitem_string: String,
    plant_string: String
) extends Entity

object ifiglacctlir
    extends TableSpec[Joined[ifiglacctlir_E_part1, ifiglacctlir_E_part2]](
      enableChangeDataFeed = true,
      manualClusterBy = None,
      timetravelDays = 35
    )
    with Loaded
