// AUTO GENERATED CODE - DO NOT EDIT
package ct.dna.lakehouse.sr_raw.ct_gbl_successfactors

import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

case class E_pl_mysuccess_api_background_languages(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    lastmodifieddate_string: String,
    writingprof_string: String,
    bgorderpos_string: String,
    language_string: String,
    backgroundelementid_string: String,
    readingprof_string: String,
    contains_masked_personal_data_boolean: BoxedBoolean,
    speakingprof_string: String,
    userid_string: String
) extends Entity

object pl_mysuccess_api_background_languages
    extends TableSpec[E_pl_mysuccess_api_background_languages](enableChangeDataFeed = true, manualClusterBy = None, timetravelDays = 35)
    with Loaded

// AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY

import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_pl_mysuccess_api_background_languages(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val lastmodifieddate_string: ColumnWithName = ColumnWithName(prefix + "lastmodifieddate_string")
  val writingprof_string: ColumnWithName = ColumnWithName(prefix + "writingprof_string")
  val bgorderpos_string: ColumnWithName = ColumnWithName(prefix + "bgorderpos_string")
  val language_string: ColumnWithName = ColumnWithName(prefix + "language_string")
  val backgroundelementid_string: ColumnWithName = ColumnWithName(prefix + "backgroundelementid_string")
  val readingprof_string: ColumnWithName = ColumnWithName(prefix + "readingprof_string")
  val contains_masked_personal_data_boolean: ColumnWithName = ColumnWithName(prefix + "contains_masked_personal_data_boolean")
  val speakingprof_string: ColumnWithName = ColumnWithName(prefix + "speakingprof_string")
  val userid_string: ColumnWithName = ColumnWithName(prefix + "userid_string")
}

object C_pl_mysuccess_api_background_languages extends C_pl_mysuccess_api_background_languages("") {
  def as(alias: String): C_pl_mysuccess_api_background_languages = new C_pl_mysuccess_api_background_languages(alias + ".")
}

// AUTO GENERATED:END
