// LOADED TABLE SPEC AUTO GENERATED:START
// Generated by LoadedTableSpecAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr_raw.ct_gbl_epp

import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.Loaded
import ct.dna.lakehouse.core.model.TableSpec

case class E_adrc(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    client_string: String,
    addrnumber_string: String,
    date_from_string: String,
    nation_string: String,
    date_to_string: String,
    title_string: String,
    name1_string: String,
    name2_string: String,
    name3_string: String,
    name4_string: String,
    name_text_string: String,
    name_co_string: String,
    city1_string: String,
    city2_string: String,
    city_code_string: String,
    cityp_code_string: String,
    home_city_string: String,
    cityh_code_string: String,
    chckstatus_string: String,
    regiogroup_string: String,
    post_code1_string: String,
    post_code2_string: String,
    post_code3_string: String,
    pcode1_ext_string: String,
    pcode2_ext_string: String,
    pcode3_ext_string: String,
    po_box_string: String,
    dont_use_p_string: String,
    po_box_num_string: String,
    po_box_loc_string: String,
    city_code2_string: String,
    po_box_reg_string: String,
    po_box_cty_string: String,
    postalarea_string: String,
    transpzone_string: String,
    street_string: String,
    dont_use_s_string: String,
    streetcode_string: String,
    streetabbr_string: String,
    house_num1_string: String,
    house_num2_string: String,
    house_num3_string: String,
    str_suppl1_string: String,
    str_suppl2_string: String,
    str_suppl3_string: String,
    location_string: String,
    building_string: String,
    floor_string: String,
    roomnumber_string: String,
    country_string: String,
    langu_string: String,
    region_string: String,
    addr_group_string: String,
    flaggroups_string: String,
    pers_addr_string: String,
    sort1_string: String,
    sort2_string: String,
    sort_phn_string: String,
    deflt_comm_string: String,
    tel_number_string: String,
    tel_extens_string: String,
    fax_number_string: String,
    fax_extens_string: String,
    flagcomm2_string: String,
    flagcomm3_string: String,
    flagcomm4_string: String,
    flagcomm5_string: String,
    flagcomm6_string: String,
    flagcomm7_string: String,
    flagcomm8_string: String,
    flagcomm9_string: String,
    flagcomm10_string: String,
    flagcomm11_string: String,
    flagcomm12_string: String,
    flagcomm13_string: String,
    addrorigin_string: String,
    mc_name1_string: String,
    mc_city1_string: String,
    mc_street_string: String,
    extension1_string: String,
    extension2_string: String,
    time_zone_string: String,
    taxjurcode_string: String,
    address_id_string: String,
    langu_crea_string: String,
    adrc_uuid_binary: Array[Byte],
    uuid_belated_string: String,
    id_category_string: String,
    adrc_err_status_string: String,
    po_box_lobby_string: String,
    deli_serv_type_string: String,
    deli_serv_number_string: String,
    county_code_string: String,
    county_string: String,
    township_code_string: String,
    township_string: String,
    mc_county_string: String,
    mc_township_string: String,
    xpcpt_string: String,
    duns_string: String,
    dunsp4_string: String
) extends Entity

object adrc
    extends TableSpec[E_adrc](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.Columns("_mk_instance", "_mk_partition", "_mk_file"),
      timetravelDays = 35
    )
    with Loaded
// LOADED TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_adrc(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val client_string: ColumnWithName = ColumnWithName(prefix + "client_string")
  val addrnumber_string: ColumnWithName = ColumnWithName(prefix + "addrnumber_string")
  val date_from_string: ColumnWithName = ColumnWithName(prefix + "date_from_string")
  val nation_string: ColumnWithName = ColumnWithName(prefix + "nation_string")
  val date_to_string: ColumnWithName = ColumnWithName(prefix + "date_to_string")
  val title_string: ColumnWithName = ColumnWithName(prefix + "title_string")
  val name1_string: ColumnWithName = ColumnWithName(prefix + "name1_string")
  val name2_string: ColumnWithName = ColumnWithName(prefix + "name2_string")
  val name3_string: ColumnWithName = ColumnWithName(prefix + "name3_string")
  val name4_string: ColumnWithName = ColumnWithName(prefix + "name4_string")
  val name_text_string: ColumnWithName = ColumnWithName(prefix + "name_text_string")
  val name_co_string: ColumnWithName = ColumnWithName(prefix + "name_co_string")
  val city1_string: ColumnWithName = ColumnWithName(prefix + "city1_string")
  val city2_string: ColumnWithName = ColumnWithName(prefix + "city2_string")
  val city_code_string: ColumnWithName = ColumnWithName(prefix + "city_code_string")
  val cityp_code_string: ColumnWithName = ColumnWithName(prefix + "cityp_code_string")
  val home_city_string: ColumnWithName = ColumnWithName(prefix + "home_city_string")
  val cityh_code_string: ColumnWithName = ColumnWithName(prefix + "cityh_code_string")
  val chckstatus_string: ColumnWithName = ColumnWithName(prefix + "chckstatus_string")
  val regiogroup_string: ColumnWithName = ColumnWithName(prefix + "regiogroup_string")
  val post_code1_string: ColumnWithName = ColumnWithName(prefix + "post_code1_string")
  val post_code2_string: ColumnWithName = ColumnWithName(prefix + "post_code2_string")
  val post_code3_string: ColumnWithName = ColumnWithName(prefix + "post_code3_string")
  val pcode1_ext_string: ColumnWithName = ColumnWithName(prefix + "pcode1_ext_string")
  val pcode2_ext_string: ColumnWithName = ColumnWithName(prefix + "pcode2_ext_string")
  val pcode3_ext_string: ColumnWithName = ColumnWithName(prefix + "pcode3_ext_string")
  val po_box_string: ColumnWithName = ColumnWithName(prefix + "po_box_string")
  val dont_use_p_string: ColumnWithName = ColumnWithName(prefix + "dont_use_p_string")
  val po_box_num_string: ColumnWithName = ColumnWithName(prefix + "po_box_num_string")
  val po_box_loc_string: ColumnWithName = ColumnWithName(prefix + "po_box_loc_string")
  val city_code2_string: ColumnWithName = ColumnWithName(prefix + "city_code2_string")
  val po_box_reg_string: ColumnWithName = ColumnWithName(prefix + "po_box_reg_string")
  val po_box_cty_string: ColumnWithName = ColumnWithName(prefix + "po_box_cty_string")
  val postalarea_string: ColumnWithName = ColumnWithName(prefix + "postalarea_string")
  val transpzone_string: ColumnWithName = ColumnWithName(prefix + "transpzone_string")
  val street_string: ColumnWithName = ColumnWithName(prefix + "street_string")
  val dont_use_s_string: ColumnWithName = ColumnWithName(prefix + "dont_use_s_string")
  val streetcode_string: ColumnWithName = ColumnWithName(prefix + "streetcode_string")
  val streetabbr_string: ColumnWithName = ColumnWithName(prefix + "streetabbr_string")
  val house_num1_string: ColumnWithName = ColumnWithName(prefix + "house_num1_string")
  val house_num2_string: ColumnWithName = ColumnWithName(prefix + "house_num2_string")
  val house_num3_string: ColumnWithName = ColumnWithName(prefix + "house_num3_string")
  val str_suppl1_string: ColumnWithName = ColumnWithName(prefix + "str_suppl1_string")
  val str_suppl2_string: ColumnWithName = ColumnWithName(prefix + "str_suppl2_string")
  val str_suppl3_string: ColumnWithName = ColumnWithName(prefix + "str_suppl3_string")
  val location_string: ColumnWithName = ColumnWithName(prefix + "location_string")
  val building_string: ColumnWithName = ColumnWithName(prefix + "building_string")
  val floor_string: ColumnWithName = ColumnWithName(prefix + "floor_string")
  val roomnumber_string: ColumnWithName = ColumnWithName(prefix + "roomnumber_string")
  val country_string: ColumnWithName = ColumnWithName(prefix + "country_string")
  val langu_string: ColumnWithName = ColumnWithName(prefix + "langu_string")
  val region_string: ColumnWithName = ColumnWithName(prefix + "region_string")
  val addr_group_string: ColumnWithName = ColumnWithName(prefix + "addr_group_string")
  val flaggroups_string: ColumnWithName = ColumnWithName(prefix + "flaggroups_string")
  val pers_addr_string: ColumnWithName = ColumnWithName(prefix + "pers_addr_string")
  val sort1_string: ColumnWithName = ColumnWithName(prefix + "sort1_string")
  val sort2_string: ColumnWithName = ColumnWithName(prefix + "sort2_string")
  val sort_phn_string: ColumnWithName = ColumnWithName(prefix + "sort_phn_string")
  val deflt_comm_string: ColumnWithName = ColumnWithName(prefix + "deflt_comm_string")
  val tel_number_string: ColumnWithName = ColumnWithName(prefix + "tel_number_string")
  val tel_extens_string: ColumnWithName = ColumnWithName(prefix + "tel_extens_string")
  val fax_number_string: ColumnWithName = ColumnWithName(prefix + "fax_number_string")
  val fax_extens_string: ColumnWithName = ColumnWithName(prefix + "fax_extens_string")
  val flagcomm2_string: ColumnWithName = ColumnWithName(prefix + "flagcomm2_string")
  val flagcomm3_string: ColumnWithName = ColumnWithName(prefix + "flagcomm3_string")
  val flagcomm4_string: ColumnWithName = ColumnWithName(prefix + "flagcomm4_string")
  val flagcomm5_string: ColumnWithName = ColumnWithName(prefix + "flagcomm5_string")
  val flagcomm6_string: ColumnWithName = ColumnWithName(prefix + "flagcomm6_string")
  val flagcomm7_string: ColumnWithName = ColumnWithName(prefix + "flagcomm7_string")
  val flagcomm8_string: ColumnWithName = ColumnWithName(prefix + "flagcomm8_string")
  val flagcomm9_string: ColumnWithName = ColumnWithName(prefix + "flagcomm9_string")
  val flagcomm10_string: ColumnWithName = ColumnWithName(prefix + "flagcomm10_string")
  val flagcomm11_string: ColumnWithName = ColumnWithName(prefix + "flagcomm11_string")
  val flagcomm12_string: ColumnWithName = ColumnWithName(prefix + "flagcomm12_string")
  val flagcomm13_string: ColumnWithName = ColumnWithName(prefix + "flagcomm13_string")
  val addrorigin_string: ColumnWithName = ColumnWithName(prefix + "addrorigin_string")
  val mc_name1_string: ColumnWithName = ColumnWithName(prefix + "mc_name1_string")
  val mc_city1_string: ColumnWithName = ColumnWithName(prefix + "mc_city1_string")
  val mc_street_string: ColumnWithName = ColumnWithName(prefix + "mc_street_string")
  val extension1_string: ColumnWithName = ColumnWithName(prefix + "extension1_string")
  val extension2_string: ColumnWithName = ColumnWithName(prefix + "extension2_string")
  val time_zone_string: ColumnWithName = ColumnWithName(prefix + "time_zone_string")
  val taxjurcode_string: ColumnWithName = ColumnWithName(prefix + "taxjurcode_string")
  val address_id_string: ColumnWithName = ColumnWithName(prefix + "address_id_string")
  val langu_crea_string: ColumnWithName = ColumnWithName(prefix + "langu_crea_string")
  val adrc_uuid_binary: ColumnWithName = ColumnWithName(prefix + "adrc_uuid_binary")
  val uuid_belated_string: ColumnWithName = ColumnWithName(prefix + "uuid_belated_string")
  val id_category_string: ColumnWithName = ColumnWithName(prefix + "id_category_string")
  val adrc_err_status_string: ColumnWithName = ColumnWithName(prefix + "adrc_err_status_string")
  val po_box_lobby_string: ColumnWithName = ColumnWithName(prefix + "po_box_lobby_string")
  val deli_serv_type_string: ColumnWithName = ColumnWithName(prefix + "deli_serv_type_string")
  val deli_serv_number_string: ColumnWithName = ColumnWithName(prefix + "deli_serv_number_string")
  val county_code_string: ColumnWithName = ColumnWithName(prefix + "county_code_string")
  val county_string: ColumnWithName = ColumnWithName(prefix + "county_string")
  val township_code_string: ColumnWithName = ColumnWithName(prefix + "township_code_string")
  val township_string: ColumnWithName = ColumnWithName(prefix + "township_string")
  val mc_county_string: ColumnWithName = ColumnWithName(prefix + "mc_county_string")
  val mc_township_string: ColumnWithName = ColumnWithName(prefix + "mc_township_string")
  val xpcpt_string: ColumnWithName = ColumnWithName(prefix + "xpcpt_string")
  val duns_string: ColumnWithName = ColumnWithName(prefix + "duns_string")
  val dunsp4_string: ColumnWithName = ColumnWithName(prefix + "dunsp4_string")
}

object C_adrc extends C_adrc("") {
  def as(alias: String): C_adrc = new C_adrc(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
