package ct.dna.lakehouse.sr_raw.ct_gbl_epp
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

@LakehouseEntity
case class t001_E(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    dttdsp_string: String,
    surccm_string: String,
    xkdft_string: String,
    xvvwa_string: String,
    wfvar_string: String,
    xjvaa_string: String,
    ebukr_string: String,
    xcession_string: String,
    dtaxr_string: String,
    xskfn_string: String,
    fmhrdate_date: Date,
    mregl_string: String,
    xfmca_string: String,
    infmt_string: String,
    mwskv_string: String,
    xbbbf_string: String,
    txjcd_string: String,
    fdbuk_string: String,
    bukrs_glob_string: String,
    rcomp_string: String,
    periv_string: String,
    xbbko_string: String,
    xgjrv_string: String,
    dttaxc_string: String,
    stceg_string: String,
    adrnr_string: String,
    fm_derive_acc_string: String,
    offsacct_string: String,
    buvar_string: String,
    wt_newwt_string: String,
    xcos_string: String,
    xsplt_string: String,
    xkkbi_string: String,
    xfdsd_string: String,
    pp_pdate_string: String,
    ktop2_string: String,
    xfdis_string: String,
    umkrs_string: String,
    xslta_string: String,
    xnegp_string: String,
    pst_per_var_string: String,
    butxt_string: String,
    opvar_string: String,
    dtprov_string: String,
    fstva_string: String,
    xeink_string: String,
    ktopl_string: String,
    spras_string: String,
    xbbsc_string: String,
    mwska_string: String,
    waabw_string: String,
    land1_string: String,
    kkber_string: String,
    dkweg_string: String,
    xprod_string: String,
    xmwsn_string: String,
    txkrs_string: String,
    kokfi_string: String,
    xfmcb_string: String,
    dtamtc_string: String,
    xbbba_string: String,
    mandt_string: String,
    impda_string: String,
    bapovar_string: String,
    ort01_string: String,
    xcovr_string: String,
    xvatdate_string: String,
    waers_string: String,
    bukrs_string: String,
    fstvare_string: String,
    xvalv_string: String,
    xfmco_string: String,
    xextb_string: String,
    fikrs_string: String,
    xgsbe_string: String,
    xfdmm_string: String,
    xstdt_string: String,
    xbbbe_string: String,
    kopim_string: String,
    fmhrdate_string: String
) extends Entity

object t001
    extends TableSpec[t001_E](
      enableChangeDataFeed = true,
      manualClusterBy = None,
      timetravelDays = 35
    )
    with Loaded
