package ct.dna.lakehouse.sr_raw.ct_gbl_epp
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class tvfk_E(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  kalsmc_string: String,
  oiabalan_string: String,
  oiindcm_string: String,
  kalsmcc_string: String,
  txtlf_string: String,
  oinetexit_string: String,
  relep_string: String,
  oinetrpt_string: String,
  uevor_string: String,
  fkart_mev_reset_string: String,
  kalsmcd_string: String,
  oiinvcyc9_string: String,
  ernam_string: String,
  kalsmbp_string: String,
  xfilkd_string: String,
  trvog_string: String,
  kalsmcb_string: String,
  oiinvcyc7_string: String,
  j_1ainvref_string: String,
  j_1btdidl_string: String,
  xblnr_fi_s_string: String,
  kalvg_string: String,
  pargk_string: String,
  txtgr_p_string: String,
  umfng_string: String,
  rfbfk_string: String,
  j_1acpdel_string: String,
  oiinvcyc5_string: String,
  j_1btdcol_string: String,
  j_1btdcoh_string: String,
  kalsm_string: String,
  fkart_ab_string: String,
  fkart_rl_string: String,
  oiinvcyc2_string: String,
  oiinvcyc8_string: String,
  mandt_string: String,
  oic_errha_string: String,
  oibtcexit_string: String,
  oiptrmex_string: String,
  j_1bmainpa_string: String,
  stafo_string: String,
  txtgr_string: String,
  hityp_pr_string: String,
  blart_string: String,
  grbed_s_string: String,
  oiinvcyc3_string: String,
  j_1bnfrel_string: String,
  oiamwofi_string: String,
  kvslv_string: String,
  vbtyp_string: String,
  kopgr_string: String,
  uveib_string: String,
  numke_string: String,
  xvalgs_string: String,
  kschl_string: String,
  xnegp_string: String,
  oic_fkart_string: String,
  fkarts_string: String,
  oifeepd_string: String,
  oiinvcyc1_string: String,
  oic_accval_string: String,
  incpo_string: String,
  oic_diffin_string: String,
  ordnr_fi_s_string: String,
  pargp_string: String,
  ism_xkrvo_string: String,
  j_1btdidh_string: String,
  oiinvcyc6_string: String,
  oifinexit_string: String,
  oiinvcyc4_string: String,
  kalsmca_string: String,
  vbtyp_ext_string: String,
  fkart_string: String,
  oiinvapp_string: String,
  oicinpd_string: String,
  stati_string: String,
  xkoiv_string: String,
  oiselexit_string: String,
  fktyp_string: String,
  oic_dicntr_string: String,
  borvf_string: String,
  numki_string: String,
  kappl_string: String,
  kunn0_string: String,
  txn08_string: String
) extends Entity

object tvfk extends TableSpec[tvfk_E](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
