// AUTO GENERATED CODE - DO NOT EDIT
package ct.dna.lakehouse.sr_raw.ct_gbl_ad

import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

case class E_locations(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    ou_region_string: String,
    c_string: String,
    ou_subsidiary_string: String,
    ou_location_name_string: String,
    ou_location_code_string: String,
    description_string: String,
    rec_src_string: String,
    contains_masked_personal_data_boolean: BoxedBoolean,
    l_string: String,
    co_string: String,
    canonicalname_string: String,
    ou_subsidiary_division_string: String,
    objectguid_string: String,
    name_string: String,
    load_dt_string: String,
    distinguishedname_string: String,
    ou_division_string: String,
    id_long: BoxedLong
) extends Entity

object locations extends TableSpec[E_locations](enableChangeDataFeed = true, manualClusterBy = None, timetravelDays = 35) with Loaded

// AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY

import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_locations(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val ou_region_string: ColumnWithName = ColumnWithName(prefix + "ou_region_string")
  val c_string: ColumnWithName = ColumnWithName(prefix + "c_string")
  val ou_subsidiary_string: ColumnWithName = ColumnWithName(prefix + "ou_subsidiary_string")
  val ou_location_name_string: ColumnWithName = ColumnWithName(prefix + "ou_location_name_string")
  val ou_location_code_string: ColumnWithName = ColumnWithName(prefix + "ou_location_code_string")
  val description_string: ColumnWithName = ColumnWithName(prefix + "description_string")
  val rec_src_string: ColumnWithName = ColumnWithName(prefix + "rec_src_string")
  val contains_masked_personal_data_boolean: ColumnWithName = ColumnWithName(prefix + "contains_masked_personal_data_boolean")
  val l_string: ColumnWithName = ColumnWithName(prefix + "l_string")
  val co_string: ColumnWithName = ColumnWithName(prefix + "co_string")
  val canonicalname_string: ColumnWithName = ColumnWithName(prefix + "canonicalname_string")
  val ou_subsidiary_division_string: ColumnWithName = ColumnWithName(prefix + "ou_subsidiary_division_string")
  val objectguid_string: ColumnWithName = ColumnWithName(prefix + "objectguid_string")
  val name_string: ColumnWithName = ColumnWithName(prefix + "name_string")
  val load_dt_string: ColumnWithName = ColumnWithName(prefix + "load_dt_string")
  val distinguishedname_string: ColumnWithName = ColumnWithName(prefix + "distinguishedname_string")
  val ou_division_string: ColumnWithName = ColumnWithName(prefix + "ou_division_string")
  val id_long: ColumnWithName = ColumnWithName(prefix + "id_long")
}

object C_locations extends C_locations("") {
  def as(alias: String): C_locations = new C_locations(alias + ".")
}

// AUTO GENERATED:END
