rules = [
  DisableSyntax,
  ProcedureSyntax,
  RedundantSyntax,
  OrganizeImports,
  RemoveUnused
]





OrganizeImports {
  targetDialect = Scala2
  expandRelative = true
  groups = ["re:javax?\\.", "scala.", "*"]
}