package ct.dna.lakehouse.sr_raw.ct_gbl_p64
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class marc_E_part1(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  uomgr_string: String,
  vers_active_string: String,
  @Decimal(3, 1) ueeto_decimal_3_1: BigDecimal,
  @Decimal(11, 0) pps_grprt_decimal_11_0: BigDecimal,
  matnr_string: String,
  pps_hunit_out_string: String,
  @Decimal(3, 1) _sapmp_tolprmi_decimal_3_1: BigDecimal,
  pps_strategy_string: String,
  @Decimal(3, 0) resvp_decimal_3_0: BigDecimal,
  pps_peg_strategy_string: String,
  iuid_type_string: String,
  @Decimal(13, 3) bstmi_decimal_13_3: BigDecimal,
  ueetk_string: String,
  lgpro_string: String,
  ladgr_string: String,
  diber_string: String,
  rgekz_string: String,
  atpkz_string: String,
  sgt_stk_prt_string: String,
  @Decimal(13, 3) pps_conhap_out_decimal_13_3: BigDecimal,
  schgt_string: String,
  @Decimal(13, 6) zzqcf_decimal_13_6: BigDecimal,
  shpro_string: String,
  @Decimal(13, 2) vkumc_decimal_13_2: BigDecimal,
  ocmpf_string: String,
  _vso_r_fork_dir_string: String,
  prctr_string: String,
  otype_string: String,
  lfmon_string: String,
  lizyk_string: String,
  sobsk_string: String,
  kzech_string: String,
  mrppp_string: String,
  vint2_string: String,
  @Decimal(5, 2) kausf_decimal_5_2: BigDecimal,
  @Decimal(9, 0) wstgh_decimal_9_0: BigDecimal,
  pps_hunit_string: String,
  sauft_string: String,
  plnnr_string: String,
  usequ_string: String,
  fsh_mg_arun_req_string: String,
  @Decimal(13, 3) umlmc_decimal_13_3: BigDecimal,
  lzeih_string: String,
  objid_string: String,
  pps_fixpeg_string: String,
  loggr_string: String,
  copam_string: String,
  fsh_calendar_group_string: String,
  bwtty_string: String,
  @Decimal(13, 2) vkglg_decimal_13_2: BigDecimal,
  kordb_string: String,
  sgt_mmstd_string: String,
  nkmpr_string: String,
  profil_string: String,
  autru_string: String,
  kzppv_string: String,
  fhori_string: String,
  @Decimal(2, 1) abfac_decimal_2_1: BigDecimal,
  bwscl_string: String,
  qmatv_string: String,
  ccfix_string: String,
  prend_string: String,
  pps_heur_id_string: String,
  miskz_string: String,
  steuc_string: String,
  prene_string: String,
  plnty_string: String,
  @Decimal(4, 2) vrbfk_decimal_4_2: BigDecimal,
  pstat_string: String,
  zzeudr_string: String,
  sgt_mrpsi_string: String,
  uchkz_string: String,
  indus_string: String,
  ausdt_string: String,
  compl_string: String,
  umrsl_string: String,
  pfrei_string: String,
  frtme_string: String,
  dplfs_string: String,
  kzpro_string: String,
  mdach_string: String,
  kzkup_string: String,
  vrbmt_string: String,
  dispr_string: String,
  ucmat_string: String,
  sbdkz_string: String,
  max_troc_string: String,
  kzpsp_string: String,
  @Decimal(13, 3) bwesb_decimal_13_3: BigDecimal,
  rdprf_string: String,
  multiple_ekgrp_string: String,
  vrbwk_string: String,
  stlan_string: String,
  stlal_string: String,
  @Decimal(13, 3) pps_conhap_decimal_13_3: BigDecimal,
  @Decimal(5, 2) bearz_decimal_5_2: BigDecimal,
  ref_schema_string: String,
  zzplantref_string: String,
  pps_atpcheck_string: String,
  @Decimal(3, 0) plifz_decimal_3_0: BigDecimal,
  sfcpf_string: String,
  fxhor_string: String,
  @Decimal(3, 1) _sapmp_tolprpl_decimal_3_1: BigDecimal,
  @Decimal(13, 3) bstfe_decimal_13_3: BigDecimal,
  auftl_string: String,
  xmcng_string: String,
  kzkfk_string: String,
  fsh_seaim_string: String,
  nfmat_string: String,
  ppskz_string: String,
  @Decimal(3, 0) takzt_decimal_3_0: BigDecimal,
  _vso_r_pkgrp_string: String,
  _vso_r_lane_num_string: String,
  @Decimal(13, 3) minbe_decimal_13_3: BigDecimal,
  ffrei_string: String,
  dispo_string: String,
  gpmkz_string: String,
  sgt_mrp_atp_status_string: String,
  eprio_string: String,
  sgt_covs_string: String,
  sfepr_string: String,
  plvar_string: String,
  vers_cseg_string: String,
  lgfsb_string: String,
  shzet_string: String,
  werks_string: String,
  cuobj_string: String,
  rotation_date_string: String,
  @Decimal(13, 3) eislo_decimal_13_3: BigDecimal,
  @Decimal(5, 0) mpdau_decimal_5_0: BigDecimal,
  fprfm_string: String,
  mandt_string: String,
  casnr_string: String,
  qmata_string: String,
  cuobv_string: String,
  @Decimal(13, 3) vbamg_decimal_13_3: BigDecimal,
  dismm_string: String,
  lfrhy_string: String,
  @Decimal(5, 2) vbeaz_decimal_5_2: BigDecimal,
  @Decimal(3, 1) lgrad_decimal_3_1: BigDecimal,
  prefe_string: String,
  stdpd_string: String,
  fxpru_string: String,
  ekgrp_string: String,
  @Decimal(11, 0) pps_giprt_decimal_11_0: BigDecimal,
  perkz_string: String,
  stawn_string: String,
  sgt_defsc_string: String,
  @Decimal(3, 1) sproz_decimal_3_1: BigDecimal,
  matgr_string: String,
  sgt_scope_string: String,
  convt_string: String,
  dpcbt_string: String,
  servg_string: String,
  @Decimal(13, 3) fixls_decimal_13_3: BigDecimal,
  apokz_string: String,
  @Decimal(13, 3) maxls_decimal_13_3: BigDecimal,
  @Decimal(3, 0) gi_pr_time_decimal_3_0: BigDecimal,
  kzagl_string: String,
  beskz_string: String,
  fevor_string: String,
  @Decimal(3, 0) dplho_decimal_3_0: BigDecimal,
  mmstd_string: String,
  kzkri_string: String,
  fsh_kzech_string: String,
  lagpr_string: String,
  kzdkz_string: String,
  @Decimal(13, 3) basmg_decimal_13_3: BigDecimal,
  nf_flag_string: String,
  @Decimal(3, 0) wzeit_decimal_3_0: BigDecimal,
  iuid_relevant_string: String,
  @Decimal(11, 2) losfx_decimal_11_2: BigDecimal,
  pps_planning_type_string: String,
  sgt_chint_string: String,
  itark_string: String,
  preno_string: String,
  ausme_string: String,
  @Decimal(3, 0) dzeit_decimal_3_0: BigDecimal,
  ahdis_string: String,
  mtvfp_string: String,
  herbl_string: String,
  @Decimal(13, 3) glgmg_decimal_13_3: BigDecimal,
  vrbdt_string: String,
  zzccref_string: String,
  @Decimal(13, 3) minls_decimal_13_3: BigDecimal,
  altsl_string: String,
  lfgja_string: String,
  @Decimal(3, 0) quazt_decimal_3_0: BigDecimal,
  megru_string: String,
  dplpu_string: String,
  aplal_string: String,
  sgt_prcm_string: String,
  ssqss_string: String,
  kzdie_string: String,
  fsh_var_group_string: String,
  @Decimal(13, 2) vktrw_decimal_13_2: BigDecimal,
  @Decimal(5, 0) maxlz_decimal_5_0: BigDecimal,
  @Decimal(5, 2) ruezt_decimal_5_2: BigDecimal,
  cons_procg_string: String,
  @Decimal(13, 3) bstrf_decimal_13_3: BigDecimal,
  mownr_string: String,
  gpnum_string: String,
  prenc_string: String,
  mfrgr_string: String,
  mcrue_string: String,
  @Decimal(11, 0) pps_peg_past_al_decimal_11_0: BigDecimal,
  @Decimal(13, 3) target_stock_decimal_13_3: BigDecimal,
  sgt_statc_string: String,
  xchar_string: String,
  kzaus_string: String,
  @Decimal(13, 3) losgr_decimal_13_3: BigDecimal,
  insmk_string: String,
  maabc_string: String,
  vrmod_string: String,
  @Decimal(13, 3) ltinc_decimal_13_3: BigDecimal,
  vspvb_string: String,
  vint1_string: String,
  verkz_string: String,
  preng_string: String,
  herkr_string: String,
  sobsl_string: String,
  @Decimal(5, 2) vzusl_decimal_5_2: BigDecimal,
  @Decimal(5, 2) vrvez_decimal_5_2: BigDecimal,
  @Decimal(5, 2) ausss_decimal_5_2: BigDecimal,
  _vso_r_pal_vend_string: String,
  awsls_string: String,
  periv_string: String,
  mtver_string: String,
  herkl_string: String,
  @Decimal(13, 3) bstma_decimal_13_3: BigDecimal,
  @Decimal(5, 2) tranz_decimal_5_2: BigDecimal,
  mmsta_string: String,
  kzbed_string: String,
  uid_iea_string: String,
  disgr_string: String,
  @Decimal(13, 3) eisbe_decimal_13_3: BigDecimal,
  disls_string: String,
  sernp_string: String,
  lvorm_string: String,
  @Decimal(13, 3) mabst_decimal_13_3: BigDecimal,
  mogru_string: String,
  @Decimal(11, 0) pps_peg_fut_al_decimal_11_0: BigDecimal
) extends Entity


@LakehouseEntity
case class marc_E_part2(
  @PK _mk_org: String,
  min_troc_string: String,
  @Decimal(3, 0) webaz_decimal_3_0: BigDecimal,
  shflg_string: String,
  expme_string: String,
  kautb_string: String,
  abcin_string: String,
  rwpro_string: String,
  fvidk_string: String,
  @Decimal(5, 0) prfrq_decimal_5_0: BigDecimal,
  qssys_string: String,
  ncost_string: String,
  qzgtp_string: String,
  xchpf_string: String,
  strgr_string: String,
  fabkz_string: String,
  @Decimal(13, 3) trame_decimal_13_3: BigDecimal,
  @Decimal(3, 1) uneto_decimal_3_1: BigDecimal
) extends Entity

object marc extends TableSpec[Joined[marc_E_part1, marc_E_part2]](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
