package ct.dna.lakehouse.sr_raw.ct_gbl_p43
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class ekbe_E(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  @Decimal(13, 2) retamt_lc_decimal_13_2: BigDecimal,
  @Decimal(13, 2) dmbtr_pop_decimal_13_2: BigDecimal,
  @Decimal(13, 3) lsmng_decimal_13_3: BigDecimal,
  @Decimal(9, 5) wkurs_decimal_9_5: BigDecimal,
  lemin_string: String,
  fsh_collection_string: String,
  fsh_season_string: String,
  matnr_string: String,
  @Decimal(13, 2) retamt_fc_decimal_13_2: BigDecimal,
  logsy_string: String,
  cpudt_string: String,
  @Decimal(13, 3) wesbb_decimal_13_3: BigDecimal,
  fsh_season_year_string: String,
  sgt_scat_string: String,
  grund_string: String,
  ernam_string: String,
  vbeln_st_string: String,
  belnr_string: String,
  bewtp_string: String,
  evere_string: String,
  @Decimal(13, 3) qty_diff_decimal_13_3: BigDecimal,
  @Decimal(13, 3) menge_pop_decimal_13_3: BigDecimal,
  xblnr_string: String,
  @Decimal(13, 2) dmbtr_decimal_13_2: BigDecimal,
  @Decimal(13, 3) bpmng_decimal_13_3: BigDecimal,
  @Decimal(13, 2) areww_decimal_13_2: BigDecimal,
  buzei_string: String,
  @Decimal(13, 2) refwr_decimal_13_2: BigDecimal,
  vgabe_string: String,
  packno_string: String,
  @Decimal(13, 2) wrbtr_pop_decimal_13_2: BigDecimal,
  ebeln_string: String,
  @Decimal(13, 2) kudif_decimal_13_2: BigDecimal,
  lfbnr_string: String,
  et_upd_string: String,
  @Decimal(13, 2) reewr_decimal_13_2: BigDecimal,
  vbelp_st_string: String,
  @Decimal(13, 2) arewr_decimal_13_2: BigDecimal,
  @Decimal(13, 2) wrbtr_decimal_13_2: BigDecimal,
  @Decimal(13, 3) bpmng_pop_decimal_13_3: BigDecimal,
  xwsbr_string: String,
  charg_string: String,
  xmacc_string: String,
  ebelp_string: String,
  werks_string: String,
  mandt_string: String,
  introw_string: String,
  cputm_string: String,
  elikz_string: String,
  inv_item_origin_string: String,
  wrf_charstc3_string: String,
  @Decimal(13, 3) bpwes_decimal_13_3: BigDecimal,
  @Decimal(13, 3) menge_decimal_13_3: BigDecimal,
  fsh_theme_string: String,
  saprl_string: String,
  etens_string: String,
  j_sc_die_comp_f_string: String,
  @Decimal(13, 3) bamng_decimal_13_3: BigDecimal,
  gjahr_string: String,
  lfgja_string: String,
  mwskz_string: String,
  ematn_string: String,
  @Decimal(13, 2) retamtp_lc_decimal_13_2: BigDecimal,
  xunpl_string: String,
  @Decimal(13, 2) rewrb_decimal_13_2: BigDecimal,
  @Decimal(13, 2) arewr_pop_decimal_13_2: BigDecimal,
  bekkn_string: String,
  srvpos_string: String,
  hswae_string: String,
  knumv_string: String,
  @Decimal(13, 3) bpweb_decimal_13_3: BigDecimal,
  weora_string: String,
  lsmeh_string: String,
  lfpos_string: String,
  shkzg_string: String,
  bwtar_string: String,
  @Decimal(13, 2) arewb_decimal_13_2: BigDecimal,
  bldat_string: String,
  @Decimal(13, 3) wesbs_decimal_13_3: BigDecimal,
  @Decimal(13, 2) retamtp_fc_decimal_13_2: BigDecimal,
  budat_string: String,
  wrf_charstc1_string: String,
  wrf_charstc2_string: String,
  zekkn_string: String,
  bwart_string: String,
  waers_string: String,
  xwoff_string: String
) extends Entity

object ekbe extends TableSpec[ekbe_E](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
