package ct.dna.lakehouse.sr_raw.ct_gbl_p43
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class lfa1_E(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  ort02_string: String,
  dlgrp_string: String,
  dtams_string: String,
  gbdat_string: String,
  telfx_string: String,
  kraus_string: String,
  exp_string: String,
  xcpdk_string: String,
  begru_string: String,
  brsch_string: String,
  regss_string: String,
  ernam_string: String,
  pfach_string: String,
  icmstaxpay_string: String,
  sfrgr_string: String,
  term_li_string: String,
  name3_string: String,
  spras_string: String,
  fityp_string: String,
  sortl_string: String,
  stgdl_string: String,
  borgr_datun_string: String,
  bahns_string: String,
  cvp_xblck_string: String,
  name1_string: String,
  stcd5_string: String,
  confs_string: String,
  telx1_string: String,
  stkzn_string: String,
  legalnat_string: String,
  qssysdat_string: String,
  stkza_string: String,
  duefl_string: String,
  telbx_string: String,
  stcd1_string: String,
  regio_string: String,
  crtn_string: String,
  alc_string: String,
  stkzu_string: String,
  stcd4_string: String,
  datlt_string: String,
  carrier_conf_string: String,
  gbort_string: String,
  ppa_relevant_string: String,
  scheduling_type_string: String,
  transport_chain_string: String,
  stcd6_string: String,
  psost_string: String,
  emnfr_string: String,
  lnrza_string: String,
  land1_string: String,
  stceg_string: String,
  lfurl_string: String,
  ric_string: String,
  scacd_string: String,
  bbsnr_string: String,
  stcd2_string: String,
  crc_num_string: String,
  stenr_string: String,
  anred_string: String,
  fisku_string: String,
  updat_string: String,
  mcod2_string: String,
  nodel_string: String,
  zz_cvm_string: String,
  werks_string: String,
  pson1_string: String,
  mcod3_string: String,
  j_sc_currency_string: String,
  j_1kftbus_string: String,
  decregpc_string: String,
  mandt_string: String,
  ktokk_string: String,
  sperz_string: String,
  j_1kfrepre_string: String,
  vbund_string: String,
  psohs_string: String,
  pson3_string: String,
  txjcd_string: String,
  plkal_string: String,
  zz_cvn_string: String,
  fiskn_string: String,
  rne_string: String,
  ipisp_string: String,
  telf1_string: String,
  name4_string: String,
  psofg_string: String,
  mcod1_string: String,
  psotl_string: String,
  profs_string: String,
  rg_string: String,
  konzs_string: String,
  adrnr_string: String,
  comsize_string: String,
  psois_string: String,
  zsvgr_string: String,
  telf2_string: String,
  j_1kftind_string: String,
  podkzb_string: String,
  esrnr_string: String,
  actss_string: String,
  xzemp_string: String,
  psovn_string: String,
  teltx_string: String,
  borgr_yeaun_string: String,
  revdb_string: String,
  sperm_string: String,
  indtyp_string: String,
  submi_relevant_string: String,
  pstlz_string: String,
  rnedate_string: String,
  pmt_office_string: String,
  taxbs_string: String,
  pson2_string: String,
  name2_string: String,
  stcdt_string: String,
  cnae_string: String,
  ltsna_string: String,
  pstl2_string: String,
  sperq_string: String,
  dunsp4_string: String,
  @Decimal(3, 0) staging_time_decimal_3_0: BigDecimal,
  uf_string: String,
  min_comp_string: String,
  stcd3_string: String,
  dtaws_string: String,
  ktock_string: String,
  lifnr_string: String,
  werkr_string: String,
  ort01_string: String,
  bubkz_string: String,
  lzone_string: String,
  @Decimal(15, 2) j_sc_capital_decimal_15_2: BigDecimal,
  kunnr_string: String,
  sperr_string: String,
  loevm_string: String,
  stras_string: String,
  pfort_string: String,
  bbbnr_string: String,
  uptim_string: String,
  tdt_string: String,
  xlfza_string: String,
  qssys_string: String,
  rgdate_string: String,
  sexkz_string: String,
  erdat_string: String
) extends Entity

object lfa1 extends TableSpec[lfa1_E](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
