// LOADED TABLE SPEC AUTO GENERATED:START
// Generated by LoadedTableSpecAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr_raw.ct_gbl_p43

import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.Loaded
import ct.dna.lakehouse.core.model.TableSpec

case class E_plko(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt_string: String,
    plnty_string: String,
    plnnr_string: String,
    plnal_string: String,
    zaehl_string: String,
    datuv_string: String,
    techv_string: String,
    aennr_string: String,
    loekz_string: String,
    parkz_string: String,
    andat_string: String,
    annam_string: String,
    aedat_string: String,
    aenam_string: String,
    verwe_string: String,
    werks_string: String,
    statu_string: String,
    plnme_string: String,
    @Decimal(13, 3) losvn_decimal_13_3: BigDecimal,
    @Decimal(13, 3) losbs_decimal_13_3: BigDecimal,
    vagrp_string: String,
    aeszn_string: String,
    ktext_string: String,
    txtsp_string: String,
    abdat_string: String,
    @Decimal(4, 0) abanz_decimal_4_0: BigDecimal,
    profidnetz_string: String,
    kokrs_string: String,
    qvewerks_string: String,
    qvemenge_string: String,
    qveversion_string: String,
    qvedatum_string: String,
    qvegruppe_string: String,
    qvecode_string: String,
    qdynregel_string: String,
    qdynhead_string: String,
    qprziehver_string: String,
    qversnprzv_string: String,
    qkzraster_string: String,
    qdynstring_string: String,
    strat_string: String,
    ppool_string: String,
    istru_string: String,
    iwerk_string: String,
    anlzu_string: String,
    arbid_string: String,
    extnum_string: String,
    delkz_string: String,
    arbty_string: String,
    stupr_string: String,
    clndr_string: String,
    prtyp_string: String,
    reodat_string: String,
    netid_string: String,
    flg_chk_string: String,
    pspnr_string: String,
    ttras_string: String,
    kzkfg_string: String,
    plnnr_alt_string: String,
    flg_capo_string: String,
    stlty_string: String,
    stlnr_string: String,
    stlal_string: String,
    slwbez_string: String,
    ppkztlzu_string: String,
    chrule_string: String,
    ccoaa_string: String,
    st_arbid_string: String,
    meinh_string: String,
    @Decimal(5, 0) umrez_decimal_5_0: BigDecimal,
    @Decimal(5, 0) umren_decimal_5_0: BigDecimal,
    @Decimal(13, 3) bmsch_decimal_13_3: BigDecimal,
    adpsp_string: String,
    ms_flag_string: String,
    @Decimal(16, 0) tstmp_bw_decimal_16_0: BigDecimal,
    mes_routingid_string: String,
    xhiertl_string: String,
    tl_extid_string: String
) extends Entity

object plko
    extends TableSpec[E_plko](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.Columns("_mk_instance", "_mk_partition", "_mk_file"),
      timetravelDays = 35
    )
    with Loaded
// LOADED TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_plko(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val mandt_string: ColumnWithName = ColumnWithName(prefix + "mandt_string")
  val plnty_string: ColumnWithName = ColumnWithName(prefix + "plnty_string")
  val plnnr_string: ColumnWithName = ColumnWithName(prefix + "plnnr_string")
  val plnal_string: ColumnWithName = ColumnWithName(prefix + "plnal_string")
  val zaehl_string: ColumnWithName = ColumnWithName(prefix + "zaehl_string")
  val datuv_string: ColumnWithName = ColumnWithName(prefix + "datuv_string")
  val techv_string: ColumnWithName = ColumnWithName(prefix + "techv_string")
  val aennr_string: ColumnWithName = ColumnWithName(prefix + "aennr_string")
  val loekz_string: ColumnWithName = ColumnWithName(prefix + "loekz_string")
  val parkz_string: ColumnWithName = ColumnWithName(prefix + "parkz_string")
  val andat_string: ColumnWithName = ColumnWithName(prefix + "andat_string")
  val annam_string: ColumnWithName = ColumnWithName(prefix + "annam_string")
  val aedat_string: ColumnWithName = ColumnWithName(prefix + "aedat_string")
  val aenam_string: ColumnWithName = ColumnWithName(prefix + "aenam_string")
  val verwe_string: ColumnWithName = ColumnWithName(prefix + "verwe_string")
  val werks_string: ColumnWithName = ColumnWithName(prefix + "werks_string")
  val statu_string: ColumnWithName = ColumnWithName(prefix + "statu_string")
  val plnme_string: ColumnWithName = ColumnWithName(prefix + "plnme_string")
  val losvn_decimal_13_3: ColumnWithName = ColumnWithName(prefix + "losvn_decimal_13_3")
  val losbs_decimal_13_3: ColumnWithName = ColumnWithName(prefix + "losbs_decimal_13_3")
  val vagrp_string: ColumnWithName = ColumnWithName(prefix + "vagrp_string")
  val aeszn_string: ColumnWithName = ColumnWithName(prefix + "aeszn_string")
  val ktext_string: ColumnWithName = ColumnWithName(prefix + "ktext_string")
  val txtsp_string: ColumnWithName = ColumnWithName(prefix + "txtsp_string")
  val abdat_string: ColumnWithName = ColumnWithName(prefix + "abdat_string")
  val abanz_decimal_4_0: ColumnWithName = ColumnWithName(prefix + "abanz_decimal_4_0")
  val profidnetz_string: ColumnWithName = ColumnWithName(prefix + "profidnetz_string")
  val kokrs_string: ColumnWithName = ColumnWithName(prefix + "kokrs_string")
  val qvewerks_string: ColumnWithName = ColumnWithName(prefix + "qvewerks_string")
  val qvemenge_string: ColumnWithName = ColumnWithName(prefix + "qvemenge_string")
  val qveversion_string: ColumnWithName = ColumnWithName(prefix + "qveversion_string")
  val qvedatum_string: ColumnWithName = ColumnWithName(prefix + "qvedatum_string")
  val qvegruppe_string: ColumnWithName = ColumnWithName(prefix + "qvegruppe_string")
  val qvecode_string: ColumnWithName = ColumnWithName(prefix + "qvecode_string")
  val qdynregel_string: ColumnWithName = ColumnWithName(prefix + "qdynregel_string")
  val qdynhead_string: ColumnWithName = ColumnWithName(prefix + "qdynhead_string")
  val qprziehver_string: ColumnWithName = ColumnWithName(prefix + "qprziehver_string")
  val qversnprzv_string: ColumnWithName = ColumnWithName(prefix + "qversnprzv_string")
  val qkzraster_string: ColumnWithName = ColumnWithName(prefix + "qkzraster_string")
  val qdynstring_string: ColumnWithName = ColumnWithName(prefix + "qdynstring_string")
  val strat_string: ColumnWithName = ColumnWithName(prefix + "strat_string")
  val ppool_string: ColumnWithName = ColumnWithName(prefix + "ppool_string")
  val istru_string: ColumnWithName = ColumnWithName(prefix + "istru_string")
  val iwerk_string: ColumnWithName = ColumnWithName(prefix + "iwerk_string")
  val anlzu_string: ColumnWithName = ColumnWithName(prefix + "anlzu_string")
  val arbid_string: ColumnWithName = ColumnWithName(prefix + "arbid_string")
  val extnum_string: ColumnWithName = ColumnWithName(prefix + "extnum_string")
  val delkz_string: ColumnWithName = ColumnWithName(prefix + "delkz_string")
  val arbty_string: ColumnWithName = ColumnWithName(prefix + "arbty_string")
  val stupr_string: ColumnWithName = ColumnWithName(prefix + "stupr_string")
  val clndr_string: ColumnWithName = ColumnWithName(prefix + "clndr_string")
  val prtyp_string: ColumnWithName = ColumnWithName(prefix + "prtyp_string")
  val reodat_string: ColumnWithName = ColumnWithName(prefix + "reodat_string")
  val netid_string: ColumnWithName = ColumnWithName(prefix + "netid_string")
  val flg_chk_string: ColumnWithName = ColumnWithName(prefix + "flg_chk_string")
  val pspnr_string: ColumnWithName = ColumnWithName(prefix + "pspnr_string")
  val ttras_string: ColumnWithName = ColumnWithName(prefix + "ttras_string")
  val kzkfg_string: ColumnWithName = ColumnWithName(prefix + "kzkfg_string")
  val plnnr_alt_string: ColumnWithName = ColumnWithName(prefix + "plnnr_alt_string")
  val flg_capo_string: ColumnWithName = ColumnWithName(prefix + "flg_capo_string")
  val stlty_string: ColumnWithName = ColumnWithName(prefix + "stlty_string")
  val stlnr_string: ColumnWithName = ColumnWithName(prefix + "stlnr_string")
  val stlal_string: ColumnWithName = ColumnWithName(prefix + "stlal_string")
  val slwbez_string: ColumnWithName = ColumnWithName(prefix + "slwbez_string")
  val ppkztlzu_string: ColumnWithName = ColumnWithName(prefix + "ppkztlzu_string")
  val chrule_string: ColumnWithName = ColumnWithName(prefix + "chrule_string")
  val ccoaa_string: ColumnWithName = ColumnWithName(prefix + "ccoaa_string")
  val st_arbid_string: ColumnWithName = ColumnWithName(prefix + "st_arbid_string")
  val meinh_string: ColumnWithName = ColumnWithName(prefix + "meinh_string")
  val umrez_decimal_5_0: ColumnWithName = ColumnWithName(prefix + "umrez_decimal_5_0")
  val umren_decimal_5_0: ColumnWithName = ColumnWithName(prefix + "umren_decimal_5_0")
  val bmsch_decimal_13_3: ColumnWithName = ColumnWithName(prefix + "bmsch_decimal_13_3")
  val adpsp_string: ColumnWithName = ColumnWithName(prefix + "adpsp_string")
  val ms_flag_string: ColumnWithName = ColumnWithName(prefix + "ms_flag_string")
  val tstmp_bw_decimal_16_0: ColumnWithName = ColumnWithName(prefix + "tstmp_bw_decimal_16_0")
  val mes_routingid_string: ColumnWithName = ColumnWithName(prefix + "mes_routingid_string")
  val xhiertl_string: ColumnWithName = ColumnWithName(prefix + "xhiertl_string")
  val tl_extid_string: ColumnWithName = ColumnWithName(prefix + "tl_extid_string")
}

object C_plko extends C_plko("") {
  def as(alias: String): C_plko = new C_plko(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
