package ct.dna.lakehouse.sr_raw.ct_gbl_p43
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

@LakehouseEntity
case class t001w_E(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    vkorg_string: String,
    sourcing_string: String,
    regio_string: String,
    j_1bbranch_string: String,
    werks_string: String,
    vtweg_string: String,
    kkowk_string: String,
    stras_string: String,
    pkosa_string: String,
    counc_string: String,
    pfach_string: String,
    mgvlareval_string: String,
    spras_string: String,
    taxiw_string: String,
    bedpl_string: String,
    mgvupd_string: String,
    fsh_mg_arun_req_string: String,
    kordb_string: String,
    bzqhl_string: String,
    name1_string: String,
    vstel_string: String,
    txnam_ma2_string: String,
    vlfkz_string: String,
    txnam_ma1_string: String,
    oihcredipi_string: String,
    @Decimal(3, 0) let03_decimal_3_0: BigDecimal,
    misch_string: String,
    wksop_string: String,
    land1_string: String,
    nodetype_string: String,
    storetype_string: String,
    bzirk_string: String,
    bwkey_string: String,
    fabkl_string: String,
    fsh_seaim_string: String,
    cityc_string: String,
    mandt_string: String,
    zone1_string: String,
    nschema_string: String,
    txjcd_string: String,
    @Decimal(3, 0) let02_decimal_3_0: BigDecimal,
    adrnr_string: String,
    ekorg_string: String,
    dvsart_string: String,
    vtbfi_string: String,
    chazv_string: String,
    fprfw_string: String,
    chazv_old_string: String,
    spart_string: String,
    oihvtype_string: String,
    betol_string: String,
    sgt_stat_string: String,
    fsh_bom_maintenance_string: String,
    pstlz_string: String,
    oilival_string: String,
    name2_string: String,
    @Decimal(3, 0) let01_decimal_3_0: BigDecimal,
    iwerk_string: String,
    ort01_string: String,
    lifnr_string: String,
    awsls_string: String,
    mgvlaupd_string: String,
    kunnr_string: String,
    achvm_string: String,
    dep_store_string: String,
    txnam_ma3_string: String
) extends Entity

object t001w
    extends TableSpec[t001w_E](
      enableChangeDataFeed = true,
      manualClusterBy = None,
      timetravelDays = 35
    )
    with Loaded
