// LOADED TABLE SPEC AUTO GENERATED:START
// Generated by LoadedTableSpecAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr_raw.ct_gbl_p43

import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.Loaded
import ct.dna.lakehouse.core.model.TableSpec

case class E_t415s(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt_string: String,
    stlst_string: String,
    kzbdp_string: String,
    kzpaf_string: String,
    kzklf_string: String,
    kzapf_string: String,
    kzauf_string: String,
    kzsme_string: String,
    kzrva_string: String,
    kzams_string: String,
    dlock_string: String,
    auprf_string: String
) extends Entity

object t415s
    extends TableSpec[E_t415s](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.Columns("_mk_instance", "_mk_partition", "_mk_file"),
      timetravelDays = 35
    )
    with Loaded
// LOADED TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_t415s(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val mandt_string: ColumnWithName = ColumnWithName(prefix + "mandt_string")
  val stlst_string: ColumnWithName = ColumnWithName(prefix + "stlst_string")
  val kzbdp_string: ColumnWithName = ColumnWithName(prefix + "kzbdp_string")
  val kzpaf_string: ColumnWithName = ColumnWithName(prefix + "kzpaf_string")
  val kzklf_string: ColumnWithName = ColumnWithName(prefix + "kzklf_string")
  val kzapf_string: ColumnWithName = ColumnWithName(prefix + "kzapf_string")
  val kzauf_string: ColumnWithName = ColumnWithName(prefix + "kzauf_string")
  val kzsme_string: ColumnWithName = ColumnWithName(prefix + "kzsme_string")
  val kzrva_string: ColumnWithName = ColumnWithName(prefix + "kzrva_string")
  val kzams_string: ColumnWithName = ColumnWithName(prefix + "kzams_string")
  val dlock_string: ColumnWithName = ColumnWithName(prefix + "dlock_string")
  val auprf_string: ColumnWithName = ColumnWithName(prefix + "auprf_string")
}

object C_t415s extends C_t415s("") {
  def as(alias: String): C_t415s = new C_t415s(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
