// AUTO GENERATED CODE - DO NOT EDIT
package ct.dna.lakehouse.catalog.sr_raw.ct_it_test

import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

case class E_ivanti_cvdetected(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    patch_string: String,
    found_string: String,
    cvdetected_idn_long: BoxedLong,
    numinstalltries_long: BoxedLong,
    patchdetected_long: BoxedLong,
    datedetected_string: String,
    patchinstallsucceeded_long: BoxedLong,
    computer_idn_long: BoxedLong,
    expected_string: String,
    reason_string: String,
    _sourceinstance_string: String,
    _sourcehost_string: String,
    vulnerability_idn_long: BoxedLong,
    _sourcedb_string: String,
    _sourceport_long: BoxedLong,
    coreguid_string: String
) extends Entity

object ivanti_cvdetected extends TableSpec[E_ivanti_cvdetected](enableChangeDataFeed = true, manualClusterBy = None, timetravelDays = 35) with Loaded

// AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY

import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_ivanti_cvdetected(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val patch_string: ColumnWithName = ColumnWithName(prefix + "patch_string")
  val found_string: ColumnWithName = ColumnWithName(prefix + "found_string")
  val cvdetected_idn_long: ColumnWithName = ColumnWithName(prefix + "cvdetected_idn_long")
  val numinstalltries_long: ColumnWithName = ColumnWithName(prefix + "numinstalltries_long")
  val patchdetected_long: ColumnWithName = ColumnWithName(prefix + "patchdetected_long")
  val datedetected_string: ColumnWithName = ColumnWithName(prefix + "datedetected_string")
  val patchinstallsucceeded_long: ColumnWithName = ColumnWithName(prefix + "patchinstallsucceeded_long")
  val computer_idn_long: ColumnWithName = ColumnWithName(prefix + "computer_idn_long")
  val expected_string: ColumnWithName = ColumnWithName(prefix + "expected_string")
  val reason_string: ColumnWithName = ColumnWithName(prefix + "reason_string")
  val _sourceinstance_string: ColumnWithName = ColumnWithName(prefix + "_sourceinstance_string")
  val _sourcehost_string: ColumnWithName = ColumnWithName(prefix + "_sourcehost_string")
  val vulnerability_idn_long: ColumnWithName = ColumnWithName(prefix + "vulnerability_idn_long")
  val _sourcedb_string: ColumnWithName = ColumnWithName(prefix + "_sourcedb_string")
  val _sourceport_long: ColumnWithName = ColumnWithName(prefix + "_sourceport_long")
  val coreguid_string: ColumnWithName = ColumnWithName(prefix + "coreguid_string")
}

object C_ivanti_cvdetected extends C_ivanti_cvdetected("") {
  def as(alias: String): C_ivanti_cvdetected = new C_ivanti_cvdetected(alias + ".")
}

// AUTO GENERATED:END
