// AUTO GENERATED CODE - DO NOT EDIT
package ct.dna.lakehouse.catalog.sr_raw.ct_it_test

import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

case class E_ivanti_metaattributes(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    length_long: BoxedLong,
    def_string: String,
    cht_string: String,
    chs_string: String,
    rus_string: String,
    _sourceinstance_string: String,
    _sourcehost_string: String,
    enu_string: String,
    attrname_string: String,
    fra_string: String,
    kor_string: String,
    deu_string: String,
    displaymask_string: String,
    ptb_string: String,
    datatype_string: String,
    esp_string: String,
    _sourcedb_string: String,
    _sourceport_long: BoxedLong,
    jpn_string: String,
    metaattributes_idn_long: BoxedLong,
    coreguid_string: String
) extends Entity

object ivanti_metaattributes extends TableSpec[E_ivanti_metaattributes](enableChangeDataFeed = true, manualClusterBy = None, timetravelDays = 35) with Loaded

// AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY

import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_ivanti_metaattributes(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val length_long: ColumnWithName = ColumnWithName(prefix + "length_long")
  val def_string: ColumnWithName = ColumnWithName(prefix + "def_string")
  val cht_string: ColumnWithName = ColumnWithName(prefix + "cht_string")
  val chs_string: ColumnWithName = ColumnWithName(prefix + "chs_string")
  val rus_string: ColumnWithName = ColumnWithName(prefix + "rus_string")
  val _sourceinstance_string: ColumnWithName = ColumnWithName(prefix + "_sourceinstance_string")
  val _sourcehost_string: ColumnWithName = ColumnWithName(prefix + "_sourcehost_string")
  val enu_string: ColumnWithName = ColumnWithName(prefix + "enu_string")
  val attrname_string: ColumnWithName = ColumnWithName(prefix + "attrname_string")
  val fra_string: ColumnWithName = ColumnWithName(prefix + "fra_string")
  val kor_string: ColumnWithName = ColumnWithName(prefix + "kor_string")
  val deu_string: ColumnWithName = ColumnWithName(prefix + "deu_string")
  val displaymask_string: ColumnWithName = ColumnWithName(prefix + "displaymask_string")
  val ptb_string: ColumnWithName = ColumnWithName(prefix + "ptb_string")
  val datatype_string: ColumnWithName = ColumnWithName(prefix + "datatype_string")
  val esp_string: ColumnWithName = ColumnWithName(prefix + "esp_string")
  val _sourcedb_string: ColumnWithName = ColumnWithName(prefix + "_sourcedb_string")
  val _sourceport_long: ColumnWithName = ColumnWithName(prefix + "_sourceport_long")
  val jpn_string: ColumnWithName = ColumnWithName(prefix + "jpn_string")
  val metaattributes_idn_long: ColumnWithName = ColumnWithName(prefix + "metaattributes_idn_long")
  val coreguid_string: ColumnWithName = ColumnWithName(prefix + "coreguid_string")
}

object C_ivanti_metaattributes extends C_ivanti_metaattributes("") {
  def as(alias: String): C_ivanti_metaattributes = new C_ivanti_metaattributes(alias + ".")
}

// AUTO GENERATED:END
