// AUTO GENERATED CODE - DO NOT EDIT
package ct.dna.lakehouse.catalog.sr_raw.ct_it_test

import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

case class E_ivanti_fixeddrives(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    deviceid_string: String,
    _sourcehost_string: String,
    storagetotal_long: BoxedLong,
    name_string: String,
    capabilities_long: BoxedLong,
    bytespersect_long: BoxedLong,
    manufacturer_string: String,
    sed_string: String,
    vendordesc_string: String,
    driveno_long: BoxedLong,
    sectors_long: BoxedLong,
    _sourceinstance_string: String,
    partitions_long: BoxedLong,
    trackspercylinder_long: BoxedLong,
    cmosramtype_string: String,
    drivetype_string: String,
    totaltracks_long: BoxedLong,
    mediatype_string: String,
    cylinders_long: BoxedLong,
    caption_string: String,
    bustype_string: String,
    diskindex_long: BoxedLong,
    fde_string: String,
    fixeddrives_idn_long: BoxedLong,
    heads_long: BoxedLong,
    model_string: String,
    totalsectors_long: BoxedLong,
    healthstatus_string: String,
    computer_idn_long: BoxedLong,
    interface_string: String,
    firmwarerev_string: String,
    serialnumber_string: String,
    _sourcedb_string: String,
    _sourceport_long: BoxedLong,
    coreguid_string: String
) extends Entity

object ivanti_fixeddrives extends TableSpec[E_ivanti_fixeddrives](enableChangeDataFeed = true, manualClusterBy = None, timetravelDays = 35) with Loaded

// AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY

import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_ivanti_fixeddrives(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val deviceid_string: ColumnWithName = ColumnWithName(prefix + "deviceid_string")
  val _sourcehost_string: ColumnWithName = ColumnWithName(prefix + "_sourcehost_string")
  val storagetotal_long: ColumnWithName = ColumnWithName(prefix + "storagetotal_long")
  val name_string: ColumnWithName = ColumnWithName(prefix + "name_string")
  val capabilities_long: ColumnWithName = ColumnWithName(prefix + "capabilities_long")
  val bytespersect_long: ColumnWithName = ColumnWithName(prefix + "bytespersect_long")
  val manufacturer_string: ColumnWithName = ColumnWithName(prefix + "manufacturer_string")
  val sed_string: ColumnWithName = ColumnWithName(prefix + "sed_string")
  val vendordesc_string: ColumnWithName = ColumnWithName(prefix + "vendordesc_string")
  val driveno_long: ColumnWithName = ColumnWithName(prefix + "driveno_long")
  val sectors_long: ColumnWithName = ColumnWithName(prefix + "sectors_long")
  val _sourceinstance_string: ColumnWithName = ColumnWithName(prefix + "_sourceinstance_string")
  val partitions_long: ColumnWithName = ColumnWithName(prefix + "partitions_long")
  val trackspercylinder_long: ColumnWithName = ColumnWithName(prefix + "trackspercylinder_long")
  val cmosramtype_string: ColumnWithName = ColumnWithName(prefix + "cmosramtype_string")
  val drivetype_string: ColumnWithName = ColumnWithName(prefix + "drivetype_string")
  val totaltracks_long: ColumnWithName = ColumnWithName(prefix + "totaltracks_long")
  val mediatype_string: ColumnWithName = ColumnWithName(prefix + "mediatype_string")
  val cylinders_long: ColumnWithName = ColumnWithName(prefix + "cylinders_long")
  val caption_string: ColumnWithName = ColumnWithName(prefix + "caption_string")
  val bustype_string: ColumnWithName = ColumnWithName(prefix + "bustype_string")
  val diskindex_long: ColumnWithName = ColumnWithName(prefix + "diskindex_long")
  val fde_string: ColumnWithName = ColumnWithName(prefix + "fde_string")
  val fixeddrives_idn_long: ColumnWithName = ColumnWithName(prefix + "fixeddrives_idn_long")
  val heads_long: ColumnWithName = ColumnWithName(prefix + "heads_long")
  val model_string: ColumnWithName = ColumnWithName(prefix + "model_string")
  val totalsectors_long: ColumnWithName = ColumnWithName(prefix + "totalsectors_long")
  val healthstatus_string: ColumnWithName = ColumnWithName(prefix + "healthstatus_string")
  val computer_idn_long: ColumnWithName = ColumnWithName(prefix + "computer_idn_long")
  val interface_string: ColumnWithName = ColumnWithName(prefix + "interface_string")
  val firmwarerev_string: ColumnWithName = ColumnWithName(prefix + "firmwarerev_string")
  val serialnumber_string: ColumnWithName = ColumnWithName(prefix + "serialnumber_string")
  val _sourcedb_string: ColumnWithName = ColumnWithName(prefix + "_sourcedb_string")
  val _sourceport_long: ColumnWithName = ColumnWithName(prefix + "_sourceport_long")
  val coreguid_string: ColumnWithName = ColumnWithName(prefix + "coreguid_string")
}

object C_ivanti_fixeddrives extends C_ivanti_fixeddrives("") {
  def as(alias: String): C_ivanti_fixeddrives = new C_ivanti_fixeddrives(alias + ".")
}

// AUTO GENERATED:END
