// AUTO GENERATED CODE - DO NOT EDIT
package ct.dna.lakehouse.catalog.sr_raw.ct_it_test

import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

case class E_microsoft_intune_managed_devices(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    managementagent_string: String,
    exchangeaccessstatereason_string: String,
    isencrypted_boolean: BoxedBoolean,
    androidsecuritypatchlevel_string: String,
    exchangelastsuccessfulsyncdatetime_string: String,
    imei_string: String,
    totalstoragespaceinbytes_long: BoxedLong,
    contains_masked_personal_data_boolean: BoxedBoolean,
    lastsyncdatetime_string: String,
    easactivationdatetime_string: String,
    userdisplayname_string: String,
    osversion_string: String,
    devicename_string: String,
    managementstate_string: String,
    managementcertificateexpirationdate_string: String,
    azureaddeviceid_string: String,
    userprincipalname_string: String,
    issupervised_boolean: BoxedBoolean,
    compliancestate_string: String,
    devicecategorydisplayname_string: String,
    requireuserenrollmentapproval_boolean: BoxedBoolean,
    jailbroken_string: String,
    manufacturer_string: String,
    meid_string: String,
    wifimacaddress_string: String,
    id_string: String,
    enrolleddatetime_string: String,
    easdeviceid_string: String,
    manageddevicename_string: String,
    model_string: String,
    userid_string: String,
    freestoragespaceinbytes_long: BoxedLong,
    subscribercarrier_string: String,
    manageddeviceownertype_string: String,
    azureadregistered_boolean: BoxedBoolean,
    compliancegraceperiodexpirationdatetime_string: String,
    deviceenrollmenttype_string: String,
    easactivated_boolean: BoxedBoolean,
    serialnumber_string: String,
    physicalmemoryinbytes_long: BoxedLong,
    phonenumber_string: String,
    partnerreportedthreatstate_string: String,
    exchangeaccessstate_string: String,
    deviceregistrationstate_string: String,
    operatingsystem_string: String,
    emailaddress_string: String
) extends Entity

object microsoft_intune_managed_devices
    extends TableSpec[E_microsoft_intune_managed_devices](enableChangeDataFeed = true, manualClusterBy = None, timetravelDays = 35)
    with Loaded

// AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY

import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_microsoft_intune_managed_devices(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val managementagent_string: ColumnWithName = ColumnWithName(prefix + "managementagent_string")
  val exchangeaccessstatereason_string: ColumnWithName = ColumnWithName(prefix + "exchangeaccessstatereason_string")
  val isencrypted_boolean: ColumnWithName = ColumnWithName(prefix + "isencrypted_boolean")
  val androidsecuritypatchlevel_string: ColumnWithName = ColumnWithName(prefix + "androidsecuritypatchlevel_string")
  val exchangelastsuccessfulsyncdatetime_string: ColumnWithName = ColumnWithName(prefix + "exchangelastsuccessfulsyncdatetime_string")
  val imei_string: ColumnWithName = ColumnWithName(prefix + "imei_string")
  val totalstoragespaceinbytes_long: ColumnWithName = ColumnWithName(prefix + "totalstoragespaceinbytes_long")
  val contains_masked_personal_data_boolean: ColumnWithName = ColumnWithName(prefix + "contains_masked_personal_data_boolean")
  val lastsyncdatetime_string: ColumnWithName = ColumnWithName(prefix + "lastsyncdatetime_string")
  val easactivationdatetime_string: ColumnWithName = ColumnWithName(prefix + "easactivationdatetime_string")
  val userdisplayname_string: ColumnWithName = ColumnWithName(prefix + "userdisplayname_string")
  val osversion_string: ColumnWithName = ColumnWithName(prefix + "osversion_string")
  val devicename_string: ColumnWithName = ColumnWithName(prefix + "devicename_string")
  val managementstate_string: ColumnWithName = ColumnWithName(prefix + "managementstate_string")
  val managementcertificateexpirationdate_string: ColumnWithName = ColumnWithName(prefix + "managementcertificateexpirationdate_string")
  val azureaddeviceid_string: ColumnWithName = ColumnWithName(prefix + "azureaddeviceid_string")
  val userprincipalname_string: ColumnWithName = ColumnWithName(prefix + "userprincipalname_string")
  val issupervised_boolean: ColumnWithName = ColumnWithName(prefix + "issupervised_boolean")
  val compliancestate_string: ColumnWithName = ColumnWithName(prefix + "compliancestate_string")
  val devicecategorydisplayname_string: ColumnWithName = ColumnWithName(prefix + "devicecategorydisplayname_string")
  val requireuserenrollmentapproval_boolean: ColumnWithName = ColumnWithName(prefix + "requireuserenrollmentapproval_boolean")
  val jailbroken_string: ColumnWithName = ColumnWithName(prefix + "jailbroken_string")
  val manufacturer_string: ColumnWithName = ColumnWithName(prefix + "manufacturer_string")
  val meid_string: ColumnWithName = ColumnWithName(prefix + "meid_string")
  val wifimacaddress_string: ColumnWithName = ColumnWithName(prefix + "wifimacaddress_string")
  val id_string: ColumnWithName = ColumnWithName(prefix + "id_string")
  val enrolleddatetime_string: ColumnWithName = ColumnWithName(prefix + "enrolleddatetime_string")
  val easdeviceid_string: ColumnWithName = ColumnWithName(prefix + "easdeviceid_string")
  val manageddevicename_string: ColumnWithName = ColumnWithName(prefix + "manageddevicename_string")
  val model_string: ColumnWithName = ColumnWithName(prefix + "model_string")
  val userid_string: ColumnWithName = ColumnWithName(prefix + "userid_string")
  val freestoragespaceinbytes_long: ColumnWithName = ColumnWithName(prefix + "freestoragespaceinbytes_long")
  val subscribercarrier_string: ColumnWithName = ColumnWithName(prefix + "subscribercarrier_string")
  val manageddeviceownertype_string: ColumnWithName = ColumnWithName(prefix + "manageddeviceownertype_string")
  val azureadregistered_boolean: ColumnWithName = ColumnWithName(prefix + "azureadregistered_boolean")
  val compliancegraceperiodexpirationdatetime_string: ColumnWithName = ColumnWithName(prefix + "compliancegraceperiodexpirationdatetime_string")
  val deviceenrollmenttype_string: ColumnWithName = ColumnWithName(prefix + "deviceenrollmenttype_string")
  val easactivated_boolean: ColumnWithName = ColumnWithName(prefix + "easactivated_boolean")
  val serialnumber_string: ColumnWithName = ColumnWithName(prefix + "serialnumber_string")
  val physicalmemoryinbytes_long: ColumnWithName = ColumnWithName(prefix + "physicalmemoryinbytes_long")
  val phonenumber_string: ColumnWithName = ColumnWithName(prefix + "phonenumber_string")
  val partnerreportedthreatstate_string: ColumnWithName = ColumnWithName(prefix + "partnerreportedthreatstate_string")
  val exchangeaccessstate_string: ColumnWithName = ColumnWithName(prefix + "exchangeaccessstate_string")
  val deviceregistrationstate_string: ColumnWithName = ColumnWithName(prefix + "deviceregistrationstate_string")
  val operatingsystem_string: ColumnWithName = ColumnWithName(prefix + "operatingsystem_string")
  val emailaddress_string: ColumnWithName = ColumnWithName(prefix + "emailaddress_string")
}

object C_microsoft_intune_managed_devices extends C_microsoft_intune_managed_devices("") {
  def as(alias: String): C_microsoft_intune_managed_devices = new C_microsoft_intune_managed_devices(alias + ".")
}

// AUTO GENERATED:END
