// AUTO GENERATED CODE - DO NOT EDIT
package ct.dna.lakehouse.catalog.sr_raw.ct_gbl_ivanti

import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

case class E_bios(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    installeddate_string: String,
    firmwarerevision_string: String,
    assettag_string: String,
    hwattrs_string: String,
    univrom_string: String,
    monitorserial_string: String,
    smbiosver_string: String,
    romfamily_string: String,
    _sourceinstance_string: String,
    ideserial_string: String,
    _sourcehost_string: String,
    biosdate_string: String,
    sysmodnum_string: String,
    uefienabled_string: String,
    boardrevlevel_string: String,
    monitorvendorid_string: String,
    machid_string: String,
    systemname_string: String,
    monmanufacturer_string: String,
    bootromver_string: String,
    romsize_long: BoxedLong,
    manufacturer_string: String,
    systemserial_string: String,
    monitormfgweek_long: BoxedLong,
    securebootenabled_string: String,
    monitormfgyear_long: BoxedLong,
    swbundle_string: String,
    systemmodel_string: String,
    monitorsize_string: String,
    model_string: String,
    servicetag_string: String,
    idbytes_string: String,
    contains_masked_personal_data_boolean: BoxedBoolean,
    computer_idn_long: BoxedLong,
    sysmanufacturer_string: String,
    romfilever_string: String,
    _sourcedb_string: String,
    romversion_string: String,
    _sourceport_long: BoxedLong,
    copyright_string: String,
    serialnum_string: String,
    ordnum_string: String,
    monitormodel_string: String,
    coreguid_string: String
) extends Entity

object bios extends TableSpec[E_bios](enableChangeDataFeed = true, manualClusterBy = None, timetravelDays = 35) with Loaded

// AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY

import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_bios(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val installeddate_string: ColumnWithName = ColumnWithName(prefix + "installeddate_string")
  val firmwarerevision_string: ColumnWithName = ColumnWithName(prefix + "firmwarerevision_string")
  val assettag_string: ColumnWithName = ColumnWithName(prefix + "assettag_string")
  val hwattrs_string: ColumnWithName = ColumnWithName(prefix + "hwattrs_string")
  val univrom_string: ColumnWithName = ColumnWithName(prefix + "univrom_string")
  val monitorserial_string: ColumnWithName = ColumnWithName(prefix + "monitorserial_string")
  val smbiosver_string: ColumnWithName = ColumnWithName(prefix + "smbiosver_string")
  val romfamily_string: ColumnWithName = ColumnWithName(prefix + "romfamily_string")
  val _sourceinstance_string: ColumnWithName = ColumnWithName(prefix + "_sourceinstance_string")
  val ideserial_string: ColumnWithName = ColumnWithName(prefix + "ideserial_string")
  val _sourcehost_string: ColumnWithName = ColumnWithName(prefix + "_sourcehost_string")
  val biosdate_string: ColumnWithName = ColumnWithName(prefix + "biosdate_string")
  val sysmodnum_string: ColumnWithName = ColumnWithName(prefix + "sysmodnum_string")
  val uefienabled_string: ColumnWithName = ColumnWithName(prefix + "uefienabled_string")
  val boardrevlevel_string: ColumnWithName = ColumnWithName(prefix + "boardrevlevel_string")
  val monitorvendorid_string: ColumnWithName = ColumnWithName(prefix + "monitorvendorid_string")
  val machid_string: ColumnWithName = ColumnWithName(prefix + "machid_string")
  val systemname_string: ColumnWithName = ColumnWithName(prefix + "systemname_string")
  val monmanufacturer_string: ColumnWithName = ColumnWithName(prefix + "monmanufacturer_string")
  val bootromver_string: ColumnWithName = ColumnWithName(prefix + "bootromver_string")
  val romsize_long: ColumnWithName = ColumnWithName(prefix + "romsize_long")
  val manufacturer_string: ColumnWithName = ColumnWithName(prefix + "manufacturer_string")
  val systemserial_string: ColumnWithName = ColumnWithName(prefix + "systemserial_string")
  val monitormfgweek_long: ColumnWithName = ColumnWithName(prefix + "monitormfgweek_long")
  val securebootenabled_string: ColumnWithName = ColumnWithName(prefix + "securebootenabled_string")
  val monitormfgyear_long: ColumnWithName = ColumnWithName(prefix + "monitormfgyear_long")
  val swbundle_string: ColumnWithName = ColumnWithName(prefix + "swbundle_string")
  val systemmodel_string: ColumnWithName = ColumnWithName(prefix + "systemmodel_string")
  val monitorsize_string: ColumnWithName = ColumnWithName(prefix + "monitorsize_string")
  val model_string: ColumnWithName = ColumnWithName(prefix + "model_string")
  val servicetag_string: ColumnWithName = ColumnWithName(prefix + "servicetag_string")
  val idbytes_string: ColumnWithName = ColumnWithName(prefix + "idbytes_string")
  val contains_masked_personal_data_boolean: ColumnWithName = ColumnWithName(prefix + "contains_masked_personal_data_boolean")
  val computer_idn_long: ColumnWithName = ColumnWithName(prefix + "computer_idn_long")
  val sysmanufacturer_string: ColumnWithName = ColumnWithName(prefix + "sysmanufacturer_string")
  val romfilever_string: ColumnWithName = ColumnWithName(prefix + "romfilever_string")
  val _sourcedb_string: ColumnWithName = ColumnWithName(prefix + "_sourcedb_string")
  val romversion_string: ColumnWithName = ColumnWithName(prefix + "romversion_string")
  val _sourceport_long: ColumnWithName = ColumnWithName(prefix + "_sourceport_long")
  val copyright_string: ColumnWithName = ColumnWithName(prefix + "copyright_string")
  val serialnum_string: ColumnWithName = ColumnWithName(prefix + "serialnum_string")
  val ordnum_string: ColumnWithName = ColumnWithName(prefix + "ordnum_string")
  val monitormodel_string: ColumnWithName = ColumnWithName(prefix + "monitormodel_string")
  val coreguid_string: ColumnWithName = ColumnWithName(prefix + "coreguid_string")
}

object C_bios extends C_bios("") {
  def as(alias: String): C_bios = new C_bios(alias + ".")
}

// AUTO GENERATED:END
