// AUTO GENERATED CODE - DO NOT EDIT
package ct.dna.lakehouse.catalog.sr_raw.ct_gbl_ivanti

import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

case class E_customgroup(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    _sourcehost_string: String,
    syncenabled_long: BoxedLong,
    parentcustomgroup_idn_long: BoxedLong,
    guid_string: String,
    sourcecore_string: String,
    revision_long: BoxedLong,
    lastsaveddate_string: String,
    contains_masked_personal_data_boolean: BoxedBoolean,
    type_long: BoxedLong,
    lastsavedby_string: String,
    consoleuser_idn_long: BoxedLong,
    _sourceinstance_string: String,
    customgroup_idn_long: BoxedLong,
    notes_string: String,
    name_string: String,
    readonly_long: BoxedLong,
    _sourcedb_string: String,
    _sourceport_long: BoxedLong
) extends Entity

object customgroup extends TableSpec[E_customgroup](enableChangeDataFeed = true, manualClusterBy = None, timetravelDays = 35) with Loaded

// AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY

import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_customgroup(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val _sourcehost_string: ColumnWithName = ColumnWithName(prefix + "_sourcehost_string")
  val syncenabled_long: ColumnWithName = ColumnWithName(prefix + "syncenabled_long")
  val parentcustomgroup_idn_long: ColumnWithName = ColumnWithName(prefix + "parentcustomgroup_idn_long")
  val guid_string: ColumnWithName = ColumnWithName(prefix + "guid_string")
  val sourcecore_string: ColumnWithName = ColumnWithName(prefix + "sourcecore_string")
  val revision_long: ColumnWithName = ColumnWithName(prefix + "revision_long")
  val lastsaveddate_string: ColumnWithName = ColumnWithName(prefix + "lastsaveddate_string")
  val contains_masked_personal_data_boolean: ColumnWithName = ColumnWithName(prefix + "contains_masked_personal_data_boolean")
  val type_long: ColumnWithName = ColumnWithName(prefix + "type_long")
  val lastsavedby_string: ColumnWithName = ColumnWithName(prefix + "lastsavedby_string")
  val consoleuser_idn_long: ColumnWithName = ColumnWithName(prefix + "consoleuser_idn_long")
  val _sourceinstance_string: ColumnWithName = ColumnWithName(prefix + "_sourceinstance_string")
  val customgroup_idn_long: ColumnWithName = ColumnWithName(prefix + "customgroup_idn_long")
  val notes_string: ColumnWithName = ColumnWithName(prefix + "notes_string")
  val name_string: ColumnWithName = ColumnWithName(prefix + "name_string")
  val readonly_long: ColumnWithName = ColumnWithName(prefix + "readonly_long")
  val _sourcedb_string: ColumnWithName = ColumnWithName(prefix + "_sourcedb_string")
  val _sourceport_long: ColumnWithName = ColumnWithName(prefix + "_sourceport_long")
}

object C_customgroup extends C_customgroup("") {
  def as(alias: String): C_customgroup = new C_customgroup(alias + ".")
}

// AUTO GENERATED:END
