// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_p64

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_p64.{ekko => sr_raw_ekko}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrEkko(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK ebeln: String,
    bukrs: String,
    bstyp: String,
    bsart: String,
    bsakz: String,
    loekz: String,
    statu: String,
    aedat: String,
    ernam: String,
    pincr: String,
    lponr: String,
    lifnr: String,
    spras: String,
    zterm: String,
    @Decimal(3, 0) zbd1t: java.math.BigDecimal,
    @Decimal(3, 0) zbd2t: java.math.BigDecimal,
    @Decimal(3, 0) zbd3t: java.math.BigDecimal,
    @Decimal(5, 3) zbd1p: java.math.BigDecimal,
    @Decimal(5, 3) zbd2p: java.math.BigDecimal,
    ekorg: String,
    ekgrp: String,
    waers: String,
    @Decimal(9, 5) wkurs: java.math.BigDecimal,
    kufix: String,
    bedat: String,
    kdatb: String,
    kdate: String,
    bwbdt: String,
    angdt: String,
    bnddt: String,
    gwldt: String,
    ausnr: String,
    angnr: String,
    ihran: String,
    ihrez: String,
    verkf: String,
    telf1: String,
    llief: String,
    kunnr: String,
    konnr: String,
    abgru: String,
    autlf: String,
    weakt: String,
    reswk: String,
    lblif: String,
    inco1: String,
    inco2: String,
    @Decimal(15, 2) ktwrt: java.math.BigDecimal,
    submi: String,
    knumv: String,
    kalsm: String,
    stafo: String,
    lifre: String,
    exnum: String,
    unsez: String,
    logsy: String,
    upinc: String,
    stako: String,
    frggr: String,
    frgsx: String,
    frgke: String,
    frgzu: String,
    frgrl: String,
    lands: String,
    lphis: String,
    adrnr: String,
    stceg_l: String,
    stceg: String,
    absgr: String,
    addnr: String,
    kornr: String,
    memory: String,
    procstat: String,
    @Decimal(15, 2) rlwrt: java.math.BigDecimal,
    revno: String,
    scmproc: String,
    reason_code: String,
    memorytype: String,
    rettp: String,
    @Decimal(5, 2) retpc: java.math.BigDecimal,
    dptyp: String,
    @Decimal(5, 2) dppct: java.math.BigDecimal,
    @Decimal(11, 2) dpamt: java.math.BigDecimal,
    dpdat: String,
    msr_id: String,
    hierarchy_exists: String,
    threshold_exists: String,
    legal_contract: String,
    description: String,
    release_date: String,
    vsart: String,
    handoverloc: String,
    shipcond: String,
    incov: String,
    inco2_l: String,
    inco3_l: String,
    externalsystem: String,
    externalreferenceid: String,
    @Decimal(21, 7) ext_rev_tmstmp: java.math.BigDecimal,
    force_id: String,
    force_cnt: String,
    reloc_id: String,
    reloc_seq_id: String,
    source_logsys: String,
    fsh_transaction: String,
    fsh_item_group: String,
    fsh_vas_last_item: String,
    fsh_os_stg_change: String,
    plc: String,
    smb: String,
    ecc: String,
    ipp: String,
    cur: String,
    eco: String,
    pco: String,
    dpt: String,
    top: String,
    sus: String,
    pcn: String,
    tru: String,
    pcy: String,
    pcd: String,
    pbn: String,
    amn: String,
    dno: String,
    postat: String,
    vzskz: String,
    fsh_snst_status: String,
    pohf_type: String,
    eq_eindt: String,
    eq_werks: String,
    fixpo: String,
    ekgrp_allow: String,
    werks_allow: String,
    contract_allow: String,
    pstyp_allow: String,
    fixpo_allow: String,
    key_id_allow: String,
    aurel_allow: String,
    delper_allow: String,
    eindt_allow: String,
    ltsnr_allow: String,
    otb_level: String,
    otb_cond_type: String,
    key_id: String,
    @Decimal(17, 2) otb_value: java.math.BigDecimal,
    otb_curr: String,
    @Decimal(17, 2) otb_res_value: java.math.BigDecimal,
    @Decimal(17, 2) otb_spec_value: java.math.BigDecimal,
    spr_rsn_profile: String,
    budg_type: String,
    otb_status: String,
    otb_reason: String,
    check_type: String,
    con_otb_req: String,
    con_prebook_lev: String,
    con_distr_lev: String
) extends Entity

object ekko extends TableSpec[SrEkko] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_p64.E_ekko] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_p64.E_ekko] = sr_raw_ekko

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("ebeln", coalesce(col("ebeln_string"), lit(""))),
    ("bukrs", col("bukrs_string")),
    ("bstyp", col("bstyp_string")),
    ("bsart", col("bsart_string")),
    ("bsakz", col("bsakz_string")),
    ("loekz", col("loekz_string")),
    ("statu", col("statu_string")),
    ("aedat", col("aedat_string")),
    ("ernam", col("ernam_string")),
    ("pincr", col("pincr_string")),
    ("lponr", col("lponr_string")),
    ("lifnr", col("lifnr_string")),
    ("spras", col("spras_string")),
    ("zterm", col("zterm_string")),
    ("zbd1t", col("zbd1t_decimal_3_0")),
    ("zbd2t", col("zbd2t_decimal_3_0")),
    ("zbd3t", col("zbd3t_decimal_3_0")),
    ("zbd1p", col("zbd1p_decimal_5_3")),
    ("zbd2p", col("zbd2p_decimal_5_3")),
    ("ekorg", col("ekorg_string")),
    ("ekgrp", col("ekgrp_string")),
    ("waers", col("waers_string")),
    ("wkurs", col("wkurs_decimal_9_5")),
    ("kufix", col("kufix_string")),
    ("bedat", col("bedat_string")),
    ("kdatb", col("kdatb_string")),
    ("kdate", col("kdate_string")),
    ("bwbdt", col("bwbdt_string")),
    ("angdt", col("angdt_string")),
    ("bnddt", col("bnddt_string")),
    ("gwldt", col("gwldt_string")),
    ("ausnr", col("ausnr_string")),
    ("angnr", col("angnr_string")),
    ("ihran", col("ihran_string")),
    ("ihrez", col("ihrez_string")),
    ("verkf", col("verkf_string")),
    ("telf1", col("telf1_string")),
    ("llief", col("llief_string")),
    ("kunnr", col("kunnr_string")),
    ("konnr", col("konnr_string")),
    ("abgru", col("abgru_string")),
    ("autlf", col("autlf_string")),
    ("weakt", col("weakt_string")),
    ("reswk", col("reswk_string")),
    ("lblif", col("lblif_string")),
    ("inco1", col("inco1_string")),
    ("inco2", col("inco2_string")),
    ("ktwrt", col("ktwrt_decimal_15_2")),
    ("submi", col("submi_string")),
    ("knumv", col("knumv_string")),
    ("kalsm", col("kalsm_string")),
    ("stafo", col("stafo_string")),
    ("lifre", col("lifre_string")),
    ("exnum", col("exnum_string")),
    ("unsez", col("unsez_string")),
    ("logsy", col("logsy_string")),
    ("upinc", col("upinc_string")),
    ("stako", col("stako_string")),
    ("frggr", col("frggr_string")),
    ("frgsx", col("frgsx_string")),
    ("frgke", col("frgke_string")),
    ("frgzu", col("frgzu_string")),
    ("frgrl", col("frgrl_string")),
    ("lands", col("lands_string")),
    ("lphis", col("lphis_string")),
    ("adrnr", col("adrnr_string")),
    ("stceg_l", col("stceg_l_string")),
    ("stceg", col("stceg_string")),
    ("absgr", col("absgr_string")),
    ("addnr", col("addnr_string")),
    ("kornr", col("kornr_string")),
    ("memory", col("memory_string")),
    ("procstat", col("procstat_string")),
    ("rlwrt", col("rlwrt_decimal_15_2")),
    ("revno", col("revno_string")),
    ("scmproc", col("scmproc_string")),
    ("reason_code", col("reason_code_string")),
    ("memorytype", col("memorytype_string")),
    ("rettp", col("rettp_string")),
    ("retpc", col("retpc_decimal_5_2")),
    ("dptyp", col("dptyp_string")),
    ("dppct", col("dppct_decimal_5_2")),
    ("dpamt", col("dpamt_decimal_11_2")),
    ("dpdat", col("dpdat_string")),
    ("msr_id", col("msr_id_string")),
    ("hierarchy_exists", col("hierarchy_exists_string")),
    ("threshold_exists", col("threshold_exists_string")),
    ("legal_contract", col("legal_contract_string")),
    ("description", col("description_string")),
    ("release_date", col("release_date_string")),
    ("vsart", col("vsart_string")),
    ("handoverloc", col("handoverloc_string")),
    ("shipcond", col("shipcond_string")),
    ("incov", col("incov_string")),
    ("inco2_l", col("inco2_l_string")),
    ("inco3_l", col("inco3_l_string")),
    ("externalsystem", col("externalsystem_string")),
    ("externalreferenceid", col("externalreferenceid_string")),
    ("ext_rev_tmstmp", col("ext_rev_tmstmp_decimal_21_7")),
    ("force_id", col("force_id_string")),
    ("force_cnt", col("force_cnt_string")),
    ("reloc_id", col("reloc_id_string")),
    ("reloc_seq_id", col("reloc_seq_id_string")),
    ("source_logsys", col("source_logsys_string")),
    ("fsh_transaction", col("fsh_transaction_string")),
    ("fsh_item_group", col("fsh_item_group_string")),
    ("fsh_vas_last_item", col("fsh_vas_last_item_string")),
    ("fsh_os_stg_change", col("fsh_os_stg_change_string")),
    ("plc", col("plc_string")),
    ("smb", col("smb_string")),
    ("ecc", col("ecc_string")),
    ("ipp", col("ipp_string")),
    ("cur", col("cur_string")),
    ("eco", col("eco_string")),
    ("pco", col("pco_string")),
    ("dpt", col("dpt_string")),
    ("top", col("top_string")),
    ("sus", col("sus_string")),
    ("pcn", col("pcn_string")),
    ("tru", col("tru_string")),
    ("pcy", col("pcy_string")),
    ("pcd", col("pcd_string")),
    ("pbn", col("pbn_string")),
    ("amn", col("amn_string")),
    ("dno", col("dno_string")),
    ("postat", col("postat_string")),
    ("vzskz", col("vzskz_string")),
    ("fsh_snst_status", col("fsh_snst_status_string")),
    ("pohf_type", col("pohf_type_string")),
    ("eq_eindt", col("eq_eindt_string")),
    ("eq_werks", col("eq_werks_string")),
    ("fixpo", col("fixpo_string")),
    ("ekgrp_allow", col("ekgrp_allow_string")),
    ("werks_allow", col("werks_allow_string")),
    ("contract_allow", col("contract_allow_string")),
    ("pstyp_allow", col("pstyp_allow_string")),
    ("fixpo_allow", col("fixpo_allow_string")),
    ("key_id_allow", col("key_id_allow_string")),
    ("aurel_allow", col("aurel_allow_string")),
    ("delper_allow", col("delper_allow_string")),
    ("eindt_allow", col("eindt_allow_string")),
    ("ltsnr_allow", col("ltsnr_allow_string")),
    ("otb_level", col("otb_level_string")),
    ("otb_cond_type", col("otb_cond_type_string")),
    ("key_id", col("key_id_string")),
    ("otb_value", col("otb_value_decimal_17_2")),
    ("otb_curr", col("otb_curr_string")),
    ("otb_res_value", col("otb_res_value_decimal_17_2")),
    ("otb_spec_value", col("otb_spec_value_decimal_17_2")),
    ("spr_rsn_profile", col("spr_rsn_profile_string")),
    ("budg_type", col("budg_type_string")),
    ("otb_status", col("otb_status_string")),
    ("otb_reason", col("otb_reason_string")),
    ("check_type", col("check_type_string")),
    ("con_otb_req", col("con_otb_req_string")),
    ("con_prebook_lev", col("con_prebook_lev_string")),
    ("con_distr_lev", col("con_distr_lev_string"))
  )
}
