// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_p12

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_mast(
    @PK mandt: String,
    @PK matnr: String,
    @PK werks: String,
    @PK stlan: String,
    @PK stlnr: String,
    @PK stlal: String,
    @Decimal(13, 3) losvn: BigDecimal,
    @Decimal(13, 3) losbs: BigDecimal,
    andat: String,
    annam: String,
    aedat: String,
    aenam: String,
    cslty: String,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String
) extends Entity

object mast
    extends TableSpec[E_mast](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[sr_raw.ct_gbl_p12.E_mast] {
  override def sourceTableSpec: TableSpec[sr_raw.ct_gbl_p12.E_mast] = sr_raw.ct_gbl_p12.mast
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("mandt", col("mandt_string")),
    ("matnr", col("matnr_string")),
    ("werks", col("werks_string")),
    ("stlan", col("stlan_string")),
    ("stlnr", col("stlnr_string")),
    ("stlal", col("stlal_string")),
    ("losvn", col("losvn_decimal_13_3")),
    ("losbs", col("losbs_decimal_13_3")),
    ("andat", col("andat_string")),
    ("annam", col("annam_string")),
    ("aedat", col("aedat_string")),
    ("aenam", col("aenam_string")),
    ("cslty", col("cslty_string"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_mast(prefix: String) extends ColumnWithNameAccessor {
  val mandt: ColumnWithName = ColumnWithName(prefix + "mandt")
  val matnr: ColumnWithName = ColumnWithName(prefix + "matnr")
  val werks: ColumnWithName = ColumnWithName(prefix + "werks")
  val stlan: ColumnWithName = ColumnWithName(prefix + "stlan")
  val stlnr: ColumnWithName = ColumnWithName(prefix + "stlnr")
  val stlal: ColumnWithName = ColumnWithName(prefix + "stlal")
  val losvn: ColumnWithName = ColumnWithName(prefix + "losvn")
  val losbs: ColumnWithName = ColumnWithName(prefix + "losbs")
  val andat: ColumnWithName = ColumnWithName(prefix + "andat")
  val annam: ColumnWithName = ColumnWithName(prefix + "annam")
  val aedat: ColumnWithName = ColumnWithName(prefix + "aedat")
  val aenam: ColumnWithName = ColumnWithName(prefix + "aenam")
  val cslty: ColumnWithName = ColumnWithName(prefix + "cslty")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
}

object C_mast extends C_mast("") {
  def as(alias: String): C_mast = new C_mast(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
