// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_p73

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_ekbe(
    @PK mandt: String,
    @PK ebeln: String,
    @PK ebelp: String,
    @PK zekkn: String,
    @PK vgabe: String,
    @PK gjahr: String,
    @PK belnr: String,
    @PK buzei: String,
    bewtp: String,
    bwart: String,
    budat: String,
    @Decimal(13, 3) menge: BigDecimal,
    @Decimal(13, 3) bpmng: BigDecimal,
    @Decimal(13, 2) dmbtr: BigDecimal,
    @Decimal(13, 2) wrbtr: BigDecimal,
    waers: String,
    @Decimal(13, 2) arewr: BigDecimal,
    @Decimal(13, 3) wesbs: BigDecimal,
    @Decimal(13, 3) bpwes: BigDecimal,
    shkzg: String,
    bwtar: String,
    elikz: String,
    xblnr: String,
    lfgja: String,
    lfbnr: String,
    lfpos: String,
    grund: String,
    cpudt: String,
    cputm: String,
    @Decimal(13, 2) reewr: BigDecimal,
    evere: String,
    @Decimal(13, 2) refwr: BigDecimal,
    matnr: String,
    werks: String,
    xwsbr: String,
    etens: String,
    knumv: String,
    mwskz: String,
    @Decimal(13, 3) lsmng: BigDecimal,
    lsmeh: String,
    ematn: String,
    @Decimal(13, 2) areww: BigDecimal,
    hswae: String,
    @Decimal(13, 3) bamng: BigDecimal,
    charg: String,
    bldat: String,
    xwoff: String,
    xunpl: String,
    ernam: String,
    srvpos: String,
    packno: String,
    introw: String,
    bekkn: String,
    lemin: String,
    @Decimal(13, 2) arewb: BigDecimal,
    @Decimal(13, 2) rewrb: BigDecimal,
    saprl: String,
    @Decimal(13, 3) menge_pop: BigDecimal,
    @Decimal(13, 3) bpmng_pop: BigDecimal,
    @Decimal(13, 2) dmbtr_pop: BigDecimal,
    @Decimal(13, 2) wrbtr_pop: BigDecimal,
    @Decimal(13, 3) wesbb: BigDecimal,
    @Decimal(13, 3) bpweb: BigDecimal,
    weora: String,
    @Decimal(13, 2) arewr_pop: BigDecimal,
    @Decimal(13, 2) kudif: BigDecimal,
    @Decimal(13, 2) retamt_fc: BigDecimal,
    @Decimal(13, 2) retamt_lc: BigDecimal,
    @Decimal(13, 2) retamtp_fc: BigDecimal,
    @Decimal(13, 2) retamtp_lc: BigDecimal,
    xmacc: String,
    @Decimal(9, 5) wkurs: BigDecimal,
    inv_item_origin: String,
    vbeln_st: String,
    vbelp_st: String,
    sgt_scat: String,
    et_upd: String,
    j_sc_die_comp_f: String,
    @Decimal(13, 3) qty_diff: BigDecimal,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String
) extends Entity

object ekbe
    extends TableSpec[E_ekbe](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[sr_raw.ct_gbl_p73.E_ekbe] {
  override def sourceTableSpec: TableSpec[sr_raw.ct_gbl_p73.E_ekbe] = sr_raw.ct_gbl_p73.ekbe
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("mandt", col("mandt_string")),
    ("ebeln", col("ebeln_string")),
    ("ebelp", col("ebelp_string")),
    ("zekkn", col("zekkn_string")),
    ("vgabe", col("vgabe_string")),
    ("gjahr", col("gjahr_string")),
    ("belnr", col("belnr_string")),
    ("buzei", col("buzei_string")),
    ("bewtp", col("bewtp_string")),
    ("bwart", col("bwart_string")),
    ("budat", col("budat_string")),
    ("menge", col("menge_decimal_13_3")),
    ("bpmng", col("bpmng_decimal_13_3")),
    ("dmbtr", col("dmbtr_decimal_13_2")),
    ("wrbtr", col("wrbtr_decimal_13_2")),
    ("waers", col("waers_string")),
    ("arewr", col("arewr_decimal_13_2")),
    ("wesbs", col("wesbs_decimal_13_3")),
    ("bpwes", col("bpwes_decimal_13_3")),
    ("shkzg", col("shkzg_string")),
    ("bwtar", col("bwtar_string")),
    ("elikz", col("elikz_string")),
    ("xblnr", col("xblnr_string")),
    ("lfgja", col("lfgja_string")),
    ("lfbnr", col("lfbnr_string")),
    ("lfpos", col("lfpos_string")),
    ("grund", col("grund_string")),
    ("cpudt", col("cpudt_string")),
    ("cputm", col("cputm_string")),
    ("reewr", col("reewr_decimal_13_2")),
    ("evere", col("evere_string")),
    ("refwr", col("refwr_decimal_13_2")),
    ("matnr", col("matnr_string")),
    ("werks", col("werks_string")),
    ("xwsbr", col("xwsbr_string")),
    ("etens", col("etens_string")),
    ("knumv", col("knumv_string")),
    ("mwskz", col("mwskz_string")),
    ("lsmng", col("lsmng_decimal_13_3")),
    ("lsmeh", col("lsmeh_string")),
    ("ematn", col("ematn_string")),
    ("areww", col("areww_decimal_13_2")),
    ("hswae", col("hswae_string")),
    ("bamng", col("bamng_decimal_13_3")),
    ("charg", col("charg_string")),
    ("bldat", col("bldat_string")),
    ("xwoff", col("xwoff_string")),
    ("xunpl", col("xunpl_string")),
    ("ernam", col("ernam_string")),
    ("srvpos", col("srvpos_string")),
    ("packno", col("packno_string")),
    ("introw", col("introw_string")),
    ("bekkn", col("bekkn_string")),
    ("lemin", col("lemin_string")),
    ("arewb", col("arewb_decimal_13_2")),
    ("rewrb", col("rewrb_decimal_13_2")),
    ("saprl", col("saprl_string")),
    ("menge_pop", col("menge_pop_decimal_13_3")),
    ("bpmng_pop", col("bpmng_pop_decimal_13_3")),
    ("dmbtr_pop", col("dmbtr_pop_decimal_13_2")),
    ("wrbtr_pop", col("wrbtr_pop_decimal_13_2")),
    ("wesbb", col("wesbb_decimal_13_3")),
    ("bpweb", col("bpweb_decimal_13_3")),
    ("weora", col("weora_string")),
    ("arewr_pop", col("arewr_pop_decimal_13_2")),
    ("kudif", col("kudif_decimal_13_2")),
    ("retamt_fc", col("retamt_fc_decimal_13_2")),
    ("retamt_lc", col("retamt_lc_decimal_13_2")),
    ("retamtp_fc", col("retamtp_fc_decimal_13_2")),
    ("retamtp_lc", col("retamtp_lc_decimal_13_2")),
    ("xmacc", col("xmacc_string")),
    ("wkurs", col("wkurs_decimal_9_5")),
    ("inv_item_origin", col("inv_item_origin_string")),
    ("vbeln_st", col("vbeln_st_string")),
    ("vbelp_st", col("vbelp_st_string")),
    ("sgt_scat", col("sgt_scat_string")),
    ("et_upd", col("et_upd_string")),
    ("j_sc_die_comp_f", col("j_sc_die_comp_f_string")),
    ("qty_diff", col("qty_diff_decimal_13_3"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_ekbe(prefix: String) extends ColumnWithNameAccessor {
  val mandt: ColumnWithName = ColumnWithName(prefix + "mandt")
  val ebeln: ColumnWithName = ColumnWithName(prefix + "ebeln")
  val ebelp: ColumnWithName = ColumnWithName(prefix + "ebelp")
  val zekkn: ColumnWithName = ColumnWithName(prefix + "zekkn")
  val vgabe: ColumnWithName = ColumnWithName(prefix + "vgabe")
  val gjahr: ColumnWithName = ColumnWithName(prefix + "gjahr")
  val belnr: ColumnWithName = ColumnWithName(prefix + "belnr")
  val buzei: ColumnWithName = ColumnWithName(prefix + "buzei")
  val bewtp: ColumnWithName = ColumnWithName(prefix + "bewtp")
  val bwart: ColumnWithName = ColumnWithName(prefix + "bwart")
  val budat: ColumnWithName = ColumnWithName(prefix + "budat")
  val menge: ColumnWithName = ColumnWithName(prefix + "menge")
  val bpmng: ColumnWithName = ColumnWithName(prefix + "bpmng")
  val dmbtr: ColumnWithName = ColumnWithName(prefix + "dmbtr")
  val wrbtr: ColumnWithName = ColumnWithName(prefix + "wrbtr")
  val waers: ColumnWithName = ColumnWithName(prefix + "waers")
  val arewr: ColumnWithName = ColumnWithName(prefix + "arewr")
  val wesbs: ColumnWithName = ColumnWithName(prefix + "wesbs")
  val bpwes: ColumnWithName = ColumnWithName(prefix + "bpwes")
  val shkzg: ColumnWithName = ColumnWithName(prefix + "shkzg")
  val bwtar: ColumnWithName = ColumnWithName(prefix + "bwtar")
  val elikz: ColumnWithName = ColumnWithName(prefix + "elikz")
  val xblnr: ColumnWithName = ColumnWithName(prefix + "xblnr")
  val lfgja: ColumnWithName = ColumnWithName(prefix + "lfgja")
  val lfbnr: ColumnWithName = ColumnWithName(prefix + "lfbnr")
  val lfpos: ColumnWithName = ColumnWithName(prefix + "lfpos")
  val grund: ColumnWithName = ColumnWithName(prefix + "grund")
  val cpudt: ColumnWithName = ColumnWithName(prefix + "cpudt")
  val cputm: ColumnWithName = ColumnWithName(prefix + "cputm")
  val reewr: ColumnWithName = ColumnWithName(prefix + "reewr")
  val evere: ColumnWithName = ColumnWithName(prefix + "evere")
  val refwr: ColumnWithName = ColumnWithName(prefix + "refwr")
  val matnr: ColumnWithName = ColumnWithName(prefix + "matnr")
  val werks: ColumnWithName = ColumnWithName(prefix + "werks")
  val xwsbr: ColumnWithName = ColumnWithName(prefix + "xwsbr")
  val etens: ColumnWithName = ColumnWithName(prefix + "etens")
  val knumv: ColumnWithName = ColumnWithName(prefix + "knumv")
  val mwskz: ColumnWithName = ColumnWithName(prefix + "mwskz")
  val lsmng: ColumnWithName = ColumnWithName(prefix + "lsmng")
  val lsmeh: ColumnWithName = ColumnWithName(prefix + "lsmeh")
  val ematn: ColumnWithName = ColumnWithName(prefix + "ematn")
  val areww: ColumnWithName = ColumnWithName(prefix + "areww")
  val hswae: ColumnWithName = ColumnWithName(prefix + "hswae")
  val bamng: ColumnWithName = ColumnWithName(prefix + "bamng")
  val charg: ColumnWithName = ColumnWithName(prefix + "charg")
  val bldat: ColumnWithName = ColumnWithName(prefix + "bldat")
  val xwoff: ColumnWithName = ColumnWithName(prefix + "xwoff")
  val xunpl: ColumnWithName = ColumnWithName(prefix + "xunpl")
  val ernam: ColumnWithName = ColumnWithName(prefix + "ernam")
  val srvpos: ColumnWithName = ColumnWithName(prefix + "srvpos")
  val packno: ColumnWithName = ColumnWithName(prefix + "packno")
  val introw: ColumnWithName = ColumnWithName(prefix + "introw")
  val bekkn: ColumnWithName = ColumnWithName(prefix + "bekkn")
  val lemin: ColumnWithName = ColumnWithName(prefix + "lemin")
  val arewb: ColumnWithName = ColumnWithName(prefix + "arewb")
  val rewrb: ColumnWithName = ColumnWithName(prefix + "rewrb")
  val saprl: ColumnWithName = ColumnWithName(prefix + "saprl")
  val menge_pop: ColumnWithName = ColumnWithName(prefix + "menge_pop")
  val bpmng_pop: ColumnWithName = ColumnWithName(prefix + "bpmng_pop")
  val dmbtr_pop: ColumnWithName = ColumnWithName(prefix + "dmbtr_pop")
  val wrbtr_pop: ColumnWithName = ColumnWithName(prefix + "wrbtr_pop")
  val wesbb: ColumnWithName = ColumnWithName(prefix + "wesbb")
  val bpweb: ColumnWithName = ColumnWithName(prefix + "bpweb")
  val weora: ColumnWithName = ColumnWithName(prefix + "weora")
  val arewr_pop: ColumnWithName = ColumnWithName(prefix + "arewr_pop")
  val kudif: ColumnWithName = ColumnWithName(prefix + "kudif")
  val retamt_fc: ColumnWithName = ColumnWithName(prefix + "retamt_fc")
  val retamt_lc: ColumnWithName = ColumnWithName(prefix + "retamt_lc")
  val retamtp_fc: ColumnWithName = ColumnWithName(prefix + "retamtp_fc")
  val retamtp_lc: ColumnWithName = ColumnWithName(prefix + "retamtp_lc")
  val xmacc: ColumnWithName = ColumnWithName(prefix + "xmacc")
  val wkurs: ColumnWithName = ColumnWithName(prefix + "wkurs")
  val inv_item_origin: ColumnWithName = ColumnWithName(prefix + "inv_item_origin")
  val vbeln_st: ColumnWithName = ColumnWithName(prefix + "vbeln_st")
  val vbelp_st: ColumnWithName = ColumnWithName(prefix + "vbelp_st")
  val sgt_scat: ColumnWithName = ColumnWithName(prefix + "sgt_scat")
  val et_upd: ColumnWithName = ColumnWithName(prefix + "et_upd")
  val j_sc_die_comp_f: ColumnWithName = ColumnWithName(prefix + "j_sc_die_comp_f")
  val qty_diff: ColumnWithName = ColumnWithName(prefix + "qty_diff")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
}

object C_ekbe extends C_ekbe("") {
  def as(alias: String): C_ekbe = new C_ekbe(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
