// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_p73

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_ekpo_part1(
    @PK mandt: String,
    @PK ebeln: String,
    @PK ebelp: String,
    loekz: String,
    statu: String,
    aedat: String,
    txz01: String,
    matnr: String,
    ematn: String,
    bukrs: String,
    werks: String,
    lgort: String,
    bednr: String,
    matkl: String,
    infnr: String,
    idnlf: String,
    @Decimal(13, 3) ktmng: BigDecimal,
    @Decimal(13, 3) menge: BigDecimal,
    meins: String,
    bprme: String,
    @Decimal(5, 0) bpumz: BigDecimal,
    @Decimal(5, 0) bpumn: BigDecimal,
    @Decimal(5, 0) umrez: BigDecimal,
    @Decimal(5, 0) umren: BigDecimal,
    @Decimal(11, 2) netpr: BigDecimal,
    @Decimal(5, 0) peinh: BigDecimal,
    @Decimal(13, 2) netwr: BigDecimal,
    @Decimal(13, 2) brtwr: BigDecimal,
    agdat: String,
    @Decimal(3, 0) webaz: BigDecimal,
    mwskz: String,
    bonus: String,
    insmk: String,
    spinf: String,
    prsdr: String,
    schpr: String,
    @Decimal(3, 0) mahnz: BigDecimal,
    @Decimal(3, 0) mahn1: BigDecimal,
    @Decimal(3, 0) mahn2: BigDecimal,
    @Decimal(3, 0) mahn3: BigDecimal,
    @Decimal(3, 1) uebto: BigDecimal,
    uebtk: String,
    @Decimal(3, 1) untto: BigDecimal,
    bwtar: String,
    bwtty: String,
    abskz: String,
    agmem: String,
    elikz: String,
    erekz: String,
    pstyp: String,
    knttp: String,
    kzvbr: String,
    vrtkz: String,
    twrkz: String,
    wepos: String,
    weunb: String,
    repos: String,
    webre: String,
    kzabs: String,
    labnr: String,
    konnr: String,
    ktpnr: String,
    abdat: String,
    @Decimal(13, 3) abftz: BigDecimal,
    @Decimal(3, 0) etfz1: BigDecimal,
    @Decimal(3, 0) etfz2: BigDecimal,
    kzstu: String,
    notkz: String,
    lmein: String,
    evers: String,
    @Decimal(13, 2) zwert: BigDecimal,
    @Decimal(13, 2) navnw: BigDecimal,
    @Decimal(13, 3) abmng: BigDecimal,
    prdat: String,
    bstyp: String,
    @Decimal(13, 2) effwr: BigDecimal,
    xoblr: String,
    kunnr: String,
    adrnr: String,
    ekkol: String,
    sktof: String,
    stafo: String,
    @Decimal(3, 0) plifz: BigDecimal,
    @Decimal(13, 3) ntgew: BigDecimal,
    gewei: String,
    txjcd: String,
    etdrk: String,
    sobkz: String,
    arsnr: String,
    arsps: String,
    insnc: String,
    ssqss: String,
    zgtyp: String,
    ean11: String,
    bstae: String,
    revlv: String,
    geber: String,
    fistl: String,
    fipos: String,
    ko_gsber: String,
    ko_pargb: String,
    ko_prctr: String,
    ko_pprctr: String,
    meprf: String,
    @Decimal(13, 3) brgew: BigDecimal,
    @Decimal(13, 3) volum: BigDecimal,
    voleh: String,
    inco1: String,
    inco2: String,
    vorab: String,
    kolif: String,
    ltsnr: String,
    packno: String,
    fplnr: String,
    @Decimal(13, 2) gnetwr: BigDecimal,
    stapo: String,
    uebpo: String,
    lewed: String,
    emlif: String,
    lblkz: String,
    satnr: String,
    attyp: String,
    vsart: String,
    handoverloc: String,
    kanba: String,
    adrn2: String,
    cuobj: String,
    xersy: String,
    eildt: String,
    drdat: String,
    druhr: String,
    drunr: String,
    aktnr: String,
    abeln: String,
    abelp: String,
    @Decimal(13, 3) anzpu: BigDecimal,
    punei: String,
    saiso: String,
    saisj: String,
    ebon2: String,
    ebon3: String,
    ebonf: String,
    mlmaa: String,
    @Decimal(4, 0) mhdrz: BigDecimal,
    anfnr: String,
    anfps: String,
    kzkfg: String,
    usequ: String,
    umsok: String,
    banfn: String,
    bnfpo: String,
    mtart: String,
    uptyp: String,
    upvor: String,
    @Decimal(13, 2) kzwi1: BigDecimal,
    @Decimal(13, 2) kzwi2: BigDecimal,
    @Decimal(13, 2) kzwi3: BigDecimal,
    @Decimal(13, 2) kzwi4: BigDecimal,
    @Decimal(13, 2) kzwi5: BigDecimal,
    @Decimal(13, 2) kzwi6: BigDecimal,
    sikgr: String,
    @Decimal(15, 3) mfzhi: BigDecimal,
    @Decimal(15, 3) ffzhi: BigDecimal,
    retpo: String,
    aurel: String,
    bsgru: String,
    lfret: String,
    mfrgr: String,
    nrfhg: String,
    j_1bnbm: String,
    j_1bmatuse: String,
    j_1bmatorg: String,
    j_1bownpro: String,
    j_1bindust: String,
    abueb: String,
    nlabd: String,
    nfabd: String,
    kzbws: String,
    @Decimal(13, 2) bonba: BigDecimal,
    fabkz: String,
    j_1aindxp: String,
    j_1aidatep: String,
    mprof: String,
    eglkz: String,
    kztlf: String,
    kzfme: String,
    rdprf: String,
    techs: String,
    chg_srv: String,
    chg_fplnr: String,
    mfrpn: String,
    mfrnr: String,
    emnfr: String,
    novet: String,
    afnam: String,
    tzonrc: String,
    iprkz: String,
    lebre: String,
    berid: String,
    xconditions: String,
    apoms: String,
    ccomp: String,
    grant_nbr: String,
    fkber: String,
    status: String,
    reslo: String,
    kblnr: String,
    kblpos: String,
    weora: String,
    srv_bas_com: String,
    prio_urg: String,
    prio_req: String,
    empst: String,
    diff_invoice: String,
    trmrisk_relevant: String,
    creationdate: String,
    creationtime: String,
    spe_abgru: String,
    spe_crm_so: String,
    spe_crm_so_item: String,
    spe_crm_ref_so: String,
    spe_crm_ref_item: String,
    spe_crm_fkrel: String,
    spe_chng_sys: String,
    spe_insmk_src: String,
    spe_cq_ctrltype: String,
    spe_cq_nocq: String,
    reason_code: String,
    @Decimal(15, 3) cqu_sar: BigDecimal,
    anzsn: BoxedInt,
    spe_ewm_dtc: String,
    exlin: String,
    exsnr: String,
    ehtyp: String,
    @Decimal(5, 2) retpc: BigDecimal,
    dptyp: String,
    @Decimal(5, 2) dppct: BigDecimal,
    @Decimal(11, 2) dpamt: BigDecimal,
    dpdat: String,
    fls_rsto: String,
    ext_rfx_number: String,
    ext_rfx_item: String,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String
) extends Entity

case class E_ekpo_part2(
    @PK mandt: String,
    ext_rfx_system_string: String,
    srm_contract_id_string: String,
    srm_contract_itm_string: String,
    blk_reason_id_string: String,
    blk_reason_txt_string: String,
    itcons_string: String,
    fixmg_string: String,
    wabwe_string: String,
    cmpl_dlv_itm_string: String,
    inco2_l_string: String,
    inco3_l_string: String,
    externalreferenceid_string: String,
    tc_aut_det_string: String,
    manual_tc_reason_string: String,
    fiscal_incentive_string: String,
    tax_subject_st_string: String,
    fiscal_incentive_id_string: String,
    sf_txjcd_string: String,
    _bev1_negen_item_string: String,
    _bev1_nedepfree_string: String,
    _bev1_nestruccat_string: String,
    advcode_string: String,
    budget_pd_string: String,
    excpe_string: String,
    fmfgus_key_string: String,
    iuid_relevant_string: String,
    mrpind_string: String,
    sgt_scat_string: String,
    sgt_rcat_string: String,
    wrf_charstc1_string: String,
    wrf_charstc2_string: String,
    wrf_charstc3_string: String,
    zz_kostl_string: String,
    zz_bukrs_string: String,
    refsite_string: String,
    _sapmp_gpose_string: String,
    angpn_string: String,
    admoi_string: String,
    adpri_string: String,
    lprio_string: String,
    adacn_string: String,
    afpnr_string: String,
    bsark_string: String,
    audat_string: String,
    angnr_string: String,
    pnstat_string: String,
    addns_string: String,
    serru_string: String,
    sernp_string: String,
    disub_sobkz_string: String,
    disub_pspnr_string: String,
    disub_kunnr_string: String,
    disub_vbeln_string: String,
    disub_posnr_string: String,
    disub_owner_string: String,
    fsh_season_year_string: String,
    fsh_season_string: String,
    fsh_collection_string: String,
    fsh_theme_string: String,
    fsh_atp_date_string: String,
    fsh_vas_rel_string: String,
    fsh_vas_prnt_id_string: String,
    fsh_transaction_string: String,
    fsh_item_group_string: String,
    fsh_item_string: String,
    fsh_ss_string: String,
    fsh_grid_cond_rec_string: String,
    fsh_psm_pfm_split_string: String,
    @Decimal(13, 3) cnfm_qty_decimal_13_3: BigDecimal,
    fsh_pqr_uepos_string: String,
    stpac_string: String,
    lgbzo_string: String,
    lgbzo_b_string: String,
    addrnum_string: String,
    consnum_string: String,
    borgr_miss_string: String,
    ref_item_string: String,
    source_id_string: String,
    source_key_string: String,
    put_back_string: String,
    pol_id_string: String,
    cons_order_string: String
) extends Entity

object ekpo
    extends TableSpec[Joined[E_ekpo_part1, E_ekpo_part2]](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[Joined[sr_raw.ct_gbl_p73.E_ekpo_part1, sr_raw.ct_gbl_p73.E_ekpo_part2]] {
  override def sourceTableSpec: TableSpec[Joined[sr_raw.ct_gbl_p73.E_ekpo_part1, sr_raw.ct_gbl_p73.E_ekpo_part2]] = sr_raw.ct_gbl_p73.ekpo
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("mandt", col("mandt_string")),
    ("ebeln", col("ebeln_string")),
    ("ebelp", col("ebelp_string")),
    ("loekz", col("loekz_string")),
    ("statu", col("statu_string")),
    ("aedat", col("aedat_string")),
    ("txz01", col("txz01_string")),
    ("matnr", col("matnr_string")),
    ("ematn", col("ematn_string")),
    ("bukrs", col("bukrs_string")),
    ("werks", col("werks_string")),
    ("lgort", col("lgort_string")),
    ("bednr", col("bednr_string")),
    ("matkl", col("matkl_string")),
    ("infnr", col("infnr_string")),
    ("idnlf", col("idnlf_string")),
    ("ktmng", col("ktmng_decimal_13_3")),
    ("menge", col("menge_decimal_13_3")),
    ("meins", col("meins_string")),
    ("bprme", col("bprme_string")),
    ("bpumz", col("bpumz_decimal_5_0")),
    ("bpumn", col("bpumn_decimal_5_0")),
    ("umrez", col("umrez_decimal_5_0")),
    ("umren", col("umren_decimal_5_0")),
    ("netpr", col("netpr_decimal_11_2")),
    ("peinh", col("peinh_decimal_5_0")),
    ("netwr", col("netwr_decimal_13_2")),
    ("brtwr", col("brtwr_decimal_13_2")),
    ("agdat", col("agdat_string")),
    ("webaz", col("webaz_decimal_3_0")),
    ("mwskz", col("mwskz_string")),
    ("bonus", col("bonus_string")),
    ("insmk", col("insmk_string")),
    ("spinf", col("spinf_string")),
    ("prsdr", col("prsdr_string")),
    ("schpr", col("schpr_string")),
    ("mahnz", col("mahnz_decimal_3_0")),
    ("mahn1", col("mahn1_decimal_3_0")),
    ("mahn2", col("mahn2_decimal_3_0")),
    ("mahn3", col("mahn3_decimal_3_0")),
    ("uebto", col("uebto_decimal_3_1")),
    ("uebtk", col("uebtk_string")),
    ("untto", col("untto_decimal_3_1")),
    ("bwtar", col("bwtar_string")),
    ("bwtty", col("bwtty_string")),
    ("abskz", col("abskz_string")),
    ("agmem", col("agmem_string")),
    ("elikz", col("elikz_string")),
    ("erekz", col("erekz_string")),
    ("pstyp", col("pstyp_string")),
    ("knttp", col("knttp_string")),
    ("kzvbr", col("kzvbr_string")),
    ("vrtkz", col("vrtkz_string")),
    ("twrkz", col("twrkz_string")),
    ("wepos", col("wepos_string")),
    ("weunb", col("weunb_string")),
    ("repos", col("repos_string")),
    ("webre", col("webre_string")),
    ("kzabs", col("kzabs_string")),
    ("labnr", col("labnr_string")),
    ("konnr", col("konnr_string")),
    ("ktpnr", col("ktpnr_string")),
    ("abdat", col("abdat_string")),
    ("abftz", col("abftz_decimal_13_3")),
    ("etfz1", col("etfz1_decimal_3_0")),
    ("etfz2", col("etfz2_decimal_3_0")),
    ("kzstu", col("kzstu_string")),
    ("notkz", col("notkz_string")),
    ("lmein", col("lmein_string")),
    ("evers", col("evers_string")),
    ("zwert", col("zwert_decimal_13_2")),
    ("navnw", col("navnw_decimal_13_2")),
    ("abmng", col("abmng_decimal_13_3")),
    ("prdat", col("prdat_string")),
    ("bstyp", col("bstyp_string")),
    ("effwr", col("effwr_decimal_13_2")),
    ("xoblr", col("xoblr_string")),
    ("kunnr", col("kunnr_string")),
    ("adrnr", col("adrnr_string")),
    ("ekkol", col("ekkol_string")),
    ("sktof", col("sktof_string")),
    ("stafo", col("stafo_string")),
    ("plifz", col("plifz_decimal_3_0")),
    ("ntgew", col("ntgew_decimal_13_3")),
    ("gewei", col("gewei_string")),
    ("txjcd", col("txjcd_string")),
    ("etdrk", col("etdrk_string")),
    ("sobkz", col("sobkz_string")),
    ("arsnr", col("arsnr_string")),
    ("arsps", col("arsps_string")),
    ("insnc", col("insnc_string")),
    ("ssqss", col("ssqss_string")),
    ("zgtyp", col("zgtyp_string")),
    ("ean11", col("ean11_string")),
    ("bstae", col("bstae_string")),
    ("revlv", col("revlv_string")),
    ("geber", col("geber_string")),
    ("fistl", col("fistl_string")),
    ("fipos", col("fipos_string")),
    ("ko_gsber", col("ko_gsber_string")),
    ("ko_pargb", col("ko_pargb_string")),
    ("ko_prctr", col("ko_prctr_string")),
    ("ko_pprctr", col("ko_pprctr_string")),
    ("meprf", col("meprf_string")),
    ("brgew", col("brgew_decimal_13_3")),
    ("volum", col("volum_decimal_13_3")),
    ("voleh", col("voleh_string")),
    ("inco1", col("inco1_string")),
    ("inco2", col("inco2_string")),
    ("vorab", col("vorab_string")),
    ("kolif", col("kolif_string")),
    ("ltsnr", col("ltsnr_string")),
    ("packno", col("packno_string")),
    ("fplnr", col("fplnr_string")),
    ("gnetwr", col("gnetwr_decimal_13_2")),
    ("stapo", col("stapo_string")),
    ("uebpo", col("uebpo_string")),
    ("lewed", col("lewed_string")),
    ("emlif", col("emlif_string")),
    ("lblkz", col("lblkz_string")),
    ("satnr", col("satnr_string")),
    ("attyp", col("attyp_string")),
    ("vsart", col("vsart_string")),
    ("handoverloc", col("handoverloc_string")),
    ("kanba", col("kanba_string")),
    ("adrn2", col("adrn2_string")),
    ("cuobj", col("cuobj_string")),
    ("xersy", col("xersy_string")),
    ("eildt", col("eildt_string")),
    ("drdat", col("drdat_string")),
    ("druhr", col("druhr_string")),
    ("drunr", col("drunr_string")),
    ("aktnr", col("aktnr_string")),
    ("abeln", col("abeln_string")),
    ("abelp", col("abelp_string")),
    ("anzpu", col("anzpu_decimal_13_3")),
    ("punei", col("punei_string")),
    ("saiso", col("saiso_string")),
    ("saisj", col("saisj_string")),
    ("ebon2", col("ebon2_string")),
    ("ebon3", col("ebon3_string")),
    ("ebonf", col("ebonf_string")),
    ("mlmaa", col("mlmaa_string")),
    ("mhdrz", col("mhdrz_decimal_4_0")),
    ("anfnr", col("anfnr_string")),
    ("anfps", col("anfps_string")),
    ("kzkfg", col("kzkfg_string")),
    ("usequ", col("usequ_string")),
    ("umsok", col("umsok_string")),
    ("banfn", col("banfn_string")),
    ("bnfpo", col("bnfpo_string")),
    ("mtart", col("mtart_string")),
    ("uptyp", col("uptyp_string")),
    ("upvor", col("upvor_string")),
    ("kzwi1", col("kzwi1_decimal_13_2")),
    ("kzwi2", col("kzwi2_decimal_13_2")),
    ("kzwi3", col("kzwi3_decimal_13_2")),
    ("kzwi4", col("kzwi4_decimal_13_2")),
    ("kzwi5", col("kzwi5_decimal_13_2")),
    ("kzwi6", col("kzwi6_decimal_13_2")),
    ("sikgr", col("sikgr_string")),
    ("mfzhi", col("mfzhi_decimal_15_3")),
    ("ffzhi", col("ffzhi_decimal_15_3")),
    ("retpo", col("retpo_string")),
    ("aurel", col("aurel_string")),
    ("bsgru", col("bsgru_string")),
    ("lfret", col("lfret_string")),
    ("mfrgr", col("mfrgr_string")),
    ("nrfhg", col("nrfhg_string")),
    ("j_1bnbm", col("j_1bnbm_string")),
    ("j_1bmatuse", col("j_1bmatuse_string")),
    ("j_1bmatorg", col("j_1bmatorg_string")),
    ("j_1bownpro", col("j_1bownpro_string")),
    ("j_1bindust", col("j_1bindust_string")),
    ("abueb", col("abueb_string")),
    ("nlabd", col("nlabd_string")),
    ("nfabd", col("nfabd_string")),
    ("kzbws", col("kzbws_string")),
    ("bonba", col("bonba_decimal_13_2")),
    ("fabkz", col("fabkz_string")),
    ("j_1aindxp", col("j_1aindxp_string")),
    ("j_1aidatep", col("j_1aidatep_string")),
    ("mprof", col("mprof_string")),
    ("eglkz", col("eglkz_string")),
    ("kztlf", col("kztlf_string")),
    ("kzfme", col("kzfme_string")),
    ("rdprf", col("rdprf_string")),
    ("techs", col("techs_string")),
    ("chg_srv", col("chg_srv_string")),
    ("chg_fplnr", col("chg_fplnr_string")),
    ("mfrpn", col("mfrpn_string")),
    ("mfrnr", col("mfrnr_string")),
    ("emnfr", col("emnfr_string")),
    ("novet", col("novet_string")),
    ("afnam", col("afnam_string")),
    ("tzonrc", col("tzonrc_string")),
    ("iprkz", col("iprkz_string")),
    ("lebre", col("lebre_string")),
    ("berid", col("berid_string")),
    ("xconditions", col("xconditions_string")),
    ("apoms", col("apoms_string")),
    ("ccomp", col("ccomp_string")),
    ("grant_nbr", col("grant_nbr_string")),
    ("fkber", col("fkber_string")),
    ("status", col("status_string")),
    ("reslo", col("reslo_string")),
    ("kblnr", col("kblnr_string")),
    ("kblpos", col("kblpos_string")),
    ("weora", col("weora_string")),
    ("srv_bas_com", col("srv_bas_com_string")),
    ("prio_urg", col("prio_urg_string")),
    ("prio_req", col("prio_req_string")),
    ("empst", col("empst_string")),
    ("diff_invoice", col("diff_invoice_string")),
    ("trmrisk_relevant", col("trmrisk_relevant_string")),
    ("creationdate", col("creationdate_string")),
    ("creationtime", col("creationtime_string")),
    ("spe_abgru", col("spe_abgru_string")),
    ("spe_crm_so", col("spe_crm_so_string")),
    ("spe_crm_so_item", col("spe_crm_so_item_string")),
    ("spe_crm_ref_so", col("spe_crm_ref_so_string")),
    ("spe_crm_ref_item", col("spe_crm_ref_item_string")),
    ("spe_crm_fkrel", col("spe_crm_fkrel_string")),
    ("spe_chng_sys", col("spe_chng_sys_string")),
    ("spe_insmk_src", col("spe_insmk_src_string")),
    ("spe_cq_ctrltype", col("spe_cq_ctrltype_string")),
    ("spe_cq_nocq", col("spe_cq_nocq_string")),
    ("reason_code", col("reason_code_string")),
    ("cqu_sar", col("cqu_sar_decimal_15_3")),
    ("anzsn", col("anzsn_int")),
    ("spe_ewm_dtc", col("spe_ewm_dtc_string")),
    ("exlin", col("exlin_string")),
    ("exsnr", col("exsnr_string")),
    ("ehtyp", col("ehtyp_string")),
    ("retpc", col("retpc_decimal_5_2")),
    ("dptyp", col("dptyp_string")),
    ("dppct", col("dppct_decimal_5_2")),
    ("dpamt", col("dpamt_decimal_11_2")),
    ("dpdat", col("dpdat_string")),
    ("fls_rsto", col("fls_rsto_string")),
    ("ext_rfx_number", col("ext_rfx_number_string")),
    ("ext_rfx_item", col("ext_rfx_item_string"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_ekpo(prefix: String) extends ColumnWithNameAccessor {
  val mandt: ColumnWithName = ColumnWithName(prefix + "mandt")
  val ebeln: ColumnWithName = ColumnWithName(prefix + "ebeln")
  val ebelp: ColumnWithName = ColumnWithName(prefix + "ebelp")
  val loekz: ColumnWithName = ColumnWithName(prefix + "loekz")
  val statu: ColumnWithName = ColumnWithName(prefix + "statu")
  val aedat: ColumnWithName = ColumnWithName(prefix + "aedat")
  val txz01: ColumnWithName = ColumnWithName(prefix + "txz01")
  val matnr: ColumnWithName = ColumnWithName(prefix + "matnr")
  val ematn: ColumnWithName = ColumnWithName(prefix + "ematn")
  val bukrs: ColumnWithName = ColumnWithName(prefix + "bukrs")
  val werks: ColumnWithName = ColumnWithName(prefix + "werks")
  val lgort: ColumnWithName = ColumnWithName(prefix + "lgort")
  val bednr: ColumnWithName = ColumnWithName(prefix + "bednr")
  val matkl: ColumnWithName = ColumnWithName(prefix + "matkl")
  val infnr: ColumnWithName = ColumnWithName(prefix + "infnr")
  val idnlf: ColumnWithName = ColumnWithName(prefix + "idnlf")
  val ktmng: ColumnWithName = ColumnWithName(prefix + "ktmng")
  val menge: ColumnWithName = ColumnWithName(prefix + "menge")
  val meins: ColumnWithName = ColumnWithName(prefix + "meins")
  val bprme: ColumnWithName = ColumnWithName(prefix + "bprme")
  val bpumz: ColumnWithName = ColumnWithName(prefix + "bpumz")
  val bpumn: ColumnWithName = ColumnWithName(prefix + "bpumn")
  val umrez: ColumnWithName = ColumnWithName(prefix + "umrez")
  val umren: ColumnWithName = ColumnWithName(prefix + "umren")
  val netpr: ColumnWithName = ColumnWithName(prefix + "netpr")
  val peinh: ColumnWithName = ColumnWithName(prefix + "peinh")
  val netwr: ColumnWithName = ColumnWithName(prefix + "netwr")
  val brtwr: ColumnWithName = ColumnWithName(prefix + "brtwr")
  val agdat: ColumnWithName = ColumnWithName(prefix + "agdat")
  val webaz: ColumnWithName = ColumnWithName(prefix + "webaz")
  val mwskz: ColumnWithName = ColumnWithName(prefix + "mwskz")
  val bonus: ColumnWithName = ColumnWithName(prefix + "bonus")
  val insmk: ColumnWithName = ColumnWithName(prefix + "insmk")
  val spinf: ColumnWithName = ColumnWithName(prefix + "spinf")
  val prsdr: ColumnWithName = ColumnWithName(prefix + "prsdr")
  val schpr: ColumnWithName = ColumnWithName(prefix + "schpr")
  val mahnz: ColumnWithName = ColumnWithName(prefix + "mahnz")
  val mahn1: ColumnWithName = ColumnWithName(prefix + "mahn1")
  val mahn2: ColumnWithName = ColumnWithName(prefix + "mahn2")
  val mahn3: ColumnWithName = ColumnWithName(prefix + "mahn3")
  val uebto: ColumnWithName = ColumnWithName(prefix + "uebto")
  val uebtk: ColumnWithName = ColumnWithName(prefix + "uebtk")
  val untto: ColumnWithName = ColumnWithName(prefix + "untto")
  val bwtar: ColumnWithName = ColumnWithName(prefix + "bwtar")
  val bwtty: ColumnWithName = ColumnWithName(prefix + "bwtty")
  val abskz: ColumnWithName = ColumnWithName(prefix + "abskz")
  val agmem: ColumnWithName = ColumnWithName(prefix + "agmem")
  val elikz: ColumnWithName = ColumnWithName(prefix + "elikz")
  val erekz: ColumnWithName = ColumnWithName(prefix + "erekz")
  val pstyp: ColumnWithName = ColumnWithName(prefix + "pstyp")
  val knttp: ColumnWithName = ColumnWithName(prefix + "knttp")
  val kzvbr: ColumnWithName = ColumnWithName(prefix + "kzvbr")
  val vrtkz: ColumnWithName = ColumnWithName(prefix + "vrtkz")
  val twrkz: ColumnWithName = ColumnWithName(prefix + "twrkz")
  val wepos: ColumnWithName = ColumnWithName(prefix + "wepos")
  val weunb: ColumnWithName = ColumnWithName(prefix + "weunb")
  val repos: ColumnWithName = ColumnWithName(prefix + "repos")
  val webre: ColumnWithName = ColumnWithName(prefix + "webre")
  val kzabs: ColumnWithName = ColumnWithName(prefix + "kzabs")
  val labnr: ColumnWithName = ColumnWithName(prefix + "labnr")
  val konnr: ColumnWithName = ColumnWithName(prefix + "konnr")
  val ktpnr: ColumnWithName = ColumnWithName(prefix + "ktpnr")
  val abdat: ColumnWithName = ColumnWithName(prefix + "abdat")
  val abftz: ColumnWithName = ColumnWithName(prefix + "abftz")
  val etfz1: ColumnWithName = ColumnWithName(prefix + "etfz1")
  val etfz2: ColumnWithName = ColumnWithName(prefix + "etfz2")
  val kzstu: ColumnWithName = ColumnWithName(prefix + "kzstu")
  val notkz: ColumnWithName = ColumnWithName(prefix + "notkz")
  val lmein: ColumnWithName = ColumnWithName(prefix + "lmein")
  val evers: ColumnWithName = ColumnWithName(prefix + "evers")
  val zwert: ColumnWithName = ColumnWithName(prefix + "zwert")
  val navnw: ColumnWithName = ColumnWithName(prefix + "navnw")
  val abmng: ColumnWithName = ColumnWithName(prefix + "abmng")
  val prdat: ColumnWithName = ColumnWithName(prefix + "prdat")
  val bstyp: ColumnWithName = ColumnWithName(prefix + "bstyp")
  val effwr: ColumnWithName = ColumnWithName(prefix + "effwr")
  val xoblr: ColumnWithName = ColumnWithName(prefix + "xoblr")
  val kunnr: ColumnWithName = ColumnWithName(prefix + "kunnr")
  val adrnr: ColumnWithName = ColumnWithName(prefix + "adrnr")
  val ekkol: ColumnWithName = ColumnWithName(prefix + "ekkol")
  val sktof: ColumnWithName = ColumnWithName(prefix + "sktof")
  val stafo: ColumnWithName = ColumnWithName(prefix + "stafo")
  val plifz: ColumnWithName = ColumnWithName(prefix + "plifz")
  val ntgew: ColumnWithName = ColumnWithName(prefix + "ntgew")
  val gewei: ColumnWithName = ColumnWithName(prefix + "gewei")
  val txjcd: ColumnWithName = ColumnWithName(prefix + "txjcd")
  val etdrk: ColumnWithName = ColumnWithName(prefix + "etdrk")
  val sobkz: ColumnWithName = ColumnWithName(prefix + "sobkz")
  val arsnr: ColumnWithName = ColumnWithName(prefix + "arsnr")
  val arsps: ColumnWithName = ColumnWithName(prefix + "arsps")
  val insnc: ColumnWithName = ColumnWithName(prefix + "insnc")
  val ssqss: ColumnWithName = ColumnWithName(prefix + "ssqss")
  val zgtyp: ColumnWithName = ColumnWithName(prefix + "zgtyp")
  val ean11: ColumnWithName = ColumnWithName(prefix + "ean11")
  val bstae: ColumnWithName = ColumnWithName(prefix + "bstae")
  val revlv: ColumnWithName = ColumnWithName(prefix + "revlv")
  val geber: ColumnWithName = ColumnWithName(prefix + "geber")
  val fistl: ColumnWithName = ColumnWithName(prefix + "fistl")
  val fipos: ColumnWithName = ColumnWithName(prefix + "fipos")
  val ko_gsber: ColumnWithName = ColumnWithName(prefix + "ko_gsber")
  val ko_pargb: ColumnWithName = ColumnWithName(prefix + "ko_pargb")
  val ko_prctr: ColumnWithName = ColumnWithName(prefix + "ko_prctr")
  val ko_pprctr: ColumnWithName = ColumnWithName(prefix + "ko_pprctr")
  val meprf: ColumnWithName = ColumnWithName(prefix + "meprf")
  val brgew: ColumnWithName = ColumnWithName(prefix + "brgew")
  val volum: ColumnWithName = ColumnWithName(prefix + "volum")
  val voleh: ColumnWithName = ColumnWithName(prefix + "voleh")
  val inco1: ColumnWithName = ColumnWithName(prefix + "inco1")
  val inco2: ColumnWithName = ColumnWithName(prefix + "inco2")
  val vorab: ColumnWithName = ColumnWithName(prefix + "vorab")
  val kolif: ColumnWithName = ColumnWithName(prefix + "kolif")
  val ltsnr: ColumnWithName = ColumnWithName(prefix + "ltsnr")
  val packno: ColumnWithName = ColumnWithName(prefix + "packno")
  val fplnr: ColumnWithName = ColumnWithName(prefix + "fplnr")
  val gnetwr: ColumnWithName = ColumnWithName(prefix + "gnetwr")
  val stapo: ColumnWithName = ColumnWithName(prefix + "stapo")
  val uebpo: ColumnWithName = ColumnWithName(prefix + "uebpo")
  val lewed: ColumnWithName = ColumnWithName(prefix + "lewed")
  val emlif: ColumnWithName = ColumnWithName(prefix + "emlif")
  val lblkz: ColumnWithName = ColumnWithName(prefix + "lblkz")
  val satnr: ColumnWithName = ColumnWithName(prefix + "satnr")
  val attyp: ColumnWithName = ColumnWithName(prefix + "attyp")
  val vsart: ColumnWithName = ColumnWithName(prefix + "vsart")
  val handoverloc: ColumnWithName = ColumnWithName(prefix + "handoverloc")
  val kanba: ColumnWithName = ColumnWithName(prefix + "kanba")
  val adrn2: ColumnWithName = ColumnWithName(prefix + "adrn2")
  val cuobj: ColumnWithName = ColumnWithName(prefix + "cuobj")
  val xersy: ColumnWithName = ColumnWithName(prefix + "xersy")
  val eildt: ColumnWithName = ColumnWithName(prefix + "eildt")
  val drdat: ColumnWithName = ColumnWithName(prefix + "drdat")
  val druhr: ColumnWithName = ColumnWithName(prefix + "druhr")
  val drunr: ColumnWithName = ColumnWithName(prefix + "drunr")
  val aktnr: ColumnWithName = ColumnWithName(prefix + "aktnr")
  val abeln: ColumnWithName = ColumnWithName(prefix + "abeln")
  val abelp: ColumnWithName = ColumnWithName(prefix + "abelp")
  val anzpu: ColumnWithName = ColumnWithName(prefix + "anzpu")
  val punei: ColumnWithName = ColumnWithName(prefix + "punei")
  val saiso: ColumnWithName = ColumnWithName(prefix + "saiso")
  val saisj: ColumnWithName = ColumnWithName(prefix + "saisj")
  val ebon2: ColumnWithName = ColumnWithName(prefix + "ebon2")
  val ebon3: ColumnWithName = ColumnWithName(prefix + "ebon3")
  val ebonf: ColumnWithName = ColumnWithName(prefix + "ebonf")
  val mlmaa: ColumnWithName = ColumnWithName(prefix + "mlmaa")
  val mhdrz: ColumnWithName = ColumnWithName(prefix + "mhdrz")
  val anfnr: ColumnWithName = ColumnWithName(prefix + "anfnr")
  val anfps: ColumnWithName = ColumnWithName(prefix + "anfps")
  val kzkfg: ColumnWithName = ColumnWithName(prefix + "kzkfg")
  val usequ: ColumnWithName = ColumnWithName(prefix + "usequ")
  val umsok: ColumnWithName = ColumnWithName(prefix + "umsok")
  val banfn: ColumnWithName = ColumnWithName(prefix + "banfn")
  val bnfpo: ColumnWithName = ColumnWithName(prefix + "bnfpo")
  val mtart: ColumnWithName = ColumnWithName(prefix + "mtart")
  val uptyp: ColumnWithName = ColumnWithName(prefix + "uptyp")
  val upvor: ColumnWithName = ColumnWithName(prefix + "upvor")
  val kzwi1: ColumnWithName = ColumnWithName(prefix + "kzwi1")
  val kzwi2: ColumnWithName = ColumnWithName(prefix + "kzwi2")
  val kzwi3: ColumnWithName = ColumnWithName(prefix + "kzwi3")
  val kzwi4: ColumnWithName = ColumnWithName(prefix + "kzwi4")
  val kzwi5: ColumnWithName = ColumnWithName(prefix + "kzwi5")
  val kzwi6: ColumnWithName = ColumnWithName(prefix + "kzwi6")
  val sikgr: ColumnWithName = ColumnWithName(prefix + "sikgr")
  val mfzhi: ColumnWithName = ColumnWithName(prefix + "mfzhi")
  val ffzhi: ColumnWithName = ColumnWithName(prefix + "ffzhi")
  val retpo: ColumnWithName = ColumnWithName(prefix + "retpo")
  val aurel: ColumnWithName = ColumnWithName(prefix + "aurel")
  val bsgru: ColumnWithName = ColumnWithName(prefix + "bsgru")
  val lfret: ColumnWithName = ColumnWithName(prefix + "lfret")
  val mfrgr: ColumnWithName = ColumnWithName(prefix + "mfrgr")
  val nrfhg: ColumnWithName = ColumnWithName(prefix + "nrfhg")
  val j_1bnbm: ColumnWithName = ColumnWithName(prefix + "j_1bnbm")
  val j_1bmatuse: ColumnWithName = ColumnWithName(prefix + "j_1bmatuse")
  val j_1bmatorg: ColumnWithName = ColumnWithName(prefix + "j_1bmatorg")
  val j_1bownpro: ColumnWithName = ColumnWithName(prefix + "j_1bownpro")
  val j_1bindust: ColumnWithName = ColumnWithName(prefix + "j_1bindust")
  val abueb: ColumnWithName = ColumnWithName(prefix + "abueb")
  val nlabd: ColumnWithName = ColumnWithName(prefix + "nlabd")
  val nfabd: ColumnWithName = ColumnWithName(prefix + "nfabd")
  val kzbws: ColumnWithName = ColumnWithName(prefix + "kzbws")
  val bonba: ColumnWithName = ColumnWithName(prefix + "bonba")
  val fabkz: ColumnWithName = ColumnWithName(prefix + "fabkz")
  val j_1aindxp: ColumnWithName = ColumnWithName(prefix + "j_1aindxp")
  val j_1aidatep: ColumnWithName = ColumnWithName(prefix + "j_1aidatep")
  val mprof: ColumnWithName = ColumnWithName(prefix + "mprof")
  val eglkz: ColumnWithName = ColumnWithName(prefix + "eglkz")
  val kztlf: ColumnWithName = ColumnWithName(prefix + "kztlf")
  val kzfme: ColumnWithName = ColumnWithName(prefix + "kzfme")
  val rdprf: ColumnWithName = ColumnWithName(prefix + "rdprf")
  val techs: ColumnWithName = ColumnWithName(prefix + "techs")
  val chg_srv: ColumnWithName = ColumnWithName(prefix + "chg_srv")
  val chg_fplnr: ColumnWithName = ColumnWithName(prefix + "chg_fplnr")
  val mfrpn: ColumnWithName = ColumnWithName(prefix + "mfrpn")
  val mfrnr: ColumnWithName = ColumnWithName(prefix + "mfrnr")
  val emnfr: ColumnWithName = ColumnWithName(prefix + "emnfr")
  val novet: ColumnWithName = ColumnWithName(prefix + "novet")
  val afnam: ColumnWithName = ColumnWithName(prefix + "afnam")
  val tzonrc: ColumnWithName = ColumnWithName(prefix + "tzonrc")
  val iprkz: ColumnWithName = ColumnWithName(prefix + "iprkz")
  val lebre: ColumnWithName = ColumnWithName(prefix + "lebre")
  val berid: ColumnWithName = ColumnWithName(prefix + "berid")
  val xconditions: ColumnWithName = ColumnWithName(prefix + "xconditions")
  val apoms: ColumnWithName = ColumnWithName(prefix + "apoms")
  val ccomp: ColumnWithName = ColumnWithName(prefix + "ccomp")
  val grant_nbr: ColumnWithName = ColumnWithName(prefix + "grant_nbr")
  val fkber: ColumnWithName = ColumnWithName(prefix + "fkber")
  val status: ColumnWithName = ColumnWithName(prefix + "status")
  val reslo: ColumnWithName = ColumnWithName(prefix + "reslo")
  val kblnr: ColumnWithName = ColumnWithName(prefix + "kblnr")
  val kblpos: ColumnWithName = ColumnWithName(prefix + "kblpos")
  val weora: ColumnWithName = ColumnWithName(prefix + "weora")
  val srv_bas_com: ColumnWithName = ColumnWithName(prefix + "srv_bas_com")
  val prio_urg: ColumnWithName = ColumnWithName(prefix + "prio_urg")
  val prio_req: ColumnWithName = ColumnWithName(prefix + "prio_req")
  val empst: ColumnWithName = ColumnWithName(prefix + "empst")
  val diff_invoice: ColumnWithName = ColumnWithName(prefix + "diff_invoice")
  val trmrisk_relevant: ColumnWithName = ColumnWithName(prefix + "trmrisk_relevant")
  val creationdate: ColumnWithName = ColumnWithName(prefix + "creationdate")
  val creationtime: ColumnWithName = ColumnWithName(prefix + "creationtime")
  val spe_abgru: ColumnWithName = ColumnWithName(prefix + "spe_abgru")
  val spe_crm_so: ColumnWithName = ColumnWithName(prefix + "spe_crm_so")
  val spe_crm_so_item: ColumnWithName = ColumnWithName(prefix + "spe_crm_so_item")
  val spe_crm_ref_so: ColumnWithName = ColumnWithName(prefix + "spe_crm_ref_so")
  val spe_crm_ref_item: ColumnWithName = ColumnWithName(prefix + "spe_crm_ref_item")
  val spe_crm_fkrel: ColumnWithName = ColumnWithName(prefix + "spe_crm_fkrel")
  val spe_chng_sys: ColumnWithName = ColumnWithName(prefix + "spe_chng_sys")
  val spe_insmk_src: ColumnWithName = ColumnWithName(prefix + "spe_insmk_src")
  val spe_cq_ctrltype: ColumnWithName = ColumnWithName(prefix + "spe_cq_ctrltype")
  val spe_cq_nocq: ColumnWithName = ColumnWithName(prefix + "spe_cq_nocq")
  val reason_code: ColumnWithName = ColumnWithName(prefix + "reason_code")
  val cqu_sar: ColumnWithName = ColumnWithName(prefix + "cqu_sar")
  val anzsn: ColumnWithName = ColumnWithName(prefix + "anzsn")
  val spe_ewm_dtc: ColumnWithName = ColumnWithName(prefix + "spe_ewm_dtc")
  val exlin: ColumnWithName = ColumnWithName(prefix + "exlin")
  val exsnr: ColumnWithName = ColumnWithName(prefix + "exsnr")
  val ehtyp: ColumnWithName = ColumnWithName(prefix + "ehtyp")
  val retpc: ColumnWithName = ColumnWithName(prefix + "retpc")
  val dptyp: ColumnWithName = ColumnWithName(prefix + "dptyp")
  val dppct: ColumnWithName = ColumnWithName(prefix + "dppct")
  val dpamt: ColumnWithName = ColumnWithName(prefix + "dpamt")
  val dpdat: ColumnWithName = ColumnWithName(prefix + "dpdat")
  val fls_rsto: ColumnWithName = ColumnWithName(prefix + "fls_rsto")
  val ext_rfx_number: ColumnWithName = ColumnWithName(prefix + "ext_rfx_number")
  val ext_rfx_item: ColumnWithName = ColumnWithName(prefix + "ext_rfx_item")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val ext_rfx_system_string: ColumnWithName = ColumnWithName(prefix + "ext_rfx_system_string")
  val srm_contract_id_string: ColumnWithName = ColumnWithName(prefix + "srm_contract_id_string")
  val srm_contract_itm_string: ColumnWithName = ColumnWithName(prefix + "srm_contract_itm_string")
  val blk_reason_id_string: ColumnWithName = ColumnWithName(prefix + "blk_reason_id_string")
  val blk_reason_txt_string: ColumnWithName = ColumnWithName(prefix + "blk_reason_txt_string")
  val itcons_string: ColumnWithName = ColumnWithName(prefix + "itcons_string")
  val fixmg_string: ColumnWithName = ColumnWithName(prefix + "fixmg_string")
  val wabwe_string: ColumnWithName = ColumnWithName(prefix + "wabwe_string")
  val cmpl_dlv_itm_string: ColumnWithName = ColumnWithName(prefix + "cmpl_dlv_itm_string")
  val inco2_l_string: ColumnWithName = ColumnWithName(prefix + "inco2_l_string")
  val inco3_l_string: ColumnWithName = ColumnWithName(prefix + "inco3_l_string")
  val externalreferenceid_string: ColumnWithName = ColumnWithName(prefix + "externalreferenceid_string")
  val tc_aut_det_string: ColumnWithName = ColumnWithName(prefix + "tc_aut_det_string")
  val manual_tc_reason_string: ColumnWithName = ColumnWithName(prefix + "manual_tc_reason_string")
  val fiscal_incentive_string: ColumnWithName = ColumnWithName(prefix + "fiscal_incentive_string")
  val tax_subject_st_string: ColumnWithName = ColumnWithName(prefix + "tax_subject_st_string")
  val fiscal_incentive_id_string: ColumnWithName = ColumnWithName(prefix + "fiscal_incentive_id_string")
  val sf_txjcd_string: ColumnWithName = ColumnWithName(prefix + "sf_txjcd_string")
  val _bev1_negen_item_string: ColumnWithName = ColumnWithName(prefix + "_bev1_negen_item_string")
  val _bev1_nedepfree_string: ColumnWithName = ColumnWithName(prefix + "_bev1_nedepfree_string")
  val _bev1_nestruccat_string: ColumnWithName = ColumnWithName(prefix + "_bev1_nestruccat_string")
  val advcode_string: ColumnWithName = ColumnWithName(prefix + "advcode_string")
  val budget_pd_string: ColumnWithName = ColumnWithName(prefix + "budget_pd_string")
  val excpe_string: ColumnWithName = ColumnWithName(prefix + "excpe_string")
  val fmfgus_key_string: ColumnWithName = ColumnWithName(prefix + "fmfgus_key_string")
  val iuid_relevant_string: ColumnWithName = ColumnWithName(prefix + "iuid_relevant_string")
  val mrpind_string: ColumnWithName = ColumnWithName(prefix + "mrpind_string")
  val sgt_scat_string: ColumnWithName = ColumnWithName(prefix + "sgt_scat_string")
  val sgt_rcat_string: ColumnWithName = ColumnWithName(prefix + "sgt_rcat_string")
  val wrf_charstc1_string: ColumnWithName = ColumnWithName(prefix + "wrf_charstc1_string")
  val wrf_charstc2_string: ColumnWithName = ColumnWithName(prefix + "wrf_charstc2_string")
  val wrf_charstc3_string: ColumnWithName = ColumnWithName(prefix + "wrf_charstc3_string")
  val zz_kostl_string: ColumnWithName = ColumnWithName(prefix + "zz_kostl_string")
  val zz_bukrs_string: ColumnWithName = ColumnWithName(prefix + "zz_bukrs_string")
  val refsite_string: ColumnWithName = ColumnWithName(prefix + "refsite_string")
  val _sapmp_gpose_string: ColumnWithName = ColumnWithName(prefix + "_sapmp_gpose_string")
  val angpn_string: ColumnWithName = ColumnWithName(prefix + "angpn_string")
  val admoi_string: ColumnWithName = ColumnWithName(prefix + "admoi_string")
  val adpri_string: ColumnWithName = ColumnWithName(prefix + "adpri_string")
  val lprio_string: ColumnWithName = ColumnWithName(prefix + "lprio_string")
  val adacn_string: ColumnWithName = ColumnWithName(prefix + "adacn_string")
  val afpnr_string: ColumnWithName = ColumnWithName(prefix + "afpnr_string")
  val bsark_string: ColumnWithName = ColumnWithName(prefix + "bsark_string")
  val audat_string: ColumnWithName = ColumnWithName(prefix + "audat_string")
  val angnr_string: ColumnWithName = ColumnWithName(prefix + "angnr_string")
  val pnstat_string: ColumnWithName = ColumnWithName(prefix + "pnstat_string")
  val addns_string: ColumnWithName = ColumnWithName(prefix + "addns_string")
  val serru_string: ColumnWithName = ColumnWithName(prefix + "serru_string")
  val sernp_string: ColumnWithName = ColumnWithName(prefix + "sernp_string")
  val disub_sobkz_string: ColumnWithName = ColumnWithName(prefix + "disub_sobkz_string")
  val disub_pspnr_string: ColumnWithName = ColumnWithName(prefix + "disub_pspnr_string")
  val disub_kunnr_string: ColumnWithName = ColumnWithName(prefix + "disub_kunnr_string")
  val disub_vbeln_string: ColumnWithName = ColumnWithName(prefix + "disub_vbeln_string")
  val disub_posnr_string: ColumnWithName = ColumnWithName(prefix + "disub_posnr_string")
  val disub_owner_string: ColumnWithName = ColumnWithName(prefix + "disub_owner_string")
  val fsh_season_year_string: ColumnWithName = ColumnWithName(prefix + "fsh_season_year_string")
  val fsh_season_string: ColumnWithName = ColumnWithName(prefix + "fsh_season_string")
  val fsh_collection_string: ColumnWithName = ColumnWithName(prefix + "fsh_collection_string")
  val fsh_theme_string: ColumnWithName = ColumnWithName(prefix + "fsh_theme_string")
  val fsh_atp_date_string: ColumnWithName = ColumnWithName(prefix + "fsh_atp_date_string")
  val fsh_vas_rel_string: ColumnWithName = ColumnWithName(prefix + "fsh_vas_rel_string")
  val fsh_vas_prnt_id_string: ColumnWithName = ColumnWithName(prefix + "fsh_vas_prnt_id_string")
  val fsh_transaction_string: ColumnWithName = ColumnWithName(prefix + "fsh_transaction_string")
  val fsh_item_group_string: ColumnWithName = ColumnWithName(prefix + "fsh_item_group_string")
  val fsh_item_string: ColumnWithName = ColumnWithName(prefix + "fsh_item_string")
  val fsh_ss_string: ColumnWithName = ColumnWithName(prefix + "fsh_ss_string")
  val fsh_grid_cond_rec_string: ColumnWithName = ColumnWithName(prefix + "fsh_grid_cond_rec_string")
  val fsh_psm_pfm_split_string: ColumnWithName = ColumnWithName(prefix + "fsh_psm_pfm_split_string")
  val cnfm_qty_decimal_13_3: ColumnWithName = ColumnWithName(prefix + "cnfm_qty_decimal_13_3")
  val fsh_pqr_uepos_string: ColumnWithName = ColumnWithName(prefix + "fsh_pqr_uepos_string")
  val stpac_string: ColumnWithName = ColumnWithName(prefix + "stpac_string")
  val lgbzo_string: ColumnWithName = ColumnWithName(prefix + "lgbzo_string")
  val lgbzo_b_string: ColumnWithName = ColumnWithName(prefix + "lgbzo_b_string")
  val addrnum_string: ColumnWithName = ColumnWithName(prefix + "addrnum_string")
  val consnum_string: ColumnWithName = ColumnWithName(prefix + "consnum_string")
  val borgr_miss_string: ColumnWithName = ColumnWithName(prefix + "borgr_miss_string")
  val ref_item_string: ColumnWithName = ColumnWithName(prefix + "ref_item_string")
  val source_id_string: ColumnWithName = ColumnWithName(prefix + "source_id_string")
  val source_key_string: ColumnWithName = ColumnWithName(prefix + "source_key_string")
  val put_back_string: ColumnWithName = ColumnWithName(prefix + "put_back_string")
  val pol_id_string: ColumnWithName = ColumnWithName(prefix + "pol_id_string")
  val cons_order_string: ColumnWithName = ColumnWithName(prefix + "cons_order_string")
}

object C_ekpo extends C_ekpo("") {
  def as(alias: String): C_ekpo = new C_ekpo(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
