// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_p73

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_t001k(
    @PK mandt: String,
    @PK bwkey: String,
    bukrs: String,
    bwmod: String,
    xbkng: String,
    mlbwa: String,
    mlbwv: String,
    xvkbw: String,
    erklaerkom: String,
    uprof: String,
    wbpro: String,
    mlast: String,
    mlasv: String,
    @Decimal(5, 2) bdifp: BigDecimal,
    xlbpd: String,
    xewrx: String,
    x2fdo: String,
    prsfr: String,
    mlccs: String,
    xefre: String,
    efrej: String,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String
) extends Entity

object t001k
    extends TableSpec[E_t001k](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[sr_raw.ct_gbl_p73.E_t001k] {
  override def sourceTableSpec: TableSpec[sr_raw.ct_gbl_p73.E_t001k] = sr_raw.ct_gbl_p73.t001k
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("mandt", col("mandt_string")),
    ("bwkey", col("bwkey_string")),
    ("bukrs", col("bukrs_string")),
    ("bwmod", col("bwmod_string")),
    ("xbkng", col("xbkng_string")),
    ("mlbwa", col("mlbwa_string")),
    ("mlbwv", col("mlbwv_string")),
    ("xvkbw", col("xvkbw_string")),
    ("erklaerkom", col("erklaerkom_string")),
    ("uprof", col("uprof_string")),
    ("wbpro", col("wbpro_string")),
    ("mlast", col("mlast_string")),
    ("mlasv", col("mlasv_string")),
    ("bdifp", col("bdifp_decimal_5_2")),
    ("xlbpd", col("xlbpd_string")),
    ("xewrx", col("xewrx_string")),
    ("x2fdo", col("x2fdo_string")),
    ("prsfr", col("prsfr_string")),
    ("mlccs", col("mlccs_string")),
    ("xefre", col("xefre_string")),
    ("efrej", col("efrej_string"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_t001k(prefix: String) extends ColumnWithNameAccessor {
  val mandt: ColumnWithName = ColumnWithName(prefix + "mandt")
  val bwkey: ColumnWithName = ColumnWithName(prefix + "bwkey")
  val bukrs: ColumnWithName = ColumnWithName(prefix + "bukrs")
  val bwmod: ColumnWithName = ColumnWithName(prefix + "bwmod")
  val xbkng: ColumnWithName = ColumnWithName(prefix + "xbkng")
  val mlbwa: ColumnWithName = ColumnWithName(prefix + "mlbwa")
  val mlbwv: ColumnWithName = ColumnWithName(prefix + "mlbwv")
  val xvkbw: ColumnWithName = ColumnWithName(prefix + "xvkbw")
  val erklaerkom: ColumnWithName = ColumnWithName(prefix + "erklaerkom")
  val uprof: ColumnWithName = ColumnWithName(prefix + "uprof")
  val wbpro: ColumnWithName = ColumnWithName(prefix + "wbpro")
  val mlast: ColumnWithName = ColumnWithName(prefix + "mlast")
  val mlasv: ColumnWithName = ColumnWithName(prefix + "mlasv")
  val bdifp: ColumnWithName = ColumnWithName(prefix + "bdifp")
  val xlbpd: ColumnWithName = ColumnWithName(prefix + "xlbpd")
  val xewrx: ColumnWithName = ColumnWithName(prefix + "xewrx")
  val x2fdo: ColumnWithName = ColumnWithName(prefix + "x2fdo")
  val prsfr: ColumnWithName = ColumnWithName(prefix + "prsfr")
  val mlccs: ColumnWithName = ColumnWithName(prefix + "mlccs")
  val xefre: ColumnWithName = ColumnWithName(prefix + "xefre")
  val efrej: ColumnWithName = ColumnWithName(prefix + "efrej")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
}

object C_t001k extends C_t001k("") {
  def as(alias: String): C_t001k = new C_t001k(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
