// AUTO GENERATED CODE - DO NOT EDIT
package ct.dna.lakehouse.sr_raw.ct_gbl_ivanti

import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

case class E_environsettings(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    _sourcehost_string: String,
    _sourceport_long: BoxedLong,
    _sourceinstance_string: String,
    _sourcedb_string: String,
    computer_idn_long: BoxedLong,
    operating_system_idn_long: BoxedLong,
    environsettings_idn_long: BoxedLong,
    name_string: String,
    valuestring_string: String,
    totstorage_long: BoxedLong,
    contains_masked_personal_data_boolean: BoxedBoolean,
    coreguid_string: String
) extends Entity

object environsettings extends TableSpec[E_environsettings](enableChangeDataFeed = true, manualClusterBy = None, timetravelDays = 35) with Loaded

// AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY

import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_environsettings(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val _sourcehost_string: ColumnWithName = ColumnWithName(prefix + "_sourcehost_string")
  val _sourceport_long: ColumnWithName = ColumnWithName(prefix + "_sourceport_long")
  val _sourceinstance_string: ColumnWithName = ColumnWithName(prefix + "_sourceinstance_string")
  val _sourcedb_string: ColumnWithName = ColumnWithName(prefix + "_sourcedb_string")
  val computer_idn_long: ColumnWithName = ColumnWithName(prefix + "computer_idn_long")
  val operating_system_idn_long: ColumnWithName = ColumnWithName(prefix + "operating_system_idn_long")
  val environsettings_idn_long: ColumnWithName = ColumnWithName(prefix + "environsettings_idn_long")
  val name_string: ColumnWithName = ColumnWithName(prefix + "name_string")
  val valuestring_string: ColumnWithName = ColumnWithName(prefix + "valuestring_string")
  val totstorage_long: ColumnWithName = ColumnWithName(prefix + "totstorage_long")
  val contains_masked_personal_data_boolean: ColumnWithName = ColumnWithName(prefix + "contains_masked_personal_data_boolean")
  val coreguid_string: ColumnWithName = ColumnWithName(prefix + "coreguid_string")
}

object C_environsettings extends C_environsettings("") {
  def as(alias: String): C_environsettings = new C_environsettings(alias + ".")
}

// AUTO GENERATED:END
