// LOADED TABLE SPEC AUTO GENERATED:START
// Generated by LoadedTableSpecAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr_raw.ct_gbl_ivanti

import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.Loaded
import ct.dna.lakehouse.core.model.TableSpec

case class E_ld_task_machine(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    _sourcehost_string: String,
    _sourceport_long: BoxedLong,
    _sourceinstance_string: String,
    _sourcedb_string: String,
    ld_task_idn_long: BoxedLong,
    computer_idn_long: BoxedLong,
    mac_status_long: BoxedLong,
    mac_retcode_long: BoxedLong,
    mac_woke_up_long: BoxedLong,
    status_time_string: String,
    retcode_message_string: String,
    custom_message_string: String,
    apm_policy_users_idn_long: BoxedLong,
    source_type_long: BoxedLong,
    source_idn_long: BoxedLong,
    package_idn_long: BoxedLong,
    policystarttime_string: String,
    stage_long: BoxedLong,
    contains_masked_personal_data_boolean: BoxedBoolean,
    coreguid_string: String
) extends Entity

object ld_task_machine
    extends TableSpec[E_ld_task_machine](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.Columns("_mk_instance", "_mk_partition", "_mk_file"),
      timetravelDays = 35
    )
    with Loaded
// LOADED TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_ld_task_machine(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val _sourcehost_string: ColumnWithName = ColumnWithName(prefix + "_sourcehost_string")
  val _sourceport_long: ColumnWithName = ColumnWithName(prefix + "_sourceport_long")
  val _sourceinstance_string: ColumnWithName = ColumnWithName(prefix + "_sourceinstance_string")
  val _sourcedb_string: ColumnWithName = ColumnWithName(prefix + "_sourcedb_string")
  val ld_task_idn_long: ColumnWithName = ColumnWithName(prefix + "ld_task_idn_long")
  val computer_idn_long: ColumnWithName = ColumnWithName(prefix + "computer_idn_long")
  val mac_status_long: ColumnWithName = ColumnWithName(prefix + "mac_status_long")
  val mac_retcode_long: ColumnWithName = ColumnWithName(prefix + "mac_retcode_long")
  val mac_woke_up_long: ColumnWithName = ColumnWithName(prefix + "mac_woke_up_long")
  val status_time_string: ColumnWithName = ColumnWithName(prefix + "status_time_string")
  val retcode_message_string: ColumnWithName = ColumnWithName(prefix + "retcode_message_string")
  val custom_message_string: ColumnWithName = ColumnWithName(prefix + "custom_message_string")
  val apm_policy_users_idn_long: ColumnWithName = ColumnWithName(prefix + "apm_policy_users_idn_long")
  val source_type_long: ColumnWithName = ColumnWithName(prefix + "source_type_long")
  val source_idn_long: ColumnWithName = ColumnWithName(prefix + "source_idn_long")
  val package_idn_long: ColumnWithName = ColumnWithName(prefix + "package_idn_long")
  val policystarttime_string: ColumnWithName = ColumnWithName(prefix + "policystarttime_string")
  val stage_long: ColumnWithName = ColumnWithName(prefix + "stage_long")
  val contains_masked_personal_data_boolean: ColumnWithName = ColumnWithName(prefix + "contains_masked_personal_data_boolean")
  val coreguid_string: ColumnWithName = ColumnWithName(prefix + "coreguid_string")
}

object C_ld_task_machine extends C_ld_task_machine("") {
  def as(alias: String): C_ld_task_machine = new C_ld_task_machine(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
