// LOADED TABLE SPEC AUTO GENERATED:START
// Generated by LoadedTableSpecAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr_raw.ct_gbl_ivanti

import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.Loaded
import ct.dna.lakehouse.core.model.TableSpec

case class E_motherboard(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    _sourcehost_string: String,
    _sourceport_long: BoxedLong,
    _sourceinstance_string: String,
    _sourcedb_string: String,
    computer_idn_long: BoxedLong,
    manufacturer_string: String,
    chipset_string: String,
    numslots_string: String,
    frugrpindex_long: BoxedLong,
    opgrpindex_long: BoxedLong,
    maxcpu_long: BoxedLong,
    productname_string: String,
    mbversion_string: String,
    serialnum_string: String,
    busspeed_long: BoxedLong,
    pcislots_long: BoxedLong,
    pcislotsavail_long: BoxedLong,
    coreguid_string: String,
    contains_masked_personal_data_boolean: BoxedBoolean
) extends Entity

object motherboard
    extends TableSpec[E_motherboard](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.Columns("_mk_instance", "_mk_partition", "_mk_file"),
      timetravelDays = 35
    )
    with Loaded
// LOADED TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_motherboard(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val _sourcehost_string: ColumnWithName = ColumnWithName(prefix + "_sourcehost_string")
  val _sourceport_long: ColumnWithName = ColumnWithName(prefix + "_sourceport_long")
  val _sourceinstance_string: ColumnWithName = ColumnWithName(prefix + "_sourceinstance_string")
  val _sourcedb_string: ColumnWithName = ColumnWithName(prefix + "_sourcedb_string")
  val computer_idn_long: ColumnWithName = ColumnWithName(prefix + "computer_idn_long")
  val manufacturer_string: ColumnWithName = ColumnWithName(prefix + "manufacturer_string")
  val chipset_string: ColumnWithName = ColumnWithName(prefix + "chipset_string")
  val numslots_string: ColumnWithName = ColumnWithName(prefix + "numslots_string")
  val frugrpindex_long: ColumnWithName = ColumnWithName(prefix + "frugrpindex_long")
  val opgrpindex_long: ColumnWithName = ColumnWithName(prefix + "opgrpindex_long")
  val maxcpu_long: ColumnWithName = ColumnWithName(prefix + "maxcpu_long")
  val productname_string: ColumnWithName = ColumnWithName(prefix + "productname_string")
  val mbversion_string: ColumnWithName = ColumnWithName(prefix + "mbversion_string")
  val serialnum_string: ColumnWithName = ColumnWithName(prefix + "serialnum_string")
  val busspeed_long: ColumnWithName = ColumnWithName(prefix + "busspeed_long")
  val pcislots_long: ColumnWithName = ColumnWithName(prefix + "pcislots_long")
  val pcislotsavail_long: ColumnWithName = ColumnWithName(prefix + "pcislotsavail_long")
  val coreguid_string: ColumnWithName = ColumnWithName(prefix + "coreguid_string")
  val contains_masked_personal_data_boolean: ColumnWithName = ColumnWithName(prefix + "contains_masked_personal_data_boolean")
}

object C_motherboard extends C_motherboard("") {
  def as(alias: String): C_motherboard = new C_motherboard(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
