// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_pbr

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_stko(
    @PK mandt: String,
    @PK stlty: String,
    @PK stlnr: String,
    @PK stlal: String,
    @PK stkoz: String,
    datuv: String,
    techv: String,
    aennr: String,
    lkenz: String,
    loekz: String,
    vgkzl: String,
    andat: String,
    annam: String,
    aedat: String,
    aenam: String,
    bmein: String,
    @Decimal(13, 3) bmeng: BigDecimal,
    cadkz: String,
    labor: String,
    ltxsp: String,
    stktx: String,
    stlst: String,
    wrkan: String,
    dvdat: String,
    dvnam: String,
    aehlp: String,
    alekz: String,
    valid_to: String,
    valid_to_rkey: String,
    ecn_to: String,
    ecn_to_rkey: String,
    zzce_status: String,
    zz_source: String,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    guidx_binary: Array[Byte]
) extends Entity

object stko
    extends TableSpec[E_stko](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[sr_raw.ct_gbl_pbr.E_stko] {
  override def sourceTableSpec: TableSpec[sr_raw.ct_gbl_pbr.E_stko] = sr_raw.ct_gbl_pbr.stko
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("mandt", col("mandt_string")),
    ("stlty", col("stlty_string")),
    ("stlnr", col("stlnr_string")),
    ("stlal", col("stlal_string")),
    ("stkoz", col("stkoz_string")),
    ("datuv", col("datuv_string")),
    ("techv", col("techv_string")),
    ("aennr", col("aennr_string")),
    ("lkenz", col("lkenz_string")),
    ("loekz", col("loekz_string")),
    ("vgkzl", col("vgkzl_string")),
    ("andat", col("andat_string")),
    ("annam", col("annam_string")),
    ("aedat", col("aedat_string")),
    ("aenam", col("aenam_string")),
    ("bmein", col("bmein_string")),
    ("bmeng", col("bmeng_decimal_13_3")),
    ("cadkz", col("cadkz_string")),
    ("labor", col("labor_string")),
    ("ltxsp", col("ltxsp_string")),
    ("stktx", col("stktx_string")),
    ("stlst", col("stlst_string")),
    ("wrkan", col("wrkan_string")),
    ("dvdat", col("dvdat_string")),
    ("dvnam", col("dvnam_string")),
    ("aehlp", col("aehlp_string")),
    ("alekz", col("alekz_string")),
    ("valid_to", col("valid_to_string")),
    ("valid_to_rkey", col("valid_to_rkey_string")),
    ("ecn_to", col("ecn_to_string")),
    ("ecn_to_rkey", col("ecn_to_rkey_string")),
    ("zzce_status", col("zzce_status_string")),
    ("zz_source", col("zz_source_string"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_stko(prefix: String) extends ColumnWithNameAccessor {
  val mandt: ColumnWithName = ColumnWithName(prefix + "mandt")
  val stlty: ColumnWithName = ColumnWithName(prefix + "stlty")
  val stlnr: ColumnWithName = ColumnWithName(prefix + "stlnr")
  val stlal: ColumnWithName = ColumnWithName(prefix + "stlal")
  val stkoz: ColumnWithName = ColumnWithName(prefix + "stkoz")
  val datuv: ColumnWithName = ColumnWithName(prefix + "datuv")
  val techv: ColumnWithName = ColumnWithName(prefix + "techv")
  val aennr: ColumnWithName = ColumnWithName(prefix + "aennr")
  val lkenz: ColumnWithName = ColumnWithName(prefix + "lkenz")
  val loekz: ColumnWithName = ColumnWithName(prefix + "loekz")
  val vgkzl: ColumnWithName = ColumnWithName(prefix + "vgkzl")
  val andat: ColumnWithName = ColumnWithName(prefix + "andat")
  val annam: ColumnWithName = ColumnWithName(prefix + "annam")
  val aedat: ColumnWithName = ColumnWithName(prefix + "aedat")
  val aenam: ColumnWithName = ColumnWithName(prefix + "aenam")
  val bmein: ColumnWithName = ColumnWithName(prefix + "bmein")
  val bmeng: ColumnWithName = ColumnWithName(prefix + "bmeng")
  val cadkz: ColumnWithName = ColumnWithName(prefix + "cadkz")
  val labor: ColumnWithName = ColumnWithName(prefix + "labor")
  val ltxsp: ColumnWithName = ColumnWithName(prefix + "ltxsp")
  val stktx: ColumnWithName = ColumnWithName(prefix + "stktx")
  val stlst: ColumnWithName = ColumnWithName(prefix + "stlst")
  val wrkan: ColumnWithName = ColumnWithName(prefix + "wrkan")
  val dvdat: ColumnWithName = ColumnWithName(prefix + "dvdat")
  val dvnam: ColumnWithName = ColumnWithName(prefix + "dvnam")
  val aehlp: ColumnWithName = ColumnWithName(prefix + "aehlp")
  val alekz: ColumnWithName = ColumnWithName(prefix + "alekz")
  val valid_to: ColumnWithName = ColumnWithName(prefix + "valid_to")
  val valid_to_rkey: ColumnWithName = ColumnWithName(prefix + "valid_to_rkey")
  val ecn_to: ColumnWithName = ColumnWithName(prefix + "ecn_to")
  val ecn_to_rkey: ColumnWithName = ColumnWithName(prefix + "ecn_to_rkey")
  val zzce_status: ColumnWithName = ColumnWithName(prefix + "zzce_status")
  val zz_source: ColumnWithName = ColumnWithName(prefix + "zz_source")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val guidx_binary: ColumnWithName = ColumnWithName(prefix + "guidx_binary")
}

object C_stko extends C_stko("") {
  def as(alias: String): C_stko = new C_stko(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
