// LOADED TABLE SPEC AUTO GENERATED:START
// Generated by LoadedTableSpecAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr_raw.ct_gbl_ghp

import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.Loaded
import ct.dna.lakehouse.core.model.TableSpec

case class E_ckmlpr(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt_string: String,
    kalnr_string: String,
    curtp_string: String,
    @Decimal(5, 0) peinh_decimal_5_0: BigDecimal,
    zprsdat_string: String,
    @Decimal(11, 2) zkprs_decimal_11_2: BigDecimal,
    kalkz_string: String,
    pprdz_string: String,
    pdatz_string: String,
    bwva1_string: String,
    vers1_string: String,
    @Decimal(11, 2) zplpr_decimal_11_2: BigDecimal,
    @Decimal(11, 2) fplpx_decimal_11_2: BigDecimal,
    zbwst_string: String,
    kalkl_string: String,
    pprdl_string: String,
    pdatl_string: String,
    bwva2_string: String,
    vers2_string: String,
    @Decimal(11, 2) lplpr_decimal_11_2: BigDecimal,
    @Decimal(11, 2) lplpx_decimal_11_2: BigDecimal,
    lbwst_string: String,
    kalkv_string: String,
    pprdv_string: String,
    pdatv_string: String,
    bwva3_string: String,
    vers3_string: String,
    @Decimal(11, 2) vplpr_decimal_11_2: BigDecimal,
    @Decimal(11, 2) vplpx_decimal_11_2: BigDecimal,
    cbwst_string: String,
    set_by_marking_string: String,
    eibdatj_string: String,
    eipoper_string: String,
    @Decimal(11, 2) eiprice_decimal_11_2: BigDecimal,
    sdm_version_string: String
) extends Entity

object ckmlpr
    extends TableSpec[E_ckmlpr](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.Columns("_mk_instance", "_mk_partition", "_mk_file"),
      timetravelDays = 35
    )
    with Loaded
// LOADED TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_ckmlpr(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val mandt_string: ColumnWithName = ColumnWithName(prefix + "mandt_string")
  val kalnr_string: ColumnWithName = ColumnWithName(prefix + "kalnr_string")
  val curtp_string: ColumnWithName = ColumnWithName(prefix + "curtp_string")
  val peinh_decimal_5_0: ColumnWithName = ColumnWithName(prefix + "peinh_decimal_5_0")
  val zprsdat_string: ColumnWithName = ColumnWithName(prefix + "zprsdat_string")
  val zkprs_decimal_11_2: ColumnWithName = ColumnWithName(prefix + "zkprs_decimal_11_2")
  val kalkz_string: ColumnWithName = ColumnWithName(prefix + "kalkz_string")
  val pprdz_string: ColumnWithName = ColumnWithName(prefix + "pprdz_string")
  val pdatz_string: ColumnWithName = ColumnWithName(prefix + "pdatz_string")
  val bwva1_string: ColumnWithName = ColumnWithName(prefix + "bwva1_string")
  val vers1_string: ColumnWithName = ColumnWithName(prefix + "vers1_string")
  val zplpr_decimal_11_2: ColumnWithName = ColumnWithName(prefix + "zplpr_decimal_11_2")
  val fplpx_decimal_11_2: ColumnWithName = ColumnWithName(prefix + "fplpx_decimal_11_2")
  val zbwst_string: ColumnWithName = ColumnWithName(prefix + "zbwst_string")
  val kalkl_string: ColumnWithName = ColumnWithName(prefix + "kalkl_string")
  val pprdl_string: ColumnWithName = ColumnWithName(prefix + "pprdl_string")
  val pdatl_string: ColumnWithName = ColumnWithName(prefix + "pdatl_string")
  val bwva2_string: ColumnWithName = ColumnWithName(prefix + "bwva2_string")
  val vers2_string: ColumnWithName = ColumnWithName(prefix + "vers2_string")
  val lplpr_decimal_11_2: ColumnWithName = ColumnWithName(prefix + "lplpr_decimal_11_2")
  val lplpx_decimal_11_2: ColumnWithName = ColumnWithName(prefix + "lplpx_decimal_11_2")
  val lbwst_string: ColumnWithName = ColumnWithName(prefix + "lbwst_string")
  val kalkv_string: ColumnWithName = ColumnWithName(prefix + "kalkv_string")
  val pprdv_string: ColumnWithName = ColumnWithName(prefix + "pprdv_string")
  val pdatv_string: ColumnWithName = ColumnWithName(prefix + "pdatv_string")
  val bwva3_string: ColumnWithName = ColumnWithName(prefix + "bwva3_string")
  val vers3_string: ColumnWithName = ColumnWithName(prefix + "vers3_string")
  val vplpr_decimal_11_2: ColumnWithName = ColumnWithName(prefix + "vplpr_decimal_11_2")
  val vplpx_decimal_11_2: ColumnWithName = ColumnWithName(prefix + "vplpx_decimal_11_2")
  val cbwst_string: ColumnWithName = ColumnWithName(prefix + "cbwst_string")
  val set_by_marking_string: ColumnWithName = ColumnWithName(prefix + "set_by_marking_string")
  val eibdatj_string: ColumnWithName = ColumnWithName(prefix + "eibdatj_string")
  val eipoper_string: ColumnWithName = ColumnWithName(prefix + "eipoper_string")
  val eiprice_decimal_11_2: ColumnWithName = ColumnWithName(prefix + "eiprice_decimal_11_2")
  val sdm_version_string: ColumnWithName = ColumnWithName(prefix + "sdm_version_string")
}

object C_ckmlpr extends C_ckmlpr("") {
  def as(alias: String): C_ckmlpr = new C_ckmlpr(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
