package ct.dna.lakehouse.sr_raw.ct_gbl_ghp
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class eket_E(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  handover_date_string: String,
  ebelp_string: String,
  handoverdate_string: String,
  zz_pudat_string: String,
  @Decimal(17, 2) otb_value_decimal_17_2: BigDecimal,
  eindt_string: String,
  startdate_string: String,
  @Decimal(13, 3) wesbb_decimal_13_3: BigDecimal,
  eldat_string: String,
  wauhr_string: String,
  cd_locno_string: String,
  fsh_os_id_string: String,
  @Decimal(13, 3) mng02_decimal_13_3: BigDecimal,
  rsnum_string: String,
  enddate_string: String,
  gts_ind_string: String,
  key_id_string: String,
  @Decimal(3, 0) dateshift_number_decimal_3_0: BigDecimal,
  ebeln_string: String,
  @Decimal(17, 2) otb_spec_value_decimal_17_2: BigDecimal,
  tddat_string: String,
  fixkz_string: String,
  anzsn_int: BoxedInt,
  @Decimal(13, 3) wamng_decimal_13_3: BigDecimal,
  check_type_string: String,
  _dataaging_string: String,
  banfn_string: String,
  aulwe_string: String,
  abart_string: String,
  qunum_string: String,
  charg_string: String,
  otb_curr_string: String,
  estkz_string: String,
  @Decimal(13, 3) ameng_decimal_13_3: BigDecimal,
  @Decimal(13, 3) _cwm_dabmg_decimal_13_3: BigDecimal,
  mbdat_string: String,
  nodisp_string: String,
  tsp_string: String,
  geo_route_string: String,
  mandt_string: String,
  etenr_string: String,
  dng_date_string: String,
  mbuhr_string: String,
  cd_loctype_string: String,
  slfdt_string: String,
  tms_ref_uuid_string: String,
  bedat_string: String,
  verid_string: String,
  @Decimal(13, 3) fsh_salloc_qty_decimal_13_3: BigDecimal,
  @Decimal(13, 3) menge_decimal_13_3: BigDecimal,
  wadat_string: String,
  bnfpo_string: String,
  licha_string: String,
  qupos_string: String,
  altdt_string: String,
  chkom_string: String,
  spr_rsn_profile_string: String,
  route_gts_string: String,
  @Decimal(13, 3) fsh_ralloc_qty_decimal_13_3: BigDecimal,
  eluhr_string: String,
  lddat_string: String,
  sernr_string: String,
  dng_time_string: String,
  arun_req_dlvdate_string: String,
  @Decimal(13, 3) dabmg_decimal_13_3: BigDecimal,
  dl_id_string: String,
  @Decimal(3, 0) mahnz_decimal_3_0: BigDecimal,
  tduhr_string: String,
  otb_status_string: String,
  handovertime_string: String,
  otb_reason_string: String,
  cncl_ancmnt_done_string: String,
  no_scem_string: String,
  @Decimal(13, 3) _cwm_wemng_decimal_13_3: BigDecimal,
  @Decimal(13, 3) glmng_decimal_13_3: BigDecimal,
  dat01_string: String,
  uzeit_string: String,
  budg_type_string: String,
  @Decimal(13, 3) _cwm_menge_decimal_13_3: BigDecimal,
  @Decimal(17, 2) otb_res_value_decimal_17_2: BigDecimal,
  lpein_string: String,
  uniqueid_string: String,
  lduhr_string: String,
  @Decimal(13, 3) wemng_decimal_13_3: BigDecimal
) extends Entity

object eket extends TableSpec[eket_E](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
