package ct.dna.lakehouse.sr_raw.ct_gbl_ghp
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class kna1_E_part1(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  ort02_string: String,
  hzuor_string: String,
  _vso_r_pk_mat_string: String,
  katr6_string: String,
  j_3gabrken_string: String,
  faksd_string: String,
  dtams_string: String,
  exp_string: String,
  j_1iexco_string: String,
  kdkg1_string: String,
  begru_string: String,
  telfx_string: String,
  abrvw_string: String,
  _vso_r_load_pref_string: String,
  pspnr_string: String,
  data_ctrlr9_string: String,
  xcpdk_string: String,
  @Decimal(5, 2) j_3gstdmon_decimal_5_2: BigDecimal,
  brsch_string: String,
  locco_string: String,
  ktocd_string: String,
  jmzah_string: String,
  ernam_string: String,
  counc_string: String,
  bran2_string: String,
  cassd_string: String,
  _vso_r_one_sort_string: String,
  dear3_string: String,
  j_3gagdumi_string: String,
  milve_string: String,
  pfach_string: String,
  consolidate_invoice_string: String,
  data_ctrlr8_string: String,
  j_3gfristlo_string: String,
  j_3getyp_string: String,
  etikg_string: String,
  ccc03_string: String,
  umjah_string: String,
  icmstaxpay_string: String,
  name3_string: String,
  spras_string: String,
  sortl_string: String,
  data_ctrlr3_string: String,
  j_1iexrg_string: String,
  bran3_string: String,
  fityp_string: String,
  cfopc_string: String,
  @Decimal(5, 2) j_3gtagmon_decimal_5_2: BigDecimal,
  bran5_string: String,
  cvp_xblck_string: String,
  name1_string: String,
  stcd5_string: String,
  confs_string: String,
  telx1_string: String,
  stkzn_string: String,
  dear4_string: String,
  bahns_string: String,
  _vso_r_dpoint_string: String,
  @Decimal(8, 2) umsat_decimal_8_2: BigDecimal,
  legalnat_string: String,
  einvoice_mode_string: String,
  stkza_string: String,
  duefl_string: String,
  suframa_string: String,
  telbx_string: String,
  stcd1_string: String,
  regio_string: String,
  crtn_string: String,
  _vso_r_pal_ul_string: String,
  alc_string: String,
  stkzu_string: String,
  zz1_ct1_cus_string: String,
  stcd4_string: String,
  datlt_string: String,
  stcd6_string: String,
  j_3gmaschb_string: String,
  b2c_indicator_string: String,
  j_1ilstno_string: String,
  rpmkr_string: String,
  data_ctrlr6_string: String,
  psost_string: String,
  j_3gabgvg_string: String,
  ccc02_string: String,
  psoo3_string: String,
  j_3gmeinsa_string: String,
  kokrs_string: String,
  data_ctrlr4_string: String,
  delivery_date_rule_string: String,
  j_3gkleivo_string: String,
  j_3gvmonat_string: String,
  land1_string: String,
  katr5_string: String,
  bahne_string: String,
  stceg_string: String,
  ric_string: String,
  ktokd_string: String,
  bbsnr_string: String,
  j_3gzuschue_string: String,
  stcd2_string: String,
  _vso_r_uld_side_string: String,
  j_3gzutvhlg_string: String,
  txlw1_string: String,
  knazk_string: String,
  cityc_string: String,
  anred_string: String,
  rule_exclusion_string: String,
  @Decimal(13, 3) _vso_r_palhgt_decimal_13_3: BigDecimal,
  xicms_string: String,
  j_3gschprs_string: String,
  updat_string: String,
  lgort_string: String,
  dear2_string: String,
  mcod2_string: String,
  nodel_string: String,
  werks_string: String,
  katr8_string: String,
  pson1_string: String,
  kna1_addr_eew_cust_string: String,
  mcod3_string: String,
  xxipi_string: String,
  _sapcem_kvmeq_string: String,
  psoo1_string: String,
  decregpc_string: String,
  mandt_string: String,
  knurl_string: String,
  @Decimal(5, 2) j_3gstdtag_decimal_5_2: BigDecimal,
  zz1_segment_cus_string: String,
  sperz_string: String,
  kdkg3_string: String,
  zz1_subvertical_cus_string: String,
  j_1kftbus_string: String,
  j_1kfrepre_string: String,
  j_3gagint_string: String,
  niels_string: String,
  ccc01_string: String,
  vbund_string: String,
  j_3gnegmen_string: String,
  psohs_string: String,
  data_ctrlr7_string: String,
  lifsd_string: String,
  @Decimal(15, 2) umsa1_decimal_15_2: BigDecimal,
  pson3_string: String,
  psoo5_string: String,
  txjcd_string: String,
  ekont_string: String,
  katr2_string: String,
  dear1_string: String,
  telf1_string: String,
  name4_string: String,
  psofg_string: String,
  fiskn_string: String,
  xdcset_string: String,
  _vso_r_matpal_string: String,
  rne_string: String,
  mcod1_string: String,
  rg_string: String,
  j_3gfmgue_string: String,
  gform_string: String,
  psotl_string: String,
  konzs_string: String,
  adrnr_string: String,
  j_3gzugtag_string: String,
  kdkg4_string: String,
  comsize_string: String,
  psois_string: String,
  j_1ipanref_string: String,
  telf2_string: String,
  j_3gagext_string: String,
  paytrsn_string: String,
  j_1iexcicu_string: String,
  j_3geminbe_string: String,
  j_1kftind_string: String,
  xknza_string: String,
  data_ctrlr1_string: String,
  xzemp_string: String,
  j_1iexcd_string: String,
  fee_schedule_string: String,
  psovn_string: String,
  uwaer_string: String,
  psoo4_string: String,
  knrza_string: String,
  j_3gcalid_string: String,
  teltx_string: String,
  kukla_string: String,
  dear5_string: String,
  _vso_r_one_mat_string: String,
  dear6_string: String,
  donate_mark_string: String,
  _vso_r_i_no_lyr_string: String,
  j_3gabrart_string: String,
  gst_tds_string: String,
  exabl_string: String,
  duns_string: String,
  indtyp_string: String,
  txlw2_string: String,
  xsubt_string: String,
  katr4_string: String,
  jmjah_string: String,
  pstlz_string: String,
  rnedate_string: String,
  pmt_office_string: String,
  j_3gaabrech_string: String,
  zz1_vertical_cus_string: String,
  pson2_string: String,
  allowance_type_string: String,
  name2_string: String,
  zz1_ct2_cus_string: String,
  stcdt_string: String,
  bran1_string: String,
  cnae_string: String,
  sam_ue_id_string: String,
  data_ctrlr5_string: String,
  aedat_string: String,
  j_1icstno_string: String,
  katr3_string: String,
  pstl2_string: String,
  j_3gblsper_string: String,
  uf_string: String,
  katr7_string: String,
  j_1isern_string: String,
  dtaws_string: String,
  kdkg2_string: String,
  katr1_string: String,
  ccc04_string: String,
  bonded_area_confirm_string: String,
  stcd3_string: String,
  ph_biz_style_string: String,
  ort01_string: String,
  lifnr_string: String,
  j_1iexdi_string: String,
  bran4_string: String,
  j_3glabrech_string: String,
  periv_string: String,
  psoo2_string: String,
  bubkz_string: String,
  lzone_string: String,
  aufsd_string: String,
  duns4_string: String,
  kunnr_string: String,
  sperr_string: String,
  coaufnr_string: String,
  loevm_string: String
) extends Entity


@LakehouseEntity
case class kna1_E_part2(
  @PK _mk_org: String,
  _sapcem_dber_string: String,
  stras_string: String,
  kdkg5_string: String,
  pfort_string: String,
  inspbydebi_string: String,
  katr10_string: String,
  usnam_string: String,
  j_1ipanno_string: String,
  uptim_string: String,
  sam_eft_ind_string: String,
  j_3gagstdi_string: String,
  j_3gabglg_string: String,
  bbbnr_string: String,
  j_3gkeinsa_string: String,
  j_1iexrn_string: String,
  tdt_string: String,
  kna1_eew_cust_string: String,
  data_ctrlr10_string: String,
  kostl_string: String,
  civve_string: String,
  j_3greftyp_string: String,
  katr9_string: String,
  rgdate_string: String,
  inspatdebi_string: String,
  j_3ginvsta_string: String,
  data_ctrlr2_string: String,
  erdat_string: String
) extends Entity

object kna1 extends TableSpec[Joined[kna1_E_part1, kna1_E_part2]](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
