package ct.dna.lakehouse.sr_raw.ct_gbl_ghp
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class konp_E(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  zterm_string: String,
  knumt_string: String,
  @Decimal(15, 3) kstbm_decimal_15_3: BigDecimal,
  konwa_string: String,
  valtg_string: String,
  @Decimal(5, 0) kpein_decimal_5_0: BigDecimal,
  @Decimal(11, 2) kbetr_decimal_11_2: BigDecimal,
  @Decimal(15, 3) mxkbas_decimal_15_3: BigDecimal,
  klf_kal_string: String,
  prsch_string: String,
  mdflg_string: String,
  @Decimal(15, 2) kstbw_decimal_15_2: BigDecimal,
  konms_string: String,
  mwsk1_string: String,
  vertn_string: String,
  knuma_ag_string: String,
  krech_string: String,
  vkkal_string: String,
  mwsk2_string: String,
  @Decimal(15, 3) mikbas_decimal_15_3: BigDecimal,
  cndn_chgreason_string: String,
  konws_string: String,
  knuma_sq_string: String,
  cmmdtyprcgcndnfmlauuid_binary: Array[Byte],
  @Decimal(15, 2) rswrt_decimal_15_2: BigDecimal,
  vbewa_string: String,
  @Decimal(11, 2) kbrue_decimal_11_2: BigDecimal,
  @Decimal(11, 2) mxwrt_decimal_11_2: BigDecimal,
  knuma_bo_string: String,
  knumh_string: String,
  valdt_string: String,
  @Decimal(13, 2) komxwrt_decimal_13_2: BigDecimal,
  @Decimal(5, 0) kumza_decimal_5_0: BigDecimal,
  mandt_string: String,
  kfrst_string: String,
  @Decimal(15, 2) fkwrt_decimal_15_2: BigDecimal,
  kspae_string: String,
  @Decimal(15, 2) pkwrt_decimal_15_2: BigDecimal,
  meins_string: String,
  kznep_string: String,
  stfkz_string: String,
  kwaeh_string: String,
  kopos_string: String,
  @Decimal(15, 2) ukbas_decimal_15_2: BigDecimal,
  uasta_string: String,
  vertt_string: String,
  kmein_string: String,
  anzauf_string: String,
  zaehk_ind_string: String,
  bosta_string: String,
  @Decimal(11, 2) gkwrt_decimal_11_2: BigDecimal,
  aktnr_string: String,
  kschl_string: String,
  @Decimal(5, 0) kumne_decimal_5_0: BigDecimal,
  kzbzg_string: String,
  lifnr_string: String,
  knuma_pi_string: String,
  klf_stg_string: String,
  kunnr_string: String,
  bomat_string: String,
  kappl_string: String,
  loevm_ko_string: String
) extends Entity

object konp extends TableSpec[konp_E](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
