package ct.dna.lakehouse.sr_raw.ct_gbl_ghp
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class vbrk_E(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  apm_approval_status_string: String,
  cmwae_string: String,
  kdgrp_string: String,
  bukrs_string: String,
  kurrf_dat_string: String,
  maber_string: String,
  zterm_string: String,
  vkorg_string: String,
  buchk_string: String,
  bdr_status_string: String,
  waerk_string: String,
  grwcu_string: String,
  sdm_version_string: String,
  zza1_process_string: String,
  spe_billing_ind_string: String,
  @Decimal(15, 2) netwr_decimal_15_2: BigDecimal,
  dpc_rel_string: String,
  taxk3_string: String,
  taxk1_string: String,
  ernam_string: String,
  belnr_string: String,
  counc_string: String,
  erzet_string: String,
  inco3_l_string: String,
  fksto_string: String,
  expkz_string: String,
  vkont_string: String,
  konda_string: String,
  taxk9_string: String,
  ad01fareg_string: String,
  intra_excl_string: String,
  bdr_ref_logsys_string: String,
  bstnk_vf_string: String,
  zlsch_string: String,
  mschl_string: String,
  taxk6_string: String,
  taxk8_string: String,
  xblnr_string: String,
  fk_source_sys_string: String,
  @Decimal(9, 5) kurrf_decimal_9_5: BigDecimal,
  xegdr_string: String,
  regio_string: String,
  j_1afitp_string: String,
  zza1_subdiv_string: String,
  fkara_string: String,
  custh_univ_sales_relvnce_string: String,
  zapcgkh_string: String,
  relik_string: String,
  akwae_string: String,
  taxk2_string: String,
  taxk5_string: String,
  numpg_string: String,
  kunag_string: String,
  exnum_string: String,
  @Decimal(9, 5) akkur_decimal_9_5: BigDecimal,
  kidno_string: String,
  land1_string: String,
  _dataaging_string: String,
  knuma_string: String,
  j_3gkbaul_string: String,
  vbeln_string: String,
  srcedoc_ext_comm_syst_type_string: String,
  ad01basdoc_string: String,
  stceg_l_string: String,
  stceg_h_string: String,
  bzirk_string: String,
  stceg_string: String,
  j_1tpbupl_string: String,
  kurst_string: String,
  @Decimal(21, 7) changed_on_decimal_21_7: BigDecimal,
  sppaym_string: String,
  draft_string: String,
  cityc_string: String,
  @Decimal(9, 5) cmkuf_decimal_9_5: BigDecimal,
  fkk_docstat_string: String,
  pspsd_string: String,
  valdt_string: String,
  vsbed_string: String,
  knkli_string: String,
  ktgrd_string: String,
  kalsm_string: String,
  custh_branch_uuid_string: String,
  taxk7_string: String,
  fkart_ab_string: String,
  fkart_rl_string: String,
  logsys_string: String,
  vtweg_string: String,
  sepon_string: String,
  rfbsk_string: String,
  poper_string: String,
  mansp_string: String,
  pbd_status_string: String,
  zukri_string: String,
  mandt_string: String,
  @Decimal(13, 2) mwsbk_decimal_13_2: BigDecimal,
  j_3gkenie_string: String,
  hityp_pr_string: String,
  vtref_string: String,
  apcgk_extendh_string: String,
  vbund_string: String,
  stafo_string: String,
  mndid_string: String,
  blart_string: String,
  inco1_string: String,
  valtg_string: String,
  zza1_cert_string: String,
  rplnr_string: String,
  sfakn_string: String,
  clrst_string: String,
  stwae_string: String,
  inco2_l_string: String,
  vbtyp_string: String,
  pay_type_string: String,
  fktyp_crm_string: String,
  dummy_billingdoc_incl_eew_ps_string: String,
  fkdat_rl_string: String,
  gjahr_string: String,
  kunrg_string: String,
  ico_lifnr_string: String,
  pltyp_string: String,
  zza1_numcert_string: String,
  spart_string: String,
  kunwe_string: String,
  landtx_string: String,
  bvtyp_string: String,
  taxk4_string: String,
  mrnkz_string: String,
  stgrd_string: String,
  cpkur_string: String,
  apm_approval_reason_string: String,
  intra_rel_string: String,
  inco2_string: String,
  zzexpdat_string: String,
  vf_todo_string: String,
  zzforeing_trade_string: String,
  aedat_string: String,
  uvprs_string: String,
  accrrel_string: String,
  zabdath_string: String,
  uvals_string: String,
  activedocument_string: String,
  vf_status_string: String,
  fksak_string: String,
  bdr_ref_vbtyp_string: String,
  fkart_string: String,
  abstk_string: String,
  nrzas_string: String,
  gbstk_string: String,
  knumv_string: String,
  bdr_ref_string: String,
  sppord_string: String,
  zuonr_string: String,
  lcnum_string: String,
  fktyp_string: String,
  vchrnmbr_string: String,
  kkber_string: String,
  mndvg_string: String,
  glo_log_ref1_hd_string: String,
  fkdat_string: String,
  kappl_string: String,
  bupla_string: String,
  erdat_string: String,
  incov_string: String
) extends Entity

object vbrk extends TableSpec[vbrk_E](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
