// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_e32

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_a016(
    @PK mandt: String,
    @PK kappl: String,
    @PK kschl: String,
    @PK evrtn: String,
    @PK evrtp: String,
    @PK datbi: String,
    datab: String,
    knumh: String,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String
) extends Entity

object a016
    extends TableSpec[E_a016](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[sr_raw.ct_gbl_e32.E_a016] {
  override def sourceTableSpec: TableSpec[sr_raw.ct_gbl_e32.E_a016] = sr_raw.ct_gbl_e32.a016
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("mandt", col("mandt_string")),
    ("kappl", col("kappl_string")),
    ("kschl", col("kschl_string")),
    ("evrtn", col("evrtn_string")),
    ("evrtp", col("evrtp_string")),
    ("datbi", col("datbi_string")),
    ("datab", col("datab_string")),
    ("knumh", col("knumh_string"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_a016(prefix: String) extends ColumnWithNameAccessor {
  val mandt: ColumnWithName = ColumnWithName(prefix + "mandt")
  val kappl: ColumnWithName = ColumnWithName(prefix + "kappl")
  val kschl: ColumnWithName = ColumnWithName(prefix + "kschl")
  val evrtn: ColumnWithName = ColumnWithName(prefix + "evrtn")
  val evrtp: ColumnWithName = ColumnWithName(prefix + "evrtp")
  val datbi: ColumnWithName = ColumnWithName(prefix + "datbi")
  val datab: ColumnWithName = ColumnWithName(prefix + "datab")
  val knumh: ColumnWithName = ColumnWithName(prefix + "knumh")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
}

object C_a016 extends C_a016("") {
  def as(alias: String): C_a016 = new C_a016(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
