// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_e32

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_e32.{afpo => sr_raw_afpo}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrAfpo(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK aufnr: String,
    @PK posnr: String,
    psobs: String,
    qunum: String,
    qupos: String,
    projn: String,
    plnum: String,
    strmp: String,
    etrmp: String,
    kdauf: String,
    kdpos: String,
    kdein: String,
    beskz: String,
    @Decimal(13, 3) psamg: java.math.BigDecimal,
    @Decimal(13, 3) psmng: java.math.BigDecimal,
    @Decimal(13, 3) wemng: java.math.BigDecimal,
    @Decimal(13, 3) iamng: java.math.BigDecimal,
    amein: String,
    meins: String,
    matnr: String,
    @Decimal(13, 3) pamng: java.math.BigDecimal,
    @Decimal(13, 3) pgmng: java.math.BigDecimal,
    knttp: String,
    tpauf: String,
    ltrmi: String,
    ltrmp: String,
    kalnr: String,
    @Decimal(3, 1) uebto: java.math.BigDecimal,
    uebtk: String,
    @Decimal(3, 1) untto: java.math.BigDecimal,
    insmk: String,
    wepos: String,
    bwtar: String,
    bwtty: String,
    pwerk: String,
    lgort: String,
    @Decimal(5, 0) umrez: java.math.BigDecimal,
    @Decimal(5, 0) umren: java.math.BigDecimal,
    @Decimal(3, 0) webaz: java.math.BigDecimal,
    elikz: String,
    safnr: String,
    verid: String,
    sernr: String,
    techs: String,
    dwerk: String,
    dauty: String,
    dauat: String,
    dgltp: String,
    dglts: String,
    dfrei: String,
    dnrel: String,
    verto: String,
    sobkz: String,
    kzvbr: String,
    @Decimal(13, 2) wewrt: java.math.BigDecimal,
    weunb: String,
    ablad: String,
    wempf: String,
    charg: String,
    gsber: String,
    weaed: String,
    cuobj: String,
    kbnkz: String,
    arsnr: String,
    arsps: String,
    krsnr: String,
    krsps: String,
    kckey: String,
    rtp01: String,
    rtp02: String,
    rtp03: String,
    rtp04: String,
    ksvon: String,
    ksbis: String,
    objnp: String,
    ndisr: String,
    @Decimal(13, 3) vfmng: java.math.BigDecimal,
    gsbtr: String,
    kzavc: String,
    kzbws: String,
    xloek: String,
    sernp: String,
    anzsn: Int,
    objtype: String,
    ch_proc: String,
    fxpru: String,
    cuobj_root: String,
    berid: String,
    techs_copy: String,
    sgt_scat: String,
    kunnr2: String,
    mill_oc_aufnr_u: String,
    @Decimal(13, 3) mill_oc_rumng: java.math.BigDecimal,
    mill_oc_sort: String
) extends Entity

object afpo extends TableSpec[SrAfpo] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_afpo] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_afpo] = sr_raw_afpo

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("aufnr", coalesce(col("aufnr_string"), lit(""))),
    ("posnr", coalesce(col("posnr_string"), lit(""))),
    ("psobs", col("psobs_string")),
    ("qunum", col("qunum_string")),
    ("qupos", col("qupos_string")),
    ("projn", col("projn_string")),
    ("plnum", col("plnum_string")),
    ("strmp", col("strmp_string")),
    ("etrmp", col("etrmp_string")),
    ("kdauf", col("kdauf_string")),
    ("kdpos", col("kdpos_string")),
    ("kdein", col("kdein_string")),
    ("beskz", col("beskz_string")),
    ("psamg", col("psamg_decimal_13_3")),
    ("psmng", col("psmng_decimal_13_3")),
    ("wemng", col("wemng_decimal_13_3")),
    ("iamng", col("iamng_decimal_13_3")),
    ("amein", col("amein_string")),
    ("meins", col("meins_string")),
    ("matnr", col("matnr_string")),
    ("pamng", col("pamng_decimal_13_3")),
    ("pgmng", col("pgmng_decimal_13_3")),
    ("knttp", col("knttp_string")),
    ("tpauf", col("tpauf_string")),
    ("ltrmi", col("ltrmi_string")),
    ("ltrmp", col("ltrmp_string")),
    ("kalnr", col("kalnr_string")),
    ("uebto", col("uebto_decimal_3_1")),
    ("uebtk", col("uebtk_string")),
    ("untto", col("untto_decimal_3_1")),
    ("insmk", col("insmk_string")),
    ("wepos", col("wepos_string")),
    ("bwtar", col("bwtar_string")),
    ("bwtty", col("bwtty_string")),
    ("pwerk", col("pwerk_string")),
    ("lgort", col("lgort_string")),
    ("umrez", col("umrez_decimal_5_0")),
    ("umren", col("umren_decimal_5_0")),
    ("webaz", col("webaz_decimal_3_0")),
    ("elikz", col("elikz_string")),
    ("safnr", col("safnr_string")),
    ("verid", col("verid_string")),
    ("sernr", col("sernr_string")),
    ("techs", col("techs_string")),
    ("dwerk", col("dwerk_string")),
    ("dauty", col("dauty_string")),
    ("dauat", col("dauat_string")),
    ("dgltp", col("dgltp_string")),
    ("dglts", col("dglts_string")),
    ("dfrei", col("dfrei_string")),
    ("dnrel", col("dnrel_string")),
    ("verto", col("verto_string")),
    ("sobkz", col("sobkz_string")),
    ("kzvbr", col("kzvbr_string")),
    ("wewrt", col("wewrt_decimal_13_2")),
    ("weunb", col("weunb_string")),
    ("ablad", col("ablad_string")),
    ("wempf", col("wempf_string")),
    ("charg", col("charg_string")),
    ("gsber", col("gsber_string")),
    ("weaed", col("weaed_string")),
    ("cuobj", col("cuobj_string")),
    ("kbnkz", col("kbnkz_string")),
    ("arsnr", col("arsnr_string")),
    ("arsps", col("arsps_string")),
    ("krsnr", col("krsnr_string")),
    ("krsps", col("krsps_string")),
    ("kckey", col("kckey_string")),
    ("rtp01", col("rtp01_string")),
    ("rtp02", col("rtp02_string")),
    ("rtp03", col("rtp03_string")),
    ("rtp04", col("rtp04_string")),
    ("ksvon", col("ksvon_string")),
    ("ksbis", col("ksbis_string")),
    ("objnp", col("objnp_string")),
    ("ndisr", col("ndisr_string")),
    ("vfmng", col("vfmng_decimal_13_3")),
    ("gsbtr", col("gsbtr_string")),
    ("kzavc", col("kzavc_string")),
    ("kzbws", col("kzbws_string")),
    ("xloek", col("xloek_string")),
    ("sernp", col("sernp_string")),
    ("anzsn", coalesce(col("anzsn_int"), lit(0))),
    ("objtype", col("objtype_string")),
    ("ch_proc", col("ch_proc_string")),
    ("fxpru", col("fxpru_string")),
    ("cuobj_root", col("cuobj_root_string")),
    ("berid", col("berid_string")),
    ("techs_copy", col("techs_copy_string")),
    ("sgt_scat", col("sgt_scat_string")),
    ("kunnr2", col("kunnr2_string")),
    ("mill_oc_aufnr_u", col("mill_oc_aufnr_u_string")),
    ("mill_oc_rumng", col("mill_oc_rumng_decimal_13_3")),
    ("mill_oc_sort", col("mill_oc_sort_string"))
  )
}
