// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_e32

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_e32.{afru => sr_raw_afru}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, hex, lit, struct}

case class SrAfru(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK rueck: String,
    @PK rmzhl: String,
    ersda: String,
    ernam: String,
    laeda: String,
    aenam: String,
    budat: String,
    arbid: String,
    werks: String,
    ltxa1: String,
    txtsp: String,
    @Decimal(9, 3) iserh: java.math.BigDecimal,
    zeier: String,
    ile01: String,
    @Decimal(13, 3) ism01: java.math.BigDecimal,
    ile02: String,
    @Decimal(13, 3) ism02: java.math.BigDecimal,
    ile03: String,
    @Decimal(13, 3) ism03: java.math.BigDecimal,
    ile04: String,
    @Decimal(13, 3) ism04: java.math.BigDecimal,
    ile05: String,
    @Decimal(13, 3) ism05: java.math.BigDecimal,
    ile06: String,
    @Decimal(13, 3) ism06: java.math.BigDecimal,
    abarb: String,
    @Decimal(7, 1) ismnw: java.math.BigDecimal,
    ismne: String,
    learr: String,
    @Decimal(5, 1) idaur: java.math.BigDecimal,
    idaue: String,
    zcode: String,
    loart: String,
    qualf: String,
    @Decimal(5, 2) anzma: java.math.BigDecimal,
    logrp: String,
    @Decimal(13, 3) gmnga: java.math.BigDecimal,
    @Decimal(13, 3) lmnga: java.math.BigDecimal,
    @Decimal(13, 3) xmnga: java.math.BigDecimal,
    gmein: String,
    meinh: String,
    grund: String,
    pernr: String,
    isdd: String,
    isdz: String,
    ierd: String,
    ierz: String,
    isbd: String,
    isbz: String,
    iebd: String,
    iebz: String,
    isad: String,
    isaz: String,
    iedd: String,
    iedz: String,
    pedd: String,
    pedz: String,
    wablnr: String,
    weblnr: String,
    aueru: String,
    ausor: String,
    stndr: String,
    manur: String,
    meilr: String,
    aufpl: String,
    aplzl: String,
    aufnr: String,
    aplfl: String,
    vornr: String,
    sumnr: String,
    @Decimal(9, 3) ofm01: java.math.BigDecimal,
    ofe01: String,
    lek01: String,
    @Decimal(9, 3) ofm02: java.math.BigDecimal,
    ofe02: String,
    lek02: String,
    @Decimal(9, 3) ofm03: java.math.BigDecimal,
    ofe03: String,
    lek03: String,
    @Decimal(9, 3) ofm04: java.math.BigDecimal,
    ofe04: String,
    lek04: String,
    @Decimal(9, 3) ofm05: java.math.BigDecimal,
    ofe05: String,
    lek05: String,
    @Decimal(9, 3) ofm06: java.math.BigDecimal,
    ofe06: String,
    lek06: String,
    @Decimal(7, 1) ofmnw: java.math.BigDecimal,
    ofmne: String,
    leknw: String,
    @Decimal(5, 1) odaur: java.math.BigDecimal,
    odaue: String,
    stokz: String,
    stzhl: String,
    @Decimal(13, 3) smeng: java.math.BigDecimal,
    rueck_mst: String,
    rmzhl_mst: String,
    pdsnr: String,
    kapid: String,
    split: Int,
    zausw: String,
    orind: String,
    origf: String,
    canum: String,
    belnr_ist: String,
    belnr_umb: String,
    @Decimal(13, 3) rmnga: java.math.BigDecimal,
    catsbelnr: String,
    satza: String,
    erzet: String,
    @Decimal(11, 2) catsprice: java.math.BigDecimal,
    catstcurr: String,
    @Decimal(5, 0) catspeinh: java.math.BigDecimal,
    bemot: String,
    @Decimal(13, 3) iprz1: java.math.BigDecimal,
    ipre1: String,
    iprk1: String,
    exnam: String,
    exerd: String,
    exerz: String,
    prz01: String,
    @Decimal(13, 3) oprz1: java.math.BigDecimal,
    opre1: String,
    skokrs: String,
    skostl: String,
    nodat: String,
    ismnu: String,
    ofmnu: String,
    packno: String,
    extid: String,
    schgrup: String,
    kaptprog: String,
    obmat: String,
    obcha: String,
    licha: String,
    myear: String,
    me_sfcid: String,
    @Decimal(13, 3) me_2nd_conf_qty: java.math.BigDecimal,
    role_id: String,
    ucmat: String,
    uccha: String,
    wty_ind: String
) extends Entity

object afru extends TableSpec[SrAfru] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_afru] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_afru] = sr_raw_afru

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("rueck", coalesce(col("rueck_string"), lit(""))),
    ("rmzhl", coalesce(col("rmzhl_string"), lit(""))),
    ("ersda", col("ersda_string")),
    ("ernam", col("ernam_string")),
    ("laeda", col("laeda_string")),
    ("aenam", col("aenam_string")),
    ("budat", col("budat_string")),
    ("arbid", col("arbid_string")),
    ("werks", col("werks_string")),
    ("ltxa1", col("ltxa1_string")),
    ("txtsp", col("txtsp_string")),
    ("iserh", col("iserh_decimal_9_3")),
    ("zeier", col("zeier_string")),
    ("ile01", col("ile01_string")),
    ("ism01", col("ism01_decimal_13_3")),
    ("ile02", col("ile02_string")),
    ("ism02", col("ism02_decimal_13_3")),
    ("ile03", col("ile03_string")),
    ("ism03", col("ism03_decimal_13_3")),
    ("ile04", col("ile04_string")),
    ("ism04", col("ism04_decimal_13_3")),
    ("ile05", col("ile05_string")),
    ("ism05", col("ism05_decimal_13_3")),
    ("ile06", col("ile06_string")),
    ("ism06", col("ism06_decimal_13_3")),
    ("abarb", col("abarb_string")),
    ("ismnw", col("ismnw_decimal_7_1")),
    ("ismne", col("ismne_string")),
    ("learr", col("learr_string")),
    ("idaur", col("idaur_decimal_5_1")),
    ("idaue", col("idaue_string")),
    ("zcode", col("zcode_string")),
    ("loart", col("loart_string")),
    ("qualf", col("qualf_string")),
    ("anzma", col("anzma_decimal_5_2")),
    ("logrp", col("logrp_string")),
    ("gmnga", col("gmnga_decimal_13_3")),
    ("lmnga", col("lmnga_decimal_13_3")),
    ("xmnga", col("xmnga_decimal_13_3")),
    ("gmein", col("gmein_string")),
    ("meinh", col("meinh_string")),
    ("grund", col("grund_string")),
    ("pernr", col("pernr_string")),
    ("isdd", col("isdd_string")),
    ("isdz", col("isdz_string")),
    ("ierd", col("ierd_string")),
    ("ierz", col("ierz_string")),
    ("isbd", col("isbd_string")),
    ("isbz", col("isbz_string")),
    ("iebd", col("iebd_string")),
    ("iebz", col("iebz_string")),
    ("isad", col("isad_string")),
    ("isaz", col("isaz_string")),
    ("iedd", col("iedd_string")),
    ("iedz", col("iedz_string")),
    ("pedd", col("pedd_string")),
    ("pedz", col("pedz_string")),
    ("wablnr", col("wablnr_string")),
    ("weblnr", col("weblnr_string")),
    ("aueru", col("aueru_string")),
    ("ausor", col("ausor_string")),
    ("stndr", col("stndr_string")),
    ("manur", col("manur_string")),
    ("meilr", col("meilr_string")),
    ("aufpl", col("aufpl_string")),
    ("aplzl", col("aplzl_string")),
    ("aufnr", col("aufnr_string")),
    ("aplfl", col("aplfl_string")),
    ("vornr", col("vornr_string")),
    ("sumnr", col("sumnr_string")),
    ("ofm01", col("ofm01_decimal_9_3")),
    ("ofe01", col("ofe01_string")),
    ("lek01", col("lek01_string")),
    ("ofm02", col("ofm02_decimal_9_3")),
    ("ofe02", col("ofe02_string")),
    ("lek02", col("lek02_string")),
    ("ofm03", col("ofm03_decimal_9_3")),
    ("ofe03", col("ofe03_string")),
    ("lek03", col("lek03_string")),
    ("ofm04", col("ofm04_decimal_9_3")),
    ("ofe04", col("ofe04_string")),
    ("lek04", col("lek04_string")),
    ("ofm05", col("ofm05_decimal_9_3")),
    ("ofe05", col("ofe05_string")),
    ("lek05", col("lek05_string")),
    ("ofm06", col("ofm06_decimal_9_3")),
    ("ofe06", col("ofe06_string")),
    ("lek06", col("lek06_string")),
    ("ofmnw", col("ofmnw_decimal_7_1")),
    ("ofmne", col("ofmne_string")),
    ("leknw", col("leknw_string")),
    ("odaur", col("odaur_decimal_5_1")),
    ("odaue", col("odaue_string")),
    ("stokz", col("stokz_string")),
    ("stzhl", col("stzhl_string")),
    ("smeng", col("smeng_decimal_13_3")),
    ("rueck_mst", col("rueck_mst_string")),
    ("rmzhl_mst", col("rmzhl_mst_string")),
    ("pdsnr", col("pdsnr_string")),
    ("kapid", col("kapid_string")),
    ("split", coalesce(col("split_int"), lit(0))),
    ("zausw", col("zausw_string")),
    ("orind", col("orind_string")),
    ("origf", col("origf_string")),
    ("canum", col("canum_string")),
    ("belnr_ist", col("belnr_ist_string")),
    ("belnr_umb", col("belnr_umb_string")),
    ("rmnga", col("rmnga_decimal_13_3")),
    ("catsbelnr", col("catsbelnr_string")),
    ("satza", col("satza_string")),
    ("erzet", col("erzet_string")),
    ("catsprice", col("catsprice_decimal_11_2")),
    ("catstcurr", col("catstcurr_string")),
    ("catspeinh", col("catspeinh_decimal_5_0")),
    ("bemot", col("bemot_string")),
    ("iprz1", col("iprz1_decimal_13_3")),
    ("ipre1", col("ipre1_string")),
    ("iprk1", col("iprk1_string")),
    ("exnam", col("exnam_string")),
    ("exerd", col("exerd_string")),
    ("exerz", col("exerz_string")),
    ("prz01", col("prz01_string")),
    ("oprz1", col("oprz1_decimal_13_3")),
    ("opre1", col("opre1_string")),
    ("skokrs", col("skokrs_string")),
    ("skostl", col("skostl_string")),
    ("nodat", col("nodat_string")),
    ("ismnu", col("ismnu_string")),
    ("ofmnu", col("ofmnu_string")),
    ("packno", col("packno_string")),
    ("extid", hex(col("extid_binary"))),
    ("schgrup", col("schgrup_string")),
    ("kaptprog", col("kaptprog_string")),
    ("obmat", col("obmat_string")),
    ("obcha", col("obcha_string")),
    ("licha", col("licha_string")),
    ("myear", col("myear_string")),
    ("me_sfcid", col("me_sfcid_string")),
    ("me_2nd_conf_qty", col("me_2nd_conf_qty_decimal_13_3")),
    ("role_id", col("role_id_string")),
    ("ucmat", col("ucmat_string")),
    ("uccha", col("uccha_string")),
    ("wty_ind", col("wty_ind_string"))
  )
}
