// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_e32

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_e32.{afvc => sr_raw_afvc}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, hex, lit, struct}

case class SrAfvc(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK aufpl: String,
    @PK aplzl: String,
    plnfl: String,
    plnkn: String,
    plnal: String,
    plnty: String,
    @Decimal(3, 0) vintv: java.math.BigDecimal,
    plnnr: String,
    zaehl: String,
    vornr: String,
    steus: String,
    arbid: String,
    pdest: String,
    werks: String,
    ktsch: String,
    ltxa1: String,
    ltxa2: String,
    txtsp: String,
    vplty: String,
    vplnr: String,
    vplal: String,
    vplfl: String,
    vgwts: String,
    lar01: String,
    lar02: String,
    lar03: String,
    lar04: String,
    lar05: String,
    lar06: String,
    zerma: String,
    zgdat: String,
    zcode: String,
    zulnr: String,
    @Decimal(3, 0) loanz: java.math.BigDecimal,
    loart: String,
    rsanz: String,
    qualf: String,
    @Decimal(5, 2) anzma: java.math.BigDecimal,
    rfgrp: String,
    rfsch: String,
    rasch: String,
    @Decimal(5, 3) aufak: java.math.BigDecimal,
    logrp: String,
    uemus: String,
    uekan: String,
    flies: String,
    spmus: String,
    @Decimal(3, 0) splim: java.math.BigDecimal,
    ablipkz: String,
    rstra: String,
    sumnr: String,
    sortl: String,
    lifnr: String,
    @Decimal(11, 2) preis: java.math.BigDecimal,
    @Decimal(5, 0) peinh: java.math.BigDecimal,
    sakto: String,
    waers: String,
    infnr: String,
    esokz: String,
    ekorg: String,
    ekgrp: String,
    kzlgf: String,
    kzwrtf: String,
    matkl: String,
    ddehn: String,
    anzzl: Int,
    prznt: Int,
    mlstn: String,
    pprio: String,
    bukrs: String,
    anfko: String,
    anfkokrs: String,
    indet: String,
    larnt: String,
    @Decimal(11, 2) prkst: java.math.BigDecimal,
    aplfl: String,
    rueck: String,
    rmzhl: String,
    projn: String,
    objnr: String,
    @Decimal(3, 0) spanz: java.math.BigDecimal,
    bedid: String,
    bedzl: String,
    banfn: String,
    bnfpo: String,
    lek01: String,
    lek02: String,
    lek03: String,
    lek04: String,
    lek05: String,
    lek06: String,
    selkz: String,
    kalid: String,
    frsp: String,
    stdkn: String,
    anlzu: String,
    istru: String,
    istty: String,
    istnr: String,
    istkn: String,
    istpo: String,
    iupoz: String,
    ebort: String,
    vertl: String,
    leknw: String,
    nprio: String,
    pvzkn: String,
    phflg: String,
    phseq: String,
    knobj: String,
    erfsicht: String,
    qppktabs: String,
    otype: String,
    objektid: String,
    qlkapar: String,
    rstuf: String,
    nptxtky: String,
    subsys: String,
    pspnr: String,
    packno: String,
    txjcd: String,
    scope: String,
    gsber: String,
    prctr: String,
    no_disp: String,
    qkzprzeit: String,
    qkzztmg1: String,
    qkzprmeng: String,
    qkzprfrei: String,
    kzfeat: String,
    qkztlsbest: String,
    aennr: String,
    cuobj_arb: String,
    @Decimal(8, 0) evgew: java.math.BigDecimal,
    arbii: String,
    werki: String,
    cy_seqnrv: String,
    kapt_puffr: Int,
    ebeln: String,
    ebelp: String,
    wempf: String,
    ablad: String,
    clasf: String,
    frunv: String,
    zschl: String,
    kalsm: String,
    sched_end: String,
    netzkont: String,
    owaer: String,
    afnam: String,
    bednr: String,
    kzfix: String,
    pernr: String,
    frdlb: String,
    qpart: String,
    loekz: String,
    @Decimal(9, 5) wkurs: java.math.BigDecimal,
    prod_act: String,
    fplnr: String,
    objtype: String,
    ch_proc: String,
    klvar: String,
    kalnr: String,
    fordn: String,
    fordp: String,
    @Decimal(11, 2) mat_prkst: java.math.BigDecimal,
    prz01: String,
    rfpnt: String,
    func_area: String,
    techs: String,
    adpsp: String,
    rfippnt: String,
    mes_operid: String,
    mes_stepid: String,
    _cum_cuguid: String,
    _isdfps_objnr: String,
    mill_oc_aufnr_mo: String,
    wty_ind: String,
    tplnr: String,
    equnr: String
) extends Entity

object afvc extends TableSpec[SrAfvc] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_afvc] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_afvc] = sr_raw_afvc

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("aufpl", coalesce(col("aufpl_string"), lit(""))),
    ("aplzl", coalesce(col("aplzl_string"), lit(""))),
    ("plnfl", col("plnfl_string")),
    ("plnkn", col("plnkn_string")),
    ("plnal", col("plnal_string")),
    ("plnty", col("plnty_string")),
    ("vintv", col("vintv_decimal_3_0")),
    ("plnnr", col("plnnr_string")),
    ("zaehl", col("zaehl_string")),
    ("vornr", col("vornr_string")),
    ("steus", col("steus_string")),
    ("arbid", col("arbid_string")),
    ("pdest", col("pdest_string")),
    ("werks", col("werks_string")),
    ("ktsch", col("ktsch_string")),
    ("ltxa1", col("ltxa1_string")),
    ("ltxa2", col("ltxa2_string")),
    ("txtsp", col("txtsp_string")),
    ("vplty", col("vplty_string")),
    ("vplnr", col("vplnr_string")),
    ("vplal", col("vplal_string")),
    ("vplfl", col("vplfl_string")),
    ("vgwts", col("vgwts_string")),
    ("lar01", col("lar01_string")),
    ("lar02", col("lar02_string")),
    ("lar03", col("lar03_string")),
    ("lar04", col("lar04_string")),
    ("lar05", col("lar05_string")),
    ("lar06", col("lar06_string")),
    ("zerma", col("zerma_string")),
    ("zgdat", col("zgdat_string")),
    ("zcode", col("zcode_string")),
    ("zulnr", col("zulnr_string")),
    ("loanz", col("loanz_decimal_3_0")),
    ("loart", col("loart_string")),
    ("rsanz", col("rsanz_string")),
    ("qualf", col("qualf_string")),
    ("anzma", col("anzma_decimal_5_2")),
    ("rfgrp", col("rfgrp_string")),
    ("rfsch", col("rfsch_string")),
    ("rasch", col("rasch_string")),
    ("aufak", col("aufak_decimal_5_3")),
    ("logrp", col("logrp_string")),
    ("uemus", col("uemus_string")),
    ("uekan", col("uekan_string")),
    ("flies", col("flies_string")),
    ("spmus", col("spmus_string")),
    ("splim", col("splim_decimal_3_0")),
    ("ablipkz", col("ablipkz_string")),
    ("rstra", col("rstra_string")),
    ("sumnr", col("sumnr_string")),
    ("sortl", col("sortl_string")),
    ("lifnr", col("lifnr_string")),
    ("preis", col("preis_decimal_11_2")),
    ("peinh", col("peinh_decimal_5_0")),
    ("sakto", col("sakto_string")),
    ("waers", col("waers_string")),
    ("infnr", col("infnr_string")),
    ("esokz", col("esokz_string")),
    ("ekorg", col("ekorg_string")),
    ("ekgrp", col("ekgrp_string")),
    ("kzlgf", col("kzlgf_string")),
    ("kzwrtf", col("kzwrtf_string")),
    ("matkl", col("matkl_string")),
    ("ddehn", col("ddehn_string")),
    ("anzzl", coalesce(col("anzzl_int"), lit(0))),
    ("prznt", coalesce(col("prznt_int"), lit(0))),
    ("mlstn", col("mlstn_string")),
    ("pprio", col("pprio_string")),
    ("bukrs", col("bukrs_string")),
    ("anfko", col("anfko_string")),
    ("anfkokrs", col("anfkokrs_string")),
    ("indet", col("indet_string")),
    ("larnt", col("larnt_string")),
    ("prkst", col("prkst_decimal_11_2")),
    ("aplfl", col("aplfl_string")),
    ("rueck", col("rueck_string")),
    ("rmzhl", col("rmzhl_string")),
    ("projn", col("projn_string")),
    ("objnr", col("objnr_string")),
    ("spanz", col("spanz_decimal_3_0")),
    ("bedid", col("bedid_string")),
    ("bedzl", col("bedzl_string")),
    ("banfn", col("banfn_string")),
    ("bnfpo", col("bnfpo_string")),
    ("lek01", col("lek01_string")),
    ("lek02", col("lek02_string")),
    ("lek03", col("lek03_string")),
    ("lek04", col("lek04_string")),
    ("lek05", col("lek05_string")),
    ("lek06", col("lek06_string")),
    ("selkz", col("selkz_string")),
    ("kalid", col("kalid_string")),
    ("frsp", col("frsp_string")),
    ("stdkn", col("stdkn_string")),
    ("anlzu", col("anlzu_string")),
    ("istru", col("istru_string")),
    ("istty", col("istty_string")),
    ("istnr", col("istnr_string")),
    ("istkn", col("istkn_string")),
    ("istpo", col("istpo_string")),
    ("iupoz", col("iupoz_string")),
    ("ebort", col("ebort_string")),
    ("vertl", col("vertl_string")),
    ("leknw", col("leknw_string")),
    ("nprio", col("nprio_string")),
    ("pvzkn", col("pvzkn_string")),
    ("phflg", col("phflg_string")),
    ("phseq", col("phseq_string")),
    ("knobj", col("knobj_string")),
    ("erfsicht", col("erfsicht_string")),
    ("qppktabs", col("qppktabs_string")),
    ("otype", col("otype_string")),
    ("objektid", col("objektid_string")),
    ("qlkapar", col("qlkapar_string")),
    ("rstuf", col("rstuf_string")),
    ("nptxtky", col("nptxtky_string")),
    ("subsys", col("subsys_string")),
    ("pspnr", col("pspnr_string")),
    ("packno", col("packno_string")),
    ("txjcd", col("txjcd_string")),
    ("scope", col("scope_string")),
    ("gsber", col("gsber_string")),
    ("prctr", col("prctr_string")),
    ("no_disp", col("no_disp_string")),
    ("qkzprzeit", col("qkzprzeit_string")),
    ("qkzztmg1", col("qkzztmg1_string")),
    ("qkzprmeng", col("qkzprmeng_string")),
    ("qkzprfrei", col("qkzprfrei_string")),
    ("kzfeat", col("kzfeat_string")),
    ("qkztlsbest", col("qkztlsbest_string")),
    ("aennr", col("aennr_string")),
    ("cuobj_arb", col("cuobj_arb_string")),
    ("evgew", col("evgew_decimal_8_0")),
    ("arbii", col("arbii_string")),
    ("werki", col("werki_string")),
    ("cy_seqnrv", col("cy_seqnrv_string")),
    ("kapt_puffr", coalesce(col("kapt_puffr_int"), lit(0))),
    ("ebeln", col("ebeln_string")),
    ("ebelp", col("ebelp_string")),
    ("wempf", col("wempf_string")),
    ("ablad", col("ablad_string")),
    ("clasf", col("clasf_string")),
    ("frunv", col("frunv_string")),
    ("zschl", col("zschl_string")),
    ("kalsm", col("kalsm_string")),
    ("sched_end", col("sched_end_string")),
    ("netzkont", col("netzkont_string")),
    ("owaer", col("owaer_string")),
    ("afnam", col("afnam_string")),
    ("bednr", col("bednr_string")),
    ("kzfix", col("kzfix_string")),
    ("pernr", col("pernr_string")),
    ("frdlb", col("frdlb_string")),
    ("qpart", col("qpart_string")),
    ("loekz", col("loekz_string")),
    ("wkurs", col("wkurs_decimal_9_5")),
    ("prod_act", col("prod_act_string")),
    ("fplnr", col("fplnr_string")),
    ("objtype", col("objtype_string")),
    ("ch_proc", col("ch_proc_string")),
    ("klvar", col("klvar_string")),
    ("kalnr", col("kalnr_string")),
    ("fordn", col("fordn_string")),
    ("fordp", col("fordp_string")),
    ("mat_prkst", col("mat_prkst_decimal_11_2")),
    ("prz01", col("prz01_string")),
    ("rfpnt", col("rfpnt_string")),
    ("func_area", col("func_area_string")),
    ("techs", col("techs_string")),
    ("adpsp", col("adpsp_string")),
    ("rfippnt", col("rfippnt_string")),
    ("mes_operid", col("mes_operid_string")),
    ("mes_stepid", col("mes_stepid_string")),
    ("_cum_cuguid", hex(col("_cum_cuguid_binary"))),
    ("_isdfps_objnr", col("_isdfps_objnr_string")),
    ("mill_oc_aufnr_mo", col("mill_oc_aufnr_mo_string")),
    ("wty_ind", col("wty_ind_string")),
    ("tplnr", col("tplnr_string")),
    ("equnr", col("equnr_string"))
  )
}
