// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_e32

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_e32.{aufk => sr_raw_aufk}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrAufk(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK aufnr: String,
    auart: String,
    autyp: String,
    refnr: String,
    ernam: String,
    erdat: String,
    aenam: String,
    aedat: String,
    ktext: String,
    ltext: String,
    bukrs: String,
    werks: String,
    gsber: String,
    kokrs: String,
    cckey: String,
    kostv: String,
    stort: String,
    sowrk: String,
    astkz: String,
    waers: String,
    astnr: String,
    stdat: String,
    estnr: String,
    phas0: String,
    phas1: String,
    phas2: String,
    phas3: String,
    pdat1: String,
    pdat2: String,
    pdat3: String,
    idat1: String,
    idat2: String,
    idat3: String,
    objid: String,
    vogrp: String,
    loekz: String,
    plgkz: String,
    kvewe: String,
    kappl: String,
    kalsm: String,
    zschl: String,
    abkrs: String,
    kstar: String,
    kostl: String,
    saknr: String,
    setnm: String,
    cycle: String,
    sdate: String,
    seqnr: String,
    user0: String,
    user1: String,
    user2: String,
    user3: String,
    @Decimal(11, 2) user4: java.math.BigDecimal,
    user5: String,
    user6: String,
    user7: String,
    user8: String,
    user9: String,
    objnr: String,
    prctr: String,
    pspel: String,
    awsls: String,
    abgsl: String,
    txjcd: String,
    func_area: String,
    scope: String,
    plint: String,
    kdauf: String,
    kdpos: String,
    aufex: String,
    ivpro: String,
    logsystem: String,
    flg_mltps: String,
    abukr: String,
    akstl: String,
    sizecl: String,
    izwek: String,
    umwkz: String,
    kstempf: String,
    zschm: String,
    pkosa: String,
    anfaufnr: String,
    procnr: String,
    proty: String,
    rsord: String,
    bemot: String,
    adrnra: String,
    erfzeit: String,
    aezeit: String,
    cstg_vrnt: String,
    costestnr: String,
    veraa_user: String,
    zz_formt: String,
    vname: String,
    recid: String,
    etype: String,
    otype: String,
    jv_jibcl: String,
    jv_jibsa: String,
    jv_oco: String,
    _cum_indcu: String,
    _cum_cmnum: String,
    _cum_auest: String,
    _cum_desnum: String,
    vaplz: String,
    wawrk: String,
    ferc_ind: String,
    claim_control: String,
    update_needed: String,
    update_control: String
) extends Entity

object aufk extends TableSpec[SrAufk] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_aufk] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_aufk] = sr_raw_aufk

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("aufnr", coalesce(col("aufnr_string"), lit(""))),
    ("auart", col("auart_string")),
    ("autyp", col("autyp_string")),
    ("refnr", col("refnr_string")),
    ("ernam", col("ernam_string")),
    ("erdat", col("erdat_string")),
    ("aenam", col("aenam_string")),
    ("aedat", col("aedat_string")),
    ("ktext", col("ktext_string")),
    ("ltext", col("ltext_string")),
    ("bukrs", col("bukrs_string")),
    ("werks", col("werks_string")),
    ("gsber", col("gsber_string")),
    ("kokrs", col("kokrs_string")),
    ("cckey", col("cckey_string")),
    ("kostv", col("kostv_string")),
    ("stort", col("stort_string")),
    ("sowrk", col("sowrk_string")),
    ("astkz", col("astkz_string")),
    ("waers", col("waers_string")),
    ("astnr", col("astnr_string")),
    ("stdat", col("stdat_string")),
    ("estnr", col("estnr_string")),
    ("phas0", col("phas0_string")),
    ("phas1", col("phas1_string")),
    ("phas2", col("phas2_string")),
    ("phas3", col("phas3_string")),
    ("pdat1", col("pdat1_string")),
    ("pdat2", col("pdat2_string")),
    ("pdat3", col("pdat3_string")),
    ("idat1", col("idat1_string")),
    ("idat2", col("idat2_string")),
    ("idat3", col("idat3_string")),
    ("objid", col("objid_string")),
    ("vogrp", col("vogrp_string")),
    ("loekz", col("loekz_string")),
    ("plgkz", col("plgkz_string")),
    ("kvewe", col("kvewe_string")),
    ("kappl", col("kappl_string")),
    ("kalsm", col("kalsm_string")),
    ("zschl", col("zschl_string")),
    ("abkrs", col("abkrs_string")),
    ("kstar", col("kstar_string")),
    ("kostl", col("kostl_string")),
    ("saknr", col("saknr_string")),
    ("setnm", col("setnm_string")),
    ("cycle", col("cycle_string")),
    ("sdate", col("sdate_string")),
    ("seqnr", col("seqnr_string")),
    ("user0", col("user0_string")),
    ("user1", col("user1_string")),
    ("user2", col("user2_string")),
    ("user3", col("user3_string")),
    ("user4", col("user4_decimal_11_2")),
    ("user5", col("user5_string")),
    ("user6", col("user6_string")),
    ("user7", col("user7_string")),
    ("user8", col("user8_string")),
    ("user9", col("user9_string")),
    ("objnr", col("objnr_string")),
    ("prctr", col("prctr_string")),
    ("pspel", col("pspel_string")),
    ("awsls", col("awsls_string")),
    ("abgsl", col("abgsl_string")),
    ("txjcd", col("txjcd_string")),
    ("func_area", col("func_area_string")),
    ("scope", col("scope_string")),
    ("plint", col("plint_string")),
    ("kdauf", col("kdauf_string")),
    ("kdpos", col("kdpos_string")),
    ("aufex", col("aufex_string")),
    ("ivpro", col("ivpro_string")),
    ("logsystem", col("logsystem_string")),
    ("flg_mltps", col("flg_mltps_string")),
    ("abukr", col("abukr_string")),
    ("akstl", col("akstl_string")),
    ("sizecl", col("sizecl_string")),
    ("izwek", col("izwek_string")),
    ("umwkz", col("umwkz_string")),
    ("kstempf", col("kstempf_string")),
    ("zschm", col("zschm_string")),
    ("pkosa", col("pkosa_string")),
    ("anfaufnr", col("anfaufnr_string")),
    ("procnr", col("procnr_string")),
    ("proty", col("proty_string")),
    ("rsord", col("rsord_string")),
    ("bemot", col("bemot_string")),
    ("adrnra", col("adrnra_string")),
    ("erfzeit", col("erfzeit_string")),
    ("aezeit", col("aezeit_string")),
    ("cstg_vrnt", col("cstg_vrnt_string")),
    ("costestnr", col("costestnr_string")),
    ("veraa_user", col("veraa_user_string")),
    ("zz_formt", col("zz_formt_string")),
    ("vname", col("vname_string")),
    ("recid", col("recid_string")),
    ("etype", col("etype_string")),
    ("otype", col("otype_string")),
    ("jv_jibcl", col("jv_jibcl_string")),
    ("jv_jibsa", col("jv_jibsa_string")),
    ("jv_oco", col("jv_oco_string")),
    ("_cum_indcu", col("_cum_indcu_string")),
    ("_cum_cmnum", col("_cum_cmnum_string")),
    ("_cum_auest", col("_cum_auest_string")),
    ("_cum_desnum", col("_cum_desnum_string")),
    ("vaplz", col("vaplz_string")),
    ("wawrk", col("wawrk_string")),
    ("ferc_ind", col("ferc_ind_string")),
    ("claim_control", col("claim_control_string")),
    ("update_needed", col("update_needed_string")),
    ("update_control", col("update_control_string"))
  )
}
