// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_e32

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_e32.{eine => sr_raw_eine}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrEine(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK infnr: String,
    @PK ekorg: String,
    @PK esokz: String,
    @PK werks: String,
    loekz: String,
    erdat: String,
    ernam: String,
    ekgrp: String,
    waers: String,
    bonus: String,
    mgbon: String,
    @Decimal(13, 3) minbm: java.math.BigDecimal,
    @Decimal(13, 3) norbm: java.math.BigDecimal,
    @Decimal(3, 0) aplfz: java.math.BigDecimal,
    @Decimal(3, 1) uebto: java.math.BigDecimal,
    uebtk: String,
    @Decimal(3, 1) untto: java.math.BigDecimal,
    angnr: String,
    angdt: String,
    anfnr: String,
    anfps: String,
    abskz: String,
    amodv: String,
    amodb: String,
    @Decimal(15, 3) amobm: java.math.BigDecimal,
    @Decimal(15, 2) amobw: java.math.BigDecimal,
    @Decimal(15, 3) amoam: java.math.BigDecimal,
    @Decimal(15, 2) amoaw: java.math.BigDecimal,
    amors: String,
    bstyp: String,
    ebeln: String,
    ebelp: String,
    datlb: String,
    @Decimal(11, 2) netpr: java.math.BigDecimal,
    @Decimal(5, 0) peinh: java.math.BigDecimal,
    bprme: String,
    prdat: String,
    @Decimal(5, 0) bpumz: java.math.BigDecimal,
    @Decimal(5, 0) bpumn: java.math.BigDecimal,
    mtxno: String,
    webre: String,
    @Decimal(11, 2) effpr: java.math.BigDecimal,
    ekkol: String,
    sktof: String,
    kzabs: String,
    mwskz: String,
    bwtar: String,
    ebonu: String,
    evers: String,
    exprf: String,
    bstae: String,
    meprf: String,
    inco1: String,
    inco2: String,
    xersn: String,
    ebon2: String,
    ebon3: String,
    ebonf: String,
    @Decimal(4, 0) mhdrz: java.math.BigDecimal,
    verid: String,
    @Decimal(13, 3) bstma: java.math.BigDecimal,
    rdprf: String,
    megru: String,
    j_1bnbm: String,
    spe_cre_ref_doc: String,
    iprkz: String,
    co_order: String,
    vendor_rma_req: String,
    diff_invoice: String,
    incov: String,
    inco2_l: String,
    inco3_l: String,
    mrpind: String,
    sgt_ssrel: String,
    transport_chain: String,
    @Decimal(3, 0) staging_time: java.math.BigDecimal
) extends Entity

object eine extends TableSpec[SrEine] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_eine] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_eine] = sr_raw_eine

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("infnr", coalesce(col("infnr_string"), lit(""))),
    ("ekorg", coalesce(col("ekorg_string"), lit(""))),
    ("esokz", coalesce(col("esokz_string"), lit(""))),
    ("werks", coalesce(col("werks_string"), lit(""))),
    ("loekz", col("loekz_string")),
    ("erdat", col("erdat_string")),
    ("ernam", col("ernam_string")),
    ("ekgrp", col("ekgrp_string")),
    ("waers", col("waers_string")),
    ("bonus", col("bonus_string")),
    ("mgbon", col("mgbon_string")),
    ("minbm", col("minbm_decimal_13_3")),
    ("norbm", col("norbm_decimal_13_3")),
    ("aplfz", col("aplfz_decimal_3_0")),
    ("uebto", col("uebto_decimal_3_1")),
    ("uebtk", col("uebtk_string")),
    ("untto", col("untto_decimal_3_1")),
    ("angnr", col("angnr_string")),
    ("angdt", col("angdt_string")),
    ("anfnr", col("anfnr_string")),
    ("anfps", col("anfps_string")),
    ("abskz", col("abskz_string")),
    ("amodv", col("amodv_string")),
    ("amodb", col("amodb_string")),
    ("amobm", col("amobm_decimal_15_3")),
    ("amobw", col("amobw_decimal_15_2")),
    ("amoam", col("amoam_decimal_15_3")),
    ("amoaw", col("amoaw_decimal_15_2")),
    ("amors", col("amors_string")),
    ("bstyp", col("bstyp_string")),
    ("ebeln", col("ebeln_string")),
    ("ebelp", col("ebelp_string")),
    ("datlb", col("datlb_string")),
    ("netpr", col("netpr_decimal_11_2")),
    ("peinh", col("peinh_decimal_5_0")),
    ("bprme", col("bprme_string")),
    ("prdat", col("prdat_string")),
    ("bpumz", col("bpumz_decimal_5_0")),
    ("bpumn", col("bpumn_decimal_5_0")),
    ("mtxno", col("mtxno_string")),
    ("webre", col("webre_string")),
    ("effpr", col("effpr_decimal_11_2")),
    ("ekkol", col("ekkol_string")),
    ("sktof", col("sktof_string")),
    ("kzabs", col("kzabs_string")),
    ("mwskz", col("mwskz_string")),
    ("bwtar", col("bwtar_string")),
    ("ebonu", col("ebonu_string")),
    ("evers", col("evers_string")),
    ("exprf", col("exprf_string")),
    ("bstae", col("bstae_string")),
    ("meprf", col("meprf_string")),
    ("inco1", col("inco1_string")),
    ("inco2", col("inco2_string")),
    ("xersn", col("xersn_string")),
    ("ebon2", col("ebon2_string")),
    ("ebon3", col("ebon3_string")),
    ("ebonf", col("ebonf_string")),
    ("mhdrz", col("mhdrz_decimal_4_0")),
    ("verid", col("verid_string")),
    ("bstma", col("bstma_decimal_13_3")),
    ("rdprf", col("rdprf_string")),
    ("megru", col("megru_string")),
    ("j_1bnbm", col("j_1bnbm_string")),
    ("spe_cre_ref_doc", col("spe_cre_ref_doc_string")),
    ("iprkz", col("iprkz_string")),
    ("co_order", col("co_order_string")),
    ("vendor_rma_req", col("vendor_rma_req_string")),
    ("diff_invoice", col("diff_invoice_string")),
    ("incov", col("incov_string")),
    ("inco2_l", col("inco2_l_string")),
    ("inco3_l", col("inco3_l_string")),
    ("mrpind", col("mrpind_string")),
    ("sgt_ssrel", col("sgt_ssrel_string")),
    ("transport_chain", col("transport_chain_string")),
    ("staging_time", col("staging_time_decimal_3_0"))
  )
}
