// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_e32

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_e32.{marc => sr_raw_marc}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrMarc(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK matnr: String,
    @PK werks: String,
    pstat: String,
    lvorm: String,
    bwtty: String,
    xchar: String,
    mmsta: String,
    mmstd: String,
    maabc: String,
    kzkri: String,
    ekgrp: String,
    ausme: String,
    dispr: String,
    dismm: String,
    dispo: String,
    kzdie: String,
    @Decimal(3, 0) plifz: java.math.BigDecimal,
    @Decimal(3, 0) webaz: java.math.BigDecimal,
    perkz: String,
    @Decimal(5, 2) ausss: java.math.BigDecimal,
    disls: String,
    beskz: String,
    sobsl: String,
    @Decimal(13, 3) minbe: java.math.BigDecimal,
    @Decimal(13, 3) eisbe: java.math.BigDecimal,
    @Decimal(13, 3) bstmi: java.math.BigDecimal,
    @Decimal(13, 3) bstma: java.math.BigDecimal,
    @Decimal(13, 3) bstfe: java.math.BigDecimal,
    @Decimal(13, 3) bstrf: java.math.BigDecimal,
    @Decimal(13, 3) mabst: java.math.BigDecimal,
    @Decimal(11, 2) losfx: java.math.BigDecimal,
    sbdkz: String,
    lagpr: String,
    altsl: String,
    kzaus: String,
    ausdt: String,
    nfmat: String,
    kzbed: String,
    miskz: String,
    fhori: String,
    pfrei: String,
    ffrei: String,
    rgekz: String,
    fevor: String,
    @Decimal(5, 2) bearz: java.math.BigDecimal,
    @Decimal(5, 2) ruezt: java.math.BigDecimal,
    @Decimal(5, 2) tranz: java.math.BigDecimal,
    @Decimal(13, 3) basmg: java.math.BigDecimal,
    @Decimal(3, 0) dzeit: java.math.BigDecimal,
    @Decimal(5, 0) maxlz: java.math.BigDecimal,
    lzeih: String,
    kzpro: String,
    gpmkz: String,
    @Decimal(3, 1) ueeto: java.math.BigDecimal,
    ueetk: String,
    @Decimal(3, 1) uneto: java.math.BigDecimal,
    @Decimal(3, 0) wzeit: java.math.BigDecimal,
    atpkz: String,
    @Decimal(5, 2) vzusl: java.math.BigDecimal,
    herbl: String,
    insmk: String,
    @Decimal(3, 1) sproz: java.math.BigDecimal,
    @Decimal(3, 0) quazt: java.math.BigDecimal,
    ssqss: String,
    @Decimal(5, 0) mpdau: java.math.BigDecimal,
    kzppv: String,
    kzdkz: String,
    @Decimal(9, 0) wstgh: java.math.BigDecimal,
    @Decimal(5, 0) prfrq: java.math.BigDecimal,
    nkmpr: String,
    @Decimal(13, 3) umlmc: java.math.BigDecimal,
    ladgr: String,
    xchpf: String,
    usequ: String,
    @Decimal(3, 1) lgrad: java.math.BigDecimal,
    auftl: String,
    plvar: String,
    otype: String,
    objid: String,
    mtvfp: String,
    periv: String,
    kzkfk: String,
    @Decimal(5, 2) vrvez: java.math.BigDecimal,
    @Decimal(13, 3) vbamg: java.math.BigDecimal,
    @Decimal(5, 2) vbeaz: java.math.BigDecimal,
    lizyk: String,
    bwscl: String,
    kautb: String,
    kordb: String,
    stawn: String,
    herkl: String,
    herkr: String,
    expme: String,
    mtver: String,
    prctr: String,
    @Decimal(13, 3) trame: java.math.BigDecimal,
    mrppp: String,
    sauft: String,
    fxhor: String,
    vrmod: String,
    vint1: String,
    vint2: String,
    verkz: String,
    stlal: String,
    stlan: String,
    plnnr: String,
    aplal: String,
    @Decimal(13, 3) losgr: java.math.BigDecimal,
    sobsk: String,
    frtme: String,
    lgpro: String,
    disgr: String,
    @Decimal(5, 2) kausf: java.math.BigDecimal,
    qzgtp: String,
    qmatv: String,
    @Decimal(3, 0) takzt: java.math.BigDecimal,
    rwpro: String,
    copam: String,
    abcin: String,
    awsls: String,
    sernp: String,
    cuobj: String,
    stdpd: String,
    sfepr: String,
    xmcng: String,
    qssys: String,
    lfrhy: String,
    rdprf: String,
    vrbmt: String,
    vrbwk: String,
    vrbdt: String,
    @Decimal(4, 2) vrbfk: java.math.BigDecimal,
    autru: String,
    prefe: String,
    prenc: String,
    preno: String,
    prend: String,
    prene: String,
    preng: String,
    itark: String,
    servg: String,
    kzkup: String,
    strgr: String,
    cuobv: String,
    lgfsb: String,
    schgt: String,
    ccfix: String,
    eprio: String,
    qmata: String,
    @Decimal(3, 0) resvp: java.math.BigDecimal,
    plnty: String,
    uomgr: String,
    umrsl: String,
    @Decimal(2, 1) abfac: java.math.BigDecimal,
    sfcpf: String,
    shflg: String,
    shzet: String,
    mdach: String,
    kzech: String,
    megru: String,
    mfrgr: String,
    @Decimal(13, 2) vkumc: java.math.BigDecimal,
    @Decimal(13, 2) vktrw: java.math.BigDecimal,
    kzagl: String,
    fvidk: String,
    fxpru: String,
    loggr: String,
    fprfm: String,
    @Decimal(13, 3) glgmg: java.math.BigDecimal,
    @Decimal(13, 2) vkglg: java.math.BigDecimal,
    indus: String,
    mownr: String,
    mogru: String,
    casnr: String,
    gpnum: String,
    steuc: String,
    fabkz: String,
    matgr: String,
    vspvb: String,
    dplfs: String,
    dplpu: String,
    @Decimal(3, 0) dplho: java.math.BigDecimal,
    @Decimal(13, 3) minls: java.math.BigDecimal,
    @Decimal(13, 3) maxls: java.math.BigDecimal,
    @Decimal(13, 3) fixls: java.math.BigDecimal,
    @Decimal(13, 3) ltinc: java.math.BigDecimal,
    compl: String,
    convt: String,
    shpro: String,
    ahdis: String,
    diber: String,
    kzpsp: String,
    ocmpf: String,
    apokz: String,
    mcrue: String,
    lfmon: String,
    lfgja: String,
    @Decimal(13, 3) eislo: java.math.BigDecimal,
    ncost: String,
    rotation_date: String,
    uchkz: String,
    ucmat: String,
    @Decimal(13, 3) bwesb: java.math.BigDecimal,
    sgt_covs: String,
    sgt_statc: String,
    sgt_scope: String,
    sgt_mrpsi: String,
    sgt_prcm: String,
    sgt_chint: String,
    sgt_stk_prt: String,
    sgt_defsc: String,
    sgt_mrp_atp_status: String,
    sgt_mmstd: String,
    fsh_mg_arun_req: String,
    fsh_seaim: String,
    fsh_var_group: String,
    fsh_kzech: String,
    @Decimal(3, 1) _sapmp_tolprpl: java.math.BigDecimal,
    @Decimal(3, 1) _sapmp_tolprmi: java.math.BigDecimal,
    _vso_r_pkgrp: String,
    _vso_r_lane_num: String,
    _vso_r_pal_vend: String,
    _vso_r_fork_dir: String,
    iuid_relevant: String,
    iuid_type: String,
    uid_iea: String,
    cons_procg: String,
    @Decimal(3, 0) gi_pr_time: java.math.BigDecimal,
    multiple_ekgrp: String,
    ref_schema: String,
    min_troc: String,
    max_troc: String,
    @Decimal(13, 3) target_stock: java.math.BigDecimal,
    zzplantref: String,
    zzccref: String,
    @Decimal(13, 6) zzqcf: java.math.BigDecimal,
    zzeudr: String
) extends Entity

object marc extends TableSpec[SrMarc] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_marc] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_marc] = sr_raw_marc

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("matnr", coalesce(col("matnr_string"), lit(""))),
    ("werks", coalesce(col("werks_string"), lit(""))),
    ("pstat", col("pstat_string")),
    ("lvorm", col("lvorm_string")),
    ("bwtty", col("bwtty_string")),
    ("xchar", col("xchar_string")),
    ("mmsta", col("mmsta_string")),
    ("mmstd", col("mmstd_string")),
    ("maabc", col("maabc_string")),
    ("kzkri", col("kzkri_string")),
    ("ekgrp", col("ekgrp_string")),
    ("ausme", col("ausme_string")),
    ("dispr", col("dispr_string")),
    ("dismm", col("dismm_string")),
    ("dispo", col("dispo_string")),
    ("kzdie", col("kzdie_string")),
    ("plifz", col("plifz_decimal_3_0")),
    ("webaz", col("webaz_decimal_3_0")),
    ("perkz", col("perkz_string")),
    ("ausss", col("ausss_decimal_5_2")),
    ("disls", col("disls_string")),
    ("beskz", col("beskz_string")),
    ("sobsl", col("sobsl_string")),
    ("minbe", col("minbe_decimal_13_3")),
    ("eisbe", col("eisbe_decimal_13_3")),
    ("bstmi", col("bstmi_decimal_13_3")),
    ("bstma", col("bstma_decimal_13_3")),
    ("bstfe", col("bstfe_decimal_13_3")),
    ("bstrf", col("bstrf_decimal_13_3")),
    ("mabst", col("mabst_decimal_13_3")),
    ("losfx", col("losfx_decimal_11_2")),
    ("sbdkz", col("sbdkz_string")),
    ("lagpr", col("lagpr_string")),
    ("altsl", col("altsl_string")),
    ("kzaus", col("kzaus_string")),
    ("ausdt", col("ausdt_string")),
    ("nfmat", col("nfmat_string")),
    ("kzbed", col("kzbed_string")),
    ("miskz", col("miskz_string")),
    ("fhori", col("fhori_string")),
    ("pfrei", col("pfrei_string")),
    ("ffrei", col("ffrei_string")),
    ("rgekz", col("rgekz_string")),
    ("fevor", col("fevor_string")),
    ("bearz", col("bearz_decimal_5_2")),
    ("ruezt", col("ruezt_decimal_5_2")),
    ("tranz", col("tranz_decimal_5_2")),
    ("basmg", col("basmg_decimal_13_3")),
    ("dzeit", col("dzeit_decimal_3_0")),
    ("maxlz", col("maxlz_decimal_5_0")),
    ("lzeih", col("lzeih_string")),
    ("kzpro", col("kzpro_string")),
    ("gpmkz", col("gpmkz_string")),
    ("ueeto", col("ueeto_decimal_3_1")),
    ("ueetk", col("ueetk_string")),
    ("uneto", col("uneto_decimal_3_1")),
    ("wzeit", col("wzeit_decimal_3_0")),
    ("atpkz", col("atpkz_string")),
    ("vzusl", col("vzusl_decimal_5_2")),
    ("herbl", col("herbl_string")),
    ("insmk", col("insmk_string")),
    ("sproz", col("sproz_decimal_3_1")),
    ("quazt", col("quazt_decimal_3_0")),
    ("ssqss", col("ssqss_string")),
    ("mpdau", col("mpdau_decimal_5_0")),
    ("kzppv", col("kzppv_string")),
    ("kzdkz", col("kzdkz_string")),
    ("wstgh", col("wstgh_decimal_9_0")),
    ("prfrq", col("prfrq_decimal_5_0")),
    ("nkmpr", col("nkmpr_string")),
    ("umlmc", col("umlmc_decimal_13_3")),
    ("ladgr", col("ladgr_string")),
    ("xchpf", col("xchpf_string")),
    ("usequ", col("usequ_string")),
    ("lgrad", col("lgrad_decimal_3_1")),
    ("auftl", col("auftl_string")),
    ("plvar", col("plvar_string")),
    ("otype", col("otype_string")),
    ("objid", col("objid_string")),
    ("mtvfp", col("mtvfp_string")),
    ("periv", col("periv_string")),
    ("kzkfk", col("kzkfk_string")),
    ("vrvez", col("vrvez_decimal_5_2")),
    ("vbamg", col("vbamg_decimal_13_3")),
    ("vbeaz", col("vbeaz_decimal_5_2")),
    ("lizyk", col("lizyk_string")),
    ("bwscl", col("bwscl_string")),
    ("kautb", col("kautb_string")),
    ("kordb", col("kordb_string")),
    ("stawn", col("stawn_string")),
    ("herkl", col("herkl_string")),
    ("herkr", col("herkr_string")),
    ("expme", col("expme_string")),
    ("mtver", col("mtver_string")),
    ("prctr", col("prctr_string")),
    ("trame", col("trame_decimal_13_3")),
    ("mrppp", col("mrppp_string")),
    ("sauft", col("sauft_string")),
    ("fxhor", col("fxhor_string")),
    ("vrmod", col("vrmod_string")),
    ("vint1", col("vint1_string")),
    ("vint2", col("vint2_string")),
    ("verkz", col("verkz_string")),
    ("stlal", col("stlal_string")),
    ("stlan", col("stlan_string")),
    ("plnnr", col("plnnr_string")),
    ("aplal", col("aplal_string")),
    ("losgr", col("losgr_decimal_13_3")),
    ("sobsk", col("sobsk_string")),
    ("frtme", col("frtme_string")),
    ("lgpro", col("lgpro_string")),
    ("disgr", col("disgr_string")),
    ("kausf", col("kausf_decimal_5_2")),
    ("qzgtp", col("qzgtp_string")),
    ("qmatv", col("qmatv_string")),
    ("takzt", col("takzt_decimal_3_0")),
    ("rwpro", col("rwpro_string")),
    ("copam", col("copam_string")),
    ("abcin", col("abcin_string")),
    ("awsls", col("awsls_string")),
    ("sernp", col("sernp_string")),
    ("cuobj", col("cuobj_string")),
    ("stdpd", col("stdpd_string")),
    ("sfepr", col("sfepr_string")),
    ("xmcng", col("xmcng_string")),
    ("qssys", col("qssys_string")),
    ("lfrhy", col("lfrhy_string")),
    ("rdprf", col("rdprf_string")),
    ("vrbmt", col("vrbmt_string")),
    ("vrbwk", col("vrbwk_string")),
    ("vrbdt", col("vrbdt_string")),
    ("vrbfk", col("vrbfk_decimal_4_2")),
    ("autru", col("autru_string")),
    ("prefe", col("prefe_string")),
    ("prenc", col("prenc_string")),
    ("preno", col("preno_string")),
    ("prend", col("prend_string")),
    ("prene", col("prene_string")),
    ("preng", col("preng_string")),
    ("itark", col("itark_string")),
    ("servg", col("servg_string")),
    ("kzkup", col("kzkup_string")),
    ("strgr", col("strgr_string")),
    ("cuobv", col("cuobv_string")),
    ("lgfsb", col("lgfsb_string")),
    ("schgt", col("schgt_string")),
    ("ccfix", col("ccfix_string")),
    ("eprio", col("eprio_string")),
    ("qmata", col("qmata_string")),
    ("resvp", col("resvp_decimal_3_0")),
    ("plnty", col("plnty_string")),
    ("uomgr", col("uomgr_string")),
    ("umrsl", col("umrsl_string")),
    ("abfac", col("abfac_decimal_2_1")),
    ("sfcpf", col("sfcpf_string")),
    ("shflg", col("shflg_string")),
    ("shzet", col("shzet_string")),
    ("mdach", col("mdach_string")),
    ("kzech", col("kzech_string")),
    ("megru", col("megru_string")),
    ("mfrgr", col("mfrgr_string")),
    ("vkumc", col("vkumc_decimal_13_2")),
    ("vktrw", col("vktrw_decimal_13_2")),
    ("kzagl", col("kzagl_string")),
    ("fvidk", col("fvidk_string")),
    ("fxpru", col("fxpru_string")),
    ("loggr", col("loggr_string")),
    ("fprfm", col("fprfm_string")),
    ("glgmg", col("glgmg_decimal_13_3")),
    ("vkglg", col("vkglg_decimal_13_2")),
    ("indus", col("indus_string")),
    ("mownr", col("mownr_string")),
    ("mogru", col("mogru_string")),
    ("casnr", col("casnr_string")),
    ("gpnum", col("gpnum_string")),
    ("steuc", col("steuc_string")),
    ("fabkz", col("fabkz_string")),
    ("matgr", col("matgr_string")),
    ("vspvb", col("vspvb_string")),
    ("dplfs", col("dplfs_string")),
    ("dplpu", col("dplpu_string")),
    ("dplho", col("dplho_decimal_3_0")),
    ("minls", col("minls_decimal_13_3")),
    ("maxls", col("maxls_decimal_13_3")),
    ("fixls", col("fixls_decimal_13_3")),
    ("ltinc", col("ltinc_decimal_13_3")),
    ("compl", col("compl_string")),
    ("convt", col("convt_string")),
    ("shpro", col("shpro_string")),
    ("ahdis", col("ahdis_string")),
    ("diber", col("diber_string")),
    ("kzpsp", col("kzpsp_string")),
    ("ocmpf", col("ocmpf_string")),
    ("apokz", col("apokz_string")),
    ("mcrue", col("mcrue_string")),
    ("lfmon", col("lfmon_string")),
    ("lfgja", col("lfgja_string")),
    ("eislo", col("eislo_decimal_13_3")),
    ("ncost", col("ncost_string")),
    ("rotation_date", col("rotation_date_string")),
    ("uchkz", col("uchkz_string")),
    ("ucmat", col("ucmat_string")),
    ("bwesb", col("bwesb_decimal_13_3")),
    ("sgt_covs", col("sgt_covs_string")),
    ("sgt_statc", col("sgt_statc_string")),
    ("sgt_scope", col("sgt_scope_string")),
    ("sgt_mrpsi", col("sgt_mrpsi_string")),
    ("sgt_prcm", col("sgt_prcm_string")),
    ("sgt_chint", col("sgt_chint_string")),
    ("sgt_stk_prt", col("sgt_stk_prt_string")),
    ("sgt_defsc", col("sgt_defsc_string")),
    ("sgt_mrp_atp_status", col("sgt_mrp_atp_status_string")),
    ("sgt_mmstd", col("sgt_mmstd_string")),
    ("fsh_mg_arun_req", col("fsh_mg_arun_req_string")),
    ("fsh_seaim", col("fsh_seaim_string")),
    ("fsh_var_group", col("fsh_var_group_string")),
    ("fsh_kzech", col("fsh_kzech_string")),
    ("_sapmp_tolprpl", col("_sapmp_tolprpl_decimal_3_1")),
    ("_sapmp_tolprmi", col("_sapmp_tolprmi_decimal_3_1")),
    ("_vso_r_pkgrp", col("_vso_r_pkgrp_string")),
    ("_vso_r_lane_num", col("_vso_r_lane_num_string")),
    ("_vso_r_pal_vend", col("_vso_r_pal_vend_string")),
    ("_vso_r_fork_dir", col("_vso_r_fork_dir_string")),
    ("iuid_relevant", col("iuid_relevant_string")),
    ("iuid_type", col("iuid_type_string")),
    ("uid_iea", col("uid_iea_string")),
    ("cons_procg", col("cons_procg_string")),
    ("gi_pr_time", col("gi_pr_time_decimal_3_0")),
    ("multiple_ekgrp", col("multiple_ekgrp_string")),
    ("ref_schema", col("ref_schema_string")),
    ("min_troc", col("min_troc_string")),
    ("max_troc", col("max_troc_string")),
    ("target_stock", col("target_stock_decimal_13_3")),
    ("zzplantref", col("zzplantref_string")),
    ("zzccref", col("zzccref_string")),
    ("zzqcf", col("zzqcf_decimal_13_6")),
    ("zzeudr", col("zzeudr_string"))
  )
}
