// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_e32

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_e32.{mbew => sr_raw_mbew}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrMbew(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK matnr: String,
    @PK bwkey: String,
    @PK bwtar: String,
    lvorm: String,
    @Decimal(13, 3) lbkum: java.math.BigDecimal,
    @Decimal(13, 2) salk3: java.math.BigDecimal,
    vprsv: String,
    @Decimal(11, 2) verpr: java.math.BigDecimal,
    @Decimal(11, 2) stprs: java.math.BigDecimal,
    @Decimal(5, 0) peinh: java.math.BigDecimal,
    bklas: String,
    @Decimal(13, 2) salkv: java.math.BigDecimal,
    @Decimal(13, 3) vmkum: java.math.BigDecimal,
    @Decimal(13, 2) vmsal: java.math.BigDecimal,
    vmvpr: String,
    @Decimal(11, 2) vmver: java.math.BigDecimal,
    @Decimal(11, 2) vmstp: java.math.BigDecimal,
    @Decimal(5, 0) vmpei: java.math.BigDecimal,
    vmbkl: String,
    @Decimal(13, 2) vmsav: java.math.BigDecimal,
    @Decimal(13, 3) vjkum: java.math.BigDecimal,
    @Decimal(13, 2) vjsal: java.math.BigDecimal,
    vjvpr: String,
    @Decimal(11, 2) vjver: java.math.BigDecimal,
    @Decimal(11, 2) vjstp: java.math.BigDecimal,
    @Decimal(5, 0) vjpei: java.math.BigDecimal,
    vjbkl: String,
    @Decimal(13, 2) vjsav: java.math.BigDecimal,
    lfgja: String,
    lfmon: String,
    bwtty: String,
    @Decimal(11, 2) stprv: java.math.BigDecimal,
    laepr: String,
    @Decimal(11, 2) zkprs: java.math.BigDecimal,
    zkdat: String,
    @Decimal(15, 0) timestamp_decimal_15_0: BigDecimal,
    @Decimal(11, 2) bwprs: java.math.BigDecimal,
    @Decimal(11, 2) bwprh: java.math.BigDecimal,
    @Decimal(11, 2) vjbws: java.math.BigDecimal,
    @Decimal(11, 2) vjbwh: java.math.BigDecimal,
    @Decimal(13, 2) vvjsl: java.math.BigDecimal,
    @Decimal(13, 3) vvjlb: java.math.BigDecimal,
    @Decimal(13, 3) vvmlb: java.math.BigDecimal,
    @Decimal(13, 2) vvsal: java.math.BigDecimal,
    @Decimal(11, 2) zplpr: java.math.BigDecimal,
    @Decimal(11, 2) zplp1: java.math.BigDecimal,
    @Decimal(11, 2) zplp2: java.math.BigDecimal,
    @Decimal(11, 2) zplp3: java.math.BigDecimal,
    zpld1: String,
    zpld2: String,
    zpld3: String,
    pperz: String,
    pperl: String,
    pperv: String,
    kalkz: String,
    kalkl: String,
    kalkv: String,
    kalsc: String,
    xlifo: String,
    mypol: String,
    @Decimal(11, 2) bwph1: java.math.BigDecimal,
    @Decimal(11, 2) bwps1: java.math.BigDecimal,
    abwkz: String,
    pstat: String,
    kaln1: String,
    kalnr: String,
    bwva1: String,
    bwva2: String,
    bwva3: String,
    vers1: String,
    vers2: String,
    vers3: String,
    hrkft: String,
    kosgr: String,
    pprdz: String,
    pprdl: String,
    pprdv: String,
    pdatz: String,
    pdatl: String,
    pdatv: String,
    ekalr: String,
    @Decimal(11, 2) vplpr: java.math.BigDecimal,
    mlmaa: String,
    mlast: String,
    @Decimal(11, 2) lplpr: java.math.BigDecimal,
    @Decimal(13, 2) vksal: java.math.BigDecimal,
    hkmat: String,
    sperw: String,
    kziwl: String,
    wlinl: String,
    abciw: String,
    @Decimal(6, 2) bwspa: java.math.BigDecimal,
    @Decimal(11, 2) lplpx: java.math.BigDecimal,
    @Decimal(11, 2) vplpx: java.math.BigDecimal,
    @Decimal(11, 2) fplpx: java.math.BigDecimal,
    lbwst: String,
    vbwst: String,
    fbwst: String,
    eklas: String,
    qklas: String,
    mtuse: String,
    mtorg: String,
    ownpr: String,
    xbewm: String,
    @Decimal(5, 0) bwpei: java.math.BigDecimal,
    mbrue: String,
    oklas: String,
    oippinv: String
) extends Entity

object mbew extends TableSpec[SrMbew] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_mbew] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_mbew] = sr_raw_mbew

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("matnr", coalesce(col("matnr_string"), lit(""))),
    ("bwkey", coalesce(col("bwkey_string"), lit(""))),
    ("bwtar", coalesce(col("bwtar_string"), lit(""))),
    ("lvorm", col("lvorm_string")),
    ("lbkum", col("lbkum_decimal_13_3")),
    ("salk3", col("salk3_decimal_13_2")),
    ("vprsv", col("vprsv_string")),
    ("verpr", col("verpr_decimal_11_2")),
    ("stprs", col("stprs_decimal_11_2")),
    ("peinh", col("peinh_decimal_5_0")),
    ("bklas", col("bklas_string")),
    ("salkv", col("salkv_decimal_13_2")),
    ("vmkum", col("vmkum_decimal_13_3")),
    ("vmsal", col("vmsal_decimal_13_2")),
    ("vmvpr", col("vmvpr_string")),
    ("vmver", col("vmver_decimal_11_2")),
    ("vmstp", col("vmstp_decimal_11_2")),
    ("vmpei", col("vmpei_decimal_5_0")),
    ("vmbkl", col("vmbkl_string")),
    ("vmsav", col("vmsav_decimal_13_2")),
    ("vjkum", col("vjkum_decimal_13_3")),
    ("vjsal", col("vjsal_decimal_13_2")),
    ("vjvpr", col("vjvpr_string")),
    ("vjver", col("vjver_decimal_11_2")),
    ("vjstp", col("vjstp_decimal_11_2")),
    ("vjpei", col("vjpei_decimal_5_0")),
    ("vjbkl", col("vjbkl_string")),
    ("vjsav", col("vjsav_decimal_13_2")),
    ("lfgja", col("lfgja_string")),
    ("lfmon", col("lfmon_string")),
    ("bwtty", col("bwtty_string")),
    ("stprv", col("stprv_decimal_11_2")),
    ("laepr", col("laepr_string")),
    ("zkprs", col("zkprs_decimal_11_2")),
    ("zkdat", col("zkdat_string")),
    ("timestamp_decimal_15_0", col("timestamp_decimal_15_0")),
    ("bwprs", col("bwprs_decimal_11_2")),
    ("bwprh", col("bwprh_decimal_11_2")),
    ("vjbws", col("vjbws_decimal_11_2")),
    ("vjbwh", col("vjbwh_decimal_11_2")),
    ("vvjsl", col("vvjsl_decimal_13_2")),
    ("vvjlb", col("vvjlb_decimal_13_3")),
    ("vvmlb", col("vvmlb_decimal_13_3")),
    ("vvsal", col("vvsal_decimal_13_2")),
    ("zplpr", col("zplpr_decimal_11_2")),
    ("zplp1", col("zplp1_decimal_11_2")),
    ("zplp2", col("zplp2_decimal_11_2")),
    ("zplp3", col("zplp3_decimal_11_2")),
    ("zpld1", col("zpld1_string")),
    ("zpld2", col("zpld2_string")),
    ("zpld3", col("zpld3_string")),
    ("pperz", col("pperz_string")),
    ("pperl", col("pperl_string")),
    ("pperv", col("pperv_string")),
    ("kalkz", col("kalkz_string")),
    ("kalkl", col("kalkl_string")),
    ("kalkv", col("kalkv_string")),
    ("kalsc", col("kalsc_string")),
    ("xlifo", col("xlifo_string")),
    ("mypol", col("mypol_string")),
    ("bwph1", col("bwph1_decimal_11_2")),
    ("bwps1", col("bwps1_decimal_11_2")),
    ("abwkz", col("abwkz_string")),
    ("pstat", col("pstat_string")),
    ("kaln1", col("kaln1_string")),
    ("kalnr", col("kalnr_string")),
    ("bwva1", col("bwva1_string")),
    ("bwva2", col("bwva2_string")),
    ("bwva3", col("bwva3_string")),
    ("vers1", col("vers1_string")),
    ("vers2", col("vers2_string")),
    ("vers3", col("vers3_string")),
    ("hrkft", col("hrkft_string")),
    ("kosgr", col("kosgr_string")),
    ("pprdz", col("pprdz_string")),
    ("pprdl", col("pprdl_string")),
    ("pprdv", col("pprdv_string")),
    ("pdatz", col("pdatz_string")),
    ("pdatl", col("pdatl_string")),
    ("pdatv", col("pdatv_string")),
    ("ekalr", col("ekalr_string")),
    ("vplpr", col("vplpr_decimal_11_2")),
    ("mlmaa", col("mlmaa_string")),
    ("mlast", col("mlast_string")),
    ("lplpr", col("lplpr_decimal_11_2")),
    ("vksal", col("vksal_decimal_13_2")),
    ("hkmat", col("hkmat_string")),
    ("sperw", col("sperw_string")),
    ("kziwl", col("kziwl_string")),
    ("wlinl", col("wlinl_string")),
    ("abciw", col("abciw_string")),
    ("bwspa", col("bwspa_decimal_6_2")),
    ("lplpx", col("lplpx_decimal_11_2")),
    ("vplpx", col("vplpx_decimal_11_2")),
    ("fplpx", col("fplpx_decimal_11_2")),
    ("lbwst", col("lbwst_string")),
    ("vbwst", col("vbwst_string")),
    ("fbwst", col("fbwst_string")),
    ("eklas", col("eklas_string")),
    ("qklas", col("qklas_string")),
    ("mtuse", col("mtuse_string")),
    ("mtorg", col("mtorg_string")),
    ("ownpr", col("ownpr_string")),
    ("xbewm", col("xbewm_string")),
    ("bwpei", col("bwpei_decimal_5_0")),
    ("mbrue", col("mbrue_string")),
    ("oklas", col("oklas_string")),
    ("oippinv", col("oippinv_string"))
  )
}
