// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_e32

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_e32.{prps => sr_raw_prps}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, hex, lit, struct}

case class SrPrps(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK pspnr: String,
    posid: String,
    post1: String,
    objnr: String,
    psphi: String,
    poski: String,
    ernam: String,
    erdat: String,
    aenam: String,
    aedat: String,
    vernr: String,
    verna: String,
    astnr: String,
    astna: String,
    pbukr: String,
    pgsbr: String,
    pkokr: String,
    prctr: String,
    prart: String,
    stufe: Int,
    plakz: String,
    belkz: String,
    fakkz: String,
    npfaz: String,
    zuord: String,
    trmeq: String,
    kvewe: String,
    kappl: String,
    kalsm: String,
    zschl: String,
    abgsl: String,
    akokr: String,
    akstl: String,
    fkokr: String,
    fkstl: String,
    fabkl: String,
    pspri: String,
    equnr: String,
    tplnr: String,
    pwpos: String,
    werks: String,
    txtsp: String,
    slwid: String,
    usr00: String,
    usr01: String,
    usr02: String,
    usr03: String,
    @Decimal(13, 3) usr04: java.math.BigDecimal,
    use04: String,
    @Decimal(13, 3) usr05: java.math.BigDecimal,
    use05: String,
    @Decimal(13, 3) usr06: java.math.BigDecimal,
    use06: String,
    @Decimal(13, 3) usr07: java.math.BigDecimal,
    use07: String,
    usr08: String,
    usr09: String,
    usr10: String,
    usr11: String,
    kostl: String,
    ktrg: String,
    berst: String,
    bertr: String,
    berko: String,
    berbu: String,
    clasf: String,
    spsnr: String,
    scope: String,
    xstat: String,
    txjcd: String,
    zschm: String,
    imprf: String,
    @Decimal(8, 0) evgew: java.math.BigDecimal,
    aennr: String,
    subpr: String,
    postu: String,
    plint: String,
    loevm: String,
    kzbws: String,
    fplnr: String,
    tadat: String,
    izwek: String,
    isize: String,
    iumkz: String,
    abukr: String,
    grpkz: String,
    pgprf: String,
    logsystem: String,
    pspnr_logs: String,
    stort: String,
    func_area: String,
    klvar: String,
    kalnr: String,
    posid_edit: String,
    pspkz: String,
    matnr: String,
    vlpsp: String,
    vlpkz: String,
    sort1: String,
    sort2: String,
    sort3: String,
    vname: String,
    recid: String,
    etype: String,
    otype: String,
    jibcl: String,
    jibsa: String,
    cgpl_guid16: String,
    cgpl_logsys: String,
    cgpl_objtype: String,
    adpsp: String,
    rfippnt: String,
    ferc_ind: String
) extends Entity

object prps extends TableSpec[SrPrps] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_prps] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_prps] = sr_raw_prps

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("pspnr", coalesce(col("pspnr_string"), lit(""))),
    ("posid", col("posid_string")),
    ("post1", col("post1_string")),
    ("objnr", col("objnr_string")),
    ("psphi", col("psphi_string")),
    ("poski", col("poski_string")),
    ("ernam", col("ernam_string")),
    ("erdat", col("erdat_string")),
    ("aenam", col("aenam_string")),
    ("aedat", col("aedat_string")),
    ("vernr", col("vernr_string")),
    ("verna", col("verna_string")),
    ("astnr", col("astnr_string")),
    ("astna", col("astna_string")),
    ("pbukr", col("pbukr_string")),
    ("pgsbr", col("pgsbr_string")),
    ("pkokr", col("pkokr_string")),
    ("prctr", col("prctr_string")),
    ("prart", col("prart_string")),
    ("stufe", coalesce(col("stufe_int"), lit(0))),
    ("plakz", col("plakz_string")),
    ("belkz", col("belkz_string")),
    ("fakkz", col("fakkz_string")),
    ("npfaz", col("npfaz_string")),
    ("zuord", col("zuord_string")),
    ("trmeq", col("trmeq_string")),
    ("kvewe", col("kvewe_string")),
    ("kappl", col("kappl_string")),
    ("kalsm", col("kalsm_string")),
    ("zschl", col("zschl_string")),
    ("abgsl", col("abgsl_string")),
    ("akokr", col("akokr_string")),
    ("akstl", col("akstl_string")),
    ("fkokr", col("fkokr_string")),
    ("fkstl", col("fkstl_string")),
    ("fabkl", col("fabkl_string")),
    ("pspri", col("pspri_string")),
    ("equnr", col("equnr_string")),
    ("tplnr", col("tplnr_string")),
    ("pwpos", col("pwpos_string")),
    ("werks", col("werks_string")),
    ("txtsp", col("txtsp_string")),
    ("slwid", col("slwid_string")),
    ("usr00", col("usr00_string")),
    ("usr01", col("usr01_string")),
    ("usr02", col("usr02_string")),
    ("usr03", col("usr03_string")),
    ("usr04", col("usr04_decimal_13_3")),
    ("use04", col("use04_string")),
    ("usr05", col("usr05_decimal_13_3")),
    ("use05", col("use05_string")),
    ("usr06", col("usr06_decimal_13_3")),
    ("use06", col("use06_string")),
    ("usr07", col("usr07_decimal_13_3")),
    ("use07", col("use07_string")),
    ("usr08", col("usr08_string")),
    ("usr09", col("usr09_string")),
    ("usr10", col("usr10_string")),
    ("usr11", col("usr11_string")),
    ("kostl", col("kostl_string")),
    ("ktrg", col("ktrg_string")),
    ("berst", col("berst_string")),
    ("bertr", col("bertr_string")),
    ("berko", col("berko_string")),
    ("berbu", col("berbu_string")),
    ("clasf", col("clasf_string")),
    ("spsnr", col("spsnr_string")),
    ("scope", col("scope_string")),
    ("xstat", col("xstat_string")),
    ("txjcd", col("txjcd_string")),
    ("zschm", col("zschm_string")),
    ("imprf", col("imprf_string")),
    ("evgew", col("evgew_decimal_8_0")),
    ("aennr", col("aennr_string")),
    ("subpr", col("subpr_string")),
    ("postu", col("postu_string")),
    ("plint", col("plint_string")),
    ("loevm", col("loevm_string")),
    ("kzbws", col("kzbws_string")),
    ("fplnr", col("fplnr_string")),
    ("tadat", col("tadat_string")),
    ("izwek", col("izwek_string")),
    ("isize", col("isize_string")),
    ("iumkz", col("iumkz_string")),
    ("abukr", col("abukr_string")),
    ("grpkz", col("grpkz_string")),
    ("pgprf", col("pgprf_string")),
    ("logsystem", col("logsystem_string")),
    ("pspnr_logs", col("pspnr_logs_string")),
    ("stort", col("stort_string")),
    ("func_area", col("func_area_string")),
    ("klvar", col("klvar_string")),
    ("kalnr", col("kalnr_string")),
    ("posid_edit", col("posid_edit_string")),
    ("pspkz", col("pspkz_string")),
    ("matnr", col("matnr_string")),
    ("vlpsp", col("vlpsp_string")),
    ("vlpkz", col("vlpkz_string")),
    ("sort1", col("sort1_string")),
    ("sort2", col("sort2_string")),
    ("sort3", col("sort3_string")),
    ("vname", col("vname_string")),
    ("recid", col("recid_string")),
    ("etype", col("etype_string")),
    ("otype", col("otype_string")),
    ("jibcl", col("jibcl_string")),
    ("jibsa", col("jibsa_string")),
    ("cgpl_guid16", hex(col("cgpl_guid16_binary"))),
    ("cgpl_logsys", col("cgpl_logsys_string")),
    ("cgpl_objtype", col("cgpl_objtype_string")),
    ("adpsp", col("adpsp_string")),
    ("rfippnt", col("rfippnt_string")),
    ("ferc_ind", col("ferc_ind_string"))
  )
}
