// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_e32

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_e32.{rbkp => sr_raw_rbkp}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrRbkp(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK belnr: String,
    @PK gjahr: String,
    blart: String,
    bldat: String,
    budat: String,
    usnam: String,
    tcode: String,
    cpudt: String,
    cputm: String,
    vgart: String,
    xblnr: String,
    bukrs: String,
    lifnr: String,
    waers: String,
    @Decimal(9, 5) kursf: java.math.BigDecimal,
    @Decimal(13, 2) rmwwr: java.math.BigDecimal,
    @Decimal(13, 2) beznk: java.math.BigDecimal,
    @Decimal(13, 2) wmwst1: java.math.BigDecimal,
    mwskz1: String,
    @Decimal(13, 2) wmwst2: java.math.BigDecimal,
    mwskz2: String,
    zterm: String,
    @Decimal(3, 0) zbd1t: java.math.BigDecimal,
    @Decimal(5, 3) zbd1p: java.math.BigDecimal,
    @Decimal(3, 0) zbd2t: java.math.BigDecimal,
    @Decimal(5, 3) zbd2p: java.math.BigDecimal,
    @Decimal(3, 0) zbd3t: java.math.BigDecimal,
    @Decimal(13, 2) wskto: java.math.BigDecimal,
    xrech: String,
    bktxt: String,
    saprl: String,
    logsys: String,
    xmwst: String,
    stblg: String,
    stjah: String,
    mwskz_bnk: String,
    txjcd_bnk: String,
    ivtyp: String,
    xrbtx: String,
    repart: String,
    rbstat: String,
    knumve: String,
    knumvl: String,
    @Decimal(13, 2) arkuen: java.math.BigDecimal,
    @Decimal(13, 2) arkuemw: java.math.BigDecimal,
    @Decimal(13, 2) makzn: java.math.BigDecimal,
    @Decimal(13, 2) makzmw: java.math.BigDecimal,
    @Decimal(13, 2) lieffn: java.math.BigDecimal,
    @Decimal(13, 2) lieffmw: java.math.BigDecimal,
    xautakz: String,
    esrnr: String,
    esrpz: String,
    esrre: String,
    @Decimal(13, 2) qsshb: java.math.BigDecimal,
    @Decimal(13, 2) qsfbt: java.math.BigDecimal,
    qsskz: String,
    diekz: String,
    landl: String,
    lzbkz: String,
    @Decimal(9, 5) txkrs: java.math.BigDecimal,
    @Decimal(9, 5) ctxkrs: java.math.BigDecimal,
    empfb: String,
    bvtyp: String,
    hbkid: String,
    zuonr: String,
    zlspr: String,
    zlsch: String,
    zfbdt: String,
    kidno: String,
    rebzg: String,
    rebzj: String,
    xinve: String,
    egmld: String,
    xegdr: String,
    vatdate: String,
    hkont: String,
    j_1bnftype: String,
    brnch: String,
    erfpr: String,
    secco: String,
    name1: String,
    name2: String,
    name3: String,
    name4: String,
    pstlz: String,
    ort01: String,
    land1: String,
    stras: String,
    pfach: String,
    pstl2: String,
    pskto: String,
    bankn: String,
    bankl: String,
    banks: String,
    stcd1: String,
    stcd2: String,
    stkzu: String,
    stkza: String,
    regio: String,
    bkont: String,
    dtaws: String,
    dtams: String,
    spras: String,
    xcpdk: String,
    empfg: String,
    fityp: String,
    stcdt: String,
    stkzn: String,
    stcd3: String,
    stcd4: String,
    bkref: String,
    j_1kfrepre: String,
    j_1kftbus: String,
    j_1kftind: String,
    anred: String,
    stceg: String,
    stcd5: String,
    intad: String,
    glo_re1_ot: String,
    ername: String,
    reindat: String,
    uzawe: String,
    fdlev: String,
    fdtag: String,
    zbfix: String,
    frgkz: String,
    erfnam: String,
    bupla: String,
    filkd: String,
    gsber: String,
    lotkz: String,
    sgtxt: String,
    inv_tran: String,
    prepay_status: String,
    prepay_awkey: String,
    assign_status: String,
    assign_next_date: String,
    assign_end_date: String,
    copy_by_belnr: String,
    copy_by_year: String,
    copy_to_belnr: String,
    copy_to_year: String,
    copy_user: String,
    @Decimal(28, 14) kursx: java.math.BigDecimal,
    wwert: String,
    xref3: String,
    j_1tpbupl: String,
    iseopblocked: String,
    @Decimal(21, 7) lastchangedatetime: java.math.BigDecimal,
    @Decimal(21, 7) cim_replicationtimestamp: java.math.BigDecimal,
    gst_part: String,
    plc_sup: String,
    irn: String,
    pybastyp: String,
    pybasno: String,
    pybasdat: String,
    pyiban: String,
    inwardno_hd: String,
    inwarddt_hd: String
) extends Entity

object rbkp extends TableSpec[SrRbkp] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_rbkp] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_rbkp] = sr_raw_rbkp

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("belnr", coalesce(col("belnr_string"), lit(""))),
    ("gjahr", coalesce(col("gjahr_string"), lit(""))),
    ("blart", col("blart_string")),
    ("bldat", col("bldat_string")),
    ("budat", col("budat_string")),
    ("usnam", col("usnam_string")),
    ("tcode", col("tcode_string")),
    ("cpudt", col("cpudt_string")),
    ("cputm", col("cputm_string")),
    ("vgart", col("vgart_string")),
    ("xblnr", col("xblnr_string")),
    ("bukrs", col("bukrs_string")),
    ("lifnr", col("lifnr_string")),
    ("waers", col("waers_string")),
    ("kursf", col("kursf_decimal_9_5")),
    ("rmwwr", col("rmwwr_decimal_13_2")),
    ("beznk", col("beznk_decimal_13_2")),
    ("wmwst1", col("wmwst1_decimal_13_2")),
    ("mwskz1", col("mwskz1_string")),
    ("wmwst2", col("wmwst2_decimal_13_2")),
    ("mwskz2", col("mwskz2_string")),
    ("zterm", col("zterm_string")),
    ("zbd1t", col("zbd1t_decimal_3_0")),
    ("zbd1p", col("zbd1p_decimal_5_3")),
    ("zbd2t", col("zbd2t_decimal_3_0")),
    ("zbd2p", col("zbd2p_decimal_5_3")),
    ("zbd3t", col("zbd3t_decimal_3_0")),
    ("wskto", col("wskto_decimal_13_2")),
    ("xrech", col("xrech_string")),
    ("bktxt", col("bktxt_string")),
    ("saprl", col("saprl_string")),
    ("logsys", col("logsys_string")),
    ("xmwst", col("xmwst_string")),
    ("stblg", col("stblg_string")),
    ("stjah", col("stjah_string")),
    ("mwskz_bnk", col("mwskz_bnk_string")),
    ("txjcd_bnk", col("txjcd_bnk_string")),
    ("ivtyp", col("ivtyp_string")),
    ("xrbtx", col("xrbtx_string")),
    ("repart", col("repart_string")),
    ("rbstat", col("rbstat_string")),
    ("knumve", col("knumve_string")),
    ("knumvl", col("knumvl_string")),
    ("arkuen", col("arkuen_decimal_13_2")),
    ("arkuemw", col("arkuemw_decimal_13_2")),
    ("makzn", col("makzn_decimal_13_2")),
    ("makzmw", col("makzmw_decimal_13_2")),
    ("lieffn", col("lieffn_decimal_13_2")),
    ("lieffmw", col("lieffmw_decimal_13_2")),
    ("xautakz", col("xautakz_string")),
    ("esrnr", col("esrnr_string")),
    ("esrpz", col("esrpz_string")),
    ("esrre", col("esrre_string")),
    ("qsshb", col("qsshb_decimal_13_2")),
    ("qsfbt", col("qsfbt_decimal_13_2")),
    ("qsskz", col("qsskz_string")),
    ("diekz", col("diekz_string")),
    ("landl", col("landl_string")),
    ("lzbkz", col("lzbkz_string")),
    ("txkrs", col("txkrs_decimal_9_5")),
    ("ctxkrs", col("ctxkrs_decimal_9_5")),
    ("empfb", col("empfb_string")),
    ("bvtyp", col("bvtyp_string")),
    ("hbkid", col("hbkid_string")),
    ("zuonr", col("zuonr_string")),
    ("zlspr", col("zlspr_string")),
    ("zlsch", col("zlsch_string")),
    ("zfbdt", col("zfbdt_string")),
    ("kidno", col("kidno_string")),
    ("rebzg", col("rebzg_string")),
    ("rebzj", col("rebzj_string")),
    ("xinve", col("xinve_string")),
    ("egmld", col("egmld_string")),
    ("xegdr", col("xegdr_string")),
    ("vatdate", col("vatdate_string")),
    ("hkont", col("hkont_string")),
    ("j_1bnftype", col("j_1bnftype_string")),
    ("brnch", col("brnch_string")),
    ("erfpr", col("erfpr_string")),
    ("secco", col("secco_string")),
    ("name1", col("name1_string")),
    ("name2", col("name2_string")),
    ("name3", col("name3_string")),
    ("name4", col("name4_string")),
    ("pstlz", col("pstlz_string")),
    ("ort01", col("ort01_string")),
    ("land1", col("land1_string")),
    ("stras", col("stras_string")),
    ("pfach", col("pfach_string")),
    ("pstl2", col("pstl2_string")),
    ("pskto", col("pskto_string")),
    ("bankn", col("bankn_string")),
    ("bankl", col("bankl_string")),
    ("banks", col("banks_string")),
    ("stcd1", col("stcd1_string")),
    ("stcd2", col("stcd2_string")),
    ("stkzu", col("stkzu_string")),
    ("stkza", col("stkza_string")),
    ("regio", col("regio_string")),
    ("bkont", col("bkont_string")),
    ("dtaws", col("dtaws_string")),
    ("dtams", col("dtams_string")),
    ("spras", col("spras_string")),
    ("xcpdk", col("xcpdk_string")),
    ("empfg", col("empfg_string")),
    ("fityp", col("fityp_string")),
    ("stcdt", col("stcdt_string")),
    ("stkzn", col("stkzn_string")),
    ("stcd3", col("stcd3_string")),
    ("stcd4", col("stcd4_string")),
    ("bkref", col("bkref_string")),
    ("j_1kfrepre", col("j_1kfrepre_string")),
    ("j_1kftbus", col("j_1kftbus_string")),
    ("j_1kftind", col("j_1kftind_string")),
    ("anred", col("anred_string")),
    ("stceg", col("stceg_string")),
    ("stcd5", col("stcd5_string")),
    ("intad", col("intad_string")),
    ("glo_re1_ot", col("glo_re1_ot_string")),
    ("ername", col("ername_string")),
    ("reindat", col("reindat_string")),
    ("uzawe", col("uzawe_string")),
    ("fdlev", col("fdlev_string")),
    ("fdtag", col("fdtag_string")),
    ("zbfix", col("zbfix_string")),
    ("frgkz", col("frgkz_string")),
    ("erfnam", col("erfnam_string")),
    ("bupla", col("bupla_string")),
    ("filkd", col("filkd_string")),
    ("gsber", col("gsber_string")),
    ("lotkz", col("lotkz_string")),
    ("sgtxt", col("sgtxt_string")),
    ("inv_tran", col("inv_tran_string")),
    ("prepay_status", col("prepay_status_string")),
    ("prepay_awkey", col("prepay_awkey_string")),
    ("assign_status", col("assign_status_string")),
    ("assign_next_date", col("assign_next_date_string")),
    ("assign_end_date", col("assign_end_date_string")),
    ("copy_by_belnr", col("copy_by_belnr_string")),
    ("copy_by_year", col("copy_by_year_string")),
    ("copy_to_belnr", col("copy_to_belnr_string")),
    ("copy_to_year", col("copy_to_year_string")),
    ("copy_user", col("copy_user_string")),
    ("kursx", col("kursx_decimal_28_14")),
    ("wwert", col("wwert_string")),
    ("xref3", col("xref3_string")),
    ("j_1tpbupl", col("j_1tpbupl_string")),
    ("iseopblocked", col("iseopblocked_string")),
    ("lastchangedatetime", col("lastchangedatetime_decimal_21_7")),
    ("cim_replicationtimestamp", col("cim_replicationtimestamp_decimal_21_7")),
    ("gst_part", col("gst_part_string")),
    ("plc_sup", col("plc_sup_string")),
    ("irn", col("irn_string")),
    ("pybastyp", col("pybastyp_string")),
    ("pybasno", col("pybasno_string")),
    ("pybasdat", col("pybasdat_string")),
    ("pyiban", col("pyiban_string")),
    ("inwardno_hd", col("inwardno_hd_string")),
    ("inwarddt_hd", col("inwarddt_hd_string"))
  )
}
