// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_e32

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_t024d(
    @PK mandt: String,
    @PK werks: String,
    @PK dispo: String,
    dsnam: String,
    dstel: String,
    ekgrp: String,
    mempf: String,
    gsber: String,
    prctr: String,
    usrtyp: String,
    usrkey: String,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String
) extends Entity

object t024d
    extends TableSpec[E_t024d](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[sr_raw.ct_gbl_e32.E_t024d] {
  override def sourceTableSpec: TableSpec[sr_raw.ct_gbl_e32.E_t024d] = sr_raw.ct_gbl_e32.t024d
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("mandt", col("mandt_string")),
    ("werks", col("werks_string")),
    ("dispo", col("dispo_string")),
    ("dsnam", col("dsnam_string")),
    ("dstel", col("dstel_string")),
    ("ekgrp", col("ekgrp_string")),
    ("mempf", col("mempf_string")),
    ("gsber", col("gsber_string")),
    ("prctr", col("prctr_string")),
    ("usrtyp", col("usrtyp_string")),
    ("usrkey", col("usrkey_string"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_t024d(prefix: String) extends ColumnWithNameAccessor {
  val mandt: ColumnWithName = ColumnWithName(prefix + "mandt")
  val werks: ColumnWithName = ColumnWithName(prefix + "werks")
  val dispo: ColumnWithName = ColumnWithName(prefix + "dispo")
  val dsnam: ColumnWithName = ColumnWithName(prefix + "dsnam")
  val dstel: ColumnWithName = ColumnWithName(prefix + "dstel")
  val ekgrp: ColumnWithName = ColumnWithName(prefix + "ekgrp")
  val mempf: ColumnWithName = ColumnWithName(prefix + "mempf")
  val gsber: ColumnWithName = ColumnWithName(prefix + "gsber")
  val prctr: ColumnWithName = ColumnWithName(prefix + "prctr")
  val usrtyp: ColumnWithName = ColumnWithName(prefix + "usrtyp")
  val usrkey: ColumnWithName = ColumnWithName(prefix + "usrkey")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
}

object C_t024d extends C_t024d("") {
  def as(alias: String): C_t024d = new C_t024d(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
