// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_e32

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_tbp0l(
    @PK mandt: String,
    @PK waers: String,
    @PK periv: String,
    lednr: String,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String
) extends Entity

object tbp0l
    extends TableSpec[E_tbp0l](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[sr_raw.ct_gbl_e32.E_tbp0l] {
  override def sourceTableSpec: TableSpec[sr_raw.ct_gbl_e32.E_tbp0l] = sr_raw.ct_gbl_e32.tbp0l
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("mandt", col("mandt_string")),
    ("waers", col("waers_string")),
    ("periv", col("periv_string")),
    ("lednr", col("lednr_string"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_tbp0l(prefix: String) extends ColumnWithNameAccessor {
  val mandt: ColumnWithName = ColumnWithName(prefix + "mandt")
  val waers: ColumnWithName = ColumnWithName(prefix + "waers")
  val periv: ColumnWithName = ColumnWithName(prefix + "periv")
  val lednr: ColumnWithName = ColumnWithName(prefix + "lednr")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
}

object C_tbp0l extends C_tbp0l("") {
  def as(alias: String): C_tbp0l = new C_tbp0l(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
