// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_e32

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_e32.{vbak => sr_raw_vbak}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrVbak(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK vbeln: String,
    erdat: String,
    erzet: String,
    ernam: String,
    angdt: String,
    bnddt: String,
    audat: String,
    vbtyp: String,
    trvog: String,
    auart: String,
    augru: String,
    gwldt: String,
    submi: String,
    lifsk: String,
    faksk: String,
    @Decimal(15, 2) netwr: java.math.BigDecimal,
    waerk: String,
    vkorg: String,
    vtweg: String,
    spart: String,
    vkgrp: String,
    vkbur: String,
    gsber: String,
    gskst: String,
    guebg: String,
    gueen: String,
    knumv: String,
    vdatu: String,
    vprgr: String,
    autlf: String,
    vbkla: String,
    vbklt: String,
    kalsm: String,
    vsbed: String,
    fkara: String,
    awahr: String,
    ktext: String,
    bstnk: String,
    bsark: String,
    bstdk: String,
    bstzd: String,
    ihrez: String,
    bname: String,
    telf1: String,
    @Decimal(3, 0) mahza: java.math.BigDecimal,
    mahdt: String,
    kunnr: String,
    kostl: String,
    stafo: String,
    stwae: String,
    aedat: String,
    kvgr1: String,
    kvgr2: String,
    kvgr3: String,
    kvgr4: String,
    kvgr5: String,
    knuma: String,
    kokrs: String,
    ps_psp_pnr: String,
    kurst: String,
    kkber: String,
    knkli: String,
    grupp: String,
    sbgrp: String,
    ctlpc: String,
    cmwae: String,
    cmfre: String,
    cmnup: String,
    cmngv: String,
    @Decimal(15, 2) amtbl: java.math.BigDecimal,
    hityp_pr: String,
    abrvw: String,
    abdis: String,
    vgbel: String,
    objnr: String,
    bukrs_vf: String,
    taxk1: String,
    taxk2: String,
    taxk3: String,
    taxk4: String,
    taxk5: String,
    taxk6: String,
    taxk7: String,
    taxk8: String,
    taxk9: String,
    xblnr: String,
    zuonr: String,
    vgtyp: String,
    kalsm_ch: String,
    agrzr: String,
    aufnr: String,
    qmnum: String,
    vbeln_grp: String,
    scheme_grp: String,
    abruf_part: String,
    abhod: String,
    abhov: String,
    abhob: String,
    rplnr: String,
    vzeit: String,
    stceg_l: String,
    landtx: String,
    xegdr: String,
    enqueue_grp: String,
    dat_fzau: String,
    fmbdat: String,
    vsnmr_v: String,
    handle: String,
    proli: String,
    cont_dg: String,
    crm_guid: String,
    @Decimal(21, 7) upd_tmstmp: java.math.BigDecimal,
    msr_id: String,
    tm_ctrl_key: String,
    handoverloc: String,
    glo_log_ref1_hd: String,
    psm_budat: String,
    swenr: String,
    smenr: String,
    phase: String,
    mtlaur: String,
    stage: Int,
    hb_cont_reason: String,
    hb_expdate: String,
    hb_resdate: String,
    mill_appl_id: String,
    logsysb: String,
    kalcd: String,
    multi: String,
    sppaym: String,
    wtysc_clm_hdr: String,
    zz74_matan: String,
    zz74_lwkid: String,
    zz74_pwkid: String,
    zz74_eikto: String,
    zz74_docnum: String
) extends Entity

object vbak extends TableSpec[SrVbak] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_vbak] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_e32.E_vbak] = sr_raw_vbak

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("vbeln", coalesce(col("vbeln_string"), lit(""))),
    ("erdat", col("erdat_string")),
    ("erzet", col("erzet_string")),
    ("ernam", col("ernam_string")),
    ("angdt", col("angdt_string")),
    ("bnddt", col("bnddt_string")),
    ("audat", col("audat_string")),
    ("vbtyp", col("vbtyp_string")),
    ("trvog", col("trvog_string")),
    ("auart", col("auart_string")),
    ("augru", col("augru_string")),
    ("gwldt", col("gwldt_string")),
    ("submi", col("submi_string")),
    ("lifsk", col("lifsk_string")),
    ("faksk", col("faksk_string")),
    ("netwr", col("netwr_decimal_15_2")),
    ("waerk", col("waerk_string")),
    ("vkorg", col("vkorg_string")),
    ("vtweg", col("vtweg_string")),
    ("spart", col("spart_string")),
    ("vkgrp", col("vkgrp_string")),
    ("vkbur", col("vkbur_string")),
    ("gsber", col("gsber_string")),
    ("gskst", col("gskst_string")),
    ("guebg", col("guebg_string")),
    ("gueen", col("gueen_string")),
    ("knumv", col("knumv_string")),
    ("vdatu", col("vdatu_string")),
    ("vprgr", col("vprgr_string")),
    ("autlf", col("autlf_string")),
    ("vbkla", col("vbkla_string")),
    ("vbklt", col("vbklt_string")),
    ("kalsm", col("kalsm_string")),
    ("vsbed", col("vsbed_string")),
    ("fkara", col("fkara_string")),
    ("awahr", col("awahr_string")),
    ("ktext", col("ktext_string")),
    ("bstnk", col("bstnk_string")),
    ("bsark", col("bsark_string")),
    ("bstdk", col("bstdk_string")),
    ("bstzd", col("bstzd_string")),
    ("ihrez", col("ihrez_string")),
    ("bname", col("bname_string")),
    ("telf1", col("telf1_string")),
    ("mahza", col("mahza_decimal_3_0")),
    ("mahdt", col("mahdt_string")),
    ("kunnr", col("kunnr_string")),
    ("kostl", col("kostl_string")),
    ("stafo", col("stafo_string")),
    ("stwae", col("stwae_string")),
    ("aedat", col("aedat_string")),
    ("kvgr1", col("kvgr1_string")),
    ("kvgr2", col("kvgr2_string")),
    ("kvgr3", col("kvgr3_string")),
    ("kvgr4", col("kvgr4_string")),
    ("kvgr5", col("kvgr5_string")),
    ("knuma", col("knuma_string")),
    ("kokrs", col("kokrs_string")),
    ("ps_psp_pnr", col("ps_psp_pnr_string")),
    ("kurst", col("kurst_string")),
    ("kkber", col("kkber_string")),
    ("knkli", col("knkli_string")),
    ("grupp", col("grupp_string")),
    ("sbgrp", col("sbgrp_string")),
    ("ctlpc", col("ctlpc_string")),
    ("cmwae", col("cmwae_string")),
    ("cmfre", col("cmfre_string")),
    ("cmnup", col("cmnup_string")),
    ("cmngv", col("cmngv_string")),
    ("amtbl", col("amtbl_decimal_15_2")),
    ("hityp_pr", col("hityp_pr_string")),
    ("abrvw", col("abrvw_string")),
    ("abdis", col("abdis_string")),
    ("vgbel", col("vgbel_string")),
    ("objnr", col("objnr_string")),
    ("bukrs_vf", col("bukrs_vf_string")),
    ("taxk1", col("taxk1_string")),
    ("taxk2", col("taxk2_string")),
    ("taxk3", col("taxk3_string")),
    ("taxk4", col("taxk4_string")),
    ("taxk5", col("taxk5_string")),
    ("taxk6", col("taxk6_string")),
    ("taxk7", col("taxk7_string")),
    ("taxk8", col("taxk8_string")),
    ("taxk9", col("taxk9_string")),
    ("xblnr", col("xblnr_string")),
    ("zuonr", col("zuonr_string")),
    ("vgtyp", col("vgtyp_string")),
    ("kalsm_ch", col("kalsm_ch_string")),
    ("agrzr", col("agrzr_string")),
    ("aufnr", col("aufnr_string")),
    ("qmnum", col("qmnum_string")),
    ("vbeln_grp", col("vbeln_grp_string")),
    ("scheme_grp", col("scheme_grp_string")),
    ("abruf_part", col("abruf_part_string")),
    ("abhod", col("abhod_string")),
    ("abhov", col("abhov_string")),
    ("abhob", col("abhob_string")),
    ("rplnr", col("rplnr_string")),
    ("vzeit", col("vzeit_string")),
    ("stceg_l", col("stceg_l_string")),
    ("landtx", col("landtx_string")),
    ("xegdr", col("xegdr_string")),
    ("enqueue_grp", col("enqueue_grp_string")),
    ("dat_fzau", col("dat_fzau_string")),
    ("fmbdat", col("fmbdat_string")),
    ("vsnmr_v", col("vsnmr_v_string")),
    ("handle", col("handle_string")),
    ("proli", col("proli_string")),
    ("cont_dg", col("cont_dg_string")),
    ("crm_guid", col("crm_guid_string")),
    ("upd_tmstmp", col("upd_tmstmp_decimal_21_7")),
    ("msr_id", col("msr_id_string")),
    ("tm_ctrl_key", col("tm_ctrl_key_string")),
    ("handoverloc", col("handoverloc_string")),
    ("glo_log_ref1_hd", col("glo_log_ref1_hd_string")),
    ("psm_budat", col("psm_budat_string")),
    ("swenr", col("swenr_string")),
    ("smenr", col("smenr_string")),
    ("phase", col("phase_string")),
    ("mtlaur", col("mtlaur_string")),
    ("stage", coalesce(col("stage_int"), lit(0))),
    ("hb_cont_reason", col("hb_cont_reason_string")),
    ("hb_expdate", col("hb_expdate_string")),
    ("hb_resdate", col("hb_resdate_string")),
    ("mill_appl_id", col("mill_appl_id_string")),
    ("logsysb", col("logsysb_string")),
    ("kalcd", col("kalcd_string")),
    ("multi", col("multi_string")),
    ("sppaym", col("sppaym_string")),
    ("wtysc_clm_hdr", col("wtysc_clm_hdr_string")),
    ("zz74_matan", col("zz74_matan_string")),
    ("zz74_lwkid", col("zz74_lwkid_string")),
    ("zz74_pwkid", col("zz74_pwkid_string")),
    ("zz74_eikto", col("zz74_eikto_string")),
    ("zz74_docnum", col("zz74_docnum_string"))
  )
}
