package ct.dna.lakehouse.dm_md.fin_redb

import ct.dna.lakehouse.core.framework.ChangeFeed
import ct.dna.lakehouse.core.framework.Result
import ct.dna.lakehouse.core.framework.Table
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.core.model.Updated

case class DmHsCodesRegional(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    cnkey_string: String,
    lev12_string: String,
    lev10_string: String,
    declareable_attribut_string: String,
    lev11_string: String,
    chapter_string: String,
    declarable_string: String,
    level_string: String,
    cn_description_string: String,
    section_string: String,
    hs_code_length_string: String,
    cn_code_string: String,
    lev9_string: String,
    goods_code_string: String,
    lev5_string: String,
    lev6_string: String,
    lev7_string: String,
    lev8_string: String,
    cnkey_long: BoxedLong,
    declareable_attribut_long: BoxedLong,
    cn_code_long: BoxedLong,
    level_long: BoxedLong,
    hs_code_length_long: BoxedLong
) extends Entity

object hs_codes_regional extends TableSpec[DmHsCodesRegional] with Updated.ByOneTransaction {

  private val srSource = ct.dna.lakehouse.sr_raw.mn_gbl_spcustoms.hs_codes_regional

  override def sourceTableSpecs: Seq[TableSpec[Entity]] =
    Seq(srSource)

  override def executeTransaction(
      table: Table,
      changeFeeds: Map[TableSpec[Entity], ChangeFeed]
  ): Result = {

    val feeds = sourceTableSpecs.map(s => s -> changeFeeds(s))

    if (feeds.forall { case (_, f) => f.isUnchanged }) return Result.NoChanges

    val src = changeFeeds(srSource).snapshot()

    table.overwriteByKeys(src)
  }

  override def validate(): Unit = {
    super.validate()
    require(
      sourceTableSpecs.toSet == Set(srSource),
      s"hs_codes_regional sourceTableSpecs unexpected: $sourceTableSpecs"
    )
  }
}

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_hs_codes_regional(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix, "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix, "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix, "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix, "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix, "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix, "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix, "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix, "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix, "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix, "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix, "_lh_ingest_warning")
  val cnkey_string: ColumnWithName = ColumnWithName(prefix, "cnkey_string")
  val lev12_string: ColumnWithName = ColumnWithName(prefix, "lev12_string")
  val lev10_string: ColumnWithName = ColumnWithName(prefix, "lev10_string")
  val declareable_attribut_string: ColumnWithName = ColumnWithName(prefix, "declareable_attribut_string")
  val lev11_string: ColumnWithName = ColumnWithName(prefix, "lev11_string")
  val chapter_string: ColumnWithName = ColumnWithName(prefix, "chapter_string")
  val declarable_string: ColumnWithName = ColumnWithName(prefix, "declarable_string")
  val level_string: ColumnWithName = ColumnWithName(prefix, "level_string")
  val cn_description_string: ColumnWithName = ColumnWithName(prefix, "cn_description_string")
  val section_string: ColumnWithName = ColumnWithName(prefix, "section_string")
  val hs_code_length_string: ColumnWithName = ColumnWithName(prefix, "hs_code_length_string")
  val cn_code_string: ColumnWithName = ColumnWithName(prefix, "cn_code_string")
  val lev9_string: ColumnWithName = ColumnWithName(prefix, "lev9_string")
  val goods_code_string: ColumnWithName = ColumnWithName(prefix, "goods_code_string")
  val lev5_string: ColumnWithName = ColumnWithName(prefix, "lev5_string")
  val lev6_string: ColumnWithName = ColumnWithName(prefix, "lev6_string")
  val lev7_string: ColumnWithName = ColumnWithName(prefix, "lev7_string")
  val lev8_string: ColumnWithName = ColumnWithName(prefix, "lev8_string")
  val cnkey_long: ColumnWithName = ColumnWithName(prefix, "cnkey_long")
  val declareable_attribut_long: ColumnWithName = ColumnWithName(prefix, "declareable_attribut_long")
  val cn_code_long: ColumnWithName = ColumnWithName(prefix, "cn_code_long")
  val level_long: ColumnWithName = ColumnWithName(prefix, "level_long")
  val hs_code_length_long: ColumnWithName = ColumnWithName(prefix, "hs_code_length_long")
}

object C_hs_codes_regional extends C_hs_codes_regional("") {
  def withDFAlias(alias: String): C_hs_codes_regional = new C_hs_codes_regional(alias)
  def withoutDFAlias: C_hs_codes_regional = this
}
// COLUMN ACCESSOR AUTO GENERATED:END
