package ct.dna.lakehouse.sr_raw.ct_gbl_p61
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class ekko_E(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  shipcond_string: String,
  abgru_string: String,
  bukrs_string: String,
  zterm_string: String,
  procstat_string: String,
  fixpo_string: String,
  @Decimal(3, 0) zbd1t_decimal_3_0: BigDecimal,
  logsy_string: String,
  description_string: String,
  bsart_string: String,
  inco3_l_string: String,
  fsh_os_stg_change_string: String,
  bnddt_string: String,
  ernam_string: String,
  msr_id_string: String,
  verkf_string: String,
  statu_string: String,
  spras_string: String,
  eq_eindt_string: String,
  lphis_string: String,
  ltsnr_allow_string: String,
  kdatb_string: String,
  tru_string: String,
  @Decimal(3, 0) zbd2t_decimal_3_0: BigDecimal,
  kornr_string: String,
  fsh_vas_last_item_string: String,
  key_id_string: String,
  bwbdt_string: String,
  ebeln_string: String,
  threshold_exists_string: String,
  reswk_string: String,
  contract_allow_string: String,
  @Decimal(17, 2) otb_spec_value_decimal_17_2: BigDecimal,
  frgzu_string: String,
  gwldt_string: String,
  pincr_string: String,
  frgsx_string: String,
  @Decimal(11, 2) dpamt_decimal_11_2: BigDecimal,
  addnr_string: String,
  llief_string: String,
  pco_string: String,
  angdt_string: String,
  con_distr_lev_string: String,
  exnum_string: String,
  eindt_allow_string: String,
  con_otb_req_string: String,
  source_logsys_string: String,
  fsh_transaction_string: String,
  dno_string: String,
  plc_string: String,
  pcy_string: String,
  check_type_string: String,
  unsez_string: String,
  @Decimal(5, 3) zbd1p_decimal_5_3: BigDecimal,
  postat_string: String,
  stceg_string: String,
  stceg_l_string: String,
  reason_code_string: String,
  otb_curr_string: String,
  bstyp_string: String,
  weakt_string: String,
  otb_level_string: String,
  ecc_string: String,
  pohf_type_string: String,
  pcd_string: String,
  kalsm_string: String,
  autlf_string: String,
  force_id_string: String,
  bsakz_string: String,
  rettp_string: String,
  externalsystem_string: String,
  cur_string: String,
  fixpo_allow_string: String,
  mandt_string: String,
  eq_werks_string: String,
  konnr_string: String,
  pcn_string: String,
  memorytype_string: String,
  stafo_string: String,
  ipp_string: String,
  fsh_snst_status_string: String,
  @Decimal(9, 5) wkurs_decimal_9_5: BigDecimal,
  ekgrp_string: String,
  vzskz_string: String,
  inco1_string: String,
  bedat_string: String,
  telf1_string: String,
  @Decimal(3, 0) zbd3t_decimal_3_0: BigDecimal,
  handoverloc_string: String,
  hierarchy_exists_string: String,
  dpdat_string: String,
  adrnr_string: String,
  @Decimal(21, 7) ext_rev_tmstmp_decimal_21_7: BigDecimal,
  submi_string: String,
  inco2_l_string: String,
  ihran_string: String,
  angnr_string: String,
  vsart_string: String,
  ekorg_string: String,
  frgke_string: String,
  lblif_string: String,
  aurel_allow_string: String,
  upinc_string: String,
  spr_rsn_profile_string: String,
  ausnr_string: String,
  lifre_string: String,
  scmproc_string: String,
  ekgrp_allow_string: String,
  dptyp_string: String,
  @Decimal(5, 3) zbd2p_decimal_5_3: BigDecimal,
  top_string: String,
  pstyp_allow_string: String,
  amn_string: String,
  frgrl_string: String,
  con_prebook_lev_string: String,
  @Decimal(15, 2) ktwrt_decimal_15_2: BigDecimal,
  delper_allow_string: String,
  pbn_string: String,
  fsh_item_group_string: String,
  inco2_string: String,
  loekz_string: String,
  lponr_string: String,
  stako_string: String,
  otb_status_string: String,
  absgr_string: String,
  aedat_string: String,
  externalreferenceid_string: String,
  @Decimal(17, 2) otb_value_decimal_17_2: BigDecimal,
  memory_string: String,
  legal_contract_string: String,
  otb_cond_type_string: String,
  @Decimal(5, 2) retpc_decimal_5_2: BigDecimal,
  frggr_string: String,
  lifnr_string: String,
  dpt_string: String,
  revno_string: String,
  otb_reason_string: String,
  knumv_string: String,
  force_cnt_string: String,
  reloc_id_string: String,
  release_date_string: String,
  lands_string: String,
  kunnr_string: String,
  ihrez_string: String,
  kufix_string: String,
  eco_string: String,
  key_id_allow_string: String,
  @Decimal(5, 2) dppct_decimal_5_2: BigDecimal,
  kdate_string: String,
  @Decimal(17, 2) otb_res_value_decimal_17_2: BigDecimal,
  budg_type_string: String,
  werks_allow_string: String,
  reloc_seq_id_string: String,
  @Decimal(15, 2) rlwrt_decimal_15_2: BigDecimal,
  sus_string: String,
  incov_string: String,
  waers_string: String,
  smb_string: String
) extends Entity

object ekko extends TableSpec[ekko_E](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
