// LOADED TABLE SPEC AUTO GENERATED:START
// Generated by LoadedTableSpecAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr_raw.ct_gbl_p61

import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.Loaded
import ct.dna.lakehouse.core.model.TableSpec

case class E_knvv(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt_string: String,
    kunnr_string: String,
    vkorg_string: String,
    vtweg_string: String,
    spart_string: String,
    ernam_string: String,
    erdat_string: String,
    begru_string: String,
    loevm_string: String,
    versg_string: String,
    aufsd_string: String,
    kalks_string: String,
    kdgrp_string: String,
    bzirk_string: String,
    konda_string: String,
    pltyp_string: String,
    awahr_string: String,
    inco1_string: String,
    inco2_string: String,
    lifsd_string: String,
    autlf_string: String,
    @Decimal(1, 0) antlf_decimal_1_0: BigDecimal,
    kztlf_string: String,
    kzazu_string: String,
    chspl_string: String,
    lprio_string: String,
    eikto_string: String,
    vsbed_string: String,
    faksd_string: String,
    mrnkz_string: String,
    perfk_string: String,
    perrl_string: String,
    kvakz_string: String,
    @Decimal(13, 2) kvawt_decimal_13_2: BigDecimal,
    waers_string: String,
    klabc_string: String,
    ktgrd_string: String,
    zterm_string: String,
    vwerk_string: String,
    vkgrp_string: String,
    vkbur_string: String,
    vsort_string: String,
    kvgr1_string: String,
    kvgr2_string: String,
    kvgr3_string: String,
    kvgr4_string: String,
    kvgr5_string: String,
    bokre_string: String,
    boidt_string: String,
    kurst_string: String,
    prfre_string: String,
    prat1_string: String,
    prat2_string: String,
    prat3_string: String,
    prat4_string: String,
    prat5_string: String,
    prat6_string: String,
    prat7_string: String,
    prat8_string: String,
    prat9_string: String,
    prata_string: String,
    kabss_string: String,
    kkber_string: String,
    cassd_string: String,
    rdoff_string: String,
    agrel_string: String,
    megru_string: String,
    @Decimal(3, 1) uebto_decimal_3_1: BigDecimal,
    @Decimal(3, 1) untto_decimal_3_1: BigDecimal,
    uebtk_string: String,
    pvksm_string: String,
    podkz_string: String,
    @Decimal(11, 0) podtg_decimal_11_0: BigDecimal,
    blind_string: String,
    carrier_notif_string: String,
    cvp_xblck_v_string: String,
    incov_string: String,
    inco2_l_string: String,
    inco3_l_string: String,
    _bev1_emlgpfand_string: String,
    _bev1_emlgforts_string: String,
    j_1nboesl_string: String,
    profile_string: String,
    fpart_string: String,
    fsh_kvgr6_string: String,
    fsh_kvgr7_string: String,
    fsh_kvgr8_string: String,
    fsh_kvgr9_string: String,
    fsh_kvgr10_string: String,
    fsh_grreg_string: String,
    fsh_resgy_string: String,
    fsh_sc_cid_string: String,
    fsh_vas_detc_string: String,
    fsh_vas_cg_string: String,
    fsh_grsgy_string: String,
    fsh_ss_string: String,
    fsh_msocdc_string: String,
    fsh_msopid_string: String,
    zztriggerpoint_string: String,
    @Decimal(11, 0) zztraztd_decimal_11_0: BigDecimal,
    zzprecarriage_string: String,
    zzreceiptloc_string: String,
    zzportofloading_string: String,
    zzportofdisch_string: String,
    zzdeliveryplace_string: String,
    zzspecind_string: String,
    zzsegal_string: String,
    yfta_string: String
) extends Entity

object knvv
    extends TableSpec[E_knvv](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.Columns("_mk_instance", "_mk_partition", "_mk_file"),
      timetravelDays = 35
    )
    with Loaded
// LOADED TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_knvv(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val mandt_string: ColumnWithName = ColumnWithName(prefix + "mandt_string")
  val kunnr_string: ColumnWithName = ColumnWithName(prefix + "kunnr_string")
  val vkorg_string: ColumnWithName = ColumnWithName(prefix + "vkorg_string")
  val vtweg_string: ColumnWithName = ColumnWithName(prefix + "vtweg_string")
  val spart_string: ColumnWithName = ColumnWithName(prefix + "spart_string")
  val ernam_string: ColumnWithName = ColumnWithName(prefix + "ernam_string")
  val erdat_string: ColumnWithName = ColumnWithName(prefix + "erdat_string")
  val begru_string: ColumnWithName = ColumnWithName(prefix + "begru_string")
  val loevm_string: ColumnWithName = ColumnWithName(prefix + "loevm_string")
  val versg_string: ColumnWithName = ColumnWithName(prefix + "versg_string")
  val aufsd_string: ColumnWithName = ColumnWithName(prefix + "aufsd_string")
  val kalks_string: ColumnWithName = ColumnWithName(prefix + "kalks_string")
  val kdgrp_string: ColumnWithName = ColumnWithName(prefix + "kdgrp_string")
  val bzirk_string: ColumnWithName = ColumnWithName(prefix + "bzirk_string")
  val konda_string: ColumnWithName = ColumnWithName(prefix + "konda_string")
  val pltyp_string: ColumnWithName = ColumnWithName(prefix + "pltyp_string")
  val awahr_string: ColumnWithName = ColumnWithName(prefix + "awahr_string")
  val inco1_string: ColumnWithName = ColumnWithName(prefix + "inco1_string")
  val inco2_string: ColumnWithName = ColumnWithName(prefix + "inco2_string")
  val lifsd_string: ColumnWithName = ColumnWithName(prefix + "lifsd_string")
  val autlf_string: ColumnWithName = ColumnWithName(prefix + "autlf_string")
  val antlf_decimal_1_0: ColumnWithName = ColumnWithName(prefix + "antlf_decimal_1_0")
  val kztlf_string: ColumnWithName = ColumnWithName(prefix + "kztlf_string")
  val kzazu_string: ColumnWithName = ColumnWithName(prefix + "kzazu_string")
  val chspl_string: ColumnWithName = ColumnWithName(prefix + "chspl_string")
  val lprio_string: ColumnWithName = ColumnWithName(prefix + "lprio_string")
  val eikto_string: ColumnWithName = ColumnWithName(prefix + "eikto_string")
  val vsbed_string: ColumnWithName = ColumnWithName(prefix + "vsbed_string")
  val faksd_string: ColumnWithName = ColumnWithName(prefix + "faksd_string")
  val mrnkz_string: ColumnWithName = ColumnWithName(prefix + "mrnkz_string")
  val perfk_string: ColumnWithName = ColumnWithName(prefix + "perfk_string")
  val perrl_string: ColumnWithName = ColumnWithName(prefix + "perrl_string")
  val kvakz_string: ColumnWithName = ColumnWithName(prefix + "kvakz_string")
  val kvawt_decimal_13_2: ColumnWithName = ColumnWithName(prefix + "kvawt_decimal_13_2")
  val waers_string: ColumnWithName = ColumnWithName(prefix + "waers_string")
  val klabc_string: ColumnWithName = ColumnWithName(prefix + "klabc_string")
  val ktgrd_string: ColumnWithName = ColumnWithName(prefix + "ktgrd_string")
  val zterm_string: ColumnWithName = ColumnWithName(prefix + "zterm_string")
  val vwerk_string: ColumnWithName = ColumnWithName(prefix + "vwerk_string")
  val vkgrp_string: ColumnWithName = ColumnWithName(prefix + "vkgrp_string")
  val vkbur_string: ColumnWithName = ColumnWithName(prefix + "vkbur_string")
  val vsort_string: ColumnWithName = ColumnWithName(prefix + "vsort_string")
  val kvgr1_string: ColumnWithName = ColumnWithName(prefix + "kvgr1_string")
  val kvgr2_string: ColumnWithName = ColumnWithName(prefix + "kvgr2_string")
  val kvgr3_string: ColumnWithName = ColumnWithName(prefix + "kvgr3_string")
  val kvgr4_string: ColumnWithName = ColumnWithName(prefix + "kvgr4_string")
  val kvgr5_string: ColumnWithName = ColumnWithName(prefix + "kvgr5_string")
  val bokre_string: ColumnWithName = ColumnWithName(prefix + "bokre_string")
  val boidt_string: ColumnWithName = ColumnWithName(prefix + "boidt_string")
  val kurst_string: ColumnWithName = ColumnWithName(prefix + "kurst_string")
  val prfre_string: ColumnWithName = ColumnWithName(prefix + "prfre_string")
  val prat1_string: ColumnWithName = ColumnWithName(prefix + "prat1_string")
  val prat2_string: ColumnWithName = ColumnWithName(prefix + "prat2_string")
  val prat3_string: ColumnWithName = ColumnWithName(prefix + "prat3_string")
  val prat4_string: ColumnWithName = ColumnWithName(prefix + "prat4_string")
  val prat5_string: ColumnWithName = ColumnWithName(prefix + "prat5_string")
  val prat6_string: ColumnWithName = ColumnWithName(prefix + "prat6_string")
  val prat7_string: ColumnWithName = ColumnWithName(prefix + "prat7_string")
  val prat8_string: ColumnWithName = ColumnWithName(prefix + "prat8_string")
  val prat9_string: ColumnWithName = ColumnWithName(prefix + "prat9_string")
  val prata_string: ColumnWithName = ColumnWithName(prefix + "prata_string")
  val kabss_string: ColumnWithName = ColumnWithName(prefix + "kabss_string")
  val kkber_string: ColumnWithName = ColumnWithName(prefix + "kkber_string")
  val cassd_string: ColumnWithName = ColumnWithName(prefix + "cassd_string")
  val rdoff_string: ColumnWithName = ColumnWithName(prefix + "rdoff_string")
  val agrel_string: ColumnWithName = ColumnWithName(prefix + "agrel_string")
  val megru_string: ColumnWithName = ColumnWithName(prefix + "megru_string")
  val uebto_decimal_3_1: ColumnWithName = ColumnWithName(prefix + "uebto_decimal_3_1")
  val untto_decimal_3_1: ColumnWithName = ColumnWithName(prefix + "untto_decimal_3_1")
  val uebtk_string: ColumnWithName = ColumnWithName(prefix + "uebtk_string")
  val pvksm_string: ColumnWithName = ColumnWithName(prefix + "pvksm_string")
  val podkz_string: ColumnWithName = ColumnWithName(prefix + "podkz_string")
  val podtg_decimal_11_0: ColumnWithName = ColumnWithName(prefix + "podtg_decimal_11_0")
  val blind_string: ColumnWithName = ColumnWithName(prefix + "blind_string")
  val carrier_notif_string: ColumnWithName = ColumnWithName(prefix + "carrier_notif_string")
  val cvp_xblck_v_string: ColumnWithName = ColumnWithName(prefix + "cvp_xblck_v_string")
  val incov_string: ColumnWithName = ColumnWithName(prefix + "incov_string")
  val inco2_l_string: ColumnWithName = ColumnWithName(prefix + "inco2_l_string")
  val inco3_l_string: ColumnWithName = ColumnWithName(prefix + "inco3_l_string")
  val _bev1_emlgpfand_string: ColumnWithName = ColumnWithName(prefix + "_bev1_emlgpfand_string")
  val _bev1_emlgforts_string: ColumnWithName = ColumnWithName(prefix + "_bev1_emlgforts_string")
  val j_1nboesl_string: ColumnWithName = ColumnWithName(prefix + "j_1nboesl_string")
  val profile_string: ColumnWithName = ColumnWithName(prefix + "profile_string")
  val fpart_string: ColumnWithName = ColumnWithName(prefix + "fpart_string")
  val fsh_kvgr6_string: ColumnWithName = ColumnWithName(prefix + "fsh_kvgr6_string")
  val fsh_kvgr7_string: ColumnWithName = ColumnWithName(prefix + "fsh_kvgr7_string")
  val fsh_kvgr8_string: ColumnWithName = ColumnWithName(prefix + "fsh_kvgr8_string")
  val fsh_kvgr9_string: ColumnWithName = ColumnWithName(prefix + "fsh_kvgr9_string")
  val fsh_kvgr10_string: ColumnWithName = ColumnWithName(prefix + "fsh_kvgr10_string")
  val fsh_grreg_string: ColumnWithName = ColumnWithName(prefix + "fsh_grreg_string")
  val fsh_resgy_string: ColumnWithName = ColumnWithName(prefix + "fsh_resgy_string")
  val fsh_sc_cid_string: ColumnWithName = ColumnWithName(prefix + "fsh_sc_cid_string")
  val fsh_vas_detc_string: ColumnWithName = ColumnWithName(prefix + "fsh_vas_detc_string")
  val fsh_vas_cg_string: ColumnWithName = ColumnWithName(prefix + "fsh_vas_cg_string")
  val fsh_grsgy_string: ColumnWithName = ColumnWithName(prefix + "fsh_grsgy_string")
  val fsh_ss_string: ColumnWithName = ColumnWithName(prefix + "fsh_ss_string")
  val fsh_msocdc_string: ColumnWithName = ColumnWithName(prefix + "fsh_msocdc_string")
  val fsh_msopid_string: ColumnWithName = ColumnWithName(prefix + "fsh_msopid_string")
  val zztriggerpoint_string: ColumnWithName = ColumnWithName(prefix + "zztriggerpoint_string")
  val zztraztd_decimal_11_0: ColumnWithName = ColumnWithName(prefix + "zztraztd_decimal_11_0")
  val zzprecarriage_string: ColumnWithName = ColumnWithName(prefix + "zzprecarriage_string")
  val zzreceiptloc_string: ColumnWithName = ColumnWithName(prefix + "zzreceiptloc_string")
  val zzportofloading_string: ColumnWithName = ColumnWithName(prefix + "zzportofloading_string")
  val zzportofdisch_string: ColumnWithName = ColumnWithName(prefix + "zzportofdisch_string")
  val zzdeliveryplace_string: ColumnWithName = ColumnWithName(prefix + "zzdeliveryplace_string")
  val zzspecind_string: ColumnWithName = ColumnWithName(prefix + "zzspecind_string")
  val zzsegal_string: ColumnWithName = ColumnWithName(prefix + "zzsegal_string")
  val yfta_string: ColumnWithName = ColumnWithName(prefix + "yfta_string")
}

object C_knvv extends C_knvv("") {
  def as(alias: String): C_knvv = new C_knvv(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
