// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_p24

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_p24.{ekbe => sr_raw_ekbe}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrEkbe(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK ebeln: String,
    @PK ebelp: String,
    @PK zekkn: String,
    @PK vgabe: String,
    @PK gjahr: String,
    @PK belnr: String,
    @PK buzei: String,
    bewtp: String,
    bwart: String,
    budat: String,
    @Decimal(13, 3) menge: java.math.BigDecimal,
    @Decimal(13, 3) bpmng: java.math.BigDecimal,
    @Decimal(13, 2) dmbtr: java.math.BigDecimal,
    @Decimal(13, 2) wrbtr: java.math.BigDecimal,
    waers: String,
    @Decimal(13, 2) arewr: java.math.BigDecimal,
    @Decimal(13, 3) wesbs: java.math.BigDecimal,
    @Decimal(13, 3) bpwes: java.math.BigDecimal,
    shkzg: String,
    bwtar: String,
    elikz: String,
    xblnr: String,
    lfgja: String,
    lfbnr: String,
    lfpos: String,
    grund: String,
    cpudt: String,
    cputm: String,
    @Decimal(13, 2) reewr: java.math.BigDecimal,
    evere: String,
    @Decimal(13, 2) refwr: java.math.BigDecimal,
    matnr: String,
    werks: String,
    xwsbr: String,
    etens: String,
    knumv: String,
    mwskz: String,
    @Decimal(13, 3) lsmng: java.math.BigDecimal,
    lsmeh: String,
    ematn: String,
    @Decimal(13, 2) areww: java.math.BigDecimal,
    hswae: String,
    @Decimal(13, 3) bamng: java.math.BigDecimal,
    charg: String,
    bldat: String,
    xwoff: String,
    xunpl: String,
    ernam: String,
    srvpos: String,
    packno: String,
    introw: String,
    bekkn: String,
    lemin: String,
    @Decimal(13, 2) arewb: java.math.BigDecimal,
    @Decimal(13, 2) rewrb: java.math.BigDecimal,
    saprl: String,
    @Decimal(13, 3) menge_pop: java.math.BigDecimal,
    @Decimal(13, 3) bpmng_pop: java.math.BigDecimal,
    @Decimal(13, 2) dmbtr_pop: java.math.BigDecimal,
    @Decimal(13, 2) wrbtr_pop: java.math.BigDecimal,
    @Decimal(13, 3) wesbb: java.math.BigDecimal,
    @Decimal(13, 3) bpweb: java.math.BigDecimal,
    weora: String,
    @Decimal(13, 2) arewr_pop: java.math.BigDecimal,
    @Decimal(13, 2) kudif: java.math.BigDecimal,
    @Decimal(13, 2) retamt_fc: java.math.BigDecimal,
    @Decimal(13, 2) retamt_lc: java.math.BigDecimal,
    @Decimal(13, 2) retamtp_fc: java.math.BigDecimal,
    @Decimal(13, 2) retamtp_lc: java.math.BigDecimal,
    xmacc: String,
    @Decimal(9, 5) wkurs: java.math.BigDecimal,
    inv_item_origin: String,
    vbeln_st: String,
    vbelp_st: String,
    sgt_scat: String,
    et_upd: String,
    j_sc_die_comp_f: String,
    @Decimal(13, 3) qty_diff: java.math.BigDecimal
) extends Entity

object ekbe extends TableSpec[SrEkbe] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_p24.E_ekbe] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_p24.E_ekbe] = sr_raw_ekbe

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("ebeln", coalesce(col("ebeln_string"), lit(""))),
    ("ebelp", coalesce(col("ebelp_string"), lit(""))),
    ("zekkn", coalesce(col("zekkn_string"), lit(""))),
    ("vgabe", coalesce(col("vgabe_string"), lit(""))),
    ("gjahr", coalesce(col("gjahr_string"), lit(""))),
    ("belnr", coalesce(col("belnr_string"), lit(""))),
    ("buzei", coalesce(col("buzei_string"), lit(""))),
    ("bewtp", col("bewtp_string")),
    ("bwart", col("bwart_string")),
    ("budat", col("budat_string")),
    ("menge", col("menge_decimal_13_3")),
    ("bpmng", col("bpmng_decimal_13_3")),
    ("dmbtr", col("dmbtr_decimal_13_2")),
    ("wrbtr", col("wrbtr_decimal_13_2")),
    ("waers", col("waers_string")),
    ("arewr", col("arewr_decimal_13_2")),
    ("wesbs", col("wesbs_decimal_13_3")),
    ("bpwes", col("bpwes_decimal_13_3")),
    ("shkzg", col("shkzg_string")),
    ("bwtar", col("bwtar_string")),
    ("elikz", col("elikz_string")),
    ("xblnr", col("xblnr_string")),
    ("lfgja", col("lfgja_string")),
    ("lfbnr", col("lfbnr_string")),
    ("lfpos", col("lfpos_string")),
    ("grund", col("grund_string")),
    ("cpudt", col("cpudt_string")),
    ("cputm", col("cputm_string")),
    ("reewr", col("reewr_decimal_13_2")),
    ("evere", col("evere_string")),
    ("refwr", col("refwr_decimal_13_2")),
    ("matnr", col("matnr_string")),
    ("werks", col("werks_string")),
    ("xwsbr", col("xwsbr_string")),
    ("etens", col("etens_string")),
    ("knumv", col("knumv_string")),
    ("mwskz", col("mwskz_string")),
    ("lsmng", col("lsmng_decimal_13_3")),
    ("lsmeh", col("lsmeh_string")),
    ("ematn", col("ematn_string")),
    ("areww", col("areww_decimal_13_2")),
    ("hswae", col("hswae_string")),
    ("bamng", col("bamng_decimal_13_3")),
    ("charg", col("charg_string")),
    ("bldat", col("bldat_string")),
    ("xwoff", col("xwoff_string")),
    ("xunpl", col("xunpl_string")),
    ("ernam", col("ernam_string")),
    ("srvpos", col("srvpos_string")),
    ("packno", col("packno_string")),
    ("introw", col("introw_string")),
    ("bekkn", col("bekkn_string")),
    ("lemin", col("lemin_string")),
    ("arewb", col("arewb_decimal_13_2")),
    ("rewrb", col("rewrb_decimal_13_2")),
    ("saprl", col("saprl_string")),
    ("menge_pop", col("menge_pop_decimal_13_3")),
    ("bpmng_pop", col("bpmng_pop_decimal_13_3")),
    ("dmbtr_pop", col("dmbtr_pop_decimal_13_2")),
    ("wrbtr_pop", col("wrbtr_pop_decimal_13_2")),
    ("wesbb", col("wesbb_decimal_13_3")),
    ("bpweb", col("bpweb_decimal_13_3")),
    ("weora", col("weora_string")),
    ("arewr_pop", col("arewr_pop_decimal_13_2")),
    ("kudif", col("kudif_decimal_13_2")),
    ("retamt_fc", col("retamt_fc_decimal_13_2")),
    ("retamt_lc", col("retamt_lc_decimal_13_2")),
    ("retamtp_fc", col("retamtp_fc_decimal_13_2")),
    ("retamtp_lc", col("retamtp_lc_decimal_13_2")),
    ("xmacc", col("xmacc_string")),
    ("wkurs", col("wkurs_decimal_9_5")),
    ("inv_item_origin", col("inv_item_origin_string")),
    ("vbeln_st", col("vbeln_st_string")),
    ("vbelp_st", col("vbelp_st_string")),
    ("sgt_scat", col("sgt_scat_string")),
    ("et_upd", col("et_upd_string")),
    ("j_sc_die_comp_f", col("j_sc_die_comp_f_string")),
    ("qty_diff", col("qty_diff_decimal_13_3"))
  )
}
