// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_p24

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{Joined, PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_p24.{ekpo => sr_raw_ekpo}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrEkpo_Part1(
    @PK ebeln: String,
    @PK ebelp: String,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    loekz: String,
    statu: String,
    aedat: String,
    txz01: String,
    matnr: String,
    ematn: String,
    bukrs: String,
    werks: String,
    lgort: String,
    bednr: String,
    matkl: String,
    infnr: String,
    idnlf: String,
    @Decimal(13, 3) ktmng: java.math.BigDecimal,
    @Decimal(13, 3) menge: java.math.BigDecimal,
    meins: String,
    bprme: String,
    @Decimal(5, 0) bpumz: java.math.BigDecimal,
    @Decimal(5, 0) bpumn: java.math.BigDecimal,
    @Decimal(5, 0) umrez: java.math.BigDecimal,
    @Decimal(5, 0) umren: java.math.BigDecimal,
    @Decimal(11, 2) netpr: java.math.BigDecimal,
    @Decimal(5, 0) peinh: java.math.BigDecimal,
    @Decimal(13, 2) netwr: java.math.BigDecimal,
    @Decimal(13, 2) brtwr: java.math.BigDecimal,
    agdat: String,
    @Decimal(3, 0) webaz: java.math.BigDecimal,
    mwskz: String,
    bonus: String,
    insmk: String,
    spinf: String,
    prsdr: String,
    schpr: String,
    @Decimal(3, 0) mahnz: java.math.BigDecimal,
    @Decimal(3, 0) mahn1: java.math.BigDecimal,
    @Decimal(3, 0) mahn2: java.math.BigDecimal,
    @Decimal(3, 0) mahn3: java.math.BigDecimal,
    @Decimal(3, 1) uebto: java.math.BigDecimal,
    uebtk: String,
    @Decimal(3, 1) untto: java.math.BigDecimal,
    bwtar: String,
    bwtty: String,
    abskz: String,
    agmem: String,
    elikz: String,
    erekz: String,
    pstyp: String,
    knttp: String,
    kzvbr: String,
    vrtkz: String,
    twrkz: String,
    wepos: String,
    weunb: String,
    repos: String,
    webre: String,
    kzabs: String,
    labnr: String,
    konnr: String,
    ktpnr: String,
    abdat: String,
    @Decimal(13, 3) abftz: java.math.BigDecimal,
    @Decimal(3, 0) etfz1: java.math.BigDecimal,
    @Decimal(3, 0) etfz2: java.math.BigDecimal,
    kzstu: String,
    notkz: String,
    lmein: String,
    evers: String,
    @Decimal(13, 2) zwert: java.math.BigDecimal,
    @Decimal(13, 2) navnw: java.math.BigDecimal,
    @Decimal(13, 3) abmng: java.math.BigDecimal,
    prdat: String,
    bstyp: String,
    @Decimal(13, 2) effwr: java.math.BigDecimal,
    xoblr: String,
    kunnr: String,
    adrnr: String,
    ekkol: String,
    sktof: String,
    stafo: String,
    @Decimal(3, 0) plifz: java.math.BigDecimal,
    @Decimal(13, 3) ntgew: java.math.BigDecimal,
    gewei: String,
    txjcd: String,
    etdrk: String,
    sobkz: String,
    arsnr: String,
    arsps: String,
    insnc: String,
    ssqss: String,
    zgtyp: String,
    ean11: String,
    bstae: String,
    revlv: String,
    geber: String,
    fistl: String,
    fipos: String,
    ko_gsber: String,
    ko_pargb: String,
    ko_prctr: String,
    ko_pprctr: String,
    meprf: String,
    @Decimal(13, 3) brgew: java.math.BigDecimal,
    @Decimal(13, 3) volum: java.math.BigDecimal,
    voleh: String,
    inco1: String,
    inco2: String,
    vorab: String,
    kolif: String,
    ltsnr: String,
    packno: String,
    fplnr: String,
    @Decimal(13, 2) gnetwr: java.math.BigDecimal,
    stapo: String,
    uebpo: String,
    lewed: String,
    emlif: String,
    lblkz: String,
    satnr: String,
    attyp: String,
    vsart: String,
    handoverloc: String,
    kanba: String,
    adrn2: String,
    cuobj: String,
    xersy: String,
    eildt: String,
    drdat: String,
    druhr: String,
    drunr: String,
    aktnr: String,
    abeln: String,
    abelp: String,
    @Decimal(13, 3) anzpu: java.math.BigDecimal,
    punei: String,
    saiso: String,
    saisj: String,
    ebon2: String,
    ebon3: String,
    ebonf: String,
    mlmaa: String,
    @Decimal(4, 0) mhdrz: java.math.BigDecimal,
    anfnr: String,
    anfps: String,
    kzkfg: String,
    usequ: String,
    umsok: String,
    banfn: String,
    bnfpo: String,
    mtart: String,
    uptyp: String,
    upvor: String,
    @Decimal(13, 2) kzwi1: java.math.BigDecimal,
    @Decimal(13, 2) kzwi2: java.math.BigDecimal,
    @Decimal(13, 2) kzwi3: java.math.BigDecimal,
    @Decimal(13, 2) kzwi4: java.math.BigDecimal,
    @Decimal(13, 2) kzwi5: java.math.BigDecimal,
    @Decimal(13, 2) kzwi6: java.math.BigDecimal,
    sikgr: String,
    @Decimal(15, 3) mfzhi: java.math.BigDecimal,
    @Decimal(15, 3) ffzhi: java.math.BigDecimal,
    retpo: String,
    aurel: String,
    bsgru: String,
    lfret: String,
    mfrgr: String,
    nrfhg: String,
    j_1bnbm: String,
    j_1bmatuse: String,
    j_1bmatorg: String,
    j_1bownpro: String,
    j_1bindust: String,
    abueb: String,
    nlabd: String,
    nfabd: String,
    kzbws: String,
    @Decimal(13, 2) bonba: java.math.BigDecimal,
    fabkz: String,
    j_1aindxp: String,
    j_1aidatep: String,
    mprof: String,
    eglkz: String,
    kztlf: String,
    kzfme: String,
    rdprf: String,
    techs: String,
    chg_srv: String,
    chg_fplnr: String,
    mfrpn: String,
    mfrnr: String,
    emnfr: String,
    novet: String,
    afnam: String,
    tzonrc: String,
    iprkz: String,
    lebre: String,
    berid: String,
    xconditions: String,
    apoms: String,
    ccomp: String,
    grant_nbr: String,
    fkber: String,
    status: String,
    reslo: String,
    kblnr: String,
    kblpos: String,
    weora: String,
    srv_bas_com: String,
    prio_urg: String,
    prio_req: String,
    empst: String,
    diff_invoice: String,
    trmrisk_relevant: String,
    creationdate: String,
    creationtime: String,
    spe_abgru: String,
    spe_crm_so: String,
    spe_crm_so_item: String,
    spe_crm_ref_so: String,
    spe_crm_ref_item: String,
    spe_crm_fkrel: String,
    spe_chng_sys: String,
    spe_insmk_src: String,
    spe_cq_ctrltype: String,
    spe_cq_nocq: String,
    reason_code: String,
    @Decimal(15, 3) cqu_sar: java.math.BigDecimal,
    anzsn: Int,
    spe_ewm_dtc: String,
    exlin: String,
    exsnr: String,
    ehtyp: String,
    @Decimal(5, 2) retpc: java.math.BigDecimal,
    dptyp: String,
    @Decimal(5, 2) dppct: java.math.BigDecimal,
    @Decimal(11, 2) dpamt: java.math.BigDecimal,
    dpdat: String,
    fls_rsto: String,
    ext_rfx_number: String,
    ext_rfx_item: String
) extends Entity

case class SrEkpo_Part2(
    @PK ebeln: String,
    @PK ebelp: String,
    @NotNull _mk_org: String,
    ext_rfx_system: String,
    srm_contract_id: String,
    srm_contract_itm: String,
    blk_reason_id: String,
    blk_reason_txt: String,
    itcons: String,
    fixmg: String,
    wabwe: String,
    cmpl_dlv_itm: String,
    inco2_l: String,
    inco3_l: String,
    externalreferenceid: String,
    tc_aut_det: String,
    manual_tc_reason: String,
    fiscal_incentive: String,
    tax_subject_st: String,
    fiscal_incentive_id: String,
    sf_txjcd: String,
    _bev1_negen_item: String,
    _bev1_nedepfree: String,
    _bev1_nestruccat: String,
    advcode: String,
    budget_pd: String,
    excpe: String,
    fmfgus_key: String,
    iuid_relevant: String,
    mrpind: String,
    sgt_scat: String,
    sgt_rcat: String,
    wrf_charstc1: String,
    wrf_charstc2: String,
    wrf_charstc3: String,
    refsite: String,
    _sapmp_gpose: String,
    angpn: String,
    admoi: String,
    adpri: String,
    lprio: String,
    adacn: String,
    afpnr: String,
    bsark: String,
    audat: String,
    angnr: String,
    pnstat: String,
    addns: String,
    serru: String,
    sernp: String,
    disub_sobkz: String,
    disub_pspnr: String,
    disub_kunnr: String,
    disub_vbeln: String,
    disub_posnr: String,
    disub_owner: String,
    fsh_season_year: String,
    fsh_season: String,
    fsh_collection: String,
    fsh_theme: String,
    fsh_atp_date: String,
    fsh_vas_rel: String,
    fsh_vas_prnt_id: String,
    fsh_transaction: String,
    fsh_item_group: String,
    fsh_item: String,
    fsh_ss: String,
    fsh_grid_cond_rec: String,
    fsh_psm_pfm_split: String,
    @Decimal(13, 3) cnfm_qty: java.math.BigDecimal,
    fsh_pqr_uepos: String,
    stpac: String,
    lgbzo: String,
    lgbzo_b: String,
    addrnum: String,
    consnum: String,
    borgr_miss: String,
    ref_item: String,
    source_id: String,
    source_key: String,
    put_back: String,
    pol_id: String,
    cons_order: String
) extends Entity

object ekpo
    extends TableSpec[Joined[SrEkpo_Part1, SrEkpo_Part2]]
    with ChangeKey[
      ct.dna.lakehouse.core.model.Entity.Joined[ct.dna.lakehouse.sr_raw.ct_gbl_p24.E_ekpo_part1, ct.dna.lakehouse.sr_raw.ct_gbl_p24.E_ekpo_part2]
    ] {

  override def sourceTableSpec
      : TableSpec[ct.dna.lakehouse.core.model.Entity.Joined[ct.dna.lakehouse.sr_raw.ct_gbl_p24.E_ekpo_part1, ct.dna.lakehouse.sr_raw.ct_gbl_p24.E_ekpo_part2]] =
    sr_raw_ekpo

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("ebeln", coalesce(col("ebeln_string"), lit(""))),
    ("ebelp", coalesce(col("ebelp_string"), lit(""))),
    ("loekz", col("loekz_string")),
    ("statu", col("statu_string")),
    ("aedat", col("aedat_string")),
    ("txz01", col("txz01_string")),
    ("matnr", col("matnr_string")),
    ("ematn", col("ematn_string")),
    ("bukrs", col("bukrs_string")),
    ("werks", col("werks_string")),
    ("lgort", col("lgort_string")),
    ("bednr", col("bednr_string")),
    ("matkl", col("matkl_string")),
    ("infnr", col("infnr_string")),
    ("idnlf", col("idnlf_string")),
    ("ktmng", col("ktmng_decimal_13_3")),
    ("menge", col("menge_decimal_13_3")),
    ("meins", col("meins_string")),
    ("bprme", col("bprme_string")),
    ("bpumz", col("bpumz_decimal_5_0")),
    ("bpumn", col("bpumn_decimal_5_0")),
    ("umrez", col("umrez_decimal_5_0")),
    ("umren", col("umren_decimal_5_0")),
    ("netpr", col("netpr_decimal_11_2")),
    ("peinh", col("peinh_decimal_5_0")),
    ("netwr", col("netwr_decimal_13_2")),
    ("brtwr", col("brtwr_decimal_13_2")),
    ("agdat", col("agdat_string")),
    ("webaz", col("webaz_decimal_3_0")),
    ("mwskz", col("mwskz_string")),
    ("bonus", col("bonus_string")),
    ("insmk", col("insmk_string")),
    ("spinf", col("spinf_string")),
    ("prsdr", col("prsdr_string")),
    ("schpr", col("schpr_string")),
    ("mahnz", col("mahnz_decimal_3_0")),
    ("mahn1", col("mahn1_decimal_3_0")),
    ("mahn2", col("mahn2_decimal_3_0")),
    ("mahn3", col("mahn3_decimal_3_0")),
    ("uebto", col("uebto_decimal_3_1")),
    ("uebtk", col("uebtk_string")),
    ("untto", col("untto_decimal_3_1")),
    ("bwtar", col("bwtar_string")),
    ("bwtty", col("bwtty_string")),
    ("abskz", col("abskz_string")),
    ("agmem", col("agmem_string")),
    ("elikz", col("elikz_string")),
    ("erekz", col("erekz_string")),
    ("pstyp", col("pstyp_string")),
    ("knttp", col("knttp_string")),
    ("kzvbr", col("kzvbr_string")),
    ("vrtkz", col("vrtkz_string")),
    ("twrkz", col("twrkz_string")),
    ("wepos", col("wepos_string")),
    ("weunb", col("weunb_string")),
    ("repos", col("repos_string")),
    ("webre", col("webre_string")),
    ("kzabs", col("kzabs_string")),
    ("labnr", col("labnr_string")),
    ("konnr", col("konnr_string")),
    ("ktpnr", col("ktpnr_string")),
    ("abdat", col("abdat_string")),
    ("abftz", col("abftz_decimal_13_3")),
    ("etfz1", col("etfz1_decimal_3_0")),
    ("etfz2", col("etfz2_decimal_3_0")),
    ("kzstu", col("kzstu_string")),
    ("notkz", col("notkz_string")),
    ("lmein", col("lmein_string")),
    ("evers", col("evers_string")),
    ("zwert", col("zwert_decimal_13_2")),
    ("navnw", col("navnw_decimal_13_2")),
    ("abmng", col("abmng_decimal_13_3")),
    ("prdat", col("prdat_string")),
    ("bstyp", col("bstyp_string")),
    ("effwr", col("effwr_decimal_13_2")),
    ("xoblr", col("xoblr_string")),
    ("kunnr", col("kunnr_string")),
    ("adrnr", col("adrnr_string")),
    ("ekkol", col("ekkol_string")),
    ("sktof", col("sktof_string")),
    ("stafo", col("stafo_string")),
    ("plifz", col("plifz_decimal_3_0")),
    ("ntgew", col("ntgew_decimal_13_3")),
    ("gewei", col("gewei_string")),
    ("txjcd", col("txjcd_string")),
    ("etdrk", col("etdrk_string")),
    ("sobkz", col("sobkz_string")),
    ("arsnr", col("arsnr_string")),
    ("arsps", col("arsps_string")),
    ("insnc", col("insnc_string")),
    ("ssqss", col("ssqss_string")),
    ("zgtyp", col("zgtyp_string")),
    ("ean11", col("ean11_string")),
    ("bstae", col("bstae_string")),
    ("revlv", col("revlv_string")),
    ("geber", col("geber_string")),
    ("fistl", col("fistl_string")),
    ("fipos", col("fipos_string")),
    ("ko_gsber", col("ko_gsber_string")),
    ("ko_pargb", col("ko_pargb_string")),
    ("ko_prctr", col("ko_prctr_string")),
    ("ko_pprctr", col("ko_pprctr_string")),
    ("meprf", col("meprf_string")),
    ("brgew", col("brgew_decimal_13_3")),
    ("volum", col("volum_decimal_13_3")),
    ("voleh", col("voleh_string")),
    ("inco1", col("inco1_string")),
    ("inco2", col("inco2_string")),
    ("vorab", col("vorab_string")),
    ("kolif", col("kolif_string")),
    ("ltsnr", col("ltsnr_string")),
    ("packno", col("packno_string")),
    ("fplnr", col("fplnr_string")),
    ("gnetwr", col("gnetwr_decimal_13_2")),
    ("stapo", col("stapo_string")),
    ("uebpo", col("uebpo_string")),
    ("lewed", col("lewed_string")),
    ("emlif", col("emlif_string")),
    ("lblkz", col("lblkz_string")),
    ("satnr", col("satnr_string")),
    ("attyp", col("attyp_string")),
    ("vsart", col("vsart_string")),
    ("handoverloc", col("handoverloc_string")),
    ("kanba", col("kanba_string")),
    ("adrn2", col("adrn2_string")),
    ("cuobj", col("cuobj_string")),
    ("xersy", col("xersy_string")),
    ("eildt", col("eildt_string")),
    ("drdat", col("drdat_string")),
    ("druhr", col("druhr_string")),
    ("drunr", col("drunr_string")),
    ("aktnr", col("aktnr_string")),
    ("abeln", col("abeln_string")),
    ("abelp", col("abelp_string")),
    ("anzpu", col("anzpu_decimal_13_3")),
    ("punei", col("punei_string")),
    ("saiso", col("saiso_string")),
    ("saisj", col("saisj_string")),
    ("ebon2", col("ebon2_string")),
    ("ebon3", col("ebon3_string")),
    ("ebonf", col("ebonf_string")),
    ("mlmaa", col("mlmaa_string")),
    ("mhdrz", col("mhdrz_decimal_4_0")),
    ("anfnr", col("anfnr_string")),
    ("anfps", col("anfps_string")),
    ("kzkfg", col("kzkfg_string")),
    ("usequ", col("usequ_string")),
    ("umsok", col("umsok_string")),
    ("banfn", col("banfn_string")),
    ("bnfpo", col("bnfpo_string")),
    ("mtart", col("mtart_string")),
    ("uptyp", col("uptyp_string")),
    ("upvor", col("upvor_string")),
    ("kzwi1", col("kzwi1_decimal_13_2")),
    ("kzwi2", col("kzwi2_decimal_13_2")),
    ("kzwi3", col("kzwi3_decimal_13_2")),
    ("kzwi4", col("kzwi4_decimal_13_2")),
    ("kzwi5", col("kzwi5_decimal_13_2")),
    ("kzwi6", col("kzwi6_decimal_13_2")),
    ("sikgr", col("sikgr_string")),
    ("mfzhi", col("mfzhi_decimal_15_3")),
    ("ffzhi", col("ffzhi_decimal_15_3")),
    ("retpo", col("retpo_string")),
    ("aurel", col("aurel_string")),
    ("bsgru", col("bsgru_string")),
    ("lfret", col("lfret_string")),
    ("mfrgr", col("mfrgr_string")),
    ("nrfhg", col("nrfhg_string")),
    ("j_1bnbm", col("j_1bnbm_string")),
    ("j_1bmatuse", col("j_1bmatuse_string")),
    ("j_1bmatorg", col("j_1bmatorg_string")),
    ("j_1bownpro", col("j_1bownpro_string")),
    ("j_1bindust", col("j_1bindust_string")),
    ("abueb", col("abueb_string")),
    ("nlabd", col("nlabd_string")),
    ("nfabd", col("nfabd_string")),
    ("kzbws", col("kzbws_string")),
    ("bonba", col("bonba_decimal_13_2")),
    ("fabkz", col("fabkz_string")),
    ("j_1aindxp", col("j_1aindxp_string")),
    ("j_1aidatep", col("j_1aidatep_string")),
    ("mprof", col("mprof_string")),
    ("eglkz", col("eglkz_string")),
    ("kztlf", col("kztlf_string")),
    ("kzfme", col("kzfme_string")),
    ("rdprf", col("rdprf_string")),
    ("techs", col("techs_string")),
    ("chg_srv", col("chg_srv_string")),
    ("chg_fplnr", col("chg_fplnr_string")),
    ("mfrpn", col("mfrpn_string")),
    ("mfrnr", col("mfrnr_string")),
    ("emnfr", col("emnfr_string")),
    ("novet", col("novet_string")),
    ("afnam", col("afnam_string")),
    ("tzonrc", col("tzonrc_string")),
    ("iprkz", col("iprkz_string")),
    ("lebre", col("lebre_string")),
    ("berid", col("berid_string")),
    ("xconditions", col("xconditions_string")),
    ("apoms", col("apoms_string")),
    ("ccomp", col("ccomp_string")),
    ("grant_nbr", col("grant_nbr_string")),
    ("fkber", col("fkber_string")),
    ("status", col("status_string")),
    ("reslo", col("reslo_string")),
    ("kblnr", col("kblnr_string")),
    ("kblpos", col("kblpos_string")),
    ("weora", col("weora_string")),
    ("srv_bas_com", col("srv_bas_com_string")),
    ("prio_urg", col("prio_urg_string")),
    ("prio_req", col("prio_req_string")),
    ("empst", col("empst_string")),
    ("diff_invoice", col("diff_invoice_string")),
    ("trmrisk_relevant", col("trmrisk_relevant_string")),
    ("creationdate", col("creationdate_string")),
    ("creationtime", col("creationtime_string")),
    ("spe_abgru", col("spe_abgru_string")),
    ("spe_crm_so", col("spe_crm_so_string")),
    ("spe_crm_so_item", col("spe_crm_so_item_string")),
    ("spe_crm_ref_so", col("spe_crm_ref_so_string")),
    ("spe_crm_ref_item", col("spe_crm_ref_item_string")),
    ("spe_crm_fkrel", col("spe_crm_fkrel_string")),
    ("spe_chng_sys", col("spe_chng_sys_string")),
    ("spe_insmk_src", col("spe_insmk_src_string")),
    ("spe_cq_ctrltype", col("spe_cq_ctrltype_string")),
    ("spe_cq_nocq", col("spe_cq_nocq_string")),
    ("reason_code", col("reason_code_string")),
    ("cqu_sar", col("cqu_sar_decimal_15_3")),
    ("anzsn", coalesce(col("anzsn_int"), lit(0))),
    ("spe_ewm_dtc", col("spe_ewm_dtc_string")),
    ("exlin", col("exlin_string")),
    ("exsnr", col("exsnr_string")),
    ("ehtyp", col("ehtyp_string")),
    ("retpc", col("retpc_decimal_5_2")),
    ("dptyp", col("dptyp_string")),
    ("dppct", col("dppct_decimal_5_2")),
    ("dpamt", col("dpamt_decimal_11_2")),
    ("dpdat", col("dpdat_string")),
    ("fls_rsto", col("fls_rsto_string")),
    ("ext_rfx_number", col("ext_rfx_number_string")),
    ("ext_rfx_item", col("ext_rfx_item_string")),
    ("_mk_org", col("_mk_org")),
    ("ext_rfx_system", col("ext_rfx_system_string")),
    ("srm_contract_id", col("srm_contract_id_string")),
    ("srm_contract_itm", col("srm_contract_itm_string")),
    ("blk_reason_id", col("blk_reason_id_string")),
    ("blk_reason_txt", col("blk_reason_txt_string")),
    ("itcons", col("itcons_string")),
    ("fixmg", col("fixmg_string")),
    ("wabwe", col("wabwe_string")),
    ("cmpl_dlv_itm", col("cmpl_dlv_itm_string")),
    ("inco2_l", col("inco2_l_string")),
    ("inco3_l", col("inco3_l_string")),
    ("externalreferenceid", col("externalreferenceid_string")),
    ("tc_aut_det", col("tc_aut_det_string")),
    ("manual_tc_reason", col("manual_tc_reason_string")),
    ("fiscal_incentive", col("fiscal_incentive_string")),
    ("tax_subject_st", col("tax_subject_st_string")),
    ("fiscal_incentive_id", col("fiscal_incentive_id_string")),
    ("sf_txjcd", col("sf_txjcd_string")),
    ("_bev1_negen_item", col("_bev1_negen_item_string")),
    ("_bev1_nedepfree", col("_bev1_nedepfree_string")),
    ("_bev1_nestruccat", col("_bev1_nestruccat_string")),
    ("advcode", col("advcode_string")),
    ("budget_pd", col("budget_pd_string")),
    ("excpe", col("excpe_string")),
    ("fmfgus_key", col("fmfgus_key_string")),
    ("iuid_relevant", col("iuid_relevant_string")),
    ("mrpind", col("mrpind_string")),
    ("sgt_scat", col("sgt_scat_string")),
    ("sgt_rcat", col("sgt_rcat_string")),
    ("wrf_charstc1", col("wrf_charstc1_string")),
    ("wrf_charstc2", col("wrf_charstc2_string")),
    ("wrf_charstc3", col("wrf_charstc3_string")),
    ("refsite", col("refsite_string")),
    ("_sapmp_gpose", col("_sapmp_gpose_string")),
    ("angpn", col("angpn_string")),
    ("admoi", col("admoi_string")),
    ("adpri", col("adpri_string")),
    ("lprio", col("lprio_string")),
    ("adacn", col("adacn_string")),
    ("afpnr", col("afpnr_string")),
    ("bsark", col("bsark_string")),
    ("audat", col("audat_string")),
    ("angnr", col("angnr_string")),
    ("pnstat", col("pnstat_string")),
    ("addns", col("addns_string")),
    ("serru", col("serru_string")),
    ("sernp", col("sernp_string")),
    ("disub_sobkz", col("disub_sobkz_string")),
    ("disub_pspnr", col("disub_pspnr_string")),
    ("disub_kunnr", col("disub_kunnr_string")),
    ("disub_vbeln", col("disub_vbeln_string")),
    ("disub_posnr", col("disub_posnr_string")),
    ("disub_owner", col("disub_owner_string")),
    ("fsh_season_year", col("fsh_season_year_string")),
    ("fsh_season", col("fsh_season_string")),
    ("fsh_collection", col("fsh_collection_string")),
    ("fsh_theme", col("fsh_theme_string")),
    ("fsh_atp_date", col("fsh_atp_date_string")),
    ("fsh_vas_rel", col("fsh_vas_rel_string")),
    ("fsh_vas_prnt_id", col("fsh_vas_prnt_id_string")),
    ("fsh_transaction", col("fsh_transaction_string")),
    ("fsh_item_group", col("fsh_item_group_string")),
    ("fsh_item", col("fsh_item_string")),
    ("fsh_ss", col("fsh_ss_string")),
    ("fsh_grid_cond_rec", col("fsh_grid_cond_rec_string")),
    ("fsh_psm_pfm_split", col("fsh_psm_pfm_split_string")),
    ("cnfm_qty", col("cnfm_qty_decimal_13_3")),
    ("fsh_pqr_uepos", col("fsh_pqr_uepos_string")),
    ("stpac", col("stpac_string")),
    ("lgbzo", col("lgbzo_string")),
    ("lgbzo_b", col("lgbzo_b_string")),
    ("addrnum", col("addrnum_string")),
    ("consnum", col("consnum_string")),
    ("borgr_miss", col("borgr_miss_string")),
    ("ref_item", col("ref_item_string")),
    ("source_id", col("source_id_string")),
    ("source_key", col("source_key_string")),
    ("put_back", col("put_back_string")),
    ("pol_id", col("pol_id_string")),
    ("cons_order", col("cons_order_string"))
  )
}
