package ct.dna.lakehouse.sr_raw.ct_gbl_p77
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class mbew_E(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  @Decimal(11, 2) vjstp_decimal_11_2: BigDecimal,
  vbwst_string: String,
  vprsv_string: String,
  @Decimal(11, 2) bwprh_decimal_11_2: BigDecimal,
  @Decimal(13, 2) salk3_decimal_13_2: BigDecimal,
  ownpr_string: String,
  @Decimal(11, 2) bwprs_decimal_11_2: BigDecimal,
  @Decimal(13, 2) vksal_decimal_13_2: BigDecimal,
  kalsc_string: String,
  matnr_string: String,
  @Decimal(11, 2) vmstp_decimal_11_2: BigDecimal,
  pdatv_string: String,
  lfmon_string: String,
  kalkv_string: String,
  pperz_string: String,
  abwkz_string: String,
  pdatl_string: String,
  kalkl_string: String,
  bwtty_string: String,
  @Decimal(15, 0) timestamp_decimal_15_0: BigDecimal,
  @Decimal(11, 2) verpr_decimal_11_2: BigDecimal,
  vers1_string: String,
  mtorg_string: String,
  @Decimal(13, 3) vmkum_decimal_13_3: BigDecimal,
  sperw_string: String,
  @Decimal(11, 2) stprs_decimal_11_2: BigDecimal,
  pstat_string: String,
  @Decimal(11, 2) fplpx_decimal_11_2: BigDecimal,
  @Decimal(5, 0) peinh_decimal_5_0: BigDecimal,
  kziwl_string: String,
  @Decimal(11, 2) zplp2_decimal_11_2: BigDecimal,
  @Decimal(11, 2) vjver_decimal_11_2: BigDecimal,
  @Decimal(11, 2) zplp1_decimal_11_2: BigDecimal,
  mtuse_string: String,
  @Decimal(11, 2) vjbwh_decimal_11_2: BigDecimal,
  @Decimal(11, 2) vplpx_decimal_11_2: BigDecimal,
  @Decimal(11, 2) bwps1_decimal_11_2: BigDecimal,
  @Decimal(5, 0) vmpei_decimal_5_0: BigDecimal,
  bklas_string: String,
  hkmat_string: String,
  vmbkl_string: String,
  bwva3_string: String,
  bwkey_string: String,
  lbwst_string: String,
  kalkz_string: String,
  mlast_string: String,
  laepr_string: String,
  pdatz_string: String,
  pprdv_string: String,
  @Decimal(13, 2) vvsal_decimal_13_2: BigDecimal,
  ekalr_string: String,
  @Decimal(13, 3) vvjlb_decimal_13_3: BigDecimal,
  abciw_string: String,
  mandt_string: String,
  @Decimal(11, 2) zplp3_decimal_11_2: BigDecimal,
  @Decimal(11, 2) lplpx_decimal_11_2: BigDecimal,
  hrkft_string: String,
  wlinl_string: String,
  @Decimal(11, 2) lplpr_decimal_11_2: BigDecimal,
  @Decimal(5, 0) bwpei_decimal_5_0: BigDecimal,
  kalnr_string: String,
  @Decimal(13, 3) vvmlb_decimal_13_3: BigDecimal,
  mlmaa_string: String,
  qklas_string: String,
  vjbkl_string: String,
  @Decimal(11, 2) vjbws_decimal_11_2: BigDecimal,
  zpld2_string: String,
  pperl_string: String,
  @Decimal(11, 2) stprv_decimal_11_2: BigDecimal,
  @Decimal(13, 2) salkv_decimal_13_2: BigDecimal,
  @Decimal(6, 2) bwspa_decimal_6_2: BigDecimal,
  @Decimal(13, 3) vjkum_decimal_13_3: BigDecimal,
  @Decimal(11, 2) vmver_decimal_11_2: BigDecimal,
  eklas_string: String,
  zpld1_string: String,
  vmvpr_string: String,
  @Decimal(13, 2) vvjsl_decimal_13_2: BigDecimal,
  mbrue_string: String,
  lfgja_string: String,
  xlifo_string: String,
  pperv_string: String,
  kaln1_string: String,
  @Decimal(13, 3) lbkum_decimal_13_3: BigDecimal,
  zkdat_string: String,
  mypol_string: String,
  @Decimal(5, 0) vjpei_decimal_5_0: BigDecimal,
  @Decimal(11, 2) zkprs_decimal_11_2: BigDecimal,
  pprdz_string: String,
  xbewm_string: String,
  kosgr_string: String,
  @Decimal(11, 2) bwph1_decimal_11_2: BigDecimal,
  @Decimal(13, 2) vjsal_decimal_13_2: BigDecimal,
  oklas_string: String,
  @Decimal(11, 2) zplpr_decimal_11_2: BigDecimal,
  @Decimal(13, 2) vjsav_decimal_13_2: BigDecimal,
  fbwst_string: String,
  pprdl_string: String,
  bwva1_string: String,
  bwva2_string: String,
  vers2_string: String,
  @Decimal(11, 2) vplpr_decimal_11_2: BigDecimal,
  bwtar_string: String,
  lvorm_string: String,
  zpld3_string: String,
  vers3_string: String,
  @Decimal(13, 2) vmsal_decimal_13_2: BigDecimal,
  vjvpr_string: String,
  @Decimal(13, 2) vmsav_decimal_13_2: BigDecimal,
  oippinv_string: String
) extends Entity

object mbew extends TableSpec[mbew_E](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
