// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_ghp

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_bseg_part1(
    @PK theo_surr_key: BoxedLong,
    mandt: String,
    bukrs: String,
    belnr: String,
    gjahr: String,
    buzei: String,
    buzid: String,
    augdt: String,
    augcp: String,
    augbl: String,
    bschl: String,
    koart: String,
    umskz: String,
    umsks: String,
    zumsk: String,
    shkzg: String,
    gsber: String,
    pargb: String,
    tax_country: String,
    mwskz: String,
    txdat_from: String,
    qsskz: String,
    @Decimal(23, 2) dmbtr: BigDecimal,
    @Decimal(23, 2) wrbtr: BigDecimal,
    @Decimal(23, 2) fcsl: BigDecimal,
    rfccur: String,
    @Decimal(23, 2) kzbtr: BigDecimal,
    @Decimal(23, 2) pswbt: BigDecimal,
    pswsl: String,
    @Decimal(23, 2) txbhw: BigDecimal,
    @Decimal(23, 2) txbfw: BigDecimal,
    @Decimal(23, 2) mwsts: BigDecimal,
    @Decimal(23, 2) wmwst: BigDecimal,
    @Decimal(23, 2) lwsts: BigDecimal,
    @Decimal(23, 2) lwbtr: BigDecimal,
    @Decimal(23, 2) hwbas: BigDecimal,
    @Decimal(23, 2) fwbas: BigDecimal,
    @Decimal(23, 2) hwzuz: BigDecimal,
    @Decimal(23, 2) fwzuz: BigDecimal,
    shzuz: String,
    stekz: String,
    mwart: String,
    txgrp: String,
    ktosl: String,
    @Decimal(23, 2) qsshb: BigDecimal,
    @Decimal(9, 5) kursr: BigDecimal,
    @Decimal(23, 2) gbetr: BigDecimal,
    @Decimal(23, 2) bdiff: BigDecimal,
    @Decimal(23, 2) bdif2: BigDecimal,
    valut: String,
    zuonr: String,
    sgtxt: String,
    zinkz: String,
    vbund: String,
    bewar: String,
    altkt: String,
    vorgn: String,
    fdlev: String,
    fdgrp: String,
    @Decimal(23, 2) fdwbt: BigDecimal,
    fdtag: String,
    fkont: String,
    kokrs: String,
    kostl: String,
    projn: String,
    aufnr: String,
    vbeln: String,
    vbel2: String,
    posn2: String,
    eten2: String,
    service_doc_type: String,
    service_doc_id: String,
    service_doc_item_id: String,
    anln1: String,
    anln2: String,
    anbwa: String,
    bzdat: String,
    pernr: String,
    xumsw: String,
    xhres: String,
    xkres: String,
    xopvw: String,
    xcpdd: String,
    xskst: String,
    xsauf: String,
    xspro: String,
    xserg: String,
    xfakt: String,
    xuman: String,
    xanet: String,
    xskrl: String,
    xinve: String,
    xpanz: String,
    xauto: String,
    xncop: String,
    xzahl: String,
    saknr: String,
    hkont: String,
    kunnr: String,
    lifnr: String,
    filkd: String,
    xbilk: String,
    gvtyp: String,
    hzuon: String,
    zfbdt: String,
    zterm: String,
    @Decimal(3, 0) zbd1t: BigDecimal,
    @Decimal(3, 0) zbd2t: BigDecimal,
    @Decimal(3, 0) zbd3t: BigDecimal,
    @Decimal(5, 3) zbd1p: BigDecimal,
    @Decimal(5, 3) zbd2p: BigDecimal,
    @Decimal(23, 2) skfbt: BigDecimal,
    @Decimal(23, 2) sknto: BigDecimal,
    @Decimal(23, 2) wskto: BigDecimal,
    zlsch: String,
    zlspr: String,
    zbfix: String,
    hbkid: String,
    bvtyp: String,
    @Decimal(23, 2) nebtr: BigDecimal,
    mwsk1: String,
    txdat_from1: String,
    tax_country1: String,
    @Decimal(23, 2) dmbt1: BigDecimal,
    @Decimal(23, 2) wrbt1: BigDecimal,
    mwsk2: String,
    txdat_from2: String,
    tax_country2: String,
    @Decimal(23, 2) dmbt2: BigDecimal,
    @Decimal(23, 2) wrbt2: BigDecimal,
    mwsk3: String,
    txdat_from3: String,
    tax_country3: String,
    @Decimal(23, 2) dmbt3: BigDecimal,
    @Decimal(23, 2) wrbt3: BigDecimal,
    rebzg: String,
    rebzj: String,
    rebzz: String,
    rebzt: String,
    zollt: String,
    zolld: String,
    lzbkz: String,
    landl: String,
    diekz: String,
    samnr: String,
    abper: String,
    vrskz: String,
    vrsdt: String,
    disbn: String,
    disbj: String,
    disbz: String,
    wverw: String,
    anfbn: String,
    anfbj: String,
    anfbu: String,
    anfae: String,
    @Decimal(23, 2) blnbt: BigDecimal,
    blnkz: String,
    @Decimal(7, 2) blnpz: BigDecimal,
    mschl: String,
    mansp: String,
    madat: String,
    manst: String,
    maber: String,
    esrnr: String,
    esrre: String,
    esrpz: String,
    @Decimal(23, 2) klibt: BigDecimal,
    qsznr: String,
    @Decimal(23, 2) qbshb: BigDecimal,
    @Decimal(23, 2) qsfbt: BigDecimal,
    @Decimal(23, 2) navhw: BigDecimal,
    @Decimal(23, 2) navfw: BigDecimal,
    matnr: String,
    werks: String,
    @Decimal(13, 3) menge: BigDecimal,
    meins: String,
    @Decimal(13, 3) erfmg: BigDecimal,
    erfme: String,
    @Decimal(13, 3) bpmng: BigDecimal,
    bprme: String,
    ebeln_logsys: String,
    ebeln: String,
    ebelp: String,
    zekkn: String,
    elikz: String,
    vprsv: String,
    @Decimal(5, 0) peinh: BigDecimal,
    bwkey: String,
    bwtar: String,
    bustw: String,
    @Decimal(13, 2) rewrt: BigDecimal,
    @Decimal(23, 2) rewwr: BigDecimal,
    @Decimal(23, 2) bonfb: BigDecimal,
    @Decimal(13, 2) bualt: BigDecimal,
    psalt: String,
    @Decimal(11, 2) nprei: BigDecimal,
    tbtkz: String,
    spgrp: String,
    spgrm: String,
    spgrt: String,
    spgrg: String,
    spgrv: String,
    spgrq: String,
    stceg: String,
    egbld: String,
    eglld: String,
    rstgr: String,
    ryacq: String,
    rpacq: String,
    @Decimal(23, 2) rdiff: BigDecimal,
    @Decimal(23, 2) rdif2: BigDecimal,
    prctr: String,
    xhkom: String,
    fs_product_group: String,
    branch_id: String,
    datasource_id: String,
    vname: String,
    recid: String,
    egrup: String,
    vptnr: String,
    vertt: String,
    vertn: String,
    vbewa: String,
    depot: String,
    txjcd: String,
    imkey: String,
    dabrz: String,
    @Decimal(9, 6) popts: BigDecimal,
    fipos: String,
    kstrg: String,
    nplnr: String,
    aufpl: String,
    aplzl: String,
    projk: String,
    paobjnr: String,
    pasubnr: String,
    spgrs: String,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    hist_tax_factor1_binary: Array[Byte],
    hist_tax_factor2_binary: Array[Byte],
    hist_tax_factor3_binary: Array[Byte],
    hist_tax_factor_binary: Array[Byte]
) extends Entity

case class E_bseg_part2(
    @PK theo_surr_key: BoxedLong,
    spgrc_string: String,
    btype_string: String,
    etype_string: String,
    xegdr_string: String,
    lnran_string: String,
    hrkft_string: String,
    @Decimal(23, 2) dmbe2_decimal_23_2: BigDecimal,
    @Decimal(23, 2) dmbe3_decimal_23_2: BigDecimal,
    @Decimal(23, 2) dmb21_decimal_23_2: BigDecimal,
    @Decimal(23, 2) dmb22_decimal_23_2: BigDecimal,
    @Decimal(23, 2) dmb23_decimal_23_2: BigDecimal,
    @Decimal(23, 2) dmb31_decimal_23_2: BigDecimal,
    @Decimal(23, 2) dmb32_decimal_23_2: BigDecimal,
    @Decimal(23, 2) dmb33_decimal_23_2: BigDecimal,
    @Decimal(23, 2) mwst2_decimal_23_2: BigDecimal,
    @Decimal(23, 2) mwst3_decimal_23_2: BigDecimal,
    @Decimal(23, 2) navh2_decimal_23_2: BigDecimal,
    @Decimal(23, 2) navh3_decimal_23_2: BigDecimal,
    @Decimal(23, 2) sknt2_decimal_23_2: BigDecimal,
    @Decimal(23, 2) sknt3_decimal_23_2: BigDecimal,
    @Decimal(23, 2) bdif3_decimal_23_2: BigDecimal,
    @Decimal(23, 2) rdif3_decimal_23_2: BigDecimal,
    hwmet_string: String,
    glupm_string: String,
    xragl_string: String,
    uzawe_string: String,
    lokkt_string: String,
    fistl_string: String,
    geber_string: String,
    stbuk_string: String,
    @Decimal(23, 2) txbh2_decimal_23_2: BigDecimal,
    @Decimal(23, 2) txbh3_decimal_23_2: BigDecimal,
    pprct_string: String,
    xref1_string: String,
    xref2_string: String,
    kblnr_string: String,
    kblpos_string: String,
    @Decimal(13, 2) sttax_decimal_13_2: BigDecimal,
    fkber_string: String,
    obzei_string: String,
    xnegp_string: String,
    rfzei_string: String,
    ccbtc_string: String,
    kkber_string: String,
    empfb_string: String,
    xref3_string: String,
    dtws1_string: String,
    dtws2_string: String,
    dtws3_string: String,
    dtws4_string: String,
    gricd_string: String,
    grirg_string: String,
    gityp_string: String,
    xpypr_string: String,
    kidno_string: String,
    @Decimal(23, 2) absbt_decimal_23_2: BigDecimal,
    idxsp_string: String,
    linfv_string: String,
    kontt_string: String,
    kontl_string: String,
    uebgdat_string: String,
    txdat_string: String,
    @Decimal(5, 0) agzei_decimal_5_0: BigDecimal,
    pycur_string: String,
    @Decimal(23, 2) pyamt_decimal_23_2: BigDecimal,
    bupla_string: String,
    secco_string: String,
    lstar_string: String,
    cession_kz_string: String,
    prznr_string: String,
    @Decimal(23, 2) ppdiff_decimal_23_2: BigDecimal,
    @Decimal(23, 2) ppdif2_decimal_23_2: BigDecimal,
    @Decimal(23, 2) ppdif3_decimal_23_2: BigDecimal,
    @Decimal(23, 2) penlc1_decimal_23_2: BigDecimal,
    @Decimal(23, 2) penlc2_decimal_23_2: BigDecimal,
    @Decimal(23, 2) penlc3_decimal_23_2: BigDecimal,
    @Decimal(23, 2) penfc_decimal_23_2: BigDecimal,
    pendays_int: BoxedInt,
    penrc_string: String,
    grant_nbr_string: String,
    @Decimal(13, 2) sctax_decimal_13_2: BigDecimal,
    fkber_long_string: String,
    gmvkz_string: String,
    srtype_string: String,
    intreno_string: String,
    measure_string: String,
    auggj_string: String,
    ppa_ex_ind_string: String,
    docln_string: String,
    segment_string: String,
    psegment_string: String,
    pfkber_string: String,
    hktid_string: String,
    kstar_string: String,
    xlgclr_string: String,
    taxps_string: String,
    pays_prov_string: String,
    pays_tran_string: String,
    mndid_string: String,
    xfrge_bseg_string: String,
    awtyp_string: String,
    awkey_string: String,
    awsys_string: String,
    posnr_string: String,
    buzei_sender_string: String,
    h_monat_string: String,
    h_bstat_string: String,
    h_budat_string: String,
    h_bldat_string: String,
    h_waers_string: String,
    h_blart_string: String,
    h_hwaer_string: String,
    h_hwae2_string: String,
    h_hwae3_string: String,
    sk1dt_string: String,
    sk2dt_string: String,
    prctr_drvtn_source_type_string: String,
    payt_rsn_string: String,
    _dataaging_string: String,
    fqftype_string: String,
    lqitem_string: String,
    gkont_string: String,
    gkart_string: String,
    ghkon_string: String,
    squan_string: String,
    anln2_pn_string: String,
    bwasl_pn_string: String,
    bzdat_pn_string: String,
    xvabg_pn_string: String,
    @Decimal(23, 2) anbtr_pn_decimal_23_2: BigDecimal,
    @Decimal(5, 2) prozs_pn_decimal_5_2: BigDecimal,
    acdoc_eew_dummy_string: String,
    dummy_incl_eew_cobl_string: String,
    kdgrp_string: String,
    land1_string: String,
    brsch_string: String,
    acrobjtype_string: String,
    acrlogsys_string: String,
    acrobj_id_string: String,
    acrsobj_id_string: String,
    acritmtype_string: String,
    acrrefobj_id_string: String,
    acrvaldat_string: String,
    valobjtype_string: String,
    valobj_id_string: String,
    valsobj_id_string: String,
    netdt_string: String,
    risk_class_string: String,
    sdm_version_string: String,
    glo_ref1_string: String,
    re_bukrs_string: String,
    re_account_string: String,
    dp_payment_type_string: String,
    dp_trans_id_string: String,
    dp_payment_request_string: String,
    pgeber_string: String,
    pgrant_nbr_string: String,
    budget_pd_string: String,
    pbudget_pd_string: String,
    j_1tpbupl_string: String,
    perop_beg_string: String,
    perop_end_string: String,
    fastpay_string: String,
    ignr_ivref_string: String,
    fmfgus_key_string: String,
    fmxdocnr_string: String,
    fmxyear_string: String,
    fmxdocln_string: String,
    fmxzekkn_string: String,
    prodper_string: String,
    gst_part_string: String,
    plc_sup_string: String,
    hsn_sac_string: String,
    irn_string: String,
    recrf_string: String,
    bdgt_account_string: String,
    bdgt_account_cocode_string: String,
    inward_no_string: String,
    inward_dt_string: String,
    ground_no_string: String,
    ground_dt_string: String,
    ground_typ_string: String,
    pymtkey_string: String
) extends Entity

object bseg
    extends TableSpec[Joined[E_bseg_part1, E_bseg_part2]](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[Joined[sr_raw.ct_gbl_ghp.E_bseg_part1, sr_raw.ct_gbl_ghp.E_bseg_part2]] {
  override def sourceTableSpec: TableSpec[Joined[sr_raw.ct_gbl_ghp.E_bseg_part1, sr_raw.ct_gbl_ghp.E_bseg_part2]] = sr_raw.ct_gbl_ghp.bseg
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("theo_surr_key", col("theo_surr_key_long")),
    ("mandt", col("mandt_string")),
    ("bukrs", col("bukrs_string")),
    ("belnr", col("belnr_string")),
    ("gjahr", col("gjahr_string")),
    ("buzei", col("buzei_string")),
    ("buzid", col("buzid_string")),
    ("augdt", col("augdt_string")),
    ("augcp", col("augcp_string")),
    ("augbl", col("augbl_string")),
    ("bschl", col("bschl_string")),
    ("koart", col("koart_string")),
    ("umskz", col("umskz_string")),
    ("umsks", col("umsks_string")),
    ("zumsk", col("zumsk_string")),
    ("shkzg", col("shkzg_string")),
    ("gsber", col("gsber_string")),
    ("pargb", col("pargb_string")),
    ("tax_country", col("tax_country_string")),
    ("mwskz", col("mwskz_string")),
    ("txdat_from", col("txdat_from_string")),
    ("qsskz", col("qsskz_string")),
    ("dmbtr", col("dmbtr_decimal_23_2")),
    ("wrbtr", col("wrbtr_decimal_23_2")),
    ("fcsl", col("fcsl_decimal_23_2")),
    ("rfccur", col("rfccur_string")),
    ("kzbtr", col("kzbtr_decimal_23_2")),
    ("pswbt", col("pswbt_decimal_23_2")),
    ("pswsl", col("pswsl_string")),
    ("txbhw", col("txbhw_decimal_23_2")),
    ("txbfw", col("txbfw_decimal_23_2")),
    ("mwsts", col("mwsts_decimal_23_2")),
    ("wmwst", col("wmwst_decimal_23_2")),
    ("lwsts", col("lwsts_decimal_23_2")),
    ("lwbtr", col("lwbtr_decimal_23_2")),
    ("hwbas", col("hwbas_decimal_23_2")),
    ("fwbas", col("fwbas_decimal_23_2")),
    ("hwzuz", col("hwzuz_decimal_23_2")),
    ("fwzuz", col("fwzuz_decimal_23_2")),
    ("shzuz", col("shzuz_string")),
    ("stekz", col("stekz_string")),
    ("mwart", col("mwart_string")),
    ("txgrp", col("txgrp_string")),
    ("ktosl", col("ktosl_string")),
    ("qsshb", col("qsshb_decimal_23_2")),
    ("kursr", col("kursr_decimal_9_5")),
    ("gbetr", col("gbetr_decimal_23_2")),
    ("bdiff", col("bdiff_decimal_23_2")),
    ("bdif2", col("bdif2_decimal_23_2")),
    ("valut", col("valut_string")),
    ("zuonr", col("zuonr_string")),
    ("sgtxt", col("sgtxt_string")),
    ("zinkz", col("zinkz_string")),
    ("vbund", col("vbund_string")),
    ("bewar", col("bewar_string")),
    ("altkt", col("altkt_string")),
    ("vorgn", col("vorgn_string")),
    ("fdlev", col("fdlev_string")),
    ("fdgrp", col("fdgrp_string")),
    ("fdwbt", col("fdwbt_decimal_23_2")),
    ("fdtag", col("fdtag_string")),
    ("fkont", col("fkont_string")),
    ("kokrs", col("kokrs_string")),
    ("kostl", col("kostl_string")),
    ("projn", col("projn_string")),
    ("aufnr", col("aufnr_string")),
    ("vbeln", col("vbeln_string")),
    ("vbel2", col("vbel2_string")),
    ("posn2", col("posn2_string")),
    ("eten2", col("eten2_string")),
    ("service_doc_type", col("service_doc_type_string")),
    ("service_doc_id", col("service_doc_id_string")),
    ("service_doc_item_id", col("service_doc_item_id_string")),
    ("anln1", col("anln1_string")),
    ("anln2", col("anln2_string")),
    ("anbwa", col("anbwa_string")),
    ("bzdat", col("bzdat_string")),
    ("pernr", col("pernr_string")),
    ("xumsw", col("xumsw_string")),
    ("xhres", col("xhres_string")),
    ("xkres", col("xkres_string")),
    ("xopvw", col("xopvw_string")),
    ("xcpdd", col("xcpdd_string")),
    ("xskst", col("xskst_string")),
    ("xsauf", col("xsauf_string")),
    ("xspro", col("xspro_string")),
    ("xserg", col("xserg_string")),
    ("xfakt", col("xfakt_string")),
    ("xuman", col("xuman_string")),
    ("xanet", col("xanet_string")),
    ("xskrl", col("xskrl_string")),
    ("xinve", col("xinve_string")),
    ("xpanz", col("xpanz_string")),
    ("xauto", col("xauto_string")),
    ("xncop", col("xncop_string")),
    ("xzahl", col("xzahl_string")),
    ("saknr", col("saknr_string")),
    ("hkont", col("hkont_string")),
    ("kunnr", col("kunnr_string")),
    ("lifnr", col("lifnr_string")),
    ("filkd", col("filkd_string")),
    ("xbilk", col("xbilk_string")),
    ("gvtyp", col("gvtyp_string")),
    ("hzuon", col("hzuon_string")),
    ("zfbdt", col("zfbdt_string")),
    ("zterm", col("zterm_string")),
    ("zbd1t", col("zbd1t_decimal_3_0")),
    ("zbd2t", col("zbd2t_decimal_3_0")),
    ("zbd3t", col("zbd3t_decimal_3_0")),
    ("zbd1p", col("zbd1p_decimal_5_3")),
    ("zbd2p", col("zbd2p_decimal_5_3")),
    ("skfbt", col("skfbt_decimal_23_2")),
    ("sknto", col("sknto_decimal_23_2")),
    ("wskto", col("wskto_decimal_23_2")),
    ("zlsch", col("zlsch_string")),
    ("zlspr", col("zlspr_string")),
    ("zbfix", col("zbfix_string")),
    ("hbkid", col("hbkid_string")),
    ("bvtyp", col("bvtyp_string")),
    ("nebtr", col("nebtr_decimal_23_2")),
    ("mwsk1", col("mwsk1_string")),
    ("txdat_from1", col("txdat_from1_string")),
    ("tax_country1", col("tax_country1_string")),
    ("dmbt1", col("dmbt1_decimal_23_2")),
    ("wrbt1", col("wrbt1_decimal_23_2")),
    ("mwsk2", col("mwsk2_string")),
    ("txdat_from2", col("txdat_from2_string")),
    ("tax_country2", col("tax_country2_string")),
    ("dmbt2", col("dmbt2_decimal_23_2")),
    ("wrbt2", col("wrbt2_decimal_23_2")),
    ("mwsk3", col("mwsk3_string")),
    ("txdat_from3", col("txdat_from3_string")),
    ("tax_country3", col("tax_country3_string")),
    ("dmbt3", col("dmbt3_decimal_23_2")),
    ("wrbt3", col("wrbt3_decimal_23_2")),
    ("rebzg", col("rebzg_string")),
    ("rebzj", col("rebzj_string")),
    ("rebzz", col("rebzz_string")),
    ("rebzt", col("rebzt_string")),
    ("zollt", col("zollt_string")),
    ("zolld", col("zolld_string")),
    ("lzbkz", col("lzbkz_string")),
    ("landl", col("landl_string")),
    ("diekz", col("diekz_string")),
    ("samnr", col("samnr_string")),
    ("abper", col("abper_string")),
    ("vrskz", col("vrskz_string")),
    ("vrsdt", col("vrsdt_string")),
    ("disbn", col("disbn_string")),
    ("disbj", col("disbj_string")),
    ("disbz", col("disbz_string")),
    ("wverw", col("wverw_string")),
    ("anfbn", col("anfbn_string")),
    ("anfbj", col("anfbj_string")),
    ("anfbu", col("anfbu_string")),
    ("anfae", col("anfae_string")),
    ("blnbt", col("blnbt_decimal_23_2")),
    ("blnkz", col("blnkz_string")),
    ("blnpz", col("blnpz_decimal_7_2")),
    ("mschl", col("mschl_string")),
    ("mansp", col("mansp_string")),
    ("madat", col("madat_string")),
    ("manst", col("manst_string")),
    ("maber", col("maber_string")),
    ("esrnr", col("esrnr_string")),
    ("esrre", col("esrre_string")),
    ("esrpz", col("esrpz_string")),
    ("klibt", col("klibt_decimal_23_2")),
    ("qsznr", col("qsznr_string")),
    ("qbshb", col("qbshb_decimal_23_2")),
    ("qsfbt", col("qsfbt_decimal_23_2")),
    ("navhw", col("navhw_decimal_23_2")),
    ("navfw", col("navfw_decimal_23_2")),
    ("matnr", col("matnr_string")),
    ("werks", col("werks_string")),
    ("menge", col("menge_decimal_13_3")),
    ("meins", col("meins_string")),
    ("erfmg", col("erfmg_decimal_13_3")),
    ("erfme", col("erfme_string")),
    ("bpmng", col("bpmng_decimal_13_3")),
    ("bprme", col("bprme_string")),
    ("ebeln_logsys", col("ebeln_logsys_string")),
    ("ebeln", col("ebeln_string")),
    ("ebelp", col("ebelp_string")),
    ("zekkn", col("zekkn_string")),
    ("elikz", col("elikz_string")),
    ("vprsv", col("vprsv_string")),
    ("peinh", col("peinh_decimal_5_0")),
    ("bwkey", col("bwkey_string")),
    ("bwtar", col("bwtar_string")),
    ("bustw", col("bustw_string")),
    ("rewrt", col("rewrt_decimal_13_2")),
    ("rewwr", col("rewwr_decimal_23_2")),
    ("bonfb", col("bonfb_decimal_23_2")),
    ("bualt", col("bualt_decimal_13_2")),
    ("psalt", col("psalt_string")),
    ("nprei", col("nprei_decimal_11_2")),
    ("tbtkz", col("tbtkz_string")),
    ("spgrp", col("spgrp_string")),
    ("spgrm", col("spgrm_string")),
    ("spgrt", col("spgrt_string")),
    ("spgrg", col("spgrg_string")),
    ("spgrv", col("spgrv_string")),
    ("spgrq", col("spgrq_string")),
    ("stceg", col("stceg_string")),
    ("egbld", col("egbld_string")),
    ("eglld", col("eglld_string")),
    ("rstgr", col("rstgr_string")),
    ("ryacq", col("ryacq_string")),
    ("rpacq", col("rpacq_string")),
    ("rdiff", col("rdiff_decimal_23_2")),
    ("rdif2", col("rdif2_decimal_23_2")),
    ("prctr", col("prctr_string")),
    ("xhkom", col("xhkom_string")),
    ("fs_product_group", col("fs_product_group_string")),
    ("branch_id", col("branch_id_string")),
    ("datasource_id", col("datasource_id_string")),
    ("vname", col("vname_string")),
    ("recid", col("recid_string")),
    ("egrup", col("egrup_string")),
    ("vptnr", col("vptnr_string")),
    ("vertt", col("vertt_string")),
    ("vertn", col("vertn_string")),
    ("vbewa", col("vbewa_string")),
    ("depot", col("depot_string")),
    ("txjcd", col("txjcd_string")),
    ("imkey", col("imkey_string")),
    ("dabrz", col("dabrz_string")),
    ("popts", col("popts_decimal_9_6")),
    ("fipos", col("fipos_string")),
    ("kstrg", col("kstrg_string")),
    ("nplnr", col("nplnr_string")),
    ("aufpl", col("aufpl_string")),
    ("aplzl", col("aplzl_string")),
    ("projk", col("projk_string")),
    ("paobjnr", col("paobjnr_string")),
    ("pasubnr", col("pasubnr_string")),
    ("spgrs", col("spgrs_string"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_bseg(prefix: String) extends ColumnWithNameAccessor {
  val theo_surr_key: ColumnWithName = ColumnWithName(prefix + "theo_surr_key")
  val mandt: ColumnWithName = ColumnWithName(prefix + "mandt")
  val bukrs: ColumnWithName = ColumnWithName(prefix + "bukrs")
  val belnr: ColumnWithName = ColumnWithName(prefix + "belnr")
  val gjahr: ColumnWithName = ColumnWithName(prefix + "gjahr")
  val buzei: ColumnWithName = ColumnWithName(prefix + "buzei")
  val buzid: ColumnWithName = ColumnWithName(prefix + "buzid")
  val augdt: ColumnWithName = ColumnWithName(prefix + "augdt")
  val augcp: ColumnWithName = ColumnWithName(prefix + "augcp")
  val augbl: ColumnWithName = ColumnWithName(prefix + "augbl")
  val bschl: ColumnWithName = ColumnWithName(prefix + "bschl")
  val koart: ColumnWithName = ColumnWithName(prefix + "koart")
  val umskz: ColumnWithName = ColumnWithName(prefix + "umskz")
  val umsks: ColumnWithName = ColumnWithName(prefix + "umsks")
  val zumsk: ColumnWithName = ColumnWithName(prefix + "zumsk")
  val shkzg: ColumnWithName = ColumnWithName(prefix + "shkzg")
  val gsber: ColumnWithName = ColumnWithName(prefix + "gsber")
  val pargb: ColumnWithName = ColumnWithName(prefix + "pargb")
  val tax_country: ColumnWithName = ColumnWithName(prefix + "tax_country")
  val mwskz: ColumnWithName = ColumnWithName(prefix + "mwskz")
  val txdat_from: ColumnWithName = ColumnWithName(prefix + "txdat_from")
  val qsskz: ColumnWithName = ColumnWithName(prefix + "qsskz")
  val dmbtr: ColumnWithName = ColumnWithName(prefix + "dmbtr")
  val wrbtr: ColumnWithName = ColumnWithName(prefix + "wrbtr")
  val fcsl: ColumnWithName = ColumnWithName(prefix + "fcsl")
  val rfccur: ColumnWithName = ColumnWithName(prefix + "rfccur")
  val kzbtr: ColumnWithName = ColumnWithName(prefix + "kzbtr")
  val pswbt: ColumnWithName = ColumnWithName(prefix + "pswbt")
  val pswsl: ColumnWithName = ColumnWithName(prefix + "pswsl")
  val txbhw: ColumnWithName = ColumnWithName(prefix + "txbhw")
  val txbfw: ColumnWithName = ColumnWithName(prefix + "txbfw")
  val mwsts: ColumnWithName = ColumnWithName(prefix + "mwsts")
  val wmwst: ColumnWithName = ColumnWithName(prefix + "wmwst")
  val lwsts: ColumnWithName = ColumnWithName(prefix + "lwsts")
  val lwbtr: ColumnWithName = ColumnWithName(prefix + "lwbtr")
  val hwbas: ColumnWithName = ColumnWithName(prefix + "hwbas")
  val fwbas: ColumnWithName = ColumnWithName(prefix + "fwbas")
  val hwzuz: ColumnWithName = ColumnWithName(prefix + "hwzuz")
  val fwzuz: ColumnWithName = ColumnWithName(prefix + "fwzuz")
  val shzuz: ColumnWithName = ColumnWithName(prefix + "shzuz")
  val stekz: ColumnWithName = ColumnWithName(prefix + "stekz")
  val mwart: ColumnWithName = ColumnWithName(prefix + "mwart")
  val txgrp: ColumnWithName = ColumnWithName(prefix + "txgrp")
  val ktosl: ColumnWithName = ColumnWithName(prefix + "ktosl")
  val qsshb: ColumnWithName = ColumnWithName(prefix + "qsshb")
  val kursr: ColumnWithName = ColumnWithName(prefix + "kursr")
  val gbetr: ColumnWithName = ColumnWithName(prefix + "gbetr")
  val bdiff: ColumnWithName = ColumnWithName(prefix + "bdiff")
  val bdif2: ColumnWithName = ColumnWithName(prefix + "bdif2")
  val valut: ColumnWithName = ColumnWithName(prefix + "valut")
  val zuonr: ColumnWithName = ColumnWithName(prefix + "zuonr")
  val sgtxt: ColumnWithName = ColumnWithName(prefix + "sgtxt")
  val zinkz: ColumnWithName = ColumnWithName(prefix + "zinkz")
  val vbund: ColumnWithName = ColumnWithName(prefix + "vbund")
  val bewar: ColumnWithName = ColumnWithName(prefix + "bewar")
  val altkt: ColumnWithName = ColumnWithName(prefix + "altkt")
  val vorgn: ColumnWithName = ColumnWithName(prefix + "vorgn")
  val fdlev: ColumnWithName = ColumnWithName(prefix + "fdlev")
  val fdgrp: ColumnWithName = ColumnWithName(prefix + "fdgrp")
  val fdwbt: ColumnWithName = ColumnWithName(prefix + "fdwbt")
  val fdtag: ColumnWithName = ColumnWithName(prefix + "fdtag")
  val fkont: ColumnWithName = ColumnWithName(prefix + "fkont")
  val kokrs: ColumnWithName = ColumnWithName(prefix + "kokrs")
  val kostl: ColumnWithName = ColumnWithName(prefix + "kostl")
  val projn: ColumnWithName = ColumnWithName(prefix + "projn")
  val aufnr: ColumnWithName = ColumnWithName(prefix + "aufnr")
  val vbeln: ColumnWithName = ColumnWithName(prefix + "vbeln")
  val vbel2: ColumnWithName = ColumnWithName(prefix + "vbel2")
  val posn2: ColumnWithName = ColumnWithName(prefix + "posn2")
  val eten2: ColumnWithName = ColumnWithName(prefix + "eten2")
  val service_doc_type: ColumnWithName = ColumnWithName(prefix + "service_doc_type")
  val service_doc_id: ColumnWithName = ColumnWithName(prefix + "service_doc_id")
  val service_doc_item_id: ColumnWithName = ColumnWithName(prefix + "service_doc_item_id")
  val anln1: ColumnWithName = ColumnWithName(prefix + "anln1")
  val anln2: ColumnWithName = ColumnWithName(prefix + "anln2")
  val anbwa: ColumnWithName = ColumnWithName(prefix + "anbwa")
  val bzdat: ColumnWithName = ColumnWithName(prefix + "bzdat")
  val pernr: ColumnWithName = ColumnWithName(prefix + "pernr")
  val xumsw: ColumnWithName = ColumnWithName(prefix + "xumsw")
  val xhres: ColumnWithName = ColumnWithName(prefix + "xhres")
  val xkres: ColumnWithName = ColumnWithName(prefix + "xkres")
  val xopvw: ColumnWithName = ColumnWithName(prefix + "xopvw")
  val xcpdd: ColumnWithName = ColumnWithName(prefix + "xcpdd")
  val xskst: ColumnWithName = ColumnWithName(prefix + "xskst")
  val xsauf: ColumnWithName = ColumnWithName(prefix + "xsauf")
  val xspro: ColumnWithName = ColumnWithName(prefix + "xspro")
  val xserg: ColumnWithName = ColumnWithName(prefix + "xserg")
  val xfakt: ColumnWithName = ColumnWithName(prefix + "xfakt")
  val xuman: ColumnWithName = ColumnWithName(prefix + "xuman")
  val xanet: ColumnWithName = ColumnWithName(prefix + "xanet")
  val xskrl: ColumnWithName = ColumnWithName(prefix + "xskrl")
  val xinve: ColumnWithName = ColumnWithName(prefix + "xinve")
  val xpanz: ColumnWithName = ColumnWithName(prefix + "xpanz")
  val xauto: ColumnWithName = ColumnWithName(prefix + "xauto")
  val xncop: ColumnWithName = ColumnWithName(prefix + "xncop")
  val xzahl: ColumnWithName = ColumnWithName(prefix + "xzahl")
  val saknr: ColumnWithName = ColumnWithName(prefix + "saknr")
  val hkont: ColumnWithName = ColumnWithName(prefix + "hkont")
  val kunnr: ColumnWithName = ColumnWithName(prefix + "kunnr")
  val lifnr: ColumnWithName = ColumnWithName(prefix + "lifnr")
  val filkd: ColumnWithName = ColumnWithName(prefix + "filkd")
  val xbilk: ColumnWithName = ColumnWithName(prefix + "xbilk")
  val gvtyp: ColumnWithName = ColumnWithName(prefix + "gvtyp")
  val hzuon: ColumnWithName = ColumnWithName(prefix + "hzuon")
  val zfbdt: ColumnWithName = ColumnWithName(prefix + "zfbdt")
  val zterm: ColumnWithName = ColumnWithName(prefix + "zterm")
  val zbd1t: ColumnWithName = ColumnWithName(prefix + "zbd1t")
  val zbd2t: ColumnWithName = ColumnWithName(prefix + "zbd2t")
  val zbd3t: ColumnWithName = ColumnWithName(prefix + "zbd3t")
  val zbd1p: ColumnWithName = ColumnWithName(prefix + "zbd1p")
  val zbd2p: ColumnWithName = ColumnWithName(prefix + "zbd2p")
  val skfbt: ColumnWithName = ColumnWithName(prefix + "skfbt")
  val sknto: ColumnWithName = ColumnWithName(prefix + "sknto")
  val wskto: ColumnWithName = ColumnWithName(prefix + "wskto")
  val zlsch: ColumnWithName = ColumnWithName(prefix + "zlsch")
  val zlspr: ColumnWithName = ColumnWithName(prefix + "zlspr")
  val zbfix: ColumnWithName = ColumnWithName(prefix + "zbfix")
  val hbkid: ColumnWithName = ColumnWithName(prefix + "hbkid")
  val bvtyp: ColumnWithName = ColumnWithName(prefix + "bvtyp")
  val nebtr: ColumnWithName = ColumnWithName(prefix + "nebtr")
  val mwsk1: ColumnWithName = ColumnWithName(prefix + "mwsk1")
  val txdat_from1: ColumnWithName = ColumnWithName(prefix + "txdat_from1")
  val tax_country1: ColumnWithName = ColumnWithName(prefix + "tax_country1")
  val dmbt1: ColumnWithName = ColumnWithName(prefix + "dmbt1")
  val wrbt1: ColumnWithName = ColumnWithName(prefix + "wrbt1")
  val mwsk2: ColumnWithName = ColumnWithName(prefix + "mwsk2")
  val txdat_from2: ColumnWithName = ColumnWithName(prefix + "txdat_from2")
  val tax_country2: ColumnWithName = ColumnWithName(prefix + "tax_country2")
  val dmbt2: ColumnWithName = ColumnWithName(prefix + "dmbt2")
  val wrbt2: ColumnWithName = ColumnWithName(prefix + "wrbt2")
  val mwsk3: ColumnWithName = ColumnWithName(prefix + "mwsk3")
  val txdat_from3: ColumnWithName = ColumnWithName(prefix + "txdat_from3")
  val tax_country3: ColumnWithName = ColumnWithName(prefix + "tax_country3")
  val dmbt3: ColumnWithName = ColumnWithName(prefix + "dmbt3")
  val wrbt3: ColumnWithName = ColumnWithName(prefix + "wrbt3")
  val rebzg: ColumnWithName = ColumnWithName(prefix + "rebzg")
  val rebzj: ColumnWithName = ColumnWithName(prefix + "rebzj")
  val rebzz: ColumnWithName = ColumnWithName(prefix + "rebzz")
  val rebzt: ColumnWithName = ColumnWithName(prefix + "rebzt")
  val zollt: ColumnWithName = ColumnWithName(prefix + "zollt")
  val zolld: ColumnWithName = ColumnWithName(prefix + "zolld")
  val lzbkz: ColumnWithName = ColumnWithName(prefix + "lzbkz")
  val landl: ColumnWithName = ColumnWithName(prefix + "landl")
  val diekz: ColumnWithName = ColumnWithName(prefix + "diekz")
  val samnr: ColumnWithName = ColumnWithName(prefix + "samnr")
  val abper: ColumnWithName = ColumnWithName(prefix + "abper")
  val vrskz: ColumnWithName = ColumnWithName(prefix + "vrskz")
  val vrsdt: ColumnWithName = ColumnWithName(prefix + "vrsdt")
  val disbn: ColumnWithName = ColumnWithName(prefix + "disbn")
  val disbj: ColumnWithName = ColumnWithName(prefix + "disbj")
  val disbz: ColumnWithName = ColumnWithName(prefix + "disbz")
  val wverw: ColumnWithName = ColumnWithName(prefix + "wverw")
  val anfbn: ColumnWithName = ColumnWithName(prefix + "anfbn")
  val anfbj: ColumnWithName = ColumnWithName(prefix + "anfbj")
  val anfbu: ColumnWithName = ColumnWithName(prefix + "anfbu")
  val anfae: ColumnWithName = ColumnWithName(prefix + "anfae")
  val blnbt: ColumnWithName = ColumnWithName(prefix + "blnbt")
  val blnkz: ColumnWithName = ColumnWithName(prefix + "blnkz")
  val blnpz: ColumnWithName = ColumnWithName(prefix + "blnpz")
  val mschl: ColumnWithName = ColumnWithName(prefix + "mschl")
  val mansp: ColumnWithName = ColumnWithName(prefix + "mansp")
  val madat: ColumnWithName = ColumnWithName(prefix + "madat")
  val manst: ColumnWithName = ColumnWithName(prefix + "manst")
  val maber: ColumnWithName = ColumnWithName(prefix + "maber")
  val esrnr: ColumnWithName = ColumnWithName(prefix + "esrnr")
  val esrre: ColumnWithName = ColumnWithName(prefix + "esrre")
  val esrpz: ColumnWithName = ColumnWithName(prefix + "esrpz")
  val klibt: ColumnWithName = ColumnWithName(prefix + "klibt")
  val qsznr: ColumnWithName = ColumnWithName(prefix + "qsznr")
  val qbshb: ColumnWithName = ColumnWithName(prefix + "qbshb")
  val qsfbt: ColumnWithName = ColumnWithName(prefix + "qsfbt")
  val navhw: ColumnWithName = ColumnWithName(prefix + "navhw")
  val navfw: ColumnWithName = ColumnWithName(prefix + "navfw")
  val matnr: ColumnWithName = ColumnWithName(prefix + "matnr")
  val werks: ColumnWithName = ColumnWithName(prefix + "werks")
  val menge: ColumnWithName = ColumnWithName(prefix + "menge")
  val meins: ColumnWithName = ColumnWithName(prefix + "meins")
  val erfmg: ColumnWithName = ColumnWithName(prefix + "erfmg")
  val erfme: ColumnWithName = ColumnWithName(prefix + "erfme")
  val bpmng: ColumnWithName = ColumnWithName(prefix + "bpmng")
  val bprme: ColumnWithName = ColumnWithName(prefix + "bprme")
  val ebeln_logsys: ColumnWithName = ColumnWithName(prefix + "ebeln_logsys")
  val ebeln: ColumnWithName = ColumnWithName(prefix + "ebeln")
  val ebelp: ColumnWithName = ColumnWithName(prefix + "ebelp")
  val zekkn: ColumnWithName = ColumnWithName(prefix + "zekkn")
  val elikz: ColumnWithName = ColumnWithName(prefix + "elikz")
  val vprsv: ColumnWithName = ColumnWithName(prefix + "vprsv")
  val peinh: ColumnWithName = ColumnWithName(prefix + "peinh")
  val bwkey: ColumnWithName = ColumnWithName(prefix + "bwkey")
  val bwtar: ColumnWithName = ColumnWithName(prefix + "bwtar")
  val bustw: ColumnWithName = ColumnWithName(prefix + "bustw")
  val rewrt: ColumnWithName = ColumnWithName(prefix + "rewrt")
  val rewwr: ColumnWithName = ColumnWithName(prefix + "rewwr")
  val bonfb: ColumnWithName = ColumnWithName(prefix + "bonfb")
  val bualt: ColumnWithName = ColumnWithName(prefix + "bualt")
  val psalt: ColumnWithName = ColumnWithName(prefix + "psalt")
  val nprei: ColumnWithName = ColumnWithName(prefix + "nprei")
  val tbtkz: ColumnWithName = ColumnWithName(prefix + "tbtkz")
  val spgrp: ColumnWithName = ColumnWithName(prefix + "spgrp")
  val spgrm: ColumnWithName = ColumnWithName(prefix + "spgrm")
  val spgrt: ColumnWithName = ColumnWithName(prefix + "spgrt")
  val spgrg: ColumnWithName = ColumnWithName(prefix + "spgrg")
  val spgrv: ColumnWithName = ColumnWithName(prefix + "spgrv")
  val spgrq: ColumnWithName = ColumnWithName(prefix + "spgrq")
  val stceg: ColumnWithName = ColumnWithName(prefix + "stceg")
  val egbld: ColumnWithName = ColumnWithName(prefix + "egbld")
  val eglld: ColumnWithName = ColumnWithName(prefix + "eglld")
  val rstgr: ColumnWithName = ColumnWithName(prefix + "rstgr")
  val ryacq: ColumnWithName = ColumnWithName(prefix + "ryacq")
  val rpacq: ColumnWithName = ColumnWithName(prefix + "rpacq")
  val rdiff: ColumnWithName = ColumnWithName(prefix + "rdiff")
  val rdif2: ColumnWithName = ColumnWithName(prefix + "rdif2")
  val prctr: ColumnWithName = ColumnWithName(prefix + "prctr")
  val xhkom: ColumnWithName = ColumnWithName(prefix + "xhkom")
  val fs_product_group: ColumnWithName = ColumnWithName(prefix + "fs_product_group")
  val branch_id: ColumnWithName = ColumnWithName(prefix + "branch_id")
  val datasource_id: ColumnWithName = ColumnWithName(prefix + "datasource_id")
  val vname: ColumnWithName = ColumnWithName(prefix + "vname")
  val recid: ColumnWithName = ColumnWithName(prefix + "recid")
  val egrup: ColumnWithName = ColumnWithName(prefix + "egrup")
  val vptnr: ColumnWithName = ColumnWithName(prefix + "vptnr")
  val vertt: ColumnWithName = ColumnWithName(prefix + "vertt")
  val vertn: ColumnWithName = ColumnWithName(prefix + "vertn")
  val vbewa: ColumnWithName = ColumnWithName(prefix + "vbewa")
  val depot: ColumnWithName = ColumnWithName(prefix + "depot")
  val txjcd: ColumnWithName = ColumnWithName(prefix + "txjcd")
  val imkey: ColumnWithName = ColumnWithName(prefix + "imkey")
  val dabrz: ColumnWithName = ColumnWithName(prefix + "dabrz")
  val popts: ColumnWithName = ColumnWithName(prefix + "popts")
  val fipos: ColumnWithName = ColumnWithName(prefix + "fipos")
  val kstrg: ColumnWithName = ColumnWithName(prefix + "kstrg")
  val nplnr: ColumnWithName = ColumnWithName(prefix + "nplnr")
  val aufpl: ColumnWithName = ColumnWithName(prefix + "aufpl")
  val aplzl: ColumnWithName = ColumnWithName(prefix + "aplzl")
  val projk: ColumnWithName = ColumnWithName(prefix + "projk")
  val paobjnr: ColumnWithName = ColumnWithName(prefix + "paobjnr")
  val pasubnr: ColumnWithName = ColumnWithName(prefix + "pasubnr")
  val spgrs: ColumnWithName = ColumnWithName(prefix + "spgrs")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val hist_tax_factor1_binary: ColumnWithName = ColumnWithName(prefix + "hist_tax_factor1_binary")
  val hist_tax_factor2_binary: ColumnWithName = ColumnWithName(prefix + "hist_tax_factor2_binary")
  val hist_tax_factor3_binary: ColumnWithName = ColumnWithName(prefix + "hist_tax_factor3_binary")
  val hist_tax_factor_binary: ColumnWithName = ColumnWithName(prefix + "hist_tax_factor_binary")
  val spgrc_string: ColumnWithName = ColumnWithName(prefix + "spgrc_string")
  val btype_string: ColumnWithName = ColumnWithName(prefix + "btype_string")
  val etype_string: ColumnWithName = ColumnWithName(prefix + "etype_string")
  val xegdr_string: ColumnWithName = ColumnWithName(prefix + "xegdr_string")
  val lnran_string: ColumnWithName = ColumnWithName(prefix + "lnran_string")
  val hrkft_string: ColumnWithName = ColumnWithName(prefix + "hrkft_string")
  val dmbe2_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "dmbe2_decimal_23_2")
  val dmbe3_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "dmbe3_decimal_23_2")
  val dmb21_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "dmb21_decimal_23_2")
  val dmb22_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "dmb22_decimal_23_2")
  val dmb23_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "dmb23_decimal_23_2")
  val dmb31_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "dmb31_decimal_23_2")
  val dmb32_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "dmb32_decimal_23_2")
  val dmb33_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "dmb33_decimal_23_2")
  val mwst2_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "mwst2_decimal_23_2")
  val mwst3_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "mwst3_decimal_23_2")
  val navh2_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "navh2_decimal_23_2")
  val navh3_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "navh3_decimal_23_2")
  val sknt2_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "sknt2_decimal_23_2")
  val sknt3_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "sknt3_decimal_23_2")
  val bdif3_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "bdif3_decimal_23_2")
  val rdif3_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "rdif3_decimal_23_2")
  val hwmet_string: ColumnWithName = ColumnWithName(prefix + "hwmet_string")
  val glupm_string: ColumnWithName = ColumnWithName(prefix + "glupm_string")
  val xragl_string: ColumnWithName = ColumnWithName(prefix + "xragl_string")
  val uzawe_string: ColumnWithName = ColumnWithName(prefix + "uzawe_string")
  val lokkt_string: ColumnWithName = ColumnWithName(prefix + "lokkt_string")
  val fistl_string: ColumnWithName = ColumnWithName(prefix + "fistl_string")
  val geber_string: ColumnWithName = ColumnWithName(prefix + "geber_string")
  val stbuk_string: ColumnWithName = ColumnWithName(prefix + "stbuk_string")
  val txbh2_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "txbh2_decimal_23_2")
  val txbh3_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "txbh3_decimal_23_2")
  val pprct_string: ColumnWithName = ColumnWithName(prefix + "pprct_string")
  val xref1_string: ColumnWithName = ColumnWithName(prefix + "xref1_string")
  val xref2_string: ColumnWithName = ColumnWithName(prefix + "xref2_string")
  val kblnr_string: ColumnWithName = ColumnWithName(prefix + "kblnr_string")
  val kblpos_string: ColumnWithName = ColumnWithName(prefix + "kblpos_string")
  val sttax_decimal_13_2: ColumnWithName = ColumnWithName(prefix + "sttax_decimal_13_2")
  val fkber_string: ColumnWithName = ColumnWithName(prefix + "fkber_string")
  val obzei_string: ColumnWithName = ColumnWithName(prefix + "obzei_string")
  val xnegp_string: ColumnWithName = ColumnWithName(prefix + "xnegp_string")
  val rfzei_string: ColumnWithName = ColumnWithName(prefix + "rfzei_string")
  val ccbtc_string: ColumnWithName = ColumnWithName(prefix + "ccbtc_string")
  val kkber_string: ColumnWithName = ColumnWithName(prefix + "kkber_string")
  val empfb_string: ColumnWithName = ColumnWithName(prefix + "empfb_string")
  val xref3_string: ColumnWithName = ColumnWithName(prefix + "xref3_string")
  val dtws1_string: ColumnWithName = ColumnWithName(prefix + "dtws1_string")
  val dtws2_string: ColumnWithName = ColumnWithName(prefix + "dtws2_string")
  val dtws3_string: ColumnWithName = ColumnWithName(prefix + "dtws3_string")
  val dtws4_string: ColumnWithName = ColumnWithName(prefix + "dtws4_string")
  val gricd_string: ColumnWithName = ColumnWithName(prefix + "gricd_string")
  val grirg_string: ColumnWithName = ColumnWithName(prefix + "grirg_string")
  val gityp_string: ColumnWithName = ColumnWithName(prefix + "gityp_string")
  val xpypr_string: ColumnWithName = ColumnWithName(prefix + "xpypr_string")
  val kidno_string: ColumnWithName = ColumnWithName(prefix + "kidno_string")
  val absbt_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "absbt_decimal_23_2")
  val idxsp_string: ColumnWithName = ColumnWithName(prefix + "idxsp_string")
  val linfv_string: ColumnWithName = ColumnWithName(prefix + "linfv_string")
  val kontt_string: ColumnWithName = ColumnWithName(prefix + "kontt_string")
  val kontl_string: ColumnWithName = ColumnWithName(prefix + "kontl_string")
  val uebgdat_string: ColumnWithName = ColumnWithName(prefix + "uebgdat_string")
  val txdat_string: ColumnWithName = ColumnWithName(prefix + "txdat_string")
  val agzei_decimal_5_0: ColumnWithName = ColumnWithName(prefix + "agzei_decimal_5_0")
  val pycur_string: ColumnWithName = ColumnWithName(prefix + "pycur_string")
  val pyamt_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "pyamt_decimal_23_2")
  val bupla_string: ColumnWithName = ColumnWithName(prefix + "bupla_string")
  val secco_string: ColumnWithName = ColumnWithName(prefix + "secco_string")
  val lstar_string: ColumnWithName = ColumnWithName(prefix + "lstar_string")
  val cession_kz_string: ColumnWithName = ColumnWithName(prefix + "cession_kz_string")
  val prznr_string: ColumnWithName = ColumnWithName(prefix + "prznr_string")
  val ppdiff_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "ppdiff_decimal_23_2")
  val ppdif2_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "ppdif2_decimal_23_2")
  val ppdif3_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "ppdif3_decimal_23_2")
  val penlc1_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "penlc1_decimal_23_2")
  val penlc2_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "penlc2_decimal_23_2")
  val penlc3_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "penlc3_decimal_23_2")
  val penfc_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "penfc_decimal_23_2")
  val pendays_int: ColumnWithName = ColumnWithName(prefix + "pendays_int")
  val penrc_string: ColumnWithName = ColumnWithName(prefix + "penrc_string")
  val grant_nbr_string: ColumnWithName = ColumnWithName(prefix + "grant_nbr_string")
  val sctax_decimal_13_2: ColumnWithName = ColumnWithName(prefix + "sctax_decimal_13_2")
  val fkber_long_string: ColumnWithName = ColumnWithName(prefix + "fkber_long_string")
  val gmvkz_string: ColumnWithName = ColumnWithName(prefix + "gmvkz_string")
  val srtype_string: ColumnWithName = ColumnWithName(prefix + "srtype_string")
  val intreno_string: ColumnWithName = ColumnWithName(prefix + "intreno_string")
  val measure_string: ColumnWithName = ColumnWithName(prefix + "measure_string")
  val auggj_string: ColumnWithName = ColumnWithName(prefix + "auggj_string")
  val ppa_ex_ind_string: ColumnWithName = ColumnWithName(prefix + "ppa_ex_ind_string")
  val docln_string: ColumnWithName = ColumnWithName(prefix + "docln_string")
  val segment_string: ColumnWithName = ColumnWithName(prefix + "segment_string")
  val psegment_string: ColumnWithName = ColumnWithName(prefix + "psegment_string")
  val pfkber_string: ColumnWithName = ColumnWithName(prefix + "pfkber_string")
  val hktid_string: ColumnWithName = ColumnWithName(prefix + "hktid_string")
  val kstar_string: ColumnWithName = ColumnWithName(prefix + "kstar_string")
  val xlgclr_string: ColumnWithName = ColumnWithName(prefix + "xlgclr_string")
  val taxps_string: ColumnWithName = ColumnWithName(prefix + "taxps_string")
  val pays_prov_string: ColumnWithName = ColumnWithName(prefix + "pays_prov_string")
  val pays_tran_string: ColumnWithName = ColumnWithName(prefix + "pays_tran_string")
  val mndid_string: ColumnWithName = ColumnWithName(prefix + "mndid_string")
  val xfrge_bseg_string: ColumnWithName = ColumnWithName(prefix + "xfrge_bseg_string")
  val awtyp_string: ColumnWithName = ColumnWithName(prefix + "awtyp_string")
  val awkey_string: ColumnWithName = ColumnWithName(prefix + "awkey_string")
  val awsys_string: ColumnWithName = ColumnWithName(prefix + "awsys_string")
  val posnr_string: ColumnWithName = ColumnWithName(prefix + "posnr_string")
  val buzei_sender_string: ColumnWithName = ColumnWithName(prefix + "buzei_sender_string")
  val h_monat_string: ColumnWithName = ColumnWithName(prefix + "h_monat_string")
  val h_bstat_string: ColumnWithName = ColumnWithName(prefix + "h_bstat_string")
  val h_budat_string: ColumnWithName = ColumnWithName(prefix + "h_budat_string")
  val h_bldat_string: ColumnWithName = ColumnWithName(prefix + "h_bldat_string")
  val h_waers_string: ColumnWithName = ColumnWithName(prefix + "h_waers_string")
  val h_blart_string: ColumnWithName = ColumnWithName(prefix + "h_blart_string")
  val h_hwaer_string: ColumnWithName = ColumnWithName(prefix + "h_hwaer_string")
  val h_hwae2_string: ColumnWithName = ColumnWithName(prefix + "h_hwae2_string")
  val h_hwae3_string: ColumnWithName = ColumnWithName(prefix + "h_hwae3_string")
  val sk1dt_string: ColumnWithName = ColumnWithName(prefix + "sk1dt_string")
  val sk2dt_string: ColumnWithName = ColumnWithName(prefix + "sk2dt_string")
  val prctr_drvtn_source_type_string: ColumnWithName = ColumnWithName(prefix + "prctr_drvtn_source_type_string")
  val payt_rsn_string: ColumnWithName = ColumnWithName(prefix + "payt_rsn_string")
  val _dataaging_string: ColumnWithName = ColumnWithName(prefix + "_dataaging_string")
  val fqftype_string: ColumnWithName = ColumnWithName(prefix + "fqftype_string")
  val lqitem_string: ColumnWithName = ColumnWithName(prefix + "lqitem_string")
  val gkont_string: ColumnWithName = ColumnWithName(prefix + "gkont_string")
  val gkart_string: ColumnWithName = ColumnWithName(prefix + "gkart_string")
  val ghkon_string: ColumnWithName = ColumnWithName(prefix + "ghkon_string")
  val squan_string: ColumnWithName = ColumnWithName(prefix + "squan_string")
  val anln2_pn_string: ColumnWithName = ColumnWithName(prefix + "anln2_pn_string")
  val bwasl_pn_string: ColumnWithName = ColumnWithName(prefix + "bwasl_pn_string")
  val bzdat_pn_string: ColumnWithName = ColumnWithName(prefix + "bzdat_pn_string")
  val xvabg_pn_string: ColumnWithName = ColumnWithName(prefix + "xvabg_pn_string")
  val anbtr_pn_decimal_23_2: ColumnWithName = ColumnWithName(prefix + "anbtr_pn_decimal_23_2")
  val prozs_pn_decimal_5_2: ColumnWithName = ColumnWithName(prefix + "prozs_pn_decimal_5_2")
  val acdoc_eew_dummy_string: ColumnWithName = ColumnWithName(prefix + "acdoc_eew_dummy_string")
  val dummy_incl_eew_cobl_string: ColumnWithName = ColumnWithName(prefix + "dummy_incl_eew_cobl_string")
  val kdgrp_string: ColumnWithName = ColumnWithName(prefix + "kdgrp_string")
  val land1_string: ColumnWithName = ColumnWithName(prefix + "land1_string")
  val brsch_string: ColumnWithName = ColumnWithName(prefix + "brsch_string")
  val acrobjtype_string: ColumnWithName = ColumnWithName(prefix + "acrobjtype_string")
  val acrlogsys_string: ColumnWithName = ColumnWithName(prefix + "acrlogsys_string")
  val acrobj_id_string: ColumnWithName = ColumnWithName(prefix + "acrobj_id_string")
  val acrsobj_id_string: ColumnWithName = ColumnWithName(prefix + "acrsobj_id_string")
  val acritmtype_string: ColumnWithName = ColumnWithName(prefix + "acritmtype_string")
  val acrrefobj_id_string: ColumnWithName = ColumnWithName(prefix + "acrrefobj_id_string")
  val acrvaldat_string: ColumnWithName = ColumnWithName(prefix + "acrvaldat_string")
  val valobjtype_string: ColumnWithName = ColumnWithName(prefix + "valobjtype_string")
  val valobj_id_string: ColumnWithName = ColumnWithName(prefix + "valobj_id_string")
  val valsobj_id_string: ColumnWithName = ColumnWithName(prefix + "valsobj_id_string")
  val netdt_string: ColumnWithName = ColumnWithName(prefix + "netdt_string")
  val risk_class_string: ColumnWithName = ColumnWithName(prefix + "risk_class_string")
  val sdm_version_string: ColumnWithName = ColumnWithName(prefix + "sdm_version_string")
  val glo_ref1_string: ColumnWithName = ColumnWithName(prefix + "glo_ref1_string")
  val re_bukrs_string: ColumnWithName = ColumnWithName(prefix + "re_bukrs_string")
  val re_account_string: ColumnWithName = ColumnWithName(prefix + "re_account_string")
  val dp_payment_type_string: ColumnWithName = ColumnWithName(prefix + "dp_payment_type_string")
  val dp_trans_id_string: ColumnWithName = ColumnWithName(prefix + "dp_trans_id_string")
  val dp_payment_request_string: ColumnWithName = ColumnWithName(prefix + "dp_payment_request_string")
  val pgeber_string: ColumnWithName = ColumnWithName(prefix + "pgeber_string")
  val pgrant_nbr_string: ColumnWithName = ColumnWithName(prefix + "pgrant_nbr_string")
  val budget_pd_string: ColumnWithName = ColumnWithName(prefix + "budget_pd_string")
  val pbudget_pd_string: ColumnWithName = ColumnWithName(prefix + "pbudget_pd_string")
  val j_1tpbupl_string: ColumnWithName = ColumnWithName(prefix + "j_1tpbupl_string")
  val perop_beg_string: ColumnWithName = ColumnWithName(prefix + "perop_beg_string")
  val perop_end_string: ColumnWithName = ColumnWithName(prefix + "perop_end_string")
  val fastpay_string: ColumnWithName = ColumnWithName(prefix + "fastpay_string")
  val ignr_ivref_string: ColumnWithName = ColumnWithName(prefix + "ignr_ivref_string")
  val fmfgus_key_string: ColumnWithName = ColumnWithName(prefix + "fmfgus_key_string")
  val fmxdocnr_string: ColumnWithName = ColumnWithName(prefix + "fmxdocnr_string")
  val fmxyear_string: ColumnWithName = ColumnWithName(prefix + "fmxyear_string")
  val fmxdocln_string: ColumnWithName = ColumnWithName(prefix + "fmxdocln_string")
  val fmxzekkn_string: ColumnWithName = ColumnWithName(prefix + "fmxzekkn_string")
  val prodper_string: ColumnWithName = ColumnWithName(prefix + "prodper_string")
  val gst_part_string: ColumnWithName = ColumnWithName(prefix + "gst_part_string")
  val plc_sup_string: ColumnWithName = ColumnWithName(prefix + "plc_sup_string")
  val hsn_sac_string: ColumnWithName = ColumnWithName(prefix + "hsn_sac_string")
  val irn_string: ColumnWithName = ColumnWithName(prefix + "irn_string")
  val recrf_string: ColumnWithName = ColumnWithName(prefix + "recrf_string")
  val bdgt_account_string: ColumnWithName = ColumnWithName(prefix + "bdgt_account_string")
  val bdgt_account_cocode_string: ColumnWithName = ColumnWithName(prefix + "bdgt_account_cocode_string")
  val inward_no_string: ColumnWithName = ColumnWithName(prefix + "inward_no_string")
  val inward_dt_string: ColumnWithName = ColumnWithName(prefix + "inward_dt_string")
  val ground_no_string: ColumnWithName = ColumnWithName(prefix + "ground_no_string")
  val ground_dt_string: ColumnWithName = ColumnWithName(prefix + "ground_dt_string")
  val ground_typ_string: ColumnWithName = ColumnWithName(prefix + "ground_typ_string")
  val pymtkey_string: ColumnWithName = ColumnWithName(prefix + "pymtkey_string")
}

object C_bseg extends C_bseg("") {
  def as(alias: String): C_bseg = new C_bseg(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
