// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_ghp

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_ebkn(
    @PK mandt: String,
    @PK banfn: String,
    @PK bnfpo: String,
    @PK zebkn: String,
    loekz: String,
    erdat: String,
    ernam: String,
    @Decimal(13, 3) menge: BigDecimal,
    @Decimal(3, 1) vproz: BigDecimal,
    sakto: String,
    gsber: String,
    kostl: String,
    projn: String,
    vbeln: String,
    vbelp: String,
    veten: String,
    anln1: String,
    anln2: String,
    aufnr: String,
    wempf: String,
    ablad: String,
    kokrs: String,
    xbkst: String,
    xbauf: String,
    xbpro: String,
    kstrg: String,
    paobjnr: String,
    prctr: String,
    ps_psp_pnr: String,
    nplnr: String,
    aufpl: String,
    imkey: String,
    aplzl: String,
    vptnr: String,
    fipos: String,
    recid: String,
    fistl: String,
    geber: String,
    fkber: String,
    dabrz: String,
    @Decimal(13, 2) netwr: BigDecimal,
    aufpl_ord: String,
    aplzl_ord: String,
    extwbselement: String,
    extvornr: String,
    service_doc_type: String,
    service_doc_id: String,
    service_doc_item_id: String,
    kblnr: String,
    kblpos: String,
    lstar: String,
    prznr: String,
    grant_nbr: String,
    fm_split_batch: String,
    fm_split_begru: String,
    budget_pd: String,
    dummy_incl_eew_cobl: String,
    fmfgus_key: String,
    egrup: String,
    vname: String,
    tcobjnr: String,
    dateofservice: String,
    notaxcorr: String,
    @Decimal(9, 6) diffoptrate: BigDecimal,
    hasdiffoptrate: String,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String
) extends Entity

object ebkn
    extends TableSpec[E_ebkn](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[sr_raw.ct_gbl_ghp.E_ebkn] {
  override def sourceTableSpec: TableSpec[sr_raw.ct_gbl_ghp.E_ebkn] = sr_raw.ct_gbl_ghp.ebkn
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("mandt", col("mandt_string")),
    ("banfn", col("banfn_string")),
    ("bnfpo", col("bnfpo_string")),
    ("zebkn", col("zebkn_string")),
    ("loekz", col("loekz_string")),
    ("erdat", col("erdat_string")),
    ("ernam", col("ernam_string")),
    ("menge", col("menge_decimal_13_3")),
    ("vproz", col("vproz_decimal_3_1")),
    ("sakto", col("sakto_string")),
    ("gsber", col("gsber_string")),
    ("kostl", col("kostl_string")),
    ("projn", col("projn_string")),
    ("vbeln", col("vbeln_string")),
    ("vbelp", col("vbelp_string")),
    ("veten", col("veten_string")),
    ("anln1", col("anln1_string")),
    ("anln2", col("anln2_string")),
    ("aufnr", col("aufnr_string")),
    ("wempf", col("wempf_string")),
    ("ablad", col("ablad_string")),
    ("kokrs", col("kokrs_string")),
    ("xbkst", col("xbkst_string")),
    ("xbauf", col("xbauf_string")),
    ("xbpro", col("xbpro_string")),
    ("kstrg", col("kstrg_string")),
    ("paobjnr", col("paobjnr_string")),
    ("prctr", col("prctr_string")),
    ("ps_psp_pnr", col("ps_psp_pnr_string")),
    ("nplnr", col("nplnr_string")),
    ("aufpl", col("aufpl_string")),
    ("imkey", col("imkey_string")),
    ("aplzl", col("aplzl_string")),
    ("vptnr", col("vptnr_string")),
    ("fipos", col("fipos_string")),
    ("recid", col("recid_string")),
    ("fistl", col("fistl_string")),
    ("geber", col("geber_string")),
    ("fkber", col("fkber_string")),
    ("dabrz", col("dabrz_string")),
    ("netwr", col("netwr_decimal_13_2")),
    ("aufpl_ord", col("aufpl_ord_string")),
    ("aplzl_ord", col("aplzl_ord_string")),
    ("extwbselement", col("extwbselement_string")),
    ("extvornr", col("extvornr_string")),
    ("service_doc_type", col("service_doc_type_string")),
    ("service_doc_id", col("service_doc_id_string")),
    ("service_doc_item_id", col("service_doc_item_id_string")),
    ("kblnr", col("kblnr_string")),
    ("kblpos", col("kblpos_string")),
    ("lstar", col("lstar_string")),
    ("prznr", col("prznr_string")),
    ("grant_nbr", col("grant_nbr_string")),
    ("fm_split_batch", col("fm_split_batch_string")),
    ("fm_split_begru", col("fm_split_begru_string")),
    ("budget_pd", col("budget_pd_string")),
    ("dummy_incl_eew_cobl", col("dummy_incl_eew_cobl_string")),
    ("fmfgus_key", col("fmfgus_key_string")),
    ("egrup", col("egrup_string")),
    ("vname", col("vname_string")),
    ("tcobjnr", col("tcobjnr_string")),
    ("dateofservice", col("dateofservice_string")),
    ("notaxcorr", col("notaxcorr_string")),
    ("diffoptrate", col("diffoptrate_decimal_9_6")),
    ("hasdiffoptrate", col("hasdiffoptrate_string"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_ebkn(prefix: String) extends ColumnWithNameAccessor {
  val mandt: ColumnWithName = ColumnWithName(prefix + "mandt")
  val banfn: ColumnWithName = ColumnWithName(prefix + "banfn")
  val bnfpo: ColumnWithName = ColumnWithName(prefix + "bnfpo")
  val zebkn: ColumnWithName = ColumnWithName(prefix + "zebkn")
  val loekz: ColumnWithName = ColumnWithName(prefix + "loekz")
  val erdat: ColumnWithName = ColumnWithName(prefix + "erdat")
  val ernam: ColumnWithName = ColumnWithName(prefix + "ernam")
  val menge: ColumnWithName = ColumnWithName(prefix + "menge")
  val vproz: ColumnWithName = ColumnWithName(prefix + "vproz")
  val sakto: ColumnWithName = ColumnWithName(prefix + "sakto")
  val gsber: ColumnWithName = ColumnWithName(prefix + "gsber")
  val kostl: ColumnWithName = ColumnWithName(prefix + "kostl")
  val projn: ColumnWithName = ColumnWithName(prefix + "projn")
  val vbeln: ColumnWithName = ColumnWithName(prefix + "vbeln")
  val vbelp: ColumnWithName = ColumnWithName(prefix + "vbelp")
  val veten: ColumnWithName = ColumnWithName(prefix + "veten")
  val anln1: ColumnWithName = ColumnWithName(prefix + "anln1")
  val anln2: ColumnWithName = ColumnWithName(prefix + "anln2")
  val aufnr: ColumnWithName = ColumnWithName(prefix + "aufnr")
  val wempf: ColumnWithName = ColumnWithName(prefix + "wempf")
  val ablad: ColumnWithName = ColumnWithName(prefix + "ablad")
  val kokrs: ColumnWithName = ColumnWithName(prefix + "kokrs")
  val xbkst: ColumnWithName = ColumnWithName(prefix + "xbkst")
  val xbauf: ColumnWithName = ColumnWithName(prefix + "xbauf")
  val xbpro: ColumnWithName = ColumnWithName(prefix + "xbpro")
  val kstrg: ColumnWithName = ColumnWithName(prefix + "kstrg")
  val paobjnr: ColumnWithName = ColumnWithName(prefix + "paobjnr")
  val prctr: ColumnWithName = ColumnWithName(prefix + "prctr")
  val ps_psp_pnr: ColumnWithName = ColumnWithName(prefix + "ps_psp_pnr")
  val nplnr: ColumnWithName = ColumnWithName(prefix + "nplnr")
  val aufpl: ColumnWithName = ColumnWithName(prefix + "aufpl")
  val imkey: ColumnWithName = ColumnWithName(prefix + "imkey")
  val aplzl: ColumnWithName = ColumnWithName(prefix + "aplzl")
  val vptnr: ColumnWithName = ColumnWithName(prefix + "vptnr")
  val fipos: ColumnWithName = ColumnWithName(prefix + "fipos")
  val recid: ColumnWithName = ColumnWithName(prefix + "recid")
  val fistl: ColumnWithName = ColumnWithName(prefix + "fistl")
  val geber: ColumnWithName = ColumnWithName(prefix + "geber")
  val fkber: ColumnWithName = ColumnWithName(prefix + "fkber")
  val dabrz: ColumnWithName = ColumnWithName(prefix + "dabrz")
  val netwr: ColumnWithName = ColumnWithName(prefix + "netwr")
  val aufpl_ord: ColumnWithName = ColumnWithName(prefix + "aufpl_ord")
  val aplzl_ord: ColumnWithName = ColumnWithName(prefix + "aplzl_ord")
  val extwbselement: ColumnWithName = ColumnWithName(prefix + "extwbselement")
  val extvornr: ColumnWithName = ColumnWithName(prefix + "extvornr")
  val service_doc_type: ColumnWithName = ColumnWithName(prefix + "service_doc_type")
  val service_doc_id: ColumnWithName = ColumnWithName(prefix + "service_doc_id")
  val service_doc_item_id: ColumnWithName = ColumnWithName(prefix + "service_doc_item_id")
  val kblnr: ColumnWithName = ColumnWithName(prefix + "kblnr")
  val kblpos: ColumnWithName = ColumnWithName(prefix + "kblpos")
  val lstar: ColumnWithName = ColumnWithName(prefix + "lstar")
  val prznr: ColumnWithName = ColumnWithName(prefix + "prznr")
  val grant_nbr: ColumnWithName = ColumnWithName(prefix + "grant_nbr")
  val fm_split_batch: ColumnWithName = ColumnWithName(prefix + "fm_split_batch")
  val fm_split_begru: ColumnWithName = ColumnWithName(prefix + "fm_split_begru")
  val budget_pd: ColumnWithName = ColumnWithName(prefix + "budget_pd")
  val dummy_incl_eew_cobl: ColumnWithName = ColumnWithName(prefix + "dummy_incl_eew_cobl")
  val fmfgus_key: ColumnWithName = ColumnWithName(prefix + "fmfgus_key")
  val egrup: ColumnWithName = ColumnWithName(prefix + "egrup")
  val vname: ColumnWithName = ColumnWithName(prefix + "vname")
  val tcobjnr: ColumnWithName = ColumnWithName(prefix + "tcobjnr")
  val dateofservice: ColumnWithName = ColumnWithName(prefix + "dateofservice")
  val notaxcorr: ColumnWithName = ColumnWithName(prefix + "notaxcorr")
  val diffoptrate: ColumnWithName = ColumnWithName(prefix + "diffoptrate")
  val hasdiffoptrate: ColumnWithName = ColumnWithName(prefix + "hasdiffoptrate")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
}

object C_ebkn extends C_ebkn("") {
  def as(alias: String): C_ebkn = new C_ebkn(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
