// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_ghp

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_prcd_elements(
    @PK client: String,
    @PK knumv: String,
    @PK kposn: String,
    @PK stunr: String,
    @PK zaehk: String,
    kappl: String,
    kschl: String,
    kdatu: String,
    krech: String,
    @Decimal(24, 9) kawrt: BigDecimal,
    @Decimal(24, 9) kbetr: BigDecimal,
    waers: String,
    @Decimal(9, 5) kkurs: BigDecimal,
    @Decimal(5, 0) kpein: BigDecimal,
    kmein: String,
    kumza: BigDecimal,
    kumne: BigDecimal,
    kntyp: String,
    kstat: String,
    knprs: String,
    kruek: String,
    kreli: String,
    kherk: String,
    kgrpe: String,
    kolnr: String,
    knumh: String,
    kopos: String,
    kvsl1: String,
    sakn1: String,
    mwsk1: String,
    kvsl2: String,
    sakn2: String,
    mwsk2: String,
    lifnr: String,
    @Decimal(5, 2) kdiff: BigDecimal,
    @Decimal(15, 2) kwert: BigDecimal,
    waerk: String,
    ksteu: String,
    kinak: String,
    koaid: String,
    zaeko: String,
    kfaktor: BoxedDouble,
    kdupl: String,
    kfaktor1: BoxedDouble,
    kzbzg: String,
    @Decimal(24, 9) kstbs: BigDecimal,
    konms: String,
    konws: String,
    kwaeh: String,
    @Decimal(15, 2) kwert_k: BigDecimal,
    kfkiv: String,
    kmprs: String,
    prsqu: String,
    txjlv: String,
    koupd: String,
    kmxaw: String,
    kmxwr: String,
    @Decimal(24, 9) kawrt_k: BigDecimal,
    kunnr: String,
    kvarc: String,
    varcond: String,
    ktrel: String,
    mdflg: String,
    _dataaging: String,
    cpf_guid: String,
    @Decimal(31, 14) kaqty: BigDecimal,
    val_zero: String,
    is_acct_detn_relevant: String,
    tax_country: String,
    common_suppl_data: String,
    pricingsubprocedure: String,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    kbflag_binary: Array[Byte]
) extends Entity

object prcd_elements
    extends TableSpec[E_prcd_elements](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[sr_raw.ct_gbl_ghp.E_prcd_elements] {
  override def sourceTableSpec: TableSpec[sr_raw.ct_gbl_ghp.E_prcd_elements] = sr_raw.ct_gbl_ghp.prcd_elements
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("client", col("client_string")),
    ("knumv", col("knumv_string")),
    ("kposn", col("kposn_string")),
    ("stunr", col("stunr_string")),
    ("zaehk", col("zaehk_string")),
    ("kappl", col("kappl_string")),
    ("kschl", col("kschl_string")),
    ("kdatu", col("kdatu_string")),
    ("krech", col("krech_string")),
    ("kawrt", col("kawrt_decimal_24_9")),
    ("kbetr", col("kbetr_decimal_24_9")),
    ("waers", col("waers_string")),
    ("kkurs", col("kkurs_decimal_9_5")),
    ("kpein", col("kpein_decimal_5_0")),
    ("kmein", col("kmein_string")),
    ("kumza", col("kumza_decimal_10_0")),
    ("kumne", col("kumne_decimal_10_0")),
    ("kntyp", col("kntyp_string")),
    ("kstat", col("kstat_string")),
    ("knprs", col("knprs_string")),
    ("kruek", col("kruek_string")),
    ("kreli", col("kreli_string")),
    ("kherk", col("kherk_string")),
    ("kgrpe", col("kgrpe_string")),
    ("kolnr", col("kolnr_string")),
    ("knumh", col("knumh_string")),
    ("kopos", col("kopos_string")),
    ("kvsl1", col("kvsl1_string")),
    ("sakn1", col("sakn1_string")),
    ("mwsk1", col("mwsk1_string")),
    ("kvsl2", col("kvsl2_string")),
    ("sakn2", col("sakn2_string")),
    ("mwsk2", col("mwsk2_string")),
    ("lifnr", col("lifnr_string")),
    ("kdiff", col("kdiff_decimal_5_2")),
    ("kwert", col("kwert_decimal_15_2")),
    ("waerk", col("waerk_string")),
    ("ksteu", col("ksteu_string")),
    ("kinak", col("kinak_string")),
    ("koaid", col("koaid_string")),
    ("zaeko", col("zaeko_string")),
    ("kfaktor", col("kfaktor_double")),
    ("kdupl", col("kdupl_string")),
    ("kfaktor1", col("kfaktor1_double")),
    ("kzbzg", col("kzbzg_string")),
    ("kstbs", col("kstbs_decimal_24_9")),
    ("konms", col("konms_string")),
    ("konws", col("konws_string")),
    ("kwaeh", col("kwaeh_string")),
    ("kwert_k", col("kwert_k_decimal_15_2")),
    ("kfkiv", col("kfkiv_string")),
    ("kmprs", col("kmprs_string")),
    ("prsqu", col("prsqu_string")),
    ("txjlv", col("txjlv_string")),
    ("koupd", col("koupd_string")),
    ("kmxaw", col("kmxaw_string")),
    ("kmxwr", col("kmxwr_string")),
    ("kawrt_k", col("kawrt_k_decimal_24_9")),
    ("kunnr", col("kunnr_string")),
    ("kvarc", col("kvarc_string")),
    ("varcond", col("varcond_string")),
    ("ktrel", col("ktrel_string")),
    ("mdflg", col("mdflg_string")),
    ("_dataaging", col("_dataaging_string")),
    ("cpf_guid", col("cpf_guid_string")),
    ("kaqty", col("kaqty_decimal_31_14")),
    ("val_zero", col("val_zero_string")),
    ("is_acct_detn_relevant", col("is_acct_detn_relevant_string")),
    ("tax_country", col("tax_country_string")),
    ("common_suppl_data", col("common_suppl_data_string")),
    ("pricingsubprocedure", col("pricingsubprocedure_string"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_prcd_elements(prefix: String) extends ColumnWithNameAccessor {
  val client: ColumnWithName = ColumnWithName(prefix + "client")
  val knumv: ColumnWithName = ColumnWithName(prefix + "knumv")
  val kposn: ColumnWithName = ColumnWithName(prefix + "kposn")
  val stunr: ColumnWithName = ColumnWithName(prefix + "stunr")
  val zaehk: ColumnWithName = ColumnWithName(prefix + "zaehk")
  val kappl: ColumnWithName = ColumnWithName(prefix + "kappl")
  val kschl: ColumnWithName = ColumnWithName(prefix + "kschl")
  val kdatu: ColumnWithName = ColumnWithName(prefix + "kdatu")
  val krech: ColumnWithName = ColumnWithName(prefix + "krech")
  val kawrt: ColumnWithName = ColumnWithName(prefix + "kawrt")
  val kbetr: ColumnWithName = ColumnWithName(prefix + "kbetr")
  val waers: ColumnWithName = ColumnWithName(prefix + "waers")
  val kkurs: ColumnWithName = ColumnWithName(prefix + "kkurs")
  val kpein: ColumnWithName = ColumnWithName(prefix + "kpein")
  val kmein: ColumnWithName = ColumnWithName(prefix + "kmein")
  val kumza: ColumnWithName = ColumnWithName(prefix + "kumza")
  val kumne: ColumnWithName = ColumnWithName(prefix + "kumne")
  val kntyp: ColumnWithName = ColumnWithName(prefix + "kntyp")
  val kstat: ColumnWithName = ColumnWithName(prefix + "kstat")
  val knprs: ColumnWithName = ColumnWithName(prefix + "knprs")
  val kruek: ColumnWithName = ColumnWithName(prefix + "kruek")
  val kreli: ColumnWithName = ColumnWithName(prefix + "kreli")
  val kherk: ColumnWithName = ColumnWithName(prefix + "kherk")
  val kgrpe: ColumnWithName = ColumnWithName(prefix + "kgrpe")
  val kolnr: ColumnWithName = ColumnWithName(prefix + "kolnr")
  val knumh: ColumnWithName = ColumnWithName(prefix + "knumh")
  val kopos: ColumnWithName = ColumnWithName(prefix + "kopos")
  val kvsl1: ColumnWithName = ColumnWithName(prefix + "kvsl1")
  val sakn1: ColumnWithName = ColumnWithName(prefix + "sakn1")
  val mwsk1: ColumnWithName = ColumnWithName(prefix + "mwsk1")
  val kvsl2: ColumnWithName = ColumnWithName(prefix + "kvsl2")
  val sakn2: ColumnWithName = ColumnWithName(prefix + "sakn2")
  val mwsk2: ColumnWithName = ColumnWithName(prefix + "mwsk2")
  val lifnr: ColumnWithName = ColumnWithName(prefix + "lifnr")
  val kdiff: ColumnWithName = ColumnWithName(prefix + "kdiff")
  val kwert: ColumnWithName = ColumnWithName(prefix + "kwert")
  val waerk: ColumnWithName = ColumnWithName(prefix + "waerk")
  val ksteu: ColumnWithName = ColumnWithName(prefix + "ksteu")
  val kinak: ColumnWithName = ColumnWithName(prefix + "kinak")
  val koaid: ColumnWithName = ColumnWithName(prefix + "koaid")
  val zaeko: ColumnWithName = ColumnWithName(prefix + "zaeko")
  val kfaktor: ColumnWithName = ColumnWithName(prefix + "kfaktor")
  val kdupl: ColumnWithName = ColumnWithName(prefix + "kdupl")
  val kfaktor1: ColumnWithName = ColumnWithName(prefix + "kfaktor1")
  val kzbzg: ColumnWithName = ColumnWithName(prefix + "kzbzg")
  val kstbs: ColumnWithName = ColumnWithName(prefix + "kstbs")
  val konms: ColumnWithName = ColumnWithName(prefix + "konms")
  val konws: ColumnWithName = ColumnWithName(prefix + "konws")
  val kwaeh: ColumnWithName = ColumnWithName(prefix + "kwaeh")
  val kwert_k: ColumnWithName = ColumnWithName(prefix + "kwert_k")
  val kfkiv: ColumnWithName = ColumnWithName(prefix + "kfkiv")
  val kmprs: ColumnWithName = ColumnWithName(prefix + "kmprs")
  val prsqu: ColumnWithName = ColumnWithName(prefix + "prsqu")
  val txjlv: ColumnWithName = ColumnWithName(prefix + "txjlv")
  val koupd: ColumnWithName = ColumnWithName(prefix + "koupd")
  val kmxaw: ColumnWithName = ColumnWithName(prefix + "kmxaw")
  val kmxwr: ColumnWithName = ColumnWithName(prefix + "kmxwr")
  val kawrt_k: ColumnWithName = ColumnWithName(prefix + "kawrt_k")
  val kunnr: ColumnWithName = ColumnWithName(prefix + "kunnr")
  val kvarc: ColumnWithName = ColumnWithName(prefix + "kvarc")
  val varcond: ColumnWithName = ColumnWithName(prefix + "varcond")
  val ktrel: ColumnWithName = ColumnWithName(prefix + "ktrel")
  val mdflg: ColumnWithName = ColumnWithName(prefix + "mdflg")
  val _dataaging: ColumnWithName = ColumnWithName(prefix + "_dataaging")
  val cpf_guid: ColumnWithName = ColumnWithName(prefix + "cpf_guid")
  val kaqty: ColumnWithName = ColumnWithName(prefix + "kaqty")
  val val_zero: ColumnWithName = ColumnWithName(prefix + "val_zero")
  val is_acct_detn_relevant: ColumnWithName = ColumnWithName(prefix + "is_acct_detn_relevant")
  val tax_country: ColumnWithName = ColumnWithName(prefix + "tax_country")
  val common_suppl_data: ColumnWithName = ColumnWithName(prefix + "common_suppl_data")
  val pricingsubprocedure: ColumnWithName = ColumnWithName(prefix + "pricingsubprocedure")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val kbflag_binary: ColumnWithName = ColumnWithName(prefix + "kbflag_binary")
}

object C_prcd_elements extends C_prcd_elements("") {
  def as(alias: String): C_prcd_elements = new C_prcd_elements(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
