// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_ghp

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_ska1(
    @PK mandt: String,
    @PK ktopl: String,
    @PK saknr: String,
    xbilk: String,
    sakan: String,
    bilkt: String,
    erdat: String,
    ernam: String,
    gvtyp: String,
    ktoks: String,
    mustr: String,
    vbund: String,
    xloev: String,
    xspea: String,
    xspeb: String,
    xspep: String,
    mcod1: String,
    func_area: String,
    glaccount_type: String,
    glaccount_subtype: String,
    main_saknr: String,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    @Decimal(15, 0) last_changed_ts_decimal_15_0: BigDecimal
) extends Entity

object ska1
    extends TableSpec[E_ska1](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[sr_raw.ct_gbl_ghp.E_ska1] {
  override def sourceTableSpec: TableSpec[sr_raw.ct_gbl_ghp.E_ska1] = sr_raw.ct_gbl_ghp.ska1
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("mandt", col("mandt_string")),
    ("ktopl", col("ktopl_string")),
    ("saknr", col("saknr_string")),
    ("xbilk", col("xbilk_string")),
    ("sakan", col("sakan_string")),
    ("bilkt", col("bilkt_string")),
    ("erdat", col("erdat_string")),
    ("ernam", col("ernam_string")),
    ("gvtyp", col("gvtyp_string")),
    ("ktoks", col("ktoks_string")),
    ("mustr", col("mustr_string")),
    ("vbund", col("vbund_string")),
    ("xloev", col("xloev_string")),
    ("xspea", col("xspea_string")),
    ("xspeb", col("xspeb_string")),
    ("xspep", col("xspep_string")),
    ("mcod1", col("mcod1_string")),
    ("func_area", col("func_area_string")),
    ("glaccount_type", col("glaccount_type_string")),
    ("glaccount_subtype", col("glaccount_subtype_string")),
    ("main_saknr", col("main_saknr_string"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_ska1(prefix: String) extends ColumnWithNameAccessor {
  val mandt: ColumnWithName = ColumnWithName(prefix + "mandt")
  val ktopl: ColumnWithName = ColumnWithName(prefix + "ktopl")
  val saknr: ColumnWithName = ColumnWithName(prefix + "saknr")
  val xbilk: ColumnWithName = ColumnWithName(prefix + "xbilk")
  val sakan: ColumnWithName = ColumnWithName(prefix + "sakan")
  val bilkt: ColumnWithName = ColumnWithName(prefix + "bilkt")
  val erdat: ColumnWithName = ColumnWithName(prefix + "erdat")
  val ernam: ColumnWithName = ColumnWithName(prefix + "ernam")
  val gvtyp: ColumnWithName = ColumnWithName(prefix + "gvtyp")
  val ktoks: ColumnWithName = ColumnWithName(prefix + "ktoks")
  val mustr: ColumnWithName = ColumnWithName(prefix + "mustr")
  val vbund: ColumnWithName = ColumnWithName(prefix + "vbund")
  val xloev: ColumnWithName = ColumnWithName(prefix + "xloev")
  val xspea: ColumnWithName = ColumnWithName(prefix + "xspea")
  val xspeb: ColumnWithName = ColumnWithName(prefix + "xspeb")
  val xspep: ColumnWithName = ColumnWithName(prefix + "xspep")
  val mcod1: ColumnWithName = ColumnWithName(prefix + "mcod1")
  val func_area: ColumnWithName = ColumnWithName(prefix + "func_area")
  val glaccount_type: ColumnWithName = ColumnWithName(prefix + "glaccount_type")
  val glaccount_subtype: ColumnWithName = ColumnWithName(prefix + "glaccount_subtype")
  val main_saknr: ColumnWithName = ColumnWithName(prefix + "main_saknr")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val last_changed_ts_decimal_15_0: ColumnWithName = ColumnWithName(prefix + "last_changed_ts_decimal_15_0")
}

object C_ska1 extends C_ska1("") {
  def as(alias: String): C_ska1 = new C_ska1(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
