// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_ghp

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_ghp.{t001 => sr_raw_t001}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrT001(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK bukrs: String,
    butxt: String,
    ort01: String,
    land1: String,
    waers: String,
    spras: String,
    ktopl: String,
    waabw: String,
    periv: String,
    kokfi: String,
    rcomp: String,
    adrnr: String,
    stceg: String,
    fikrs: String,
    xfmco: String,
    xfmcb: String,
    xfmca: String,
    txjcd: String,
    fmhrdate: String,
    xtemplt: String,
    transit_plant: String,
    buvar: String,
    fdbuk: String,
    xfdis: String,
    xvalv: String,
    xskfn: String,
    kkber: String,
    xmwsn: String,
    mregl: String,
    xgsbe: String,
    xgjrv: String,
    xkdft: String,
    xprod: String,
    xeink: String,
    xjvaa: String,
    xvvwa: String,
    xslta: String,
    xfdmm: String,
    xfdsd: String,
    xextb: String,
    ebukr: String,
    ktop2: String,
    umkrs: String,
    bukrs_glob: String,
    fstva: String,
    opvar: String,
    xcovr: String,
    txkrs: String,
    wfvar: String,
    xbbbf: String,
    xbbbe: String,
    xbbba: String,
    xbbko: String,
    xstdt: String,
    mwskv: String,
    mwska: String,
    impda: String,
    xnegp: String,
    xkkbi: String,
    wt_newwt: String,
    pp_pdate: String,
    infmt: String,
    fstvare: String,
    kopim: String,
    dkweg: String,
    offsacct: String,
    bapovar: String,
    xcos: String,
    xcession: String,
    xsplt: String,
    surccm: String,
    dtprov: String,
    dtamtc: String,
    dttaxc: String,
    dttdsp: String,
    dtaxr: String,
    xvatdate: String,
    pst_per_var: String,
    xbbsc: String,
    f_obsolete: String,
    fm_derive_acc: String
) extends Entity

object t001 extends TableSpec[SrT001] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_ghp.E_t001] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_ghp.E_t001] = sr_raw_t001

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("bukrs", coalesce(col("bukrs_string"), lit(""))),
    ("butxt", col("butxt_string")),
    ("ort01", col("ort01_string")),
    ("land1", col("land1_string")),
    ("waers", col("waers_string")),
    ("spras", col("spras_string")),
    ("ktopl", col("ktopl_string")),
    ("waabw", col("waabw_string")),
    ("periv", col("periv_string")),
    ("kokfi", col("kokfi_string")),
    ("rcomp", col("rcomp_string")),
    ("adrnr", col("adrnr_string")),
    ("stceg", col("stceg_string")),
    ("fikrs", col("fikrs_string")),
    ("xfmco", col("xfmco_string")),
    ("xfmcb", col("xfmcb_string")),
    ("xfmca", col("xfmca_string")),
    ("txjcd", col("txjcd_string")),
    ("fmhrdate", col("fmhrdate_string")),
    ("xtemplt", col("xtemplt_string")),
    ("transit_plant", col("transit_plant_string")),
    ("buvar", col("buvar_string")),
    ("fdbuk", col("fdbuk_string")),
    ("xfdis", col("xfdis_string")),
    ("xvalv", col("xvalv_string")),
    ("xskfn", col("xskfn_string")),
    ("kkber", col("kkber_string")),
    ("xmwsn", col("xmwsn_string")),
    ("mregl", col("mregl_string")),
    ("xgsbe", col("xgsbe_string")),
    ("xgjrv", col("xgjrv_string")),
    ("xkdft", col("xkdft_string")),
    ("xprod", col("xprod_string")),
    ("xeink", col("xeink_string")),
    ("xjvaa", col("xjvaa_string")),
    ("xvvwa", col("xvvwa_string")),
    ("xslta", col("xslta_string")),
    ("xfdmm", col("xfdmm_string")),
    ("xfdsd", col("xfdsd_string")),
    ("xextb", col("xextb_string")),
    ("ebukr", col("ebukr_string")),
    ("ktop2", col("ktop2_string")),
    ("umkrs", col("umkrs_string")),
    ("bukrs_glob", col("bukrs_glob_string")),
    ("fstva", col("fstva_string")),
    ("opvar", col("opvar_string")),
    ("xcovr", col("xcovr_string")),
    ("txkrs", col("txkrs_string")),
    ("wfvar", col("wfvar_string")),
    ("xbbbf", col("xbbbf_string")),
    ("xbbbe", col("xbbbe_string")),
    ("xbbba", col("xbbba_string")),
    ("xbbko", col("xbbko_string")),
    ("xstdt", col("xstdt_string")),
    ("mwskv", col("mwskv_string")),
    ("mwska", col("mwska_string")),
    ("impda", col("impda_string")),
    ("xnegp", col("xnegp_string")),
    ("xkkbi", col("xkkbi_string")),
    ("wt_newwt", col("wt_newwt_string")),
    ("pp_pdate", col("pp_pdate_string")),
    ("infmt", col("infmt_string")),
    ("fstvare", col("fstvare_string")),
    ("kopim", col("kopim_string")),
    ("dkweg", col("dkweg_string")),
    ("offsacct", col("offsacct_string")),
    ("bapovar", col("bapovar_string")),
    ("xcos", col("xcos_string")),
    ("xcession", col("xcession_string")),
    ("xsplt", col("xsplt_string")),
    ("surccm", col("surccm_string")),
    ("dtprov", col("dtprov_string")),
    ("dtamtc", col("dtamtc_string")),
    ("dttaxc", col("dttaxc_string")),
    ("dttdsp", col("dttdsp_string")),
    ("dtaxr", col("dtaxr_string")),
    ("xvatdate", col("xvatdate_string")),
    ("pst_per_var", col("pst_per_var_string")),
    ("xbbsc", col("xbbsc_string")),
    ("f_obsolete", col("f_obsolete_string")),
    ("fm_derive_acc", col("fm_derive_acc_string"))
  )
}
