// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_ghp

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_t059q(
    @PK mandt: String,
    @PK land1: String,
    @PK qsskz: String,
    qscod: String,
    qsbez: String,
    @Decimal(5, 2) qproz: BigDecimal,
    @Decimal(4, 2) qsatz: BigDecimal,
    xntto: String,
    xqsbz: String,
    @Decimal(4, 2) qsatr: BigDecimal,
    xqfor: String,
    @Decimal(23, 2) qmind: BigDecimal,
    qmiwa: String,
    bland: String,
    fprcd: String,
    qekar: String,
    @Decimal(4, 2) qsats: BigDecimal,
    j_1isectio: String,
    j_1itxvnty: String,
    j_1ixvnds: String,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String
) extends Entity

object t059q
    extends TableSpec[E_t059q](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[sr_raw.ct_gbl_ghp.E_t059q] {
  override def sourceTableSpec: TableSpec[sr_raw.ct_gbl_ghp.E_t059q] = sr_raw.ct_gbl_ghp.t059q
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("mandt", col("mandt_string")),
    ("land1", col("land1_string")),
    ("qsskz", col("qsskz_string")),
    ("qscod", col("qscod_string")),
    ("qsbez", col("qsbez_string")),
    ("qproz", col("qproz_decimal_5_2")),
    ("qsatz", col("qsatz_decimal_4_2")),
    ("xntto", col("xntto_string")),
    ("xqsbz", col("xqsbz_string")),
    ("qsatr", col("qsatr_decimal_4_2")),
    ("xqfor", col("xqfor_string")),
    ("qmind", col("qmind_decimal_23_2")),
    ("qmiwa", col("qmiwa_string")),
    ("bland", col("bland_string")),
    ("fprcd", col("fprcd_string")),
    ("qekar", col("qekar_string")),
    ("qsats", col("qsats_decimal_4_2")),
    ("j_1isectio", col("j_1isectio_string")),
    ("j_1itxvnty", col("j_1itxvnty_string")),
    ("j_1ixvnds", col("j_1ixvnds_string"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_t059q(prefix: String) extends ColumnWithNameAccessor {
  val mandt: ColumnWithName = ColumnWithName(prefix + "mandt")
  val land1: ColumnWithName = ColumnWithName(prefix + "land1")
  val qsskz: ColumnWithName = ColumnWithName(prefix + "qsskz")
  val qscod: ColumnWithName = ColumnWithName(prefix + "qscod")
  val qsbez: ColumnWithName = ColumnWithName(prefix + "qsbez")
  val qproz: ColumnWithName = ColumnWithName(prefix + "qproz")
  val qsatz: ColumnWithName = ColumnWithName(prefix + "qsatz")
  val xntto: ColumnWithName = ColumnWithName(prefix + "xntto")
  val xqsbz: ColumnWithName = ColumnWithName(prefix + "xqsbz")
  val qsatr: ColumnWithName = ColumnWithName(prefix + "qsatr")
  val xqfor: ColumnWithName = ColumnWithName(prefix + "xqfor")
  val qmind: ColumnWithName = ColumnWithName(prefix + "qmind")
  val qmiwa: ColumnWithName = ColumnWithName(prefix + "qmiwa")
  val bland: ColumnWithName = ColumnWithName(prefix + "bland")
  val fprcd: ColumnWithName = ColumnWithName(prefix + "fprcd")
  val qekar: ColumnWithName = ColumnWithName(prefix + "qekar")
  val qsats: ColumnWithName = ColumnWithName(prefix + "qsats")
  val j_1isectio: ColumnWithName = ColumnWithName(prefix + "j_1isectio")
  val j_1itxvnty: ColumnWithName = ColumnWithName(prefix + "j_1itxvnty")
  val j_1ixvnds: ColumnWithName = ColumnWithName(prefix + "j_1ixvnds")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
}

object C_t059q extends C_t059q("") {
  def as(alias: String): C_t059q = new C_t059q(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
