// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_epp

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_epp.{afko => sr_raw_afko}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrAfko(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK aufnr: String,
    gltrp: String,
    gstrp: String,
    ftrms: String,
    gltrs: String,
    gstrs: String,
    gstri: String,
    getri: String,
    gltri: String,
    ftrmi: String,
    ftrmp: String,
    rsnum: String,
    @Decimal(13, 3) gasmg: java.math.BigDecimal,
    @Decimal(13, 3) gamng: java.math.BigDecimal,
    gmein: String,
    plnbez: String,
    plnty: String,
    plnnr: String,
    plnaw: String,
    plnal: String,
    pverw: String,
    plauf: String,
    @Decimal(13, 3) plsvb: java.math.BigDecimal,
    plnme: String,
    @Decimal(13, 3) plsvn: java.math.BigDecimal,
    pdatv: String,
    paenr: String,
    plgrp: String,
    @Decimal(13, 3) lodiv: java.math.BigDecimal,
    stlty: String,
    stlbez: String,
    stlst: String,
    stlnr: String,
    sdatv: String,
    @Decimal(13, 3) sbmng: java.math.BigDecimal,
    sbmeh: String,
    saenr: String,
    stlal: String,
    stlan: String,
    @Decimal(13, 3) slsvn: java.math.BigDecimal,
    @Decimal(13, 3) slsbs: java.math.BigDecimal,
    aufld: String,
    dispo: String,
    aufpl: String,
    fevor: String,
    fhori: String,
    terkz: String,
    redkz: String,
    aprio: String,
    ntzue: String,
    vorue: String,
    profid: String,
    vorgz: String,
    sichz: String,
    freiz: String,
    upter: String,
    bedid: String,
    pronr: String,
    zaehl: String,
    mzaehl: String,
    zkriz: String,
    prueflos: String,
    klvarp: String,
    klvari: String,
    rgekz: String,
    plart: String,
    flg_aob: String,
    flg_arbei: String,
    gltpp: String,
    gstpp: String,
    gltps: String,
    gstps: String,
    ftrps: String,
    rdkzp: String,
    trkzp: String,
    rueck: String,
    rmzhl: String,
    @Decimal(13, 3) igmng: java.math.BigDecimal,
    ratid: String,
    groid: String,
    cuobj: String,
    gluzs: String,
    gsuzs: String,
    revlv: String,
    rshty: String,
    rshid: String,
    rsnty: String,
    rsnid: String,
    nauterm: String,
    naucost: String,
    @Decimal(2, 0) stufe: java.math.BigDecimal,
    @Decimal(4, 0) wegxx: java.math.BigDecimal,
    @Decimal(4, 0) vwegx: java.math.BigDecimal,
    arsnr: String,
    arsps: String,
    maufnr: String,
    lknot: String,
    rknot: String,
    prodnet: String,
    @Decimal(13, 3) iasmg: java.math.BigDecimal,
    abarb: String,
    aufnt: String,
    aufpt: String,
    aplzt: String,
    no_disp: String,
    csplit: String,
    aennr: String,
    cy_seqnr: String,
    breaks: String,
    @Decimal(6, 3) vorgz_trm: java.math.BigDecimal,
    @Decimal(6, 3) sichz_trm: java.math.BigDecimal,
    trmdt: String,
    gluzp: String,
    gsuzp: String,
    gsuzi: String,
    geuzi: String,
    glupp: String,
    gsupp: String,
    glups: String,
    gsups: String,
    chsch: String,
    kapt_vorgz: String,
    kapt_sichz: String,
    lead_aufnr: String,
    pnetstartd: String,
    pnetstartt: String,
    pnetendd: String,
    pnetendt: String,
    kbed: String,
    kkalkr: String,
    sfcpf: String,
    @Decimal(13, 3) rmnga: java.math.BigDecimal,
    gsbtr: String,
    @Decimal(13, 3) vfmng: java.math.BigDecimal,
    nopcost: String,
    netzkont: String,
    atrkz: String,
    objtype: String,
    ch_proc: String,
    kapversa: String,
    colordproc: String,
    kzerb: String,
    conf_key: String,
    st_arbid: String,
    vsnmr_v: String,
    terhw: String,
    splstat: String,
    costupd: String,
    @Decimal(13, 3) max_gamng: java.math.BigDecimal,
    mes_routingid: String,
    adpsp: String,
    rmanr: String,
    posnr_rma: String,
    posnv_rma: String,
    @Decimal(5, 0) cfb_maxlz: java.math.BigDecimal,
    cfb_lzeih: String,
    @Decimal(4, 0) cfb_adtdays: java.math.BigDecimal,
    cfb_datofm: String,
    cfb_bbdpi: String,
    oihantyp: String,
    mill_ratio: Int,
    bmeins: String,
    @Decimal(13, 3) bmenge: java.math.BigDecimal,
    mill_oc_zuskz: String
) extends Entity

object afko extends TableSpec[SrAfko] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_afko] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_afko] = sr_raw_afko

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("aufnr", coalesce(col("aufnr_string"), lit(""))),
    ("gltrp", col("gltrp_string")),
    ("gstrp", col("gstrp_string")),
    ("ftrms", col("ftrms_string")),
    ("gltrs", col("gltrs_string")),
    ("gstrs", col("gstrs_string")),
    ("gstri", col("gstri_string")),
    ("getri", col("getri_string")),
    ("gltri", col("gltri_string")),
    ("ftrmi", col("ftrmi_string")),
    ("ftrmp", col("ftrmp_string")),
    ("rsnum", col("rsnum_string")),
    ("gasmg", col("gasmg_decimal_13_3")),
    ("gamng", col("gamng_decimal_13_3")),
    ("gmein", col("gmein_string")),
    ("plnbez", col("plnbez_string")),
    ("plnty", col("plnty_string")),
    ("plnnr", col("plnnr_string")),
    ("plnaw", col("plnaw_string")),
    ("plnal", col("plnal_string")),
    ("pverw", col("pverw_string")),
    ("plauf", col("plauf_string")),
    ("plsvb", col("plsvb_decimal_13_3")),
    ("plnme", col("plnme_string")),
    ("plsvn", col("plsvn_decimal_13_3")),
    ("pdatv", col("pdatv_string")),
    ("paenr", col("paenr_string")),
    ("plgrp", col("plgrp_string")),
    ("lodiv", col("lodiv_decimal_13_3")),
    ("stlty", col("stlty_string")),
    ("stlbez", col("stlbez_string")),
    ("stlst", col("stlst_string")),
    ("stlnr", col("stlnr_string")),
    ("sdatv", col("sdatv_string")),
    ("sbmng", col("sbmng_decimal_13_3")),
    ("sbmeh", col("sbmeh_string")),
    ("saenr", col("saenr_string")),
    ("stlal", col("stlal_string")),
    ("stlan", col("stlan_string")),
    ("slsvn", col("slsvn_decimal_13_3")),
    ("slsbs", col("slsbs_decimal_13_3")),
    ("aufld", col("aufld_string")),
    ("dispo", col("dispo_string")),
    ("aufpl", col("aufpl_string")),
    ("fevor", col("fevor_string")),
    ("fhori", col("fhori_string")),
    ("terkz", col("terkz_string")),
    ("redkz", col("redkz_string")),
    ("aprio", col("aprio_string")),
    ("ntzue", col("ntzue_string")),
    ("vorue", col("vorue_string")),
    ("profid", col("profid_string")),
    ("vorgz", col("vorgz_string")),
    ("sichz", col("sichz_string")),
    ("freiz", col("freiz_string")),
    ("upter", col("upter_string")),
    ("bedid", col("bedid_string")),
    ("pronr", col("pronr_string")),
    ("zaehl", col("zaehl_string")),
    ("mzaehl", col("mzaehl_string")),
    ("zkriz", col("zkriz_string")),
    ("prueflos", col("prueflos_string")),
    ("klvarp", col("klvarp_string")),
    ("klvari", col("klvari_string")),
    ("rgekz", col("rgekz_string")),
    ("plart", col("plart_string")),
    ("flg_aob", col("flg_aob_string")),
    ("flg_arbei", col("flg_arbei_string")),
    ("gltpp", col("gltpp_string")),
    ("gstpp", col("gstpp_string")),
    ("gltps", col("gltps_string")),
    ("gstps", col("gstps_string")),
    ("ftrps", col("ftrps_string")),
    ("rdkzp", col("rdkzp_string")),
    ("trkzp", col("trkzp_string")),
    ("rueck", col("rueck_string")),
    ("rmzhl", col("rmzhl_string")),
    ("igmng", col("igmng_decimal_13_3")),
    ("ratid", col("ratid_string")),
    ("groid", col("groid_string")),
    ("cuobj", col("cuobj_string")),
    ("gluzs", col("gluzs_string")),
    ("gsuzs", col("gsuzs_string")),
    ("revlv", col("revlv_string")),
    ("rshty", col("rshty_string")),
    ("rshid", col("rshid_string")),
    ("rsnty", col("rsnty_string")),
    ("rsnid", col("rsnid_string")),
    ("nauterm", col("nauterm_string")),
    ("naucost", col("naucost_string")),
    ("stufe", col("stufe_decimal_2_0")),
    ("wegxx", col("wegxx_decimal_4_0")),
    ("vwegx", col("vwegx_decimal_4_0")),
    ("arsnr", col("arsnr_string")),
    ("arsps", col("arsps_string")),
    ("maufnr", col("maufnr_string")),
    ("lknot", col("lknot_string")),
    ("rknot", col("rknot_string")),
    ("prodnet", col("prodnet_string")),
    ("iasmg", col("iasmg_decimal_13_3")),
    ("abarb", col("abarb_string")),
    ("aufnt", col("aufnt_string")),
    ("aufpt", col("aufpt_string")),
    ("aplzt", col("aplzt_string")),
    ("no_disp", col("no_disp_string")),
    ("csplit", col("csplit_string")),
    ("aennr", col("aennr_string")),
    ("cy_seqnr", col("cy_seqnr_string")),
    ("breaks", col("breaks_string")),
    ("vorgz_trm", col("vorgz_trm_decimal_6_3")),
    ("sichz_trm", col("sichz_trm_decimal_6_3")),
    ("trmdt", col("trmdt_string")),
    ("gluzp", col("gluzp_string")),
    ("gsuzp", col("gsuzp_string")),
    ("gsuzi", col("gsuzi_string")),
    ("geuzi", col("geuzi_string")),
    ("glupp", col("glupp_string")),
    ("gsupp", col("gsupp_string")),
    ("glups", col("glups_string")),
    ("gsups", col("gsups_string")),
    ("chsch", col("chsch_string")),
    ("kapt_vorgz", col("kapt_vorgz_string")),
    ("kapt_sichz", col("kapt_sichz_string")),
    ("lead_aufnr", col("lead_aufnr_string")),
    ("pnetstartd", col("pnetstartd_string")),
    ("pnetstartt", col("pnetstartt_string")),
    ("pnetendd", col("pnetendd_string")),
    ("pnetendt", col("pnetendt_string")),
    ("kbed", col("kbed_string")),
    ("kkalkr", col("kkalkr_string")),
    ("sfcpf", col("sfcpf_string")),
    ("rmnga", col("rmnga_decimal_13_3")),
    ("gsbtr", col("gsbtr_string")),
    ("vfmng", col("vfmng_decimal_13_3")),
    ("nopcost", col("nopcost_string")),
    ("netzkont", col("netzkont_string")),
    ("atrkz", col("atrkz_string")),
    ("objtype", col("objtype_string")),
    ("ch_proc", col("ch_proc_string")),
    ("kapversa", col("kapversa_string")),
    ("colordproc", col("colordproc_string")),
    ("kzerb", col("kzerb_string")),
    ("conf_key", col("conf_key_string")),
    ("st_arbid", col("st_arbid_string")),
    ("vsnmr_v", col("vsnmr_v_string")),
    ("terhw", col("terhw_string")),
    ("splstat", col("splstat_string")),
    ("costupd", col("costupd_string")),
    ("max_gamng", col("max_gamng_decimal_13_3")),
    ("mes_routingid", col("mes_routingid_string")),
    ("adpsp", col("adpsp_string")),
    ("rmanr", col("rmanr_string")),
    ("posnr_rma", col("posnr_rma_string")),
    ("posnv_rma", col("posnv_rma_string")),
    ("cfb_maxlz", col("cfb_maxlz_decimal_5_0")),
    ("cfb_lzeih", col("cfb_lzeih_string")),
    ("cfb_adtdays", col("cfb_adtdays_decimal_4_0")),
    ("cfb_datofm", col("cfb_datofm_string")),
    ("cfb_bbdpi", col("cfb_bbdpi_string")),
    ("oihantyp", col("oihantyp_string")),
    ("mill_ratio", coalesce(col("mill_ratio_int"), lit(0))),
    ("bmeins", col("bmeins_string")),
    ("bmenge", col("bmenge_decimal_13_3")),
    ("mill_oc_zuskz", col("mill_oc_zuskz_string"))
  )
}
