// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_epp

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_afvv(
    @PK mandt: String,
    @PK aufpl: String,
    @PK aplzl: String,
    meinh: String,
    @Decimal(5, 0) umren: BigDecimal,
    @Decimal(5, 0) umrez: BigDecimal,
    @Decimal(13, 3) bmsch: BigDecimal,
    @Decimal(9, 3) zmerh: BigDecimal,
    zeier: String,
    vge01: String,
    @Decimal(9, 3) vgw01: BigDecimal,
    vge02: String,
    @Decimal(9, 3) vgw02: BigDecimal,
    vge03: String,
    @Decimal(9, 3) vgw03: BigDecimal,
    vge04: String,
    @Decimal(9, 3) vgw04: BigDecimal,
    vge05: String,
    @Decimal(9, 3) vgw05: BigDecimal,
    vge06: String,
    @Decimal(9, 3) vgw06: BigDecimal,
    zeimu: String,
    @Decimal(9, 3) zminu: BigDecimal,
    @Decimal(13, 3) minwe: BigDecimal,
    zeimb: String,
    @Decimal(9, 3) zminb: BigDecimal,
    zeilm: String,
    @Decimal(9, 3) zlmax: BigDecimal,
    zeilp: String,
    @Decimal(9, 3) zlpro: BigDecimal,
    zeiwn: String,
    @Decimal(9, 3) zwnor: BigDecimal,
    zeiwm: String,
    @Decimal(9, 3) zwmin: BigDecimal,
    zeitn: String,
    @Decimal(9, 3) ztnor: BigDecimal,
    zeitm: String,
    @Decimal(9, 3) ztmin: BigDecimal,
    @Decimal(3, 0) plifz: BigDecimal,
    @Decimal(5, 1) dauno: BigDecimal,
    daune: String,
    @Decimal(5, 1) daumi: BigDecimal,
    daume: String,
    einsa: String,
    einse: String,
    @Decimal(7, 1) arbei: BigDecimal,
    arbeh: String,
    @Decimal(13, 3) mgvrg: BigDecimal,
    @Decimal(13, 3) asvrg: BigDecimal,
    @Decimal(13, 3) lmnga: BigDecimal,
    @Decimal(13, 3) xmnga: BigDecimal,
    @Decimal(13, 3) gmnga: BigDecimal,
    @Decimal(13, 3) ism01: BigDecimal,
    @Decimal(13, 3) ism02: BigDecimal,
    @Decimal(13, 3) ism03: BigDecimal,
    @Decimal(13, 3) ism04: BigDecimal,
    @Decimal(13, 3) ism05: BigDecimal,
    @Decimal(13, 3) ism06: BigDecimal,
    @Decimal(13, 3) ismnw: BigDecimal,
    fsavd: String,
    fsavz: String,
    fssbd: String,
    fssbz: String,
    fssad: String,
    fssaz: String,
    fsedd: String,
    fsedz: String,
    fssld: String,
    fsslz: String,
    fseld: String,
    fselz: String,
    ssavd: String,
    ssavz: String,
    sssbd: String,
    sssbz: String,
    sssad: String,
    sssaz: String,
    ssedd: String,
    ssedz: String,
    sssld: String,
    ssslz: String,
    sseld: String,
    sselz: String,
    isavd: String,
    ieavd: String,
    isdd: String,
    isdz: String,
    ierd: String,
    ierz: String,
    isbd: String,
    isbz: String,
    iebd: String,
    iebz: String,
    isad: String,
    isaz: String,
    iedd: String,
    iedz: String,
    pedd: String,
    pedz: String,
    @Decimal(3, 0) puffr: BigDecimal,
    @Decimal(3, 0) pufgs: BigDecimal,
    ntanf: String,
    ntanz: String,
    ntend: String,
    ntenz: String,
    ewstd: String,
    ewstz: String,
    ewend: String,
    ewenz: String,
    @Decimal(5, 1) ewdan: BigDecimal,
    ewdne: String,
    @Decimal(5, 1) ewdam: BigDecimal,
    ewdme: String,
    ewste: String,
    ewsta: String,
    wartz: BoxedDouble,
    wrtze: String,
    ruest: BoxedDouble,
    rstze: String,
    bearz: BoxedDouble,
    beaze: String,
    abrue: BoxedDouble,
    aruze: String,
    liegz: BoxedDouble,
    ligze: String,
    tranz: BoxedDouble,
    traze: String,
    @Decimal(9, 3) iserh: BigDecimal,
    @Decimal(9, 3) ofm01: BigDecimal,
    @Decimal(9, 3) ofm02: BigDecimal,
    @Decimal(9, 3) ofm03: BigDecimal,
    @Decimal(9, 3) ofm04: BigDecimal,
    @Decimal(9, 3) ofm05: BigDecimal,
    @Decimal(9, 3) ofm06: BigDecimal,
    @Decimal(7, 1) ofmnw: BigDecimal,
    bzoffb: String,
    ehoffb: String,
    @Decimal(5, 0) offstb: BigDecimal,
    @Decimal(5, 0) offste: BigDecimal,
    bzoffe: String,
    ehoffe: String,
    fpavd: String,
    fpavz: String,
    fpedd: String,
    fpedz: String,
    spavd: String,
    spavz: String,
    spedd: String,
    spedz: String,
    beazp: String,
    @Decimal(3, 0) pufgp: BigDecimal,
    @Decimal(3, 0) puffp: BigDecimal,
    bearp: BoxedDouble,
    epanf: String,
    epanz: String,
    epend: String,
    epenz: String,
    @Decimal(5, 1) pdau: BigDecimal,
    pdae: String,
    knote: String,
    vstzw: String,
    vstga: String,
    qrastzeht: String,
    @Decimal(5, 2) qrastzfak: BigDecimal,
    @Decimal(13, 3) qrastmeng: BigDecimal,
    qrastereh: String,
    @Decimal(3, 0) aufkt: BigDecimal,
    @Decimal(13, 3) rmnga: BigDecimal,
    ile01: String,
    ile02: String,
    ile03: String,
    ile04: String,
    ile05: String,
    ile06: String,
    @Decimal(5, 3) rwfak: BigDecimal,
    @Decimal(13, 3) iprz1: BigDecimal,
    ipre1: String,
    iprk1: String,
    takt: String,
    @Decimal(13, 3) oprz1: BigDecimal,
    opre1: String,
    pspm_indicator: String,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String
) extends Entity

object afvv
    extends TableSpec[E_afvv](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[sr_raw.ct_gbl_epp.E_afvv] {
  override def sourceTableSpec: TableSpec[sr_raw.ct_gbl_epp.E_afvv] = sr_raw.ct_gbl_epp.afvv
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("mandt", col("mandt_string")),
    ("aufpl", col("aufpl_string")),
    ("aplzl", col("aplzl_string")),
    ("meinh", col("meinh_string")),
    ("umren", col("umren_decimal_5_0")),
    ("umrez", col("umrez_decimal_5_0")),
    ("bmsch", col("bmsch_decimal_13_3")),
    ("zmerh", col("zmerh_decimal_9_3")),
    ("zeier", col("zeier_string")),
    ("vge01", col("vge01_string")),
    ("vgw01", col("vgw01_decimal_9_3")),
    ("vge02", col("vge02_string")),
    ("vgw02", col("vgw02_decimal_9_3")),
    ("vge03", col("vge03_string")),
    ("vgw03", col("vgw03_decimal_9_3")),
    ("vge04", col("vge04_string")),
    ("vgw04", col("vgw04_decimal_9_3")),
    ("vge05", col("vge05_string")),
    ("vgw05", col("vgw05_decimal_9_3")),
    ("vge06", col("vge06_string")),
    ("vgw06", col("vgw06_decimal_9_3")),
    ("zeimu", col("zeimu_string")),
    ("zminu", col("zminu_decimal_9_3")),
    ("minwe", col("minwe_decimal_13_3")),
    ("zeimb", col("zeimb_string")),
    ("zminb", col("zminb_decimal_9_3")),
    ("zeilm", col("zeilm_string")),
    ("zlmax", col("zlmax_decimal_9_3")),
    ("zeilp", col("zeilp_string")),
    ("zlpro", col("zlpro_decimal_9_3")),
    ("zeiwn", col("zeiwn_string")),
    ("zwnor", col("zwnor_decimal_9_3")),
    ("zeiwm", col("zeiwm_string")),
    ("zwmin", col("zwmin_decimal_9_3")),
    ("zeitn", col("zeitn_string")),
    ("ztnor", col("ztnor_decimal_9_3")),
    ("zeitm", col("zeitm_string")),
    ("ztmin", col("ztmin_decimal_9_3")),
    ("plifz", col("plifz_decimal_3_0")),
    ("dauno", col("dauno_decimal_5_1")),
    ("daune", col("daune_string")),
    ("daumi", col("daumi_decimal_5_1")),
    ("daume", col("daume_string")),
    ("einsa", col("einsa_string")),
    ("einse", col("einse_string")),
    ("arbei", col("arbei_decimal_7_1")),
    ("arbeh", col("arbeh_string")),
    ("mgvrg", col("mgvrg_decimal_13_3")),
    ("asvrg", col("asvrg_decimal_13_3")),
    ("lmnga", col("lmnga_decimal_13_3")),
    ("xmnga", col("xmnga_decimal_13_3")),
    ("gmnga", col("gmnga_decimal_13_3")),
    ("ism01", col("ism01_decimal_13_3")),
    ("ism02", col("ism02_decimal_13_3")),
    ("ism03", col("ism03_decimal_13_3")),
    ("ism04", col("ism04_decimal_13_3")),
    ("ism05", col("ism05_decimal_13_3")),
    ("ism06", col("ism06_decimal_13_3")),
    ("ismnw", col("ismnw_decimal_13_3")),
    ("fsavd", col("fsavd_string")),
    ("fsavz", col("fsavz_string")),
    ("fssbd", col("fssbd_string")),
    ("fssbz", col("fssbz_string")),
    ("fssad", col("fssad_string")),
    ("fssaz", col("fssaz_string")),
    ("fsedd", col("fsedd_string")),
    ("fsedz", col("fsedz_string")),
    ("fssld", col("fssld_string")),
    ("fsslz", col("fsslz_string")),
    ("fseld", col("fseld_string")),
    ("fselz", col("fselz_string")),
    ("ssavd", col("ssavd_string")),
    ("ssavz", col("ssavz_string")),
    ("sssbd", col("sssbd_string")),
    ("sssbz", col("sssbz_string")),
    ("sssad", col("sssad_string")),
    ("sssaz", col("sssaz_string")),
    ("ssedd", col("ssedd_string")),
    ("ssedz", col("ssedz_string")),
    ("sssld", col("sssld_string")),
    ("ssslz", col("ssslz_string")),
    ("sseld", col("sseld_string")),
    ("sselz", col("sselz_string")),
    ("isavd", col("isavd_string")),
    ("ieavd", col("ieavd_string")),
    ("isdd", col("isdd_string")),
    ("isdz", col("isdz_string")),
    ("ierd", col("ierd_string")),
    ("ierz", col("ierz_string")),
    ("isbd", col("isbd_string")),
    ("isbz", col("isbz_string")),
    ("iebd", col("iebd_string")),
    ("iebz", col("iebz_string")),
    ("isad", col("isad_string")),
    ("isaz", col("isaz_string")),
    ("iedd", col("iedd_string")),
    ("iedz", col("iedz_string")),
    ("pedd", col("pedd_string")),
    ("pedz", col("pedz_string")),
    ("puffr", col("puffr_decimal_3_0")),
    ("pufgs", col("pufgs_decimal_3_0")),
    ("ntanf", col("ntanf_string")),
    ("ntanz", col("ntanz_string")),
    ("ntend", col("ntend_string")),
    ("ntenz", col("ntenz_string")),
    ("ewstd", col("ewstd_string")),
    ("ewstz", col("ewstz_string")),
    ("ewend", col("ewend_string")),
    ("ewenz", col("ewenz_string")),
    ("ewdan", col("ewdan_decimal_5_1")),
    ("ewdne", col("ewdne_string")),
    ("ewdam", col("ewdam_decimal_5_1")),
    ("ewdme", col("ewdme_string")),
    ("ewste", col("ewste_string")),
    ("ewsta", col("ewsta_string")),
    ("wartz", col("wartz_double")),
    ("wrtze", col("wrtze_string")),
    ("ruest", col("ruest_double")),
    ("rstze", col("rstze_string")),
    ("bearz", col("bearz_double")),
    ("beaze", col("beaze_string")),
    ("abrue", col("abrue_double")),
    ("aruze", col("aruze_string")),
    ("liegz", col("liegz_double")),
    ("ligze", col("ligze_string")),
    ("tranz", col("tranz_double")),
    ("traze", col("traze_string")),
    ("iserh", col("iserh_decimal_9_3")),
    ("ofm01", col("ofm01_decimal_9_3")),
    ("ofm02", col("ofm02_decimal_9_3")),
    ("ofm03", col("ofm03_decimal_9_3")),
    ("ofm04", col("ofm04_decimal_9_3")),
    ("ofm05", col("ofm05_decimal_9_3")),
    ("ofm06", col("ofm06_decimal_9_3")),
    ("ofmnw", col("ofmnw_decimal_7_1")),
    ("bzoffb", col("bzoffb_string")),
    ("ehoffb", col("ehoffb_string")),
    ("offstb", col("offstb_decimal_5_0")),
    ("offste", col("offste_decimal_5_0")),
    ("bzoffe", col("bzoffe_string")),
    ("ehoffe", col("ehoffe_string")),
    ("fpavd", col("fpavd_string")),
    ("fpavz", col("fpavz_string")),
    ("fpedd", col("fpedd_string")),
    ("fpedz", col("fpedz_string")),
    ("spavd", col("spavd_string")),
    ("spavz", col("spavz_string")),
    ("spedd", col("spedd_string")),
    ("spedz", col("spedz_string")),
    ("beazp", col("beazp_string")),
    ("pufgp", col("pufgp_decimal_3_0")),
    ("puffp", col("puffp_decimal_3_0")),
    ("bearp", col("bearp_double")),
    ("epanf", col("epanf_string")),
    ("epanz", col("epanz_string")),
    ("epend", col("epend_string")),
    ("epenz", col("epenz_string")),
    ("pdau", col("pdau_decimal_5_1")),
    ("pdae", col("pdae_string")),
    ("knote", col("knote_string")),
    ("vstzw", col("vstzw_string")),
    ("vstga", col("vstga_string")),
    ("qrastzeht", col("qrastzeht_string")),
    ("qrastzfak", col("qrastzfak_decimal_5_2")),
    ("qrastmeng", col("qrastmeng_decimal_13_3")),
    ("qrastereh", col("qrastereh_string")),
    ("aufkt", col("aufkt_decimal_3_0")),
    ("rmnga", col("rmnga_decimal_13_3")),
    ("ile01", col("ile01_string")),
    ("ile02", col("ile02_string")),
    ("ile03", col("ile03_string")),
    ("ile04", col("ile04_string")),
    ("ile05", col("ile05_string")),
    ("ile06", col("ile06_string")),
    ("rwfak", col("rwfak_decimal_5_3")),
    ("iprz1", col("iprz1_decimal_13_3")),
    ("ipre1", col("ipre1_string")),
    ("iprk1", col("iprk1_string")),
    ("takt", col("takt_string")),
    ("oprz1", col("oprz1_decimal_13_3")),
    ("opre1", col("opre1_string")),
    ("pspm_indicator", col("pspm_indicator_string"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_afvv(prefix: String) extends ColumnWithNameAccessor {
  val mandt: ColumnWithName = ColumnWithName(prefix + "mandt")
  val aufpl: ColumnWithName = ColumnWithName(prefix + "aufpl")
  val aplzl: ColumnWithName = ColumnWithName(prefix + "aplzl")
  val meinh: ColumnWithName = ColumnWithName(prefix + "meinh")
  val umren: ColumnWithName = ColumnWithName(prefix + "umren")
  val umrez: ColumnWithName = ColumnWithName(prefix + "umrez")
  val bmsch: ColumnWithName = ColumnWithName(prefix + "bmsch")
  val zmerh: ColumnWithName = ColumnWithName(prefix + "zmerh")
  val zeier: ColumnWithName = ColumnWithName(prefix + "zeier")
  val vge01: ColumnWithName = ColumnWithName(prefix + "vge01")
  val vgw01: ColumnWithName = ColumnWithName(prefix + "vgw01")
  val vge02: ColumnWithName = ColumnWithName(prefix + "vge02")
  val vgw02: ColumnWithName = ColumnWithName(prefix + "vgw02")
  val vge03: ColumnWithName = ColumnWithName(prefix + "vge03")
  val vgw03: ColumnWithName = ColumnWithName(prefix + "vgw03")
  val vge04: ColumnWithName = ColumnWithName(prefix + "vge04")
  val vgw04: ColumnWithName = ColumnWithName(prefix + "vgw04")
  val vge05: ColumnWithName = ColumnWithName(prefix + "vge05")
  val vgw05: ColumnWithName = ColumnWithName(prefix + "vgw05")
  val vge06: ColumnWithName = ColumnWithName(prefix + "vge06")
  val vgw06: ColumnWithName = ColumnWithName(prefix + "vgw06")
  val zeimu: ColumnWithName = ColumnWithName(prefix + "zeimu")
  val zminu: ColumnWithName = ColumnWithName(prefix + "zminu")
  val minwe: ColumnWithName = ColumnWithName(prefix + "minwe")
  val zeimb: ColumnWithName = ColumnWithName(prefix + "zeimb")
  val zminb: ColumnWithName = ColumnWithName(prefix + "zminb")
  val zeilm: ColumnWithName = ColumnWithName(prefix + "zeilm")
  val zlmax: ColumnWithName = ColumnWithName(prefix + "zlmax")
  val zeilp: ColumnWithName = ColumnWithName(prefix + "zeilp")
  val zlpro: ColumnWithName = ColumnWithName(prefix + "zlpro")
  val zeiwn: ColumnWithName = ColumnWithName(prefix + "zeiwn")
  val zwnor: ColumnWithName = ColumnWithName(prefix + "zwnor")
  val zeiwm: ColumnWithName = ColumnWithName(prefix + "zeiwm")
  val zwmin: ColumnWithName = ColumnWithName(prefix + "zwmin")
  val zeitn: ColumnWithName = ColumnWithName(prefix + "zeitn")
  val ztnor: ColumnWithName = ColumnWithName(prefix + "ztnor")
  val zeitm: ColumnWithName = ColumnWithName(prefix + "zeitm")
  val ztmin: ColumnWithName = ColumnWithName(prefix + "ztmin")
  val plifz: ColumnWithName = ColumnWithName(prefix + "plifz")
  val dauno: ColumnWithName = ColumnWithName(prefix + "dauno")
  val daune: ColumnWithName = ColumnWithName(prefix + "daune")
  val daumi: ColumnWithName = ColumnWithName(prefix + "daumi")
  val daume: ColumnWithName = ColumnWithName(prefix + "daume")
  val einsa: ColumnWithName = ColumnWithName(prefix + "einsa")
  val einse: ColumnWithName = ColumnWithName(prefix + "einse")
  val arbei: ColumnWithName = ColumnWithName(prefix + "arbei")
  val arbeh: ColumnWithName = ColumnWithName(prefix + "arbeh")
  val mgvrg: ColumnWithName = ColumnWithName(prefix + "mgvrg")
  val asvrg: ColumnWithName = ColumnWithName(prefix + "asvrg")
  val lmnga: ColumnWithName = ColumnWithName(prefix + "lmnga")
  val xmnga: ColumnWithName = ColumnWithName(prefix + "xmnga")
  val gmnga: ColumnWithName = ColumnWithName(prefix + "gmnga")
  val ism01: ColumnWithName = ColumnWithName(prefix + "ism01")
  val ism02: ColumnWithName = ColumnWithName(prefix + "ism02")
  val ism03: ColumnWithName = ColumnWithName(prefix + "ism03")
  val ism04: ColumnWithName = ColumnWithName(prefix + "ism04")
  val ism05: ColumnWithName = ColumnWithName(prefix + "ism05")
  val ism06: ColumnWithName = ColumnWithName(prefix + "ism06")
  val ismnw: ColumnWithName = ColumnWithName(prefix + "ismnw")
  val fsavd: ColumnWithName = ColumnWithName(prefix + "fsavd")
  val fsavz: ColumnWithName = ColumnWithName(prefix + "fsavz")
  val fssbd: ColumnWithName = ColumnWithName(prefix + "fssbd")
  val fssbz: ColumnWithName = ColumnWithName(prefix + "fssbz")
  val fssad: ColumnWithName = ColumnWithName(prefix + "fssad")
  val fssaz: ColumnWithName = ColumnWithName(prefix + "fssaz")
  val fsedd: ColumnWithName = ColumnWithName(prefix + "fsedd")
  val fsedz: ColumnWithName = ColumnWithName(prefix + "fsedz")
  val fssld: ColumnWithName = ColumnWithName(prefix + "fssld")
  val fsslz: ColumnWithName = ColumnWithName(prefix + "fsslz")
  val fseld: ColumnWithName = ColumnWithName(prefix + "fseld")
  val fselz: ColumnWithName = ColumnWithName(prefix + "fselz")
  val ssavd: ColumnWithName = ColumnWithName(prefix + "ssavd")
  val ssavz: ColumnWithName = ColumnWithName(prefix + "ssavz")
  val sssbd: ColumnWithName = ColumnWithName(prefix + "sssbd")
  val sssbz: ColumnWithName = ColumnWithName(prefix + "sssbz")
  val sssad: ColumnWithName = ColumnWithName(prefix + "sssad")
  val sssaz: ColumnWithName = ColumnWithName(prefix + "sssaz")
  val ssedd: ColumnWithName = ColumnWithName(prefix + "ssedd")
  val ssedz: ColumnWithName = ColumnWithName(prefix + "ssedz")
  val sssld: ColumnWithName = ColumnWithName(prefix + "sssld")
  val ssslz: ColumnWithName = ColumnWithName(prefix + "ssslz")
  val sseld: ColumnWithName = ColumnWithName(prefix + "sseld")
  val sselz: ColumnWithName = ColumnWithName(prefix + "sselz")
  val isavd: ColumnWithName = ColumnWithName(prefix + "isavd")
  val ieavd: ColumnWithName = ColumnWithName(prefix + "ieavd")
  val isdd: ColumnWithName = ColumnWithName(prefix + "isdd")
  val isdz: ColumnWithName = ColumnWithName(prefix + "isdz")
  val ierd: ColumnWithName = ColumnWithName(prefix + "ierd")
  val ierz: ColumnWithName = ColumnWithName(prefix + "ierz")
  val isbd: ColumnWithName = ColumnWithName(prefix + "isbd")
  val isbz: ColumnWithName = ColumnWithName(prefix + "isbz")
  val iebd: ColumnWithName = ColumnWithName(prefix + "iebd")
  val iebz: ColumnWithName = ColumnWithName(prefix + "iebz")
  val isad: ColumnWithName = ColumnWithName(prefix + "isad")
  val isaz: ColumnWithName = ColumnWithName(prefix + "isaz")
  val iedd: ColumnWithName = ColumnWithName(prefix + "iedd")
  val iedz: ColumnWithName = ColumnWithName(prefix + "iedz")
  val pedd: ColumnWithName = ColumnWithName(prefix + "pedd")
  val pedz: ColumnWithName = ColumnWithName(prefix + "pedz")
  val puffr: ColumnWithName = ColumnWithName(prefix + "puffr")
  val pufgs: ColumnWithName = ColumnWithName(prefix + "pufgs")
  val ntanf: ColumnWithName = ColumnWithName(prefix + "ntanf")
  val ntanz: ColumnWithName = ColumnWithName(prefix + "ntanz")
  val ntend: ColumnWithName = ColumnWithName(prefix + "ntend")
  val ntenz: ColumnWithName = ColumnWithName(prefix + "ntenz")
  val ewstd: ColumnWithName = ColumnWithName(prefix + "ewstd")
  val ewstz: ColumnWithName = ColumnWithName(prefix + "ewstz")
  val ewend: ColumnWithName = ColumnWithName(prefix + "ewend")
  val ewenz: ColumnWithName = ColumnWithName(prefix + "ewenz")
  val ewdan: ColumnWithName = ColumnWithName(prefix + "ewdan")
  val ewdne: ColumnWithName = ColumnWithName(prefix + "ewdne")
  val ewdam: ColumnWithName = ColumnWithName(prefix + "ewdam")
  val ewdme: ColumnWithName = ColumnWithName(prefix + "ewdme")
  val ewste: ColumnWithName = ColumnWithName(prefix + "ewste")
  val ewsta: ColumnWithName = ColumnWithName(prefix + "ewsta")
  val wartz: ColumnWithName = ColumnWithName(prefix + "wartz")
  val wrtze: ColumnWithName = ColumnWithName(prefix + "wrtze")
  val ruest: ColumnWithName = ColumnWithName(prefix + "ruest")
  val rstze: ColumnWithName = ColumnWithName(prefix + "rstze")
  val bearz: ColumnWithName = ColumnWithName(prefix + "bearz")
  val beaze: ColumnWithName = ColumnWithName(prefix + "beaze")
  val abrue: ColumnWithName = ColumnWithName(prefix + "abrue")
  val aruze: ColumnWithName = ColumnWithName(prefix + "aruze")
  val liegz: ColumnWithName = ColumnWithName(prefix + "liegz")
  val ligze: ColumnWithName = ColumnWithName(prefix + "ligze")
  val tranz: ColumnWithName = ColumnWithName(prefix + "tranz")
  val traze: ColumnWithName = ColumnWithName(prefix + "traze")
  val iserh: ColumnWithName = ColumnWithName(prefix + "iserh")
  val ofm01: ColumnWithName = ColumnWithName(prefix + "ofm01")
  val ofm02: ColumnWithName = ColumnWithName(prefix + "ofm02")
  val ofm03: ColumnWithName = ColumnWithName(prefix + "ofm03")
  val ofm04: ColumnWithName = ColumnWithName(prefix + "ofm04")
  val ofm05: ColumnWithName = ColumnWithName(prefix + "ofm05")
  val ofm06: ColumnWithName = ColumnWithName(prefix + "ofm06")
  val ofmnw: ColumnWithName = ColumnWithName(prefix + "ofmnw")
  val bzoffb: ColumnWithName = ColumnWithName(prefix + "bzoffb")
  val ehoffb: ColumnWithName = ColumnWithName(prefix + "ehoffb")
  val offstb: ColumnWithName = ColumnWithName(prefix + "offstb")
  val offste: ColumnWithName = ColumnWithName(prefix + "offste")
  val bzoffe: ColumnWithName = ColumnWithName(prefix + "bzoffe")
  val ehoffe: ColumnWithName = ColumnWithName(prefix + "ehoffe")
  val fpavd: ColumnWithName = ColumnWithName(prefix + "fpavd")
  val fpavz: ColumnWithName = ColumnWithName(prefix + "fpavz")
  val fpedd: ColumnWithName = ColumnWithName(prefix + "fpedd")
  val fpedz: ColumnWithName = ColumnWithName(prefix + "fpedz")
  val spavd: ColumnWithName = ColumnWithName(prefix + "spavd")
  val spavz: ColumnWithName = ColumnWithName(prefix + "spavz")
  val spedd: ColumnWithName = ColumnWithName(prefix + "spedd")
  val spedz: ColumnWithName = ColumnWithName(prefix + "spedz")
  val beazp: ColumnWithName = ColumnWithName(prefix + "beazp")
  val pufgp: ColumnWithName = ColumnWithName(prefix + "pufgp")
  val puffp: ColumnWithName = ColumnWithName(prefix + "puffp")
  val bearp: ColumnWithName = ColumnWithName(prefix + "bearp")
  val epanf: ColumnWithName = ColumnWithName(prefix + "epanf")
  val epanz: ColumnWithName = ColumnWithName(prefix + "epanz")
  val epend: ColumnWithName = ColumnWithName(prefix + "epend")
  val epenz: ColumnWithName = ColumnWithName(prefix + "epenz")
  val pdau: ColumnWithName = ColumnWithName(prefix + "pdau")
  val pdae: ColumnWithName = ColumnWithName(prefix + "pdae")
  val knote: ColumnWithName = ColumnWithName(prefix + "knote")
  val vstzw: ColumnWithName = ColumnWithName(prefix + "vstzw")
  val vstga: ColumnWithName = ColumnWithName(prefix + "vstga")
  val qrastzeht: ColumnWithName = ColumnWithName(prefix + "qrastzeht")
  val qrastzfak: ColumnWithName = ColumnWithName(prefix + "qrastzfak")
  val qrastmeng: ColumnWithName = ColumnWithName(prefix + "qrastmeng")
  val qrastereh: ColumnWithName = ColumnWithName(prefix + "qrastereh")
  val aufkt: ColumnWithName = ColumnWithName(prefix + "aufkt")
  val rmnga: ColumnWithName = ColumnWithName(prefix + "rmnga")
  val ile01: ColumnWithName = ColumnWithName(prefix + "ile01")
  val ile02: ColumnWithName = ColumnWithName(prefix + "ile02")
  val ile03: ColumnWithName = ColumnWithName(prefix + "ile03")
  val ile04: ColumnWithName = ColumnWithName(prefix + "ile04")
  val ile05: ColumnWithName = ColumnWithName(prefix + "ile05")
  val ile06: ColumnWithName = ColumnWithName(prefix + "ile06")
  val rwfak: ColumnWithName = ColumnWithName(prefix + "rwfak")
  val iprz1: ColumnWithName = ColumnWithName(prefix + "iprz1")
  val ipre1: ColumnWithName = ColumnWithName(prefix + "ipre1")
  val iprk1: ColumnWithName = ColumnWithName(prefix + "iprk1")
  val takt: ColumnWithName = ColumnWithName(prefix + "takt")
  val oprz1: ColumnWithName = ColumnWithName(prefix + "oprz1")
  val opre1: ColumnWithName = ColumnWithName(prefix + "opre1")
  val pspm_indicator: ColumnWithName = ColumnWithName(prefix + "pspm_indicator")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
}

object C_afvv extends C_afvv("") {
  def as(alias: String): C_afvv = new C_afvv(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
