// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_epp

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_epp.{crhd => sr_raw_crhd}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrCrhd(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK objty: String,
    @PK objid: String,
    begda: String,
    endda: String,
    aedat_grnd: String,
    aenam_grnd: String,
    aedat_vora: String,
    aenam_vora: String,
    aedat_term: String,
    aenam_term: String,
    aedat_tech: String,
    aenam_tech: String,
    arbpl: String,
    werks: String,
    verwe: String,
    lvorm: String,
    par01: String,
    par02: String,
    par03: String,
    par04: String,
    par05: String,
    par06: String,
    paru1: String,
    paru2: String,
    paru3: String,
    paru4: String,
    paru5: String,
    paru6: String,
    @Decimal(9, 3) parv1: java.math.BigDecimal,
    @Decimal(9, 3) parv2: java.math.BigDecimal,
    @Decimal(9, 3) parv3: java.math.BigDecimal,
    @Decimal(9, 3) parv4: java.math.BigDecimal,
    @Decimal(9, 3) parv5: java.math.BigDecimal,
    @Decimal(9, 3) parv6: java.math.BigDecimal,
    planv: String,
    stand: String,
    veran: String,
    vgwts: String,
    vgm01: String,
    vgm02: String,
    vgm03: String,
    vgm04: String,
    vgm05: String,
    vgm06: String,
    xdefa: String,
    xkost: String,
    xsprr: String,
    xterm: String,
    zgr01: String,
    zgr02: String,
    zgr03: String,
    zgr04: String,
    zgr05: String,
    zgr06: String,
    ktsch: String,
    @Decimal(3, 0) loanz: java.math.BigDecimal,
    loart: String,
    logrp: String,
    qualf: String,
    rasch: String,
    steus: String,
    vge01: String,
    vge02: String,
    vge03: String,
    vge04: String,
    vge05: String,
    vge06: String,
    ktsch_ref: String,
    loart_ref: String,
    loanz_ref: String,
    logrp_ref: String,
    qualf_ref: String,
    rasch_ref: String,
    steus_ref: String,
    fort1: String,
    fort2: String,
    fort3: String,
    kapid: String,
    ortgr: String,
    zeiwn: String,
    @Decimal(9, 3) zwnor: java.math.BigDecimal,
    zeiwm: String,
    @Decimal(9, 3) zwmin: java.math.BigDecimal,
    formr: String,
    matyp: String,
    cplgr: String,
    sortb: String,
    @Decimal(3, 1) mtrvp: java.math.BigDecimal,
    @Decimal(3, 1) mtmvp: java.math.BigDecimal,
    @Decimal(3, 1) mtpvp: java.math.BigDecimal,
    rsanz: String,
    pdest: String,
    hroid: String,
    fortn: String,
    zgr01_ref: String,
    zgr02_ref: String,
    zgr03_ref: String,
    zgr04_ref: String,
    zgr05_ref: String,
    zgr06_ref: String,
    steus_c: String,
    steus_i: String,
    steus_n: String,
    steus_q: String,
    ruzus: String,
    rsanz_ref: String,
    hr: String,
    prvbe: String,
    subsys: String,
    bdegr: String,
    rgekz: String,
    hrtyp: String,
    slwid: String,
    lifnr: String,
    slwid_ref: String,
    lifnr_ref: String,
    vgarb: String,
    vgdim: String,
    hrplvar: String,
    vgdau: String,
    stobj: String,
    resgr: String,
    lgort_res: String,
    mixmat: String,
    istbed_kz: String,
    srtype: String,
    sntype: String
) extends Entity

object crhd extends TableSpec[SrCrhd] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_crhd] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_crhd] = sr_raw_crhd

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("objty", coalesce(col("objty_string"), lit(""))),
    ("objid", coalesce(col("objid_string"), lit(""))),
    ("begda", col("begda_string")),
    ("endda", col("endda_string")),
    ("aedat_grnd", col("aedat_grnd_string")),
    ("aenam_grnd", col("aenam_grnd_string")),
    ("aedat_vora", col("aedat_vora_string")),
    ("aenam_vora", col("aenam_vora_string")),
    ("aedat_term", col("aedat_term_string")),
    ("aenam_term", col("aenam_term_string")),
    ("aedat_tech", col("aedat_tech_string")),
    ("aenam_tech", col("aenam_tech_string")),
    ("arbpl", col("arbpl_string")),
    ("werks", col("werks_string")),
    ("verwe", col("verwe_string")),
    ("lvorm", col("lvorm_string")),
    ("par01", col("par01_string")),
    ("par02", col("par02_string")),
    ("par03", col("par03_string")),
    ("par04", col("par04_string")),
    ("par05", col("par05_string")),
    ("par06", col("par06_string")),
    ("paru1", col("paru1_string")),
    ("paru2", col("paru2_string")),
    ("paru3", col("paru3_string")),
    ("paru4", col("paru4_string")),
    ("paru5", col("paru5_string")),
    ("paru6", col("paru6_string")),
    ("parv1", col("parv1_decimal_9_3")),
    ("parv2", col("parv2_decimal_9_3")),
    ("parv3", col("parv3_decimal_9_3")),
    ("parv4", col("parv4_decimal_9_3")),
    ("parv5", col("parv5_decimal_9_3")),
    ("parv6", col("parv6_decimal_9_3")),
    ("planv", col("planv_string")),
    ("stand", col("stand_string")),
    ("veran", col("veran_string")),
    ("vgwts", col("vgwts_string")),
    ("vgm01", col("vgm01_string")),
    ("vgm02", col("vgm02_string")),
    ("vgm03", col("vgm03_string")),
    ("vgm04", col("vgm04_string")),
    ("vgm05", col("vgm05_string")),
    ("vgm06", col("vgm06_string")),
    ("xdefa", col("xdefa_string")),
    ("xkost", col("xkost_string")),
    ("xsprr", col("xsprr_string")),
    ("xterm", col("xterm_string")),
    ("zgr01", col("zgr01_string")),
    ("zgr02", col("zgr02_string")),
    ("zgr03", col("zgr03_string")),
    ("zgr04", col("zgr04_string")),
    ("zgr05", col("zgr05_string")),
    ("zgr06", col("zgr06_string")),
    ("ktsch", col("ktsch_string")),
    ("loanz", col("loanz_decimal_3_0")),
    ("loart", col("loart_string")),
    ("logrp", col("logrp_string")),
    ("qualf", col("qualf_string")),
    ("rasch", col("rasch_string")),
    ("steus", col("steus_string")),
    ("vge01", col("vge01_string")),
    ("vge02", col("vge02_string")),
    ("vge03", col("vge03_string")),
    ("vge04", col("vge04_string")),
    ("vge05", col("vge05_string")),
    ("vge06", col("vge06_string")),
    ("ktsch_ref", col("ktsch_ref_string")),
    ("loart_ref", col("loart_ref_string")),
    ("loanz_ref", col("loanz_ref_string")),
    ("logrp_ref", col("logrp_ref_string")),
    ("qualf_ref", col("qualf_ref_string")),
    ("rasch_ref", col("rasch_ref_string")),
    ("steus_ref", col("steus_ref_string")),
    ("fort1", col("fort1_string")),
    ("fort2", col("fort2_string")),
    ("fort3", col("fort3_string")),
    ("kapid", col("kapid_string")),
    ("ortgr", col("ortgr_string")),
    ("zeiwn", col("zeiwn_string")),
    ("zwnor", col("zwnor_decimal_9_3")),
    ("zeiwm", col("zeiwm_string")),
    ("zwmin", col("zwmin_decimal_9_3")),
    ("formr", col("formr_string")),
    ("matyp", col("matyp_string")),
    ("cplgr", col("cplgr_string")),
    ("sortb", col("sortb_string")),
    ("mtrvp", col("mtrvp_decimal_3_1")),
    ("mtmvp", col("mtmvp_decimal_3_1")),
    ("mtpvp", col("mtpvp_decimal_3_1")),
    ("rsanz", col("rsanz_string")),
    ("pdest", col("pdest_string")),
    ("hroid", col("hroid_string")),
    ("fortn", col("fortn_string")),
    ("zgr01_ref", col("zgr01_ref_string")),
    ("zgr02_ref", col("zgr02_ref_string")),
    ("zgr03_ref", col("zgr03_ref_string")),
    ("zgr04_ref", col("zgr04_ref_string")),
    ("zgr05_ref", col("zgr05_ref_string")),
    ("zgr06_ref", col("zgr06_ref_string")),
    ("steus_c", col("steus_c_string")),
    ("steus_i", col("steus_i_string")),
    ("steus_n", col("steus_n_string")),
    ("steus_q", col("steus_q_string")),
    ("ruzus", col("ruzus_string")),
    ("rsanz_ref", col("rsanz_ref_string")),
    ("hr", col("hr_string")),
    ("prvbe", col("prvbe_string")),
    ("subsys", col("subsys_string")),
    ("bdegr", col("bdegr_string")),
    ("rgekz", col("rgekz_string")),
    ("hrtyp", col("hrtyp_string")),
    ("slwid", col("slwid_string")),
    ("lifnr", col("lifnr_string")),
    ("slwid_ref", col("slwid_ref_string")),
    ("lifnr_ref", col("lifnr_ref_string")),
    ("vgarb", col("vgarb_string")),
    ("vgdim", col("vgdim_string")),
    ("hrplvar", col("hrplvar_string")),
    ("vgdau", col("vgdau_string")),
    ("stobj", col("stobj_string")),
    ("resgr", col("resgr_string")),
    ("lgort_res", col("lgort_res_string")),
    ("mixmat", col("mixmat_string")),
    ("istbed_kz", col("istbed_kz_string")),
    ("srtype", col("srtype_string")),
    ("sntype", col("sntype_string"))
  )
}
