// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_epp

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_epp.{csks => sr_raw_csks}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrCsks(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK kokrs: String,
    @PK kostl: String,
    @PK datbi: String,
    datab: String,
    bkzkp: String,
    pkzkp: String,
    bukrs: String,
    gsber: String,
    kosar: String,
    verak: String,
    verak_user: String,
    waers: String,
    kalsm: String,
    txjcd: String,
    prctr: String,
    werks: String,
    logsystem: String,
    ersda: String,
    usnam: String,
    bkzks: String,
    bkzer: String,
    bkzob: String,
    pkzks: String,
    pkzer: String,
    vmeth: String,
    mgefl: String,
    abtei: String,
    nkost: String,
    kvewe: String,
    kappl: String,
    koszschl: String,
    land1: String,
    anred: String,
    name1: String,
    name2: String,
    name3: String,
    name4: String,
    ort01: String,
    ort02: String,
    stras: String,
    pfach: String,
    pstlz: String,
    pstl2: String,
    regio: String,
    spras: String,
    telbx: String,
    telf1: String,
    telf2: String,
    telfx: String,
    teltx: String,
    telx1: String,
    datlt: String,
    drnam: String,
    khinr: String,
    cckey: String,
    kompl: String,
    stakz: String,
    objnr: String,
    funkt: String,
    afunk: String,
    cpi_templ: String,
    cpd_templ: String,
    func_area: String,
    sci_templ: String,
    scd_templ: String,
    ski_templ: String,
    skd_templ: String,
    vname: String,
    recid: String,
    etype: String,
    jv_otype: String,
    jv_jibcl: String,
    jv_jibsa: String,
    ferc_ind: String
) extends Entity

object csks extends TableSpec[SrCsks] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_csks] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_csks] = sr_raw_csks

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("kokrs", coalesce(col("kokrs_string"), lit(""))),
    ("kostl", coalesce(col("kostl_string"), lit(""))),
    ("datbi", coalesce(col("datbi_string"), lit(""))),
    ("datab", col("datab_string")),
    ("bkzkp", col("bkzkp_string")),
    ("pkzkp", col("pkzkp_string")),
    ("bukrs", col("bukrs_string")),
    ("gsber", col("gsber_string")),
    ("kosar", col("kosar_string")),
    ("verak", col("verak_string")),
    ("verak_user", col("verak_user_string")),
    ("waers", col("waers_string")),
    ("kalsm", col("kalsm_string")),
    ("txjcd", col("txjcd_string")),
    ("prctr", col("prctr_string")),
    ("werks", col("werks_string")),
    ("logsystem", col("logsystem_string")),
    ("ersda", col("ersda_string")),
    ("usnam", col("usnam_string")),
    ("bkzks", col("bkzks_string")),
    ("bkzer", col("bkzer_string")),
    ("bkzob", col("bkzob_string")),
    ("pkzks", col("pkzks_string")),
    ("pkzer", col("pkzer_string")),
    ("vmeth", col("vmeth_string")),
    ("mgefl", col("mgefl_string")),
    ("abtei", col("abtei_string")),
    ("nkost", col("nkost_string")),
    ("kvewe", col("kvewe_string")),
    ("kappl", col("kappl_string")),
    ("koszschl", col("koszschl_string")),
    ("land1", col("land1_string")),
    ("anred", col("anred_string")),
    ("name1", col("name1_string")),
    ("name2", col("name2_string")),
    ("name3", col("name3_string")),
    ("name4", col("name4_string")),
    ("ort01", col("ort01_string")),
    ("ort02", col("ort02_string")),
    ("stras", col("stras_string")),
    ("pfach", col("pfach_string")),
    ("pstlz", col("pstlz_string")),
    ("pstl2", col("pstl2_string")),
    ("regio", col("regio_string")),
    ("spras", col("spras_string")),
    ("telbx", col("telbx_string")),
    ("telf1", col("telf1_string")),
    ("telf2", col("telf2_string")),
    ("telfx", col("telfx_string")),
    ("teltx", col("teltx_string")),
    ("telx1", col("telx1_string")),
    ("datlt", col("datlt_string")),
    ("drnam", col("drnam_string")),
    ("khinr", col("khinr_string")),
    ("cckey", col("cckey_string")),
    ("kompl", col("kompl_string")),
    ("stakz", col("stakz_string")),
    ("objnr", col("objnr_string")),
    ("funkt", col("funkt_string")),
    ("afunk", col("afunk_string")),
    ("cpi_templ", col("cpi_templ_string")),
    ("cpd_templ", col("cpd_templ_string")),
    ("func_area", col("func_area_string")),
    ("sci_templ", col("sci_templ_string")),
    ("scd_templ", col("scd_templ_string")),
    ("ski_templ", col("ski_templ_string")),
    ("skd_templ", col("skd_templ_string")),
    ("vname", col("vname_string")),
    ("recid", col("recid_string")),
    ("etype", col("etype_string")),
    ("jv_otype", col("jv_otype_string")),
    ("jv_jibcl", col("jv_jibcl_string")),
    ("jv_jibsa", col("jv_jibsa_string")),
    ("ferc_ind", col("ferc_ind_string"))
  )
}
