// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_epp

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_epp.{eban => sr_raw_eban}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrEban(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK banfn: String,
    @PK bnfpo: String,
    bsart: String,
    bstyp: String,
    bsakz: String,
    loekz: String,
    statu: String,
    estkz: String,
    frgkz: String,
    frgzu: String,
    frgst: String,
    ekgrp: String,
    ernam: String,
    erdat: String,
    afnam: String,
    txz01: String,
    matnr: String,
    ematn: String,
    werks: String,
    lgort: String,
    bednr: String,
    matkl: String,
    reswk: String,
    @Decimal(13, 3) menge: java.math.BigDecimal,
    meins: String,
    @Decimal(13, 3) bumng: java.math.BigDecimal,
    badat: String,
    lpein: String,
    lfdat: String,
    frgdt: String,
    @Decimal(3, 0) webaz: java.math.BigDecimal,
    @Decimal(11, 2) preis: java.math.BigDecimal,
    @Decimal(5, 0) peinh: java.math.BigDecimal,
    pstyp: String,
    knttp: String,
    kzvbr: String,
    kflag: String,
    vrtkz: String,
    twrkz: String,
    wepos: String,
    weunb: String,
    repos: String,
    lifnr: String,
    flief: String,
    ekorg: String,
    vrtyp: String,
    konnr: String,
    ktpnr: String,
    infnr: String,
    zugba: String,
    qunum: String,
    qupos: String,
    dispo: String,
    sernr: String,
    bvdat: String,
    @Decimal(3, 0) batol: java.math.BigDecimal,
    @Decimal(7, 0) bvdrk: java.math.BigDecimal,
    ebeln: String,
    ebelp: String,
    bedat: String,
    @Decimal(13, 3) bsmng: java.math.BigDecimal,
    lblni: String,
    bwtar: String,
    xoblr: String,
    ebakz: String,
    rsnum: String,
    sobkz: String,
    arsnr: String,
    arsps: String,
    fixkz: String,
    bmein: String,
    revlv: String,
    vorab: String,
    packno: String,
    kanba: String,
    bpueb: String,
    cuobj: String,
    frggr: String,
    frgrl: String,
    aktnr: String,
    charg: String,
    umsok: String,
    verid: String,
    fipos: String,
    fistl: String,
    geber: String,
    kzkfg: String,
    satnr: String,
    @Decimal(13, 3) mng02: java.math.BigDecimal,
    dat01: String,
    attyp: String,
    adrnr: String,
    adrn2: String,
    kunnr: String,
    emlif: String,
    lblkz: String,
    kzbws: String,
    waers: String,
    idnlf: String,
    gsfrg: String,
    mprof: String,
    kzfme: String,
    spras: String,
    techs: String,
    mfrpn: String,
    mfrnr: String,
    emnfr: String,
    fordn: String,
    fordp: String,
    @Decimal(3, 0) plifz: java.math.BigDecimal,
    berid: String,
    uzeit: String,
    fkber: String,
    grant_nbr: String,
    memory: String,
    banpr: String,
    @Decimal(15, 2) rlwrt: java.math.BigDecimal,
    blckd: String,
    revno: String,
    blckt: String,
    beswk: String,
    eprofile: String,
    eprefdoc: String,
    eprefitm: String,
    @Decimal(13, 3) gmmng: java.math.BigDecimal,
    wrtkz: String,
    reslo: String,
    kblnr: String,
    kblpos: String,
    prio_urg: String,
    prio_req: String,
    memorytype: String,
    anzsn: Int,
    @Decimal(4, 0) mhdrz: java.math.BigDecimal,
    iprkz: String,
    nodisp: String,
    srm_contract_id: String,
    srm_contract_itm: String,
    budget_pd: String,
    expert_mode: String,
    storenetworkid: String,
    storesupplierid: String,
    creationdate: String,
    creationtime: String,
    iscrreplicationbeforeapproval: String,
    mmpur_pr_cen_reqn_app_rpld_pr: String,
    @Decimal(21, 7) ext_rev_tmstmp: java.math.BigDecimal,
    fmfgus_key: String,
    advcode: String,
    stacode: String,
    banfn_cs: String,
    bnfpo_cs: String,
    item_cs: String,
    @Decimal(13, 3) bsmng_snd: java.math.BigDecimal,
    no_mard_data: String,
    admoi: String,
    adpri: String,
    lprio: String,
    adacn: String,
    addns: String,
    serru: String,
    disub_sobkz: String,
    disub_pspnr: String,
    disub_kunnr: String,
    disub_vbeln: String,
    disub_posnr: String,
    disub_owner: String,
    fsh_season_year: String,
    fsh_season: String,
    fsh_collection: String,
    fsh_theme: String,
    fsh_vas_rel: String,
    fsh_vas_prnt_id: String,
    fsh_transaction: String,
    fsh_item_group: String,
    fsh_item: String,
    iuid_relevant: String,
    sgt_scat: String,
    sgt_rcat: String,
    wrf_charstc1: String,
    wrf_charstc2: String,
    wrf_charstc3: String,
    yysent: String,
    yydate: String,
    yytime: String
) extends Entity

object eban extends TableSpec[SrEban] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_eban] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_eban] = sr_raw_eban

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("banfn", coalesce(col("banfn_string"), lit(""))),
    ("bnfpo", coalesce(col("bnfpo_string"), lit(""))),
    ("bsart", col("bsart_string")),
    ("bstyp", col("bstyp_string")),
    ("bsakz", col("bsakz_string")),
    ("loekz", col("loekz_string")),
    ("statu", col("statu_string")),
    ("estkz", col("estkz_string")),
    ("frgkz", col("frgkz_string")),
    ("frgzu", col("frgzu_string")),
    ("frgst", col("frgst_string")),
    ("ekgrp", col("ekgrp_string")),
    ("ernam", col("ernam_string")),
    ("erdat", col("erdat_string")),
    ("afnam", col("afnam_string")),
    ("txz01", col("txz01_string")),
    ("matnr", col("matnr_string")),
    ("ematn", col("ematn_string")),
    ("werks", col("werks_string")),
    ("lgort", col("lgort_string")),
    ("bednr", col("bednr_string")),
    ("matkl", col("matkl_string")),
    ("reswk", col("reswk_string")),
    ("menge", col("menge_decimal_13_3")),
    ("meins", col("meins_string")),
    ("bumng", col("bumng_decimal_13_3")),
    ("badat", col("badat_string")),
    ("lpein", col("lpein_string")),
    ("lfdat", col("lfdat_string")),
    ("frgdt", col("frgdt_string")),
    ("webaz", col("webaz_decimal_3_0")),
    ("preis", col("preis_decimal_11_2")),
    ("peinh", col("peinh_decimal_5_0")),
    ("pstyp", col("pstyp_string")),
    ("knttp", col("knttp_string")),
    ("kzvbr", col("kzvbr_string")),
    ("kflag", col("kflag_string")),
    ("vrtkz", col("vrtkz_string")),
    ("twrkz", col("twrkz_string")),
    ("wepos", col("wepos_string")),
    ("weunb", col("weunb_string")),
    ("repos", col("repos_string")),
    ("lifnr", col("lifnr_string")),
    ("flief", col("flief_string")),
    ("ekorg", col("ekorg_string")),
    ("vrtyp", col("vrtyp_string")),
    ("konnr", col("konnr_string")),
    ("ktpnr", col("ktpnr_string")),
    ("infnr", col("infnr_string")),
    ("zugba", col("zugba_string")),
    ("qunum", col("qunum_string")),
    ("qupos", col("qupos_string")),
    ("dispo", col("dispo_string")),
    ("sernr", col("sernr_string")),
    ("bvdat", col("bvdat_string")),
    ("batol", col("batol_decimal_3_0")),
    ("bvdrk", col("bvdrk_decimal_7_0")),
    ("ebeln", col("ebeln_string")),
    ("ebelp", col("ebelp_string")),
    ("bedat", col("bedat_string")),
    ("bsmng", col("bsmng_decimal_13_3")),
    ("lblni", col("lblni_string")),
    ("bwtar", col("bwtar_string")),
    ("xoblr", col("xoblr_string")),
    ("ebakz", col("ebakz_string")),
    ("rsnum", col("rsnum_string")),
    ("sobkz", col("sobkz_string")),
    ("arsnr", col("arsnr_string")),
    ("arsps", col("arsps_string")),
    ("fixkz", col("fixkz_string")),
    ("bmein", col("bmein_string")),
    ("revlv", col("revlv_string")),
    ("vorab", col("vorab_string")),
    ("packno", col("packno_string")),
    ("kanba", col("kanba_string")),
    ("bpueb", col("bpueb_string")),
    ("cuobj", col("cuobj_string")),
    ("frggr", col("frggr_string")),
    ("frgrl", col("frgrl_string")),
    ("aktnr", col("aktnr_string")),
    ("charg", col("charg_string")),
    ("umsok", col("umsok_string")),
    ("verid", col("verid_string")),
    ("fipos", col("fipos_string")),
    ("fistl", col("fistl_string")),
    ("geber", col("geber_string")),
    ("kzkfg", col("kzkfg_string")),
    ("satnr", col("satnr_string")),
    ("mng02", col("mng02_decimal_13_3")),
    ("dat01", col("dat01_string")),
    ("attyp", col("attyp_string")),
    ("adrnr", col("adrnr_string")),
    ("adrn2", col("adrn2_string")),
    ("kunnr", col("kunnr_string")),
    ("emlif", col("emlif_string")),
    ("lblkz", col("lblkz_string")),
    ("kzbws", col("kzbws_string")),
    ("waers", col("waers_string")),
    ("idnlf", col("idnlf_string")),
    ("gsfrg", col("gsfrg_string")),
    ("mprof", col("mprof_string")),
    ("kzfme", col("kzfme_string")),
    ("spras", col("spras_string")),
    ("techs", col("techs_string")),
    ("mfrpn", col("mfrpn_string")),
    ("mfrnr", col("mfrnr_string")),
    ("emnfr", col("emnfr_string")),
    ("fordn", col("fordn_string")),
    ("fordp", col("fordp_string")),
    ("plifz", col("plifz_decimal_3_0")),
    ("berid", col("berid_string")),
    ("uzeit", col("uzeit_string")),
    ("fkber", col("fkber_string")),
    ("grant_nbr", col("grant_nbr_string")),
    ("memory", col("memory_string")),
    ("banpr", col("banpr_string")),
    ("rlwrt", col("rlwrt_decimal_15_2")),
    ("blckd", col("blckd_string")),
    ("revno", col("revno_string")),
    ("blckt", col("blckt_string")),
    ("beswk", col("beswk_string")),
    ("eprofile", col("eprofile_string")),
    ("eprefdoc", col("eprefdoc_string")),
    ("eprefitm", col("eprefitm_string")),
    ("gmmng", col("gmmng_decimal_13_3")),
    ("wrtkz", col("wrtkz_string")),
    ("reslo", col("reslo_string")),
    ("kblnr", col("kblnr_string")),
    ("kblpos", col("kblpos_string")),
    ("prio_urg", col("prio_urg_string")),
    ("prio_req", col("prio_req_string")),
    ("memorytype", col("memorytype_string")),
    ("anzsn", coalesce(col("anzsn_int"), lit(0))),
    ("mhdrz", col("mhdrz_decimal_4_0")),
    ("iprkz", col("iprkz_string")),
    ("nodisp", col("nodisp_string")),
    ("srm_contract_id", col("srm_contract_id_string")),
    ("srm_contract_itm", col("srm_contract_itm_string")),
    ("budget_pd", col("budget_pd_string")),
    ("expert_mode", col("expert_mode_string")),
    ("storenetworkid", col("storenetworkid_string")),
    ("storesupplierid", col("storesupplierid_string")),
    ("creationdate", col("creationdate_string")),
    ("creationtime", col("creationtime_string")),
    ("iscrreplicationbeforeapproval", col("iscrreplicationbeforeapproval_string")),
    ("mmpur_pr_cen_reqn_app_rpld_pr", col("mmpur_pr_cen_reqn_app_rpld_pr_string")),
    ("ext_rev_tmstmp", col("ext_rev_tmstmp_decimal_21_7")),
    ("fmfgus_key", col("fmfgus_key_string")),
    ("advcode", col("advcode_string")),
    ("stacode", col("stacode_string")),
    ("banfn_cs", col("banfn_cs_string")),
    ("bnfpo_cs", col("bnfpo_cs_string")),
    ("item_cs", col("item_cs_string")),
    ("bsmng_snd", col("bsmng_snd_decimal_13_3")),
    ("no_mard_data", col("no_mard_data_string")),
    ("admoi", col("admoi_string")),
    ("adpri", col("adpri_string")),
    ("lprio", col("lprio_string")),
    ("adacn", col("adacn_string")),
    ("addns", col("addns_string")),
    ("serru", col("serru_string")),
    ("disub_sobkz", col("disub_sobkz_string")),
    ("disub_pspnr", col("disub_pspnr_string")),
    ("disub_kunnr", col("disub_kunnr_string")),
    ("disub_vbeln", col("disub_vbeln_string")),
    ("disub_posnr", col("disub_posnr_string")),
    ("disub_owner", col("disub_owner_string")),
    ("fsh_season_year", col("fsh_season_year_string")),
    ("fsh_season", col("fsh_season_string")),
    ("fsh_collection", col("fsh_collection_string")),
    ("fsh_theme", col("fsh_theme_string")),
    ("fsh_vas_rel", col("fsh_vas_rel_string")),
    ("fsh_vas_prnt_id", col("fsh_vas_prnt_id_string")),
    ("fsh_transaction", col("fsh_transaction_string")),
    ("fsh_item_group", col("fsh_item_group_string")),
    ("fsh_item", col("fsh_item_string")),
    ("iuid_relevant", col("iuid_relevant_string")),
    ("sgt_scat", col("sgt_scat_string")),
    ("sgt_rcat", col("sgt_rcat_string")),
    ("wrf_charstc1", col("wrf_charstc1_string")),
    ("wrf_charstc2", col("wrf_charstc2_string")),
    ("wrf_charstc3", col("wrf_charstc3_string")),
    ("yysent", col("yysent_string")),
    ("yydate", col("yydate_string")),
    ("yytime", col("yytime_string"))
  )
}
