// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_epp

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_eket(
    @PK mandt: String,
    @PK ebeln: String,
    @PK ebelp: String,
    @PK etenr: String,
    eindt: String,
    slfdt: String,
    lpein: String,
    @Decimal(13, 3) menge: BigDecimal,
    @Decimal(13, 3) ameng: BigDecimal,
    @Decimal(13, 3) wemng: BigDecimal,
    @Decimal(13, 3) wamng: BigDecimal,
    uzeit: String,
    banfn: String,
    bnfpo: String,
    estkz: String,
    qunum: String,
    qupos: String,
    @Decimal(3, 0) mahnz: BigDecimal,
    bedat: String,
    rsnum: String,
    sernr: String,
    fixkz: String,
    @Decimal(13, 3) glmng: BigDecimal,
    @Decimal(13, 3) dabmg: BigDecimal,
    charg: String,
    licha: String,
    chkom: String,
    verid: String,
    abart: String,
    @Decimal(13, 3) mng02: BigDecimal,
    dat01: String,
    altdt: String,
    aulwe: String,
    mbdat: String,
    mbuhr: String,
    lddat: String,
    lduhr: String,
    tddat: String,
    tduhr: String,
    wadat: String,
    wauhr: String,
    eldat: String,
    eluhr: String,
    anzsn: BoxedInt,
    nodisp: String,
    geo_route: String,
    route_gts: String,
    gts_ind: String,
    tsp: String,
    cd_locno: String,
    cd_loctype: String,
    handoverdate: String,
    handovertime: String,
    sel: String,
    cci: String,
    sen: String,
    psel: String,
    pcci: String,
    psen: String,
    dno: String,
    shm: String,
    smb: String,
    ecc: String,
    plc: String,
    key_id: String,
    @Decimal(17, 2) otb_value: BigDecimal,
    otb_curr: String,
    @Decimal(17, 2) otb_res_value: BigDecimal,
    @Decimal(17, 2) otb_spec_value: BigDecimal,
    spr_rsn_profile: String,
    budg_type: String,
    otb_status: String,
    otb_reason: String,
    check_type: String,
    dl_id: String,
    handover_date: String,
    no_scem: String,
    dng_date: String,
    dng_time: String,
    cncl_ancmnt_done: String,
    @Decimal(3, 0) dateshift_number: BigDecimal,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String
) extends Entity

object eket
    extends TableSpec[E_eket](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[sr_raw.ct_gbl_epp.E_eket] {
  override def sourceTableSpec: TableSpec[sr_raw.ct_gbl_epp.E_eket] = sr_raw.ct_gbl_epp.eket
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("mandt", col("mandt_string")),
    ("ebeln", col("ebeln_string")),
    ("ebelp", col("ebelp_string")),
    ("etenr", col("etenr_string")),
    ("eindt", col("eindt_string")),
    ("slfdt", col("slfdt_string")),
    ("lpein", col("lpein_string")),
    ("menge", col("menge_decimal_13_3")),
    ("ameng", col("ameng_decimal_13_3")),
    ("wemng", col("wemng_decimal_13_3")),
    ("wamng", col("wamng_decimal_13_3")),
    ("uzeit", col("uzeit_string")),
    ("banfn", col("banfn_string")),
    ("bnfpo", col("bnfpo_string")),
    ("estkz", col("estkz_string")),
    ("qunum", col("qunum_string")),
    ("qupos", col("qupos_string")),
    ("mahnz", col("mahnz_decimal_3_0")),
    ("bedat", col("bedat_string")),
    ("rsnum", col("rsnum_string")),
    ("sernr", col("sernr_string")),
    ("fixkz", col("fixkz_string")),
    ("glmng", col("glmng_decimal_13_3")),
    ("dabmg", col("dabmg_decimal_13_3")),
    ("charg", col("charg_string")),
    ("licha", col("licha_string")),
    ("chkom", col("chkom_string")),
    ("verid", col("verid_string")),
    ("abart", col("abart_string")),
    ("mng02", col("mng02_decimal_13_3")),
    ("dat01", col("dat01_string")),
    ("altdt", col("altdt_string")),
    ("aulwe", col("aulwe_string")),
    ("mbdat", col("mbdat_string")),
    ("mbuhr", col("mbuhr_string")),
    ("lddat", col("lddat_string")),
    ("lduhr", col("lduhr_string")),
    ("tddat", col("tddat_string")),
    ("tduhr", col("tduhr_string")),
    ("wadat", col("wadat_string")),
    ("wauhr", col("wauhr_string")),
    ("eldat", col("eldat_string")),
    ("eluhr", col("eluhr_string")),
    ("anzsn", col("anzsn_int")),
    ("nodisp", col("nodisp_string")),
    ("geo_route", col("geo_route_string")),
    ("route_gts", col("route_gts_string")),
    ("gts_ind", col("gts_ind_string")),
    ("tsp", col("tsp_string")),
    ("cd_locno", col("cd_locno_string")),
    ("cd_loctype", col("cd_loctype_string")),
    ("handoverdate", col("handoverdate_string")),
    ("handovertime", col("handovertime_string")),
    ("sel", col("sel_string")),
    ("cci", col("cci_string")),
    ("sen", col("sen_string")),
    ("psel", col("psel_string")),
    ("pcci", col("pcci_string")),
    ("psen", col("psen_string")),
    ("dno", col("dno_string")),
    ("shm", col("shm_string")),
    ("smb", col("smb_string")),
    ("ecc", col("ecc_string")),
    ("plc", col("plc_string")),
    ("key_id", col("key_id_string")),
    ("otb_value", col("otb_value_decimal_17_2")),
    ("otb_curr", col("otb_curr_string")),
    ("otb_res_value", col("otb_res_value_decimal_17_2")),
    ("otb_spec_value", col("otb_spec_value_decimal_17_2")),
    ("spr_rsn_profile", col("spr_rsn_profile_string")),
    ("budg_type", col("budg_type_string")),
    ("otb_status", col("otb_status_string")),
    ("otb_reason", col("otb_reason_string")),
    ("check_type", col("check_type_string")),
    ("dl_id", col("dl_id_string")),
    ("handover_date", col("handover_date_string")),
    ("no_scem", col("no_scem_string")),
    ("dng_date", col("dng_date_string")),
    ("dng_time", col("dng_time_string")),
    ("cncl_ancmnt_done", col("cncl_ancmnt_done_string")),
    ("dateshift_number", col("dateshift_number_decimal_3_0"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_eket(prefix: String) extends ColumnWithNameAccessor {
  val mandt: ColumnWithName = ColumnWithName(prefix + "mandt")
  val ebeln: ColumnWithName = ColumnWithName(prefix + "ebeln")
  val ebelp: ColumnWithName = ColumnWithName(prefix + "ebelp")
  val etenr: ColumnWithName = ColumnWithName(prefix + "etenr")
  val eindt: ColumnWithName = ColumnWithName(prefix + "eindt")
  val slfdt: ColumnWithName = ColumnWithName(prefix + "slfdt")
  val lpein: ColumnWithName = ColumnWithName(prefix + "lpein")
  val menge: ColumnWithName = ColumnWithName(prefix + "menge")
  val ameng: ColumnWithName = ColumnWithName(prefix + "ameng")
  val wemng: ColumnWithName = ColumnWithName(prefix + "wemng")
  val wamng: ColumnWithName = ColumnWithName(prefix + "wamng")
  val uzeit: ColumnWithName = ColumnWithName(prefix + "uzeit")
  val banfn: ColumnWithName = ColumnWithName(prefix + "banfn")
  val bnfpo: ColumnWithName = ColumnWithName(prefix + "bnfpo")
  val estkz: ColumnWithName = ColumnWithName(prefix + "estkz")
  val qunum: ColumnWithName = ColumnWithName(prefix + "qunum")
  val qupos: ColumnWithName = ColumnWithName(prefix + "qupos")
  val mahnz: ColumnWithName = ColumnWithName(prefix + "mahnz")
  val bedat: ColumnWithName = ColumnWithName(prefix + "bedat")
  val rsnum: ColumnWithName = ColumnWithName(prefix + "rsnum")
  val sernr: ColumnWithName = ColumnWithName(prefix + "sernr")
  val fixkz: ColumnWithName = ColumnWithName(prefix + "fixkz")
  val glmng: ColumnWithName = ColumnWithName(prefix + "glmng")
  val dabmg: ColumnWithName = ColumnWithName(prefix + "dabmg")
  val charg: ColumnWithName = ColumnWithName(prefix + "charg")
  val licha: ColumnWithName = ColumnWithName(prefix + "licha")
  val chkom: ColumnWithName = ColumnWithName(prefix + "chkom")
  val verid: ColumnWithName = ColumnWithName(prefix + "verid")
  val abart: ColumnWithName = ColumnWithName(prefix + "abart")
  val mng02: ColumnWithName = ColumnWithName(prefix + "mng02")
  val dat01: ColumnWithName = ColumnWithName(prefix + "dat01")
  val altdt: ColumnWithName = ColumnWithName(prefix + "altdt")
  val aulwe: ColumnWithName = ColumnWithName(prefix + "aulwe")
  val mbdat: ColumnWithName = ColumnWithName(prefix + "mbdat")
  val mbuhr: ColumnWithName = ColumnWithName(prefix + "mbuhr")
  val lddat: ColumnWithName = ColumnWithName(prefix + "lddat")
  val lduhr: ColumnWithName = ColumnWithName(prefix + "lduhr")
  val tddat: ColumnWithName = ColumnWithName(prefix + "tddat")
  val tduhr: ColumnWithName = ColumnWithName(prefix + "tduhr")
  val wadat: ColumnWithName = ColumnWithName(prefix + "wadat")
  val wauhr: ColumnWithName = ColumnWithName(prefix + "wauhr")
  val eldat: ColumnWithName = ColumnWithName(prefix + "eldat")
  val eluhr: ColumnWithName = ColumnWithName(prefix + "eluhr")
  val anzsn: ColumnWithName = ColumnWithName(prefix + "anzsn")
  val nodisp: ColumnWithName = ColumnWithName(prefix + "nodisp")
  val geo_route: ColumnWithName = ColumnWithName(prefix + "geo_route")
  val route_gts: ColumnWithName = ColumnWithName(prefix + "route_gts")
  val gts_ind: ColumnWithName = ColumnWithName(prefix + "gts_ind")
  val tsp: ColumnWithName = ColumnWithName(prefix + "tsp")
  val cd_locno: ColumnWithName = ColumnWithName(prefix + "cd_locno")
  val cd_loctype: ColumnWithName = ColumnWithName(prefix + "cd_loctype")
  val handoverdate: ColumnWithName = ColumnWithName(prefix + "handoverdate")
  val handovertime: ColumnWithName = ColumnWithName(prefix + "handovertime")
  val sel: ColumnWithName = ColumnWithName(prefix + "sel")
  val cci: ColumnWithName = ColumnWithName(prefix + "cci")
  val sen: ColumnWithName = ColumnWithName(prefix + "sen")
  val psel: ColumnWithName = ColumnWithName(prefix + "psel")
  val pcci: ColumnWithName = ColumnWithName(prefix + "pcci")
  val psen: ColumnWithName = ColumnWithName(prefix + "psen")
  val dno: ColumnWithName = ColumnWithName(prefix + "dno")
  val shm: ColumnWithName = ColumnWithName(prefix + "shm")
  val smb: ColumnWithName = ColumnWithName(prefix + "smb")
  val ecc: ColumnWithName = ColumnWithName(prefix + "ecc")
  val plc: ColumnWithName = ColumnWithName(prefix + "plc")
  val key_id: ColumnWithName = ColumnWithName(prefix + "key_id")
  val otb_value: ColumnWithName = ColumnWithName(prefix + "otb_value")
  val otb_curr: ColumnWithName = ColumnWithName(prefix + "otb_curr")
  val otb_res_value: ColumnWithName = ColumnWithName(prefix + "otb_res_value")
  val otb_spec_value: ColumnWithName = ColumnWithName(prefix + "otb_spec_value")
  val spr_rsn_profile: ColumnWithName = ColumnWithName(prefix + "spr_rsn_profile")
  val budg_type: ColumnWithName = ColumnWithName(prefix + "budg_type")
  val otb_status: ColumnWithName = ColumnWithName(prefix + "otb_status")
  val otb_reason: ColumnWithName = ColumnWithName(prefix + "otb_reason")
  val check_type: ColumnWithName = ColumnWithName(prefix + "check_type")
  val dl_id: ColumnWithName = ColumnWithName(prefix + "dl_id")
  val handover_date: ColumnWithName = ColumnWithName(prefix + "handover_date")
  val no_scem: ColumnWithName = ColumnWithName(prefix + "no_scem")
  val dng_date: ColumnWithName = ColumnWithName(prefix + "dng_date")
  val dng_time: ColumnWithName = ColumnWithName(prefix + "dng_time")
  val cncl_ancmnt_done: ColumnWithName = ColumnWithName(prefix + "cncl_ancmnt_done")
  val dateshift_number: ColumnWithName = ColumnWithName(prefix + "dateshift_number")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
}

object C_eket extends C_eket("") {
  def as(alias: String): C_eket = new C_eket(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
