// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_epp

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_epp.{eket => sr_raw_eket}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrEket(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK ebeln: String,
    @PK ebelp: String,
    @PK etenr: String,
    eindt: String,
    slfdt: String,
    lpein: String,
    @Decimal(13, 3) menge: java.math.BigDecimal,
    @Decimal(13, 3) ameng: java.math.BigDecimal,
    @Decimal(13, 3) wemng: java.math.BigDecimal,
    @Decimal(13, 3) wamng: java.math.BigDecimal,
    uzeit: String,
    banfn: String,
    bnfpo: String,
    estkz: String,
    qunum: String,
    qupos: String,
    @Decimal(3, 0) mahnz: java.math.BigDecimal,
    bedat: String,
    rsnum: String,
    sernr: String,
    fixkz: String,
    @Decimal(13, 3) glmng: java.math.BigDecimal,
    @Decimal(13, 3) dabmg: java.math.BigDecimal,
    charg: String,
    licha: String,
    chkom: String,
    verid: String,
    abart: String,
    @Decimal(13, 3) mng02: java.math.BigDecimal,
    dat01: String,
    altdt: String,
    aulwe: String,
    mbdat: String,
    mbuhr: String,
    lddat: String,
    lduhr: String,
    tddat: String,
    tduhr: String,
    wadat: String,
    wauhr: String,
    eldat: String,
    eluhr: String,
    anzsn: Int,
    nodisp: String,
    geo_route: String,
    route_gts: String,
    gts_ind: String,
    tsp: String,
    cd_locno: String,
    cd_loctype: String,
    handoverdate: String,
    handovertime: String,
    sel: String,
    cci: String,
    sen: String,
    psel: String,
    pcci: String,
    psen: String,
    dno: String,
    shm: String,
    smb: String,
    ecc: String,
    plc: String,
    key_id: String,
    @Decimal(17, 2) otb_value: java.math.BigDecimal,
    otb_curr: String,
    @Decimal(17, 2) otb_res_value: java.math.BigDecimal,
    @Decimal(17, 2) otb_spec_value: java.math.BigDecimal,
    spr_rsn_profile: String,
    budg_type: String,
    otb_status: String,
    otb_reason: String,
    check_type: String,
    dl_id: String,
    handover_date: String,
    no_scem: String,
    dng_date: String,
    dng_time: String,
    cncl_ancmnt_done: String,
    @Decimal(3, 0) dateshift_number: java.math.BigDecimal
) extends Entity

object eket extends TableSpec[SrEket] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_eket] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_eket] = sr_raw_eket

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("ebeln", coalesce(col("ebeln_string"), lit(""))),
    ("ebelp", coalesce(col("ebelp_string"), lit(""))),
    ("etenr", coalesce(col("etenr_string"), lit(""))),
    ("eindt", col("eindt_string")),
    ("slfdt", col("slfdt_string")),
    ("lpein", col("lpein_string")),
    ("menge", col("menge_decimal_13_3")),
    ("ameng", col("ameng_decimal_13_3")),
    ("wemng", col("wemng_decimal_13_3")),
    ("wamng", col("wamng_decimal_13_3")),
    ("uzeit", col("uzeit_string")),
    ("banfn", col("banfn_string")),
    ("bnfpo", col("bnfpo_string")),
    ("estkz", col("estkz_string")),
    ("qunum", col("qunum_string")),
    ("qupos", col("qupos_string")),
    ("mahnz", col("mahnz_decimal_3_0")),
    ("bedat", col("bedat_string")),
    ("rsnum", col("rsnum_string")),
    ("sernr", col("sernr_string")),
    ("fixkz", col("fixkz_string")),
    ("glmng", col("glmng_decimal_13_3")),
    ("dabmg", col("dabmg_decimal_13_3")),
    ("charg", col("charg_string")),
    ("licha", col("licha_string")),
    ("chkom", col("chkom_string")),
    ("verid", col("verid_string")),
    ("abart", col("abart_string")),
    ("mng02", col("mng02_decimal_13_3")),
    ("dat01", col("dat01_string")),
    ("altdt", col("altdt_string")),
    ("aulwe", col("aulwe_string")),
    ("mbdat", col("mbdat_string")),
    ("mbuhr", col("mbuhr_string")),
    ("lddat", col("lddat_string")),
    ("lduhr", col("lduhr_string")),
    ("tddat", col("tddat_string")),
    ("tduhr", col("tduhr_string")),
    ("wadat", col("wadat_string")),
    ("wauhr", col("wauhr_string")),
    ("eldat", col("eldat_string")),
    ("eluhr", col("eluhr_string")),
    ("anzsn", coalesce(col("anzsn_int"), lit(0))),
    ("nodisp", col("nodisp_string")),
    ("geo_route", col("geo_route_string")),
    ("route_gts", col("route_gts_string")),
    ("gts_ind", col("gts_ind_string")),
    ("tsp", col("tsp_string")),
    ("cd_locno", col("cd_locno_string")),
    ("cd_loctype", col("cd_loctype_string")),
    ("handoverdate", col("handoverdate_string")),
    ("handovertime", col("handovertime_string")),
    ("sel", col("sel_string")),
    ("cci", col("cci_string")),
    ("sen", col("sen_string")),
    ("psel", col("psel_string")),
    ("pcci", col("pcci_string")),
    ("psen", col("psen_string")),
    ("dno", col("dno_string")),
    ("shm", col("shm_string")),
    ("smb", col("smb_string")),
    ("ecc", col("ecc_string")),
    ("plc", col("plc_string")),
    ("key_id", col("key_id_string")),
    ("otb_value", col("otb_value_decimal_17_2")),
    ("otb_curr", col("otb_curr_string")),
    ("otb_res_value", col("otb_res_value_decimal_17_2")),
    ("otb_spec_value", col("otb_spec_value_decimal_17_2")),
    ("spr_rsn_profile", col("spr_rsn_profile_string")),
    ("budg_type", col("budg_type_string")),
    ("otb_status", col("otb_status_string")),
    ("otb_reason", col("otb_reason_string")),
    ("check_type", col("check_type_string")),
    ("dl_id", col("dl_id_string")),
    ("handover_date", col("handover_date_string")),
    ("no_scem", col("no_scem_string")),
    ("dng_date", col("dng_date_string")),
    ("dng_time", col("dng_time_string")),
    ("cncl_ancmnt_done", col("cncl_ancmnt_done_string")),
    ("dateshift_number", col("dateshift_number_decimal_3_0"))
  )
}
