// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_epp

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_epp.{lfb1 => sr_raw_lfb1}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrLfb1(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK lifnr: String,
    @PK bukrs: String,
    pernr: String,
    erdat: String,
    ernam: String,
    sperr: String,
    loevm: String,
    zuawa: String,
    akont: String,
    begru: String,
    vzskz: String,
    zwels: String,
    xverr: String,
    zahls: String,
    zterm: String,
    eikto: String,
    zsabe: String,
    kverm: String,
    fdgrv: String,
    busab: String,
    lnrze: String,
    lnrzb: String,
    zindt: String,
    zinrt: String,
    datlz: String,
    xdezv: String,
    @Decimal(13, 2) webtr: java.math.BigDecimal,
    @Decimal(3, 0) kultg: java.math.BigDecimal,
    reprf: String,
    togru: String,
    hbkid: String,
    xpore: String,
    qsznr: String,
    qszdt: String,
    qsskz: String,
    blnkz: String,
    mindk: String,
    altkn: String,
    zgrup: String,
    mgrup: String,
    uzawe: String,
    qsrec: String,
    qsbgr: String,
    qland: String,
    xedip: String,
    frgrp: String,
    togrr: String,
    tlfxs: String,
    intad: String,
    xlfzb: String,
    guzte: String,
    gricd: String,
    gridt: String,
    xausz: String,
    cerdt: String,
    confs: String,
    updat: String,
    uptim: String,
    nodel: String,
    tlfns: String,
    avsnd: String,
    ad_hash: String,
    cvp_xblck_b: String,
    ciiucode: String,
    zbokd: String,
    zqsskz: String,
    zqszdt: String,
    zqsznr: String,
    zmindat: String,
    j_sc_subcontype: String,
    j_sc_compdate: String,
    j_sc_offsm: String,
    j_sc_offsr: String,
    @Decimal(6, 3) basis_pnt: java.math.BigDecimal,
    gmvkzk: String,
    prepay_relevant: String,
    assign_test: String
) extends Entity

object lfb1 extends TableSpec[SrLfb1] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_lfb1] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_lfb1] = sr_raw_lfb1

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("lifnr", coalesce(col("lifnr_string"), lit(""))),
    ("bukrs", coalesce(col("bukrs_string"), lit(""))),
    ("pernr", col("pernr_string")),
    ("erdat", col("erdat_string")),
    ("ernam", col("ernam_string")),
    ("sperr", col("sperr_string")),
    ("loevm", col("loevm_string")),
    ("zuawa", col("zuawa_string")),
    ("akont", col("akont_string")),
    ("begru", col("begru_string")),
    ("vzskz", col("vzskz_string")),
    ("zwels", col("zwels_string")),
    ("xverr", col("xverr_string")),
    ("zahls", col("zahls_string")),
    ("zterm", col("zterm_string")),
    ("eikto", col("eikto_string")),
    ("zsabe", col("zsabe_string")),
    ("kverm", col("kverm_string")),
    ("fdgrv", col("fdgrv_string")),
    ("busab", col("busab_string")),
    ("lnrze", col("lnrze_string")),
    ("lnrzb", col("lnrzb_string")),
    ("zindt", col("zindt_string")),
    ("zinrt", col("zinrt_string")),
    ("datlz", col("datlz_string")),
    ("xdezv", col("xdezv_string")),
    ("webtr", col("webtr_decimal_13_2")),
    ("kultg", col("kultg_decimal_3_0")),
    ("reprf", col("reprf_string")),
    ("togru", col("togru_string")),
    ("hbkid", col("hbkid_string")),
    ("xpore", col("xpore_string")),
    ("qsznr", col("qsznr_string")),
    ("qszdt", col("qszdt_string")),
    ("qsskz", col("qsskz_string")),
    ("blnkz", col("blnkz_string")),
    ("mindk", col("mindk_string")),
    ("altkn", col("altkn_string")),
    ("zgrup", col("zgrup_string")),
    ("mgrup", col("mgrup_string")),
    ("uzawe", col("uzawe_string")),
    ("qsrec", col("qsrec_string")),
    ("qsbgr", col("qsbgr_string")),
    ("qland", col("qland_string")),
    ("xedip", col("xedip_string")),
    ("frgrp", col("frgrp_string")),
    ("togrr", col("togrr_string")),
    ("tlfxs", col("tlfxs_string")),
    ("intad", col("intad_string")),
    ("xlfzb", col("xlfzb_string")),
    ("guzte", col("guzte_string")),
    ("gricd", col("gricd_string")),
    ("gridt", col("gridt_string")),
    ("xausz", col("xausz_string")),
    ("cerdt", col("cerdt_string")),
    ("confs", col("confs_string")),
    ("updat", col("updat_string")),
    ("uptim", col("uptim_string")),
    ("nodel", col("nodel_string")),
    ("tlfns", col("tlfns_string")),
    ("avsnd", col("avsnd_string")),
    ("ad_hash", col("ad_hash_string")),
    ("cvp_xblck_b", col("cvp_xblck_b_string")),
    ("ciiucode", col("ciiucode_string")),
    ("zbokd", col("zbokd_string")),
    ("zqsskz", col("zqsskz_string")),
    ("zqszdt", col("zqszdt_string")),
    ("zqsznr", col("zqsznr_string")),
    ("zmindat", col("zmindat_string")),
    ("j_sc_subcontype", col("j_sc_subcontype_string")),
    ("j_sc_compdate", col("j_sc_compdate_string")),
    ("j_sc_offsm", col("j_sc_offsm_string")),
    ("j_sc_offsr", col("j_sc_offsr_string")),
    ("basis_pnt", col("basis_pnt_decimal_6_3")),
    ("gmvkzk", col("gmvkzk_string")),
    ("prepay_relevant", col("prepay_relevant_string")),
    ("assign_test", col("assign_test_string"))
  )
}
