// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_epp

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_epp.{lfm1 => sr_raw_lfm1}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrLfm1(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK lifnr: String,
    @PK ekorg: String,
    erdat: String,
    ernam: String,
    sperm: String,
    loevm: String,
    lfabc: String,
    waers: String,
    verkf: String,
    telf1: String,
    @Decimal(13, 2) minbw: java.math.BigDecimal,
    zterm: String,
    inco1: String,
    inco2: String,
    webre: String,
    kzabs: String,
    kalsk: String,
    kzaut: String,
    expvz: String,
    zolla: String,
    meprf: String,
    ekgrp: String,
    xersy: String,
    @Decimal(3, 0) plifz: java.math.BigDecimal,
    mrppp: String,
    lfrhy: String,
    libes: String,
    lipre: String,
    liser: String,
    incov: String,
    inco2_l: String,
    inco3_l: String,
    prfre: String,
    nrgew: String,
    boind: String,
    blind: String,
    kzret: String,
    skrit: String,
    bstae: String,
    rdprf: String,
    megru: String,
    @Decimal(4, 1) vensl: java.math.BigDecimal,
    bopnr: String,
    xersr: String,
    eikto: String,
    abueb: String,
    paprf: String,
    agrel: String,
    xnbwy: String,
    vsbed: String,
    lebre: String,
    bolre: String,
    umsae: String,
    vendor_rma_req: String,
    j_1nboesl: String,
    aubel: String,
    valid_pro: String,
    @Decimal(13, 2) hscabs: java.math.BigDecimal,
    @Decimal(5, 2) hscpe: java.math.BigDecimal,
    @Decimal(13, 2) hscmin: java.math.BigDecimal,
    @Decimal(13, 2) hscmax: java.math.BigDecimal,
    fsh_sc_cid: String,
    fsh_vas_detc: String,
    upprs: String,
    activity_profil: String,
    transport_chain: String,
    @Decimal(3, 0) staging_time: java.math.BigDecimal,
    yfta: String
) extends Entity

object lfm1 extends TableSpec[SrLfm1] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_lfm1] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_lfm1] = sr_raw_lfm1

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("lifnr", coalesce(col("lifnr_string"), lit(""))),
    ("ekorg", coalesce(col("ekorg_string"), lit(""))),
    ("erdat", col("erdat_string")),
    ("ernam", col("ernam_string")),
    ("sperm", col("sperm_string")),
    ("loevm", col("loevm_string")),
    ("lfabc", col("lfabc_string")),
    ("waers", col("waers_string")),
    ("verkf", col("verkf_string")),
    ("telf1", col("telf1_string")),
    ("minbw", col("minbw_decimal_13_2")),
    ("zterm", col("zterm_string")),
    ("inco1", col("inco1_string")),
    ("inco2", col("inco2_string")),
    ("webre", col("webre_string")),
    ("kzabs", col("kzabs_string")),
    ("kalsk", col("kalsk_string")),
    ("kzaut", col("kzaut_string")),
    ("expvz", col("expvz_string")),
    ("zolla", col("zolla_string")),
    ("meprf", col("meprf_string")),
    ("ekgrp", col("ekgrp_string")),
    ("xersy", col("xersy_string")),
    ("plifz", col("plifz_decimal_3_0")),
    ("mrppp", col("mrppp_string")),
    ("lfrhy", col("lfrhy_string")),
    ("libes", col("libes_string")),
    ("lipre", col("lipre_string")),
    ("liser", col("liser_string")),
    ("incov", col("incov_string")),
    ("inco2_l", col("inco2_l_string")),
    ("inco3_l", col("inco3_l_string")),
    ("prfre", col("prfre_string")),
    ("nrgew", col("nrgew_string")),
    ("boind", col("boind_string")),
    ("blind", col("blind_string")),
    ("kzret", col("kzret_string")),
    ("skrit", col("skrit_string")),
    ("bstae", col("bstae_string")),
    ("rdprf", col("rdprf_string")),
    ("megru", col("megru_string")),
    ("vensl", col("vensl_decimal_4_1")),
    ("bopnr", col("bopnr_string")),
    ("xersr", col("xersr_string")),
    ("eikto", col("eikto_string")),
    ("abueb", col("abueb_string")),
    ("paprf", col("paprf_string")),
    ("agrel", col("agrel_string")),
    ("xnbwy", col("xnbwy_string")),
    ("vsbed", col("vsbed_string")),
    ("lebre", col("lebre_string")),
    ("bolre", col("bolre_string")),
    ("umsae", col("umsae_string")),
    ("vendor_rma_req", col("vendor_rma_req_string")),
    ("j_1nboesl", col("j_1nboesl_string")),
    ("aubel", col("aubel_string")),
    ("valid_pro", col("valid_pro_string")),
    ("hscabs", col("hscabs_decimal_13_2")),
    ("hscpe", col("hscpe_decimal_5_2")),
    ("hscmin", col("hscmin_decimal_13_2")),
    ("hscmax", col("hscmax_decimal_13_2")),
    ("fsh_sc_cid", col("fsh_sc_cid_string")),
    ("fsh_vas_detc", col("fsh_vas_detc_string")),
    ("upprs", col("upprs_string")),
    ("activity_profil", col("activity_profil_string")),
    ("transport_chain", col("transport_chain_string")),
    ("staging_time", col("staging_time_decimal_3_0")),
    ("yfta", col("yfta_string"))
  )
}
