// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_epp

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_epp.{mard => sr_raw_mard}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrMard(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK matnr: String,
    @PK werks: String,
    @PK lgort: String,
    pstat: String,
    lvorm: String,
    lfgja: String,
    lfmon: String,
    sperr: String,
    @Decimal(13, 3) labst: java.math.BigDecimal,
    @Decimal(13, 3) umlme: java.math.BigDecimal,
    @Decimal(13, 3) insme: java.math.BigDecimal,
    @Decimal(13, 3) einme: java.math.BigDecimal,
    @Decimal(13, 3) speme: java.math.BigDecimal,
    @Decimal(13, 3) retme: java.math.BigDecimal,
    @Decimal(13, 3) vmlab: java.math.BigDecimal,
    @Decimal(13, 3) vmuml: java.math.BigDecimal,
    @Decimal(13, 3) vmins: java.math.BigDecimal,
    @Decimal(13, 3) vmein: java.math.BigDecimal,
    @Decimal(13, 3) vmspe: java.math.BigDecimal,
    @Decimal(13, 3) vmret: java.math.BigDecimal,
    kzill: String,
    kzilq: String,
    kzile: String,
    kzils: String,
    kzvll: String,
    kzvlq: String,
    kzvle: String,
    kzvls: String,
    diskz: String,
    lsobs: String,
    @Decimal(13, 3) lminb: java.math.BigDecimal,
    @Decimal(13, 3) lbstf: java.math.BigDecimal,
    herkl: String,
    exppg: String,
    exver: String,
    lgpbe: String,
    @Decimal(13, 3) klabs: java.math.BigDecimal,
    @Decimal(13, 3) kinsm: java.math.BigDecimal,
    @Decimal(13, 3) keinm: java.math.BigDecimal,
    @Decimal(13, 3) kspem: java.math.BigDecimal,
    dlinl: String,
    prctl: String,
    ersda: String,
    @Decimal(13, 2) vklab: java.math.BigDecimal,
    @Decimal(13, 2) vkuml: java.math.BigDecimal,
    lwmkb: String,
    bskrf: Double,
    mdrue: String,
    mdjin: String
) extends Entity

object mard extends TableSpec[SrMard] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_mard] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_mard] = sr_raw_mard

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("matnr", coalesce(col("matnr_string"), lit(""))),
    ("werks", coalesce(col("werks_string"), lit(""))),
    ("lgort", coalesce(col("lgort_string"), lit(""))),
    ("pstat", col("pstat_string")),
    ("lvorm", col("lvorm_string")),
    ("lfgja", col("lfgja_string")),
    ("lfmon", col("lfmon_string")),
    ("sperr", col("sperr_string")),
    ("labst", col("labst_decimal_13_3")),
    ("umlme", col("umlme_decimal_13_3")),
    ("insme", col("insme_decimal_13_3")),
    ("einme", col("einme_decimal_13_3")),
    ("speme", col("speme_decimal_13_3")),
    ("retme", col("retme_decimal_13_3")),
    ("vmlab", col("vmlab_decimal_13_3")),
    ("vmuml", col("vmuml_decimal_13_3")),
    ("vmins", col("vmins_decimal_13_3")),
    ("vmein", col("vmein_decimal_13_3")),
    ("vmspe", col("vmspe_decimal_13_3")),
    ("vmret", col("vmret_decimal_13_3")),
    ("kzill", col("kzill_string")),
    ("kzilq", col("kzilq_string")),
    ("kzile", col("kzile_string")),
    ("kzils", col("kzils_string")),
    ("kzvll", col("kzvll_string")),
    ("kzvlq", col("kzvlq_string")),
    ("kzvle", col("kzvle_string")),
    ("kzvls", col("kzvls_string")),
    ("diskz", col("diskz_string")),
    ("lsobs", col("lsobs_string")),
    ("lminb", col("lminb_decimal_13_3")),
    ("lbstf", col("lbstf_decimal_13_3")),
    ("herkl", col("herkl_string")),
    ("exppg", col("exppg_string")),
    ("exver", col("exver_string")),
    ("lgpbe", col("lgpbe_string")),
    ("klabs", col("klabs_decimal_13_3")),
    ("kinsm", col("kinsm_decimal_13_3")),
    ("keinm", col("keinm_decimal_13_3")),
    ("kspem", col("kspem_decimal_13_3")),
    ("dlinl", col("dlinl_string")),
    ("prctl", col("prctl_string")),
    ("ersda", col("ersda_string")),
    ("vklab", col("vklab_decimal_13_2")),
    ("vkuml", col("vkuml_decimal_13_2")),
    ("lwmkb", col("lwmkb_string")),
    ("bskrf", coalesce(col("bskrf_double"), lit(0.0))),
    ("mdrue", col("mdrue_string")),
    ("mdjin", col("mdjin_string"))
  )
}
