// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_epp

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_epp.{plpo => sr_raw_plpo}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrPlpo(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK plnty: String,
    @PK plnnr: String,
    @PK plnkn: String,
    @PK zaehl: String,
    datuv: String,
    techv: String,
    aennr: String,
    loekz: String,
    parkz: String,
    andat: String,
    annam: String,
    aedat: String,
    aenam: String,
    sumnr: String,
    vornr: String,
    steus: String,
    arbid: String,
    objty: String,
    werks: String,
    ktsch: String,
    ltxa1: String,
    ltxa2: String,
    txtsp: String,
    vplty: String,
    vplnr: String,
    vplal: String,
    vplfl: String,
    @Decimal(3, 0) vintv: java.math.BigDecimal,
    meinh: String,
    @Decimal(5, 0) umren: java.math.BigDecimal,
    @Decimal(5, 0) umrez: java.math.BigDecimal,
    @Decimal(13, 3) bmsch: java.math.BigDecimal,
    @Decimal(9, 3) zmerh: java.math.BigDecimal,
    zeier: String,
    lar01: String,
    vge01: String,
    @Decimal(9, 3) vgw01: java.math.BigDecimal,
    lar02: String,
    vge02: String,
    @Decimal(9, 3) vgw02: java.math.BigDecimal,
    lar03: String,
    vge03: String,
    @Decimal(9, 3) vgw03: java.math.BigDecimal,
    lar04: String,
    vge04: String,
    @Decimal(9, 3) vgw04: java.math.BigDecimal,
    lar05: String,
    vge05: String,
    @Decimal(9, 3) vgw05: java.math.BigDecimal,
    lar06: String,
    vge06: String,
    @Decimal(9, 3) vgw06: java.math.BigDecimal,
    zerma: String,
    zgdat: String,
    zcode: String,
    zulnr: String,
    rsanz: String,
    pdest: String,
    @Decimal(3, 0) loanz: java.math.BigDecimal,
    loart: String,
    qualf: String,
    @Decimal(5, 2) anzma: java.math.BigDecimal,
    rfgrp: String,
    rfsch: String,
    rasch: String,
    @Decimal(5, 3) aufak: java.math.BigDecimal,
    logrp: String,
    uemus: String,
    uekan: String,
    flies: String,
    zeimu: String,
    @Decimal(9, 3) zminu: java.math.BigDecimal,
    @Decimal(13, 3) minwe: java.math.BigDecimal,
    spmus: String,
    @Decimal(3, 0) splim: java.math.BigDecimal,
    zeimb: String,
    @Decimal(9, 3) zminb: java.math.BigDecimal,
    zeilm: String,
    @Decimal(9, 3) zlmax: java.math.BigDecimal,
    zeilp: String,
    @Decimal(9, 3) zlpro: java.math.BigDecimal,
    zeiwn: String,
    @Decimal(9, 3) zwnor: java.math.BigDecimal,
    zeiwm: String,
    @Decimal(9, 3) zwmin: java.math.BigDecimal,
    zeitn: String,
    @Decimal(9, 3) ztnor: java.math.BigDecimal,
    zeitm: String,
    @Decimal(9, 3) ztmin: java.math.BigDecimal,
    ablipkz: String,
    rstra: String,
    bzoffb: String,
    @Decimal(5, 0) offstb: java.math.BigDecimal,
    ehoffb: String,
    bzoffe: String,
    @Decimal(5, 0) offste: java.math.BigDecimal,
    ehoffe: String,
    sortl: String,
    lifnr: String,
    @Decimal(3, 0) plifz: java.math.BigDecimal,
    @Decimal(11, 2) preis: java.math.BigDecimal,
    @Decimal(5, 0) peinh: java.math.BigDecimal,
    sakto: String,
    waers: String,
    infnr: String,
    esokz: String,
    ekorg: String,
    ekgrp: String,
    kzlgf: String,
    matkl: String,
    @Decimal(5, 1) dauno: java.math.BigDecimal,
    daune: String,
    @Decimal(5, 1) daumi: java.math.BigDecimal,
    daume: String,
    ddehn: String,
    einsa: String,
    einse: String,
    @Decimal(7, 1) arbei: java.math.BigDecimal,
    arbeh: String,
    anzzl: Int,
    prznt: Int,
    vertl: String,
    mlstn: String,
    pprio: String,
    bukrs: String,
    slwid: String,
    usr00: String,
    usr01: String,
    usr02: String,
    usr03: String,
    @Decimal(13, 3) usr04: java.math.BigDecimal,
    use04: String,
    @Decimal(13, 3) usr05: java.math.BigDecimal,
    use05: String,
    @Decimal(13, 3) usr06: java.math.BigDecimal,
    use06: String,
    @Decimal(13, 3) usr07: java.math.BigDecimal,
    use07: String,
    usr08: String,
    usr09: String,
    usr10: String,
    usr11: String,
    anfko: String,
    anfkokrs: String,
    kapar: String,
    indet: String,
    larnt: String,
    @Decimal(11, 2) prkst: java.math.BigDecimal,
    @Decimal(5, 2) qrastermng: java.math.BigDecimal,
    qrastereh: String,
    anlzu: String,
    istru: String,
    istty: String,
    istnr: String,
    istkn: String,
    istpo: String,
    iupoz: String,
    ebort: String,
    kalid: String,
    frsp: String,
    vertn: String,
    zgr01: String,
    zgr02: String,
    zgr03: String,
    zgr04: String,
    zgr05: String,
    zgr06: String,
    mdlid: String,
    ruzus: String,
    bmeih: String,
    @Decimal(13, 3) bmvrg: java.math.BigDecimal,
    ckselkz: String,
    kalkz: String,
    nprio: String,
    pvzkn: String,
    phflg: String,
    phseq: String,
    knobj: String,
    erfsicht: String,
    pspnr: String,
    qlotype: String,
    qlobjektid: String,
    qlkapar: String,
    qkzprzeit: String,
    qkzztmg1: String,
    qkzprmeng: String,
    qkzprfrei: String,
    qrastzeht: String,
    @Decimal(5, 2) qrastzfak: java.math.BigDecimal,
    @Decimal(13, 3) qrastmeng: java.math.BigDecimal,
    qppktabs: String,
    krit1: String,
    classid: String,
    packno: String,
    ebeln: String,
    ebelp: String,
    capoc: String,
    flg_captxt: String,
    @Decimal(8, 0) cn_weight: java.math.BigDecimal,
    qkztlsbest: String,
    @Decimal(3, 0) aufkt: java.math.BigDecimal,
    @Decimal(5, 2) dafkt: java.math.BigDecimal,
    @Decimal(5, 3) rwfak: java.math.BigDecimal,
    aaufg: String,
    verdart: String,
    uavo_aufl: String,
    frdlb: String,
    qpart: String,
    prz01: String,
    takt: String,
    oprid: String,
    nvadd: String,
    @Decimal(8, 0) evgew: java.math.BigDecimal,
    rfpnt: String,
    flg_tsk_group: String,
    adpsp: String,
    tplnr: String,
    equnr: String,
    mes_operid: String,
    mes_stepid: String,
    manu_proc: String,
    _sapmp_met_lrch: String,
    @Decimal(13, 3) _sapmp_max_fertl: java.math.BigDecimal,
    @Decimal(13, 3) _sapmp_fix_as_j: java.math.BigDecimal,
    @Decimal(13, 3) _sapmp_fix_as_e: java.math.BigDecimal,
    @Decimal(13, 3) _sapmp_fix_as_l: java.math.BigDecimal,
    _sapmp_abl_zahl: String,
    subplnal: String,
    subplnnr: String,
    subplnty: String,
    xexcltl: String,
    rtype: String,
    yauto: String,
    ydeflt: String
) extends Entity

object plpo extends TableSpec[SrPlpo] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_plpo] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_epp.E_plpo] = sr_raw_plpo

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("plnty", coalesce(col("plnty_string"), lit(""))),
    ("plnnr", coalesce(col("plnnr_string"), lit(""))),
    ("plnkn", coalesce(col("plnkn_string"), lit(""))),
    ("zaehl", coalesce(col("zaehl_string"), lit(""))),
    ("datuv", col("datuv_string")),
    ("techv", col("techv_string")),
    ("aennr", col("aennr_string")),
    ("loekz", col("loekz_string")),
    ("parkz", col("parkz_string")),
    ("andat", col("andat_string")),
    ("annam", col("annam_string")),
    ("aedat", col("aedat_string")),
    ("aenam", col("aenam_string")),
    ("sumnr", col("sumnr_string")),
    ("vornr", col("vornr_string")),
    ("steus", col("steus_string")),
    ("arbid", col("arbid_string")),
    ("objty", col("objty_string")),
    ("werks", col("werks_string")),
    ("ktsch", col("ktsch_string")),
    ("ltxa1", col("ltxa1_string")),
    ("ltxa2", col("ltxa2_string")),
    ("txtsp", col("txtsp_string")),
    ("vplty", col("vplty_string")),
    ("vplnr", col("vplnr_string")),
    ("vplal", col("vplal_string")),
    ("vplfl", col("vplfl_string")),
    ("vintv", col("vintv_decimal_3_0")),
    ("meinh", col("meinh_string")),
    ("umren", col("umren_decimal_5_0")),
    ("umrez", col("umrez_decimal_5_0")),
    ("bmsch", col("bmsch_decimal_13_3")),
    ("zmerh", col("zmerh_decimal_9_3")),
    ("zeier", col("zeier_string")),
    ("lar01", col("lar01_string")),
    ("vge01", col("vge01_string")),
    ("vgw01", col("vgw01_decimal_9_3")),
    ("lar02", col("lar02_string")),
    ("vge02", col("vge02_string")),
    ("vgw02", col("vgw02_decimal_9_3")),
    ("lar03", col("lar03_string")),
    ("vge03", col("vge03_string")),
    ("vgw03", col("vgw03_decimal_9_3")),
    ("lar04", col("lar04_string")),
    ("vge04", col("vge04_string")),
    ("vgw04", col("vgw04_decimal_9_3")),
    ("lar05", col("lar05_string")),
    ("vge05", col("vge05_string")),
    ("vgw05", col("vgw05_decimal_9_3")),
    ("lar06", col("lar06_string")),
    ("vge06", col("vge06_string")),
    ("vgw06", col("vgw06_decimal_9_3")),
    ("zerma", col("zerma_string")),
    ("zgdat", col("zgdat_string")),
    ("zcode", col("zcode_string")),
    ("zulnr", col("zulnr_string")),
    ("rsanz", col("rsanz_string")),
    ("pdest", col("pdest_string")),
    ("loanz", col("loanz_decimal_3_0")),
    ("loart", col("loart_string")),
    ("qualf", col("qualf_string")),
    ("anzma", col("anzma_decimal_5_2")),
    ("rfgrp", col("rfgrp_string")),
    ("rfsch", col("rfsch_string")),
    ("rasch", col("rasch_string")),
    ("aufak", col("aufak_decimal_5_3")),
    ("logrp", col("logrp_string")),
    ("uemus", col("uemus_string")),
    ("uekan", col("uekan_string")),
    ("flies", col("flies_string")),
    ("zeimu", col("zeimu_string")),
    ("zminu", col("zminu_decimal_9_3")),
    ("minwe", col("minwe_decimal_13_3")),
    ("spmus", col("spmus_string")),
    ("splim", col("splim_decimal_3_0")),
    ("zeimb", col("zeimb_string")),
    ("zminb", col("zminb_decimal_9_3")),
    ("zeilm", col("zeilm_string")),
    ("zlmax", col("zlmax_decimal_9_3")),
    ("zeilp", col("zeilp_string")),
    ("zlpro", col("zlpro_decimal_9_3")),
    ("zeiwn", col("zeiwn_string")),
    ("zwnor", col("zwnor_decimal_9_3")),
    ("zeiwm", col("zeiwm_string")),
    ("zwmin", col("zwmin_decimal_9_3")),
    ("zeitn", col("zeitn_string")),
    ("ztnor", col("ztnor_decimal_9_3")),
    ("zeitm", col("zeitm_string")),
    ("ztmin", col("ztmin_decimal_9_3")),
    ("ablipkz", col("ablipkz_string")),
    ("rstra", col("rstra_string")),
    ("bzoffb", col("bzoffb_string")),
    ("offstb", col("offstb_decimal_5_0")),
    ("ehoffb", col("ehoffb_string")),
    ("bzoffe", col("bzoffe_string")),
    ("offste", col("offste_decimal_5_0")),
    ("ehoffe", col("ehoffe_string")),
    ("sortl", col("sortl_string")),
    ("lifnr", col("lifnr_string")),
    ("plifz", col("plifz_decimal_3_0")),
    ("preis", col("preis_decimal_11_2")),
    ("peinh", col("peinh_decimal_5_0")),
    ("sakto", col("sakto_string")),
    ("waers", col("waers_string")),
    ("infnr", col("infnr_string")),
    ("esokz", col("esokz_string")),
    ("ekorg", col("ekorg_string")),
    ("ekgrp", col("ekgrp_string")),
    ("kzlgf", col("kzlgf_string")),
    ("matkl", col("matkl_string")),
    ("dauno", col("dauno_decimal_5_1")),
    ("daune", col("daune_string")),
    ("daumi", col("daumi_decimal_5_1")),
    ("daume", col("daume_string")),
    ("ddehn", col("ddehn_string")),
    ("einsa", col("einsa_string")),
    ("einse", col("einse_string")),
    ("arbei", col("arbei_decimal_7_1")),
    ("arbeh", col("arbeh_string")),
    ("anzzl", coalesce(col("anzzl_int"), lit(0))),
    ("prznt", coalesce(col("prznt_int"), lit(0))),
    ("vertl", col("vertl_string")),
    ("mlstn", col("mlstn_string")),
    ("pprio", col("pprio_string")),
    ("bukrs", col("bukrs_string")),
    ("slwid", col("slwid_string")),
    ("usr00", col("usr00_string")),
    ("usr01", col("usr01_string")),
    ("usr02", col("usr02_string")),
    ("usr03", col("usr03_string")),
    ("usr04", col("usr04_decimal_13_3")),
    ("use04", col("use04_string")),
    ("usr05", col("usr05_decimal_13_3")),
    ("use05", col("use05_string")),
    ("usr06", col("usr06_decimal_13_3")),
    ("use06", col("use06_string")),
    ("usr07", col("usr07_decimal_13_3")),
    ("use07", col("use07_string")),
    ("usr08", col("usr08_string")),
    ("usr09", col("usr09_string")),
    ("usr10", col("usr10_string")),
    ("usr11", col("usr11_string")),
    ("anfko", col("anfko_string")),
    ("anfkokrs", col("anfkokrs_string")),
    ("kapar", col("kapar_string")),
    ("indet", col("indet_string")),
    ("larnt", col("larnt_string")),
    ("prkst", col("prkst_decimal_11_2")),
    ("qrastermng", col("qrastermng_decimal_5_2")),
    ("qrastereh", col("qrastereh_string")),
    ("anlzu", col("anlzu_string")),
    ("istru", col("istru_string")),
    ("istty", col("istty_string")),
    ("istnr", col("istnr_string")),
    ("istkn", col("istkn_string")),
    ("istpo", col("istpo_string")),
    ("iupoz", col("iupoz_string")),
    ("ebort", col("ebort_string")),
    ("kalid", col("kalid_string")),
    ("frsp", col("frsp_string")),
    ("vertn", col("vertn_string")),
    ("zgr01", col("zgr01_string")),
    ("zgr02", col("zgr02_string")),
    ("zgr03", col("zgr03_string")),
    ("zgr04", col("zgr04_string")),
    ("zgr05", col("zgr05_string")),
    ("zgr06", col("zgr06_string")),
    ("mdlid", col("mdlid_string")),
    ("ruzus", col("ruzus_string")),
    ("bmeih", col("bmeih_string")),
    ("bmvrg", col("bmvrg_decimal_13_3")),
    ("ckselkz", col("ckselkz_string")),
    ("kalkz", col("kalkz_string")),
    ("nprio", col("nprio_string")),
    ("pvzkn", col("pvzkn_string")),
    ("phflg", col("phflg_string")),
    ("phseq", col("phseq_string")),
    ("knobj", col("knobj_string")),
    ("erfsicht", col("erfsicht_string")),
    ("pspnr", col("pspnr_string")),
    ("qlotype", col("qlotype_string")),
    ("qlobjektid", col("qlobjektid_string")),
    ("qlkapar", col("qlkapar_string")),
    ("qkzprzeit", col("qkzprzeit_string")),
    ("qkzztmg1", col("qkzztmg1_string")),
    ("qkzprmeng", col("qkzprmeng_string")),
    ("qkzprfrei", col("qkzprfrei_string")),
    ("qrastzeht", col("qrastzeht_string")),
    ("qrastzfak", col("qrastzfak_decimal_5_2")),
    ("qrastmeng", col("qrastmeng_decimal_13_3")),
    ("qppktabs", col("qppktabs_string")),
    ("krit1", col("krit1_string")),
    ("classid", col("classid_string")),
    ("packno", col("packno_string")),
    ("ebeln", col("ebeln_string")),
    ("ebelp", col("ebelp_string")),
    ("capoc", col("capoc_string")),
    ("flg_captxt", col("flg_captxt_string")),
    ("cn_weight", col("cn_weight_decimal_8_0")),
    ("qkztlsbest", col("qkztlsbest_string")),
    ("aufkt", col("aufkt_decimal_3_0")),
    ("dafkt", col("dafkt_decimal_5_2")),
    ("rwfak", col("rwfak_decimal_5_3")),
    ("aaufg", col("aaufg_string")),
    ("verdart", col("verdart_string")),
    ("uavo_aufl", col("uavo_aufl_string")),
    ("frdlb", col("frdlb_string")),
    ("qpart", col("qpart_string")),
    ("prz01", col("prz01_string")),
    ("takt", col("takt_string")),
    ("oprid", col("oprid_string")),
    ("nvadd", col("nvadd_string")),
    ("evgew", col("evgew_decimal_8_0")),
    ("rfpnt", col("rfpnt_string")),
    ("flg_tsk_group", col("flg_tsk_group_string")),
    ("adpsp", col("adpsp_string")),
    ("tplnr", col("tplnr_string")),
    ("equnr", col("equnr_string")),
    ("mes_operid", col("mes_operid_string")),
    ("mes_stepid", col("mes_stepid_string")),
    ("manu_proc", col("manu_proc_string")),
    ("_sapmp_met_lrch", col("_sapmp_met_lrch_string")),
    ("_sapmp_max_fertl", col("_sapmp_max_fertl_decimal_13_3")),
    ("_sapmp_fix_as_j", col("_sapmp_fix_as_j_decimal_13_3")),
    ("_sapmp_fix_as_e", col("_sapmp_fix_as_e_decimal_13_3")),
    ("_sapmp_fix_as_l", col("_sapmp_fix_as_l_decimal_13_3")),
    ("_sapmp_abl_zahl", col("_sapmp_abl_zahl_string")),
    ("subplnal", col("subplnal_string")),
    ("subplnnr", col("subplnnr_string")),
    ("subplnty", col("subplnty_string")),
    ("xexcltl", col("xexcltl_string")),
    ("rtype", col("rtype_string")),
    ("yauto", col("yauto_string")),
    ("ydeflt", col("ydeflt_string"))
  )
}
