// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_epp

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_tka01(
    @PK mandt: String,
    @PK kokrs: String,
    bezei: String,
    waers: String,
    ktopl: String,
    lmona: String,
    kokfi: String,
    logsystem: String,
    alemt: String,
    md_logsystem: String,
    khinr: String,
    komp1: String,
    komp0: String,
    komp2: String,
    erkrs: String,
    dprct: String,
    phinr: String,
    pcldg: String,
    pcbel: String,
    xwbuk: String,
    bphinr: String,
    xbpale: String,
    kstar_fin: String,
    kstar_fid: String,
    pcacur: String,
    pcacurtp: String,
    pcatrcur: String,
    ctyp: String,
    rclac: String,
    blart: String,
    fikrs: String,
    rcl_primac: String,
    pca_alemt: String,
    pca_valu: String,
    cvprof: String,
    cvact: String,
    vname: String,
    pca_acc_diff: String,
    tp_valohb: String,
    defprctr: String,
    f_obsolete: String,
    auth_use_no_std: String,
    auth_use_add1: String,
    auth_use_add2: String,
    auth_ke_no_std: String,
    auth_ke_use_add1: String,
    auth_ke_use_add2: String,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String
) extends Entity

object tka01
    extends TableSpec[E_tka01](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[sr_raw.ct_gbl_epp.E_tka01] {
  override def sourceTableSpec: TableSpec[sr_raw.ct_gbl_epp.E_tka01] = sr_raw.ct_gbl_epp.tka01
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("mandt", col("mandt_string")),
    ("kokrs", col("kokrs_string")),
    ("bezei", col("bezei_string")),
    ("waers", col("waers_string")),
    ("ktopl", col("ktopl_string")),
    ("lmona", col("lmona_string")),
    ("kokfi", col("kokfi_string")),
    ("logsystem", col("logsystem_string")),
    ("alemt", col("alemt_string")),
    ("md_logsystem", col("md_logsystem_string")),
    ("khinr", col("khinr_string")),
    ("komp1", col("komp1_string")),
    ("komp0", col("komp0_string")),
    ("komp2", col("komp2_string")),
    ("erkrs", col("erkrs_string")),
    ("dprct", col("dprct_string")),
    ("phinr", col("phinr_string")),
    ("pcldg", col("pcldg_string")),
    ("pcbel", col("pcbel_string")),
    ("xwbuk", col("xwbuk_string")),
    ("bphinr", col("bphinr_string")),
    ("xbpale", col("xbpale_string")),
    ("kstar_fin", col("kstar_fin_string")),
    ("kstar_fid", col("kstar_fid_string")),
    ("pcacur", col("pcacur_string")),
    ("pcacurtp", col("pcacurtp_string")),
    ("pcatrcur", col("pcatrcur_string")),
    ("ctyp", col("ctyp_string")),
    ("rclac", col("rclac_string")),
    ("blart", col("blart_string")),
    ("fikrs", col("fikrs_string")),
    ("rcl_primac", col("rcl_primac_string")),
    ("pca_alemt", col("pca_alemt_string")),
    ("pca_valu", col("pca_valu_string")),
    ("cvprof", col("cvprof_string")),
    ("cvact", col("cvact_string")),
    ("vname", col("vname_string")),
    ("pca_acc_diff", col("pca_acc_diff_string")),
    ("tp_valohb", col("tp_valohb_string")),
    ("defprctr", col("defprctr_string")),
    ("f_obsolete", col("f_obsolete_string")),
    ("auth_use_no_std", col("auth_use_no_std_string")),
    ("auth_use_add1", col("auth_use_add1_string")),
    ("auth_use_add2", col("auth_use_add2_string")),
    ("auth_ke_no_std", col("auth_ke_no_std_string")),
    ("auth_ke_use_add1", col("auth_ke_use_add1_string")),
    ("auth_ke_use_add2", col("auth_ke_use_add2_string"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_tka01(prefix: String) extends ColumnWithNameAccessor {
  val mandt: ColumnWithName = ColumnWithName(prefix + "mandt")
  val kokrs: ColumnWithName = ColumnWithName(prefix + "kokrs")
  val bezei: ColumnWithName = ColumnWithName(prefix + "bezei")
  val waers: ColumnWithName = ColumnWithName(prefix + "waers")
  val ktopl: ColumnWithName = ColumnWithName(prefix + "ktopl")
  val lmona: ColumnWithName = ColumnWithName(prefix + "lmona")
  val kokfi: ColumnWithName = ColumnWithName(prefix + "kokfi")
  val logsystem: ColumnWithName = ColumnWithName(prefix + "logsystem")
  val alemt: ColumnWithName = ColumnWithName(prefix + "alemt")
  val md_logsystem: ColumnWithName = ColumnWithName(prefix + "md_logsystem")
  val khinr: ColumnWithName = ColumnWithName(prefix + "khinr")
  val komp1: ColumnWithName = ColumnWithName(prefix + "komp1")
  val komp0: ColumnWithName = ColumnWithName(prefix + "komp0")
  val komp2: ColumnWithName = ColumnWithName(prefix + "komp2")
  val erkrs: ColumnWithName = ColumnWithName(prefix + "erkrs")
  val dprct: ColumnWithName = ColumnWithName(prefix + "dprct")
  val phinr: ColumnWithName = ColumnWithName(prefix + "phinr")
  val pcldg: ColumnWithName = ColumnWithName(prefix + "pcldg")
  val pcbel: ColumnWithName = ColumnWithName(prefix + "pcbel")
  val xwbuk: ColumnWithName = ColumnWithName(prefix + "xwbuk")
  val bphinr: ColumnWithName = ColumnWithName(prefix + "bphinr")
  val xbpale: ColumnWithName = ColumnWithName(prefix + "xbpale")
  val kstar_fin: ColumnWithName = ColumnWithName(prefix + "kstar_fin")
  val kstar_fid: ColumnWithName = ColumnWithName(prefix + "kstar_fid")
  val pcacur: ColumnWithName = ColumnWithName(prefix + "pcacur")
  val pcacurtp: ColumnWithName = ColumnWithName(prefix + "pcacurtp")
  val pcatrcur: ColumnWithName = ColumnWithName(prefix + "pcatrcur")
  val ctyp: ColumnWithName = ColumnWithName(prefix + "ctyp")
  val rclac: ColumnWithName = ColumnWithName(prefix + "rclac")
  val blart: ColumnWithName = ColumnWithName(prefix + "blart")
  val fikrs: ColumnWithName = ColumnWithName(prefix + "fikrs")
  val rcl_primac: ColumnWithName = ColumnWithName(prefix + "rcl_primac")
  val pca_alemt: ColumnWithName = ColumnWithName(prefix + "pca_alemt")
  val pca_valu: ColumnWithName = ColumnWithName(prefix + "pca_valu")
  val cvprof: ColumnWithName = ColumnWithName(prefix + "cvprof")
  val cvact: ColumnWithName = ColumnWithName(prefix + "cvact")
  val vname: ColumnWithName = ColumnWithName(prefix + "vname")
  val pca_acc_diff: ColumnWithName = ColumnWithName(prefix + "pca_acc_diff")
  val tp_valohb: ColumnWithName = ColumnWithName(prefix + "tp_valohb")
  val defprctr: ColumnWithName = ColumnWithName(prefix + "defprctr")
  val f_obsolete: ColumnWithName = ColumnWithName(prefix + "f_obsolete")
  val auth_use_no_std: ColumnWithName = ColumnWithName(prefix + "auth_use_no_std")
  val auth_use_add1: ColumnWithName = ColumnWithName(prefix + "auth_use_add1")
  val auth_use_add2: ColumnWithName = ColumnWithName(prefix + "auth_use_add2")
  val auth_ke_no_std: ColumnWithName = ColumnWithName(prefix + "auth_ke_no_std")
  val auth_ke_use_add1: ColumnWithName = ColumnWithName(prefix + "auth_ke_use_add1")
  val auth_ke_use_add2: ColumnWithName = ColumnWithName(prefix + "auth_ke_use_add2")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
}

object C_tka01 extends C_tka01("") {
  def as(alias: String): C_tka01 = new C_tka01(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
