import sbt._
import sbt.Keys._
import sbtassembly.AssemblyPlugin
import sbtassembly.AssemblyPlugin.autoImport._

object DBX_ASSEMBLY_17_3 extends AutoPlugin {

  override def requires = AssemblyPlugin
  override def trigger = allRequirements

  object autoImport {
    // pro Projekt anpassbar:
    val dbxShadedLibs = settingKey[Seq[ModuleID]]("Libs, die in DBX JARs geshadet werden")
  }
  import autoImport._

  override def projectSettings: Seq[Def.Setting[_]] = Seq(
    // Defaultwert, falls ein Projekt dbxShadedLibs nicht explizit setzt
    dbxShadedLibs := Seq.empty,

    // Shade-Regeln
    assembly / assemblyShadeRules ++= dbxShadedLibs.value.map { moduleID => ShadeRule.rename("*.**" -> "ct.dna.shaded.@0").inLibrary(moduleID) },

    // Excluded JARs (fast 1:1 aus deiner assembly.sbt übernommen,
    // aber parametrisiert über dbxIncludedLibs/dbxShadedLibs)
    assembly / assemblyExcludedJars := {

      val log = streams.value.log
      val cp = (assembly / fullClasspath).value

      val DBR_libs = dbxIncludedLibs.map(m => (m.organization, m.name) -> m.revision).toMap
      val toBeShaded_libs = dbxShadedLibs.value.map(m => (m.organization, m.name) -> m.revision).toMap

      val project_libs = cp.map(_.get(moduleID.key).map { m => (m.organization, m.name) -> m.revision }.getOrElse(("", ""), "")).toMap

      val excluded_dbr_libs = project_libs.filter { case (lib, rev) => DBR_libs.getOrElse(lib, "") == rev }
      val excluded_shaded_libs = project_libs.filter { case (lib, rev) => toBeShaded_libs.getOrElse(lib, "") == rev }

      val (kept_missmatch_libs, kept_good_libs) =
        project_libs
          .filterNot { case (lib, rev) => DBR_libs.getOrElse(lib, "") == rev }
          .filterNot { case (lib, rev) => toBeShaded_libs.getOrElse(lib, "") == rev }
          .partition { case (lib, _) => DBR_libs.contains(lib) || toBeShaded_libs.contains(lib) }

      val finalExcludedJars = cp.filter(attr => attr.get(moduleID.key).exists { module => excluded_dbr_libs.contains((module.organization, module.name)) })

      def logLibs(prefix: String, libs: Map[(String, String), String]): Unit =
        libs.toSeq.sorted.map { case ((org, name), rev) => s"""$prefix "$org" % "$name" % "$rev"""" }.foreach(msg => log.info(msg))

      logLibs("Excluded (part of DBR):", excluded_dbr_libs)
      logLibs("Excluded (shaded):", excluded_shaded_libs)
      logLibs("Included:", kept_good_libs)

      if (kept_missmatch_libs.nonEmpty) {
        kept_missmatch_libs.toSeq.sorted.foreach { case ((org, name), rev) =>
          log.error(s"""Consider Shading or change dependencies: "$org" % "$name" % "$rev" - DBX rev  "${DBR_libs((org, name))}"""")
        }
        sys.error("Failing as we have conflicting versions.")
      }

      finalExcludedJars
    },

    // Merge-Strategie zentral im Plugin
    assembly / assemblyMergeStrategy := {
      case PathList("log4j2.properties") => MergeStrategy.discard

      case PathList("META-INF", "services", _*)                 => MergeStrategy.concat
      case PathList("ct", "dna", "shaded", "module-info.class") => MergeStrategy.discard
      case PathList("ct", "dna", "shaded", "LICENSE")           => MergeStrategy.discard
      case PathList("ct", "dna", "shaded", "NOTICE")            => MergeStrategy.discard
      case PathList("ct", "dna", "shaded", "META-INF", _ @_*)   => MergeStrategy.discard
      case PathList("module-info.class")                        => MergeStrategy.discard
      case PathList("LICENSE")                                  => MergeStrategy.discard
      case PathList("NOTICE")                                   => MergeStrategy.discard
      case PathList("META-INF", _ @_*)                          => MergeStrategy.discard
      case x                                                    => MergeStrategy.singleOrError
    }
  )

  // adapted for DBR 17.3 LTS
  lazy val dbxIncludedLibs: Seq[ModuleID] = Seq(
    "io.delta" % "delta-spark_2.13" % "4.0.0",
    "io.delta" % "delta-storage" % "4.0.0",
    "org.apache.spark" % "spark-common-utils_2.13" % "4.0.0",
    "org.apache.spark" % "spark-core_2.13" % "4.0.0",
    "org.apache.spark" % "spark-sql_2.13" % "4.0.0",
    "org.apache.spark" % "spark-kvstore_2.13" % "4.0.0",
    "org.apache.spark" % "spark-launcher_2.13" % "4.0.0",
    "org.apache.spark" % "spark-network-common_2.13" % "4.0.0",
    "org.apache.spark" % "spark-network-shuffle_2.13" % "4.0.0",
    "org.apache.spark" % "spark-tags_2.13" % "4.0.0",
    "org.apache.spark" % "spark-unsafe_2.13" % "4.0.0"
  ) ++ Seq(
    "antlr" % "antlr" % "2.7.7",
    "com.amazonaws" % "amazon-kinesis-client" % "1.12.0",
    "com.amazonaws" % "aws-java-sdk-autoscaling" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-cloudformation" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-cloudfront" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-cloudhsm" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-cloudsearch" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-cloudtrail" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-cloudwatch" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-cloudwatchmetrics" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-codedeploy" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-cognitoidentity" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-cognitosync" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-config" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-core" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-datapipeline" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-directconnect" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-directory" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-dynamodb" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-ec2" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-ecs" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-efs" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-elasticache" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-elasticbeanstalk" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-elasticloadbalancing" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-elastictranscoder" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-emr" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-glacier" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-glue" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-iam" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-importexport" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-kinesis" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-kms" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-lambda" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-logs" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-machinelearning" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-opsworks" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-rds" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-redshift" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-route53" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-s3" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-ses" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-simpledb" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-simpleworkflow" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-sns" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-sqs" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-ssm" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-storagegateway" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-sts" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-support" % "1.12.638",
    "com.amazonaws" % "aws-java-sdk-swf-libraries" % "1.11.22",
    "com.amazonaws" % "aws-java-sdk-workspaces" % "1.12.638",
    "com.amazonaws" % "jmespath-java" % "1.12.638",
    "com.clearspring.analytics" % "stream" % "2.9.8",
    "com.databricks" % "Rserve" % "1.8-3",
    "com.databricks" % "databricks-sdk-java" % "0.27.0",
    "com.databricks" % "jets3t" % "0.7.1-0",
    "com.databricks.scalapb" % "scalapb-runtime_2.13" % "0.4.15-11",
    "com.esotericsoftware" % "kryo-shaded" % "4.0.3",
    "com.esotericsoftware" % "minlog" % "1.3.0",
    "com.fasterxml" % "classmate" % "1.5.1",
    "com.fasterxml.jackson.core" % "jackson-annotations" % "2.18.2",
    "com.fasterxml.jackson.core" % "jackson-core" % "2.18.2",
    "com.fasterxml.jackson.core" % "jackson-databind" % "2.18.2",
    "com.fasterxml.jackson.dataformat" % "jackson-dataformat-cbor" % "2.18.2",
    "com.fasterxml.jackson.dataformat" % "jackson-dataformat-yaml" % "2.15.2",
    "com.fasterxml.jackson.datatype" % "jackson-datatype-joda" % "2.18.2",
    "com.fasterxml.jackson.datatype" % "jackson-datatype-jsr310" % "2.18.2",
    "com.fasterxml.jackson.module" % "jackson-module-paranamer" % "2.18.2",
    "com.fasterxml.jackson.module" % "jackson-module-scala_2.13" % "2.18.2",
    "com.github.ben-manes.caffeine" % "caffeine" % "2.9.3",
    "com.github.blemale" % "scaffeine_2.13" % "4.1.0",
    "com.github.fommil" % "jniloader" % "1.1",
    "com.github.fommil.netlib" % "native_ref-java" % "1.1",
    "com.github.fommil.netlib" % "native_ref-java" % "1.1-natives",
    "com.github.fommil.netlib" % "native_system-java" % "1.1",
    "com.github.fommil.netlib" % "native_system-java" % "1.1-natives",
    "com.github.fommil.netlib" % "netlib-native_ref-linux-x86_64" % "1.1-natives",
    "com.github.fommil.netlib" % "netlib-native_system-linux-x86_64" % "1.1-natives",
    "com.github.luben" % "zstd-jni" % "1.5.6-10",
    "com.github.virtuald" % "curvesapi" % "1.08",
    "com.github.wendykierp" % "JTransforms" % "3.1",
    "com.google.api.grpc" % "proto-google-common-protos" % "2.5.1",
    "com.google.code.findbugs" % "jsr305" % "3.0.0",
    "com.google.code.gson" % "gson" % "2.11.0",
    "com.google.crypto.tink" % "tink" % "1.16.0",
    "com.google.errorprone" % "error_prone_annotations" % "2.36.0",
    "com.google.flatbuffers" % "flatbuffers-java" % "24.3.25",
    "com.google.guava" % "failureaccess" % "1.0.2",
    "com.google.guava" % "guava" % "33.4.0-jre",
    "com.google.guava" % "listenablefuture" % "9999.0-empty-to-avoid-conflict-with-guava",
    "com.google.j2objc" % "j2objc-annotations" % "3.0.0",
    "com.google.protobuf" % "protobuf-java" % "3.25.5",
    "com.google.protobuf" % "protobuf-java-util" % "3.25.5",
    "com.helger" % "profiler" % "1.1.1",
    "com.ibm.icu" % "icu4j" % "75.1",
    "com.jcraft" % "jsch" % "0.1.55",
    "com.lihaoyi" % "sourcecode_2.13" % "0.1.9",
    "com.microsoft.azure" % "azure-data-lake-store-sdk" % "2.3.10",
    "com.microsoft.sqlserver" % "mssql-jdbc" % "11.2.2.jre8",
    "com.microsoft.sqlserver" % "mssql-jdbc" % "11.2.3.jre8",
    "com.ning" % "compress-lzf" % "1.1.2",
    "com.sun.mail" % "javax.mail" % "1.5.2",
    "com.sun.xml.bind" % "jaxb-core" % "2.2.11",
    "com.sun.xml.bind" % "jaxb-impl" % "2.2.11",
    "com.tdunning" % "json" % "1.8",
    "com.thoughtworks.paranamer" % "paranamer" % "2.8",
    "com.trueaccord.lenses" % "lenses_2.13" % "0.4.13",
    "com.twitter" % "chill-java" % "0.10.0",
    "com.twitter" % "chill_2.13" % "0.10.0",
    "com.twitter" % "util-app_2.13" % "19.8.1",
    "com.twitter" % "util-core_2.13" % "19.8.1",
    "com.twitter" % "util-function_2.13" % "19.8.1",
    "com.twitter" % "util-jvm_2.13" % "19.8.1",
    "com.twitter" % "util-lint_2.13" % "19.8.1",
    "com.twitter" % "util-registry_2.13" % "19.8.1",
    "com.twitter" % "util-stats_2.13" % "19.8.1",
    "com.typesafe" % "config" % "1.4.3",
    "com.typesafe.scala-logging" % "scala-logging_2.13" % "3.9.2",
    "com.uber" % "h3" % "3.7.3",
    "com.univocity" % "univocity-parsers" % "2.9.1",
    "com.zaxxer" % "HikariCP" % "4.0.3",
    "com.zaxxer" % "SparseBitSet" % "1.3",
    "commons-cli" % "commons-cli" % "1.9.0",
    "commons-codec" % "commons-codec" % "1.17.2",
    "commons-collections" % "commons-collections" % "3.2.2",
    "commons-dbcp" % "commons-dbcp" % "1.4",
    "commons-fileupload" % "commons-fileupload" % "1.5",
    "commons-httpclient" % "commons-httpclient" % "3.1",
    "commons-io" % "commons-io" % "2.18.0",
    "commons-lang" % "commons-lang" % "2.6",
    "commons-logging" % "commons-logging" % "1.1.3",
    "commons-pool" % "commons-pool" % "1.5.4",
    "dev.ludovic.netlib" % "arpack" % "3.0.3",
    "dev.ludovic.netlib" % "blas" % "3.0.3",
    "dev.ludovic.netlib" % "lapack" % "3.0.3",
    "info.ganglia.gmetric4j" % "gmetric4j" % "1.0.10",
    "io.airlift" % "aircompressor" % "2.0.2",
    "io.delta" % "delta-sharing-client_2.13" % "1.3.5",
    "io.dropwizard.metrics" % "metrics-annotation" % "4.2.30",
    "io.dropwizard.metrics" % "metrics-core" % "4.2.30",
    "io.dropwizard.metrics" % "metrics-graphite" % "4.2.30",
    "io.dropwizard.metrics" % "metrics-healthchecks" % "4.2.30",
    "io.dropwizard.metrics" % "metrics-jetty9" % "4.2.30",
    "io.dropwizard.metrics" % "metrics-jmx" % "4.2.30",
    "io.dropwizard.metrics" % "metrics-json" % "4.2.30",
    "io.dropwizard.metrics" % "metrics-jvm" % "4.2.30",
    "io.dropwizard.metrics" % "metrics-servlets" % "4.2.30",
    "io.github.java-diff-utils" % "java-diff-utils" % "4.15",
    "io.netty" % "netty-all" % "4.1.118.Final",
    "io.netty" % "netty-buffer" % "4.1.118.Final",
    "io.netty" % "netty-codec" % "4.1.118.Final",
    "io.netty" % "netty-codec-http" % "4.1.118.Final",
    "io.netty" % "netty-codec-http2" % "4.1.118.Final",
    "io.netty" % "netty-codec-socks" % "4.1.118.Final",
    "io.netty" % "netty-common" % "4.1.118.Final",
    "io.netty" % "netty-handler" % "4.1.118.Final",
    "io.netty" % "netty-handler-proxy" % "4.1.118.Final",
    "io.netty" % "netty-resolver" % "4.1.118.Final",
    "io.netty" % "netty-tcnative-boringssl-static" % "2.0.70.Final",
    // "io.netty" % "netty-tcnative-boringssl-static" % "2.0.70.Final-db-r0-linux-aarch_64",
    // "io.netty" % "netty-tcnative-boringssl-static" % "2.0.70.Final-db-r0-linux-x86_64",
    // "io.netty" % "netty-tcnative-boringssl-static" % "2.0.70.Final-db-r0-osx-aarch_64",
    // "io.netty" % "netty-tcnative-boringssl-static" % "2.0.70.Final-db-r0-osx-x86_64",
    // "io.netty" % "netty-tcnative-boringssl-static" % "2.0.70.Final-db-r0-windows-x86_64",
    "io.netty" % "netty-tcnative-classes" % "2.0.70.Final",
    "io.netty" % "netty-transport" % "4.1.118.Final",
    "io.netty" % "netty-transport-classes-epoll" % "4.1.118.Final",
    "io.netty" % "netty-transport-classes-kqueue" % "4.1.118.Final",
    "io.netty" % "netty-transport-native-epoll" % "4.1.118.Final",
    // "io.netty" % "netty-transport-native-epoll" % "4.1.118.Final-linux-aarch_64",
    // "io.netty" % "netty-transport-native-epoll" % "4.1.118.Final-linux-riscv64",
    // "io.netty" % "netty-transport-native-epoll" % "4.1.118.Final-linux-x86_64",
    "io.netty" % "netty-transport-native-kqueue" % "4.1.118.Final",
    // "io.netty" % "netty-transport-native-kqueue" % "4.1.118.Final-osx-aarch_64",
    // "io.netty" % "netty-transport-native-kqueue" % "4.1.118.Final-osx-x86_64",
    "io.netty" % "netty-transport-native-unix-common" % "4.1.118.Final",
    "io.prometheus" % "simpleclient" % "0.16.1-databricks",
    "io.prometheus" % "simpleclient_common" % "0.16.1-databricks",
    "io.prometheus" % "simpleclient_dropwizard" % "0.16.1-databricks",
    "io.prometheus" % "simpleclient_pushgateway" % "0.16.1-databricks",
    "io.prometheus" % "simpleclient_servlet" % "0.16.1-databricks",
    "io.prometheus" % "simpleclient_servlet_common" % "0.16.1-databricks",
    "io.prometheus" % "simpleclient_tracer_common" % "0.16.1-databricks",
    "io.prometheus" % "simpleclient_tracer_otel" % "0.16.1-databricks",
    "io.prometheus" % "simpleclient_tracer_otel_agent" % "0.16.1-databricks",
    "io.prometheus.jmx" % "collector" % "0.18.0",
    "jakarta.annotation" % "jakarta.annotation-api" % "1.3.5",
    "jakarta.servlet" % "jakarta.servlet-api" % "4.0.3",
    "jakarta.validation" % "jakarta.validation-api" % "2.0.2",
    "jakarta.ws.rs" % "jakarta.ws.rs-api" % "2.1.6",
    "javax.activation" % "activation" % "1.1.1",
    "javax.annotation" % "javax.annotation-api" % "1.3.2",
    "javax.el" % "javax.el-api" % "2.2.4",
    "javax.jdo" % "jdo-api" % "3.0.1",
    "javax.media" % "jai_core" % "jai_core_dummy",
    "javax.transaction" % "jta" % "1.1",
    "javax.transaction" % "transaction-api" % "1.1",
    "javax.xml.bind" % "jaxb-api" % "2.2.11",
    "javolution" % "javolution" % "5.5.1",
    "jline" % "jline" % "2.14.6",
    "joda-time" % "joda-time" % "2.13.0",
    "net.java.dev.jna" % "jna" % "5.8.0",
    "net.razorvine" % "pickle" % "1.5",
    "net.sf.jpam" % "jpam" % "1.1",
    "net.sf.opencsv" % "opencsv" % "2.3",
    "net.sf.supercsv" % "super-csv" % "2.2.0",
    "net.snowflake" % "snowflake-ingest-sdk" % "0.9.6",
    "net.sourceforge.f2j" % "arpack_combined_all" % "0.1",
    "org.acplt.remotetea" % "remotetea-oncrpc" % "1.1.2",
    "org.antlr" % "ST4" % "4.0.4",
    "org.antlr" % "antlr-runtime" % "3.5.2",
    "org.antlr" % "antlr4-runtime" % "4.13.1",
    "org.antlr" % "stringtemplate" % "3.2.1",
    "org.apache.ant" % "ant" % "1.10.11",
    "org.apache.ant" % "ant-jsch" % "1.10.11",
    "org.apache.ant" % "ant-launcher" % "1.10.11",
    "org.apache.arrow" % "arrow-format" % "18.2.0",
    "org.apache.arrow" % "arrow-memory-core" % "18.2.0",
    "org.apache.arrow" % "arrow-memory-netty" % "18.2.0",
    "org.apache.arrow" % "arrow-memory-netty-buffer-patch" % "18.2.0",
    "org.apache.arrow" % "arrow-vector" % "18.2.0",
    "org.apache.avro" % "avro" % "1.12.0",
    "org.apache.avro" % "avro-ipc" % "1.12.0",
    "org.apache.avro" % "avro-mapred" % "1.12.0",
    "org.apache.commons" % "commons-collections4" % "4.4",
    "org.apache.commons" % "commons-compress" % "1.27.1",
    "org.apache.commons" % "commons-crypto" % "1.1.0",
    "org.apache.commons" % "commons-lang3" % "3.17.0",
    "org.apache.commons" % "commons-math3" % "3.6.1",
    "org.apache.commons" % "commons-text" % "1.13.0",
    "org.apache.curator" % "curator-client" % "5.7.1",
    "org.apache.curator" % "curator-framework" % "5.7.1",
    "org.apache.curator" % "curator-recipes" % "5.7.1",
    "org.apache.datasketches" % "datasketches-java" % "6.1.1",
    "org.apache.datasketches" % "datasketches-memory" % "3.0.2",
    "org.apache.derby" % "derby" % "10.14.2.0",
    "org.apache.hadoop" % "hadoop-client-runtime" % "3.4.1",
    "org.apache.hive" % "hive-beeline" % "2.3.10",
    "org.apache.hive" % "hive-cli" % "2.3.10",
    "org.apache.hive" % "hive-jdbc" % "2.3.10",
    "org.apache.hive" % "hive-llap-client" % "2.3.10",
    "org.apache.hive" % "hive-llap-common" % "2.3.10",
    "org.apache.hive" % "hive-serde" % "2.3.10",
    "org.apache.hive" % "hive-shims" % "2.3.10",
    "org.apache.hive" % "hive-storage-api" % "2.8.1",
    "org.apache.hive.shims" % "hive-shims-0.23" % "2.3.10",
    "org.apache.hive.shims" % "hive-shims-common" % "2.3.10",
    "org.apache.hive.shims" % "hive-shims-scheduler" % "2.3.10",
    "org.apache.httpcomponents" % "httpclient" % "4.5.14",
    "org.apache.httpcomponents" % "httpcore" % "4.4.16",
    "org.apache.ivy" % "ivy" % "2.5.3",
    "org.apache.logging.log4j" % "log4j-1.2-api" % "2.24.3",
    "org.apache.logging.log4j" % "log4j-api" % "2.24.3",
    "org.apache.logging.log4j" % "log4j-core" % "2.24.3",
    "org.apache.logging.log4j" % "log4j-layout-template-json" % "2.24.3",
    "org.apache.logging.log4j" % "log4j-slf4j2-impl" % "2.24.3",
    "org.apache.orc" % "orc-core" % "2.1.1-shaded-protobuf",
    "org.apache.orc" % "orc-format" % "1.1.0-shaded-protobuf",
    "org.apache.orc" % "orc-mapreduce" % "2.1.1-shaded-protobuf",
    "org.apache.orc" % "orc-shims" % "2.1.1",
    "org.apache.poi" % "poi" % "5.4.1",
    "org.apache.poi" % "poi-ooxml" % "5.4.1",
    "org.apache.poi" % "poi-ooxml-full" % "5.4.1",
    "org.apache.poi" % "poi-ooxml-lite" % "5.4.1",
    "org.apache.thrift" % "libfb303" % "0.9.3",
    "org.apache.thrift" % "libthrift" % "0.16.0",
    "org.apache.ws.xmlschema" % "xmlschema-core" % "2.3.1",
    "org.apache.xbean" % "xbean-asm9-shaded" % "4.26",
    "org.apache.xmlbeans" % "xmlbeans" % "5.3.0",
    "org.apache.yetus" % "audience-annotations" % "0.13.0",
    "org.apache.zookeeper" % "zookeeper" % "3.9.3",
    "org.apache.zookeeper" % "zookeeper-jute" % "3.9.3",
    "org.checkerframework" % "checker-qual" % "3.43.0",
    "org.codehaus.janino" % "commons-compiler" % "3.0.16",
    "org.codehaus.janino" % "janino" % "3.0.16",
    "org.datanucleus" % "datanucleus-api-jdo" % "4.2.4",
    "org.datanucleus" % "datanucleus-core" % "4.1.17",
    "org.datanucleus" % "datanucleus-rdbms" % "4.1.19",
    "org.datanucleus" % "javax.jdo" % "3.2.0-m3",
    "org.eclipse.jetty" % "jetty-client" % "9.4.53.v20231009",
    "org.eclipse.jetty" % "jetty-continuation" % "9.4.53.v20231009",
    "org.eclipse.jetty" % "jetty-http" % "9.4.53.v20231009",
    "org.eclipse.jetty" % "jetty-io" % "9.4.53.v20231009",
    "org.eclipse.jetty" % "jetty-jndi" % "9.4.53.v20231009",
    "org.eclipse.jetty" % "jetty-plus" % "9.4.53.v20231009",
    "org.eclipse.jetty" % "jetty-proxy" % "9.4.53.v20231009",
    "org.eclipse.jetty" % "jetty-security" % "9.4.53.v20231009",
    "org.eclipse.jetty" % "jetty-server" % "9.4.53.v20231009",
    "org.eclipse.jetty" % "jetty-servlet" % "9.4.53.v20231009",
    "org.eclipse.jetty" % "jetty-servlets" % "9.4.53.v20231009",
    "org.eclipse.jetty" % "jetty-util" % "9.4.53.v20231009",
    "org.eclipse.jetty" % "jetty-util-ajax" % "9.4.53.v20231009",
    "org.eclipse.jetty" % "jetty-webapp" % "9.4.53.v20231009",
    "org.eclipse.jetty" % "jetty-xml" % "9.4.53.v20231009",
    "org.eclipse.jetty.websocket" % "websocket-api" % "9.4.53.v20231009",
    "org.eclipse.jetty.websocket" % "websocket-client" % "9.4.53.v20231009",
    "org.eclipse.jetty.websocket" % "websocket-common" % "9.4.53.v20231009",
    "org.eclipse.jetty.websocket" % "websocket-server" % "9.4.53.v20231009",
    "org.eclipse.jetty.websocket" % "websocket-servlet" % "9.4.53.v20231009",
    "org.fusesource.leveldbjni" % "leveldbjni-all" % "1.8",
    "org.glassfish.hk2" % "hk2-api" % "2.6.1",
    "org.glassfish.hk2" % "hk2-locator" % "2.6.1",
    "org.glassfish.hk2" % "hk2-utils" % "2.6.1",
    "org.glassfish.hk2" % "osgi-resource-locator" % "1.0.3",
    "org.glassfish.hk2.external" % "aopalliance-repackaged" % "2.6.1",
    "org.glassfish.hk2.external" % "jakarta.inject" % "2.6.1",
    "org.glassfish.jersey.containers" % "jersey-container-servlet" % "2.41",
    "org.glassfish.jersey.containers" % "jersey-container-servlet-core" % "2.41",
    "org.glassfish.jersey.core" % "jersey-client" % "2.41",
    "org.glassfish.jersey.core" % "jersey-common" % "2.41",
    "org.glassfish.jersey.core" % "jersey-server" % "2.41",
    "org.glassfish.jersey.inject" % "jersey-hk2" % "2.41",
    "org.hibernate.validator" % "hibernate-validator" % "6.2.5.Final",
    "org.ini4j" % "ini4j" % "0.5.4",
    "org.javassist" % "javassist" % "3.29.2-GA",
    "org.jboss.logging" % "jboss-logging" % "3.4.1.Final",
    "org.jdbi" % "jdbi" % "2.63.1",
    "org.jetbrains" % "annotations" % "17.0.0",
    "org.jline" % "jline" % "3.27.1-jdk8",
    "org.joda" % "joda-convert" % "1.7",
    "org.jodd" % "jodd-core" % "3.5.2",
    "org.json4s" % "json4s-ast_2.13" % "4.0.7",
    "org.json4s" % "json4s-core_2.13" % "4.0.7",
    "org.json4s" % "json4s-jackson-core_2.13" % "4.0.7",
    "org.json4s" % "json4s-jackson_2.13" % "4.0.7",
    "org.json4s" % "json4s-scalap_2.13" % "4.0.7",
    "org.lz4" % "lz4-java" % "1.8.0-databricks-1",
    "org.mlflow" % "mlflow-spark_2.13" % "2.9.1",
    "org.objenesis" % "objenesis" % "3.3",
    "org.postgresql" % "postgresql" % "42.6.1",
    "org.roaringbitmap" % "RoaringBitmap" % "1.2.1",
    "org.rocksdb" % "rocksdbjni" % "9.8.4",
    "org.rosuda.REngine" % "REngine" % "2.1.0",
    "org.scala-lang" % "scala-compiler" % "2.13.16",
    "org.scala-lang" % "scala-library" % "2.13.16",
    "org.scala-lang" % "scala-reflect" % "2.13.16",
    "org.scala-lang.modules" % "scala-collection-compat_2.13" % "2.11.0",
    "org.scala-lang.modules" % "scala-java8-compat_2.13" % "0.9.1",
    "org.scala-lang.modules" % "scala-parallel-collections_2.13" % "1.2.0",
    "org.scala-lang.modules" % "scala-parser-combinators_2.13" % "2.4.0",
    "org.scala-lang.modules" % "scala-xml_2.13" % "2.3.0",
    "org.scala-sbt" % "test-interface" % "1.0",
    "org.scalacheck" % "scalacheck_2.13" % "1.18.0",
    "org.scalactic" % "scalactic_2.13" % "3.2.19",
    "org.scalanlp" % "breeze-macros_2.13" % "2.1.0",
    "org.scalanlp" % "breeze_2.13" % "2.1.0",
    "org.scalatest" % "scalatest-compatible" % "3.2.19",
    "org.scalatest" % "scalatest-core_2.13" % "3.2.19",
    "org.scalatest" % "scalatest-diagrams_2.13" % "3.2.19",
    "org.scalatest" % "scalatest-featurespec_2.13" % "3.2.19",
    "org.scalatest" % "scalatest-flatspec_2.13" % "3.2.19",
    "org.scalatest" % "scalatest-freespec_2.13" % "3.2.19",
    "org.scalatest" % "scalatest-funspec_2.13" % "3.2.19",
    "org.scalatest" % "scalatest-funsuite_2.13" % "3.2.19",
    "org.scalatest" % "scalatest-matchers-core_2.13" % "3.2.19",
    "org.scalatest" % "scalatest-mustmatchers_2.13" % "3.2.19",
    "org.scalatest" % "scalatest-propspec_2.13" % "3.2.19",
    "org.scalatest" % "scalatest-refspec_2.13" % "3.2.19",
    "org.scalatest" % "scalatest-shouldmatchers_2.13" % "3.2.19",
    "org.scalatest" % "scalatest-wordspec_2.13" % "3.2.19",
    "org.scalatest" % "scalatest_2.13" % "3.2.19",
    "org.slf4j" % "jcl-over-slf4j" % "2.0.16",
    "org.slf4j" % "jul-to-slf4j" % "2.0.16",
    "org.slf4j" % "slf4j-api" % "2.0.16",
    "org.slf4j" % "slf4j-simple" % "1.7.25",
    "org.threeten" % "threeten-extra" % "1.8.0",
    "org.tukaani" % "xz" % "1.10",
    "org.typelevel" % "algebra_2.13" % "2.8.0",
    "org.typelevel" % "cats-kernel_2.13" % "2.8.0",
    "org.typelevel" % "spire-macros_2.13" % "0.18.0",
    "org.typelevel" % "spire-platform_2.13" % "0.18.0",
    "org.typelevel" % "spire-util_2.13" % "0.18.0",
    "org.typelevel" % "spire_2.13" % "0.18.0",
    "org.wildfly.openssl" % "wildfly-openssl" % "1.1.3.Final",
    "org.xerial" % "sqlite-jdbc" % "3.42.0.0",
    "org.xerial.snappy" % "snappy-java" % "1.1.10.3",
    "org.yaml" % "snakeyaml" % "2.0",
    "oro" % "oro" % "2.0.8",
    "pl.edu.icm" % "JLargeArrays" % "1.5",
    "software.amazon.cryptools" % "AmazonCorrettoCryptoProvider" % "2.5.0-linux-x86_64",
    "stax" % "stax-api" % "1.0.1"
  )

}
