// LOADED TABLE SPEC AUTO GENERATED:START
// Generated by LoadedTableSpecAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr_raw.ct_gbl_bmc

import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.Loaded
import ct.dna.lakehouse.core.model.TableSpec

case class E_conti_amtools_landesk_staging_(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    chassistype_string: String,
    boardname_string: String,
    domainname_string: String,
    version_string: String,
    devicename_string: String,
    fullname_string: String,
    currentbuild_string: String,
    availableinaddm_long: BoxedLong,
    model_string: String,
    serialnum_string: String,
    display_id_string: String,
    physaddress_string: String,
    mhzspeed_long: BoxedLong,
    loginname_string: String,
    ipaddress_string: String,
    ostype_string: String,
    proc_type_string: String,
    manufacturer_string: String,
    lastupdinvsvr_long: BoxedLong,
    _type_string: String,
    modified_date_long: BoxedLong,
    lddb_name_string: String,
    primaryowner_string: String,
    computerlocation_string: String
) extends Entity

object conti_amtools_landesk_staging_
    extends TableSpec[E_conti_amtools_landesk_staging_](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.Columns("_mk_instance", "_mk_partition", "_mk_file"),
      timetravelDays = 35
    )
    with Loaded
// LOADED TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_conti_amtools_landesk_staging_(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val chassistype_string: ColumnWithName = ColumnWithName(prefix + "chassistype_string")
  val boardname_string: ColumnWithName = ColumnWithName(prefix + "boardname_string")
  val domainname_string: ColumnWithName = ColumnWithName(prefix + "domainname_string")
  val version_string: ColumnWithName = ColumnWithName(prefix + "version_string")
  val devicename_string: ColumnWithName = ColumnWithName(prefix + "devicename_string")
  val fullname_string: ColumnWithName = ColumnWithName(prefix + "fullname_string")
  val currentbuild_string: ColumnWithName = ColumnWithName(prefix + "currentbuild_string")
  val availableinaddm_long: ColumnWithName = ColumnWithName(prefix + "availableinaddm_long")
  val model_string: ColumnWithName = ColumnWithName(prefix + "model_string")
  val serialnum_string: ColumnWithName = ColumnWithName(prefix + "serialnum_string")
  val display_id_string: ColumnWithName = ColumnWithName(prefix + "display_id_string")
  val physaddress_string: ColumnWithName = ColumnWithName(prefix + "physaddress_string")
  val mhzspeed_long: ColumnWithName = ColumnWithName(prefix + "mhzspeed_long")
  val loginname_string: ColumnWithName = ColumnWithName(prefix + "loginname_string")
  val ipaddress_string: ColumnWithName = ColumnWithName(prefix + "ipaddress_string")
  val ostype_string: ColumnWithName = ColumnWithName(prefix + "ostype_string")
  val proc_type_string: ColumnWithName = ColumnWithName(prefix + "proc_type_string")
  val manufacturer_string: ColumnWithName = ColumnWithName(prefix + "manufacturer_string")
  val lastupdinvsvr_long: ColumnWithName = ColumnWithName(prefix + "lastupdinvsvr_long")
  val _type_string: ColumnWithName = ColumnWithName(prefix + "_type_string")
  val modified_date_long: ColumnWithName = ColumnWithName(prefix + "modified_date_long")
  val lddb_name_string: ColumnWithName = ColumnWithName(prefix + "lddb_name_string")
  val primaryowner_string: ColumnWithName = ColumnWithName(prefix + "primaryowner_string")
  val computerlocation_string: ColumnWithName = ColumnWithName(prefix + "computerlocation_string")
}

object C_conti_amtools_landesk_staging_ extends C_conti_amtools_landesk_staging_("") {
  def as(alias: String): C_conti_amtools_landesk_staging_ = new C_conti_amtools_landesk_staging_(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
