package ct.dna.lakehouse.sr_raw.ct_gbl_e32
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class kna1_E(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  j_1kftind_string: String,
  ort02_string: String,
  hzuor_string: String,
  zz74_etiar_string: String,
  _vso_r_pk_mat_string: String,
  katr6_string: String,
  zz74_verbot_string: String,
  faksd_string: String,
  dtams_string: String,
  exp_string: String,
  _vso_r_load_pref_string: String,
  xcpdk_string: String,
  kdkg1_string: String,
  begru_string: String,
  telfx_string: String,
  abrvw_string: String,
  brsch_string: String,
  zz74_an2lbl_string: String,
  locco_string: String,
  ktocd_string: String,
  jmzah_string: String,
  ernam_string: String,
  counc_string: String,
  bran2_string: String,
  cassd_string: String,
  _vso_r_one_sort_string: String,
  dear3_string: String,
  milve_string: String,
  pfach_string: String,
  @Decimal(12, 4) umsat_decimal_12_4: BigDecimal,
  etikg_string: String,
  ccc03_string: String,
  umjah_string: String,
  icmstaxpay_string: String,
  name3_string: String,
  spras_string: String,
  sortl_string: String,
  bran3_string: String,
  fityp_string: String,
  cfopc_string: String,
  bran5_string: String,
  cvp_xblck_string: String,
  _vso_r_dpoint_string: String,
  name1_string: String,
  stcd5_string: String,
  confs_string: String,
  telx1_string: String,
  stkzn_string: String,
  dear4_string: String,
  bahns_string: String,
  legalnat_string: String,
  stkza_string: String,
  duefl_string: String,
  suframa_string: String,
  telbx_string: String,
  stcd1_string: String,
  regio_string: String,
  crtn_string: String,
  _vso_r_pal_ul_string: String,
  alc_string: String,
  stkzu_string: String,
  stcd4_string: String,
  datlt_string: String,
  stcd6_string: String,
  zz_ish_string: String,
  rpmkr_string: String,
  psost_string: String,
  ccc02_string: String,
  psoo3_string: String,
  land1_string: String,
  zsgr_string: String,
  @Decimal(19, 4) umsa1_decimal_19_4: BigDecimal,
  katr5_string: String,
  bahne_string: String,
  stceg_string: String,
  ric_string: String,
  ktokd_string: String,
  bbsnr_string: String,
  stcd2_string: String,
  _vso_r_uld_side_string: String,
  txlw1_string: String,
  knazk_string: String,
  cityc_string: String,
  anred_string: String,
  @Decimal(13, 3) _vso_r_palhgt_decimal_13_3: BigDecimal,
  xicms_string: String,
  updat_string: String,
  dear2_string: String,
  mcod2_string: String,
  nodel_string: String,
  werks_string: String,
  katr8_string: String,
  pson1_string: String,
  mcod3_string: String,
  xxipi_string: String,
  psoo1_string: String,
  j_1kftbus_string: String,
  decregpc_string: String,
  knurl_string: String,
  sperz_string: String,
  kdkg3_string: String,
  zz_guo_string: String,
  mandt_string: String,
  j_1kfrepre_string: String,
  niels_string: String,
  ccc01_string: String,
  vbund_string: String,
  psohs_string: String,
  lifsd_string: String,
  pson3_string: String,
  psoo5_string: String,
  txjcd_string: String,
  ekont_string: String,
  katr2_string: String,
  fiskn_string: String,
  dear1_string: String,
  zharm_string: String,
  telf1_string: String,
  name4_string: String,
  psofg_string: String,
  _vso_r_matpal_string: String,
  rne_string: String,
  mcod1_string: String,
  rg_string: String,
  gform_string: String,
  psotl_string: String,
  konzs_string: String,
  adrnr_string: String,
  kdkg4_string: String,
  comsize_string: String,
  psois_string: String,
  telf2_string: String,
  xknza_string: String,
  xzemp_string: String,
  psovn_string: String,
  uwaer_string: String,
  psoo4_string: String,
  knrza_string: String,
  teltx_string: String,
  kukla_string: String,
  dear5_string: String,
  _vso_r_i_no_lyr_string: String,
  _vso_r_one_mat_string: String,
  dear6_string: String,
  exabl_string: String,
  indtyp_string: String,
  txlw2_string: String,
  xsubt_string: String,
  katr4_string: String,
  jmjah_string: String,
  pstlz_string: String,
  rnedate_string: String,
  pmt_office_string: String,
  pson2_string: String,
  name2_string: String,
  zz74_varlbl_string: String,
  stcdt_string: String,
  bran1_string: String,
  cnae_string: String,
  katr3_string: String,
  pstl2_string: String,
  uf_string: String,
  katr7_string: String,
  stcd3_string: String,
  dtaws_string: String,
  kdkg2_string: String,
  ort01_string: String,
  lifnr_string: String,
  katr1_string: String,
  ccc04_string: String,
  bran4_string: String,
  periv_string: String,
  psoo2_string: String,
  bubkz_string: String,
  lzone_string: String,
  aufsd_string: String,
  kunnr_string: String,
  sperr_string: String,
  zsvertical_string: String,
  loevm_string: String,
  zvertical_string: String,
  stras_string: String,
  kdkg5_string: String,
  pfort_string: String,
  inspbydebi_string: String,
  katr10_string: String,
  bbbnr_string: String,
  uptim_string: String,
  tdt_string: String,
  civve_string: String,
  katr9_string: String,
  rgdate_string: String,
  inspatdebi_string: String,
  erdat_string: String,
  @Decimal(8, 2) umsat_decimal_8_2: BigDecimal,
  @Decimal(15, 2) umsa1_decimal_15_2: BigDecimal
) extends Entity

object kna1 extends TableSpec[kna1_E](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
