package ct.dna.lakehouse.sr_raw.ct_gbl_e32
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class mara_E_part1(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  zz_praefix_matnr_string: String,
  liqdt_string: String,
  matnr_string: String,
  mcond_string: String,
  formt_string: String,
  zz_dicke_string: String,
  gds_relevant_string: String,
  _dsd_sv_cnt_grp_string: String,
  whmatgr_string: String,
  size1_string: String,
  tragr_string: String,
  zz_dat_pr_string: String,
  inhme_string: String,
  xgchp_string: String,
  tare_var_string: String,
  magrv_string: String,
  vpsta_string: String,
  rdmhd_string: String,
  begru_string: String,
  rmatp_string: String,
  fiber_part5_string: String,
  @Decimal(15, 3) maxh_decimal_15_3: BigDecimal,
  @Decimal(15, 3) maxl_decimal_15_3: BigDecimal,
  _bev1_luldegrp_string: String,
  zz_matnr_neu_string: String,
  ernam_string: String,
  prdha_string: String,
  @Decimal(3, 1) volto_decimal_3_1: BigDecimal,
  _vso_r_bot_ind_string: String,
  _vso_r_kzgvh_ind_string: String,
  free_char_string: String,
  allow_pmat_igno_string: String,
  raube_string: String,
  cadkz_string: String,
  zz_zusatztext_string: String,
  hutyp_string: String,
  ekwsl_string: String,
  zz_praegung_string: String,
  zz_kdmat_txt_neu_string: String,
  entar_string: String,
  attyp_string: String,
  zz_hd_vererben_string: String,
  @Decimal(5, 0) vpreh_decimal_5_0: BigDecimal,
  @Decimal(3, 0) fuelg_decimal_3_0: BigDecimal,
  @Decimal(13, 3) _vso_r_pal_min_h_decimal_13_3: BigDecimal,
  mstav_string: String,
  _dsd_sl_toltyp_string: String,
  zzgold_maktx_string: String,
  etiag_string: String,
  bwscl_string: String,
  _vso_r_tilt_ind_string: String,
  pstat_string: String,
  mtpos_mara_string: String,
  bstat_string: String,
  _vso_r_no_p_gvh_string: String,
  @Decimal(13, 3) wesch_decimal_13_3: BigDecimal,
  blatt_string: String,
  zz_breite_string: String,
  fiber_code5_string: String,
  @Decimal(13, 3) laeng_decimal_13_3: BigDecimal,
  zeivr_string: String,
  compl_string: String,
  animal_origin_string: String,
  fiber_code4_string: String,
  kzumw_string: String,
  @Decimal(13, 3) ntgew_decimal_13_3: BigDecimal,
  @Decimal(13, 3) breit_decimal_13_3: BigDecimal,
  _dsd_vc_group_string: String,
  kzkfg_string: String,
  @Decimal(15, 3) maxb_decimal_15_3: BigDecimal,
  zz_ernam_etik_string: String,
  ervoe_string: String,
  saiso_string: String,
  @Decimal(13, 3) ergew_decimal_13_3: BigDecimal,
  qqtimeuom_string: String,
  @Decimal(13, 3) _vso_r_pal_ovr_d_decimal_13_3: BigDecimal,
  kzkup_string: String,
  @Decimal(13, 3) hoehe_decimal_13_3: BigDecimal,
  imatn_string: String,
  zz_dessin_string: String,
  bflme_string: String,
  fsh_mg_at2_string: String,
  nsnid_string: String,
  zz_erzeit_etik_string: String,
  behvo_string: String,
  zz_farbe_string: String,
  groes_string: String,
  dg_pack_status_string: String,
  gewei_string: String,
  psm_code_string: String,
  ferth_string: String,
  _vso_r_stack_no_string: String,
  fsh_mg_at3_string: String,
  przus_string: String,
  serlv_string: String,
  cuobf_string: String,
  fsh_seaim_string: String,
  iprkz_string: String,
  picnum_string: String,
  ipmipproduct_string: String,
  size2_atinn_string: String,
  anp_string: String,
  fsh_mg_at1_string: String,
  fiber_code2_string: String,
  zz_abrdatum_string: String,
  color_string: String,
  rbnrm_string: String,
  medium_string: String,
  mfrpn_string: String,
  kzrev_string: String,
  @Decimal(13, 3) inhal_decimal_13_3: BigDecimal,
  fiber_part1_string: String,
  sprof_string: String,
  _bev1_nestruccat_string: String,
  @Decimal(3, 0) mhdlp_decimal_3_0: BigDecimal,
  qgrp_string: String,
  etifo_string: String,
  _bev1_luleinh_string: String,
  zz_konfekt_string: String,
  kosch_string: String,
  zeinr_string: String,
  zz_desfam_string: String,
  mstae_string: String,
  gtin_variant_string: String,
  saity_string: String,
  _vso_r_quan_unit_string: String,
  zz_dat_pvo_string: String,
  ergei_string: String,
  ersda_string: String,
  mandt_string: String,
  kzwsm_string: String,
  eannr_string: String,
  pmata_string: String,
  extwg_string: String,
  sgt_covsa_string: String,
  @Decimal(3, 1) gewto_decimal_3_1: BigDecimal,
  kzgvh_string: String,
  saisj_string: String,
  blanz_string: String,
  whstc_string: String,
  satnr_string: String,
  gennr_string: String,
  aeklk_string: String,
  @Decimal(3, 0) zz_anz_etik_decimal_3_0: BigDecimal,
  sgt_scope_string: String,
  sled_bbd_string: String,
  voleh_string: String,
  _vso_r_pal_ind_string: String,
  @Decimal(3, 1) maxc_tol_decimal_3_1: BigDecimal,
  mstdv_string: String,
  bwvor_string: String,
  fiber_part3_string: String,
  etiar_string: String,
  meins_string: String,
  cwqproc_string: String,
  zz_format_string: String,
  fashgrd_string: String,
  fiber_part2_string: String,
  care_code_string: String,
  pilferable_string: String,
  profl_string: String,
  hazmat_string: String,
  stfak_int: BoxedInt,
  retdelc_string: String,
  @Decimal(4, 0) mhdhb_decimal_4_0: BigDecimal,
  zz_kdmat_neu_string: String,
  @Decimal(13, 3) _vso_r_pal_b_ht_decimal_13_3: BigDecimal,
  spart_string: String,
  serial_string: String,
  vabme_string: String,
  @Decimal(13, 3) inhbr_decimal_13_3: BigDecimal,
  mbrsh_string: String,
  mfrnr_string: String,
  mprof_string: String,
  mstde_string: String,
  ean11_string: String,
  sgt_stat_string: String,
  @Decimal(13, 3) _vso_r_pal_ovr_w_decimal_13_3: BigDecimal,
  size2_string: String,
  meabm_string: String,
  fsh_sealv_string: String,
  fiber_code1_string: String,
  numtp_string: String,
  iloos_string: String,
  cwqtolgr_string: String,
  zzgold_sysid_string: String,
  zz_laenge_string: String,
  sgt_csgr_string: String,
  cmrel_string: String,
  mfrgr_string: String,
  zzgold_mandt_string: String,
  logunit_string: String,
  vhart_string: String,
  packcode_string: String,
  _vso_r_top_ind_string: String,
  @Decimal(15, 3) maxc_decimal_15_3: BigDecimal,
  aenam_string: String,
  size1_atinn_string: String,
  _vso_r_stack_ind_string: String,
  color_atinn_string: String,
  aeszn_string: String,
  @Decimal(4, 0) mhdrz_decimal_4_0: BigDecimal,
  cmeth_string: String,
  loglev_reto_string: String,
  cwqrel_string: String,
  bmatn_string: String,
  bstme_string: String,
  fsh_sc_mid_string: String,
  kzeff_string: String,
  nrfhg_string: String,
  bbtyp_string: String,
  zeifo_string: String,
  maxdim_uom_string: String,
  matfi_string: String,
  adspc_spc_string: String,
  zz_konform_string: String,
  ihivi_string: String,
  weora_string: String,
  herkl_string: String,
  hutyp_dflt_string: String,
  commodity_string: String,
  qmpur_string: String,
  fiber_code3_string: String,
  bismt_string: String,
  mtart_string: String,
  stoff_string: String,
  zeiar_string: String,
  kunnr_string: String,
  tempb_string: String,
  labor_string: String,
  @Decimal(13, 3) volum_decimal_13_3: BigDecimal,
  wrkst_string: String,
  mlgut_string: String,
  @Decimal(13, 3) ervol_decimal_13_3: BigDecimal,
  taklv_string: String,
  hndlcode_string: String,
  normt_string: String,
  kznfm_string: String,
  sgt_rel_string: String,
  textile_comp_ind_string: String,
  lvorm_string: String,
  matkl_string: String
) extends Entity


@LakehouseEntity
case class mara_E_part2(
  @PK _mk_org: String,
  ps_smartform_string: String,
  zz_erdat_etik_string: String,
  @Decimal(3, 0) qqtime_decimal_3_0: BigDecimal,
  zzgold_matnr_string: String,
  laeda_string: String,
  adprof_string: String,
  datab_string: String,
  disst_string: String,
  xchpf_string: String,
  @Decimal(13, 3) brgew_decimal_13_3: BigDecimal,
  brand_id_string: String,
  plgtp_string: String,
  fiber_part4_string: String,
  @Decimal(13, 3) _vso_r_tol_b_ht_decimal_13_3: BigDecimal
) extends Entity

object mara extends TableSpec[Joined[mara_E_part1, mara_E_part2]](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
