package ct.dna.lakehouse.sr_raw.ct_gbl_e32
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class stpo_E(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  itmid_string: String,
  sortf_string: String,
  @Decimal(13, 3) romen_decimal_13_3: BigDecimal,
  kstpz_string: String,
  kzclb_string: String,
  annam_string: String,
  alpos_string: String,
  clszu_string: String,
  clobk_string: String,
  idnrk_string: String,
  romei_string: String,
  potx2_string: String,
  fmeng_string: String,
  schgt_string: String,
  clmul_string: String,
  guidx_binary: Array[Byte],
  dvdat_string: String,
  rekrs_string: String,
  @Decimal(3, 0) ewahr_decimal_3_0: BigDecimal,
  stlty_string: String,
  sanvs_string: String,
  sanin_string: String,
  nfeag_string: String,
  idpos_string: String,
  @Decimal(13, 3) roanz_decimal_13_3: BigDecimal,
  vcekz_string: String,
  @Decimal(3, 0) nlfzt_decimal_3_0: BigDecimal,
  potx1_string: String,
  dvnam_string: String,
  prvbe_string: String,
  alpgr_string: String,
  guid_string: String,
  netau_string: String,
  kndbz_string: String,
  doknr_string: String,
  @Decimal(5, 0) peinh_decimal_5_0: BigDecimal,
  postp_string: String,
  kzkup_string: String,
  alekz_string: String,
  sanko_string: String,
  clalt_string: String,
  datuv_string: String,
  sanka_string: String,
  stlnr_string: String,
  vgpzl_string: String,
  pswrk_string: String,
  andat_string: String,
  idvar_string: String,
  alprf_string: String,
  rekri_string: String,
  vstkz_string: String,
  @Decimal(13, 3) roms3_decimal_13_3: BigDecimal,
  class_string: String,
  nfmat_string: String,
  nfgrp_string: String,
  lgort_string: String,
  verti_string: String,
  kstnr_string: String,
  stvkn_string: String,
  stkkz_string: String,
  itsob_string: String,
  kstty_string: String,
  lkenz_string: String,
  vackz_string: String,
  mandt_string: String,
  dokar_string: String,
  tpekz_string: String,
  ablad_string: String,
  vgknt_string: String,
  ekgrp_string: String,
  @Decimal(5, 2) csstr_decimal_5_2: BigDecimal,
  erskz_string: String,
  klart_string: String,
  ecn_to_rkey_string: String,
  inskz_string: String,
  nlfmv_string: String,
  awakz_string: String,
  kznfp_string: String,
  knobj_string: String,
  @Decimal(13, 3) roms2_decimal_13_3: BigDecimal,
  valkz_string: String,
  wempf_string: String,
  potpr_string: String,
  kstkn_string: String,
  aehlp_string: String,
  @Decimal(13, 3) menge_decimal_13_3: BigDecimal,
  meins_string: String,
  @Decimal(3, 0) nlfzv_decimal_3_0: BigDecimal,
  @Decimal(5, 2) ausch_decimal_5_2: BigDecimal,
  ekorg_string: String,
  sakto_string: String,
  alpst_string: String,
  stlkn_string: String,
  rform_string: String,
  idhis_string: String,
  intrm_string: String,
  doktl_string: String,
  @Decimal(11, 2) preis_decimal_11_2: BigDecimal,
  valid_to_string: String,
  rfpnt_string: String,
  @Decimal(3, 0) lifzt_decimal_3_0: BigDecimal,
  aenam_string: String,
  ecn_to_string: String,
  aedat_string: String,
  sanfe_string: String,
  ltxsp_string: String,
  rvrel_string: String,
  stpoz_string: String,
  cview_string: String,
  valid_to_rkey_string: String,
  lifnr_string: String,
  upskz_string: String,
  beikz_string: String,
  dspst_string: String,
  kndvb_string: String,
  objty_string: String,
  sgt_catv_string: String,
  cufactor_string: String,
  aennr_string: String,
  funcid_string: String,
  @Decimal(13, 3) roms1_decimal_13_3: BigDecimal,
  techv_string: String,
  @Decimal(3, 0) webaz_decimal_3_0: BigDecimal,
  sgt_cmkz_string: String,
  dokvr_string: String,
  matkl_string: String,
  @Decimal(5, 2) avoau_decimal_5_2: BigDecimal,
  posnr_string: String,
  waers_string: String,
  cadpo_string: String
) extends Entity

object stpo extends TableSpec[stpo_E](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
