// SCHEMA SPEC AUTO GENERATED:START
// Generated by SchemaSpecAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr_raw

import ct.dna.lakehouse.core.model.SchemaSpec

package object iemea_vahz_sapme extends SchemaSpec
// SCHEMA SPEC AUTO GENERATED:END
