package ct.dna.lakehouse.sr_raw.ct_gbl_p73
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class t001_E(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  xfdis_string: String,
  ktop2_string: String,
  xcos_string: String,
  mandt_string: String,
  dtaxr_string: String,
  xkkbi_string: String,
  butxt_string: String,
  bukrs_string: String,
  buvar_string: String,
  xslta_string: String,
  xcovr_string: String,
  dtprov_string: String,
  fdbuk_string: String,
  rcomp_string: String,
  xfdsd_string: String,
  mwska_string: String,
  ktopl_string: String,
  pp_pdate_string: String,
  wfvar_string: String,
  spras_string: String,
  xfmco_string: String,
  fstva_string: String,
  fikrs_string: String,
  xkdft_string: String,
  kopim_string: String,
  xbbsc_string: String,
  umkrs_string: String,
  land1_string: String,
  bapovar_string: String,
  stceg_string: String,
  xfdmm_string: String,
  infmt_string: String,
  dttaxc_string: String,
  dkweg_string: String,
  bukrs_glob_string: String,
  xbbba_string: String,
  xcession_string: String,
  mwskv_string: String,
  xmwsn_string: String,
  kokfi_string: String,
  xeink_string: String,
  dttdsp_string: String,
  txjcd_string: String,
  xfmcb_string: String,
  impda_string: String,
  adrnr_string: String,
  xvatdate_string: String,
  xjvaa_string: String,
  xstdt_string: String,
  pst_per_var_string: String,
  xskfn_string: String,
  xsplt_string: String,
  ebukr_string: String,
  waabw_string: String,
  fmhrdate_date: Date,
  opvar_string: String,
  xgsbe_string: String,
  offsacct_string: String,
  xbbko_string: String,
  xvvwa_string: String,
  xextb_string: String,
  surccm_string: String,
  fstvare_string: String,
  fm_derive_acc_string: String,
  xnegp_string: String,
  xfmca_string: String,
  xvalv_string: String,
  xgjrv_string: String,
  ort01_string: String,
  wt_newwt_string: String,
  dtamtc_string: String,
  periv_string: String,
  mregl_string: String,
  txkrs_string: String,
  xprod_string: String,
  xbbbf_string: String,
  xbbbe_string: String,
  kkber_string: String,
  waers_string: String,
  fmhrdate_string: String
) extends Entity

object t001 extends TableSpec[t001_E](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
