// LOADED TABLE SPEC AUTO GENERATED:START
// Generated by LoadedTableSpecAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr_raw.ct_gbl_smartrecruiters

import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.Loaded
import ct.dna.lakehouse.core.model.TableSpec

case class E_chr_candidate(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    candidate_city_string: String,
    candidate_consent_status_string: String,
    candidate_country_region_string: String,
    candidate_deletion_reason_string: String,
    candidate_email_string: String,
    candidate_first_name_string: String,
    candidate_first_and_last_name_string: String,
    candidate_id_string: String,
    candidate_last_name_string: String,
    candidate_last_update_date_string: String,
    candidate_location_string: String,
    candidate_source_string: String,
    candidate_source_referrer_id_string: String,
    candidate_source_subtype_string: String,
    candidate_source_type_string: String,
    current_employer_string: String,
    is_candidate_deleted_string: String,
    is_custom_candidate_source_string: String,
    is_candidate_deferred_string: String,
    latest_consent_acquired_date_string: String,
    latest_consent_request_date_string: String,
    number_of_candidate_tags_string: String
) extends Entity

object chr_candidate
    extends TableSpec[E_chr_candidate](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.Columns("_mk_instance", "_mk_partition", "_mk_file"),
      timetravelDays = 35
    )
    with Loaded
// LOADED TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_chr_candidate(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val candidate_city_string: ColumnWithName = ColumnWithName(prefix + "candidate_city_string")
  val candidate_consent_status_string: ColumnWithName = ColumnWithName(prefix + "candidate_consent_status_string")
  val candidate_country_region_string: ColumnWithName = ColumnWithName(prefix + "candidate_country_region_string")
  val candidate_deletion_reason_string: ColumnWithName = ColumnWithName(prefix + "candidate_deletion_reason_string")
  val candidate_email_string: ColumnWithName = ColumnWithName(prefix + "candidate_email_string")
  val candidate_first_name_string: ColumnWithName = ColumnWithName(prefix + "candidate_first_name_string")
  val candidate_first_and_last_name_string: ColumnWithName = ColumnWithName(prefix + "candidate_first_and_last_name_string")
  val candidate_id_string: ColumnWithName = ColumnWithName(prefix + "candidate_id_string")
  val candidate_last_name_string: ColumnWithName = ColumnWithName(prefix + "candidate_last_name_string")
  val candidate_last_update_date_string: ColumnWithName = ColumnWithName(prefix + "candidate_last_update_date_string")
  val candidate_location_string: ColumnWithName = ColumnWithName(prefix + "candidate_location_string")
  val candidate_source_string: ColumnWithName = ColumnWithName(prefix + "candidate_source_string")
  val candidate_source_referrer_id_string: ColumnWithName = ColumnWithName(prefix + "candidate_source_referrer_id_string")
  val candidate_source_subtype_string: ColumnWithName = ColumnWithName(prefix + "candidate_source_subtype_string")
  val candidate_source_type_string: ColumnWithName = ColumnWithName(prefix + "candidate_source_type_string")
  val current_employer_string: ColumnWithName = ColumnWithName(prefix + "current_employer_string")
  val is_candidate_deleted_string: ColumnWithName = ColumnWithName(prefix + "is_candidate_deleted_string")
  val is_custom_candidate_source_string: ColumnWithName = ColumnWithName(prefix + "is_custom_candidate_source_string")
  val is_candidate_deferred_string: ColumnWithName = ColumnWithName(prefix + "is_candidate_deferred_string")
  val latest_consent_acquired_date_string: ColumnWithName = ColumnWithName(prefix + "latest_consent_acquired_date_string")
  val latest_consent_request_date_string: ColumnWithName = ColumnWithName(prefix + "latest_consent_request_date_string")
  val number_of_candidate_tags_string: ColumnWithName = ColumnWithName(prefix + "number_of_candidate_tags_string")
}

object C_chr_candidate extends C_chr_candidate("") {
  def as(alias: String): C_chr_candidate = new C_chr_candidate(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
