name: Sbt credentials
description: Create sbt credential file for Artifactory
inputs:
  host:
    description: Artifactory Host
    required: true
  username:
    description: Artifactory Username
    required: true
  token:
    description: Artifactory Token
    required: true
runs:
  using: composite
  steps:
    - name: SBT credentials setup
      shell: bash
      run: |
        mkdir -p /root/.sbt
        echo 'realm=Artifactory Realm' > /root/.sbt/.credentials
        echo "host=${{ inputs.host }}" >> /root/.sbt/.credentials
        echo "user=${{ inputs.username }}" >> /root/.sbt/.credentials
        echo "password=${{ inputs.token }}" >> /root/.sbt/.credentials
