#!/usr/bin/env python3
"""Regenerate FxRatesTest.xlsx for ct.dna.lakehouse.dw_tx.fin_fxrates.FxRatesTest.

Run via:  python3 lakehouse/src/test/scripts/ct/dna/lakehouse/dw_tx/fin_fxrates/generate_fxrates_test_xlsx.py

------------------------------------------------------------------------------
Test design — end-to-end MERGE lifecycle for the fxrates DW transform.
------------------------------------------------------------------------------

The fxrates transform:
  1. Reads TCURR + TCURF from ct_gbl_ghp sources + an archive UC table
  2. Joins TCURR with TCURF (on mandt/kurst/fcurr/tcurr, gdatu >= condition)
  3. Computes EUR base rates, inverse rates, cross rates, identity rates
  4. MERGEs into target (update existing, insert new, delete removed)

Because each run recomputes ALL rates from scratch (full-load-on-change),
the test phases are:
  Phase 0 — empty TCURR/TCURF sources → empty target
  Phase 1 — load TCURR/TCURF with 2 currencies (USD, INR) → 9 target rows
  Phase 2 — replace TCURR with different currencies (USD, GBP) → 9 target rows
             (INR rows deleted, GBP rows inserted, USD rate unchanged)

Uses exact-fraction ukurs values to avoid floating-point comparison issues:
  USD: ukurs=-2.0 → rate=1/2=0.5    (exact)
  INR: ukurs=-4.0 → rate=1/4=0.25   (exact)
  GBP: ukurs=-0.5 → rate=1/0.5=2.0  (exact)

SAP inverted date: gdatu = 99999999 - yyyyMMdd
  gdatu=79739898 → 99999999-79739898=20260101 → rate_date=2026-01-01

The xlsx is regenerated by this script; expected target rows match the
production transform's arithmetic exactly.
"""
from datetime import date, datetime
from decimal import Decimal, ROUND_HALF_UP, getcontext
from pathlib import Path

from openpyxl import Workbook
from openpyxl.utils import get_column_letter

# Set high precision for rate computation
getcontext().prec = 50

def _resource_sibling(filename: str) -> Path:
    here = Path(__file__).resolve()
    scripts_root = next(p for p in here.parents if p.name == "scripts" and p.parent.name == "test")
    pkg = here.parent.relative_to(scripts_root)
    return scripts_root.parent / "resources" / pkg / filename


OUT = _resource_sibling("FxRatesTest.xlsx")

# ---------------------------------------------------------------------------
# Source schemas
# ---------------------------------------------------------------------------
# E_tcurr: 19 fields — order must match entityStructType
TCURR_FIELDS = [
    ("mandt", "string"),
    ("kurst", "string"),
    ("fcurr", "string"),
    ("tcurr", "string"),
    ("gdatu", "string"),
    ("ukurs", "decimal"),
    ("ffact", "decimal"),
    ("tfact", "decimal"),
    ("_mk_org", "string"),
    ("_mk_site", "string"),
    ("_mk_system", "string"),
    ("_mk_instance", "string"),
    ("_mk_partition", "string"),
    ("_mk_file", "string"),
    ("_mk_container", "string"),
    ("_mk_account", "string"),
    ("_mk_created_at", "timestamp"),
    ("_lh_id_in_message", "long"),
    ("_lh_ingest_warning", "string"),
]
TCURR_NAMES = [n for n, _ in TCURR_FIELDS]

# E_tcurf: 20 fields — order must match entityStructType
TCURF_FIELDS = [
    ("mandt", "string"),
    ("kurst", "string"),
    ("fcurr", "string"),
    ("tcurr", "string"),
    ("gdatu", "string"),
    ("ffact", "decimal"),
    ("tfact", "decimal"),
    ("abwct", "string"),
    ("abwga", "string"),
    ("_mk_org", "string"),
    ("_mk_site", "string"),
    ("_mk_system", "string"),
    ("_mk_instance", "string"),
    ("_mk_partition", "string"),
    ("_mk_file", "string"),
    ("_mk_container", "string"),
    ("_mk_account", "string"),
    ("_mk_created_at", "timestamp"),
    ("_lh_id_in_message", "long"),
    ("_lh_ingest_warning", "string"),
]
TCURF_NAMES = [n for n, _ in TCURF_FIELDS]

# Target: fx_conversion_rates (5 fields)
TGT_NAMES = ["rate_date", "fcurr", "tcurr", "kurst", "final_rate"]

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
TS = datetime(2024, 1, 1, 12, 0, 0)
SYSTEM = "GHP"
INSTANCE = "100"
ORG = "CT"
SITE = "GBL"
MANDT = "100"
KURST = "MGR"
TARGET_CURRENCY = "EUR"

# SAP inverted date for 2026-01-01
GDATU = "79739898"  # 99999999 - 20260101
RATE_DATE = date(2026, 1, 1)


# ---------------------------------------------------------------------------
# Source row builders
# ---------------------------------------------------------------------------
def build_tcurr_row(fcurr, ukurs):
    """Build a TCURR source row."""
    overrides = {
        "_mk_org": ORG,
        "_mk_site": SITE,
        "_mk_system": SYSTEM,
        "_mk_instance": INSTANCE,
        "_mk_partition": "p",
        "_mk_file": "f",
        "_mk_container": "c",
        "_mk_account": "a",
        "_mk_created_at": TS,
        "_lh_id_in_message": 1,
        "mandt": MANDT,
        "kurst": KURST,
        "fcurr": fcurr,
        "tcurr": TARGET_CURRENCY,
        "gdatu": GDATU,
        "ukurs": str(Decimal(str(ukurs))),
    }
    return [overrides.get(name, None) for name in TCURR_NAMES]


def build_tcurf_row(fcurr, ffact=1, tfact=1):
    """Build a TCURF source row with matching gdatu."""
    overrides = {
        "_mk_org": ORG,
        "_mk_site": SITE,
        "_mk_system": SYSTEM,
        "_mk_instance": INSTANCE,
        "_mk_partition": "p",
        "_mk_file": "f",
        "_mk_container": "c",
        "_mk_account": "a",
        "_mk_created_at": TS,
        "_lh_id_in_message": 1,
        "mandt": MANDT,
        "kurst": KURST,
        "fcurr": fcurr,
        "tcurr": TARGET_CURRENCY,
        "gdatu": GDATU,
        "ffact": str(Decimal(str(ffact))),
        "tfact": str(Decimal(str(tfact))),
    }
    return [overrides.get(name, None) for name in TCURF_NAMES]


# ---------------------------------------------------------------------------
# Rate computation (mirrors Spark logic exactly)
# ---------------------------------------------------------------------------
def compute_rate(ukurs, ffact=1, tfact=1):
    """Compute final_rate exactly as the Spark transform does.

    For negative ukurs: rate = (tfact/ffact) * (1/|ukurs|)
    For positive ukurs: rate = (tfact/ffact) * ukurs
    """
    uk = Decimal(str(ukurs))
    ff = Decimal(str(ffact))
    tf = Decimal(str(tfact))

    if uk < 0:
        adjusted = Decimal(1) / abs(uk)
    else:
        adjusted = uk

    return float((tf / ff) * adjusted)


def compute_all_rates(currencies):
    """Compute all output rates for a set of currencies.

    currencies: list of (fcurr, ukurs, ffact, tfact)
    Returns: sorted list of (rate_date, fcurr, tcurr, kurst, final_rate) tuples
    """
    # EUR base rates
    eur_rates = {}
    for fcurr, ukurs, ffact, tfact in currencies:
        rate = compute_rate(ukurs, ffact, tfact)
        eur_rates[fcurr] = rate

    rows = []

    # EUR base rates: fcurr → EUR
    for fcurr, rate in eur_rates.items():
        rows.append((RATE_DATE, fcurr, TARGET_CURRENCY, KURST, rate))

    # EUR inverse rates: EUR → fcurr
    for fcurr, rate in eur_rates.items():
        inv = 1.0 / rate
        rows.append((RATE_DATE, TARGET_CURRENCY, fcurr, KURST, inv))

    # Cross rates: fcurr_a → fcurr_b = rate_a / rate_b
    fcurrs = list(eur_rates.keys())
    for a in fcurrs:
        for b in fcurrs:
            if a != b:
                cross = eur_rates[a] / eur_rates[b]
                rows.append((RATE_DATE, a, b, KURST, cross))

    # Identity rates: fcurr → fcurr = 1.0
    for fcurr in fcurrs:
        rows.append((RATE_DATE, fcurr, fcurr, KURST, 1.0))

    # Target identity: EUR → EUR = 1.0
    rows.append((RATE_DATE, TARGET_CURRENCY, TARGET_CURRENCY, KURST, 1.0))

    # Deduplicate by PK (rate_date, fcurr, tcurr, kurst)
    seen = {}
    for row in rows:
        key = (row[0], row[1], row[2], row[3])
        if key not in seen:
            seen[key] = row

    # Sort for deterministic output
    return sorted(seen.values(), key=lambda r: (r[0], r[1], r[2], r[3]))


# ---------------------------------------------------------------------------
# Phase definitions
# ---------------------------------------------------------------------------
# Phase 1: USD + INR
PHASE1_CURRENCIES = [
    ("USD", -2.0, 1, 1),   # rate = 1/2 = 0.5
    ("INR", -4.0, 1, 1),   # rate = 1/4 = 0.25
]

# Phase 2: USD + GBP (INR removed → those rows get deleted)
PHASE2_CURRENCIES = [
    ("USD", -2.0, 1, 1),   # rate = 0.5 (unchanged)
    ("GBP", -0.5, 1, 1),   # rate = 1/0.5 = 2.0
]


def build_tcurr_sheet(currencies):
    return [build_tcurr_row(fcurr, ukurs) for fcurr, ukurs, _, _ in currencies]


def build_tcurf_sheet(currencies):
    return [build_tcurf_row(fcurr, ffact, tfact) for fcurr, _, ffact, tfact in currencies]


def build_target_rows(currencies):
    """Compute expected target rows."""
    if not currencies:
        return []
    rates = compute_all_rates(currencies)
    return [[rd, fc, tc, ku, str(Decimal(str(fr)).quantize(Decimal('0.0000000001')))] for rd, fc, tc, ku, fr in rates]


# ---------------------------------------------------------------------------
# Workbook assembly
# ---------------------------------------------------------------------------
def add_sheet(wb, name, header, rows):
    ws = wb.create_sheet(name)
    ws.append(header)
    for r in rows:
        ws.append(r)


wb = Workbook()
del wb["Sheet"]

# Source sheets
add_sheet(wb, "tcurr_phase1", TCURR_NAMES, build_tcurr_sheet(PHASE1_CURRENCIES))
add_sheet(wb, "tcurr_phase2", TCURR_NAMES, build_tcurr_sheet(PHASE2_CURRENCIES))
add_sheet(wb, "tcurf", TCURF_NAMES, build_tcurf_sheet(PHASE1_CURRENCIES + PHASE2_CURRENCIES))

# Target sheets
add_sheet(wb, "target_phase0", TGT_NAMES, [])
add_sheet(wb, "target_phase1", TGT_NAMES, build_target_rows(PHASE1_CURRENCIES))
add_sheet(wb, "target_phase2", TGT_NAMES, build_target_rows(PHASE2_CURRENCIES))


wb.save(OUT)
print(f"wrote {OUT}")
print()
for phase in range(3):
    ws = wb[f"target_phase{phase}"]
    print(f"  target_phase{phase}: {ws.max_row - 1} rows")
print()
print("Phase 1 expected rates:")
for row in build_target_rows(PHASE1_CURRENCIES):
    print(f"  {row[1]:>3}→{row[2]:<3} = {row[4]}")
print()
print("Phase 2 expected rates:")
for row in build_target_rows(PHASE2_CURRENCIES):
    print(f"  {row[1]:>3}→{row[2]:<3} = {row[4]}")