package ct.dna.lakehouse.sr_raw.ct_it_test
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

@LakehouseEntity
case class ivanti_computer_E(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    lastsyncdateext_string: String,
    devicenameex_string: String,
    pmmu_string: String,
    netwareaddr_string: String,
    _sourceinstance_string: String,
    domainname_string: String,
    deviceid_string: String,
    multimedsize_long: BoxedLong,
    amtguid_string: String,
    virtmachname_string: String,
    lastenrollmentdateext_string: String,
    owneremail_string: String,
    _sourcehost_string: String,
    updatelastscandate_string: String,
    barcode_string: String,
    daysantivirus_long: BoxedLong,
    csepcredentials_idn_long: BoxedLong,
    description_string: String,
    ownerphone_string: String,
    orgunitpath_string: String,
    dsviewport_long: BoxedLong,
    swnumfiles_long: BoxedLong,
    daysspyware_long: BoxedLong,
    daysdriverupdate_long: BoxedLong,
    agentless_long: BoxedLong,
    lastpolicysync_string: String,
    devicename_string: String,
    workgroup_string: String,
    computername_string: String,
    patchswlastscandate_string: String,
    nummultimedfiles_long: BoxedLong,
    swpackagelastscandate_string: String,
    flpydrvcnt_string: String,
    multimedext_string: String,
    coprocessor_string: String,
    minilastscandate_string: String,
    workflowstatusid_long: BoxedLong,
    mainboardoem_name_string: String,
    hwlastscandate_string: String,
    hwmonitoringtype_string: String,
    swlastscandate_string: String,
    patchdriverslastscandate_string: String,
    daysupdate_long: BoxedLong,
    agls_status_long: BoxedLong,
    mdmid_string: String,
    virtmachid_string: String,
    notify_on_change_long: BoxedLong,
    dayscompliance_long: BoxedLong,
    primaryowner_string: String,
    daysblocked_long: BoxedLong,
    dayshardware_long: BoxedLong,
    manufacturer_string: String,
    os2comment_string: String,
    tenantuid_string: String,
    ldaplocation_string: String,
    laptop_string: String,
    lastupdinvsvr_string: String,
    dayscustomdef_long: BoxedLong,
    ntdomaincontroller_string: String,
    lastwmiscandate_string: String,
    computerlocation_string: String,
    inventoryserver_string: String,
    systemoem_name_string: String,
    type_string: String,
    valastscandate_string: String,
    spywarelastscandate_string: String,
    cloudtenantuid_string: String,
    computerexiststime_long: BoxedLong,
    fullname_string: String,
    dayssecurity_long: BoxedLong,
    patchavlastscandate_string: String,
    tenantname_string: String,
    ramcache_long: BoxedLong,
    model_string: String,
    daysinvserver_long: BoxedLong,
    agls_lastattempted_string: String,
    ipmiguid_string: String,
    companyname_string: String,
    barcodeconfig_string: String,
    contains_masked_personal_data_boolean: BoxedBoolean,
    recorddate_string: String,
    computer_idn_long: BoxedLong,
    devicetype_string: String,
    blockedlastscandate_string: String,
    staticlocation_string: String,
    modelnum_string: String,
    serialnumber_string: String,
    dayssofupdates_long: BoxedLong,
    _sourcedb_string: String,
    _sourceport_long: BoxedLong,
    loginname_string: String,
    displayname_string: String,
    userdefinedlastscandate_string: String,
    compliancelastscandate_string: String,
    scantype_string: String,
    status_string: String,
    securitylastscandate_string: String,
    lastdeployedosimage_string: String,
    hardwareid_string: String,
    lastlogondate_string: String,
    servertype_string: String,
    daysvulnerabil_long: BoxedLong,
    dayssoftware_long: BoxedLong,
    qualifieduser_string: String,
    coreguid_string: String,
    domain_string: String,
    location_string: String
) extends Entity

object ivanti_computer
    extends TableSpec[ivanti_computer_E](
      enableChangeDataFeed = true,
      manualClusterBy = None,
      timetravelDays = 35
    )
    with Loaded
