package ct.dna.lakehouse.sr_raw.ct_it_test
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

@LakehouseEntity
case class ivanti_processor_E(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    _sourcehost_string: String,
    virtmodeext_string: String,
    leaseexp_long: BoxedLong,
    pkgcount_long: BoxedLong,
    procfamily_string: String,
    totalcores_long: BoxedLong,
    featurestepping_string: String,
    memorytyperangereg_string: String,
    model_string: String,
    dhcpserv_string: String,
    featureid_string: String,
    stepping_string: String,
    procindex_string: String,
    physaddrext_string: String,
    machchkexcept_string: String,
    execdisable_string: String,
    mmx_string: String,
    mhzspeed_long: BoxedLong,
    hyperthreading_string: String,
    procserialnum_string: String,
    speed_long: BoxedLong,
    condmoveinstr_string: String,
    currspeed_long: BoxedLong,
    cmpxchg8binstsppt_string: String,
    proctype_string: String,
    type_string: String,
    id_string: String,
    apic_string: String,
    modelregisters_string: String,
    pageglobalenable_string: String,
    timestampcnt_string: String,
    procversion_string: String,
    slsignature_string: String,
    computer_idn_long: BoxedLong,
    procupgrade_string: String,
    cachesize_long: BoxedLong,
    architecture_string: String,
    processorphysicalcount_long: BoxedLong,
    coresperpkg_long: BoxedLong,
    globalpageenable_string: String,
    opgrpindex_long: BoxedLong,
    revision_string: String,
    pkgcores_long: BoxedLong,
    _sourcedb_string: String,
    _sourceport_long: BoxedLong,
    externalclockspeed_long: BoxedLong,
    overdriveupgrade_string: String,
    maxspeed_string: String,
    allocgran_long: BoxedLong,
    proccount_long: BoxedLong,
    proccnt_long: BoxedLong,
    pagesizeext_string: String,
    _sourceinstance_string: String,
    proclevel_string: String,
    em64t_string: String,
    machinecheckarch_string: String,
    vendor_string: String,
    frugrpindex_long: BoxedLong,
    coreguid_string: String
) extends Entity

object ivanti_processor
    extends TableSpec[ivanti_processor_E](
      enableChangeDataFeed = true,
      manualClusterBy = None,
      timetravelDays = 35
    )
    with Loaded
