package ct.dna.lakehouse.sr_raw.ct_it_test
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

@LakehouseEntity
case class ld_task_E(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    last_start_string: String,
    targeted_ipv6_string: String,
    processing_checkpoint_string: String,
    targetallusers_long: BoxedLong,
    query_idn_long: BoxedLong,
    user_customgroup_idn_long: BoxedLong,
    times_tried_long: BoxedLong,
    _sourcehost_string: String,
    last_end_string: String,
    reschedule_type_gui_long: BoxedLong,
    skeleton_complete_long: BoxedLong,
    clientpolicyhash_string: String,
    overrides_string: String,
    tasktype_long: BoxedLong,
    syncenabled_long: BoxedLong,
    always_run_long: BoxedLong,
    deliverymethod_idn_long: BoxedLong,
    ld_task_idn_long: BoxedLong,
    task_status_long: BoxedLong,
    max_retries_long: BoxedLong,
    ld_task_config_idn_long: BoxedLong,
    timezone_aware_string: String,
    notes_string: String,
    guid_string: String,
    package_idn_long: BoxedLong,
    task_reboot_machines_long: BoxedLong,
    day_month_flags_long: BoxedLong,
    sourcecore_string: String,
    scopeuser_idn_long: BoxedLong,
    remote_object_name_string: String,
    query_type_long: BoxedLong,
    task_wake_machines_long: BoxedLong,
    last_modified_string: String,
    revision_long: BoxedLong,
    clientpolicyfile_string: String,
    initial_start_string: String,
    lastsaveddate_string: String,
    remote_object_hash_string: String,
    day_week_flags_long: BoxedLong,
    autostart_long: BoxedLong,
    common_customgroup_idn_long: BoxedLong,
    contains_masked_personal_data_boolean: BoxedBoolean,
    repeatinterval_long: BoxedLong,
    ispublic_long: BoxedLong,
    next_start_string: String,
    lastsavedby_string: String,
    consoleuser_idn_long: BoxedLong,
    last_status_long: BoxedLong,
    _sourcedb_string: String,
    _sourceport_long: BoxedLong,
    policyhash_string: String,
    task_name_string: String,
    isipv6_long: BoxedLong,
    last_reschedule_timet_long: BoxedLong,
    _sourceinstance_string: String,
    grouptag_string: String,
    reschedule_type_long: BoxedLong,
    limitbyallowedmachines_long: BoxedLong
) extends Entity

object ld_task
    extends TableSpec[ld_task_E](
      enableChangeDataFeed = true,
      manualClusterBy = None,
      timetravelDays = 35
    )
    with Loaded
