package ct.dna.lakehouse.sr_raw.ct_it_test
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

@LakehouseEntity
case class masda_batches_E(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    meta_ts_ms_long: BoxedLong,
    value_time_gate_close_s_string: String,
    meta_source_table_string: String,
    value_plant_string: String,
    value_mixer_motor_winding_bottom_temp_2_f_string: String,
    value_mixer_rotor_dust_stop_ring_1_temp_f_string: String,
    value_mixer_motor_winding_top_temp_2_f_string: String,
    value_mixer_motor_tcu_air_out_f_string: String,
    value_batch_num_long: BoxedLong,
    value_time_gate_open_s_string: String,
    meta_source_db_string: String,
    value_time_electrical_power_peak_s_string: String,
    value_barrel_tcu_fluid_out_f_string: String,
    key_record_id_long: BoxedLong,
    value_time_discharge_s_string: String,
    meta_source_ts_us_long: BoxedLong,
    value_record_timestamp_string: String,
    value_temp_peak_f_string: String,
    value_front_mill_tcu_fluid_out_f_string: String,
    value_bottom_roll_tcu_fluid_out_f_string: String,
    meta_source_version_string: String,
    value_top_roll_tcu_fluid_in_f_string: String,
    meta_source_connector_string: String,
    value_time_charge_s_string: String,
    value_counts_lube_oil_per_min_string: String,
    value_wt_slab_1_lb_string: String,
    value_counts_ring_oil_per_min_string: String,
    value_time_ram_up_s_string: String,
    value_mixer_motor_arm_voltage_at_drop_v_string: String,
    value_front_mill_tcu_fluid_in_f_string: String,
    meta_source_name_string: String,
    value_screw_tcu_fluid_out_f_string: String,
    value_screw_tcu_fluid_in_f_string: String,
    value_time_door_close_s_string: String,
    value_mixer_motor_winding_top_temp_1_f_string: String,
    value_mixer_motor_tcu_air_in_f_string: String,
    meta_source_ts_ms_long: BoxedLong,
    value_motor_electrical_power_peak_kw_string: String,
    meta_op_string: String,
    meta_source_snapshot_string: String,
    value_bottom_roll_tcu_fluid_in_f_string: String,
    meta_source_ts_ns_long: BoxedLong,
    value_time_door_open_s_string: String,
    value_time_ram_down_s_string: String,
    value_motor_electrical_power_at_drop_kw_string: String,
    value_mixer_rotor_dust_stop_ring_2_temp_f_string: String,
    value_drop_code_string: String,
    value_mixer_rotor_dust_stop_ring_3_temp_f_string: String,
    value_mixer_motor_arm_current_at_drop_amp_string: String,
    value_wt_black_lb_string: String,
    meta_source_lsn_long: BoxedLong,
    value_time_idle_s_string: String,
    value_time_mix_s_string: String,
    value_drop_time_utc_string: String,
    value_back_mill_tcu_fluid_out_f_string: String,
    value_top_roll_tcu_fluid_out_f_string: String,
    value_motor_electrical_energy_kwh_string: String,
    value_mixer_rotor_dust_stop_ring_4_temp_f_string: String,
    value_drop_time_long: BoxedLong,
    value_wt_pigment_lb_string: String,
    value_unix_run_num_string: String,
    value_gate_retry_count_long: BoxedLong,
    value_time_ram_seat_s_string: String,
    value_temp_drop_f_string: String,
    meta_source_schema_string: String,
    value_mix_equivalents_string: String,
    value_wt_oil_lb_string: String,
    value_mixer_motor_winding_bottom_temp_1_f_string: String,
    meta_source_txid_long: BoxedLong,
    meta_source_sequence_string: String,
    value_back_mill_tcu_fluid_in_f_string: String,
    value_barrel_tcu_fluid_in_f_string: String
) extends Entity

object masda_batches
    extends TableSpec[masda_batches_E](
      enableChangeDataFeed = true,
      manualClusterBy = None,
      timetravelDays = 35
    )
    with Loaded
