package ct.dna.lakehouse.sr_raw.ct_it_test
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

@LakehouseEntity
case class mirezept_E(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    value_metalsu_string: String,
    meta_ts_ms_long: BoxedLong,
    value_p_fkt_16_string: String,
    value_palgew_long: BoxedLong,
    value_b_fkt_15_string: String,
    value_messer_gruppe_a_14_string: String,
    value_maschknr_string: String,
    value_oeleinspritzart_long: BoxedLong,
    value_ventilatorgruppe_1_string: String,
    value_mintemp_long: BoxedLong,
    value_p_fkt_15_string: String,
    value_b_fkt_10_string: String,
    value_ktempz3_long: BoxedLong,
    value_minzykzeit_long: BoxedLong,
    value_name_string: String,
    value_einlaufwalzeein_string: String,
    value_absaug_string: String,
    value_minspezen_long: BoxedLong,
    value_ventilatorgruppe_3_string: String,
    value_aendken_string: String,
    value_ventilatorgruppe_10_string: String,
    value_entwicklernummer_string: String,
    value_zusp4_long: BoxedLong,
    value_messer_gruppe_b_7_string: String,
    value_b_fkt_6_string: String,
    value_zusp3_long: BoxedLong,
    value_soefzeit_long: BoxedLong,
    meta_source_version_string: String,
    value_messer_gruppe_a_5_string: String,
    value_p_fkt_9_string: String,
    value_p_fkt_3_string: String,
    value_datum_long: BoxedLong,
    meta_source_table_string: String,
    value_p_fkt_11_string: String,
    value_anzwalz_long: BoxedLong,
    value_ventilatorgruppe_16_string: String,
    value_messer_gruppe_b_11_string: String,
    value_einlaufgeschwindigkeit_long: BoxedLong,
    value_b_fkt_16_string: String,
    value_messer_gruppe_b_14_string: String,
    value_messer_gruppe_b_1_string: String,
    value_messer_gruppe_a_15_string: String,
    value_messer_gruppe_b_13_string: String,
    value_maxheathistory_long: BoxedLong,
    value_ventilatorgruppe_11_string: String,
    value_beschz_long: BoxedLong,
    meta_source_connector_string: String,
    value_messer_gruppe_a_7_string: String,
    value_b_fkt_14_string: String,
    value_auslauftemperatur_long: BoxedLong,
    value_ventilatorgruppe_4_string: String,
    value_sperrzeit_long: BoxedLong,
    value_drehzahloel_long: BoxedLong,
    value_messer_gruppe_a_12_string: String,
    value_verlegemodus_string: String,
    value_messer_gruppe_b_6_string: String,
    value_ventilatorgruppe_8_string: String,
    value_b_fkt_11_string: String,
    value_anzlue_long: BoxedLong,
    value_messer_gruppe_a_1_string: String,
    value_p_fkt_13_string: String,
    value_messer_gruppe_a_9_string: String,
    value_messer_gruppe_b_10_string: String,
    value_stkgew_long: BoxedLong,
    value_ktempz2_long: BoxedLong,
    value_messer_gruppe_b_15_string: String,
    meta_source_name_string: String,
    value_messer_gruppe_b_16_string: String,
    value_messer_gruppe_b_5_string: String,
    value_arbeitsg_string: String,
    value_staubabd_string: String,
    value_maxtemp_long: BoxedLong,
    value_prozstrg_string: String,
    value_messer_gruppe_a_10_string: String,
    meta_source_commit_lsn_string: String,
    meta_source_ts_ms_long: BoxedLong,
    value_starttemp_long: BoxedLong,
    value_minlagerk_string: String,
    value_ventilatorgruppe_12_string: String,
    value_p_fkt_2_string: String,
    value_p_fkt_7_string: String,
    value_ventilatorgruppe_5_string: String,
    value_drehzahlnot_long: BoxedLong,
    value_p_fkt_4_string: String,
    value_b_fkt_13_string: String,
    value_ventilatorgruppe_13_string: String,
    meta_op_string: String,
    meta_source_snapshot_string: String,
    value_ventilatorgruppe_14_string: String,
    value_p_fkt_14_string: String,
    value_einlauftemperatur_long: BoxedLong,
    value_dichte_string: String,
    value_rowguid_string: String,
    value_produkt_string: String,
    value_mizyklz_long: BoxedLong,
    value_maxdrehza_long: BoxedLong,
    value_b_fkt_9_string: String,
    value_auswdrehz_long: BoxedLong,
    value_ktempz4_long: BoxedLong,
    value_einlaufwalzendruck_long: BoxedLong,
    value_minmizeit_long: BoxedLong,
    value_mindrehza_long: BoxedLong,
    key_twerkst_string: String,
    value_zusprot_long: BoxedLong,
    value_maxmizeit_long: BoxedLong,
    value_barcodetyp_string: String,
    value_auslaufgeschwindigkeit_long: BoxedLong,
    value_anzmat_long: BoxedLong,
    value_p_fkt_10_string: String,
    value_messer_gruppe_b_8_string: String,
    value_messer_gruppe_a_11_string: String,
    value_p_fkt_6_string: String,
    value_ventilatorgruppe_9_string: String,
    value_p_fkt_8_string: String,
    value_bearbhinweis_string: String,
    value_laserein_string: String,
    value_zusp2_long: BoxedLong,
    value_messer_gruppe_b_2_string: String,
    value_pausenzeitoel_long: BoxedLong,
    value_ventilatorgruppe_15_string: String,
    value_anzpruef_long: BoxedLong,
    value_messer_gruppe_b_4_string: String,
    value_messer_gruppe_a_13_string: String,
    value_messer_gruppe_a_2_string: String,
    value_messer_gruppe_a_16_string: String,
    value_rezstat_string: String,
    value_b_fkt_7_string: String,
    value_p_fkt_5_string: String,
    value_maxlagerz_long: BoxedLong,
    value_schlaufenlaenge_long: BoxedLong,
    value_p_fkt_12_string: String,
    value_minlagerz_long: BoxedLong,
    value_ventilatorgruppe_7_string: String,
    value_messer_gruppe_a_3_string: String,
    value_messer_gruppe_a_4_string: String,
    value_anfangsschlaufenlaenge_long: BoxedLong,
    value_p_fkt_1_string: String,
    value_messer_gruppe_a_6_string: String,
    value_praegewalzeein_string: String,
    value_ventilatorgruppe_6_string: String,
    value_zusp1_long: BoxedLong,
    value_b_fkt_12_string: String,
    value_b_fkt_5_string: String,
    value_messer_gruppe_b_9_string: String,
    value_messer_gruppe_a_8_string: String,
    value_maxspezen_long: BoxedLong,
    value_ktempz1_long: BoxedLong,
    value_ventilatorgruppe_2_string: String,
    value_pulszeitoel_long: BoxedLong,
    value_messer_gruppe_b_12_string: String,
    meta_source_schema_string: String,
    meta_source_db_string: String,
    value_b_fkt_8_string: String,
    value_messer_gruppe_b_3_string: String,
    value_pruefk_string: String,
    value_b_fkt_4_string: String,
    value_maxlagerk_string: String,
    value_bedrehz_long: BoxedLong,
    meta_source_ts_us_long: BoxedLong,
    meta_source_event_serial_no_long: BoxedLong,
    meta_source_ts_ns_long: BoxedLong,
    meta_source_change_lsn_string: String
) extends Entity

object mirezept
    extends TableSpec[mirezept_E](
      enableChangeDataFeed = true,
      manualClusterBy = None,
      timetravelDays = 35
    )
    with Loaded
