package ct.dna.lakehouse.sr_raw.ct_it_test
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

@LakehouseEntity
case class pl_mysuccess_api_user_E(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    udf05_cust_string: String,
    objective_string: String,
    udf13_cust_string: String,
    firstname_string: String,
    jobcode_string: String,
    dateofbirth_string: String,
    pronouns_string: String,
    isalumni_boolean: BoxedBoolean,
    impactofloss_string: String,
    teammemberssize_long: BoxedLong,
    performance_string: String,
    dateofposition_string: String,
    udf02_cust_string: String,
    custom01_string: String,
    udf16_cust_string: String,
    timezone_string: String,
    udf09_cust_string: String,
    custom15_string: String,
    custom14_string: String,
    matrixmanaged_boolean: BoxedBoolean,
    udf07_cust_string: String,
    competency_string: String,
    udf12_cust_string: String,
    title_string: String,
    defaultfullname_string: String,
    custom09_string: String,
    udf19_cust_string: String,
    zipcode_string: String,
    servicedate_string: String,
    addressline1_string: String,
    udf06_cust_string: String,
    mi_string: String,
    citizenship_string: String,
    empid_string: String,
    loginmethod_string: String,
    hiredate_string: String,
    scilastmodified_string: String,
    lastname_string: String,
    state_string: String,
    newtoposition_boolean: BoxedBoolean,
    udf08_cust_string: String,
    nationality_string: String,
    isprimaryassignment_boolean: BoxedBoolean,
    custom05_string: String,
    udf15_cust_string: String,
    udf10_cust_string: String,
    country_string: String,
    city_string: String,
    division_string: String,
    matrix1label_string: String,
    assignmentuuid_string: String,
    department_string: String,
    minority_boolean: BoxedBoolean,
    companyexitdate_string: String,
    gender_string: String,
    married_boolean: BoxedBoolean,
    businessphone_string: String,
    lastmodified_string: String,
    totalteamsize_string: String,
    udf01_cust_string: String,
    custom12_string: String,
    custom10_string: String,
    udf21_cust_string: String,
    potential_string: String,
    userid_string: String,
    nickname_string: String,
    keyposition_boolean: BoxedBoolean,
    defaultlocale_string: String,
    udf14_cust_string: String,
    addressline2_string: String,
    custom06_string: String,
    contains_masked_personal_data_boolean: BoxedBoolean,
    lastmodifieddatetime_string: String,
    custom03_string: String,
    location_string: String,
    suffix_string: String,
    futureleader_boolean: BoxedBoolean,
    riskofloss_string: String,
    lastmodifiedwithtz_string: String,
    onboardingid_string: String,
    custom13_string: String,
    udf11_cust_string: String,
    displayname_string: String,
    username_string: String,
    ethnicity_string: String,
    udf04_cust_string: String,
    email_string: String,
    reasonforleaving_string: String,
    udf18_cust_string: String,
    udf22_cust_string: String,
    salutation_string: String,
    udf03_cust_string: String,
    custom11_string: String,
    status_string: String,
    jobfamily_string: String,
    custom02_string: String,
    udf17_cust_string: String,
    udf25_cust_string: String,
    custom07_string: String,
    custom04_string: String
) extends Entity

object pl_mysuccess_api_user
    extends TableSpec[pl_mysuccess_api_user_E](
      enableChangeDataFeed = true,
      manualClusterBy = None,
      timetravelDays = 35
    )
    with Loaded
