package ct.dna.lakehouse.sr_raw.ct_it_test
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class pl_mysuccess_api_empjob_E(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  businessunit_string: String,
  customstring44_string: String,
  customstring4_string: String,
  customstring9_string: String,
  userid_string: String,
  countryofcompany_string: String,
  lastmodifiedon_string: String,
  customstring6_string: String,
  customstring2_string: String,
  startdate_string: String,
  fte_string: String,
  customstring12_string: String,
  exclexecutivesector_boolean: BoxedBoolean,
  customstring27_string: String,
  employmenttype_string: String,
  managerid_string: String,
  enddate_string: String,
  positionentrydate_string: String,
  worklocation_string: String,
  customstring8_string: String,
  costcenter_string: String,
  customstring30_string: String,
  paygrade_string: String,
  customstring34_string: String,
  workschedulecode_string: String,
  regulartemp_string: String,
  createdby_string: String,
  customstring28_string: String,
  customstring13_string: String,
  workingtimedirective_boolean: BoxedBoolean,
  customdouble1_string: String,
  customstring10_string: String,
  company_string: String,
  division_string: String,
  department_string: String,
  holidaycalendarcode_string: String,
  eventreason_string: String,
  lastmodifiedby_string: String,
  customstring43_string: String,
  customstring54_string: String,
  customstring19_string: String,
  customstring31_string: String,
  jobcode_string: String,
  position_string: String,
  issidelinejoballowed_boolean: BoxedBoolean,
  standardhours_string: String,
  employeeclass_string: String,
  contracttype_string: String,
  emplstatus_string: String,
  customstring17_string: String,
  customstring16_string: String,
  customstring33_string: String,
  customstring7_string: String,
  customstring14_string: String,
  contains_masked_personal_data_boolean: BoxedBoolean,
  customstring5_string: String,
  lastmodifieddatetime_string: String,
  location_string: String,
  createddatetime_string: String,
  noticeperiod_string: String,
  customstring53_string: String,
  customstring26_string: String,
  customstring20_string: String,
  customstring15_string: String,
  iscrossborderworker_boolean: BoxedBoolean,
  createdon_string: String,
  customstring29_string: String,
  event_string: String,
  customdate2_string: String,
  probationperiodenddate_string: String,
  customstring3_string: String,
  customdate1_string: String
) extends Entity

object pl_mysuccess_api_empjob extends TableSpec[pl_mysuccess_api_empjob_E](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
