// LOADED TABLE SPEC AUTO GENERATED:START
// Generated by LoadedTableSpecAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr_raw.ct_gbl_pbr

import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.Loaded
import ct.dna.lakehouse.core.model.TableSpec

case class E_vbup(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt_string: String,
    vbeln_string: String,
    posnr_string: String,
    rfsta_string: String,
    rfgsa_string: String,
    besta_string: String,
    lfsta_string: String,
    lfgsa_string: String,
    wbsta_string: String,
    fksta_string: String,
    fksaa_string: String,
    absta_string: String,
    gbsta_string: String,
    kosta_string: String,
    lvsta_string: String,
    uvall_string: String,
    uvvlk_string: String,
    uvfak_string: String,
    uvprs_string: String,
    fkivp_string: String,
    uvp01_string: String,
    uvp02_string: String,
    uvp03_string: String,
    uvp04_string: String,
    uvp05_string: String,
    pksta_string: String,
    koqua_string: String,
    costa_string: String,
    cmppi_string: String,
    cmppj_string: String,
    uvpik_string: String,
    uvpak_string: String,
    uvwak_string: String,
    dcsta_string: String,
    rrsta_string: String,
    vlstp_string: String,
    fssta_string: String,
    lssta_string: String,
    pdsta_string: String,
    manek_string: String,
    hdall_string: String,
    bump_string: String,
    ltsps_string: String,
    _sapmp_lbasp_string: String,
    fsh_ar_stat_itm_string: String,
    mill_vs_vssta_string: String
) extends Entity

object vbup
    extends TableSpec[E_vbup](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.Columns("_mk_instance", "_mk_partition", "_mk_file"),
      timetravelDays = 35
    )
    with Loaded
// LOADED TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_vbup(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val mandt_string: ColumnWithName = ColumnWithName(prefix + "mandt_string")
  val vbeln_string: ColumnWithName = ColumnWithName(prefix + "vbeln_string")
  val posnr_string: ColumnWithName = ColumnWithName(prefix + "posnr_string")
  val rfsta_string: ColumnWithName = ColumnWithName(prefix + "rfsta_string")
  val rfgsa_string: ColumnWithName = ColumnWithName(prefix + "rfgsa_string")
  val besta_string: ColumnWithName = ColumnWithName(prefix + "besta_string")
  val lfsta_string: ColumnWithName = ColumnWithName(prefix + "lfsta_string")
  val lfgsa_string: ColumnWithName = ColumnWithName(prefix + "lfgsa_string")
  val wbsta_string: ColumnWithName = ColumnWithName(prefix + "wbsta_string")
  val fksta_string: ColumnWithName = ColumnWithName(prefix + "fksta_string")
  val fksaa_string: ColumnWithName = ColumnWithName(prefix + "fksaa_string")
  val absta_string: ColumnWithName = ColumnWithName(prefix + "absta_string")
  val gbsta_string: ColumnWithName = ColumnWithName(prefix + "gbsta_string")
  val kosta_string: ColumnWithName = ColumnWithName(prefix + "kosta_string")
  val lvsta_string: ColumnWithName = ColumnWithName(prefix + "lvsta_string")
  val uvall_string: ColumnWithName = ColumnWithName(prefix + "uvall_string")
  val uvvlk_string: ColumnWithName = ColumnWithName(prefix + "uvvlk_string")
  val uvfak_string: ColumnWithName = ColumnWithName(prefix + "uvfak_string")
  val uvprs_string: ColumnWithName = ColumnWithName(prefix + "uvprs_string")
  val fkivp_string: ColumnWithName = ColumnWithName(prefix + "fkivp_string")
  val uvp01_string: ColumnWithName = ColumnWithName(prefix + "uvp01_string")
  val uvp02_string: ColumnWithName = ColumnWithName(prefix + "uvp02_string")
  val uvp03_string: ColumnWithName = ColumnWithName(prefix + "uvp03_string")
  val uvp04_string: ColumnWithName = ColumnWithName(prefix + "uvp04_string")
  val uvp05_string: ColumnWithName = ColumnWithName(prefix + "uvp05_string")
  val pksta_string: ColumnWithName = ColumnWithName(prefix + "pksta_string")
  val koqua_string: ColumnWithName = ColumnWithName(prefix + "koqua_string")
  val costa_string: ColumnWithName = ColumnWithName(prefix + "costa_string")
  val cmppi_string: ColumnWithName = ColumnWithName(prefix + "cmppi_string")
  val cmppj_string: ColumnWithName = ColumnWithName(prefix + "cmppj_string")
  val uvpik_string: ColumnWithName = ColumnWithName(prefix + "uvpik_string")
  val uvpak_string: ColumnWithName = ColumnWithName(prefix + "uvpak_string")
  val uvwak_string: ColumnWithName = ColumnWithName(prefix + "uvwak_string")
  val dcsta_string: ColumnWithName = ColumnWithName(prefix + "dcsta_string")
  val rrsta_string: ColumnWithName = ColumnWithName(prefix + "rrsta_string")
  val vlstp_string: ColumnWithName = ColumnWithName(prefix + "vlstp_string")
  val fssta_string: ColumnWithName = ColumnWithName(prefix + "fssta_string")
  val lssta_string: ColumnWithName = ColumnWithName(prefix + "lssta_string")
  val pdsta_string: ColumnWithName = ColumnWithName(prefix + "pdsta_string")
  val manek_string: ColumnWithName = ColumnWithName(prefix + "manek_string")
  val hdall_string: ColumnWithName = ColumnWithName(prefix + "hdall_string")
  val bump_string: ColumnWithName = ColumnWithName(prefix + "bump_string")
  val ltsps_string: ColumnWithName = ColumnWithName(prefix + "ltsps_string")
  val _sapmp_lbasp_string: ColumnWithName = ColumnWithName(prefix + "_sapmp_lbasp_string")
  val fsh_ar_stat_itm_string: ColumnWithName = ColumnWithName(prefix + "fsh_ar_stat_itm_string")
  val mill_vs_vssta_string: ColumnWithName = ColumnWithName(prefix + "mill_vs_vssta_string")
}

object C_vbup extends C_vbup("") {
  def as(alias: String): C_vbup = new C_vbup(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
