// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_p43

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_p43.{stpo => sr_raw_stpo}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, hex, lit, struct}

case class SrStpo(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK stlty: String,
    @PK stlnr: String,
    @PK stlkn: String,
    @PK stpoz: String,
    datuv: String,
    techv: String,
    aennr: String,
    lkenz: String,
    vgknt: String,
    vgpzl: String,
    andat: String,
    annam: String,
    aedat: String,
    aenam: String,
    idnrk: String,
    pswrk: String,
    postp: String,
    posnr: String,
    sortf: String,
    meins: String,
    @Decimal(13, 3) menge: java.math.BigDecimal,
    fmeng: String,
    @Decimal(5, 2) ausch: java.math.BigDecimal,
    @Decimal(5, 2) avoau: java.math.BigDecimal,
    netau: String,
    schgt: String,
    beikz: String,
    erskz: String,
    rvrel: String,
    sanfe: String,
    sanin: String,
    sanka: String,
    sanko: String,
    sanvs: String,
    stkkz: String,
    rekri: String,
    rekrs: String,
    cadpo: String,
    nfmat: String,
    @Decimal(3, 0) nlfzt: java.math.BigDecimal,
    verti: String,
    alpos: String,
    @Decimal(3, 0) ewahr: java.math.BigDecimal,
    ekgrp: String,
    @Decimal(3, 0) lifzt: java.math.BigDecimal,
    lifnr: String,
    @Decimal(11, 2) preis: java.math.BigDecimal,
    @Decimal(5, 0) peinh: java.math.BigDecimal,
    waers: String,
    sakto: String,
    @Decimal(13, 3) roanz: java.math.BigDecimal,
    @Decimal(13, 3) roms1: java.math.BigDecimal,
    @Decimal(13, 3) roms2: java.math.BigDecimal,
    @Decimal(13, 3) roms3: java.math.BigDecimal,
    romei: String,
    @Decimal(13, 3) romen: java.math.BigDecimal,
    rform: String,
    upskz: String,
    valkz: String,
    ltxsp: String,
    potx1: String,
    potx2: String,
    objty: String,
    matkl: String,
    @Decimal(3, 0) webaz: java.math.BigDecimal,
    dokar: String,
    doknr: String,
    dokvr: String,
    doktl: String,
    @Decimal(5, 2) csstr: java.math.BigDecimal,
    _class_string: String,
    klart: String,
    potpr: String,
    awakz: String,
    inskz: String,
    vcekz: String,
    vstkz: String,
    vackz: String,
    ekorg: String,
    clobk: String,
    clmul: String,
    clalt: String,
    cview: String,
    knobj: String,
    lgort: String,
    kzkup: String,
    intrm: String,
    tpekz: String,
    stvkn: String,
    dvdat: String,
    dvnam: String,
    dspst: String,
    alpst: String,
    alprf: String,
    alpgr: String,
    kznfp: String,
    nfgrp: String,
    nfeag: String,
    kndvb: String,
    kndbz: String,
    kstty: String,
    kstnr: String,
    kstkn: String,
    kstpz: String,
    clszu: String,
    kzclb: String,
    aehlp: String,
    prvbe: String,
    @Decimal(3, 0) nlfzv: java.math.BigDecimal,
    nlfmv: String,
    idpos: String,
    idhis: String,
    idvar: String,
    alekz: String,
    itmid: String,
    guid: String,
    itsob: String,
    rfpnt: String,
    guidx: String,
    sgt_cmkz: String,
    sgt_catv: String,
    valid_to: String,
    valid_to_rkey: String,
    ecn_to: String,
    ecn_to_rkey: String,
    ablad: String,
    wempf: String,
    cufactor: String,
    _sapmp_met_lrch: String,
    @Decimal(13, 3) _sapmp_max_fertl: java.math.BigDecimal,
    @Decimal(13, 3) _sapmp_fix_as_j: java.math.BigDecimal,
    @Decimal(13, 3) _sapmp_fix_as_e: java.math.BigDecimal,
    @Decimal(13, 3) _sapmp_fix_as_l: java.math.BigDecimal,
    _sapmp_abl_zahl: String,
    @Decimal(13, 3) _sapmp_rund_fakt: java.math.BigDecimal,
    fsh_vmkz: String,
    fsh_pgqr: String,
    fsh_pgqrrf: String,
    fsh_critical_comp: String,
    @Decimal(2, 0) fsh_critical_level: java.math.BigDecimal,
    funcid: String
) extends Entity

object stpo extends TableSpec[SrStpo] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_p43.E_stpo] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_p43.E_stpo] = sr_raw_stpo

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("stlty", coalesce(col("stlty_string"), lit(""))),
    ("stlnr", coalesce(col("stlnr_string"), lit(""))),
    ("stlkn", coalesce(col("stlkn_string"), lit(""))),
    ("stpoz", coalesce(col("stpoz_string"), lit(""))),
    ("datuv", col("datuv_string")),
    ("techv", col("techv_string")),
    ("aennr", col("aennr_string")),
    ("lkenz", col("lkenz_string")),
    ("vgknt", col("vgknt_string")),
    ("vgpzl", col("vgpzl_string")),
    ("andat", col("andat_string")),
    ("annam", col("annam_string")),
    ("aedat", col("aedat_string")),
    ("aenam", col("aenam_string")),
    ("idnrk", col("idnrk_string")),
    ("pswrk", col("pswrk_string")),
    ("postp", col("postp_string")),
    ("posnr", col("posnr_string")),
    ("sortf", col("sortf_string")),
    ("meins", col("meins_string")),
    ("menge", col("menge_decimal_13_3")),
    ("fmeng", col("fmeng_string")),
    ("ausch", col("ausch_decimal_5_2")),
    ("avoau", col("avoau_decimal_5_2")),
    ("netau", col("netau_string")),
    ("schgt", col("schgt_string")),
    ("beikz", col("beikz_string")),
    ("erskz", col("erskz_string")),
    ("rvrel", col("rvrel_string")),
    ("sanfe", col("sanfe_string")),
    ("sanin", col("sanin_string")),
    ("sanka", col("sanka_string")),
    ("sanko", col("sanko_string")),
    ("sanvs", col("sanvs_string")),
    ("stkkz", col("stkkz_string")),
    ("rekri", col("rekri_string")),
    ("rekrs", col("rekrs_string")),
    ("cadpo", col("cadpo_string")),
    ("nfmat", col("nfmat_string")),
    ("nlfzt", col("nlfzt_decimal_3_0")),
    ("verti", col("verti_string")),
    ("alpos", col("alpos_string")),
    ("ewahr", col("ewahr_decimal_3_0")),
    ("ekgrp", col("ekgrp_string")),
    ("lifzt", col("lifzt_decimal_3_0")),
    ("lifnr", col("lifnr_string")),
    ("preis", col("preis_decimal_11_2")),
    ("peinh", col("peinh_decimal_5_0")),
    ("waers", col("waers_string")),
    ("sakto", col("sakto_string")),
    ("roanz", col("roanz_decimal_13_3")),
    ("roms1", col("roms1_decimal_13_3")),
    ("roms2", col("roms2_decimal_13_3")),
    ("roms3", col("roms3_decimal_13_3")),
    ("romei", col("romei_string")),
    ("romen", col("romen_decimal_13_3")),
    ("rform", col("rform_string")),
    ("upskz", col("upskz_string")),
    ("valkz", col("valkz_string")),
    ("ltxsp", col("ltxsp_string")),
    ("potx1", col("potx1_string")),
    ("potx2", col("potx2_string")),
    ("objty", col("objty_string")),
    ("matkl", col("matkl_string")),
    ("webaz", col("webaz_decimal_3_0")),
    ("dokar", col("dokar_string")),
    ("doknr", col("doknr_string")),
    ("dokvr", col("dokvr_string")),
    ("doktl", col("doktl_string")),
    ("csstr", col("csstr_decimal_5_2")),
    ("_class_string", col("_class_string")),
    ("klart", col("klart_string")),
    ("potpr", col("potpr_string")),
    ("awakz", col("awakz_string")),
    ("inskz", col("inskz_string")),
    ("vcekz", col("vcekz_string")),
    ("vstkz", col("vstkz_string")),
    ("vackz", col("vackz_string")),
    ("ekorg", col("ekorg_string")),
    ("clobk", col("clobk_string")),
    ("clmul", col("clmul_string")),
    ("clalt", col("clalt_string")),
    ("cview", col("cview_string")),
    ("knobj", col("knobj_string")),
    ("lgort", col("lgort_string")),
    ("kzkup", col("kzkup_string")),
    ("intrm", col("intrm_string")),
    ("tpekz", col("tpekz_string")),
    ("stvkn", col("stvkn_string")),
    ("dvdat", col("dvdat_string")),
    ("dvnam", col("dvnam_string")),
    ("dspst", col("dspst_string")),
    ("alpst", col("alpst_string")),
    ("alprf", col("alprf_string")),
    ("alpgr", col("alpgr_string")),
    ("kznfp", col("kznfp_string")),
    ("nfgrp", col("nfgrp_string")),
    ("nfeag", col("nfeag_string")),
    ("kndvb", col("kndvb_string")),
    ("kndbz", col("kndbz_string")),
    ("kstty", col("kstty_string")),
    ("kstnr", col("kstnr_string")),
    ("kstkn", col("kstkn_string")),
    ("kstpz", col("kstpz_string")),
    ("clszu", col("clszu_string")),
    ("kzclb", col("kzclb_string")),
    ("aehlp", col("aehlp_string")),
    ("prvbe", col("prvbe_string")),
    ("nlfzv", col("nlfzv_decimal_3_0")),
    ("nlfmv", col("nlfmv_string")),
    ("idpos", col("idpos_string")),
    ("idhis", col("idhis_string")),
    ("idvar", col("idvar_string")),
    ("alekz", col("alekz_string")),
    ("itmid", col("itmid_string")),
    ("guid", col("guid_string")),
    ("itsob", col("itsob_string")),
    ("rfpnt", col("rfpnt_string")),
    ("guidx", hex(col("guidx_binary"))),
    ("sgt_cmkz", col("sgt_cmkz_string")),
    ("sgt_catv", col("sgt_catv_string")),
    ("valid_to", col("valid_to_string")),
    ("valid_to_rkey", col("valid_to_rkey_string")),
    ("ecn_to", col("ecn_to_string")),
    ("ecn_to_rkey", col("ecn_to_rkey_string")),
    ("ablad", col("ablad_string")),
    ("wempf", col("wempf_string")),
    ("cufactor", col("cufactor_string")),
    ("_sapmp_met_lrch", col("_sapmp_met_lrch_string")),
    ("_sapmp_max_fertl", col("_sapmp_max_fertl_decimal_13_3")),
    ("_sapmp_fix_as_j", col("_sapmp_fix_as_j_decimal_13_3")),
    ("_sapmp_fix_as_e", col("_sapmp_fix_as_e_decimal_13_3")),
    ("_sapmp_fix_as_l", col("_sapmp_fix_as_l_decimal_13_3")),
    ("_sapmp_abl_zahl", col("_sapmp_abl_zahl_string")),
    ("_sapmp_rund_fakt", col("_sapmp_rund_fakt_decimal_13_3")),
    ("fsh_vmkz", col("fsh_vmkz_string")),
    ("fsh_pgqr", col("fsh_pgqr_string")),
    ("fsh_pgqrrf", col("fsh_pgqrrf_string")),
    ("fsh_critical_comp", col("fsh_critical_comp_string")),
    ("fsh_critical_level", col("fsh_critical_level_decimal_2_0")),
    ("funcid", col("funcid_string"))
  )
}
