// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_p69

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{Joined, PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_p69.{mara => sr_raw_mara}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, hex, lit, struct}

case class SrMara_Part1(
    @PK matnr: String,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    ersda: String,
    ernam: String,
    laeda: String,
    aenam: String,
    vpsta: String,
    pstat: String,
    lvorm: String,
    mtart: String,
    mbrsh: String,
    matkl: String,
    bismt: String,
    meins: String,
    bstme: String,
    zeinr: String,
    zeiar: String,
    zeivr: String,
    zeifo: String,
    aeszn: String,
    blatt: String,
    blanz: String,
    ferth: String,
    formt: String,
    groes: String,
    wrkst: String,
    normt: String,
    labor: String,
    ekwsl: String,
    @Decimal(13, 3) brgew: java.math.BigDecimal,
    @Decimal(13, 3) ntgew: java.math.BigDecimal,
    gewei: String,
    @Decimal(13, 3) volum: java.math.BigDecimal,
    voleh: String,
    behvo: String,
    raube: String,
    tempb: String,
    disst: String,
    tragr: String,
    stoff: String,
    spart: String,
    kunnr: String,
    eannr: String,
    @Decimal(13, 3) wesch: java.math.BigDecimal,
    bwvor: String,
    bwscl: String,
    saiso: String,
    etiar: String,
    etifo: String,
    entar: String,
    ean11: String,
    numtp: String,
    @Decimal(13, 3) laeng: java.math.BigDecimal,
    @Decimal(13, 3) breit: java.math.BigDecimal,
    @Decimal(13, 3) hoehe: java.math.BigDecimal,
    meabm: String,
    prdha: String,
    aeklk: String,
    cadkz: String,
    qmpur: String,
    @Decimal(13, 3) ergew: java.math.BigDecimal,
    ergei: String,
    @Decimal(13, 3) ervol: java.math.BigDecimal,
    ervoe: String,
    @Decimal(3, 1) gewto: java.math.BigDecimal,
    @Decimal(3, 1) volto: java.math.BigDecimal,
    vabme: String,
    kzrev: String,
    kzkfg: String,
    xchpf: String,
    vhart: String,
    @Decimal(3, 0) fuelg: java.math.BigDecimal,
    stfak: Int,
    magrv: String,
    begru: String,
    datab: String,
    liqdt: String,
    saisj: String,
    plgtp: String,
    mlgut: String,
    extwg: String,
    satnr: String,
    attyp: String,
    kzkup: String,
    kznfm: String,
    pmata: String,
    mstae: String,
    mstav: String,
    mstde: String,
    mstdv: String,
    taklv: String,
    rbnrm: String,
    @Decimal(4, 0) mhdrz: java.math.BigDecimal,
    @Decimal(4, 0) mhdhb: java.math.BigDecimal,
    @Decimal(3, 0) mhdlp: java.math.BigDecimal,
    inhme: String,
    @Decimal(13, 3) inhal: java.math.BigDecimal,
    @Decimal(5, 0) vpreh: java.math.BigDecimal,
    etiag: String,
    @Decimal(13, 3) inhbr: java.math.BigDecimal,
    cmeth: String,
    cuobf: String,
    kzumw: String,
    kosch: String,
    sprof: String,
    nrfhg: String,
    mfrpn: String,
    mfrnr: String,
    bmatn: String,
    mprof: String,
    kzwsm: String,
    saity: String,
    profl: String,
    ihivi: String,
    iloos: String,
    serlv: String,
    kzgvh: String,
    xgchp: String,
    kzeff: String,
    compl: String,
    iprkz: String,
    rdmhd: String,
    przus: String,
    mtpos_mara: String,
    bflme: String,
    matfi: String,
    cmrel: String,
    bbtyp: String,
    sled_bbd: String,
    gtin_variant: String,
    gennr: String,
    rmatp: String,
    gds_relevant: String,
    weora: String,
    hutyp_dflt: String,
    pilferable: String,
    whstc: String,
    whmatgr: String,
    hndlcode: String,
    hazmat: String,
    hutyp: String,
    tare_var: String,
    @Decimal(15, 3) maxc: java.math.BigDecimal,
    @Decimal(3, 1) maxc_tol: java.math.BigDecimal,
    @Decimal(15, 3) maxl: java.math.BigDecimal,
    @Decimal(15, 3) maxb: java.math.BigDecimal,
    @Decimal(15, 3) maxh: java.math.BigDecimal,
    maxdim_uom: String,
    herkl: String,
    mfrgr: String,
    @Decimal(3, 0) qqtime: java.math.BigDecimal,
    qqtimeuom: String,
    qgrp: String,
    serial: String,
    ps_smartform: String,
    logunit: String,
    cwqrel: String,
    cwqproc: String,
    cwqtolgr: String,
    adprof: String,
    ipmipproduct: String,
    allow_pmat_igno: String,
    medium: String,
    commodity: String,
    animal_origin: String,
    textile_comp_ind: String,
    sgt_csgr: String,
    sgt_covsa: String,
    sgt_stat: String,
    sgt_scope: String,
    sgt_rel: String,
    fsh_mg_at1: String,
    fsh_mg_at2: String,
    fsh_mg_at3: String,
    fsh_sealv: String,
    fsh_seaim: String,
    fsh_sc_mid: String,
    anp: String,
    psm_code: String,
    _bev1_luleinh: String,
    _bev1_luldegrp: String,
    _bev1_nestruccat: String,
    _dsd_sl_toltyp: String,
    _dsd_sv_cnt_grp: String,
    _dsd_vc_group: String,
    @Decimal(7, 2) _sapmp_kadu: java.math.BigDecimal,
    _sapmp_abmein: String,
    @Decimal(5, 2) _sapmp_kadp: java.math.BigDecimal,
    @Decimal(4, 0) _sapmp_brad: java.math.BigDecimal,
    @Decimal(7, 2) _sapmp_spbi: java.math.BigDecimal,
    @Decimal(7, 2) _sapmp_trad: java.math.BigDecimal,
    @Decimal(7, 2) _sapmp_kedu: java.math.BigDecimal,
    @Decimal(13, 3) _sapmp_sptr: java.math.BigDecimal,
    @Decimal(7, 2) _sapmp_fbdk: java.math.BigDecimal,
    @Decimal(7, 2) _sapmp_fbhk: java.math.BigDecimal,
    _sapmp_rili: String,
    _sapmp_fbak: String,
    _sapmp_aho: String,
    @Decimal(7, 2) _sapmp_mifrr: java.math.BigDecimal,
    _vso_r_tilt_ind: String,
    _vso_r_stack_ind: String,
    _vso_r_bot_ind: String,
    _vso_r_top_ind: String,
    _vso_r_stack_no: String,
    _vso_r_pal_ind: String,
    @Decimal(13, 3) _vso_r_pal_ovr_d: java.math.BigDecimal,
    @Decimal(13, 3) _vso_r_pal_ovr_w: java.math.BigDecimal,
    @Decimal(13, 3) _vso_r_pal_b_ht: java.math.BigDecimal,
    @Decimal(13, 3) _vso_r_pal_min_h: java.math.BigDecimal,
    @Decimal(13, 3) _vso_r_tol_b_ht: java.math.BigDecimal,
    _vso_r_no_p_gvh: String,
    _vso_r_quan_unit: String,
    _vso_r_kzgvh_ind: String,
    packcode: String,
    dg_pack_status: String,
    mcond: String,
    retdelc: String,
    loglev_reto: String,
    nsnid: String,
    ovlpn: String,
    adspc_spc: String,
    varid: String,
    msbookpartno: String,
    vtype: String,
    vchnr: String,
    evval: String,
    dvers: String,
    dpcbt: String,
    xgrdt: String,
    imatn: String,
    picnum: String,
    bstat: String,
    color_atinn: String,
    size1_atinn: String,
    size2_atinn: String,
    color: String,
    size1: String,
    size2: String,
    free_char: String,
    care_code: String,
    brand_id: String,
    fiber_code1: String
) extends Entity

case class SrMara_Part2(
    @PK matnr: String,
    @NotNull _mk_org: String,
    fiber_part1: String,
    fiber_code2: String,
    fiber_part2: String,
    fiber_code3: String,
    fiber_part3: String,
    fiber_code4: String,
    fiber_part4: String,
    fiber_code5: String,
    fiber_part5: String,
    fashgrd: String,
    zzgold_matnr: String,
    zzgold_maktx: String,
    zzgold_sysid: String,
    zzgold_mandt: String,
    zz_exlistno: String
) extends Entity

object mara
    extends TableSpec[Joined[SrMara_Part1, SrMara_Part2]]
    with ChangeKey[
      ct.dna.lakehouse.core.model.Entity.Joined[ct.dna.lakehouse.sr_raw.ct_gbl_p69.E_mara_part1, ct.dna.lakehouse.sr_raw.ct_gbl_p69.E_mara_part2]
    ] {

  override def sourceTableSpec
      : TableSpec[ct.dna.lakehouse.core.model.Entity.Joined[ct.dna.lakehouse.sr_raw.ct_gbl_p69.E_mara_part1, ct.dna.lakehouse.sr_raw.ct_gbl_p69.E_mara_part2]] =
    sr_raw_mara

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("matnr", coalesce(col("matnr_string"), lit(""))),
    ("ersda", col("ersda_string")),
    ("ernam", col("ernam_string")),
    ("laeda", col("laeda_string")),
    ("aenam", col("aenam_string")),
    ("vpsta", col("vpsta_string")),
    ("pstat", col("pstat_string")),
    ("lvorm", col("lvorm_string")),
    ("mtart", col("mtart_string")),
    ("mbrsh", col("mbrsh_string")),
    ("matkl", col("matkl_string")),
    ("bismt", col("bismt_string")),
    ("meins", col("meins_string")),
    ("bstme", col("bstme_string")),
    ("zeinr", col("zeinr_string")),
    ("zeiar", col("zeiar_string")),
    ("zeivr", col("zeivr_string")),
    ("zeifo", col("zeifo_string")),
    ("aeszn", col("aeszn_string")),
    ("blatt", col("blatt_string")),
    ("blanz", col("blanz_string")),
    ("ferth", col("ferth_string")),
    ("formt", col("formt_string")),
    ("groes", col("groes_string")),
    ("wrkst", col("wrkst_string")),
    ("normt", col("normt_string")),
    ("labor", col("labor_string")),
    ("ekwsl", col("ekwsl_string")),
    ("brgew", col("brgew_decimal_13_3")),
    ("ntgew", col("ntgew_decimal_13_3")),
    ("gewei", col("gewei_string")),
    ("volum", col("volum_decimal_13_3")),
    ("voleh", col("voleh_string")),
    ("behvo", col("behvo_string")),
    ("raube", col("raube_string")),
    ("tempb", col("tempb_string")),
    ("disst", col("disst_string")),
    ("tragr", col("tragr_string")),
    ("stoff", col("stoff_string")),
    ("spart", col("spart_string")),
    ("kunnr", col("kunnr_string")),
    ("eannr", col("eannr_string")),
    ("wesch", col("wesch_decimal_13_3")),
    ("bwvor", col("bwvor_string")),
    ("bwscl", col("bwscl_string")),
    ("saiso", col("saiso_string")),
    ("etiar", col("etiar_string")),
    ("etifo", col("etifo_string")),
    ("entar", col("entar_string")),
    ("ean11", col("ean11_string")),
    ("numtp", col("numtp_string")),
    ("laeng", col("laeng_decimal_13_3")),
    ("breit", col("breit_decimal_13_3")),
    ("hoehe", col("hoehe_decimal_13_3")),
    ("meabm", col("meabm_string")),
    ("prdha", col("prdha_string")),
    ("aeklk", col("aeklk_string")),
    ("cadkz", col("cadkz_string")),
    ("qmpur", col("qmpur_string")),
    ("ergew", col("ergew_decimal_13_3")),
    ("ergei", col("ergei_string")),
    ("ervol", col("ervol_decimal_13_3")),
    ("ervoe", col("ervoe_string")),
    ("gewto", col("gewto_decimal_3_1")),
    ("volto", col("volto_decimal_3_1")),
    ("vabme", col("vabme_string")),
    ("kzrev", col("kzrev_string")),
    ("kzkfg", col("kzkfg_string")),
    ("xchpf", col("xchpf_string")),
    ("vhart", col("vhart_string")),
    ("fuelg", col("fuelg_decimal_3_0")),
    ("stfak", coalesce(col("stfak_int"), lit(0))),
    ("magrv", col("magrv_string")),
    ("begru", col("begru_string")),
    ("datab", col("datab_string")),
    ("liqdt", col("liqdt_string")),
    ("saisj", col("saisj_string")),
    ("plgtp", col("plgtp_string")),
    ("mlgut", col("mlgut_string")),
    ("extwg", col("extwg_string")),
    ("satnr", col("satnr_string")),
    ("attyp", col("attyp_string")),
    ("kzkup", col("kzkup_string")),
    ("kznfm", col("kznfm_string")),
    ("pmata", col("pmata_string")),
    ("mstae", col("mstae_string")),
    ("mstav", col("mstav_string")),
    ("mstde", col("mstde_string")),
    ("mstdv", col("mstdv_string")),
    ("taklv", col("taklv_string")),
    ("rbnrm", col("rbnrm_string")),
    ("mhdrz", col("mhdrz_decimal_4_0")),
    ("mhdhb", col("mhdhb_decimal_4_0")),
    ("mhdlp", col("mhdlp_decimal_3_0")),
    ("inhme", col("inhme_string")),
    ("inhal", col("inhal_decimal_13_3")),
    ("vpreh", col("vpreh_decimal_5_0")),
    ("etiag", col("etiag_string")),
    ("inhbr", col("inhbr_decimal_13_3")),
    ("cmeth", col("cmeth_string")),
    ("cuobf", col("cuobf_string")),
    ("kzumw", col("kzumw_string")),
    ("kosch", col("kosch_string")),
    ("sprof", col("sprof_string")),
    ("nrfhg", col("nrfhg_string")),
    ("mfrpn", col("mfrpn_string")),
    ("mfrnr", col("mfrnr_string")),
    ("bmatn", col("bmatn_string")),
    ("mprof", col("mprof_string")),
    ("kzwsm", col("kzwsm_string")),
    ("saity", col("saity_string")),
    ("profl", col("profl_string")),
    ("ihivi", col("ihivi_string")),
    ("iloos", col("iloos_string")),
    ("serlv", col("serlv_string")),
    ("kzgvh", col("kzgvh_string")),
    ("xgchp", col("xgchp_string")),
    ("kzeff", col("kzeff_string")),
    ("compl", col("compl_string")),
    ("iprkz", col("iprkz_string")),
    ("rdmhd", col("rdmhd_string")),
    ("przus", col("przus_string")),
    ("mtpos_mara", col("mtpos_mara_string")),
    ("bflme", col("bflme_string")),
    ("matfi", col("matfi_string")),
    ("cmrel", col("cmrel_string")),
    ("bbtyp", col("bbtyp_string")),
    ("sled_bbd", col("sled_bbd_string")),
    ("gtin_variant", col("gtin_variant_string")),
    ("gennr", col("gennr_string")),
    ("rmatp", col("rmatp_string")),
    ("gds_relevant", col("gds_relevant_string")),
    ("weora", col("weora_string")),
    ("hutyp_dflt", col("hutyp_dflt_string")),
    ("pilferable", col("pilferable_string")),
    ("whstc", col("whstc_string")),
    ("whmatgr", col("whmatgr_string")),
    ("hndlcode", col("hndlcode_string")),
    ("hazmat", col("hazmat_string")),
    ("hutyp", col("hutyp_string")),
    ("tare_var", col("tare_var_string")),
    ("maxc", col("maxc_decimal_15_3")),
    ("maxc_tol", col("maxc_tol_decimal_3_1")),
    ("maxl", col("maxl_decimal_15_3")),
    ("maxb", col("maxb_decimal_15_3")),
    ("maxh", col("maxh_decimal_15_3")),
    ("maxdim_uom", col("maxdim_uom_string")),
    ("herkl", col("herkl_string")),
    ("mfrgr", col("mfrgr_string")),
    ("qqtime", col("qqtime_decimal_3_0")),
    ("qqtimeuom", col("qqtimeuom_string")),
    ("qgrp", col("qgrp_string")),
    ("serial", col("serial_string")),
    ("ps_smartform", col("ps_smartform_string")),
    ("logunit", col("logunit_string")),
    ("cwqrel", col("cwqrel_string")),
    ("cwqproc", col("cwqproc_string")),
    ("cwqtolgr", col("cwqtolgr_string")),
    ("adprof", col("adprof_string")),
    ("ipmipproduct", col("ipmipproduct_string")),
    ("allow_pmat_igno", col("allow_pmat_igno_string")),
    ("medium", col("medium_string")),
    ("commodity", col("commodity_string")),
    ("animal_origin", col("animal_origin_string")),
    ("textile_comp_ind", col("textile_comp_ind_string")),
    ("sgt_csgr", col("sgt_csgr_string")),
    ("sgt_covsa", col("sgt_covsa_string")),
    ("sgt_stat", col("sgt_stat_string")),
    ("sgt_scope", col("sgt_scope_string")),
    ("sgt_rel", col("sgt_rel_string")),
    ("fsh_mg_at1", col("fsh_mg_at1_string")),
    ("fsh_mg_at2", col("fsh_mg_at2_string")),
    ("fsh_mg_at3", col("fsh_mg_at3_string")),
    ("fsh_sealv", col("fsh_sealv_string")),
    ("fsh_seaim", col("fsh_seaim_string")),
    ("fsh_sc_mid", col("fsh_sc_mid_string")),
    ("anp", col("anp_string")),
    ("psm_code", col("psm_code_string")),
    ("_bev1_luleinh", col("_bev1_luleinh_string")),
    ("_bev1_luldegrp", col("_bev1_luldegrp_string")),
    ("_bev1_nestruccat", col("_bev1_nestruccat_string")),
    ("_dsd_sl_toltyp", col("_dsd_sl_toltyp_string")),
    ("_dsd_sv_cnt_grp", col("_dsd_sv_cnt_grp_string")),
    ("_dsd_vc_group", col("_dsd_vc_group_string")),
    ("_sapmp_kadu", col("_sapmp_kadu_decimal_7_2")),
    ("_sapmp_abmein", col("_sapmp_abmein_string")),
    ("_sapmp_kadp", col("_sapmp_kadp_decimal_5_2")),
    ("_sapmp_brad", col("_sapmp_brad_decimal_4_0")),
    ("_sapmp_spbi", col("_sapmp_spbi_decimal_7_2")),
    ("_sapmp_trad", col("_sapmp_trad_decimal_7_2")),
    ("_sapmp_kedu", col("_sapmp_kedu_decimal_7_2")),
    ("_sapmp_sptr", col("_sapmp_sptr_decimal_13_3")),
    ("_sapmp_fbdk", col("_sapmp_fbdk_decimal_7_2")),
    ("_sapmp_fbhk", col("_sapmp_fbhk_decimal_7_2")),
    ("_sapmp_rili", col("_sapmp_rili_string")),
    ("_sapmp_fbak", col("_sapmp_fbak_string")),
    ("_sapmp_aho", col("_sapmp_aho_string")),
    ("_sapmp_mifrr", col("_sapmp_mifrr_decimal_7_2")),
    ("_vso_r_tilt_ind", col("_vso_r_tilt_ind_string")),
    ("_vso_r_stack_ind", col("_vso_r_stack_ind_string")),
    ("_vso_r_bot_ind", col("_vso_r_bot_ind_string")),
    ("_vso_r_top_ind", col("_vso_r_top_ind_string")),
    ("_vso_r_stack_no", col("_vso_r_stack_no_string")),
    ("_vso_r_pal_ind", col("_vso_r_pal_ind_string")),
    ("_vso_r_pal_ovr_d", col("_vso_r_pal_ovr_d_decimal_13_3")),
    ("_vso_r_pal_ovr_w", col("_vso_r_pal_ovr_w_decimal_13_3")),
    ("_vso_r_pal_b_ht", col("_vso_r_pal_b_ht_decimal_13_3")),
    ("_vso_r_pal_min_h", col("_vso_r_pal_min_h_decimal_13_3")),
    ("_vso_r_tol_b_ht", col("_vso_r_tol_b_ht_decimal_13_3")),
    ("_vso_r_no_p_gvh", col("_vso_r_no_p_gvh_string")),
    ("_vso_r_quan_unit", col("_vso_r_quan_unit_string")),
    ("_vso_r_kzgvh_ind", col("_vso_r_kzgvh_ind_string")),
    ("packcode", col("packcode_string")),
    ("dg_pack_status", col("dg_pack_status_string")),
    ("mcond", col("mcond_string")),
    ("retdelc", col("retdelc_string")),
    ("loglev_reto", col("loglev_reto_string")),
    ("nsnid", col("nsnid_string")),
    ("ovlpn", col("ovlpn_string")),
    ("adspc_spc", col("adspc_spc_string")),
    ("varid", hex(col("varid_binary"))),
    ("msbookpartno", col("msbookpartno_string")),
    ("vtype", col("vtype_string")),
    ("vchnr", col("vchnr_string")),
    ("evval", col("evval_string")),
    ("dvers", col("dvers_string")),
    ("dpcbt", col("dpcbt_string")),
    ("xgrdt", col("xgrdt_string")),
    ("imatn", col("imatn_string")),
    ("picnum", col("picnum_string")),
    ("bstat", col("bstat_string")),
    ("color_atinn", col("color_atinn_string")),
    ("size1_atinn", col("size1_atinn_string")),
    ("size2_atinn", col("size2_atinn_string")),
    ("color", col("color_string")),
    ("size1", col("size1_string")),
    ("size2", col("size2_string")),
    ("free_char", col("free_char_string")),
    ("care_code", col("care_code_string")),
    ("brand_id", col("brand_id_string")),
    ("fiber_code1", col("fiber_code1_string")),
    ("_mk_org", col("_mk_org")),
    ("fiber_part1", col("fiber_part1_string")),
    ("fiber_code2", col("fiber_code2_string")),
    ("fiber_part2", col("fiber_part2_string")),
    ("fiber_code3", col("fiber_code3_string")),
    ("fiber_part3", col("fiber_part3_string")),
    ("fiber_code4", col("fiber_code4_string")),
    ("fiber_part4", col("fiber_part4_string")),
    ("fiber_code5", col("fiber_code5_string")),
    ("fiber_part5", col("fiber_part5_string")),
    ("fashgrd", col("fashgrd_string")),
    ("zzgold_matnr", col("zzgold_matnr_string")),
    ("zzgold_maktx", col("zzgold_maktx_string")),
    ("zzgold_sysid", col("zzgold_sysid_string")),
    ("zzgold_mandt", col("zzgold_mandt_string")),
    ("zz_exlistno", col("zz_exlistno_string"))
  )
}
