// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_p69

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_t001(
    @PK mandt: String,
    @PK bukrs: String,
    butxt: String,
    ort01: String,
    land1: String,
    waers: String,
    spras: String,
    ktopl: String,
    waabw: String,
    periv: String,
    kokfi: String,
    rcomp: String,
    adrnr: String,
    stceg: String,
    fikrs: String,
    xfmco: String,
    xfmcb: String,
    xfmca: String,
    txjcd: String,
    fmhrdate: String,
    buvar: String,
    fdbuk: String,
    xfdis: String,
    xvalv: String,
    xskfn: String,
    kkber: String,
    xmwsn: String,
    mregl: String,
    xgsbe: String,
    xgjrv: String,
    xkdft: String,
    xprod: String,
    xeink: String,
    xjvaa: String,
    xvvwa: String,
    xslta: String,
    xfdmm: String,
    xfdsd: String,
    xextb: String,
    ebukr: String,
    ktop2: String,
    umkrs: String,
    bukrs_glob: String,
    fstva: String,
    opvar: String,
    xcovr: String,
    txkrs: String,
    wfvar: String,
    xbbbf: String,
    xbbbe: String,
    xbbba: String,
    xbbko: String,
    xstdt: String,
    mwskv: String,
    mwska: String,
    impda: String,
    xnegp: String,
    xkkbi: String,
    wt_newwt: String,
    pp_pdate: String,
    infmt: String,
    fstvare: String,
    kopim: String,
    dkweg: String,
    offsacct: String,
    bapovar: String,
    xcos: String,
    xcession: String,
    xsplt: String,
    surccm: String,
    dtprov: String,
    dtamtc: String,
    dttaxc: String,
    dttdsp: String,
    dtaxr: String,
    xvatdate: String,
    pst_per_var: String,
    xbbsc: String,
    f_obsolete: String,
    fm_derive_acc: String,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String
) extends Entity

object t001
    extends TableSpec[E_t001](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[sr_raw.ct_gbl_p69.E_t001] {
  override def sourceTableSpec: TableSpec[sr_raw.ct_gbl_p69.E_t001] = sr_raw.ct_gbl_p69.t001
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("mandt", col("mandt_string")),
    ("bukrs", col("bukrs_string")),
    ("butxt", col("butxt_string")),
    ("ort01", col("ort01_string")),
    ("land1", col("land1_string")),
    ("waers", col("waers_string")),
    ("spras", col("spras_string")),
    ("ktopl", col("ktopl_string")),
    ("waabw", col("waabw_string")),
    ("periv", col("periv_string")),
    ("kokfi", col("kokfi_string")),
    ("rcomp", col("rcomp_string")),
    ("adrnr", col("adrnr_string")),
    ("stceg", col("stceg_string")),
    ("fikrs", col("fikrs_string")),
    ("xfmco", col("xfmco_string")),
    ("xfmcb", col("xfmcb_string")),
    ("xfmca", col("xfmca_string")),
    ("txjcd", col("txjcd_string")),
    ("fmhrdate", col("fmhrdate_string")),
    ("buvar", col("buvar_string")),
    ("fdbuk", col("fdbuk_string")),
    ("xfdis", col("xfdis_string")),
    ("xvalv", col("xvalv_string")),
    ("xskfn", col("xskfn_string")),
    ("kkber", col("kkber_string")),
    ("xmwsn", col("xmwsn_string")),
    ("mregl", col("mregl_string")),
    ("xgsbe", col("xgsbe_string")),
    ("xgjrv", col("xgjrv_string")),
    ("xkdft", col("xkdft_string")),
    ("xprod", col("xprod_string")),
    ("xeink", col("xeink_string")),
    ("xjvaa", col("xjvaa_string")),
    ("xvvwa", col("xvvwa_string")),
    ("xslta", col("xslta_string")),
    ("xfdmm", col("xfdmm_string")),
    ("xfdsd", col("xfdsd_string")),
    ("xextb", col("xextb_string")),
    ("ebukr", col("ebukr_string")),
    ("ktop2", col("ktop2_string")),
    ("umkrs", col("umkrs_string")),
    ("bukrs_glob", col("bukrs_glob_string")),
    ("fstva", col("fstva_string")),
    ("opvar", col("opvar_string")),
    ("xcovr", col("xcovr_string")),
    ("txkrs", col("txkrs_string")),
    ("wfvar", col("wfvar_string")),
    ("xbbbf", col("xbbbf_string")),
    ("xbbbe", col("xbbbe_string")),
    ("xbbba", col("xbbba_string")),
    ("xbbko", col("xbbko_string")),
    ("xstdt", col("xstdt_string")),
    ("mwskv", col("mwskv_string")),
    ("mwska", col("mwska_string")),
    ("impda", col("impda_string")),
    ("xnegp", col("xnegp_string")),
    ("xkkbi", col("xkkbi_string")),
    ("wt_newwt", col("wt_newwt_string")),
    ("pp_pdate", col("pp_pdate_string")),
    ("infmt", col("infmt_string")),
    ("fstvare", col("fstvare_string")),
    ("kopim", col("kopim_string")),
    ("dkweg", col("dkweg_string")),
    ("offsacct", col("offsacct_string")),
    ("bapovar", col("bapovar_string")),
    ("xcos", col("xcos_string")),
    ("xcession", col("xcession_string")),
    ("xsplt", col("xsplt_string")),
    ("surccm", col("surccm_string")),
    ("dtprov", col("dtprov_string")),
    ("dtamtc", col("dtamtc_string")),
    ("dttaxc", col("dttaxc_string")),
    ("dttdsp", col("dttdsp_string")),
    ("dtaxr", col("dtaxr_string")),
    ("xvatdate", col("xvatdate_string")),
    ("pst_per_var", col("pst_per_var_string")),
    ("xbbsc", col("xbbsc_string")),
    ("f_obsolete", col("f_obsolete_string")),
    ("fm_derive_acc", col("fm_derive_acc_string"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_t001(prefix: String) extends ColumnWithNameAccessor {
  val mandt: ColumnWithName = ColumnWithName(prefix + "mandt")
  val bukrs: ColumnWithName = ColumnWithName(prefix + "bukrs")
  val butxt: ColumnWithName = ColumnWithName(prefix + "butxt")
  val ort01: ColumnWithName = ColumnWithName(prefix + "ort01")
  val land1: ColumnWithName = ColumnWithName(prefix + "land1")
  val waers: ColumnWithName = ColumnWithName(prefix + "waers")
  val spras: ColumnWithName = ColumnWithName(prefix + "spras")
  val ktopl: ColumnWithName = ColumnWithName(prefix + "ktopl")
  val waabw: ColumnWithName = ColumnWithName(prefix + "waabw")
  val periv: ColumnWithName = ColumnWithName(prefix + "periv")
  val kokfi: ColumnWithName = ColumnWithName(prefix + "kokfi")
  val rcomp: ColumnWithName = ColumnWithName(prefix + "rcomp")
  val adrnr: ColumnWithName = ColumnWithName(prefix + "adrnr")
  val stceg: ColumnWithName = ColumnWithName(prefix + "stceg")
  val fikrs: ColumnWithName = ColumnWithName(prefix + "fikrs")
  val xfmco: ColumnWithName = ColumnWithName(prefix + "xfmco")
  val xfmcb: ColumnWithName = ColumnWithName(prefix + "xfmcb")
  val xfmca: ColumnWithName = ColumnWithName(prefix + "xfmca")
  val txjcd: ColumnWithName = ColumnWithName(prefix + "txjcd")
  val fmhrdate: ColumnWithName = ColumnWithName(prefix + "fmhrdate")
  val buvar: ColumnWithName = ColumnWithName(prefix + "buvar")
  val fdbuk: ColumnWithName = ColumnWithName(prefix + "fdbuk")
  val xfdis: ColumnWithName = ColumnWithName(prefix + "xfdis")
  val xvalv: ColumnWithName = ColumnWithName(prefix + "xvalv")
  val xskfn: ColumnWithName = ColumnWithName(prefix + "xskfn")
  val kkber: ColumnWithName = ColumnWithName(prefix + "kkber")
  val xmwsn: ColumnWithName = ColumnWithName(prefix + "xmwsn")
  val mregl: ColumnWithName = ColumnWithName(prefix + "mregl")
  val xgsbe: ColumnWithName = ColumnWithName(prefix + "xgsbe")
  val xgjrv: ColumnWithName = ColumnWithName(prefix + "xgjrv")
  val xkdft: ColumnWithName = ColumnWithName(prefix + "xkdft")
  val xprod: ColumnWithName = ColumnWithName(prefix + "xprod")
  val xeink: ColumnWithName = ColumnWithName(prefix + "xeink")
  val xjvaa: ColumnWithName = ColumnWithName(prefix + "xjvaa")
  val xvvwa: ColumnWithName = ColumnWithName(prefix + "xvvwa")
  val xslta: ColumnWithName = ColumnWithName(prefix + "xslta")
  val xfdmm: ColumnWithName = ColumnWithName(prefix + "xfdmm")
  val xfdsd: ColumnWithName = ColumnWithName(prefix + "xfdsd")
  val xextb: ColumnWithName = ColumnWithName(prefix + "xextb")
  val ebukr: ColumnWithName = ColumnWithName(prefix + "ebukr")
  val ktop2: ColumnWithName = ColumnWithName(prefix + "ktop2")
  val umkrs: ColumnWithName = ColumnWithName(prefix + "umkrs")
  val bukrs_glob: ColumnWithName = ColumnWithName(prefix + "bukrs_glob")
  val fstva: ColumnWithName = ColumnWithName(prefix + "fstva")
  val opvar: ColumnWithName = ColumnWithName(prefix + "opvar")
  val xcovr: ColumnWithName = ColumnWithName(prefix + "xcovr")
  val txkrs: ColumnWithName = ColumnWithName(prefix + "txkrs")
  val wfvar: ColumnWithName = ColumnWithName(prefix + "wfvar")
  val xbbbf: ColumnWithName = ColumnWithName(prefix + "xbbbf")
  val xbbbe: ColumnWithName = ColumnWithName(prefix + "xbbbe")
  val xbbba: ColumnWithName = ColumnWithName(prefix + "xbbba")
  val xbbko: ColumnWithName = ColumnWithName(prefix + "xbbko")
  val xstdt: ColumnWithName = ColumnWithName(prefix + "xstdt")
  val mwskv: ColumnWithName = ColumnWithName(prefix + "mwskv")
  val mwska: ColumnWithName = ColumnWithName(prefix + "mwska")
  val impda: ColumnWithName = ColumnWithName(prefix + "impda")
  val xnegp: ColumnWithName = ColumnWithName(prefix + "xnegp")
  val xkkbi: ColumnWithName = ColumnWithName(prefix + "xkkbi")
  val wt_newwt: ColumnWithName = ColumnWithName(prefix + "wt_newwt")
  val pp_pdate: ColumnWithName = ColumnWithName(prefix + "pp_pdate")
  val infmt: ColumnWithName = ColumnWithName(prefix + "infmt")
  val fstvare: ColumnWithName = ColumnWithName(prefix + "fstvare")
  val kopim: ColumnWithName = ColumnWithName(prefix + "kopim")
  val dkweg: ColumnWithName = ColumnWithName(prefix + "dkweg")
  val offsacct: ColumnWithName = ColumnWithName(prefix + "offsacct")
  val bapovar: ColumnWithName = ColumnWithName(prefix + "bapovar")
  val xcos: ColumnWithName = ColumnWithName(prefix + "xcos")
  val xcession: ColumnWithName = ColumnWithName(prefix + "xcession")
  val xsplt: ColumnWithName = ColumnWithName(prefix + "xsplt")
  val surccm: ColumnWithName = ColumnWithName(prefix + "surccm")
  val dtprov: ColumnWithName = ColumnWithName(prefix + "dtprov")
  val dtamtc: ColumnWithName = ColumnWithName(prefix + "dtamtc")
  val dttaxc: ColumnWithName = ColumnWithName(prefix + "dttaxc")
  val dttdsp: ColumnWithName = ColumnWithName(prefix + "dttdsp")
  val dtaxr: ColumnWithName = ColumnWithName(prefix + "dtaxr")
  val xvatdate: ColumnWithName = ColumnWithName(prefix + "xvatdate")
  val pst_per_var: ColumnWithName = ColumnWithName(prefix + "pst_per_var")
  val xbbsc: ColumnWithName = ColumnWithName(prefix + "xbbsc")
  val f_obsolete: ColumnWithName = ColumnWithName(prefix + "f_obsolete")
  val fm_derive_acc: ColumnWithName = ColumnWithName(prefix + "fm_derive_acc")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
}

object C_t001 extends C_t001("") {
  def as(alias: String): C_t001 = new C_t001(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
