// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_p69

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_p69.{t001w => sr_raw_t001w}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrT001w(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK werks: String,
    name1: String,
    bwkey: String,
    kunnr: String,
    lifnr: String,
    fabkl: String,
    name2: String,
    stras: String,
    pfach: String,
    pstlz: String,
    ort01: String,
    ekorg: String,
    vkorg: String,
    chazv: String,
    kkowk: String,
    kordb: String,
    bedpl: String,
    land1: String,
    regio: String,
    counc: String,
    cityc: String,
    adrnr: String,
    iwerk: String,
    txjcd: String,
    vtweg: String,
    spart: String,
    spras: String,
    wksop: String,
    awsls: String,
    chazv_old: String,
    vlfkz: String,
    bzirk: String,
    zone1: String,
    taxiw: String,
    bzqhl: String,
    @Decimal(3, 0) let01: java.math.BigDecimal,
    @Decimal(3, 0) let02: java.math.BigDecimal,
    @Decimal(3, 0) let03: java.math.BigDecimal,
    txnam_ma1: String,
    txnam_ma2: String,
    txnam_ma3: String,
    betol: String,
    j_1bbranch: String,
    vtbfi: String,
    fprfw: String,
    achvm: String,
    dvsart: String,
    nodetype: String,
    nschema: String,
    pkosa: String,
    misch: String,
    mgvupd: String,
    vstel: String,
    mgvlaupd: String,
    mgvlareval: String,
    sourcing: String,
    sgt_stat: String,
    fsh_mg_arun_req: String,
    fsh_seaim: String,
    fsh_bom_maintenance: String,
    oilival: String,
    oihvtype: String,
    oihcredipi: String,
    storetype: String,
    dep_store: String
) extends Entity

object t001w extends TableSpec[SrT001w] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_p69.E_t001w] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_p69.E_t001w] = sr_raw_t001w

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("werks", coalesce(col("werks_string"), lit(""))),
    ("name1", col("name1_string")),
    ("bwkey", col("bwkey_string")),
    ("kunnr", col("kunnr_string")),
    ("lifnr", col("lifnr_string")),
    ("fabkl", col("fabkl_string")),
    ("name2", col("name2_string")),
    ("stras", col("stras_string")),
    ("pfach", col("pfach_string")),
    ("pstlz", col("pstlz_string")),
    ("ort01", col("ort01_string")),
    ("ekorg", col("ekorg_string")),
    ("vkorg", col("vkorg_string")),
    ("chazv", col("chazv_string")),
    ("kkowk", col("kkowk_string")),
    ("kordb", col("kordb_string")),
    ("bedpl", col("bedpl_string")),
    ("land1", col("land1_string")),
    ("regio", col("regio_string")),
    ("counc", col("counc_string")),
    ("cityc", col("cityc_string")),
    ("adrnr", col("adrnr_string")),
    ("iwerk", col("iwerk_string")),
    ("txjcd", col("txjcd_string")),
    ("vtweg", col("vtweg_string")),
    ("spart", col("spart_string")),
    ("spras", col("spras_string")),
    ("wksop", col("wksop_string")),
    ("awsls", col("awsls_string")),
    ("chazv_old", col("chazv_old_string")),
    ("vlfkz", col("vlfkz_string")),
    ("bzirk", col("bzirk_string")),
    ("zone1", col("zone1_string")),
    ("taxiw", col("taxiw_string")),
    ("bzqhl", col("bzqhl_string")),
    ("let01", col("let01_decimal_3_0")),
    ("let02", col("let02_decimal_3_0")),
    ("let03", col("let03_decimal_3_0")),
    ("txnam_ma1", col("txnam_ma1_string")),
    ("txnam_ma2", col("txnam_ma2_string")),
    ("txnam_ma3", col("txnam_ma3_string")),
    ("betol", col("betol_string")),
    ("j_1bbranch", col("j_1bbranch_string")),
    ("vtbfi", col("vtbfi_string")),
    ("fprfw", col("fprfw_string")),
    ("achvm", col("achvm_string")),
    ("dvsart", col("dvsart_string")),
    ("nodetype", col("nodetype_string")),
    ("nschema", col("nschema_string")),
    ("pkosa", col("pkosa_string")),
    ("misch", col("misch_string")),
    ("mgvupd", col("mgvupd_string")),
    ("vstel", col("vstel_string")),
    ("mgvlaupd", col("mgvlaupd_string")),
    ("mgvlareval", col("mgvlareval_string")),
    ("sourcing", col("sourcing_string")),
    ("sgt_stat", col("sgt_stat_string")),
    ("fsh_mg_arun_req", col("fsh_mg_arun_req_string")),
    ("fsh_seaim", col("fsh_seaim_string")),
    ("fsh_bom_maintenance", col("fsh_bom_maintenance_string")),
    ("oilival", col("oilival_string")),
    ("oihvtype", col("oihvtype_string")),
    ("oihcredipi", col("oihcredipi_string")),
    ("storetype", col("storetype_string")),
    ("dep_store", col("dep_store_string"))
  )
}
