// This file is auto-generated. Do not edit manually.
package ct.dna.lakehouse.sr.ct_gbl_p61

import ct.dna.lakehouse.core.framework.origin.ChangeKey
import ct.dna.lakehouse.core.model.Entity.{PK, NotNull, Decimal}
import ct.dna.lakehouse.core.model.{Entity, TableSpec}
import ct.dna.lakehouse.sr_raw.ct_gbl_p61.{mvke => sr_raw_mvke}
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.{coalesce, col, lit, struct}

case class SrMvke(
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt: String,
    @PK matnr: String,
    @PK vkorg: String,
    @PK vtweg: String,
    lvorm: String,
    versg: String,
    bonus: String,
    provg: String,
    sktof: String,
    vmsta: String,
    vmstd: String,
    @Decimal(13, 3) aumng: java.math.BigDecimal,
    @Decimal(13, 3) lfmng: java.math.BigDecimal,
    @Decimal(13, 3) efmng: java.math.BigDecimal,
    @Decimal(13, 3) scmng: java.math.BigDecimal,
    schme: String,
    vrkme: String,
    mtpos: String,
    dwerk: String,
    prodh: String,
    pmatn: String,
    kondm: String,
    ktgrm: String,
    mvgr1: String,
    mvgr2: String,
    mvgr3: String,
    mvgr4: String,
    mvgr5: String,
    sstuf: String,
    pflks: String,
    lstfl: String,
    lstvz: String,
    lstak: String,
    ldvfl: String,
    ldbfl: String,
    ldvzl: String,
    ldbzl: String,
    vdvfl: String,
    vdbfl: String,
    vdvzl: String,
    vdbzl: String,
    prat1: String,
    prat2: String,
    prat3: String,
    prat4: String,
    prat5: String,
    prat6: String,
    prat7: String,
    prat8: String,
    prat9: String,
    prata: String,
    rdprf: String,
    megru: String,
    @Decimal(13, 3) lfmax: java.math.BigDecimal,
    rjart: String,
    pbind: String,
    vavme: String,
    matkc: String,
    pvmso: String,
    _bev1_emlgrp: String,
    _bev1_emdrckspl: String,
    _bev1_rpbezme: String,
    _bev1_rpsns: String,
    _bev1_rpsfa: String,
    _bev1_rpski: String,
    _bev1_rpsco: String,
    _bev1_rpsso: String,
    nf_flag: String,
    plgtp: String
) extends Entity

object mvke extends TableSpec[SrMvke] with ChangeKey[ct.dna.lakehouse.sr_raw.ct_gbl_p61.E_mvke] {

  override def sourceTableSpec: TableSpec[ct.dna.lakehouse.sr_raw.ct_gbl_p61.E_mvke] = sr_raw_mvke

  def sequenceBy: Column = struct(col("_mk_created_at"), col("_lh_id_in_message"))

  lazy val preApplyMapping: Seq[(String, Column)] = Seq(
    ("_mk_org", col("_mk_org")),
    ("_mk_site", col("_mk_site")),
    ("_mk_system", col("_mk_system")),
    ("_mk_instance", col("_mk_instance")),
    ("_mk_partition", col("_mk_partition")),
    ("_mk_file", col("_mk_file")),
    ("_mk_container", col("_mk_container")),
    ("_mk_account", col("_mk_account")),
    ("_mk_created_at", col("_mk_created_at")),
    ("_lh_id_in_message", col("_lh_id_in_message")),
    ("_lh_ingest_warning", col("_lh_ingest_warning")),
    ("mandt", col("mandt_string")),
    ("matnr", coalesce(col("matnr_string"), lit(""))),
    ("vkorg", coalesce(col("vkorg_string"), lit(""))),
    ("vtweg", coalesce(col("vtweg_string"), lit(""))),
    ("lvorm", col("lvorm_string")),
    ("versg", col("versg_string")),
    ("bonus", col("bonus_string")),
    ("provg", col("provg_string")),
    ("sktof", col("sktof_string")),
    ("vmsta", col("vmsta_string")),
    ("vmstd", col("vmstd_string")),
    ("aumng", col("aumng_decimal_13_3")),
    ("lfmng", col("lfmng_decimal_13_3")),
    ("efmng", col("efmng_decimal_13_3")),
    ("scmng", col("scmng_decimal_13_3")),
    ("schme", col("schme_string")),
    ("vrkme", col("vrkme_string")),
    ("mtpos", col("mtpos_string")),
    ("dwerk", col("dwerk_string")),
    ("prodh", col("prodh_string")),
    ("pmatn", col("pmatn_string")),
    ("kondm", col("kondm_string")),
    ("ktgrm", col("ktgrm_string")),
    ("mvgr1", col("mvgr1_string")),
    ("mvgr2", col("mvgr2_string")),
    ("mvgr3", col("mvgr3_string")),
    ("mvgr4", col("mvgr4_string")),
    ("mvgr5", col("mvgr5_string")),
    ("sstuf", col("sstuf_string")),
    ("pflks", col("pflks_string")),
    ("lstfl", col("lstfl_string")),
    ("lstvz", col("lstvz_string")),
    ("lstak", col("lstak_string")),
    ("ldvfl", col("ldvfl_string")),
    ("ldbfl", col("ldbfl_string")),
    ("ldvzl", col("ldvzl_string")),
    ("ldbzl", col("ldbzl_string")),
    ("vdvfl", col("vdvfl_string")),
    ("vdbfl", col("vdbfl_string")),
    ("vdvzl", col("vdvzl_string")),
    ("vdbzl", col("vdbzl_string")),
    ("prat1", col("prat1_string")),
    ("prat2", col("prat2_string")),
    ("prat3", col("prat3_string")),
    ("prat4", col("prat4_string")),
    ("prat5", col("prat5_string")),
    ("prat6", col("prat6_string")),
    ("prat7", col("prat7_string")),
    ("prat8", col("prat8_string")),
    ("prat9", col("prat9_string")),
    ("prata", col("prata_string")),
    ("rdprf", col("rdprf_string")),
    ("megru", col("megru_string")),
    ("lfmax", col("lfmax_decimal_13_3")),
    ("rjart", col("rjart_string")),
    ("pbind", col("pbind_string")),
    ("vavme", col("vavme_string")),
    ("matkc", col("matkc_string")),
    ("pvmso", col("pvmso_string")),
    ("_bev1_emlgrp", col("_bev1_emlgrp_string")),
    ("_bev1_emdrckspl", col("_bev1_emdrckspl_string")),
    ("_bev1_rpbezme", col("_bev1_rpbezme_string")),
    ("_bev1_rpsns", col("_bev1_rpsns_string")),
    ("_bev1_rpsfa", col("_bev1_rpsfa_string")),
    ("_bev1_rpski", col("_bev1_rpski_string")),
    ("_bev1_rpsco", col("_bev1_rpsco_string")),
    ("_bev1_rpsso", col("_bev1_rpsso_string")),
    ("nf_flag", col("nf_flag_string")),
    ("plgtp", col("plgtp_string"))
  )
}
