package ct.dna.lakehouse.sr_raw.ct_gbl_psp
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class ekko_E(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  abgru_string: String,
  bukrs_string: String,
  zterm_string: String,
  procstat_string: String,
  fixpo_string: String,
  @Decimal(3, 0) zbd1t_decimal_3_0: BigDecimal,
  grwcu_string: String,
  logsy_string: String,
  distributiontype_string: String,
  iseopblocked_string: String,
  description_string: String,
  bsart_string: String,
  inco3_l_string: String,
  fsh_os_stg_change_string: String,
  bnddt_string: String,
  process_indicator_string: String,
  ernam_string: String,
  msr_id_string: String,
  verkf_string: String,
  statu_string: String,
  cont_string: String,
  shipcond_string: String,
  inco2_key_binary: Array[Byte],
  pare_dat_string: String,
  dummy_ekko_incl_eew_ps_string: String,
  eq_eindt_string: String,
  outr_string: String,
  spras_string: String,
  inco4_key_binary: Array[Byte],
  intra_excl_string: String,
  lphis_string: String,
  _dmbe_evgidcancel_string: String,
  ltsnr_allow_string: String,
  kdatb_string: String,
  has_catalog_relevant_items_string: String,
  @Decimal(3, 0) zbd2t_decimal_3_0: BigDecimal,
  kornr_string: String,
  fsh_vas_last_item_string: String,
  key_id_string: String,
  bwbdt_string: String,
  ebeln_string: String,
  parent_id_string: String,
  desp_cargo_string: String,
  threshold_exists_string: String,
  reswk_string: String,
  _dmbe_dealnumber_string: String,
  contract_allow_string: String,
  @Decimal(17, 2) otb_spec_value_decimal_17_2: BigDecimal,
  gwldt_string: String,
  pincr_string: String,
  _dmbe_evgidrenewal_string: String,
  frgsx_string: String,
  @Decimal(11, 2) dpamt_decimal_11_2: BigDecimal,
  addnr_string: String,
  frgzu_string: String,
  zapcgk_string: String,
  llief_string: String,
  angdt_string: String,
  conc_string: String,
  con_distr_lev_string: String,
  exnum_string: String,
  eindt_allow_string: String,
  con_otb_req_string: String,
  fsh_transaction_string: String,
  source_logsys_string: String,
  check_type_string: String,
  unsez_string: String,
  @Decimal(5, 3) zbd1p_decimal_5_3: BigDecimal,
  postat_string: String,
  stceg_string: String,
  stceg_l_string: String,
  reason_code_string: String,
  otb_curr_string: String,
  bstyp_string: String,
  weakt_string: String,
  zbas_date_string: String,
  pare_string: String,
  proce_string: String,
  isaged_string: String,
  grouping_id_string: String,
  otb_level_string: String,
  pohf_type_string: String,
  pfm_contract_string: String,
  kalsm_string: String,
  total_status_pcs_string: String,
  comp_string: String,
  autlf_string: String,
  force_id_string: String,
  bsakz_string: String,
  fixpo_allow_string: String,
  rettp_string: String,
  externalsystem_string: String,
  mandt_string: String,
  hashcal_bdat_string: String,
  total_status_sds_string: String,
  followon_doc_cat_string: String,
  eq_werks_string: String,
  konnr_string: String,
  followon_doc_type_string: String,
  memorytype_string: String,
  stafo_string: String,
  fsh_snst_status_string: String,
  @Decimal(9, 5) wkurs_decimal_9_5: BigDecimal,
  ekgrp_string: String,
  tms_ref_uuid_string: String,
  vzskz_string: String,
  inco1_string: String,
  bedat_string: String,
  telf1_string: String,
  inco3_key_binary: Array[Byte],
  @Decimal(3, 0) zbd3t_decimal_3_0: BigDecimal,
  handoverloc_string: String,
  hierarchy_exists_string: String,
  dpdat_string: String,
  hashcal_exists_string: String,
  zlimit_dat_string: String,
  adrnr_string: String,
  @Decimal(21, 7) ext_rev_tmstmp_decimal_21_7: BigDecimal,
  submi_string: String,
  inco2_l_string: String,
  ihran_string: String,
  desp_dat_string: String,
  angnr_string: String,
  vsart_string: String,
  ekorg_string: String,
  _dmbe_paymentdeemed_string: String,
  frgke_string: String,
  apcgk_extend_string: String,
  lblif_string: String,
  aurel_allow_string: String,
  upinc_string: String,
  spr_rsn_profile_string: String,
  ausnr_string: String,
  lifre_string: String,
  scmproc_string: String,
  ekgrp_allow_string: String,
  dptyp_string: String,
  @Decimal(5, 3) zbd2p_decimal_5_3: BigDecimal,
  @Decimal(6, 3) z_dev_decimal_6_3: BigDecimal,
  known_index_string: String,
  delper_allow_string: String,
  frgrl_string: String,
  con_prebook_lev_string: String,
  intra_rel_string: String,
  @Decimal(15, 2) ktwrt_decimal_15_2: BigDecimal,
  zindanx_string: String,
  zstart_dat_string: String,
  pstyp_allow_string: String,
  fsh_item_group_string: String,
  inco2_string: String,
  loekz_string: String,
  stako_string: String,
  @Decimal(21, 7) lastchangedatetime_decimal_21_7: BigDecimal,
  otb_status_string: String,
  lponr_string: String,
  cr_stat_string: String,
  absgr_string: String,
  aedat_string: String,
  externalreferenceid_string: String,
  memory_string: String,
  numerator_string: String,
  legal_contract_string: String,
  otb_cond_type_string: String,
  @Decimal(5, 2) retpc_decimal_5_2: BigDecimal,
  hashcal_string: String,
  lifnr_string: String,
  @Decimal(17, 2) otb_value_decimal_17_2: BigDecimal,
  total_status_pma_string: String,
  negative_string: String,
  frggr_string: String,
  revno_string: String,
  otb_reason_string: String,
  knumv_string: String,
  force_cnt_string: String,
  reloc_id_string: String,
  release_date_string: String,
  lands_string: String,
  kunnr_string: String,
  ihrez_string: String,
  kufix_string: String,
  active_id_string: String,
  key_id_allow_string: String,
  @Decimal(5, 2) dppct_decimal_5_2: BigDecimal,
  desp_string: String,
  @Decimal(17, 2) otb_res_value_decimal_17_2: BigDecimal,
  budg_type_string: String,
  zadattyp_string: String,
  total_status_dg_string: String,
  kdate_string: String,
  waers_string: String,
  werks_allow_string: String,
  reloc_seq_id_string: String,
  @Decimal(15, 2) rlwrt_decimal_15_2: BigDecimal,
  pare_cargo_string: String,
  qtn_erlst_submsn_date_string: String,
  incov_string: String
) extends Entity

object ekko extends TableSpec[ekko_E](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
