package ct.dna.lakehouse.sr_raw.ct_gbl_psp
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class ekpo_E_part1(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  techs_string: String,
  fsh_season_string: String,
  matnr_string: String,
  ko_prctr_string: String,
  _dmbe_item_type_string: String,
  retpo_string: String,
  bukrs_string: String,
  fkber_string: String,
  reslo_string: String,
  fsh_season_year_string: String,
  pol_id_string: String,
  lblkz_string: String,
  excpe_string: String,
  @Decimal(13, 2) gnetwr_decimal_13_2: BigDecimal,
  inco3_l_string: String,
  sgt_scat_string: String,
  @Decimal(13, 3) ktmng_decimal_13_3: BigDecimal,
  prio_req_string: String,
  ehtyp_string: String,
  consnum_string: String,
  txdat_string: String,
  txs_business_transaction_string: String,
  _dmbe_componentfor_string: String,
  statu_string: String,
  kblpos_comp_string: String,
  @Decimal(15, 3) mfzhi_decimal_15_3: BigDecimal,
  fsh_atp_date_string: String,
  belnr_string: String,
  @Decimal(3, 0) mahn1_decimal_3_0: BigDecimal,
  @Decimal(13, 2) kzwi6_decimal_13_2: BigDecimal,
  fsh_vas_rel_string: String,
  @Decimal(15, 3) ffzhi_decimal_15_3: BigDecimal,
  disub_pspnr_string: String,
  abueb_string: String,
  inco2_key_binary: Array[Byte],
  cons_order_string: String,
  borgr_miss_string: String,
  @Decimal(13, 2) kzwi5_decimal_13_2: BigDecimal,
  etdrk_string: String,
  inco4_key_binary: Array[Byte],
  idnlf_string: String,
  spe_cq_ctrltype_string: String,
  kblnr_string: String,
  usequ_string: String,
  status_pma_string: String,
  uebpo_string: String,
  repos_string: String,
  @Decimal(5, 0) bpumz_decimal_5_0: BigDecimal,
  berid_string: String,
  attyp_string: String,
  _bev1_nedepfree_string: String,
  knttp_string: String,
  stapo_string: String,
  delivery_address_type_string: String,
  stpac_string: String,
  j_1bnbm_string: String,
  srv_bas_com_string: String,
  lifexpos_string: String,
  @Decimal(13, 2) navnw_decimal_13_2: BigDecimal,
  renegotiation_status_string: String,
  disub_kunnr_string: String,
  dummy_ekpo_incl_eew_ps_string: String,
  sgt_rcat_string: String,
  source_key_string: String,
  advcode_string: String,
  bwtty_string: String,
  bsark_string: String,
  _bev1_negen_item_string: String,
  rfm_ref_item_string: String,
  itcons_string: String,
  j_1bownpro_string: String,
  xconditions_string: String,
  emlif_string: String,
  anfnr_string: String,
  insnc_string: String,
  fsh_vas_prnt_id_string: String,
  lewed_string: String,
  _sapmp_gpose_string: String,
  packno_string: String,
  tzonrc_string: String,
  exsnr_string: String,
  @Decimal(5, 0) umren_decimal_5_0: BigDecimal,
  @Decimal(13, 3) ntgew_decimal_13_3: BigDecimal,
  txz01_string: String,
  @Decimal(5, 0) peinh_decimal_5_0: BigDecimal,
  kzkfg_string: String,
  @Decimal(3, 0) etfz2_decimal_3_0: BigDecimal,
  ko_pargb_string: String,
  schpr_string: String,
  umsok_string: String,
  ebeln_string: String,
  @Decimal(13, 2) grwrt_decimal_13_2: BigDecimal,
  adacn_string: String,
  ebonf_string: String,
  zapcgk_string: String,
  arsps_string: String,
  lebre_string: String,
  status_sds_string: String,
  saiso_string: String,
  @Decimal(11, 2) dpamt_decimal_11_2: BigDecimal,
  audat_string: String,
  _dmbe_invoiceuom_string: String,
  pstyp_string: String,
  tms_des_loc_key_binary: Array[Byte],
  requestforquotation_string: String,
  rfm_ref_action_string: String,
  cigit_string: String,
  emnfr_string: String,
  tax_country_string: String,
  fsh_transaction_string: String,
  adpri_string: String,
  abelp_string: String,
  anzsn_int: BoxedInt,
  rdprf_string: String,
  @Decimal(13, 2) kzwi1_decimal_13_2: BigDecimal,
  ccomp_string: String,
  fsh_item_string: String,
  addns_string: String,
  gewei_string: String,
  _dataaging_string: String,
  afpnr_string: String,
  ebon3_string: String,
  assignment_priority_string: String,
  abdat_string: String,
  evers_string: String,
  @Decimal(13, 2) effwr_decimal_13_2: BigDecimal,
  creationdate_string: String,
  disub_sobkz_string: String,
  txs_usage_purpose_string: String,
  producttype_string: String,
  kblpos_cab_string: String,
  banfn_string: String,
  _dmbe_optionof_string: String,
  trmrisk_relevant_string: String,
  reason_code_string: String,
  rfm_ref_slitem_string: String,
  lifex_string: String,
  xersy_string: String,
  zbas_date_string: String,
  sf_txjcd_string: String,
  @Decimal(3, 0) plifz_decimal_3_0: BigDecimal,
  j_1aidatep_string: String,
  weunb_string: String,
  _dmbe_deal_posted_string: String,
  iprkz_string: String,
  rfm_scc_indicator_string: String,
  bstyp_string: String,
  eglkz_string: String,
  kzvbr_string: String,
  empst_string: String,
  wabwe_string: String,
  _dmbe_posteddate_string: String,
  lprio_string: String,
  afnam_string: String,
  ext_rfx_item_string: String,
  disub_vbeln_string: String,
  @Decimal(13, 2) kzwi3_decimal_13_2: BigDecimal,
  geber_string: String,
  source_id_string: String,
  j_1aindxp_string: String,
  spe_crm_ref_item_string: String,
  apoms_string: String,
  lgort_string: String,
  angpn_string: String,
  txdat_from_string: String,
  kolif_string: String,
  cmpl_dlv_itm_string: String,
  tms_src_loc_key_binary: Array[Byte],
  diff_invoice_string: String,
  mfrpn_string: String,
  erekz_string: String,
  @Decimal(13, 2) brtwr_decimal_13_2: BigDecimal,
  abskz_string: String,
  ktpnr_string: String,
  ebelp_string: String,
  @Decimal(13, 3) cnfm_qty_decimal_13_3: BigDecimal,
  werks_string: String,
  aurel_string: String,
  @Decimal(13, 3) anzpu_decimal_13_3: BigDecimal,
  kzabs_string: String,
  _bev1_nestruccat_string: String,
  isvco_string: String,
  cuobj_string: String,
  extmaterialforpurg_string: String,
  nlabd_string: String,
  webre_string: String,
  upvor_string: String,
  fsh_psm_pfm_split_string: String,
  tc_aut_det_string: String,
  sktof_string: String,
  agmem_string: String,
  mandt_string: String,
  enh_numc1_string: String,
  hashcal_bdat_string: String,
  creationtime_string: String,
  tax_subject_st_string: String,
  spinf_string: String,
  @Decimal(5, 0) umrez_decimal_5_0: BigDecimal,
  j_1bmatuse_string: String,
  ebon2_string: String,
  @Decimal(3, 0) etfz1_decimal_3_0: BigDecimal,
  disub_owner_string: String,
  rfm_diversion_string: String,
  wbs_element_string: String,
  fplnr_string: String,
  konnr_string: String,
  xoblr_string: String,
  uptyp_string: String,
  wepos_string: String,
  stafo_string: String,
  loadingpoint_string: String,
  _dmbe_optionalityfor_string: String,
  bonus_string: String,
  serru_string: String,
  @Decimal(11, 2) netpr_decimal_11_2: BigDecimal,
  saisj_string: String,
  put_back_string: String,
  stawn_string: String,
  _dmbe_accounting_type_string: String,
  elikz_string: String,
  txjcd_string: String,
  fsh_grid_cond_rec_string: String,
  _dmbe_fas_code_string: String,
  mlmaa_string: String,
  tms_ref_uuid_string: String,
  inco1_string: String,
  vcm_chain_category_string: String,
  handoverloc_string: String,
  inco3_key_binary: Array[Byte],
  voleh_string: String,
  novet_string: String,
  sobkz_string: String,
  notkz_string: String,
  satnr_string: String,
  bsgru_string: String,
  hashcal_exists_string: String,
  bnfpo_string: String,
  zlimit_dat_string: String,
  adrnr_string: String,
  wrf_charstc3_string: String,
  kblpos_string: String,
  spe_ewm_dtc_string: String
) extends Entity


@LakehouseEntity
case class ekpo_E_part2(
  @PK _mk_org: String,
  blk_reason_txt_string: String,
  @Decimal(13, 3) menge_decimal_13_3: BigDecimal,
  nfabd_string: String,
  dpdat_string: String,
  kzfme_string: String,
  fsh_theme_string: String,
  spe_crm_fkrel_string: String,
  meins_string: String,
  blk_reason_id_string: String,
  lfret_string: String,
  inco2_l_string: String,
  iuid_relevant_string: String,
  agdat_string: String,
  @Decimal(13, 2) netwr_decimal_13_2: BigDecimal,
  ko_pprctr_string: String,
  lgbzo_string: String,
  gr_by_ses_string: String,
  prdat_string: String,
  kblnr_comp_string: String,
  manual_tc_reason_string: String,
  vsart_string: String,
  fsh_pqr_uepos_string: String,
  status_dg_string: String,
  rfm_ref_doc_string: String,
  angnr_string: String,
  fixmg_string: String,
  sakto_string: String,
  dep_id_string: String,
  @Decimal(13, 2) kzwi4_decimal_13_2: BigDecimal,
  apcgk_extend_string: String,
  sikgr_string: String,
  @Decimal(13, 2) kzwi2_decimal_13_2: BigDecimal,
  mwskz_string: String,
  arun_group_prio_string: String,
  j_1bindust_string: String,
  rfm_psst_rule_string: String,
  punei_string: String,
  ematn_string: String,
  @Decimal(3, 1) uebto_decimal_3_1: BigDecimal,
  ext_rfx_system_string: String,
  eildt_string: String,
  _dmbe_effectivedatefrom_string: String,
  mfrnr_string: String,
  anfps_string: String,
  mprof_string: String,
  spe_crm_so_string: String,
  budget_pd_string: String,
  zgtyp_string: String,
  requestforquotationitem_string: String,
  chg_srv_string: String,
  @Decimal(13, 3) abftz_decimal_13_3: BigDecimal,
  contract_for_limit_string: String,
  _dmbe_mixedproduct_string: String,
  addrnum_string: String,
  enh_date1_string: String,
  arsnr_string: String,
  ean11_string: String,
  @Decimal(5, 0) bpumn_decimal_5_0: BigDecimal,
  _dmbe_cimax2_string: String,
  dptyp_string: String,
  chg_fplnr_string: String,
  ps_psp_pnr_string: String,
  spe_cq_nocq_string: String,
  @Decimal(6, 3) z_dev_decimal_6_3: BigDecimal,
  fipos_string: String,
  known_index_string: String,
  ssqss_string: String,
  labnr_string: String,
  @Decimal(3, 0) mahn2_decimal_3_0: BigDecimal,
  ekkol_string: String,
  zstart_dat_string: String,
  aktnr_string: String,
  txs_material_usage_string: String,
  @Decimal(5, 2) enh_percent_decimal_5_2: BigDecimal,
  kztlf_string: String,
  mfrgr_string: String,
  prio_urg_string: String,
  bednr_string: String,
  fsh_collection_string: String,
  zindanx_string: String,
  @Decimal(15, 2) target_value_decimal_15_2: BigDecimal,
  fls_rsto_string: String,
  cupit_string: String,
  admoi_string: String,
  fsh_item_group_string: String,
  lgbzo_b_string: String,
  inco2_string: String,
  loekz_string: String,
  arun_order_prio_int: BoxedInt,
  insmk_string: String,
  aedat_string: String,
  abeln_string: String,
  prsdr_string: String,
  @Decimal(3, 0) mahnz_decimal_3_0: BigDecimal,
  @Decimal(13, 3) abmng_decimal_13_3: BigDecimal,
  @Decimal(4, 0) mhdrz_decimal_4_0: BigDecimal,
  is_catalog_relevant_string: String,
  ltsnr_string: String,
  externalreferenceid_string: String,
  nrfhg_string: String,
  @Decimal(15, 3) cqu_sar_decimal_15_3: BigDecimal,
  numerator_string: String,
  goods_count_correction_string: String,
  spe_chng_sys_string: String,
  srm_contract_id_string: String,
  spe_crm_ref_so_string: String,
  negative_string: String,
  @Decimal(5, 2) retpc_decimal_5_2: BigDecimal,
  mrpind_string: String,
  ref_item_string: String,
  hashcal_string: String,
  pfmtransdatafootprintuuid_binary: Array[Byte],
  drdat_string: String,
  refsite_string: String,
  _dmbe_effectivedateto_string: String,
  j_1bmatorg_string: String,
  revlv_string: String,
  _dmbe_scheduling_desk_string: String,
  status_pcs_string: String,
  druhr_string: String,
  ko_gsber_string: String,
  meprf_string: String,
  fiscal_incentive_id_string: String,
  weora_string: String,
  procmt_hub_source_system_string: String,
  spe_crm_so_item_string: String,
  vrtkz_string: String,
  exlin_string: String,
  @Decimal(13, 2) zwert_decimal_13_2: BigDecimal,
  pnstat_string: String,
  kunnr_string: String,
  adrn2_string: String,
  @Decimal(3, 0) mahn3_decimal_3_0: BigDecimal,
  bwtar_string: String,
  kzbws_string: String,
  mtart_string: String,
  ext_rfx_number_string: String,
  lmein_string: String,
  spe_abgru_string: String,
  _dmbe_optionalitykey_string: String,
  @Decimal(3, 0) webaz_decimal_3_0: BigDecimal,
  enh_date2_string: String,
  fiscal_incentive_string: String,
  @Decimal(13, 2) limit_amount_decimal_13_2: BigDecimal,
  sernp_string: String,
  @Decimal(13, 3) volum_decimal_13_3: BigDecimal,
  vorab_string: String,
  disub_posnr_string: String,
  bprme_string: String,
  @Decimal(13, 2) expected_value_decimal_13_2: BigDecimal,
  rfm_psst_group_string: String,
  spe_insmk_src_string: String,
  srm_contract_itm_string: String,
  @Decimal(5, 2) dppct_decimal_5_2: BigDecimal,
  fsh_ss_string: String,
  uebtk_string: String,
  infnr_string: String,
  matkl_string: String,
  price_change_in_ses_allowed_string: String,
  wrf_charstc1_string: String,
  kostl_string: String,
  fistl_string: String,
  zadattyp_string: String,
  status_string: String,
  kzstu_string: String,
  kanba_string: String,
  bstae_string: String,
  @Decimal(13, 2) bonba_decimal_13_2: BigDecimal,
  wrf_charstc2_string: String,
  grant_nbr_string: String,
  @Decimal(3, 1) untto_decimal_3_1: BigDecimal,
  @Decimal(13, 3) brgew_decimal_13_3: BigDecimal,
  fmfgus_key_string: String,
  uniqueid_string: String,
  mgoit_string: String,
  serviceperformer_string: String,
  twrkz_string: String,
  fabkz_string: String,
  drunr_string: String
) extends Entity

object ekpo extends TableSpec[Joined[ekpo_E_part1, ekpo_E_part2]](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
