package ct.dna.lakehouse.sr_raw.ct_gbl_psp
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class lfa1_E(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  ort02_string: String,
  dlgrp_string: String,
  j_1iexcive_string: String,
  au_payment_exempt_string: String,
  dtams_string: String,
  gbdat_string: String,
  telfx_string: String,
  kraus_string: String,
  j_1iexco_string: String,
  begru_string: String,
  brsch_string: String,
  sc_currency_string: String,
  exp_string: String,
  data_ctrlr9_string: String,
  xcpdk_string: String,
  dvalss_string: String,
  regss_string: String,
  ernam_string: String,
  pfach_string: String,
  data_ctrlr8_string: String,
  ven_class_string: String,
  icmstaxpay_string: String,
  sfrgr_string: String,
  term_li_string: String,
  name3_string: String,
  spras_string: String,
  fityp_string: String,
  sortl_string: String,
  data_ctrlr3_string: String,
  j_1iexrg_string: String,
  stgdl_string: String,
  j_1issist_string: String,
  borgr_datun_string: String,
  bahns_string: String,
  cvp_xblck_string: String,
  name1_string: String,
  stcd5_string: String,
  confs_string: String,
  telx1_string: String,
  addr2_country_string: String,
  stkzn_string: String,
  legalnat_string: String,
  qssysdat_string: String,
  stkza_string: String,
  duefl_string: String,
  entpub_string: String,
  telbx_string: String,
  stcd1_string: String,
  regio_string: String,
  crtn_string: String,
  alc_string: String,
  stkzu_string: String,
  stcd4_string: String,
  datlt_string: String,
  carrier_conf_string: String,
  gbort_string: String,
  j_1ilstno_string: String,
  partner_name_string: String,
  ppa_relevant_string: String,
  scheduling_type_string: String,
  transport_chain_string: String,
  stcd6_string: String,
  j_1ivencre_string: String,
  data_ctrlr6_string: String,
  psost_string: String,
  data_ctrlr4_string: String,
  emnfr_string: String,
  lnrza_string: String,
  land1_string: String,
  au_wholly_inp_taxed_string: String,
  stceg_string: String,
  vfnid_string: String,
  lfurl_string: String,
  ric_string: String,
  scacd_string: String,
  bbsnr_string: String,
  stcd2_string: String,
  crc_num_string: String,
  stenr_string: String,
  anred_string: String,
  addr2_house_num_string: String,
  fisku_string: String,
  updat_string: String,
  mcod2_string: String,
  nodel_string: String,
  au_payment_not_exceed_75_string: String,
  au_carrying_ent_string: String,
  escrit_string: String,
  werks_string: String,
  pson1_string: String,
  mcod3_string: String,
  j_sc_currency_string: String,
  j_1kftbus_string: String,
  decregpc_string: String,
  mandt_string: String,
  ktokk_string: String,
  addr2_city_string: String,
  j_1idedref_string: String,
  sperz_string: String,
  j_1kfrepre_string: String,
  frmcss_string: String,
  j_1i_customs_string: String,
  vbund_string: String,
  psohs_string: String,
  data_ctrlr7_string: String,
  crn_string: String,
  codcae_string: String,
  pson3_string: String,
  txjcd_string: String,
  plkal_string: String,
  rne_string: String,
  ipisp_string: String,
  telf1_string: String,
  name4_string: String,
  psofg_string: String,
  fiskn_string: String,
  xdcset_string: String,
  mcod1_string: String,
  categ_string: String,
  psotl_string: String,
  profs_string: String,
  rg_string: String,
  vfnum_string: String,
  konzs_string: String,
  adrnr_string: String,
  dummy_lfa1_addr_incl_eew_ps_string: String,
  partner_utr_string: String,
  comsize_string: String,
  psois_string: String,
  j_1ipanref_string: String,
  telf2_string: String,
  paytrsn_string: String,
  j_1kftind_string: String,
  j_1ipanvaldt_string: String,
  podkzb_string: String,
  esrnr_string: String,
  au_not_entitled_abn_string: String,
  addr2_post_string: String,
  au_domestic_nature_string: String,
  actss_string: String,
  data_ctrlr1_string: String,
  xzemp_string: String,
  j_1iexcd_string: String,
  lfa1_eew_supp_string: String,
  psovn_string: String,
  teltx_string: String,
  borgr_yeaun_string: String,
  j_1ivtyp_string: String,
  revdb_string: String,
  sperm_string: String,
  indtyp_string: String,
  submi_relevant_string: String,
  pstlz_string: String,
  rnedate_string: String,
  pmt_office_string: String,
  taxbs_string: String,
  pson2_string: String,
  au_partner_without_gain_string: String,
  allowance_type_string: String,
  name2_string: String,
  stcdt_string: String,
  cnae_string: String,
  sam_ue_id_string: String,
  data_ctrlr5_string: String,
  aedat_string: String,
  j_1icstno_string: String,
  ltsna_string: String,
  ausdiv_string: String,
  pstl2_string: String,
  sperq_string: String,
  @Decimal(3, 0) staging_time_decimal_3_0: BigDecimal,
  uf_string: String,
  min_comp_string: String,
  au_private_hobby_string: String,
  stcd3_string: String,
  dtaws_string: String,
  ktock_string: String,
  j_1isern_string: String,
  addr2_street_string: String,
  werkr_string: String,
  fr_occupation_string: String,
  ort01_string: String,
  lifnr_string: String,
  j_1iexdi_string: String,
  bubkz_string: String,
  weora_string: String,
  lzone_string: String,
  @Decimal(15, 2) j_sc_capital_decimal_15_2: BigDecimal,
  au_ind_under_18_string: String,
  kunnr_string: String,
  sperr_string: String,
  loevm_string: String,
  @Decimal(15, 2) sc_capital_decimal_15_2: BigDecimal,
  stras_string: String,
  pfort_string: String,
  bbbnr_string: String,
  status_string: String,
  usnam_string: String,
  j_1ipanno_string: String,
  uptim_string: String,
  data_ctrlr10_string: String,
  sam_eft_ind_string: String,
  j_1iexrn_string: String,
  tdt_string: String,
  xlfza_string: String,
  qssys_string: String,
  rgdate_string: String,
  sexkz_string: String,
  data_ctrlr2_string: String,
  erdat_string: String
) extends Entity

object lfa1 extends TableSpec[lfa1_E](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
