package ct.dna.lakehouse.sr_raw.ct_gbl_psp
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class marc_E_part1(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  uomgr_string: String,
  scm_sft_lock_string: String,
  @Decimal(3, 1) _sapmp_tolprmi_decimal_3_1: BigDecimal,
  @Decimal(13, 3) scm_repsafty_v_decimal_13_3: BigDecimal,
  @Decimal(3, 1) ueeto_decimal_3_1: BigDecimal,
  matnr_string: String,
  @Decimal(11, 0) scm_giprt_decimal_11_0: BigDecimal,
  @Decimal(3, 0) resvp_decimal_3_0: BigDecimal,
  iuid_type_string: String,
  @Decimal(13, 3) bstmi_decimal_13_3: BigDecimal,
  zz_shelf_life_h_string: String,
  ueetk_string: String,
  lgpro_string: String,
  ladgr_string: String,
  diber_string: String,
  rgekz_string: String,
  atpkz_string: String,
  shpro_string: String,
  sgt_stk_prt_string: String,
  schgt_string: String,
  @Decimal(13, 2) vkumc_decimal_13_2: BigDecimal,
  ocmpf_string: String,
  scm_ges_bst_use_string: String,
  _vso_r_fork_dir_string: String,
  prctr_string: String,
  otype_string: String,
  lizyk_string: String,
  sobsk_string: String,
  @Decimal(13, 3) scm_ppsaftystk_decimal_13_3: BigDecimal,
  kzech_string: String,
  mrppp_string: String,
  lfmon_string: String,
  dummy_plnt_incl_eew_ps_string: String,
  vint2_string: String,
  temp_uom_string: String,
  @Decimal(5, 2) kausf_decimal_5_2: BigDecimal,
  @Decimal(9, 0) wstgh_decimal_9_0: BigDecimal,
  plnnr_string: String,
  objid_string: String,
  usequ_string: String,
  fsh_mg_arun_req_string: String,
  @Decimal(13, 3) umlmc_decimal_13_3: BigDecimal,
  lzeih_string: String,
  sauft_string: String,
  @Decimal(13, 3) scm_reord_v_decimal_13_3: BigDecimal,
  loggr_string: String,
  copam_string: String,
  zz_testprofile_string: String,
  fsh_calendar_group_string: String,
  @Decimal(3, 2) scm_scost_prcnt_decimal_3_2: BigDecimal,
  bwtty_string: String,
  @Decimal(13, 2) vkglg_decimal_13_2: BigDecimal,
  kordb_string: String,
  @Decimal(13, 3) scm_ndcostwe_decimal_13_3: BigDecimal,
  sgt_mmstd_string: String,
  nkmpr_string: String,
  profil_string: String,
  autru_string: String,
  kzppv_string: String,
  fhori_string: String,
  scm_hunit_string: String,
  bwscl_string: String,
  qmatv_string: String,
  ccfix_string: String,
  prend_string: String,
  miskz_string: String,
  steuc_string: String,
  prene_string: String,
  plnty_string: String,
  @Decimal(4, 2) vrbfk_decimal_4_2: BigDecimal,
  @Decimal(11, 0) scm_peg_past_alert_decimal_11_0: BigDecimal,
  @Decimal(2, 1) abfac_decimal_2_1: BigDecimal,
  pstat_string: String,
  zzeudr_string: String,
  @Decimal(11, 0) scm_thruput_time_decimal_11_0: BigDecimal,
  sgt_mrpsi_string: String,
  indus_string: String,
  compl_string: String,
  excise_tax_rlvnce_string: String,
  frtme_string: String,
  dplfs_string: String,
  kzpro_string: String,
  esppflg_string: String,
  uchkz_string: String,
  ausdt_string: String,
  @Decimal(15, 3) scm_min_pass_amount_decimal_15_3: BigDecimal,
  scm_hunit_out_string: String,
  umrsl_string: String,
  pfrei_string: String,
  @Decimal(11, 0) scm_grprt_decimal_11_0: BigDecimal,
  mdach_string: String,
  scm_res_net_name_string: String,
  kzkup_string: String,
  scm_shelf_life_loc_string: String,
  @Decimal(13, 3) scm_sspen_decimal_13_3: BigDecimal,
  vrbmt_string: String,
  dispr_string: String,
  ucmat_string: String,
  scm_package_id_string: String,
  sbdkz_string: String,
  scm_peg_wo_alert_fst_string: String,
  kzpsp_string: String,
  @Decimal(7, 2) temp_ctrl_min_decimal_7_2: BigDecimal,
  @Decimal(11, 0) scm_shelf_life_dur_decimal_11_0: BigDecimal,
  @Decimal(13, 3) bwesb_decimal_13_3: BigDecimal,
  rdprf_string: String,
  multiple_ekgrp_string: String,
  @Decimal(11, 0) scm_reord_dur_decimal_11_0: BigDecimal,
  max_troc_string: String,
  @Decimal(13, 3) scm_proc_cost_decimal_13_3: BigDecimal,
  vrbwk_string: String,
  stlan_string: String,
  scm_ges_mng_use_string: String,
  jitprodnconfprofile_string: String,
  @Decimal(5, 2) bearz_decimal_5_2: BigDecimal,
  @Decimal(13, 3) scm_repsafty_decimal_13_3: BigDecimal,
  @Decimal(11, 0) scm_maturity_dur_decimal_11_0: BigDecimal,
  stlal_string: String,
  _sttpec_servalid_string: String,
  ref_schema_string: String,
  @Decimal(3, 0) plifz_decimal_3_0: BigDecimal,
  sfcpf_string: String,
  fxhor_string: String,
  scm_stra1_string: String,
  @Decimal(3, 1) _sapmp_tolprpl_decimal_3_1: BigDecimal,
  @Decimal(13, 3) bstfe_decimal_13_3: BigDecimal,
  xmcng_string: String,
  kzkfk_string: String,
  fsh_seaim_string: String,
  zz_oldmatnr_string: String,
  auftl_string: String,
  nfmat_string: String,
  ppskz_string: String,
  @Decimal(3, 0) takzt_decimal_3_0: BigDecimal,
  _vso_r_pkgrp_string: String,
  _vso_r_lane_num_string: String,
  @Decimal(13, 3) minbe_decimal_13_3: BigDecimal,
  ffrei_string: String,
  dispo_string: String,
  gpmkz_string: String,
  sgt_mrp_atp_status_string: String,
  eprio_string: String,
  sgt_covs_string: String,
  lgfsb_string: String,
  @Decimal(13, 3) scm_maxstock_v_decimal_13_3: BigDecimal,
  sfepr_string: String,
  plvar_string: String,
  shzet_string: String,
  werks_string: String,
  @Decimal(11, 0) scm_shlf_lfe_req_max_decimal_11_0: BigDecimal,
  cuobj_string: String,
  rotation_date_string: String,
  @Decimal(13, 3) eislo_decimal_13_3: BigDecimal,
  @Decimal(5, 0) mpdau_decimal_5_0: BigDecimal,
  fprfm_string: String,
  zz_custmatnum_string: String,
  mandt_string: String,
  casnr_string: String,
  cuobv_string: String,
  @Decimal(13, 3) vbamg_decimal_13_3: BigDecimal,
  dismm_string: String,
  lfrhy_string: String,
  @Decimal(5, 2) vbeaz_decimal_5_2: BigDecimal,
  @Decimal(3, 1) lgrad_decimal_3_1: BigDecimal,
  qmata_string: String,
  @Decimal(13, 3) scm_conhap_out_decimal_13_3: BigDecimal,
  prefe_string: String,
  stdpd_string: String,
  fxpru_string: String,
  ekgrp_string: String,
  @Decimal(13, 3) scm_safty_v_decimal_13_3: BigDecimal,
  scm_peg_strategy_string: String,
  perkz_string: String,
  @Decimal(3, 0) scm_reldt_decimal_3_0: BigDecimal,
  stawn_string: String,
  @Decimal(11, 0) scm_target_dur_decimal_11_0: BigDecimal,
  sgt_defsc_string: String,
  @Decimal(3, 1) sproz_decimal_3_1: BigDecimal,
  matgr_string: String,
  scm_matlocid_guid16_binary: Array[Byte],
  scm_whatbom_string: String,
  sgt_scope_string: String,
  convt_string: String,
  dpcbt_string: String,
  servg_string: String,
  @Decimal(13, 3) fixls_decimal_13_3: BigDecimal,
  apokz_string: String,
  @Decimal(13, 3) maxls_decimal_13_3: BigDecimal,
  @Decimal(3, 0) gi_pr_time_decimal_3_0: BigDecimal,
  kzagl_string: String,
  beskz_string: String,
  fevor_string: String,
  @Decimal(3, 0) dplho_decimal_3_0: BigDecimal,
  mmstd_string: String,
  kzkri_string: String,
  fsh_kzech_string: String,
  lagpr_string: String,
  scm_fixpeg_prod_set_string: String,
  @Decimal(13, 3) basmg_decimal_13_3: BigDecimal,
  nf_flag_string: String,
  @Decimal(3, 0) wzeit_decimal_3_0: BigDecimal,
  iuid_relevant_string: String,
  @Decimal(11, 2) losfx_decimal_11_2: BigDecimal,
  @Decimal(13, 3) scm_ppsaftystk_v_decimal_13_3: BigDecimal,
  kzdkz_string: String,
  scm_heur_id_string: String,
  sgt_chint_string: String,
  itark_string: String,
  preno_string: String,
  ausme_string: String,
  @Decimal(3, 0) dzeit_decimal_3_0: BigDecimal,
  ahdis_string: String,
  mtvfp_string: String,
  herbl_string: String,
  @Decimal(13, 3) minls_decimal_13_3: BigDecimal,
  @Decimal(7, 2) temp_ctrl_max_decimal_7_2: BigDecimal,
  zz_prioritynum_string: String,
  @Decimal(13, 3) glgmg_decimal_13_3: BigDecimal,
  vrbdt_string: String,
  @Decimal(13, 3) _cwm_trame_decimal_13_3: BigDecimal,
  altsl_string: String,
  lfgja_string: String,
  @Decimal(11, 0) scm_peg_future_alert_decimal_11_0: BigDecimal,
  @Decimal(13, 3) scm_conhap_decimal_13_3: BigDecimal,
  @Decimal(3, 0) quazt_decimal_3_0: BigDecimal,
  megru_string: String,
  dplpu_string: String,
  aplal_string: String,
  zz_productresp_string: String,
  zz_hdate_string: String,
  sgt_prcm_string: String,
  ssqss_string: String,
  kzdie_string: String,
  fsh_var_group_string: String,
  scm_iunit_string: String,
  @Decimal(13, 2) vktrw_decimal_13_2: BigDecimal,
  @Decimal(5, 0) maxlz_decimal_5_0: BigDecimal,
  @Decimal(5, 2) ruezt_decimal_5_2: BigDecimal,
  cons_procg_string: String,
  @Decimal(13, 3) bstrf_decimal_13_3: BigDecimal,
  mownr_string: String,
  gpnum_string: String
) extends Entity


@LakehouseEntity
case class marc_E_part2(
  @PK _mk_org: String,
  prenc_string: String,
  conf_gmsync_string: String,
  mfrgr_string: String,
  mcrue_string: String,
  @Decimal(13, 3) target_stock_decimal_13_3: BigDecimal,
  sgt_statc_string: String,
  xchar_string: String,
  kzaus_string: String,
  scm_tpop_string: String,
  scm_lsuom_string: String,
  scm_get_alerts_string: String,
  insmk_string: String,
  maabc_string: String,
  vrmod_string: String,
  @Decimal(13, 3) ltinc_decimal_13_3: BigDecimal,
  vspvb_string: String,
  @Decimal(13, 3) losgr_decimal_13_3: BigDecimal,
  scm_tstrid_string: String,
  vint1_string: String,
  verkz_string: String,
  preng_string: String,
  herkr_string: String,
  sobsl_string: String,
  arun_fix_batch_string: String,
  @Decimal(5, 2) vzusl_decimal_5_2: BigDecimal,
  @Decimal(5, 2) ausss_decimal_5_2: BigDecimal,
  @Decimal(5, 2) vrvez_decimal_5_2: BigDecimal,
  scm_rrp_type_string: String,
  _vso_r_pal_vend_string: String,
  awsls_string: String,
  periv_string: String,
  mtver_string: String,
  herkl_string: String,
  @Decimal(11, 0) scm_shlf_lfe_req_min_decimal_11_0: BigDecimal,
  @Decimal(13, 3) bstma_decimal_13_3: BigDecimal,
  @Decimal(5, 2) tranz_decimal_5_2: BigDecimal,
  scm_intsrc_prof_string: String,
  mmsta_string: String,
  kzbed_string: String,
  uid_iea_string: String,
  disgr_string: String,
  @Decimal(13, 3) eisbe_decimal_13_3: BigDecimal,
  disls_string: String,
  sfty_stk_meth_string: String,
  @Decimal(13, 3) scm_coninp_decimal_13_3: BigDecimal,
  @Decimal(13, 3) scm_ndcostwa_decimal_13_3: BigDecimal,
  sernp_string: String,
  lvorm_string: String,
  @Decimal(13, 3) mabst_decimal_13_3: BigDecimal,
  mogru_string: String,
  min_troc_string: String,
  scm_profid_string: String,
  scm_prio_int: BoxedInt,
  @Decimal(3, 0) webaz_decimal_3_0: BigDecimal,
  shflg_string: String,
  expme_string: String,
  kautb_string: String,
  @Decimal(13, 3) _cwm_bwesb_decimal_13_3: BigDecimal,
  abcin_string: String,
  scm_matlocid_guid22_string: String,
  @Decimal(13, 3) _cwm_umlmc_decimal_13_3: BigDecimal,
  rwpro_string: String,
  fvidk_string: String,
  @Decimal(5, 0) prfrq_decimal_5_0: BigDecimal,
  qssys_string: String,
  ncost_string: String,
  qzgtp_string: String,
  xchpf_string: String,
  @Decimal(13, 3) scm_scost_decimal_13_3: BigDecimal,
  fabkz_string: String,
  scm_rrp_sel_group_string: String,
  strgr_string: String,
  @Decimal(13, 3) trame_decimal_13_3: BigDecimal,
  @Decimal(3, 1) uneto_decimal_3_1: BigDecimal
) extends Entity

object marc extends TableSpec[Joined[marc_E_part1, marc_E_part2]](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
