// LOADED TABLE SPEC AUTO GENERATED:START
// Generated by LoadedTableSpecAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr_raw.ct_gbl_psp

import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.Loaded
import ct.dna.lakehouse.core.model.TableSpec

case class E_vbfa(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt_string: String,
    ruuid_binary: Array[Byte],
    vbelv_string: String,
    posnv_string: String,
    vbeln_string: String,
    posnn_string: String,
    vbtyp_n_string: String,
    @Decimal(15, 3) rfmng_decimal_15_3: BigDecimal,
    meins_string: String,
    @Decimal(15, 2) rfwrt_decimal_15_2: BigDecimal,
    waers_string: String,
    vbtyp_v_string: String,
    plmin_string: String,
    taqui_string: String,
    erdat_string: String,
    erzet_string: String,
    matnr_string: String,
    bwart_string: String,
    bdart_string: String,
    plart_string: String,
    lgnum_string: String,
    aedat_string: String,
    fktyp_string: String,
    @Decimal(15, 3) brgew_decimal_15_3: BigDecimal,
    gewei_string: String,
    @Decimal(15, 3) volum_decimal_15_3: BigDecimal,
    voleh_string: String,
    fplnr_string: String,
    fpltr_string: String,
    rfmng_flo_double: BoxedDouble,
    rfmng_flt_double: BoxedDouble,
    vrkme_string: String,
    abges_double: BoxedDouble,
    sobkz_string: String,
    sonum_string: String,
    kzbef_string: String,
    @Decimal(13, 3) ntgew_decimal_13_3: BigDecimal,
    logsys_string: String,
    wbsta_string: String,
    cmeth_string: String,
    mjahr_string: String,
    stufe_string: String,
    _dataaging_string: String
) extends Entity

object vbfa
    extends TableSpec[E_vbfa](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.Columns("_mk_instance", "_mk_partition", "_mk_file"),
      timetravelDays = 35
    )
    with Loaded
// LOADED TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_vbfa(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val mandt_string: ColumnWithName = ColumnWithName(prefix + "mandt_string")
  val ruuid_binary: ColumnWithName = ColumnWithName(prefix + "ruuid_binary")
  val vbelv_string: ColumnWithName = ColumnWithName(prefix + "vbelv_string")
  val posnv_string: ColumnWithName = ColumnWithName(prefix + "posnv_string")
  val vbeln_string: ColumnWithName = ColumnWithName(prefix + "vbeln_string")
  val posnn_string: ColumnWithName = ColumnWithName(prefix + "posnn_string")
  val vbtyp_n_string: ColumnWithName = ColumnWithName(prefix + "vbtyp_n_string")
  val rfmng_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "rfmng_decimal_15_3")
  val meins_string: ColumnWithName = ColumnWithName(prefix + "meins_string")
  val rfwrt_decimal_15_2: ColumnWithName = ColumnWithName(prefix + "rfwrt_decimal_15_2")
  val waers_string: ColumnWithName = ColumnWithName(prefix + "waers_string")
  val vbtyp_v_string: ColumnWithName = ColumnWithName(prefix + "vbtyp_v_string")
  val plmin_string: ColumnWithName = ColumnWithName(prefix + "plmin_string")
  val taqui_string: ColumnWithName = ColumnWithName(prefix + "taqui_string")
  val erdat_string: ColumnWithName = ColumnWithName(prefix + "erdat_string")
  val erzet_string: ColumnWithName = ColumnWithName(prefix + "erzet_string")
  val matnr_string: ColumnWithName = ColumnWithName(prefix + "matnr_string")
  val bwart_string: ColumnWithName = ColumnWithName(prefix + "bwart_string")
  val bdart_string: ColumnWithName = ColumnWithName(prefix + "bdart_string")
  val plart_string: ColumnWithName = ColumnWithName(prefix + "plart_string")
  val lgnum_string: ColumnWithName = ColumnWithName(prefix + "lgnum_string")
  val aedat_string: ColumnWithName = ColumnWithName(prefix + "aedat_string")
  val fktyp_string: ColumnWithName = ColumnWithName(prefix + "fktyp_string")
  val brgew_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "brgew_decimal_15_3")
  val gewei_string: ColumnWithName = ColumnWithName(prefix + "gewei_string")
  val volum_decimal_15_3: ColumnWithName = ColumnWithName(prefix + "volum_decimal_15_3")
  val voleh_string: ColumnWithName = ColumnWithName(prefix + "voleh_string")
  val fplnr_string: ColumnWithName = ColumnWithName(prefix + "fplnr_string")
  val fpltr_string: ColumnWithName = ColumnWithName(prefix + "fpltr_string")
  val rfmng_flo_double: ColumnWithName = ColumnWithName(prefix + "rfmng_flo_double")
  val rfmng_flt_double: ColumnWithName = ColumnWithName(prefix + "rfmng_flt_double")
  val vrkme_string: ColumnWithName = ColumnWithName(prefix + "vrkme_string")
  val abges_double: ColumnWithName = ColumnWithName(prefix + "abges_double")
  val sobkz_string: ColumnWithName = ColumnWithName(prefix + "sobkz_string")
  val sonum_string: ColumnWithName = ColumnWithName(prefix + "sonum_string")
  val kzbef_string: ColumnWithName = ColumnWithName(prefix + "kzbef_string")
  val ntgew_decimal_13_3: ColumnWithName = ColumnWithName(prefix + "ntgew_decimal_13_3")
  val logsys_string: ColumnWithName = ColumnWithName(prefix + "logsys_string")
  val wbsta_string: ColumnWithName = ColumnWithName(prefix + "wbsta_string")
  val cmeth_string: ColumnWithName = ColumnWithName(prefix + "cmeth_string")
  val mjahr_string: ColumnWithName = ColumnWithName(prefix + "mjahr_string")
  val stufe_string: ColumnWithName = ColumnWithName(prefix + "stufe_string")
  val _dataaging_string: ColumnWithName = ColumnWithName(prefix + "_dataaging_string")
}

object C_vbfa extends C_vbfa("") {
  def as(alias: String): C_vbfa = new C_vbfa(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
