// CHANGE KEY TABLE SPEC AUTO GENERATED:START
// Generated by ChangeKeyAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr.ct_gbl_p9a

import ct.dna.lakehouse.core.model.ChangeKey
import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec
import ct.dna.lakehouse.sr_raw
import org.apache.spark.sql.Column
import org.apache.spark.sql.functions.col

case class E_query_conti_copa_qry004_zcp_copa_0004(
    _0gn_r3_ssy_ : String,
    _4zcp_copa_documenttype_ : String,
    _zdw_btype_ : String,
    @PK _zdw_bu_ : String,
    _zdw_bu_2zdw_bu_ : String,
    _zdw_bu_1zdw_bu_ : String,
    _zdw_ddate_ : String,
    _zdw_dtype_ : String,
    _zdw_gidat_ : String,
    _zdw_ivdat_ : String,
    @PK _zdw_matl_ : String,
    _zdw_matl_2zdw_matl_ : String,
    _zdw_matl_1zdw_matl_ : String,
    _zdw_ocdat_ : String,
    _zdw_pcomp_ : String,
    _zdw_pcomp_2zdw_pcomp_ : String,
    _zdw_pcomp_1zdw_pcomp_ : String,
    @PK _zdw_plant_ : String,
    _zdw_plant_2zdw_plant_ : String,
    _zdw_plant_1zdw_plant_ : String,
    _zdw_podat_ : String,
    _zdw_pscyr_ : String,
    _zdw_psdat_ : String,
    _zdw_rhdat_ : String,
    _zdw_rpdat_ : String,
    _zdw_sdto_ : String,
    _zdw_sdto_2zdw_sdto_ : String,
    _zdw_sdto_1zdw_sdto_ : String,
    @PK _zdw_seg_ : String,
    _zdw_seg_2zdw_seg_ : String,
    _zdw_seg_1zdw_seg_ : String,
    @PK _zdw_snpdt_ : String,
    _zdw_tgdat_ : String,
    _zdw_vrtup_ : String,
    _zdw_vrtup_2zdw_vrtup_ : String,
    _zdw_vrtup_1zdw_vrtup_ : String,
    @Decimal(15, 2) _1nbg5lj7w7gam9zbngu9lqisu_1nbg5lj7w7gam9zbngu9ltoku_ : BigDecimal,
    _1nbg5lj7w7gam9zbngu9lqisu_1nbg5lj7w7gam9zbngu9mwhim_ : BoxedDouble,
    _1nbg5lj7w7gam9zbngu9lqisu_1nbg5lj7w7gamnplq3t3p38s1_ : BoxedDouble,
    @Decimal(15, 3) _1nbg5lj7w7gam9zbngu9lqisu_e6l8g90fhoqyrdsl7kpfvu0l4_ : BigDecimal,
    @NotNull _mk_org: String,
    @NotNull _mk_site: String,
    @NotNull _mk_system: String,
    @NotNull _mk_instance: String,
    @NotNull _mk_partition: String,
    @NotNull _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    _lh_id_in_message: Long,
    _lh_ingest_warning: String
) extends Entity

object query_conti_copa_qry004_zcp_copa_0004
    extends TableSpec[E_query_conti_copa_qry004_zcp_copa_0004](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.PRIMARY_KEY,
      timetravelDays = 35
    )
    with ChangeKey[sr_raw.ct_gbl_p9a.E_query_conti_copa_qry004_zcp_copa_0004] {
  override def sourceTableSpec: TableSpec[sr_raw.ct_gbl_p9a.E_query_conti_copa_qry004_zcp_copa_0004] = sr_raw.ct_gbl_p9a.query_conti_copa_qry004_zcp_copa_0004
  override def sequenceBy: Column = col("_mk_created_at")

  override def preApplyMapping: Seq[(String, Column)] = Seq(
    ("_0gn_r3_ssy_", col("_0gn_r3_ssy_string")),
    ("_4zcp_copa_documenttype_", col("_4zcp_copa_documenttype_string")),
    ("_zdw_btype_", col("_zdw_btype_string")),
    ("_zdw_bu_", col("_zdw_bu_string")),
    ("_zdw_bu_2zdw_bu_", col("_zdw_bu_2zdw_bu_string")),
    ("_zdw_bu_1zdw_bu_", col("_zdw_bu_1zdw_bu_string")),
    ("_zdw_ddate_", col("_zdw_ddate_string")),
    ("_zdw_dtype_", col("_zdw_dtype_string")),
    ("_zdw_gidat_", col("_zdw_gidat_string")),
    ("_zdw_ivdat_", col("_zdw_ivdat_string")),
    ("_zdw_matl_", col("_zdw_matl_string")),
    ("_zdw_matl_2zdw_matl_", col("_zdw_matl_2zdw_matl_string")),
    ("_zdw_matl_1zdw_matl_", col("_zdw_matl_1zdw_matl_string")),
    ("_zdw_ocdat_", col("_zdw_ocdat_string")),
    ("_zdw_pcomp_", col("_zdw_pcomp_string")),
    ("_zdw_pcomp_2zdw_pcomp_", col("_zdw_pcomp_2zdw_pcomp_string")),
    ("_zdw_pcomp_1zdw_pcomp_", col("_zdw_pcomp_1zdw_pcomp_string")),
    ("_zdw_plant_", col("_zdw_plant_string")),
    ("_zdw_plant_2zdw_plant_", col("_zdw_plant_2zdw_plant_string")),
    ("_zdw_plant_1zdw_plant_", col("_zdw_plant_1zdw_plant_string")),
    ("_zdw_podat_", col("_zdw_podat_string")),
    ("_zdw_pscyr_", col("_zdw_pscyr_string")),
    ("_zdw_psdat_", col("_zdw_psdat_string")),
    ("_zdw_rhdat_", col("_zdw_rhdat_string")),
    ("_zdw_rpdat_", col("_zdw_rpdat_string")),
    ("_zdw_sdto_", col("_zdw_sdto_string")),
    ("_zdw_sdto_2zdw_sdto_", col("_zdw_sdto_2zdw_sdto_string")),
    ("_zdw_sdto_1zdw_sdto_", col("_zdw_sdto_1zdw_sdto_string")),
    ("_zdw_seg_", col("_zdw_seg_string")),
    ("_zdw_seg_2zdw_seg_", col("_zdw_seg_2zdw_seg_string")),
    ("_zdw_seg_1zdw_seg_", col("_zdw_seg_1zdw_seg_string")),
    ("_zdw_snpdt_", col("_zdw_snpdt_string")),
    ("_zdw_tgdat_", col("_zdw_tgdat_string")),
    ("_zdw_vrtup_", col("_zdw_vrtup_string")),
    ("_zdw_vrtup_2zdw_vrtup_", col("_zdw_vrtup_2zdw_vrtup_string")),
    ("_zdw_vrtup_1zdw_vrtup_", col("_zdw_vrtup_1zdw_vrtup_string")),
    ("_1nbg5lj7w7gam9zbngu9lqisu_1nbg5lj7w7gam9zbngu9ltoku_", col("_1nbg5lj7w7gam9zbngu9lqisu_1nbg5lj7w7gam9zbngu9ltoku_decimal_15_2")),
    ("_1nbg5lj7w7gam9zbngu9lqisu_1nbg5lj7w7gam9zbngu9mwhim_", col("_1nbg5lj7w7gam9zbngu9lqisu_1nbg5lj7w7gam9zbngu9mwhim_double")),
    ("_1nbg5lj7w7gam9zbngu9lqisu_1nbg5lj7w7gamnplq3t3p38s1_", col("_1nbg5lj7w7gam9zbngu9lqisu_1nbg5lj7w7gamnplq3t3p38s1_double")),
    ("_1nbg5lj7w7gam9zbngu9lqisu_e6l8g90fhoqyrdsl7kpfvu0l4_", col("_1nbg5lj7w7gam9zbngu9lqisu_e6l8g90fhoqyrdsl7kpfvu0l4_decimal_15_3"))
  )
}
// CHANGE KEY TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_query_conti_copa_qry004_zcp_copa_0004(prefix: String) extends ColumnWithNameAccessor {
  val _0gn_r3_ssy_ : ColumnWithName = ColumnWithName(prefix + "_0gn_r3_ssy_")
  val _4zcp_copa_documenttype_ : ColumnWithName = ColumnWithName(prefix + "_4zcp_copa_documenttype_")
  val _zdw_btype_ : ColumnWithName = ColumnWithName(prefix + "_zdw_btype_")
  val _zdw_bu_ : ColumnWithName = ColumnWithName(prefix + "_zdw_bu_")
  val _zdw_bu_2zdw_bu_ : ColumnWithName = ColumnWithName(prefix + "_zdw_bu_2zdw_bu_")
  val _zdw_bu_1zdw_bu_ : ColumnWithName = ColumnWithName(prefix + "_zdw_bu_1zdw_bu_")
  val _zdw_ddate_ : ColumnWithName = ColumnWithName(prefix + "_zdw_ddate_")
  val _zdw_dtype_ : ColumnWithName = ColumnWithName(prefix + "_zdw_dtype_")
  val _zdw_gidat_ : ColumnWithName = ColumnWithName(prefix + "_zdw_gidat_")
  val _zdw_ivdat_ : ColumnWithName = ColumnWithName(prefix + "_zdw_ivdat_")
  val _zdw_matl_ : ColumnWithName = ColumnWithName(prefix + "_zdw_matl_")
  val _zdw_matl_2zdw_matl_ : ColumnWithName = ColumnWithName(prefix + "_zdw_matl_2zdw_matl_")
  val _zdw_matl_1zdw_matl_ : ColumnWithName = ColumnWithName(prefix + "_zdw_matl_1zdw_matl_")
  val _zdw_ocdat_ : ColumnWithName = ColumnWithName(prefix + "_zdw_ocdat_")
  val _zdw_pcomp_ : ColumnWithName = ColumnWithName(prefix + "_zdw_pcomp_")
  val _zdw_pcomp_2zdw_pcomp_ : ColumnWithName = ColumnWithName(prefix + "_zdw_pcomp_2zdw_pcomp_")
  val _zdw_pcomp_1zdw_pcomp_ : ColumnWithName = ColumnWithName(prefix + "_zdw_pcomp_1zdw_pcomp_")
  val _zdw_plant_ : ColumnWithName = ColumnWithName(prefix + "_zdw_plant_")
  val _zdw_plant_2zdw_plant_ : ColumnWithName = ColumnWithName(prefix + "_zdw_plant_2zdw_plant_")
  val _zdw_plant_1zdw_plant_ : ColumnWithName = ColumnWithName(prefix + "_zdw_plant_1zdw_plant_")
  val _zdw_podat_ : ColumnWithName = ColumnWithName(prefix + "_zdw_podat_")
  val _zdw_pscyr_ : ColumnWithName = ColumnWithName(prefix + "_zdw_pscyr_")
  val _zdw_psdat_ : ColumnWithName = ColumnWithName(prefix + "_zdw_psdat_")
  val _zdw_rhdat_ : ColumnWithName = ColumnWithName(prefix + "_zdw_rhdat_")
  val _zdw_rpdat_ : ColumnWithName = ColumnWithName(prefix + "_zdw_rpdat_")
  val _zdw_sdto_ : ColumnWithName = ColumnWithName(prefix + "_zdw_sdto_")
  val _zdw_sdto_2zdw_sdto_ : ColumnWithName = ColumnWithName(prefix + "_zdw_sdto_2zdw_sdto_")
  val _zdw_sdto_1zdw_sdto_ : ColumnWithName = ColumnWithName(prefix + "_zdw_sdto_1zdw_sdto_")
  val _zdw_seg_ : ColumnWithName = ColumnWithName(prefix + "_zdw_seg_")
  val _zdw_seg_2zdw_seg_ : ColumnWithName = ColumnWithName(prefix + "_zdw_seg_2zdw_seg_")
  val _zdw_seg_1zdw_seg_ : ColumnWithName = ColumnWithName(prefix + "_zdw_seg_1zdw_seg_")
  val _zdw_snpdt_ : ColumnWithName = ColumnWithName(prefix + "_zdw_snpdt_")
  val _zdw_tgdat_ : ColumnWithName = ColumnWithName(prefix + "_zdw_tgdat_")
  val _zdw_vrtup_ : ColumnWithName = ColumnWithName(prefix + "_zdw_vrtup_")
  val _zdw_vrtup_2zdw_vrtup_ : ColumnWithName = ColumnWithName(prefix + "_zdw_vrtup_2zdw_vrtup_")
  val _zdw_vrtup_1zdw_vrtup_ : ColumnWithName = ColumnWithName(prefix + "_zdw_vrtup_1zdw_vrtup_")
  val _1nbg5lj7w7gam9zbngu9lqisu_1nbg5lj7w7gam9zbngu9ltoku_ : ColumnWithName = ColumnWithName(prefix + "_1nbg5lj7w7gam9zbngu9lqisu_1nbg5lj7w7gam9zbngu9ltoku_")
  val _1nbg5lj7w7gam9zbngu9lqisu_1nbg5lj7w7gam9zbngu9mwhim_ : ColumnWithName = ColumnWithName(prefix + "_1nbg5lj7w7gam9zbngu9lqisu_1nbg5lj7w7gam9zbngu9mwhim_")
  val _1nbg5lj7w7gam9zbngu9lqisu_1nbg5lj7w7gamnplq3t3p38s1_ : ColumnWithName = ColumnWithName(prefix + "_1nbg5lj7w7gam9zbngu9lqisu_1nbg5lj7w7gamnplq3t3p38s1_")
  val _1nbg5lj7w7gam9zbngu9lqisu_e6l8g90fhoqyrdsl7kpfvu0l4_ : ColumnWithName = ColumnWithName(prefix + "_1nbg5lj7w7gam9zbngu9lqisu_e6l8g90fhoqyrdsl7kpfvu0l4_")
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
}

object C_query_conti_copa_qry004_zcp_copa_0004 extends C_query_conti_copa_qry004_zcp_copa_0004("") {
  def as(alias: String): C_query_conti_copa_qry004_zcp_copa_0004 = new C_query_conti_copa_qry004_zcp_copa_0004(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
