package ct.dna.lakehouse.dw_tx.fin_fxrates

import ct.dna.lakehouse.core.framework.IDResolver
import ct.dna.lakehouse.core.testutils.TestDataManager
import ct.dna.lakehouse.core.testutils.TestForTable
import ct.dna.lakehouse.sr.ct_gbl_ghp
import ct.dna.utils.ResourceLoader
import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._

/** End-to-end test for `ct.dna.lakehouse.dw_tx.fin_fxrates.fxrates`.
  *
  * Drives the full production code path (`UpdatedTableProcessor.update(fxrates)` → `fxrates.executeTransaction`) against real Delta tables on a local ephemeral
  * Spark / Hive metastore. Each phase mutates the TCURR/TCURF source tables via [[TestDataManager.syncToSource]], runs the update, and asserts the resulting
  * target contents against an Excel sheet via [[TestDataManager.assertTargetMatches]].
  *
  * The fxrates transform reads TCURR + TCURF sources, joins them, computes EUR base rates, EUR inverse rates, cross rates, and identity rates, then MERGEs into
  * the target with a full-overwrite pattern (whenNotMatchedBySource → delete).
  *
  * Uses exact-fraction ukurs values (−2.0, −4.0, −0.5) that produce exact decimal results, avoiding floating-point comparison issues.
  *
  * Phases:
  *
  *   1. Phase 0 — TCURR/TCURF empty → target must remain empty.
  *
  *   1. Phase 1 — TCURR loaded with USD (ukurs=−2→rate=0.5) and INR (ukurs=−4→rate=0.25). Generates 9 target rows (2 base + 2 inverse + 2 cross + 3 identity).
  *
  *   1. Phase 2 — TCURR replaced with USD + GBP (ukurs=−0.5→rate=2.0). INR rows are deleted, GBP rows inserted.
  *
  * An empty archive table (`sr_raw.mn_gbl_spcentral.fxarchive`) is created via a DeltaCatalog to satisfy the production code's `SparkSession.active.table(...)`
  * call. The archive contributes no rows to the transform; GHP TCURR data is the sole source.
  *
  * The xlsx is regenerated by `lakehouse/src/test/scripts/ct/dna/lakehouse/dw_tx/fin_fxrates/generate_fxrates_test_xlsx.py`.
  */
class FxRatesTest extends TestForTable(fxrates) {

  lazy val tdm = TestDataManager("fxrates", "FxRatesTest.xlsx", ResourceLoader.withClass(fxrates.getClass))

  lazy val spark: SparkSession = SparkSession.active

  /** Read an xlsx sheet using the given spec's schema, but replacing DecimalType fields with StringType (since TestDataManager doesn't support DecimalType
    * cells), then casting them back. Finally overwrite the source Delta table.
    */
  private def syncSourceWithDecimals(spec: ct.dna.lakehouse.core.model.TableSpec[_ <: ct.dna.lakehouse.core.model.Entity], sheetName: String): Unit = {
    val originalSchema = spec.entityStructType
    // Replace DecimalType with StringType for reading
    val readSchema = StructType(originalSchema.map { f =>
      f.dataType match {
        case _: DecimalType => f.copy(dataType = StringType)
        case _              => f
      }
    })
    val rawDf = tdm.read(sheetName, readSchema)
    // Cast string columns back to their original DecimalType
    val castCols = originalSchema.map { f =>
      f.dataType match {
        case dt: DecimalType => col(f.name).cast(dt).as(f.name)
        case _               => col(f.name)
      }
    }
    val df = rawDf
      .select(castCols: _*)
      .withColumn("_lh_valid", lit(true))
      .withColumn("_lh_sequence_by", current_timestamp())
    // Write into the existing source table
    val fqn = SparkEnvAccess.idResolver.asSourceFQN(spec.id)
    val tableName = fqn.fqn
    spark.sql(s"DELETE FROM $tableName")
    df.createOrReplaceTempView("__fxrates_source_tmp")
    spark.sql(s"INSERT INTO $tableName (${df.columns.mkString(", ")}) SELECT * FROM __fxrates_source_tmp")
    spark.catalog.dropTempView("__fxrates_source_tmp")
  }

  /** Assert target matches expected xlsx sheet, handling DecimalType by reading as StringType then casting. */
  private def assertTargetWithDecimals(spec: ct.dna.lakehouse.core.model.TableSpec[_ <: ct.dna.lakehouse.core.model.Entity], sheetName: String): Unit = {
    val originalSchema = spec.entityStructType
    val readSchema = StructType(originalSchema.map { f =>
      f.dataType match {
        case _: DecimalType => f.copy(dataType = StringType)
        case _              => f
      }
    })
    val rawExpected = tdm.read(sheetName, readSchema)
    val castCols = originalSchema.map { f =>
      f.dataType match {
        case dt: DecimalType => col(f.name).cast(dt).as(f.name)
        case _               => col(f.name)
      }
    }
    val expected = rawExpected.select(castCols: _*)

    val fqn = SparkEnvAccess.idResolver.asTargetFQN(spec.id)
    val actual = spark.table(fqn.fqn).select(originalSchema.map(f => col(f.name)): _*)

    val keyColumns = spec.keyColumnNames.toSeq
    val expectedSorted = expected.orderBy(keyColumns.map(col): _*)
    val actualSorted = actual.orderBy(keyColumns.map(col): _*)

    assert(actualSorted.collect().toSeq === expectedSorted.collect().toSeq, s"Target content mismatch for sheet $sheetName")
  }

  /** Schema for the archive table read by `fxrates.executeTransaction`. */
  private val archiveSchema = StructType(
    Seq(
      StructField("kurst_string", StringType),
      StructField("fcurr_string", StringType),
      StructField("tcurr_string", StringType),
      StructField("ukurs_double", DoubleType),
      StructField("ukurs_long", LongType),
      StructField("gdatu_long", LongType)
    )
  )

  override protected def beforeAll(): Unit = {
    super.beforeAll()

    // Register 'sr_raw' as an EmptyTableCatalog so that
    // SparkSession.active.table("sr_raw.mn_gbl_spcentral.fxarchive") resolves.
    // The archive table is empty — all rates come from GHP TCURR in this test.
    spark.conf.set("spark.sql.catalog.sr_raw", classOf[EmptyTableCatalog].getName)
    spark.sql("CREATE NAMESPACE IF NOT EXISTS sr_raw.mn_gbl_spcentral")
    spark.sql(
      """CREATE TABLE IF NOT EXISTS sr_raw.mn_gbl_spcentral.fxarchive (
        |  kurst_string STRING,
        |  fcurr_string STRING,
        |  tcurr_string STRING,
        |  ukurs_double DOUBLE,
        |  ukurs_long LONG,
        |  gdatu_long LONG
        |) USING delta""".stripMargin
    )

    tdm.dropTargetIfExists(fxrates)
    fxrates.sourceTableSpecs.foreach(tdm.dropSourceIfExists)

    tdm.createAsTarget(fxrates)
    fxrates.sourceTableSpecs.foreach(tdm.createAsSource)
  }

  override protected def afterAll(): Unit = try {
    tdm.dropTargetIfExists(fxrates)
    fxrates.sourceTableSpecs.foreach(tdm.dropSourceIfExists)
    spark.sql("DROP TABLE IF EXISTS sr_raw.mn_gbl_spcentral.fxarchive")
    spark.sql("DROP NAMESPACE IF EXISTS sr_raw.mn_gbl_spcentral")
  } finally {
    // super.afterAll() calls clearIdResolverTablePrefix() which requires SparkEnv initialized,
    // so it must run before release().
    super.afterAll()
    // Release SparkEnv so its activeOption resets to None.
    // This prevents a stale reference when SparkTestBase tests (MarcTransformTest etc.)
    // call spark.stop() between this suite and MaktTest — without release, SparkEnv
    // thinks it's still initialized and skips session creation for MaktTest.
    SparkEnvAccess.release()
  }

  behavior of "fxrates"

  it should "validateToRoot" in {
    fxrates.validateToRoot()
  }

  // ---------------------------------------------------------------------------
  // Phase 0 — empty sources → empty target
  // ---------------------------------------------------------------------------

  it should "Phase 0: leave the target empty when TCURR/TCURF sources are empty" in {
    tdm.update(fxrates)
    tdm.assertTargetMatches(fxrates, "target_phase0")
  }

  // ---------------------------------------------------------------------------
  // Phase 1 — USD + INR → 9 rate rows
  // ---------------------------------------------------------------------------

  it should "Phase 1: compute EUR base, inverse, cross, and identity rates" in {
    syncSourceWithDecimals(ct_gbl_ghp.tcurr, "tcurr_phase1")
    syncSourceWithDecimals(ct_gbl_ghp.tcurf, "tcurf")

    tdm.update(fxrates)

    assertTargetWithDecimals(fxrates, "target_phase1")
  }

  // ---------------------------------------------------------------------------
  // Phase 2 — replace INR with GBP → old INR rows deleted, GBP rows inserted
  // ---------------------------------------------------------------------------

  it should "Phase 2: full-overwrite deletes removed currencies and inserts new ones" in {
    syncSourceWithDecimals(ct_gbl_ghp.tcurr, "tcurr_phase2")

    tdm.update(fxrates)

    assertTargetWithDecimals(fxrates, "target_phase2")
  }
}

/** Reflection-based access to SparkEnv methods that are private[core] in Scala but public at JVM level. */
private object SparkEnvAccess {
  private val clazz = Class.forName("ct.dna.lakehouse.core.runtime.SparkEnv$")
  private val instance = clazz.getField("MODULE$").get(null)

  def idResolver: IDResolver =
    clazz.getMethod("idResolver").invoke(instance).asInstanceOf[IDResolver]

  def release(): Unit =
    clazz.getMethod("release").invoke(instance)
}
