package ct.dna.lakehouse.sr_raw.ct_gbl_p85
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

@LakehouseEntity
case class mara_E_part1(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt_string: String,
    matnr_string: String,
    ersda_string: String,
    ernam_string: String,
    laeda_string: String,
    aenam_string: String,
    vpsta_string: String,
    pstat_string: String,
    lvorm_string: String,
    mtart_string: String,
    mbrsh_string: String,
    matkl_string: String,
    bismt_string: String,
    meins_string: String,
    bstme_string: String,
    zeinr_string: String,
    zeiar_string: String,
    zeivr_string: String,
    zeifo_string: String,
    aeszn_string: String,
    blatt_string: String,
    blanz_string: String,
    ferth_string: String,
    formt_string: String,
    groes_string: String,
    wrkst_string: String,
    normt_string: String,
    labor_string: String,
    ekwsl_string: String,
    @Decimal(13, 3) brgew_decimal_13_3: BigDecimal,
    @Decimal(13, 3) ntgew_decimal_13_3: BigDecimal,
    gewei_string: String,
    @Decimal(13, 3) volum_decimal_13_3: BigDecimal,
    voleh_string: String,
    behvo_string: String,
    raube_string: String,
    tempb_string: String,
    disst_string: String,
    tragr_string: String,
    stoff_string: String,
    spart_string: String,
    kunnr_string: String,
    eannr_string: String,
    @Decimal(13, 3) wesch_decimal_13_3: BigDecimal,
    bwvor_string: String,
    bwscl_string: String,
    saiso_string: String,
    etiar_string: String,
    etifo_string: String,
    entar_string: String,
    ean11_string: String,
    numtp_string: String,
    @Decimal(13, 3) laeng_decimal_13_3: BigDecimal,
    @Decimal(13, 3) breit_decimal_13_3: BigDecimal,
    @Decimal(13, 3) hoehe_decimal_13_3: BigDecimal,
    meabm_string: String,
    prdha_string: String,
    aeklk_string: String,
    cadkz_string: String,
    qmpur_string: String,
    @Decimal(13, 3) ergew_decimal_13_3: BigDecimal,
    ergei_string: String,
    @Decimal(13, 3) ervol_decimal_13_3: BigDecimal,
    ervoe_string: String,
    @Decimal(3, 1) gewto_decimal_3_1: BigDecimal,
    @Decimal(3, 1) volto_decimal_3_1: BigDecimal,
    vabme_string: String,
    kzrev_string: String,
    kzkfg_string: String,
    xchpf_string: String,
    vhart_string: String,
    @Decimal(3, 0) fuelg_decimal_3_0: BigDecimal,
    stfak_int: BoxedInt,
    magrv_string: String,
    begru_string: String,
    datab_string: String,
    liqdt_string: String,
    saisj_string: String,
    plgtp_string: String,
    mlgut_string: String,
    extwg_string: String,
    satnr_string: String,
    attyp_string: String,
    kzkup_string: String,
    kznfm_string: String,
    pmata_string: String,
    mstae_string: String,
    mstav_string: String,
    mstde_string: String,
    mstdv_string: String,
    taklv_string: String,
    rbnrm_string: String,
    @Decimal(4, 0) mhdrz_decimal_4_0: BigDecimal,
    @Decimal(4, 0) mhdhb_decimal_4_0: BigDecimal,
    @Decimal(3, 0) mhdlp_decimal_3_0: BigDecimal,
    inhme_string: String,
    @Decimal(13, 3) inhal_decimal_13_3: BigDecimal,
    @Decimal(5, 0) vpreh_decimal_5_0: BigDecimal,
    etiag_string: String,
    @Decimal(13, 3) inhbr_decimal_13_3: BigDecimal,
    cmeth_string: String,
    cuobf_string: String,
    kzumw_string: String,
    kosch_string: String,
    sprof_string: String,
    nrfhg_string: String,
    mfrpn_string: String,
    mfrnr_string: String,
    bmatn_string: String,
    mprof_string: String,
    kzwsm_string: String,
    saity_string: String,
    profl_string: String,
    ihivi_string: String,
    iloos_string: String,
    serlv_string: String,
    kzgvh_string: String,
    xgchp_string: String,
    kzeff_string: String,
    compl_string: String,
    iprkz_string: String,
    rdmhd_string: String,
    przus_string: String,
    mtpos_mara_string: String,
    bflme_string: String,
    matfi_string: String,
    cmrel_string: String,
    bbtyp_string: String,
    sled_bbd_string: String,
    gtin_variant_string: String,
    gennr_string: String,
    rmatp_string: String,
    gds_relevant_string: String,
    weora_string: String,
    hutyp_dflt_string: String,
    pilferable_string: String,
    whstc_string: String,
    whmatgr_string: String,
    hndlcode_string: String,
    hazmat_string: String,
    hutyp_string: String,
    tare_var_string: String,
    @Decimal(15, 3) maxc_decimal_15_3: BigDecimal,
    @Decimal(3, 1) maxc_tol_decimal_3_1: BigDecimal,
    @Decimal(15, 3) maxl_decimal_15_3: BigDecimal,
    @Decimal(15, 3) maxb_decimal_15_3: BigDecimal,
    @Decimal(15, 3) maxh_decimal_15_3: BigDecimal,
    maxdim_uom_string: String,
    herkl_string: String,
    mfrgr_string: String,
    @Decimal(3, 0) qqtime_decimal_3_0: BigDecimal,
    qqtimeuom_string: String,
    qgrp_string: String,
    serial_string: String,
    ps_smartform_string: String,
    logunit_string: String,
    cwqrel_string: String,
    cwqproc_string: String,
    cwqtolgr_string: String,
    adprof_string: String,
    ipmipproduct_string: String,
    allow_pmat_igno_string: String,
    medium_string: String,
    commodity_string: String,
    animal_origin_string: String,
    textile_comp_ind_string: String,
    sgt_csgr_string: String,
    sgt_covsa_string: String,
    sgt_stat_string: String,
    sgt_scope_string: String,
    sgt_rel_string: String,
    fsh_mg_at1_string: String,
    fsh_mg_at2_string: String,
    fsh_mg_at3_string: String,
    fsh_sealv_string: String,
    fsh_seaim_string: String,
    fsh_sc_mid_string: String,
    anp_string: String,
    psm_code_string: String,
    _bev1_luleinh_string: String,
    _bev1_luldegrp_string: String,
    _bev1_nestruccat_string: String,
    _dsd_sl_toltyp_string: String,
    _dsd_sv_cnt_grp_string: String,
    _dsd_vc_group_string: String,
    @Decimal(7, 2) _sapmp_kadu_decimal_7_2: BigDecimal,
    _sapmp_abmein_string: String,
    @Decimal(5, 2) _sapmp_kadp_decimal_5_2: BigDecimal,
    @Decimal(4, 0) _sapmp_brad_decimal_4_0: BigDecimal,
    @Decimal(7, 2) _sapmp_spbi_decimal_7_2: BigDecimal,
    @Decimal(7, 2) _sapmp_trad_decimal_7_2: BigDecimal,
    @Decimal(7, 2) _sapmp_kedu_decimal_7_2: BigDecimal,
    @Decimal(13, 3) _sapmp_sptr_decimal_13_3: BigDecimal,
    @Decimal(7, 2) _sapmp_fbdk_decimal_7_2: BigDecimal,
    @Decimal(7, 2) _sapmp_fbhk_decimal_7_2: BigDecimal,
    _sapmp_rili_string: String,
    _sapmp_fbak_string: String,
    _sapmp_aho_string: String,
    @Decimal(7, 2) _sapmp_mifrr_decimal_7_2: BigDecimal,
    _vso_r_tilt_ind_string: String,
    _vso_r_stack_ind_string: String,
    _vso_r_bot_ind_string: String,
    _vso_r_top_ind_string: String,
    _vso_r_stack_no_string: String,
    _vso_r_pal_ind_string: String,
    @Decimal(13, 3) _vso_r_pal_ovr_d_decimal_13_3: BigDecimal,
    @Decimal(13, 3) _vso_r_pal_ovr_w_decimal_13_3: BigDecimal,
    @Decimal(13, 3) _vso_r_pal_b_ht_decimal_13_3: BigDecimal,
    @Decimal(13, 3) _vso_r_pal_min_h_decimal_13_3: BigDecimal,
    @Decimal(13, 3) _vso_r_tol_b_ht_decimal_13_3: BigDecimal,
    _vso_r_no_p_gvh_string: String,
    _vso_r_quan_unit_string: String,
    _vso_r_kzgvh_ind_string: String,
    packcode_string: String,
    dg_pack_status_string: String,
    mcond_string: String,
    retdelc_string: String,
    loglev_reto_string: String,
    nsnid_string: String,
    ovlpn_string: String,
    adspc_spc_string: String,
    varid_binary: Array[Byte],
    msbookpartno_string: String,
    vtype_string: String,
    vchnr_string: String,
    evval_string: String,
    dvers_string: String,
    dpcbt_string: String,
    xgrdt_string: String,
    imatn_string: String,
    picnum_string: String,
    bstat_string: String,
    color_atinn_string: String,
    size1_atinn_string: String,
    size2_atinn_string: String,
    color_string: String,
    size1_string: String,
    size2_string: String,
    free_char_string: String,
    care_code_string: String,
    brand_id_string: String,
    fiber_code1_string: String
) extends Entity

@LakehouseEntity
case class mara_E_part2(
    @PK _mk_org: String,
    fiber_part1_string: String,
    fiber_code2_string: String,
    fiber_part2_string: String,
    fiber_code3_string: String,
    fiber_part3_string: String,
    fiber_code4_string: String,
    fiber_part4_string: String,
    fiber_code5_string: String,
    fiber_part5_string: String,
    fashgrd_string: String,
    zkerdat_string: String,
    zkerzet_string: String,
    zkfreig1_string: String,
    zkrefer_string: String,
    zzgold_matnr_string: String,
    zzgold_maktx_string: String,
    zzgold_sysid_string: String,
    zzgold_mandt_string: String
) extends Entity

object mara
    extends TableSpec[Joined[mara_E_part1, mara_E_part2]](
      enableChangeDataFeed = true,
      manualClusterBy = None,
      timetravelDays = 35
    )
    with Loaded
