package ct.dna.lakehouse.sr_raw.ct_gbl_p85
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec

@LakehouseEntity
case class marc_E_part1(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt_string: String,
    matnr_string: String,
    werks_string: String,
    pstat_string: String,
    lvorm_string: String,
    bwtty_string: String,
    xchar_string: String,
    mmsta_string: String,
    mmstd_string: String,
    maabc_string: String,
    kzkri_string: String,
    ekgrp_string: String,
    ausme_string: String,
    dispr_string: String,
    dismm_string: String,
    dispo_string: String,
    kzdie_string: String,
    @Decimal(3, 0) plifz_decimal_3_0: BigDecimal,
    @Decimal(3, 0) webaz_decimal_3_0: BigDecimal,
    perkz_string: String,
    @Decimal(5, 2) ausss_decimal_5_2: BigDecimal,
    disls_string: String,
    beskz_string: String,
    sobsl_string: String,
    @Decimal(13, 3) minbe_decimal_13_3: BigDecimal,
    @Decimal(13, 3) eisbe_decimal_13_3: BigDecimal,
    @Decimal(13, 3) bstmi_decimal_13_3: BigDecimal,
    @Decimal(13, 3) bstma_decimal_13_3: BigDecimal,
    @Decimal(13, 3) bstfe_decimal_13_3: BigDecimal,
    @Decimal(13, 3) bstrf_decimal_13_3: BigDecimal,
    @Decimal(13, 3) mabst_decimal_13_3: BigDecimal,
    @Decimal(11, 2) losfx_decimal_11_2: BigDecimal,
    sbdkz_string: String,
    lagpr_string: String,
    altsl_string: String,
    kzaus_string: String,
    ausdt_string: String,
    nfmat_string: String,
    kzbed_string: String,
    miskz_string: String,
    fhori_string: String,
    pfrei_string: String,
    ffrei_string: String,
    rgekz_string: String,
    fevor_string: String,
    @Decimal(5, 2) bearz_decimal_5_2: BigDecimal,
    @Decimal(5, 2) ruezt_decimal_5_2: BigDecimal,
    @Decimal(5, 2) tranz_decimal_5_2: BigDecimal,
    @Decimal(13, 3) basmg_decimal_13_3: BigDecimal,
    @Decimal(3, 0) dzeit_decimal_3_0: BigDecimal,
    @Decimal(5, 0) maxlz_decimal_5_0: BigDecimal,
    lzeih_string: String,
    kzpro_string: String,
    gpmkz_string: String,
    @Decimal(3, 1) ueeto_decimal_3_1: BigDecimal,
    ueetk_string: String,
    @Decimal(3, 1) uneto_decimal_3_1: BigDecimal,
    @Decimal(3, 0) wzeit_decimal_3_0: BigDecimal,
    atpkz_string: String,
    @Decimal(5, 2) vzusl_decimal_5_2: BigDecimal,
    herbl_string: String,
    insmk_string: String,
    @Decimal(3, 1) sproz_decimal_3_1: BigDecimal,
    @Decimal(3, 0) quazt_decimal_3_0: BigDecimal,
    ssqss_string: String,
    @Decimal(5, 0) mpdau_decimal_5_0: BigDecimal,
    kzppv_string: String,
    kzdkz_string: String,
    @Decimal(9, 0) wstgh_decimal_9_0: BigDecimal,
    @Decimal(5, 0) prfrq_decimal_5_0: BigDecimal,
    nkmpr_string: String,
    @Decimal(13, 3) umlmc_decimal_13_3: BigDecimal,
    ladgr_string: String,
    xchpf_string: String,
    usequ_string: String,
    @Decimal(3, 1) lgrad_decimal_3_1: BigDecimal,
    auftl_string: String,
    plvar_string: String,
    otype_string: String,
    objid_string: String,
    mtvfp_string: String,
    periv_string: String,
    kzkfk_string: String,
    @Decimal(5, 2) vrvez_decimal_5_2: BigDecimal,
    @Decimal(13, 3) vbamg_decimal_13_3: BigDecimal,
    @Decimal(5, 2) vbeaz_decimal_5_2: BigDecimal,
    lizyk_string: String,
    bwscl_string: String,
    kautb_string: String,
    kordb_string: String,
    stawn_string: String,
    herkl_string: String,
    herkr_string: String,
    expme_string: String,
    mtver_string: String,
    prctr_string: String,
    @Decimal(13, 3) trame_decimal_13_3: BigDecimal,
    mrppp_string: String,
    sauft_string: String,
    fxhor_string: String,
    vrmod_string: String,
    vint1_string: String,
    vint2_string: String,
    verkz_string: String,
    stlal_string: String,
    stlan_string: String,
    plnnr_string: String,
    aplal_string: String,
    @Decimal(13, 3) losgr_decimal_13_3: BigDecimal,
    sobsk_string: String,
    frtme_string: String,
    lgpro_string: String,
    disgr_string: String,
    @Decimal(5, 2) kausf_decimal_5_2: BigDecimal,
    qzgtp_string: String,
    qmatv_string: String,
    @Decimal(3, 0) takzt_decimal_3_0: BigDecimal,
    rwpro_string: String,
    copam_string: String,
    abcin_string: String,
    awsls_string: String,
    sernp_string: String,
    cuobj_string: String,
    stdpd_string: String,
    sfepr_string: String,
    xmcng_string: String,
    qssys_string: String,
    lfrhy_string: String,
    rdprf_string: String,
    vrbmt_string: String,
    vrbwk_string: String,
    vrbdt_string: String,
    @Decimal(4, 2) vrbfk_decimal_4_2: BigDecimal,
    autru_string: String,
    prefe_string: String,
    prenc_string: String,
    preno_string: String,
    prend_string: String,
    prene_string: String,
    preng_string: String,
    itark_string: String,
    servg_string: String,
    kzkup_string: String,
    strgr_string: String,
    cuobv_string: String,
    lgfsb_string: String,
    schgt_string: String,
    ccfix_string: String,
    eprio_string: String,
    qmata_string: String,
    @Decimal(3, 0) resvp_decimal_3_0: BigDecimal,
    plnty_string: String,
    uomgr_string: String,
    umrsl_string: String,
    @Decimal(2, 1) abfac_decimal_2_1: BigDecimal,
    sfcpf_string: String,
    shflg_string: String,
    shzet_string: String,
    mdach_string: String,
    kzech_string: String,
    megru_string: String,
    mfrgr_string: String,
    profil_string: String,
    vers_cseg_string: String,
    vers_active_string: String,
    @Decimal(13, 2) vkumc_decimal_13_2: BigDecimal,
    @Decimal(13, 2) vktrw_decimal_13_2: BigDecimal,
    kzagl_string: String,
    fvidk_string: String,
    fxpru_string: String,
    loggr_string: String,
    fprfm_string: String,
    @Decimal(13, 3) glgmg_decimal_13_3: BigDecimal,
    @Decimal(13, 2) vkglg_decimal_13_2: BigDecimal,
    indus_string: String,
    mownr_string: String,
    mogru_string: String,
    casnr_string: String,
    gpnum_string: String,
    steuc_string: String,
    fabkz_string: String,
    matgr_string: String,
    vspvb_string: String,
    dplfs_string: String,
    dplpu_string: String,
    @Decimal(3, 0) dplho_decimal_3_0: BigDecimal,
    @Decimal(13, 3) minls_decimal_13_3: BigDecimal,
    @Decimal(13, 3) maxls_decimal_13_3: BigDecimal,
    @Decimal(13, 3) fixls_decimal_13_3: BigDecimal,
    @Decimal(13, 3) ltinc_decimal_13_3: BigDecimal,
    compl_string: String,
    convt_string: String,
    shpro_string: String,
    ahdis_string: String,
    diber_string: String,
    kzpsp_string: String,
    ocmpf_string: String,
    apokz_string: String,
    mcrue_string: String,
    lfmon_string: String,
    lfgja_string: String,
    @Decimal(13, 3) eislo_decimal_13_3: BigDecimal,
    ncost_string: String,
    rotation_date_string: String,
    uchkz_string: String,
    ucmat_string: String,
    @Decimal(13, 3) bwesb_decimal_13_3: BigDecimal,
    sgt_covs_string: String,
    sgt_statc_string: String,
    sgt_scope_string: String,
    sgt_mrpsi_string: String,
    sgt_prcm_string: String,
    sgt_chint_string: String,
    sgt_stk_prt_string: String,
    sgt_defsc_string: String,
    sgt_mrp_atp_status_string: String,
    sgt_mmstd_string: String,
    fsh_mg_arun_req_string: String,
    fsh_seaim_string: String,
    fsh_var_group_string: String,
    fsh_kzech_string: String,
    fsh_calendar_group_string: String,
    ppskz_string: String,
    pps_strategy_string: String,
    pps_planning_type_string: String,
    pps_heur_id_string: String,
    pps_fixpeg_string: String,
    pps_peg_strategy_string: String,
    @Decimal(11, 0) pps_grprt_decimal_11_0: BigDecimal,
    @Decimal(11, 0) pps_giprt_decimal_11_0: BigDecimal,
    @Decimal(13, 3) pps_conhap_decimal_13_3: BigDecimal,
    pps_hunit_string: String,
    @Decimal(13, 3) pps_conhap_out_decimal_13_3: BigDecimal,
    pps_hunit_out_string: String,
    pps_atpcheck_string: String,
    @Decimal(11, 0) pps_peg_fut_al_decimal_11_0: BigDecimal,
    @Decimal(11, 0) pps_peg_past_al_decimal_11_0: BigDecimal,
    nf_flag_string: String,
    @Decimal(3, 1) _sapmp_tolprpl_decimal_3_1: BigDecimal,
    @Decimal(3, 1) _sapmp_tolprmi_decimal_3_1: BigDecimal,
    _vso_r_pkgrp_string: String,
    _vso_r_lane_num_string: String
) extends Entity

@LakehouseEntity
case class marc_E_part2(
    @PK _mk_org: String,
    _vso_r_pal_vend_string: String,
    _vso_r_fork_dir_string: String,
    iuid_relevant_string: String,
    iuid_type_string: String,
    uid_iea_string: String,
    dpcbt_string: String,
    cons_procg_string: String,
    @Decimal(3, 0) gi_pr_time_decimal_3_0: BigDecimal,
    multiple_ekgrp_string: String,
    ref_schema_string: String,
    min_troc_string: String,
    max_troc_string: String,
    @Decimal(13, 3) target_stock_decimal_13_3: BigDecimal,
    zzplantref_string: String,
    zzccref_string: String,
    @Decimal(13, 6) zzqcf_decimal_13_6: BigDecimal,
    zzeudr_string: String
) extends Entity

object marc
    extends TableSpec[Joined[marc_E_part1, marc_E_part2]](
      enableChangeDataFeed = true,
      manualClusterBy = None,
      timetravelDays = 35
    )
    with Loaded
