// LOADED TABLE SPEC AUTO GENERATED:START
// Generated by LoadedTableSpecAstBuilder - DO NOT EDIT MANUALLY
package ct.dna.lakehouse.sr_raw.ct_gbl_p85

import ct.dna.lakehouse.core.model.ClusterBy
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.Loaded
import ct.dna.lakehouse.core.model.TableSpec

case class E_msku(
    @PK _mk_org: String,
    @PK _mk_site: String,
    @PK _mk_system: String,
    @PK _mk_instance: String,
    @PK _mk_partition: String,
    @PK _mk_file: String,
    @NotNull _mk_container: String,
    @NotNull _mk_account: String,
    @NotNull _mk_created_at: Timestamp,
    @PK _lh_id_in_message: Long,
    _lh_ingest_warning: String,
    mandt_string: String,
    matnr_string: String,
    werks_string: String,
    charg_string: String,
    sobkz_string: String,
    kunnr_string: String,
    lfgja_string: String,
    lfmon_string: String,
    kuspr_string: String,
    @Decimal(13, 3) kulab_decimal_13_3: BigDecimal,
    @Decimal(13, 3) kuins_decimal_13_3: BigDecimal,
    @Decimal(13, 3) kuvla_decimal_13_3: BigDecimal,
    @Decimal(13, 3) kuvin_decimal_13_3: BigDecimal,
    kuill_string: String,
    kuilq_string: String,
    kuvll_string: String,
    kuvlq_string: String,
    kufll_string: String,
    kuflq_string: String,
    kudll_string: String,
    @Decimal(13, 3) kuein_decimal_13_3: BigDecimal,
    @Decimal(13, 3) kuvei_decimal_13_3: BigDecimal,
    ersda_string: String,
    kujin_string: String,
    kurue_string: String,
    @Decimal(13, 3) kuuml_decimal_13_3: BigDecimal,
    sgt_scat_string: String,
    fsh_season_year_string: String,
    fsh_season_string: String,
    fsh_collection_string: String,
    fsh_theme_string: String,
    @Decimal(13, 3) fsh_salloc_qty_decimal_13_3: BigDecimal
) extends Entity

object msku
    extends TableSpec[E_msku](
      enableChangeDataFeed = true,
      clusterBy = ClusterBy.Columns("_mk_instance", "_mk_partition", "_mk_file"),
      timetravelDays = 35
    )
    with Loaded
// LOADED TABLE SPEC AUTO GENERATED:END

// COLUMN ACCESSOR AUTO GENERATED:START
// Generated by ColumnWithNameAccessorEmbeddedAstBuilder - DO NOT EDIT MANUALLY
import ct.dna.lakehouse.core.model.ColumnWithName
import ct.dna.lakehouse.core.model.ColumnWithNameAccessor

sealed class C_msku(prefix: String) extends ColumnWithNameAccessor {
  val _mk_org: ColumnWithName = ColumnWithName(prefix + "_mk_org")
  val _mk_site: ColumnWithName = ColumnWithName(prefix + "_mk_site")
  val _mk_system: ColumnWithName = ColumnWithName(prefix + "_mk_system")
  val _mk_instance: ColumnWithName = ColumnWithName(prefix + "_mk_instance")
  val _mk_partition: ColumnWithName = ColumnWithName(prefix + "_mk_partition")
  val _mk_file: ColumnWithName = ColumnWithName(prefix + "_mk_file")
  val _mk_container: ColumnWithName = ColumnWithName(prefix + "_mk_container")
  val _mk_account: ColumnWithName = ColumnWithName(prefix + "_mk_account")
  val _mk_created_at: ColumnWithName = ColumnWithName(prefix + "_mk_created_at")
  val _lh_id_in_message: ColumnWithName = ColumnWithName(prefix + "_lh_id_in_message")
  val _lh_ingest_warning: ColumnWithName = ColumnWithName(prefix + "_lh_ingest_warning")
  val mandt_string: ColumnWithName = ColumnWithName(prefix + "mandt_string")
  val matnr_string: ColumnWithName = ColumnWithName(prefix + "matnr_string")
  val werks_string: ColumnWithName = ColumnWithName(prefix + "werks_string")
  val charg_string: ColumnWithName = ColumnWithName(prefix + "charg_string")
  val sobkz_string: ColumnWithName = ColumnWithName(prefix + "sobkz_string")
  val kunnr_string: ColumnWithName = ColumnWithName(prefix + "kunnr_string")
  val lfgja_string: ColumnWithName = ColumnWithName(prefix + "lfgja_string")
  val lfmon_string: ColumnWithName = ColumnWithName(prefix + "lfmon_string")
  val kuspr_string: ColumnWithName = ColumnWithName(prefix + "kuspr_string")
  val kulab_decimal_13_3: ColumnWithName = ColumnWithName(prefix + "kulab_decimal_13_3")
  val kuins_decimal_13_3: ColumnWithName = ColumnWithName(prefix + "kuins_decimal_13_3")
  val kuvla_decimal_13_3: ColumnWithName = ColumnWithName(prefix + "kuvla_decimal_13_3")
  val kuvin_decimal_13_3: ColumnWithName = ColumnWithName(prefix + "kuvin_decimal_13_3")
  val kuill_string: ColumnWithName = ColumnWithName(prefix + "kuill_string")
  val kuilq_string: ColumnWithName = ColumnWithName(prefix + "kuilq_string")
  val kuvll_string: ColumnWithName = ColumnWithName(prefix + "kuvll_string")
  val kuvlq_string: ColumnWithName = ColumnWithName(prefix + "kuvlq_string")
  val kufll_string: ColumnWithName = ColumnWithName(prefix + "kufll_string")
  val kuflq_string: ColumnWithName = ColumnWithName(prefix + "kuflq_string")
  val kudll_string: ColumnWithName = ColumnWithName(prefix + "kudll_string")
  val kuein_decimal_13_3: ColumnWithName = ColumnWithName(prefix + "kuein_decimal_13_3")
  val kuvei_decimal_13_3: ColumnWithName = ColumnWithName(prefix + "kuvei_decimal_13_3")
  val ersda_string: ColumnWithName = ColumnWithName(prefix + "ersda_string")
  val kujin_string: ColumnWithName = ColumnWithName(prefix + "kujin_string")
  val kurue_string: ColumnWithName = ColumnWithName(prefix + "kurue_string")
  val kuuml_decimal_13_3: ColumnWithName = ColumnWithName(prefix + "kuuml_decimal_13_3")
  val sgt_scat_string: ColumnWithName = ColumnWithName(prefix + "sgt_scat_string")
  val fsh_season_year_string: ColumnWithName = ColumnWithName(prefix + "fsh_season_year_string")
  val fsh_season_string: ColumnWithName = ColumnWithName(prefix + "fsh_season_string")
  val fsh_collection_string: ColumnWithName = ColumnWithName(prefix + "fsh_collection_string")
  val fsh_theme_string: ColumnWithName = ColumnWithName(prefix + "fsh_theme_string")
  val fsh_salloc_qty_decimal_13_3: ColumnWithName = ColumnWithName(prefix + "fsh_salloc_qty_decimal_13_3")
}

object C_msku extends C_msku("") {
  def as(alias: String): C_msku = new C_msku(alias + ".")
}
// COLUMN ACCESSOR AUTO GENERATED:END
