package ct.dna.lakehouse.sr_raw.ct_gbl_p85
import ct.dna.lakehouse.core.framework.origin.Loaded
import ct.dna.lakehouse.core.model.Entity
import ct.dna.lakehouse.core.model.Entity._
import ct.dna.lakehouse.core.model.TableSpec


@LakehouseEntity
case class mvke_E(
  @PK _mk_org: String,
  @PK _mk_site: String,
  @PK _mk_system: String,
  @PK _mk_instance: String,
  @PK _mk_partition: String,
  @PK _mk_file: String,
  @NotNull _mk_container: String,
  @NotNull _mk_account: String,
  @NotNull _mk_created_at: Timestamp,
  @PK _lh_id_in_message: Long,
  _lh_ingest_warning: String,
  prat7_string: String,
  bonus_string: String,
  vkorg_string: String,
  prat1_string: String,
  matnr_string: String,
  pvmso_string: String,
  versg_string: String,
  _bev1_rpbezme_string: String,
  @Decimal(13, 3) scmng_decimal_13_3: BigDecimal,
  lstvz_string: String,
  _bev1_rpsfa_string: String,
  provg_string: String,
  mvgr2_string: String,
  prat5_string: String,
  mvgr3_string: String,
  mtpos_string: String,
  prat4_string: String,
  rdprf_string: String,
  @Decimal(13, 3) efmng_decimal_13_3: BigDecimal,
  lstak_string: String,
  _bev1_emdrckspl_string: String,
  @Decimal(13, 3) aumng_decimal_13_3: BigDecimal,
  prodh_string: String,
  ldbfl_string: String,
  pmatn_string: String,
  prat6_string: String,
  mvgr5_string: String,
  vtweg_string: String,
  sktof_string: String,
  vavme_string: String,
  prat8_string: String,
  prata_string: String,
  mandt_string: String,
  vmstd_string: String,
  kondm_string: String,
  prat2_string: String,
  dwerk_string: String,
  vdvfl_string: String,
  ldvfl_string: String,
  mvgr4_string: String,
  prat3_string: String,
  nf_flag_string: String,
  vdvzl_string: String,
  lstfl_string: String,
  matkc_string: String,
  _bev1_rpsns_string: String,
  megru_string: String,
  ldbzl_string: String,
  vdbfl_string: String,
  ldvzl_string: String,
  ktgrm_string: String,
  prat9_string: String,
  mvgr1_string: String,
  _bev1_rpsco_string: String,
  sstuf_string: String,
  rjart_string: String,
  vdbzl_string: String,
  @Decimal(13, 3) lfmng_decimal_13_3: BigDecimal,
  _bev1_emlgrp_string: String,
  pflks_string: String,
  pbind_string: String,
  vmsta_string: String,
  lvorm_string: String,
  _bev1_rpsso_string: String,
  @Decimal(13, 3) lfmax_decimal_13_3: BigDecimal,
  _bev1_rpski_string: String,
  vrkme_string: String,
  schme_string: String,
  plgtp_string: String
) extends Entity

object mvke extends TableSpec[mvke_E](
  enableChangeDataFeed = true,
  manualClusterBy = None,
  timetravelDays = 35
) with Loaded
